### ISSUE TITLE
Docs: Note about Function Templates

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#100]
People are going to want to bind function templates and will get all super confused when they can't. While we could tell them to go Read A Fucking Book, we can't expect everyone to know about it. So, might as well drop something in the docs.

**Comment by nabijaczleweli** [comment]
> We can't expect everyone to know the most basic of C++'s mechanics

**Comment by ThePhD** [comment]
Function templates and their interplay with compilation is not something every person trying to make a quick game do know perfectly, no, and it gives me a place to forward people so I can close future issues about it quicker.
