### ISSUE TITLE
warning C4800 emitted by VS2019 when using sol::readonly inside new_usertype call

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#1000]
After upgrading from VS2017 to latest VS2019, the compiler now emits warning C4800 with the latest sol code: 

```cpp
struct Foo
{
	static void Register(sol::table &table)
	{
		table.new_usertype<Foo>("Foo", "id", sol::readonly(&Foo::foo));
	}
	int foo;
};
```
Compiling as Debug 64-bit. Result:

```
1>sol2\single\include\sol\sol.hpp(10713,1): warning C4800: Implicit conversion from 'T' to bool. Possible information loss
1>        with
1>        [
1>            T=int Foo::*
1>        ]
```
...with a very long cascading tail, of course.

**Comment by ThePhD** [comment]
That's a bit of a concerning warning, actually...!

Lemme dig into it.

**Comment by ThePhD** [comment]
I can't reproduce this error on latest VS2019 or VS2019 Preview anymore with /W4 and all that on. I think this one might've been fixed...!

... Somewhere. Somehow?

**Comment by sagamusix** [comment]
Pasted the same code into a new project and for some reason it doesn't trigger the warning there, although the compiler command lines are pretty much the same (modulo stuff that shouldn't matter). Still investigating.

**Comment by sagamusix** [comment]
Okay, that was simple: warning C4800 is not standard with /W4. Just add the following to the snippet and it will warn:
```
#pragma warning(default:4800)
```

**Comment by sagamusix** [comment]
@ThePhD could you reopen this issue based on my previous comment? Apparently I cannot do so.

**Comment by ThePhD** [comment]
This should totes be fixed I promise no really I swear pinky promise cross my heart hope to die stick a needle in my eye.

**Comment by sagamusix** [comment]
Fix confirmed, thanks!
