### ISSUE TITLE
Unpack usertype in LuaJIT

### ISSUE THREAD

**Issue by espkk** [ThePhD/sol2#1002]
I have a function that returns sol::lua_value which is either sol::nil or std::vector<std::strings>
Lua 5.3 was able to unpack the return from the function. After switching to LuaJIT it throws '**bad argument #1 to 'unpack' (table expected, got userdata)**' (yep, I know luajit is always a pain but it is the best lua has)

The question is, can I get this working without modifying the form of returned values/copying returns to the table?
Maybe there is a close alternative or some workaround?

**Comment by espkk** [comment]
Whoops. simply sol::as_table made the thing working. not sure if this is the best solution, but it is good enough

**Comment by ThePhD** [comment]
https://sol2.readthedocs.io/en/latest/containers.html#a-complete-example

> Note that this will not work well in Lua 5.1, as it has explicit table checks and does not check metamethods, even when pairs or ipairs is passed a table. In that case, you will need to use a more manual iteration scheme or you will have to convert it to a table. In C++, you can use sol::as_table when passing something to the library to get a table out of it: lua["arr"] = as_table( std::vector<int>{ ... });. ...
