### ISSUE TITLE
Duplicate dtor call for usertypes

### ISSUE THREAD

**Issue by doubleday** [ThePhD/sol2#1009]
Howdi - 

while writing some tests to understand how sol and gc plays with memory management I ran into an issue where the dtor of my usertype was called twice.

I digged into sols unit tests and found a test that was doing pretty much the same and seems to expect the duplicate dtor call unless I'm getting it totally wrong (likely).

In https://github.com/ThePhD/sol2/blob/develop/tests/runtime_tests/source/gc.cpp#L53 

with

```cpp
	struct test;
	static std::vector<test*> tests_destroyed;
	struct test {
		int v = 10;
		~test() {
			tests_destroyed.push_back(this);
		}
	};
	test t;
	test* pt = nullptr;
	{
		sol::state lua;

		lua["t"] = test{};
		pt = lua["t"];
	}
```

you are expecting:

```cpp
	REQUIRE(tests_destroyed.size() == 2);
```

and this is indeed what's happening. But I don't know why...

I count 2 objects:

```cpp
	test t;
	lua["t"] = test{};
```

but `t` is still in scope... so at that point I would expect only 1 dtor call.

I added some more debugging code here:

https://github.com/doubleday/sol2/commit/e48d717a1cb8328b51fa57d1470f2107487dc2d9

and get this exception:

```
.../gc.cpp:47: FAILED:
  REQUIRE( std::find(tests_constructed.begin(), tests_constructed.end(), this) != tests_constructed.end() )
with expansion:
  {?} != {?}
```

But as I said maybe I'm just missing something?

**Comment by Rochet2** [comment]
```cpp
lua["t"] = test{};
```
On this line either a move or a copy occurs.
From what I understand, in both cases a destructor is called for the original object created with `test{}`.
The same can be seen here: https://godbolt.org/z/6TPEME

The curly brackets cause the lua state to be closed and as a result any objects in it are freed.
We just copied or moved an object into lua, so that is freed. As a result we have two destructions.
```cpp
{
    sol::state lua;
    lua["t"] = test{};
    pt = lua["t"];
}
```

**Comment by ThePhD** [comment]
`test{}` produces a temporary, which after being moved/coped into the Lua VM by sol2 dies. This happens purely on the C++ side.

`sol::state`'s destructor is run. This destroys the `test` moved into the Lua VM as the entire `sol::state` is destroyed.

The counts are correct. `test t;` should not destroy by the time that `REQUIRE`s is hit. If you wrapped another `{ ... }` around where `test t;` was, the expected answer would be `4` at that point, which might be helpful in understanding the nature of the temporaries.

**Comment by doubleday** [comment]
But how do you explain the exception that I get?

```cpp
		test() {
			tests_constructed.push_back(this);
			std::cout << " test ctor " << reinterpret_cast<uintptr_t>(this) << std::endl;
		}
		~test() {
			std::cout << " test dtor " << reinterpret_cast<uintptr_t>(this) << std::endl;
			tests_destroyed.push_back(this);
		}
```

prints:

```
 test ctor 140732754741944
 test ctor 140732754741872
 test dtor 140732754741872
 test dtor 140569394298176
```

**Comment by doubleday** [comment]
This test:

```c++
TEST_CASE("gc/destructors", "test if destructors are fired properly through gc of unbound usertypes") {
    struct test;
    struct test {
        int v = 10;
        test() {
            std::cout << "test ctor \n";
        }
        ~test() {
            std::cout << "test dtor \n";
        }
    };
    test* pt = nullptr;
    {
        sol::state lua;

        lua["t"] = test{};
        pt = lua["t"];
    }
}
```

does print

```
test ctor 
test dtor 
test dtor 
```

**Comment by doubleday** [comment]
Ok - I'm an idiot. Thanks
