### ISSUE TITLE
Should `SOL_USING_CXX_LUA` imply `SOL_NO_LUA_HPP`?

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#1013]
The documentation says:

> SOL_USING_CXX_LUA triggers the following changes:
> - Lua includes are no longer wrapped in extern "C" {} blocks
> - ...

Obviously the goal of this symbol is to inform sol that Lua has been compiled as C++ code and sol can assume that Lua doesn't use `longjmp`. However, even if you `#define SOL_USING_CXX_LUA 1`, sol will still look for `lua.hpp` by default and use it, unless you *also* specify `#define SOL_NO_LUA_HPP 1`. Since `lua.hpp` wraps the Lua includes in an `extern "C"` block, you are more or less *forced* to define both symbols to 1, which seems counter-intuitive to me. Maybe I miss something obvious here, but shouldn't sol assume that `SOL_NO_LUA_HPP == 1` if `SOL_USING_CXX_LUA == 1`, unless `SOL_NO_LUA_HPP` is manually defined by the user to 0 for whatever reason?

**Comment by ThePhD** [comment]
It's not a switch where you can turn both on: `SOL_USING_CXX_LUA` takes precedence. I have cleaned up some of the configuration code and this should already be the case right now, but I believe it was also the case before anyways, so this is solved (just not well-defined in the manual).

**Comment by ThePhD** [comment]
This is now documented.
