### ISSUE TITLE
"require_DLL_example" not work with lua54.exe interpreter.

### ISSUE THREAD

**Issue by findux** [ThePhD/sol2#1014]
Hi,
I created a dll in msvc by taking the "require_dll_example" as a guide. But when I try to load in lua54.exe interpreter using "mo = require("CAVCON")", it frezing or kill itself.
if I change 41. row as shown, it works. 
->return sol::stack::call_lua(L, 1, CAVCON::open_CAVCON);
to->return 1;
I can't debug dll file somehow. So I can't find the bug properly.
My goal is make dll using existing  c++ library to use in lua interpreter.
Could you help me please.

![image](https://user-images.githubusercontent.com/4825408/90976203-b1655880-e543-11ea-9608-20f946f3a5ec.png)

**Comment by findux** [comment]
After brute force debugging, It seems getting a problem to use "sol::state_view lua(L)"

**Comment by ThePhD** [comment]
Is Lua being built as both a DLL and a static lib in both pieces of code? If I remember correctly, the lua54.exe is generally made as a static library, and mixing a statically built lua with a dll lua is... suspect, at best...?

**Comment by ThePhD** [comment]
To clarify:

- The interpreter, `lua54.exe`, contains one copy of the Lua Virtual Machine code by being built as a standalone executable that does not require `lua54.dll`
- The Lua DLL you are trying to create - with sol2 - either links in its own copy of `lua54.lib` or uses its own DLL, not the one that `lua54.exe` is referencing or the one that it was built with.
- Hilarity ensues.

**Comment by ThePhD** [comment]
I'm going to recommend you get a build of `lua54.exe` that is built against a DLL. You should then build against that DLL, so you can have your own library that dynamically references the Lua code and can use sol2.

That should fix your problem.
