### ISSUE TITLE
Support dynamic function parameter

### ISSUE THREAD

**Issue by manhnt9** [ThePhD/sol2#1015]
**Issue**
The beauty of scripting is posibility of using dynamic type and custom data that aren't always known at compile time.
Currently `sol2` enforces `static_cast` in this function so it fails to compile for functions binding that takes custom user data as parameter (i.e: `void*` to a struct or function pointer of callback):
```cpp

		static T* get_no_lua_nil_from(lua_State* L, void* udata, int index, record&) {
			bool has_derived = derive<T>::value || weak_derive<T>::value;
			if (has_derived) {
				if (lua_getmetatable(L, index) == 1) {
					lua_getfield(L, -1, &detail::base_class_cast_key()[0]);
					if (type_of(L, -1) != type::lua_nil) {
						void* basecastdata = lua_touserdata(L, -1);
						detail::inheritance_cast_function ic = reinterpret_cast<detail::inheritance_cast_function>(basecastdata);
						// use the casting function to properly adjust the pointer for the desired T
						udata = ic(udata, usertype_traits<T>::qualified_name());
					}
					lua_pop(L, 2);
				}
			}
                        T* obj = static_cast<T*>(udata); // line 12496 tag v3.2.1
			return obj;
		}
```

**Proposed solution**
Have a compile switch for unsafe function parameter binding.

**Compiler error**
```
sol.hpp:12496: error: invalid static_cast from type ‘void*’ to type ‘void (*)(ImGuiSizeCallbackData*)’
sol.hpp:12496: error: invalid static_cast from type ‘void*’ to type ‘int (*)(ImGuiInputTextCallbackData*)’
sol.hpp:12496: error: invalid static_cast from type ‘void*’ to type ‘void* (*)(long unsigned int, void*)’
sol.hpp:12496: error: invalid static_cast from type ‘void*’ to type ‘void (*)(void*, void*)’
```
When binding function:
```cpp
struct ImGuiSizeCallbackData
{
    void*   UserData;       // Read-only.   What user passed to SetNextWindowSizeConstraints()
    ImVec2  Pos;            // Read-only.   Window position, for reference.
    ImVec2  CurrentSize;    // Read-only.   Current window size.
    ImVec2  DesiredSize;    // Read-write.  Desired size, based on user's mouse position. Write to this field to restrain resizing.
};

typedef void (*ImGuiSizeCallback)(ImGuiSizeCallbackData* data);

IMGUI_API void SetNextWindowSizeConstraints(const ImVec2& size_min, const ImVec2& size_max, ImGuiSizeCallback custom_callback = NULL, void* custom_callback_data = NULL);
```

**My temporary fix**
```cpp

		static T* get_no_lua_nil_from(lua_State* L, void* udata, int index, record&) {
			bool has_derived = derive<T>::value || weak_derive<T>::value;
			if (has_derived) {
				if (lua_getmetatable(L, index) == 1) {
					lua_getfield(L, -1, &detail::base_class_cast_key()[0]);
					if (type_of(L, -1) != type::lua_nil) {
						void* basecastdata = lua_touserdata(L, -1);
						detail::inheritance_cast_function ic = reinterpret_cast<detail::inheritance_cast_function>(basecastdata);
						// use the casting function to properly adjust the pointer for the desired T
						udata = ic(udata, usertype_traits<T>::qualified_name());
					}
					lua_pop(L, 2);
				}
			}
                        T* obj = (T*)(udata); // using C-style cast
			return obj;
		}
```

**Comment by ThePhD** [comment]
A C cast is inherently unsafe. It performs one of:

- `static_cast`
- `dynamic_cast`
- `reinterpret_cast`

In that order. When you bind a function pointer from C or C++ to Lua, we go through a complicated series of backflips in order to make it a proper callable inside of Lua. This includes performing compile-time heuristics on that function pointer to start. The cast here does not help in the long run: it will (eventually) break on a function pointer that does not have the right properties.

I think the better long-term solution here is to look into a way to allow someone to push a function pointer (already done), and retrieve that function pointer (not yet done). There is likely no way to do this in a completely type-safe manner, so I will probably add the getter/checker and gate it behind `SOL_UNSAFE_FUNCTION_POINTER_RETRIEVAL`. Then your code should work without failure.

Does that sound alright?

**Comment by manhnt9** [comment]
Actually `SOL_UNSAFE_FUNCTION_POINTER_RETRIEVAL` with proper comments on the config is alright too.
It's you who decide!
Thanks.

**Comment by ThePhD** [comment]
This feature is implemented and live. It's dangerous but it works. The macro you need to define on is `SOL_GET_FUNCTION_POINTERS_UNSAFE`.

https://sol2.readthedocs.io/en/latest/safety.html

Thanks for the report!

**Comment by manhnt9** [comment]
Thank you !
I'll try it out.
