### ISSUE TITLE
Building with LuaJIT crashes at state constructor

### ISSUE THREAD

**Issue by manhnt9** [ThePhD/sol2#1019]
### Issue
After building with LuaJIT, the code crashes right at the constructor of state.
```cpp
sol::state lua;
```
![Screenshot_20200826_112224](https://user-images.githubusercontent.com/11463928/91255203-72771300-e78e-11ea-9298-9aeb71db9d26.png)

### Environment
- Ubuntu 20.04
- GCC 9.3
- No Sol config defined, only including sol.hpp
- LuaJIT 2.0.5
- Same LuaJIT build works with sol v2.18.7
- Error in sol v3.2.1

**Comment by ThePhD** [comment]
How is LuaJIT built? From the Ubuntu repositories?

**Comment by manhnt9** [comment]
I download source and run `make` to build LuaJIT.

**Comment by manhnt9** [comment]
Interesting, I retried with Ubuntu's LuaJIT 2.1.0 (installed via APT) and it works.

**Comment by manhnt9** [comment]
Also tried building `LuaJIT-2.1.0-beta3` from source but also crashed with no stack trace in debugger.
LuaJIT 2.1 is still beta. Stable LuaJIT is 2.0.5 currently.
I'm not sure why LuaJIT Ubuntu APT version works.

But Sol v2.18.7 still builds and runs with default LuaJIT build from source.
I think Sol v3 has been added many checks and is a little bit unstable.
I like new features of Sol v3 anyways. Have been upgrading from v2 and having some minor issues so far.

**Comment by manhnt9** [comment]
Closing due to unreliable reports.
Now it works with LuaJIT 2.0.5 built from source.
Maybe before the binary is messed by compiler's cache (cached translation units between rebuilds).
I can't reproduce this issue now.
