### ISSUE TITLE
Using `std::optional` within the same env as `sol::optional`

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#102]
Currently, if using both `std::optional` and `sol::optional` together, it won't compile. 

There's a lot of errors surrounding `nullopt_t` being unknown. 

The solution is to change how sol checks for the optional include: I changed `___OPTIONAL_HPP__` to `___SOL_OPTIONAL_HPP___` and it fixed the import problems.

**Comment by ThePhD** [comment]
Oh woops, I had forgotten about this issue because I viewed it right before going to sleep. ;;

Thanks for the PR, I'll pull that ASAP.

**Comment by Nava2** [comment]
Any chance of getting this back ported into the current release?

**Comment by ThePhD** [comment]
Yeah, sorry. Right now `sol`'s all busted because of the new usertype / function implementation that avoids the use of new / `unique_ptr`. My hope is to stuff all that in one big commit, either today or tomorrow.

**Comment by ThePhD** [comment]
Totally forgot to close this. It's done.
