### ISSUE TITLE
error C2653: 'traits_type': is not a class or namespace name

### ISSUE THREAD

**Issue by TerensTare** [ThePhD/sol2#1020]
- Compiler: Visual Studio 2019 build tools v16.7.2
- Language: C++
- Build System: CMake with Visual Studio 2019 Generator
- Defines: None
- Sol2 version: Latest vcpkg version

I am trying to register some classes to Lua using sol2. This is the first time I get this kind of error. The error is caused on `upvalue_this_member_function::real_call` on the conditional noexcept part. The compiler doesn't recognise the `traits_type` typedef.

**Comment by dimitrisudell** [comment]
I am also seeing this error. Code previously compiled correctly with `Visual Studio 2019 Developer Command Prompt v16.6.5` but has been failing since updating to `Visual Studio 2019 Developer Command Prompt v16.7.2`

```
sol2\include\sol\function_types_stateless.hpp(38): error C2653: 'traits_type': is not a class or namespace name
sol2\include\sol\function_types_stateless.hpp(44): note: while compiling class template member function 'int sol::function_detail::upvalue_free_function<Fx,false>::call(lua_State *)'
```

**Comment by TerensTare** [comment]
Apparently, #1008 discusses the same problem as this, so I guess it is better to close this and to add suggestions on #1008 .
