### ISSUE TITLE
error: sol/usertype_container.hpp:503:27: error: forming reference to void

### ISSUE THREAD

**Issue by jpeter42** [ThePhD/sol2#1023]
Under Linux, when compiling using g++ -std=gnu++17, the following error occurs:

/usr/include/sol/usertype_container.hpp:503:27: error: forming reference to void
  503 |    typedef decltype(*std::declval<iterator&>()) iterator_return;

**Comment by ThePhD** [comment]
Do you have an example of what triggers this error? `iterator` should not be a void type. A small code sample, a description of the problem?
