### ISSUE TITLE
Debugging the Function that got called in lua when exception thrown in c++

### ISSUE THREAD

**Issue by slauko** [ThePhD/sol2#1024]
Hello,
i may have a simple question to answer , maybe im just not seeing it ..
so my problem is: my c++ "core" is sometimes seeming randomly crashing/exception throwing and vs2019 points me somewhere in your sol.hpp

so my question is: is there a way, like to see what function caused the crash, like the name of the function in lua that got called while exception got thrown? 

its a bit hard for me to debug my code since all of this templating is a bit weird for me to understand 🤷 

i think its caused calling an exposed function in c++ from lua with wrong parameter or something but im not 100% sure and already tried to debug my code for like a week optimizing here and there but not finding the issue since i dont know exactly whats causing it in lua :/

**Comment by ThePhD** [comment]
`SOL_ALL_SAFETIES_ON`, as well as registering your own panic handler and similar and using breakpoints in VS2019 when the panic and/or error handlers are hit.

- Safeties: https://sol2.readthedocs.io/en/latest/safety.html#safety-config
- Panic function: https://sol2.readthedocs.io/en/latest/exceptions.html#typical-panic-function
- Default Error Handler for protected function calls: https://sol2.readthedocs.io/en/latest/api/protected_function.html#id3

**Comment by slauko** [comment]
weird thing is that its just crashing with SOL_ALL_SAFETIES_ON defined and no exception gets thrown .. 
even a custom panic handler doesnt gets called .. 

i rolled back to some older version of the sol.hpp and its working now without crashes..

not sure if those msvc "fixes" have anything to do with it .. can just use the old hpp fine with the 2019 preview .. guess they fixed the compiler bug in there with type_traits

**Comment by slauko** [comment]
okay, nevermind its still crashing but i dont know why .. very weird since it wasnt crashing last 2 month :/ 
could lua5.4 cause this ? this another thing i "changed"

**Comment by slauko** [comment]
hi again, sorry for writing so much @ThePhD 

i setup everything now with SOL_ALL_SAFETIES_ON and own panic handler, 
also i defined SOL_PRINT_ERRORS and if i compile in debug mode i actually get some bugs printed out that i could fix mostly. 

im just curious why if i compile in Release mode it doesnt print any errors instead just crash my application ? 

im calling stuff like so:
```	
        if (Lua["__EVENTS"] != NULL && Lua["__EVENTS"]["OnTick"] != NULL)
	{
		sol::table Table = Lua["__EVENTS"]["OnTick"];
		for (auto Entry : Table)
		{
			sol::protected_function Func(Entry.second);
			auto Result = Func();
			if (!Result.valid())
			{
				sol::error err = Result;
				std::cout << std::endl << err.what() << std::endl;
			}
		}
	}
```
and like said in debug mode i get output like "line blabla.lua in file line 10 so.... got number, expected string" but not in release mode ... did i something wrong ? 

im using sol v3.2.1 (revision e09d2ff) at the moment btw..

**Comment by pxnch** [comment]
is there any solution to this issue? im facing the exact same problem
