### ISSUE TITLE
No Error Messages

### ISSUE THREAD

**Issue by chris-cronin** [ThePhD/sol2#1026]
In no situation can I produce an error message that gets passed to my_panic.  I've tried all manner of combinations of the SOL defines, and different combinations of luajit-beta3 and lua5.4.  I've also tried many different kinds of errors.

I decided to try to catch exceptions in desperatin, and in most situations e.what() was empty.

The only time I recieved an error message was luajit-beta3, SOL_ALL_SAFETIES_ON, SOL_EXCEPTIONS_ALWAYS_UNSAFE, with no my_panic, and with a try catch block.  The exception was simply attempt to index a nil value.  However, sol also printed a message to stderr: [sol3] An error occurred and panic has been invoked: attempt to index a nil value.

I feel like I must be doing something wrong.  How can this be used without error messages.
```
#define SOL_ALL_SAFETIES_ON 1
#define SOL_EXCEPTIONS_ALWAYS_UNSAFE 1
#include <iostream>
#include "sol/sol.hpp"

void my_panic(sol::optional<std::string> maybe_msg) {
	std::cerr << "Lua panic: ";
	if(maybe_msg) {
		// There is never a maybe_msg.
		std::cerr << maybe_msg->c_str();
	}
	std::cerr << std::endl;
}
int main() {
	sol::state state(sol::c_call<decltype(&my_panic), &my_panic>);
	state.script(R"(abc=}a = 2{)");
	int a = state["abc"]["a"].get<int>();
}
```

Microsoft visual studio 2019.  Lua compiled as x64 static lib.  The project is x64.

**Comment by ThePhD** [comment]
Panic is only called at the absolute last second. If you want information, then you need to:

- Turn safeties on (as you have in the example)
- Use `safe_script` to specifically run a checking version that does not just discard the error message (and handle it by e.g. printing it out) (it sometimes [will not](https://sol2.readthedocs.io/en/latest/errors.html#protected-functions-and-access) do this by default)
- Change the [default error handler (https://sol2.readthedocs.io/en/latest/exceptions.html#exception-handling)](https://sol2.readthedocs.io/en/latest/exceptions.html#exception-handling) / [default protected function handler(https://sol2.readthedocs.io/en/latest/api/protected_function.html#id3)](https://sol2.readthedocs.io/en/latest/api/protected_function.html#id3) to actually print out warnings

**Comment by chris-cronin** [comment]
I really appreciate the response.

I figured I misunderstood something.  However, the code below still does not produce an error message.

I want to avoid having to check every single result individually that I get from sol.  I hoped that accessing a bad/nil value would cause a failure with an error message.

```
#define SOL_ALL_SAFETIES_ON 1
#include <iostream>
#include <assert.h>
#include "sol/sol.hpp"

void lua_panic_handler(sol::optional<std::string> maybe_msg) {
	std::cerr << "Lua panic: ";
	if(maybe_msg) {
		std::cerr << maybe_msg->c_str();
	}
	std::cerr << std::endl;
}

int lua_exception_handler(lua_State* L, sol::optional<const std::exception&> maybe_exception, sol::string_view description) {
	std::cerr << "Lua Exception: ";
	if(maybe_exception) {
		const std::exception& ex = *maybe_exception;
		std::cerr << ex.what();
	} else {
		std::cerr.write(description.data(), description.size());
	}

	std::cerr << std::endl;

	return sol::stack::push(L, description);
}

std::string lua_error_handler(std::string msg) {
	std::cerr << "Lua error:  " << std::endl;
	return msg;
}

int main() {
	sol::state state(sol::c_call<decltype(&lua_panic_handler), &lua_panic_handler>);
	state.open_libraries(sol::lib::base, sol::lib::debug);

	state.set_function("lua_error_handler", &lua_error_handler);
	state.script(R"(
		function handle_error(msg.)
			local trace = debug.traceback();
			return lua_error_handler(msg .. ". " .. trace)
		end)");

	sol::protected_function::set_default_handler(state["handle_error"]);
	state.set_exception_handler(lua_exception_handler);

	// All good here. I can test the script result.
	auto result = state.safe_script(R"(abc={a = 2})");

	// No error message here. However the program terminates.
	int a = state["abc"]["not_a_key"];
	
	/*
	// Is this the only way to get an error message:
	sol::optional<int> a = state["abc"]["not_a_key"];
	assert(a.has_value() && "no value for abc[not_a_key]");
	*/
}
```

**Comment by davidchisnall** [comment]
Is there a worked example of getting useful errors out for this kind of thing?  Being told that a string was expected *somewhere* in a Lua script is not a great developer experience.  I typically end up adding a load of print statements to figure out where the error is, presumably the Lua interpreter knows exactly which line failed.
