### ISSUE TITLE
Passing object to lua function does not use my own defined sol_lua_push function

### ISSUE THREAD

**Issue by Intrets** [ThePhD/sol2#1029]
Below is a slightly condensed and expanded snippet from the example at https://sol2.readthedocs.io/en/latest/tutorial/customization.html .

```c++
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <iostream>

struct two_things
{
	int a;
	bool b;
};

int sol_lua_push(sol::types<two_things>, lua_State* L, two_things const& things) {
	int amount = sol::stack::push(L, things.a);
	amount += sol::stack::push(L, things.b);
	return amount;
}

int main() {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.script("function f(a, b) print(a, b) end");

	sol::function f = lua["f"];

	two_things two_things_object{ 24, false };

	f(two_things_object); // same as f.operator()<two_things&>(two_things_object);
	f.operator()<two_things const&>(two_things_object);
	f(std::move(two_things_object));
	f(two_things{ 24, false });

	std::cin;

	return 0;
}
```

Expected result:
```
24      false
24      false
24      false
24      false
```

Actual result:
```
sol.two_things*: 0000014772C45568       nil
sol.two_things*: 0000014772C9E618       nil
24      false
24      false
```

The second call to `f` will behave as expected after this pull request I made https://github.com/ThePhD/sol2/pull/1028 .

I expect the first call to `f` to work in the same way, but without explicitly specifying the parameter as `const&`, instead it pushes a pointer (or reference?) on the stack.

**Comment by Intrets** [comment]
So if a parameter is a non-const reference it trips this flag https://github.com/ThePhD/sol2/blob/e89b6ac2e72e842a9d3b49e942d018f6c078b875/include/sol/stack_core.hpp#L945 and then uses an unqualified pusher to push the raw reference to the stack? https://github.com/ThePhD/sol2/blob/e89b6ac2e72e842a9d3b49e942d018f6c078b875/include/sol/stack_core.hpp#L917 Is this intended?

**Comment by Intrets** [comment]
I realised it also looks for a `sol_lua_push(lua_State*, ...)` without the phantom type like in the example. 

So with the following function instead:
```
int sol_lua_push(lua_State* L, two_things const& things) {
	int amount = sol::stack::push(L, things.a);
	amount += sol::stack::push(L, things.b);
	return amount;
}
```
everything works as expected.

**Comment by ThePhD** [comment]
Yeah, `push` doesn't need the type tag because... well, you're handing it the whole type.

**Comment by ThePhD** [comment]
Oh, and the docs themselves / example itself is bad. Wonder how that didn't trigger a failure on my machine...

Well, fix incoming.

**Comment by ThePhD** [comment]
Fixed in latest, I think.
