### ISSUE TITLE
Enum types

### ISSUE THREAD

**Issue by felaugmar** [ThePhD/sol2#103]
Enum types can be easily simulated by doing something like this \/

C++:
```
enum Direction {
    UP = 0,
    RIGHT,
    DOWN,
    LEFT,
};

void showEnum(int direction) {
    static_cast<Direction>(direction);
}

lua.set_function("showEnum", &showEnum);
```

Lua:
```
local Direction = {
    UP = 0,
    RIGHT = 1,
    DOWN = 2,
    LEFT = 3
}

showEnum(Direction.DOWN)
```

--

It's not a great thing, i know
But, this will be possible in future releases? \/

C++:
```
enum Direction {
    UP = 0,
    RIGHT,
    DOWN,
    LEFT,
};

void showEnum(Direction direction) {
    direction;
}

lua.new_usertype<Direction>("Dir",
                            "UP", &Direction::UP,
                            "RIGHT", &Direction::RIGHT,
                            "DOWN", &Direction::DOWN,
                            "LEFT", &Direction::LEFT);
```

Lua:
`showEnum(Direction.UP)`

**Comment by ThePhD** [comment]
````
enum class Direction {
     Up,
     Right,
     Down,
     Left
}

sol::state lua;

lua["Direction"] = lua.create_table_with( "Up", Direction::Up, "Down", Direction::Down, "Left", Direction::Left, "Right", Direction::Right );
````

Should work? If it doesn't, let me know.

**Comment by felaugmar** [comment]
Yes, it worked, of course, nice :)

Maybe a note in the tutorial about it?
probably others will question about it like me ;-/

**Comment by EliasD** [comment]
I've tried this too and this works:
```c++
sol::object obj = lua["Direction"]["Up"];
auto dir = obj.as<Direction>();
```
but ```obj.is<Direction>``` returns false. If I try to register ```Direction``` as usertype, ```obj.as<Direction>()``` fails. What can be done about this?

**Comment by Nava2** [comment]
```C++
auto dir = static_cast<Direction>(obj.as<int>());
```

**Comment by ThePhD** [comment]
That was a small oversight of mine. I have forgotten traits specifically for converting `enum class` types and the like (and plain `enum`, without the class, were treated like integers). Pushing the fix today, along with about 20 other things...

**Comment by ThePhD** [comment]
It also seems like a convenience function
````
lua.create_enum( "enum_name",
    "val1", my_enum::val1,
    "val2", my_enum::val2,
    "val3", my_enum::val3,
    "val4", my_enum::val4
    // ...
);
````

**Comment by EliasD** [comment]
Wow, thanks! That was quicker then I expected. I'll test it later. :)

```create_enum``` function would indeed be very useful. It would be also great to automatically make "enum_name" table read only. Accidentally changing or adding/removing some values in that table will lead to some bad stuff.

**Comment by ThePhD** [comment]
![It seems to work](http://i.imgur.com/BfCb32H.png)

Obligatory warning that making it "read-only" has a performance overhead etc. etc., if read-only bothers you call `new_enum<false>` to trigger a read/write table (that's just a regular table with no fancy metatable stuff).

**Comment by Nava2** [comment]
I don't think this was ever documented.

**Comment by ThePhD** [comment]
You're right, it hasn't been, I forgot. I guess I'll get on it.

**Comment by cgloeckner** [comment]
Is there a way to quickly register a large enum (that supports iteration and to_string conversion) without explicitly touching every element?

**Comment by ThePhD** [comment]
Unfortunately, no. Sol does not do auto-binding (yet).

The only way to do automatic iteration is to require the user to pick one of many available reflection libraries out there (Boost.Fusion / libmirror), force the user to annotate their types, and then hook into those structures. This is a bit of a daunting task.

The other way would be to use a parser of some sort to read C++ source and then just bind All The Things. The problem with this approach is that now I need to build a C++ parser into Sol at runtime. That would make the library a humongous pain for both end users to use (executable size and other things) and a problem for me (I'm building the early stages of a compiler. Aaahhh, the BUGS).

The good news is, Sol can be used with other generators. That is, there's no harm in grabbing, say, SWIG to do some rudimentary bindings for enums and other types while Sol just helps you manage state and register smaller, concise usertypes.

I know this answer isn't satisfactory. I don't like it myself, to be quite frank: problem is, my hands are tied until C++??, when I can take a hard dependency on built-in reflection. I'm going to hope it's before C++20.

**Comment by cgloeckner** [comment]
Oh, ok thx :D @eliasdaler suggested the following to be. Maybe someone else will find it usefull, too:
```c++
sol::table enumTable = lua["SomeEnumName"];
for(auto& enumValue : enumValues)
    enumTable [to_string(enumValue)] = enumValue
```

**Comment by Codinablack** [comment]
Sorry to be that guy who bumped this CLOSED issue from 7 years ago... but as a new user of sol, I am reading the documentation and it seems this is STILL missing from the documentation. Just thought it should be known, because being able to handle enums so easily is an AMAZING feature, that is not documented anywhere as far as I know.

![image](https://github.com/ThePhD/sol2/assets/8696596/810f8db4-b5fe-42fd-8321-fdb2708d290b)

**Comment by Rochet2** [comment]
> all the results returned there, are listing enums for sol api, not how to handle them with sol.

Not necessarily true. The last result points to the new_enum function which was implemented in relation to this issue I believe.
Though I guess it is a bit hidden inside the table members documentation.

**Comment by ThePhD** [comment]
Yes, please do use new_enum, that should solve it. If it doesn't work out
still, do let me know.

> Though I guess it is a bit hidden inside the table members documentation.

Yeah. I've got a LOT of work to do for sol2 and I haven't started yet.
Highest on the list is automatically self-documenting members based on the
bindings people write, and just... entirely new documentation based on a
C++-parsing doc generator that can export it into the RST docs (so that I
don't have to keep forgetting to update the docs when I change the
function).
