### ISSUE TITLE
Maybe unintentional compatibility break to Lua 5.1

### ISSUE THREAD

**Issue by violinyanev** [ThePhD/sol2#1031]
Dear @ThePhD ,

I was checking out the latest Sol main branch (fighting with MSVC hiccups again, saw you have a fix at @63df43e061 ). Noticed by chance that my build doesn't work any more (it uses Lua 5.1). I think it's because you added the lua_gc code in the same commit, but it fails compiling because it can't find the "LUA_GCISRUNNING" constant. A bit googling yields that it was added with Lua 5.2, so probably too new?

Anyway, just wanted to share my insight before maybe some of your other customers complain. Close if the issue is not relevant or was intended so! Also, let me know if I can/should help, maybe a sentence or two where to look and what to do!

MSVC: 16.7.4 (the one which broke of course)
Lua: 5.1.1 (upstream)
Sol: no major version, commit @63df43e061
CMake options: SOL_USING_CXX_LUA=1 SOL_EXCEPTIONS_ALWAYS_UNSAFE=1 SOL2_LUA_VERSION=5.1.1

**Comment by ThePhD** [comment]
This is fixed in latest. Or, so I hope. :D

**Comment by violinyanev** [comment]
Yup, looks great! I see you also deleted the copy-constructor etc. from load_result - 👍
