### ISSUE TITLE
Usertype __index with table doesn't work as expected

### ISSUE THREAD

**Issue by vorlov-playrix** [ThePhD/sol2#1032]
Hi. Sorry if it was already described, but I didn't find anything in docs or old issues. I'd appreciate a link if it exists.

**The problem**
I have ECS World where entities with different components live. I need to access components by type name in Lua. Components are not inherited from the same base class. And even if they were, I can't just bind a C++ `ComponentBase* Get(const char* type)` , because result will not provide derived object's Lua interface due to impossibility of runtime downcast.

**The solution**
When registering another component type, I add Lua getter to a member `ComponentAccessTable` in the World:
```
ComponentAccessTable[TypeName] = [pTypedStorage](HEntity EntityID) { return pTypedStorage->Find(EntityID); };
```
Then I want to use this table as an additional index for my World. So I register World type like this:
```
lua.new_usertype<CGameWorld>("CGameWorld"
	, sol::meta_function::index, &CGameWorld::ComponentAccessTable
	, "FindEntity", &CGameWorld::FindEntity
);
```
Note that the World has its own interface, and `ComponentAccessTable` must serve as a fallback for inexistent keys. AFAIK Lua supports setting `__index` to a table, and I expect a script `World.FindEntity` to access a class method, and script `World.MyComponent` to search corresponding getter in a ComponentAccessTable.

**What goes wrong**
Instead of searching absent keys in ComponentAccessTable, Lua returns this table as a result of access to any inexistent key, so that `World.FindEntity` is a class method, and any other key like `World.KeyThatNeverExisted` returns ComponentAccessTable itself.

**Questions**

1. Is it a bug or normal behaviour?
2. Why sol::meta_function::index can't be set to a table in the same way as __index can?
3. Maybe there is a generally better way to achieve what I want?

Thanks in advance.

**Comment by ThePhD** [comment]
From what I'm reading, you are passing a pointer to a static `sol::table` member. Is that correct?

**Comment by vorlov-playrix** [comment]
No, it is not static, it is a member, so that every World instance has its own one.

**Comment by vorlov-playrix** [comment]
And another belated question:
4. Do I need to store ComponentAccessTable somewhere in Lua, like:
`SolState["ServiceTables"]["ComponentAccessTable"] = ComponentAccessTable;`
and if I don't, will this table remain on the stack forever, or is it popped after being stored in an __index?

**Comment by ThePhD** [comment]
So I'll give the short answer and the long answer.

# Short Answer
Not yet implemented, still thinking about it. You need to write a function and index into the table yourself. You can see a fun example here of what that means: https://github.com/ThePhD/sol2/blob/develop/examples/source/usertype_dynamic_get_set.cpp#L24

# Long Answer
By the time we get through checking your function names and other key/values in the usertype, we are already outside of Lua and its mechanisms. If I were to check "is this thing they set as the index function a table or something I can index", then I might need to impose a runtime cost on everybody who does that (or add some extra compile-time to check if someone explicitly passed exactly a `sol::table` or similar object as the "index" entry).

So, I could add it as a feature with some shenanigans, but that might take a long while. I'm also not sure about that design: some people might expect that it just returns a table now, since that's kind of the behavior that's consistent with the rest of the library... but I kind of liked the smarter interpretation I talked about earlier.

**Comment by vorlov-playrix** [comment]
Thank you for the detailed answer. It is a bit counter-intuitive of `sol::meta_function::index -> sol::table` to behave differently from Lua `__index -> table`, but it is OK for me to use index function as long as this case is documented.
Sadly this one doesn't work (why?):
`sol::meta_function::index, [](CGameWorld& self, sol::stack_object key) { return self.ComponentAccessTable[key]; }`
but this one does and is enough for me:
`sol::meta_function::index, [](CGameWorld& self, const char* key) { return self.ComponentAccessTable[key]; }`
so I don't have to handle different key types manually.

And please could you answer question 4 or provide a link to docs? I still don't understand where new table is stored if I don't save it somewhere.

**Comment by ThePhD** [comment]
For question #4, it will be stored somewhere, so you're fine and don't need to keep it alive (if you pass it directly). If you write a function, then you need to keep it alive in, say, the object itself (like you are doing right now). Every `sol::reference`-derived type (`sol::table`, `sol::coroutine`, `sol::function` etc. etc.) is kept alive by simply keeping the C++ object around.

The `stack_object` key should work just fine, so I'll have to investigate that.

**Comment by vorlov-playrix** [comment]
It compiles but fails at runtime, returning nil instead of the field SmartObject. Script:
`local SO = Session.World.SmartObject(Target.Entity)`
the only thing changed is `sol::stack_object key <-> const char* key` in the index function. With const char* key it works well.
Sol 3.2.1 (latest release, single file)
VS 2019 16.7.4

**Comment by vorlov-playrix** [comment]
May be the reason is in `call_into_lua`:
```
else {
	(void)tr;
	decltype(auto) r = call<check_args>(types<meta::return_type_t<Ret0, Ret...>>(), ta, L, start, std::forward<Fx>(fx), std::forward<FxArgs>(fxargs)...);
	using R = meta::unqualified_t<decltype(r)>;
	using is_stack = meta::any<is_stack_based<R>, std::is_same<R, absolute_index>, std::is_same<R, ref_index>, std::is_same<R, raw_index>>;
	if constexpr (clean_stack && !is_stack::value) {
		lua_settop(L, 0);
	}
	return push_reference(L, std::forward<decltype(r)>(r));
}
```
`lua_settop` is called there in my case, probably after that proxy `r` indexed with stack object becomes invalid.

**Comment by ThePhD** [comment]
Oh, okay. Yeah, so `proxy` types aren't really safe for general returns. You should force the proxy type to convert to something you can use, such as a `sol::object`.

```cpp
sol::meta_function::index, [](CGameWorld& self, sol::stack_object key) -> sol::object { return self.ComponentAccessTable[key]; }
```

**Comment by vorlov-playrix** [comment]
Now it works, thank you.
