### ISSUE TITLE
referencing static float

### ISSUE THREAD

**Issue by velkyel** [ThePhD/sol2#1033]
```
static float value = 1.23;
sol::state L;

int main()
{
   L.open_libraries();
   L["value"] = &value;

   // run lua script:
   // print(type(value))
   // print(value)
}
```

print(type(value)) -> "usertype"

print(value) ->
```
stack index 1, expected number, received sol.float *: not a valid floating point number 
stack traceback:
	[C]: in ?
	[C]: in function 'base.tostring'
	[C]: in function 'base.print'
	[string "return print(value)..."]:1: in main chunk
```

it's not possible reference c/c++ float value this way?  why it's not valid floating point number? what is correct way?
thank you

**Comment by ThePhD** [comment]
Copy-pasted from someone who asked the exact same question in the Discord yesterday:

> You cannot take pointers to Lua variables that are "primitive" or "built in" types (float/double/int/strings/etc.)
Only tables.

**Comment by ThePhD** [comment]
To be clear, this is a Lua limitation, not a sol2 limitation. You can't write Lua code that treats that like a number, or references/points to a float and updates it without creating a special "Proxy" type.

**Comment by velkyel** [comment]
thank you
