### ISSUE TITLE
Objects stored in containers will not outlive the container

### ISSUE THREAD

**Issue by cschreib** [ThePhD/sol2#1036]
Setup:
 - clang-10 with libstdc++-8
 - sol-3.2.1, default configuration
 - lua-5.2

The following code example crashes for me:
```c++
// Define some type which will easily fail when used after deleted
// but that sol won't automatically understand / bind to a Lua value
struct some_userdata {
    std::string data;
};

// Define a Lua function that returns a vector of such objects
lua.set_function("create_list", []() {
    std::vector<some_userdata> v;
    v.push_back(some_userdata{"foo"});
    v.push_back(some_userdata{"bar"});
    v.push_back(some_userdata{"baz"});
    v.push_back(some_userdata{"zee"});
    v.push_back(some_userdata{"bob"});
    return v;
});

// Define a Lua function that uses such objects
lua.set_function("print_data", [](const some_userdata& d) {
    std::cout << d.data << std::endl;
});

lua.script(R"(
    local d
    do
        -- Get the list
        local list = create_list()
        -- Store the first item in a Lua variable that will outlive the list
        d = list[1]
    end
    -- Force GC, so the list is destroyed
    collectgarbage()
    -- Try to use the item we saved: crash
    print_data(d)
)");
```

I suspect the crash means that "userdata" containers (i.e., not Lua tables) generated by sol are the exclusive owners of the contained data. They will therefore delete the data when being garbage collected, regardless of whether there were existing references to these data in Lua. I don't know the internals of sol well enough to understand what is exactly returned by ``list[1]`` above, and I could not find any information in the documentation regarding the lifetime of objects in Lua containers.

Is this the intended behavior? If so, and if I wanted the example above to not crash, is returning a plain Lua table (using ``sol::as_table`` my only choice?

**Comment by Rochet2** [comment]
One approach is to explicitly copy (or move?) elements you want to exist after the deletion of the list.
Here is an example. Simply doing `d = list[1]:copy()` where the copy method creates a copy. https://godbolt.org/z/x5WKGs
This would allow you to avoid an entire as_table or copying every element always. But it requires the explicit copy when you need it and will potentially result in a crash if you make a mistake.

**Comment by ThePhD** [comment]
Containers return references, and do not copy. Mostly because this would be violently horrible for performance characteristics. So, yes: you will need explicit copies. This is one place where the C++-isms leak through.

I have been trying to think of a way to make it so things *copy* into Lua. The problem is, that _really_ breaks a lot of ways people use items from containers, such as taking out an item and making changes and expecting to see those changes from the item reflected in the original container.

It's a hard problem to juggle, and so I think it's best if you're explicit about it!

I recommend @Rochet2's Approach 3, or Approach 2.

**Comment by cschreib** [comment]
Ok that makes sense, thanks to you both! I hadn't considered this from the point of view of having a persistent C++ container being mutated from Lua, for which this ownership model makes perfect sense. I think it is probably a good idea to mention this in the documentation though.

In the mean time I'll got with option 2, as it preserves the conventional Lua ownership semantics (I'm not extremely concerned about performance, as I use Lua for UI callbacks only).
