### ISSUE TITLE
Issue with the first argument when calling a member function in lua from c++

### ISSUE THREAD

**Issue by sagunkho** [ThePhD/sol2#1037]
I'm calling the following lua function from c++ - 
```
pkt_tbl[x]["module"]["deserialize"](s.to_string());
```

Lua function being part of a metatable -
```
function CA_LOGIN:deserialize(buffer)
	print(buffer)
end
```
However, buffer is nil with one argument sent (s.to_string()) and works when making it the second argument (1, s.to_string())
I can't find the documentation for what the first argument is, so just made an issue here. please advise.

**Comment by ThePhD** [comment]
The first argument is the `self` argument. The second is the `buffer` argument. Using the colon (`:`) means "the first argument is invisible, and it's `self`. If you don't want that, remove colon (`:`) and use a dot (`.`) instead.
