### ISSUE TITLE
Inconsistent and incomplete iteration over table containing nil-valued pairs

### ISSUE THREAD

**Issue by TheMostCuriousThing** [ThePhD/sol2#104]
Two issues in one:
- In a for_each loop of key-value pairs, the table iterator excludes all nil-valued pairs. Is this intended behavior?
- The placement of nil-valued pairs in a table affects the iteration order of pairs and the indexing of pairs without keys.

cpp:
```c++
std::unordered_map<string, string> key_value_pair;
sol::table animals = lua["animals"];
animals.for_each([&](pair<sol::object, sol::object> pair) {
    key_value_pair.insert({ pair.first.as<string>(), pair.second.as<string>() });
});
for (auto i : key_value_pair) std::cout << i.first << " = " << i.second << endl;
```

lua:
```lua
animals = {
    animal_rodent = "mouse",
    "dog"
}
--[[ Output:
animal_rodent = mouse
1 = dog
--]]

animals = {
    animal_rodent = "mouse",
    "dog",
    animal_nil
}
--[[ Output (animal_nil excluded):
animal_rodent = mouse
1 = dog
--]]

animals = {
    animal_rodent = "mouse",
    animal_nil,
    "dog",
}
--[[ Output (animal_nil excluded, but dog key is 2 and iterator started at dog instead of mouse):
2 = dog
animal_rodent = mouse
--]]
```

**Comment by TheMostCuriousThing** [comment]
On a side note...I'm not sure how to iterate over only table keys or only table values using `sol::for_each`. What would be the best way in general to do this?

**Comment by ThePhD** [comment]
You can't get them separately. Lua doesn't allow for this.

I'm assuming `animal_nil` is just `nil`.

`nil` is a special key for tables in Lua. If you have it as a key, it can screw your iterations up (in fact, as a key it might even tank when you try to set it as something).

Finally, Lua's table structure is a essentially one big sloppy hash-map. Order of iteration is not guaranteed in any scenario to be in any defined order, ever. That's the limitation of the implementation and of the language, not `Sol`.

**Comment by ThePhD** [comment]
Also of note is C++'s `unordered_map` has no defined iteration order either. So if you were depending on that to be a property of the map... iiit's not.

**Comment by Nava2** [comment]
> On a side note...I'm not sure how to iterate over only table keys or only table values using sol::table::for_each. What would be the best way in general to do this?

```c++
sol::table tbl; // imagine this is assigned
tbl.for_each([](const sol::object& key, const sol::object& value) { });

// only values
tbl.for_each([](const sol::object& /*key*/, const sol::object& value) { });

// only keys
tbl.for_each([](const sol::object& key, const sol::object& /*value*/) { });
```

Not the prettiest, but it will do what you want.

**Comment by TheMostCuriousThing** [comment]
Thanks all. Sorry if I come off like an asshat with no idea what she's talking about @_@

> Finally, Lua's table structure is a essentially one big sloppy hash-map. Order of iteration is not guaranteed in any scenario to be in any defined order, ever. That's the limitation of the implementation and of the language, not Sol.

Okay, makes sense.

> Also of note is C++'s unordered_map has no defined iteration order either. So if you were depending on that to be a property of the map... iiit's not.

Wasn't depending on it, but good to know.

> Not the prettiest, but it will do what you want.

Yep, thank you kindly!

**Comment by ThePhD** [comment]
You weren't an asshat at all, don't worry.

Good luck with the library, and do drop another issue if something's unclear. (This helps me fix the documentation up so others don't come into the same problems without a solution being somewhere!)
