### ISSUE TITLE
Register ctor for aggregate initializiable types

### ISSUE THREAD

**Issue by TerensTare** [ThePhD/sol2#1041]
I have a base, `final` `struct` that has `public`-only members only and  has no ctor/dtor defined, so it can be aggregate-initializiable (C++ 20). I want to register this `struct` to be used in Lua with `new_usertype` and define a ctor for it that takes the types of all the members, but I get an error saying that the ctor is not found on VS2019 v16.7.5. I understand that this error is obvious because the ctor doesn't exist, but is there any solution/workaround to this?
Sample code:
``` cpp
struct sample final // the aggregate
{
int d1;
float d2;
};

void regSample(sol::state_view lua_)
{
lua_.new_usertype<sample>("sample", sol::constructors<sample(int, float)> // any way to define a ctor for sample ??
);
}
```

**Comment by ThePhD** [comment]
Use `sol::factories([](int arg0, float arg1) { return sample(arg0, arg1); })` instead.

**Comment by TerensTare** [comment]
Thank you very much. This solved my problem.
