### ISSUE TITLE
Sol 3.2.2 header reports version as 3.5.0

### ISSUE THREAD

**Issue by jdpage** [ThePhD/sol2#1042]
Note: the original version of this issue said 3.2.1 because I made a mistake. I downloaded a fresh copy of the headers and re-confirmed that 3.2.2 exhibits the issue.

The 3.2.2 header downloaded from the Github release page reports its version as 3.5.0 instead of 3.2.2.

Test case:
```c++
#include <iostream>
#include <sol/sol.hpp>

int main() {
  std::cout << "Sol " << SOL_VERSION_STRING << std::endl;
  std::cout << "Major: " << SOL_VERSION_MAJOR << std::endl;
  std::cout << "Minor: " << SOL_VERSION_MINOR << std::endl;
  std::cout << "Patch: " << SOL_VERSION_PATCH << std::endl;
  std::cout << "Version: " << SOL_VERSION << std::endl;

  return 0;
}
```

Expected output:
```
Sol 3.2.2
Major: 3
Minor: 2
Patch: 2
Version: 300202
```

Actual output:
```
Sol 3.5.0
Major: 3
Minor: 5
Patch: 0
Version: 300500
```

For completeness' sake: I compiled and ran the above code on Windows 10 Version 1909, using LLVM 10.0.0 installed from scoop, against Lua 5.4.1, with the following commands:

```
PS> clang++ -Ipath/to/sol -Ipath/to/lua/src -o test_case.exe test_case.cc -std=c++17
PS> ./test_case.exe
```

However, I'm pretty sure that that doesn't matter, given that the header file (lines 22 thru 45) looks like this:

```c++
// This file was generated with a script.
// Generated 2020-10-03 21:34:24.496436 UTC
// This header was generated with sol v3.2.1 (revision 48eea7b5)
// https://github.com/ThePhD/sol2

#ifndef SOL_SINGLE_INCLUDE_HPP
#define SOL_SINGLE_INCLUDE_HPP

// beginning of sol/sol.hpp

#ifndef SOL_HPP
#define SOL_HPP

// beginning of sol/version.hpp

#include <sol/config.hpp>

#include <cstdint>

#define SOL_VERSION_MAJOR 3
#define SOL_VERSION_MINOR 5
#define SOL_VERSION_PATCH 0
#define SOL_VERSION_STRING "3.5.0"
#define SOL_VERSION ((SOL_VERSION_MAJOR * 100000) + (SOL_VERSION_MINOR * 100) + (SOL_VERSION_PATCH))
```

Ran into this issue while setting up my application to show the Sol version it was compiled with. Thanks for building such a useful project! It's been spectacularly easy to use so far.

**Comment by ThePhD** [comment]
Woops, I was expecting to push a big change and I hadn't yet that would bump it to 3.5.0! My bad; just pretend it's 3.2.2 while I fix it. ;D

**Comment by ThePhD** [comment]
Fixed in latest!
