### ISSUE TITLE
Floating point issues on Linux

### ISSUE THREAD

**Issue by jacob-likens** [ThePhD/sol2#1043]
Platforms: 
g++10, clang++10 on Fedora Linux 32
MSVC v15.9 on Windows 10

There's some kind of very strange issue I've encountered with using doubles as properties that are passed between C++ and Lua. Essentially, when retrieving an internal 2D vector type `Vec2`, the `x` and `y` properties get corrupted. They always end up as 3 distinct values:

- 0
- -1.08...e-19
- -3.68...e+19

This happens when the internal `Vec2` is converted into `LuaVec2`, and it only happens on Linux. If `LuaVec2` is created via a constructor inside the Lua VM, it functions as expected. Additionally, when the LuaVec2 is converted back into Vec2 on the C++ side of things, it functions completely normally. Additionally, this only happens on Linux. When I tested it out on Windows, I received results that I originally expected!

IE:
```lua
--Returns internal mech class
player = Mech.new("PLAYER")
--sol::property that uses a getter/setter to convert between Vec2 and LuaVec2
ppos = mech.pos
print("x: "..ppos.x)
--On Linux, will output 'x: -1.084202e-19'
--On Windows will, output 'x: 108.54166412354', which is the correct number according to C++ logs
otherMech = Mech.new("othermech")
--Correctly moves otherMech on top of player
otherMech.pos = ppos

--LuaVec2 is aliased to Vec2 inside the Lua VM for user clarity.
vec = Vec2.new(2.0, 3.0)
--This will output '2' on all systems
print("x: "..vec.x)
```

Here is the wrapper struct:
```cpp
struct LuaVec2
{
    LuaVec2() : x(0.0f) y(0.0f) {}
    LuaVec2(double _x, double _y) : x(_x) y(_y) {}
    LuaVec2(Vec2 v) : x(v.x) y(v.y) {}

    Vec2 AsVec2()
    {
        return Vec2(x, y);
    }

    double x;
    double y;

};
```

And it's usertype declaration:
```cpp
sol::state lua;
sol::usertype<LuaVec2> vec2_type = lua.new_usertype<LuaVec2>("Vec2", 
        sol::constructors<LuaVec2(), LuaVec2(double, double)>());
vec2_type["x"] = &LuaVec2::x;
vec2_type["y"] = &LuaVec2::y;
```

I've used this exact same struct with a different Lua wrapper before and it worked fine on Linux. I should note that `Vec2` uses `float`, while `LuaVec2` uses `double`. I played around and made LuaVec2 use `float`, but it didn't resolve the issue.

This essentially makes the LuaVec2 object completely opaque for my Linux users. They can use the provided API and get it from the C++ side of things, and they can even pass it back to the C++ side of things and it will work perfectly fine. However they cannot read or write into it making it of very limited use. I tried on two computers running Linux and they both got the same erroneous result.

**Comment by ThePhD** [comment]
Guess I need to download me a Fedora Image so I can install it on this VM so I can test this.

This might take some time. :D

**Comment by jacob-likens** [comment]
Hmm, I set up a test outside of the codebase, isolating the offending data structures, and I couldn't get it to reproduce. I'm going to work on doing a deeper dive to see if this might actually be a me problem!

**Comment by jacob-likens** [comment]
Alright so I've definitely determined that something _wierd_ happens outside of my own code.

This code:
```lua
player = Mech.new("PLAYER")
logVec("Player", player.pos)
LOG("---- TEST TEST TEST ----")
TESTLOG(player.pos.x)
```

Will output the following:
```
[LOG] New LuaVec2: (108.541664, 114.583336)
[LOG] From Vec2: (108.541664, 114.583336)
[LUA] Player pos
(-1.084202e-19, 3.689349e+19)
[LUA] ---- TEST TEST TEST ----
[LOG] New LuaVec2: (108.541664, 114.583336)
[LOG] From Vec2: (108.541664, 114.583336)
[LUA] 0.000000
```
`[LOG]` indicates a log from C++. Specifically, I have the C++ side log every time a new LuaVec2 is created like so:

**Comment by jacob-likens** [comment]
I have discovered the issue. For some reason, this define was in one of the make scripts:
`LUA_32BITS`

And for some reason ld doesn't throw a tantrum when you statically link a 64-bit executable to a 32-bit library.

Love the wrapper btw. This is easily the best one out there, you're doing great work.

**Comment by ThePhD** [comment]
Glad you figured it out!
