### ISSUE TITLE
Error with globals

### ISSUE THREAD

**Issue by TerensTare** [ThePhD/sol2#1045]
1. Produce a simple, short, compilable test case that reproduces your problem.
``` cpp
// my_struct.hpp
inline struct my_struct final { float angle; } struct_;

void loadStruct(sol::state_view lua_) {
lua_.new_usertype<my_struct>("my_struct",
    "angle", &my_struct::angle,
);
lua_["struct_"] = sol::var(struct_); // Error persists even with std::ref
}

// main.cpp
sol::state lua;

void init() { 
lua.open_libraries(sol::lib::base); 
loadStruct(lua);
if (auto res = lua.safe_script_file("script.lua"); !res.valid())
        {
            sol::error err = res;
            std::cout << err.what();
        }
}

void Update(float time_) {
sol::safe_function fn = lua["update"];
        if (auto res = fn(time_); !res.valid())
        {
            sol::error err = res;
            std::cout << err.what();
        }
}

int main()
{
init();
while(true)
    Update(10000.f);
}
```
``` lua
-- script.lua
function update(dt)
print "updating"
local change = dt * 0.02
struct_.angle = struct_.angle + change -- problematic line
end
```

2. Make a descriptive title that summarises the bug as a whole.
I have a struct named `my_struct` and a global instance named `struct_` which I want to access on Lua. I use `loadStruct` to register the struct and instance to a given `sol::state_view`. Also, there is an `Update` function which calls `update` from "script.lua". On `update` of the script, `struct_` is accessed/modified. When I run this code, I get the following error:
``` log
script.lua:3: attempt to perform arithmetic on a nil value (field '?')
stack traceback:
        script.lua:3: in function 'base.update'
```
4. Include Compiler/IDE (Visual Studio, XCode...), Build and Deployment System, Language (C++, Objective-C++), and any special defines you have set.
- Visual Studio 2019 v16.7.5 with CMake 3.17.2, C++ Language

**Comment by ThePhD** [comment]
No repro. It prints "updating", does the update, and loops around just fine for me.

Same Cmake and Visual Studio version.

**Comment by ThePhD** [comment]
I will note that this is AFTER I changed `sol::var(struct_)` (which ONLY works when defining members on a usertype, not when setting plain globals and values in regular tables), to `struct_` or `std::ref(struct_)` or `&struct_`.

![](https://i.imgur.com/OQi84sb.png)

Here is the code I used, with the `struct_` change made:

```cpp
#include <sol/sol.hpp>
#include <iostream>

inline struct my_struct final { float angle; } struct_;

void loadStruct(sol::state_view lua_) {
	lua_.new_usertype<my_struct>("my_struct",
		"angle", &my_struct::angle
	);
	lua_["struct_"] = std::ref(struct_);
}

// main.cpp
sol::state lua;

void init() { 
	lua.open_libraries(sol::lib::base); 
	loadStruct(lua);
	if (auto res = lua.safe_script_file("script.lua"); !res.valid())
	{
		sol::error err = res;
		std::cout << err.what();
	}
}

void Update(float time_) {
	sol::safe_function fn = lua["update"];
	if (auto res = fn(time_); !res.valid())
	{
		sol::error err = res;
		std::cout << err.what() << std::endl;
	}
}

int main()
{
	init();
	while(true)
		Update(10000.f);
}
```

**Comment by TerensTare** [comment]
I solved the problem. Matter of fact, `struct_::angle` is a `std::vector<float>`, and I used float just for simplicity. Also, the .lua file was really as follows:
``` lua
function update(dt)
print "updating"
local change = dt * 0.02
struct_.angle[0] = struct_.angle[0] + change -- access of index 0
end
```
The error was caused by an access of index 0 (I forgot Lua starts indexing from 1). I'm really sorry for wasting time with this simple error.

**Comment by ThePhD** [comment]
Hey, it's no problem!

Happens to everyone, and a little sanity-check and rubber ducking never hurt anyone. :D
