### ISSUE TITLE
Why is `SOL_DEFAULT_PASS_ON_ERROR_I_` default to `SOL_ON`/`SOL_DEFAULT_ON`?

### ISSUE THREAD

**Issue by lone-wolf-akela** [ThePhD/sol2#1046]
I've read the document and it says `SOL_DEFAULT_PASS_ON_ERROR` is "very dangerous" and "DON'T TURN THIS ON UNLESS YOU HAVE AN EXTREMELY GOOD REASON".
However, in https://github.com/ThePhD/sol2/blob/288f4f4e73f379cca56f8eb7840a449adac0acb9/single/include/sol/sol.hpp#L446-L456

`SOL_DEFAULT_PASS_ON_ERROR_I_` is turned on if `SOL_ALL_SAFETIES_ON_I_` or `SOL_DEBUG_BUILD_I_` is turned on.
Why? And how can I turn off it if I'm building in debug mode?

**Comment by ThePhD** [comment]
Oops, that's just a mistake on my part!

**Comment by ThePhD** [comment]
Fixed in latest!

**Comment by lone-wolf-akela** [comment]
> Fixed in latest!

Thanks! ^_^
