### ISSUE TITLE
Use lua_newuserdatauv instead of lua_newuserdata？

### ISSUE THREAD

**Issue by sniper00** [ThePhD/sol2#1047]
lua_newuserdatauv is more Efficiently

http://www.lua.org/manual/5.4/manual.html

lua_newuserdatauv

void *lua_newuserdatauv (lua_State *L, size_t size, int nuvalue);
This function creates and pushes on the stack a new full userdata, with nuvalue associated Lua values, called user values, plus an associated block of raw memory with size bytes. (The user values can be set and read with the functions lua_setiuservalue and lua_getiuservalue.)

The function returns the address of the block of memory. Lua ensures that this address is valid as long as the corresponding userdata is alive (see §2.5). Moreover, if the userdata is marked for finalization (see §2.5.3), its address is valid at least until the call to its finalizer.

**Comment by ThePhD** [comment]
I am not sure how it is more efficient. `lua_newuserdata` can be implemented as a macro on top of `lua_newuserdatauv` like so:

```
#define lua_newuserdata(L, sz) lua_newuserdatauv((L), (sz), 0)
```

Is there some magic here I'm missing?

**Comment by ThePhD** [comment]
Oh boy:

> For compatibility, the old names still work as macros assuming one single user value. Note, however, that userdata with zero user values are more efficient memory-wise.

Guess I need to `#ifdef` on Lua 5.4 and use `lua_newuserdatauv` instead.

**Comment by ThePhD** [comment]
We now use `lua_userdatauv` to save on space where possible.

**Comment by sagamusix** [comment]
It seems like this change breaks at least VS2019 builds: https://ci.appveyor.com/project/ThePhD/sol2/builds/35928891/job/5earl4a2o251mkvc

**Comment by ThePhD** [comment]
@sagamusix This was fixed in a different commit already: see #1050 !

**Comment by sagamusix** [comment]
Hmm, but I am not using boost, and the failed CI pipeline linked above is from the latest commit of this repository...

**Comment by ThePhD** [comment]
tfw I pushed to `main`, but not `develop` 🤦‍♀️

Sorry!

**Comment by sagamusix** [comment]
No worries :)
