### ISSUE TITLE
sol::no_constructor breaks usertypes

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#105]
Even though it's been a while since you implemented `sol::no_constructor` I've only had the chance to test it right now, and unfortunately it seems like it has a few issues.

First of all, it cannot be defined by itself, ie:

```cpp
state.new_usertype<SomeClass>("SomeClass",
    sol::no_constructor,
    ...
);
```

Instead, one has to prefix it with either a string value (or a `sol::call_constructor`) like so:

```cpp
state.new_usertype<SomeClass>("SomeClass",
    "new", sol::no_constructor,
    ...
);
```

This is a usability issue, and not that important. The important issue however is that using `sol::no_constructor` causes the usertype to be completely unusable.

In my test case, I defined a usetype called `SomeClass` with the function `TestFunc` and the property `test` (both returning the same value). I then instantiated an object of that class in C++-land and passed it to lua-land by doing `state["x"] = objPointer` (I also ensured that the object would not be destructed while lua was being executed). 

Whenever `sol::no_constructor` was present, calling the function or accessing the property had unexpected results and occurred in various errors such as `attempt to index nil value "TestFunc" on userdata`. However, after removing `sol::no_constructor` it functioned again as expected.

I should also note that I didn't experience the same issue by specifying `sol::constructors<>()` and that I tried this with both LuaJIT and Lua 5.3.

Thanks.

**Comment by ThePhD** [comment]
I'm looking at it now. Sorry for it breaking: I tested it and it didn't snap, maybe one of my recent changes screwed something up...
