### ISSUE TITLE
Call a different usertype constructor and keep new

### ISSUE THREAD

**Issue by rachelwaldon** [ThePhD/sol2#1051]
I am trying to create a class object and return a shared ptr to the object after calling the constructor. What is the best way to do this? So far this is what I have tried, using sol::call_constructor, but I would like to still use new in lua.

class:
```
class Dog {
   public:  
        Dog(const double& d) : data(d) {}  
        double data;  
};
```

My binding code:
```
lua.new_usertype<Dog>("Dog",
    sol::call_constructor,sol::factories([](const double& d) {return make_shared<Dog>(d);})
);
```

This allows me to do this in lua:
`dog = Dog(2.1)`

But I want to do this:
`dog = Dog:new(2.1)`

**Comment by ThePhD** [comment]
Just remove the `sol::call_constructor` bit, and it should work. If you want both, then you have to make a `sol::factories` and specify both!

```cpp
lua.new_usertype<Dog>("Dog",
    sol::call_constructor,sol::factories([](const double& d) {return make_shared<Dog>(d);}),
    "new", sol::factories([](const double& d) {return make_shared<Dog>(d);})
);
```

I think you might only want one, though, so just use:

```cpp
lua.new_usertype<Dog>("Dog",
    sol::factories([](const double& d) {return make_shared<Dog>(d);}),
   // rest of members....
);
```

**Comment by rachelwaldon** [comment]
Thanks for the help. I tried running both of your code samples with the code snippets I posted above, and I keep getting a sol runtime error:

what():  sol: runtime error: input.lua:1: sol: no matching function call takes this number of arguments and the specified types

I got this error when I tried to run this lua code:
`dog = Dog:new(2.3)`

**Comment by ThePhD** [comment]
Oh. It might be because when doing `Dog:new(...)`, the `:` (the colon) is passing the "self" argument that is the usertype table (`Dog`). Try with just a single period, that might work!

**Comment by rachelwaldon** [comment]
Thank you! It works with the dot notation. Is there any possible way to make this work with the colon syntax using new?

**Comment by ThePhD** [comment]
To be honest, I actually thought it already worked, but it seems like it only tolerates that when you let sol2 handle making the `new` for you with `sol::constructors`.... I need to test some things.

**Comment by rachelwaldon** [comment]
Any updates on this issue? Is there a possible work around or alternative for calling a different function for a constructor with sol::factories to work with :new?

**Comment by rachelwaldon** [comment]
I came up with a workaround for dealing with the self call problem. I was wondering do you think this is best practice or is there a better way?
```
lua.new_usertype<Dog>("Dog",
     "create", [](const double& in) {return make_shared<Dog>(in);}
);

lua.script(R" (
     function Dog.new(self,v)
          return self.create(v)
     end
)");

sol::table self = lua["Dog"];
```

**Comment by ThePhD** [comment]
Right, sorry, I think I fully understand what you're getting at.

When you use normal constructor syntax with `sol::constructors`, we take care of handling both the `Dog.new` and the `Dog:new` cases (dot and colon) for you. When you use a factory, you have to handle the syntax for both yourself. I added an example to make that clear: https://github.com/ThePhD/sol2/blob/develop/examples/source/usertype.constructors.cpp

Best of luck!
