### ISSUE TITLE
How to pass table as vector to a c++ function?

### ISSUE THREAD

**Issue by Domain** [ThePhD/sol2#1054]
I have a C++ function looks like this:
`void foo(const std::vector<int>& arr)
{
...
}`

I want to call it from lua script:
`foo({1, 2})`

But I get error:
> stack index 1, expected userdata, received table: value is not a valid userdata

**Comment by ThePhD** [comment]
If you ask for a reference -- `const` or non-`const` -- sol2 expects the data to be an actual, real `std::vector` type. If you want sol2 to automatically convert, take a `std::vector<int> arr` (notice no reference: by value!).

**Comment by ThePhD** [comment]
Otherwise, you need to make a wrapper function and bind that to sol2.

**Comment by Domain** [comment]
I just remove the reference, but still have the same error
`void foo(std::vector<int> arr) { ... }`

**Comment by Domain** [comment]
Thank you!
