### ISSUE TITLE
Testing if Nested Values Exist

### ISSUE THREAD

**Issue by SnapperTT** [ThePhD/sol2#1055]
G'day,

I'm calling a function 
```
mState[nameSpace][index][funcName]( args .... );
```
If the function does not exist things understandably explode. To verify that the function exists I use:

```
	bool funcExistsINs(const char * nameSpace, int index, const char * funcName) {
		sol::table t1 = mState[nameSpace];
		if (t1 == sol::lua_nil) return false;
		sol::table t2 = t1[index];
		if (t2 == sol::lua_nil) return false;
		if (t2[funcName] == sol::lua_nil) return false;
		return true;
		}
```
It does seem puzzling to me that I can call a function directly, but I cannot query if it exists or is valid.

Is there (and/or should there be) a way to call `mState[nameSpace][index][funcName] == sol::nil`?

Cheers

**Comment by ThePhD** [comment]
```cpp
sol::optional<sol::protected_function> maybe_func = mState[nameSpace][index][funcName];
if (maybe_func) {
     // yay
}
else {
     // boo
}
```

https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#tables

**Comment by ThePhD** [comment]
Though, as a feature: maybe we should add extra overhead to `operator==` for when someone does `== sol::(lua_)nil`, where we also check if it doesn't exist. It sort of blends the 2 states together, though...

**Comment by SnapperTT** [comment]
Cheers PhD, your first comment suits my use case perfectly.

I'll defer to your judgement as to mixing (== lua_nil) with (DNE). An explicit `.exists()` or making `.valid()` work with nested tables may be better.

**Comment by ThePhD** [comment]
There... should be a `.valid()` call on proxies. Was that not satisfactory?

**Comment by ThePhD** [comment]
E.g., this: https://sol2.readthedocs.io/en/latest/api/proxy.html?highlight=valid#operator-proxy-only-members
