### ISSUE TITLE
Typos In Settings Macros

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#1057]
There are two typos in the settings macros:

SOL_FF should be SOL_OFF
https://github.com/ThePhD/sol2/blob/c068aefbeddb3dd1f1fd38d42843ecb49a3b4cdb/include/sol/version.hpp#L196
https://github.com/ThePhD/sol2/blob/e108f8bbbff810cc1a68fbc42466ee9b2712afce/single/include/sol/forward.hpp#L202

_Sorry for the multiple edits, GitHub decided to auto-swallow enter presses for some reason and just submitted immediately while trying to edit the report._

**Comment by ThePhD** [comment]
Fixed from #1058
