### ISSUE TITLE
Crash on destroyed lua state in sol::coroutine after move assign

### ISSUE THREAD

**Issue by Mikella** [ThePhD/sol2#1060]
I've encountered a crash after using move-assign on a struct storing a sol::coroutine.  For context, in my project I am storing references to in-progress sol::coroutines (along with their thread, etc) in object pools for use in an ECS system where move-assign is used to remove/destroy components.

I've attached a trimmed down example program that reproduces the issue.  I had to force garbage collection to consistently reproduce this issue, otherwise it is infrequent.  I have found that commenting out the `if (detail::xmovable(lua_state(), r.lua_state())) {` block in basic_reference::move_assign and allowing the default implementation to run resolves this issue.  I'm not sure if this is an issue with the move_assign implementation or if I'm using sol incorrectly.

Thanks for the great library!

I am using Lua 5.4 and compiling with Visual Studio 2019.  I have included a project that compiles, but here is the relevant code snippet: 

```struct CoroutineStorage
{
	CoroutineStorage(sol::state& luaContext)
	{
		mLuaState = &luaContext;
		mThreadEnvironment = sol::environment(luaContext, sol::create, luaContext.globals());
		mThread = sol::thread::create(luaContext);
		sol::set_environment(mThreadEnvironment, mThread);
		sol::state_view luaThreadState = mThread.state();

		sol::optional<sol::table> actionTable = luaThreadState["aTable"];
		if (actionTable)
		{
			mThreadTick = actionTable.value()["Tick"];
		}
	}

	CoroutineStorage& operator=(CoroutineStorage&& r) & noexcept
	{
		mThreadTick = std::move(r.mThreadTick);
		mLuaState->collect_garbage();
		mThread = std::move(r.mThread);
		mLuaState->collect_garbage();
		mThreadEnvironment = std::move(r.mThreadEnvironment);
		mLuaState->collect_garbage();
		return *this;
	}

	CoroutineStorage(CoroutineStorage&& r) noexcept = default;

	sol::state* mLuaState;
	sol::environment mThreadEnvironment;
	sol::thread mThread;
	sol::coroutine mThreadTick;
};

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::coroutine);

	lua.script(R"(
		aTable = {}
		aTable["Tick"] = function()
			coroutine.yield()
		end
		)");

	std::vector<CoroutineStorage> luaCoroutines;

	luaCoroutines.emplace_back(lua);
	luaCoroutines.emplace_back(lua);

	// This mimics the erase behavior from an object pool as implemented by Entt - https://github.com/skypjack/entt/
	auto other = std::move(luaCoroutines.back());
	luaCoroutines[0] = std::move(other);
	luaCoroutines.pop_back();
}
```
[SolReport.zip](https://github.com/ThePhD/sol2/files/5503401/SolReport.zip)

**Comment by ThePhD** [comment]
This should be fixed now in latest. Sorry about the bug!
