### ISSUE TITLE
Visual Studio 2017 including problem

### ISSUE THREAD

**Issue by zbigniewcebula** [ThePhD/sol2#1068]
Hello, I want to use sol2 in my next project, unfortunately I can't find any reasonable way to include that.
Adding "Include Directories" to Project Properties does the "job" for #include, but rest of simple:
```	
#include <iostream>
#include <sol/sol.hpp> //stops being an error after adding to include directories
int main() {
	sol::state lua; //name followed by :: must be a namespace...
	lua.open_libraries(sol::lib::base);

	lua.script("print('bark bark bark!')");
	return 0;
}
```
Does not work because VS2017 doesn't see any namespace.
Trying to CTRL+Click on **sol.hpp** ends with _A definition for the symbol '<sol.hpp>' could not be located_.

**Comment by ThePhD** [comment]
So are these hard errors when you build, or just that Visual Studio stops working?

For what it's worth, sol2 is too large for VS2017 to process sanely. You have to turn on intellisense in the header.

**Comment by ThePhD** [comment]
If it is just "my features stop working", try this:

```cpp
#ifndef __INTELLISENSE__
#include <sol.hpp>
#endif // Intellisense blocker
```

This blocks Intellisense from the header and keeps it working, but you'll likely not be able to get other nice IDE features related to sol2.

**Comment by zbigniewcebula** [comment]
This gets pretty intense :D
(/c++17 is set)
![obraz](https://user-images.githubusercontent.com/6533930/99737474-abdac880-2ac8-11eb-9b0f-a63e83267368.png)

**Comment by ThePhD** [comment]
You can maybe get around this by not using the single header or upgrading to VS 2019. Sorry it's a pain!

**Comment by vdweller84** [comment]
Hi, can you please consider reopening this? Please keep in mind that some console SDKs don't support VS2019 and therefore we're pretty much stuck with VS2017 for some projects.

I originally opened [1362](https://github.com/ThePhD/sol2/issues/1362), I thought I had it under control, now I try to build on my laptop and not even the single header works.

Even if you think of some temporary workaround for this, please do let us know.

**Comment by ThePhD** [comment]
The workaround for this is going to be me rewriting a ton of the library so that it's not all crammed in a single header, things are compiled separately, and it's built properly so every single C++ file doesn't pay obscene costs of parsing all that code.

Which means I can't solve this directly right now, as I've got a metric crap ton on my plate to do. Sorry; it might be a long, long while, but it *is* on my radar.
