### ISSUE TITLE
UB in stack_core.hpp (applying non-zero offset to nullptr)

### ISSUE THREAD

**Issue by dpacbach** [ThePhD/sol2#1071]
Hello,

I recently tried turning on UBSan (Undefined Behavior Sanitizer) on my build that uses sol2, and at runtime it is giving me an exception:

```
../sol2/include/sol/stack_core.hpp:92:79: runtime error: applying non-zero offset 384 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../sol2/include/sol/stack_core.hpp:92:79 
```

The lines in question are:

```cpp
89  inline void align_one(std::size_t a, std::size_t s, void*& target_alignment) {
90      std::size_t space = (std::numeric_limits<std::size_t>::max)();
91      target_alignment = align(a, s, target_alignment, space);
92      target_alignment = static_cast<void*>(static_cast<char*>(target_alignment) + s);  // here!
93  }
```

and the `align_one` function appears to be called in some cases with `target_alignment == nullptr`.  This is undefined behavior because "the behavior of a program is not defined if it adds a non-zero offset (or in C, any offset) to a null pointer" (that quote was taken from the clang commit that added this check [here](https://reviews.llvm.org/rC374293)).

I'm not quite sure what that code is trying to do, but can you find a way to do the same thing with adding offsets to `nullptr`s?  Thanks

**Comment by ThePhD** [comment]
This should totally super 100% be fixed now, I promise!

**Comment by dpacbach** [comment]
@ThePhD Hey thanks for that -- I would like to test the fix, but unfortunately it's hard because when I upgrade my sol2 (which is at v3.2.1 at the moment) to master (or the latest version), I get hit with two other issues:

Issue #1070 breaks my build
Issue #1072 breaks my tests

Hopefully you'll be able to take a look at those (I am pretty sure that both of them are regressions that could have/should have been prevented with unit tests).
