### ISSUE TITLE
How to handle non-owning smart pointers?

### ISSUE THREAD

**Issue by SirLynix** [ThePhD/sol2#1074]
Hi,

I have a smart pointer type which doesn't own the object. It behaves like a regular pointer but automatically goes to nullptr when the object is destructed (and its value updates when it's moved).

The point of such a type is to allow Lua to keep a weak reference to the object and trigger an error if it's used when invalid.

Here's an example:
```lua
gamemode:On("playerdeath", function (gm, player)
	print(player:GetName() .. " died")
	timer.Sleep(gm:GetProperty("respawntime") * 1000)
	player:Respawn()
end)
```

Since the player may disconnect during the respawn time, respawning it should trigger an error, and allow to check if the handle is still valid:
```lua
gamemode:On("playerdeath", function (gm, player)
	print(player:GetName() .. " died")
	timer.Sleep(gm:GetProperty("respawntime") * 1000)
	-- Player can be invalid since we gave back the control to the application for a moment, check it again
	if (not player:IsValid()) then
		return
	end

	player:Respawn()
end)
```

I tried to specialize sol::unique_usertype_traits but as I understood (after a few crashes), it's meant for owning pointers as the is_null and get functions are only used when pushing the type.

Is there a way to handle non-owning smart pointers and keep binding class to sol easily?

Thank you

**Comment by Rochet2** [comment]
Seems like exactly what I was trying to do and needed this for: https://github.com/ThePhD/sol2/issues/1010

**Comment by ThePhD** [comment]
I think I'm going to make this available to all types, not just unique usertypes. This check can apply to any type, and I think that using a mix of usertype checking should be a-okay. The extension point will be named `sol_lua_check_access()`, and it will be strategically sprinkled before any function call involving that type. One question left to answer is if it should apply to both member functions AND free functions, e.g.:

```cpp
// just this?
struct checked_ptr {
     void foo_member(int arg);
}l
// maybe this?
void foo(const checked_ptr& self, int arg);
// but also this??
void foo_free(int arg1, const checked_ptr& self);
```

Current working idea is that all of these accesses get checked, as well as member variable get/set... but maybe that's too much?

**Comment by SirLynix** [comment]
I also think it should be checked on every access, that's what I did with a handmade solution.

**Comment by Smertig** [comment]
Perhaps, you shouldn't add extension point for **checking**, but something similar to `operator dot()` overloading?
I assume that it could work as follows:
```cpp
shared-ptr-like foo(weak-ptr-like player) {
  return player.lock(); // nullptr in lua will trigger lua error (or we can throw exception right here)
}

usertype["operator-dot-like"] = &foo;
```

```lua
local a = obj.a -- automatically transforms to `local a = foo(obj).a`
obj:bar(123) -- automatically transforms to `foo(obj):bar(123)`
```

**Comment by ThePhD** [comment]
Well, if you want operator dot semantics, you could override the `__index` metamethod and do your checks/throws then. It also wouldn't apply in all cases: what happens with:

```lua
cpp_func(123, obj)
```

? Is that access-checked with an "operator dot"-alike?

**Comment by Rochet2** [comment]
> I also think it should be checked on every access, that's what I did with a handmade solution.

This is what I was looking for in my issue as well. The main reason for me to have this ability is to make safety checks and limiting the safety only to one argument would somewhat defeat the purpose of the check.

**Comment by ThePhD** [comment]
A first draft of this has landed in latest. The following code does, presumably, what all of you would expect it to do:

```cpp
#define SOL_ALL_SAFETIES_ON 1
#define SOL_PRINT_ERRORS    1

#include <sol/sol.hpp>
#include <iostream>

template <typename Type, typename Deleter = std::default_delete<Type>>
class checked_ptr {
private:
	using pointer = Type*;
	pointer ptr;
	Deleter del;

public:
	checked_ptr() noexcept : checked_ptr(nullptr) {
	}
	checked_ptr(std::nullptr_t) noexcept : ptr(nullptr), del() {
	}
	checked_ptr(pointer ptr_) noexcept : ptr(ptr_), del() {
	}

	pointer get() const noexcept {
		return ptr;
	}

	void reset() noexcept {
		if (ptr != nullptr) {
			del(ptr);
			ptr = nullptr;
		}
	}
};

struct checked_class {
	int value = 4645;
};

namespace sol {
	template <>
	struct unique_usertype_traits<checked_ptr<checked_class>> {
		static checked_class* get(lua_State*, const checked_ptr<checked_class>& ptr) noexcept {
			return ptr.get();
		}

		static bool is_null(lua_State*, const checked_ptr<checked_class>& ptr) noexcept {
			return ptr.get() == nullptr;
		}
	};
} // namespace sol

void sol_lua_check_access(sol::types<checked_class>, lua_State* L, int index, sol::stack::record& tracking) {
	sol::optional<checked_ptr<checked_class>&> maybe_checked = sol::stack::check_get<checked_ptr<checked_class>&>(L, index, sol::no_panic, tracking);
	if (!maybe_checked.has_value()) {
		return;
	}
	checked_ptr<checked_class>& checked = *maybe_checked;
	if (checked.get() == nullptr) {
		// freak out in whatever way is appropriate, here
		throw std::runtime_error("You dun goofed");
	}
}

int main() {
	sol::state lua;

	lua["c"] = checked_ptr<checked_class>(new checked_class());
	lua["c_nil"] = checked_ptr<checked_class>();

	lua["f"] = [](checked_class cc) { std::cout << cc.value << std::endl; };

	sol::optional<sol::error> maybe_error = lua.safe_script("f(c)", sol::script_pass_on_error);
	if (maybe_error) {
		const sol::error& err = *maybe_error;
		std::cerr << "shit hit hte fan:\n" << err.what() << std::endl;
		return 1;
	}

	checked_ptr<checked_class>& c = lua["c"];
	c.reset();

	sol::optional<sol::error> should_error = lua.safe_script("f(c)", sol::script_pass_on_error);
	if (!should_error.has_value()) {
		std::cerr << "we did NOT get an error, despite there should being one!" << std::endl;
		return 1;
	}
	return 0;
}
```

This program should exit with code 0.

Part of this is also that `unique_usertype_traits` has been simplified as well. You don't need a `value = true` boolean anymore, and you don't need either `actual_type` or `type` if you have a special pointer class that follows either `unique_ptr` or `shared_ptr` in its template-shape.

"But if you don't need the defines anymore, why not move it out of that class entirely and just use cleaner, simpler free functions?"

Someone may still need to provide those typedefs, as well as the currently semi-secret `rebind_actual_type` mechanism that allows `shared_ptr` the ability to downcast from `shared_ptr<Derived>` to `shared_ptr<Base>` in class interfaces.

The documentation isn't updated because I'm overhauling the docs, which will hopefully be done by June if I don't die under a pile of C Standard Editing and other stuff.

Lemme know if it works for y'all.

**Comment by ThePhD** [comment]
I am going to add doing the documentation for this in a much more organized mega-issue for doc overhaul and version 4.
