### ISSUE TITLE
sol::overload Breaking sol::optional Usage

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#1075]
**Environment:**
  * Visual Studio 2019 - 16.8.2
  * C++ with /std:c++17 enabled.
  * sol2 latest. Commit: 38473d39fe3b2b91c07cbd2343942620b0def71f
  * LuaJIT via MoonJIT (Compiled with Lua 5.2 features enabled.)

**The Issue:**

While using sol::overload, I cannot seem to continue to use sol::optional parameters. They turn into expected/required parameters instead. If not using sol::overload to register the same functions with different names instead of overloading, they function as expected.

**Code Example:**

C++ setup code:
```cpp
// Registration of our test functions inside of a global table 'test.derp'..
auto test = this->m_LuaState[u8"test"].get_or_create<sol::table>();
auto derp = test[u8"derp"].get_or_create<sol::table>();

derp[u8"herp"] = sol::overload(
    // test.derp.herp('str', 'str', 'str');
    // test.derp.herp('str', 'str', 'str', 42);
    [this](sol::this_state s, const std::string_view& str1, const std::string_view& str2, const std::string_view& str3, sol::optional<uint32_t> flags) -> sol::object {
        printf_s("herp (1) called\r\n");
        return sol::make_object(s, sol::nil);
    },

    // test.derp.herp('str', 'str', function(r) end);
    // test.derp.herp('str', 'str', function(r) end, 42);
    [this](sol::this_state s, const std::string_view& str1, const std::string_view& str2, sol::function func, sol::optional<uint32_t> flags) -> sol::object {
        printf_s("herp (2) called\r\n");
        return sol::make_object(s, sol::nil);
    });
```

As for the Lua script to test the cases of these:

```lua
-- invalid [no matching function call takes this number of arguments and the specified type]
test.derp.herp('str1', 'str2', 'str3');

-- valid
test.derp.herp('str1', 'str2', 'str3', 42);


-- invalid [no matching function call takes this number of arguments and the specified type]
test.derp.herp('str1', 'str2', function(r) end);

-- valid
test.derp.herp('str1', 'str2', function(r) end, 42);
```

As mentioned, if these are broken into two separate function registrations instead of overloading (ie. herp1 and herp2) then `sol::optional` is respected and works fine. Just seems to be a problem when used inside of `sol::overload(...)`. I didn't see a limitation in the docs regarding this kind of setup, so I assume this should work.

**Comment by atom0s** [comment]
As a means to prove/test further, here is an additional overload that can be added as the fallback, with argument dumping to show it's seeing the proper argument types that should connect to the two overloads, but fails to.

```cpp
// test.derp.herp(...) fallback
[this](sol::this_state s, const sol::variadic_args args) -> sol::object {
    printf_s("herp (fallback) called\r\n");

    std::stringstream str;
    for (std::size_t x = 0; x < args.size(); x++)
    {
        str << sol::type_name(s, args.get_type(x));
        str << ", ";
    }
    printf_s("  > %s\r\n\r\n", str.str().c_str());

    return sol::make_object(s, sol::nil);
}
```

Running with this added, executing the same Lua as above yields the output:
```
herp (fallback) called
  > string, string, string,

herp (1) called
herp (fallback) called
  > string, string, function,

herp (2) called
```

**Comment by ThePhD** [comment]
This is now fixed. It costs some general performance for very large overload sets but anything with "fuzzy" counts (such as `variadic_args` or `optional` will now be properly handled.

**Comment by atom0s** [comment]
Thanks can confirm looks to be good on my end now too. :) 

Noticed a small compile bug that I made a PR for as well. 
https://github.com/ThePhD/sol2/pull/1091
