### ISSUE TITLE
How to iterate functions in the order of their definition in source file?

### ISSUE THREAD

**Issue by piotr-piatkowski** [ThePhD/sol2#1076]
This is just a question - I have a bunch of scripts that are defining some processing function and list of unit tests for them. So after loading script with `lua_view_.safe_script_file(...)` I'm finding all functions prefixed with `test_` with the following code:

```
        vector<pair<string, sol::protected_function>> functions;
        for (auto &kv: lua_view_) {
            if(kv.second.get_type() == sol::type::function && kv.first.as<string>().find("test_", 0) == 0) {
                functions.push_back(pair(kv.first.as<string>(), kv.second));
            }
        }
```
Now, the problem is that they come in random order - which, I believe, is because of how LUA iterates tables. So the question is - is there any way to iterate functions in the order they were defined in the source file?

**Comment by ThePhD** [comment]
Unfortunately, no! This is an intrinsic Lua limitation. The folks at Factorio added some deterministic ways of doing this by patching Lua directly, which is compleeetely outside of my jurisdiction!
