### ISSUE TITLE
sol::environment::set_on has different behaviour with different lua versions

### ISSUE THREAD

**Issue by petrmikheev** [ThePhD/sol2#1079]
**Environment**

sol2 latest, commit 76065527f73542e8433d3997d74c7afb597bef79

```
Ubuntu 20.04.1 LTS
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Package: libluajit-5.1-dev        Version: 2.1.0~beta3+dfsg-5.1build1
Package: lua5.3                   Version: 5.3.3-1.1ubuntu2
```

**Code**

```c++
#include <sol/sol.hpp>

int main() {
  sol::state lua;
  sol::function genFn = lua.load("return function() return x end");

  sol::environment env1(lua, sol::create);
  env1["x"] = 1;

  sol::environment env2(lua, sol::create);
  env2["x"] = 2;

  env1.set_on(genFn);
  sol::function get1 = genFn();

  env2.set_on(genFn);
  sol::function get2 = genFn();

  std::cout << "get1() -> " << (int)get1() << std::endl;
  std::cout << "get2() -> " << (int)get2() << std::endl;

  return 0;
}
```

**Use case**

I need to run several instances of the same script in separate sandboxes. For performance reasons I want to load it only once and then change the environment before every call.

With luajit it works as desired (i.e. get1() -> 1, get2() -> 2).
In case of lua5.3 the environment applies not only to genFn, but to all its *previous* outputs as well.

**Result with luajit**

```
$ g++ -o test test.cpp -Isol2/include -I/usr/include/luajit-2.1 -lluajit-5.1 -std=c++17
$ ./test 
get1() -> 1
get2() -> 2
```

**Result with lua5.3**
```
$ g++ -o test test.cpp -Isol2/include -I/usr/include/lua5.3 -llua5.3 -std=c++17
$ ./test
get1() -> 2
get2() -> 2
```

**Questions**

1. Is it defined and expected behaviour for luajit? Can I rely that it will not change in future versions of sol2?
2. Is it expected behaviour for lua5.3? Or just a bug?
3. Is there any workaround how to make it work with lua5.3 the same as it works with luajit?

**Comment by ThePhD** [comment]
The environment can either be applied when executing the code or when compiling the original snippet. You can argue for both, and they likely fall out this way due to implementation specifics.

I don't know which behavior is _better_, per se. And I can't influence it one way or the other, I don't think. Each implementation handles their environments differently, and looking at the manual they're not incredibly specific about cases like this.

**Comment by ThePhD** [comment]
This exposes Lua implementation details that I unfortunately cannot control. Both functions refer to `x`, and it is unclear if the function call should do `_ENV.x` or if it should bake `_ENV` into the load call.

The Lua manual STRONGLY suggests that the first suggestion -- doing `_ENV.x` at the time the call is made, not when the function is generated -- would favor the second approach over the first approach. You are better off explicitly attaching the environment to (`genFn` AND `get1`), or (`genFn` AND `get2`), both when you do the generation AND when you call the function.

**Comment by petrmikheev** [comment]
> You are better off explicitly attaching the environment to (genFn AND get1), or (genFn AND get2), both when you do the generation AND when you call the function.

The problem was that any attempt to change the environment of `get2` also changes the environment of previously created `get1`. I.e. with lua 5.3 if both `get1` and `get2` are produced by a common `genFn`, they are always in one environment and can not be separated, no matter how many times a call environment::set_on.

I think the proper solution for my use case is to cache `genFn` as a bytecode:

```c++
auto genFn = lua.load("return function() return x end").get<sol::function>().dump();
sol::function get1 = lua.script(genFn);
sol::function get2 = lua.script(genFn);
```
