### ISSUE TITLE
Writing to property fails if class isn't copyable.

### ISSUE THREAD

**Issue by billw2012** [ThePhD/sol2#108]
Not sure if this is expected, but I don't see why it would be the case. I'm obviously not trying to copy the whole class just assign to a property.
Error: [string "..."]:3: sol: cannot write to this type: copy assignment/constructor not available

    void uncopyable_class_test()
    {
    	using namespace sol;
    
    	struct NoCopy
    	{
    		int get() const { return _you_can_copy_me; }
    		void set(int val) { _you_can_copy_me = val; }
    
    		int _you_can_copy_me;
    		std::mutex _haha_you_cant_copy_me;
    	};
    
    	state lua;
    	lua.new_usertype<NoCopy>("NoCopy", "val", property(&NoCopy::get, &NoCopy::set));
    
    	lua.script(R"__(
    nocopy = NoCopy.new()
    nocopy.val = 5
    			   )__");
    }

**Comment by ThePhD** [comment]
Looks like a bug.

**Comment by nabijaczleweli** [comment]
can confirm am bug

**Comment by ThePhD** [comment]
I'm having a hard time testing this because VC++ strangles both the copy and move constructor when `std::mutex` is a member. When I test by just having a type that I explicitly make noncopyable / movable, it works (with the recent tests I just added in `test_usertypes.cpp`).

I'm... thinking this is more or less okay now. I'll revisit it if you still have problems.

**Comment by ronald-reagan** [comment]
Hey. I'm currently having this exact issue with my own class. The test code given by the original asker throws the error for me, the error is only thrown when attempting to set the variable, reading from it is fine.
The error is solved for me as soon as I give my class a copy assignment operator,
`Foo& operator=(const Foo&) { return *this; }`
Alike OP, what the property returns / takes as an argument don't influence the output.

Thanks for your continued help.

**Comment by ThePhD** [comment]
I added a test for this specific case with OP's code. If this next commit passes all the tests, I'm going to drop a formal release for this and everything else I've worked on.

**Comment by ThePhD** [comment]
Confirmed fixed, release here: https://github.com/ThePhD/sol2/releases/tag/v2.8.0
