### ISSUE TITLE
Storing a parameter object stores its pointer

### ISSUE THREAD

**Issue by SirLynix** [ThePhD/sol2#1080]
Hi,

I was trying to debug a code in my game (using sol3):
```lua
gamemode:OnAsync("playerdeath", function (self, player, attacker)
	timer.Sleep(self:GetProperty("respawntime") * 1000) -- does a coroutine.yield and schedule a coroutine.resume using a timer
	self:SpawnPlayer(player)
end)
```

`player` is a `ObjectHandle<Player>` which is a non-owning smart pointer (when the object gets deleted, it gets invalid, kinda like a weak_ptr), so when I call a player function I have a check which triggers a Lua error if it's not valid anymore, etc.

But here, it seems like it's not the object that is passed but a pointer to it, which becomes invalid if the Lua object lives longer than the C++ object, which is the case here due to the coroutine, and thus when checking the ObjectHandle the app crashes because it's a dangling pointer.

I managed to reproduce this in this small example:
https://godbolt.org/z/aG3qax

Notice the output:
```
Foo: 0x7ffed333d6ef
sol.Foo*
Print: 0x7ffed333d6ef
~Foo: 0x7ffed333d6ef
Print: 0x7ffed333d6ef
```

Print gets called after the object destruction via a dangling pointer.
I printed the internal sol metatable which shows it's a pointer: `sol.Foo*`

But when replacing
```cpp
		Foo m;
		storeFoo(m);
```

by

```cpp
		storeFoo(Foo{});
```

the metatable becomes `sol.Foo` and a true object is stored, changing the output to:
```
Foo: 0x7ffcedddfb6f
Foo: 0x7ffcedddfc5f
sol.Foo
Print: 0x1086ea0
~Foo: 0x7ffcedddfc5f
~Foo: 0x7ffcedddfb6f
Print: 0x1086ea0
~Foo: 0x1086ea0
```
[godbolt](https://godbolt.org/z/Yffz4o)

Which shows the object is copied as I expected it to be to Lua.

So my question is: what am I doing wrong here? I have some functions between the object creation and the sol3 call which is why I have a reference passed to sol3. How can I prevent it to make a pointer out of my object?

Thanks

**Comment by Smertig** [comment]
Try to use `storeFoo(std::move(m));`. It helps in my case.

**Comment by SirLynix** [comment]
> Try to use `storeFoo(std::move(m));`. It helps in my case.

It does indeed work with a move, but in my case I cannot do such a thing, the problem is that I have a function that calls multiple Lua callbacks with the same parameters, moving would break with more than one callback.

**Comment by Smertig** [comment]
You can also make a copy manually; `storeFoo(ObjectHandle<Player>(m))`.
I know, that it's just a workaround. I made a wrapper in my project that accepts all arguments by value and moves them to coroutine (to make sure there are no dangling pointers).

However, I would also like to know how to handle this case adequately.

**Comment by SirLynix** [comment]
Since my dispatching function is template that complicates things a bit but it's doable. However I find it a bit weird that creating a pointer to an object is the default way sol handles this. I would have though of a `sol::ref` / reference_wrapper thing or something about this. So yeah, same as you, waiting to see where I'm misusing sol.

**Comment by ThePhD** [comment]
In general, calls to sol2 function types do not aggressively copy members. This is done for performance reasons: we explain that in the notes about functions:

> All arguments are forwarded. Unlike get/set/operator[] on sol::state or sol::table, **value semantics are not used here**.
> ...
> — https://sol2.readthedocs.io/en/latest/functions.html#functions-and-argument-passing

"How do I get around this behavior?" Hard-move or hard-copy. For the `ObjectHandle<Player>` case, you need to explicitly make a copy, or explicitly move it into that function call.

**Comment by SirLynix** [comment]
Okay, this is a bit counter-intuitive in my opinion, an explicit `sol::move` or `sol::forward` would have been more C++-like.

Would it be possible to have a sol specialization to disable this behavior for certain types?

**Comment by ThePhD** [comment]
I can add a trait to specialize to get around it and document it. It'll probably be called `sol::is_push_value_semantic<T>` or something wordy like that. Or maybe it'll be a customization point like all the others...? .... No, I think the overridable boolean-esque trait is probably the best....

It's counter-intuitive in a purely C++ perspective. It's exactly intuitive for a Lua perspective. It depends on whether or not you value the fact that you're calling something based on Lua and want its semantics, or you're thinking primarily in Lua and you want its reference semantics. We chose the Lua semantics but an escape hatch is certainly needed.

**Comment by SirLynix** [comment]
Another cool way of doing that would be a `sol::pass_as_value(t)` function or so. I think it would be great to have it as a part of sol as maybe it can do some optimizations that we couldn't outside of it.

For example, if I were to implement it, I would make a function that returns a `std::remove_reference_t<T>` in order to copy it, plus handle the fact the object can't be copied and such to prevent some errors. But sol does know some types will not be referenced (like std::string for example).

**Comment by ThePhD** [comment]
The compile-time switch is documented here: https://sol2.readthedocs.io/en/latest/safety.html

I'm not sure why you'd want a specific sol2 feature for this `the_type{an_object_of_the_type}` forces a copy and then moves it in. The only thing you'd miss here is a bit of performance from having to copy, and then move in the temporary, rather than just a single copy.

**Comment by ThePhD** [comment]
(You can force a copy with a `const_cast<the_type&>(an_object_of_the_type);` too.

**Comment by SirLynix** [comment]
My point is that sol3 knows some type won't be passed as references to Lua and I (as a user) don't. For example a `std::string` will not be passed as a reference to lua by sol (because it makes no sense). If I code something to force a copy of an object then I will make an useless copy of a string.  
Of course the solution could be "then don't use it on a string", but there are other types that sol knows can be safely passed as values without making a copy and others that don't (std::string being an example, but I suppose every sol::object and such is safe as well). Also I'm in the case where I'm passing variadic parameters to a sol::protected_function, so I'd have to use it on every parameter (and excludes some of them myself).

My point is just that this is looking like I'd have to look at sol3 internals to know which type I don't have to copy, which is why I think it would be better for sol to have this forward function itself.
Plus of course, when sol3 is updated, it could break/be incomplete.

> (You can force a copy with a `const_cast<the_type&>(an_object_of_the_type);` too. (With no loss of performance at all.)

This kind of ugly hack that depends on sol internals is part of the reason I think this should be a sol3 function (no offense 😄 )

**Comment by ThePhD** [comment]
`pass_as_value` should be in latest now. I think.

**Comment by SirLynix** [comment]
Thanks a lot!
