### ISSUE TITLE
'redefinition of 'fx_traits<R(Args...)>noexcept, false>' error using sol2

### ISSUE THREAD

**Issue by xubury** [ThePhD/sol2#1083]
Hi, I am trying to use sol2. But I keep getting this `redefinition of 'fx_traits<R(Args...)>noexcept, false>` error even with a single sol2 header.
Any idea how to solve it?
![20201202102745](https://user-images.githubusercontent.com/46261364/100820395-11479580-3489-11eb-9707-58ba35e7859b.jpg)

**Comment by xubury** [comment]
my bad, it seems it's only a clangd intellisense error. It compile just fine.

**Comment by ThePhD** [comment]
Ah, alright. Sorry; sol2 really does trip up intellisense in a lot of places. Thanks for using sol2 though!
