### ISSUE TITLE
How to own a Lua callback properly?

### ISSUE THREAD

**Issue by xubury** [ThePhD/sol2#1085]
Great project! But I ran into some problems here.
I wanted to store a lua callback. But when I do something like the code sinppet I get a segmentation fault.
I think what happened is the `foo` object's `OnFinished` get destructed by `sol::state lua` . So `OnFinished` become a dangling pointer.
One workaround I do is put `OnFinished = nullptr;` in Foo's destructor. But I thinks it is not so intuitive. Can there be another solution?
```
#include <sol/sol.hpp>
#include <iostream>

struct Foo
{
    using FuncType = std::function<void()>;
    FuncType OnFinished;
};

int main()
{
    Foo foo;
    {
        sol::state lua;
        lua.open_libraries();
    
        lua.set_function("C_SetCallBack", [&foo](Foo::FuncType func){
            foo.OnFinished = std::move(func);
        });
        lua.script(R"(
        print_test = function ()
            print("test")
        end
        C_SetCallBack(print_test)
        )"); 
    }
}
```
https://godbolt.org/z/enPxse

**Comment by ThePhD** [comment]
You have to move the `sol::state` up one scope level to prevent ownership problems like this. No lua object type in C++ for sol2 can exist without the state right now. (I am working on a suite of "stateless" types that would allow someone to essentially remove the strong ownership model altogether, e.g. `stateless_function` as well as `function_view`.)

If you don't/can't do that, then you need to manually destroy / delete the callback.

**Comment by ThePhD** [comment]
I'm gonna fold this feature request into another issue request where I'm tracking some of this stuff too in relation to coroutine changes #1061.
