### ISSUE TITLE
Missing luaopen_bit32 with lua 5.4

### ISSUE THREAD

**Issue by rcharron** [ThePhD/sol2#1086]
Hello, 
I just upgraded fedora to version 33 and got a problem with sol.
Compiler complains about nonexistent luaopen_bit32. From what I see, it's really missing in /usr/include/lualib.h
Version of lua is 5.4.1, version of sol is v3.2.2

Just including <sol/sol.hpp> should reproduce the bug.

I guess the #ifdef macro should be corrected but I don't know how.

My fix was to comment the line about bit32, but it's not a good solution. 
BTW: thanks for the work, sol is awesome  and so easy to use :)

**Comment by atom0s** [comment]
Looks like Lua 5.3 moved from the bits lib to just having actual operators (finally). 

https://www.lua.org/manual/5.3/readme.html#changes
https://www.lua.org/manual/5.3/manual.html#3.4.2

Most likely this is being triggered by your code/project defining `LUA_COMPAT_5_2` somewhere as the other two conditions are unlikely with Lua 5.4.x. 

```cpp
#elif (SOL_LUA_VESION_I_ == 502) || defined(LUA_COMPAT_BITLIB) || defined(LUA_COMPAT_5_2)
```
SOL_LUA_VESION_I_ should be getting set to SOL_LUA_VERSION which should be set to LUA_VERSION_NUM given that Lua 5.4.x will be 504.

LUA_COMPAT_BITLIB shouldn't exist/be set for 5.4.x as it no longer exists. (Also be sure your code/project isn't setting it manually.)

**Comment by rcharron** [comment]
In fact in /usr/include/luaconf-x86_64.h I see
```
#define LUA_COMPAT_5_1
#define LUA_COMPAT_5_2
```

For the rest you are right SOL_LUA_VESION_I_ is 504 and LUA_COMPAT_BITLIB doesn't exist

I don't think I should un-define LUA_COMPAT_5_2 by hand.

**Comment by atom0s** [comment]
That sounds like a possible bug with the package of Lua you are using and being misconfigured. The official 5.4.2 release of Lua does not define either of those in its included luaconf.h. Just one for 5_3 instead. `luaconf-x86_64.h` is also not a stock file part of Lua's package, so it sounds like a specifically maintained configuration setup for that given package. 

luaconf.h is user-editable though from the main release, or can be configured with compiler switches. At the bottom of the file there is a comment/space made for user-specific edits. You can go into that part of the file and add:

```cpp
#undef LUA_COMPAT_5_1
#undef LUA_COMPAT_5_2
```

Do you have a link to the exact package of Lua you use? Would be interested to see what they are doing with those compat flags when the official build of 5.4.x does not have them.

**Comment by ThePhD** [comment]
Why are they defining that but not providing the compatibility...?

That's pretty silly. But, I'll just.... scope the check down when it's not Lua 5.4. Here's to hoping we don't break anyone...

**Comment by rcharron** [comment]
Sorry for late reply
I just checked where this file `luaconf-x86_64.h` comes from. It seems to be the official package of Fedora (33).
When I ask the list of files installed `dnf repoquery -l lua-devel-5.4.2-1.fc33.x86_64`, the file is listed. 
Maybe it could be useful to see if people with other linux versions have this problem ?
