### ISSUE TITLE
Set working directory

### ISSUE THREAD

**Issue by yamashi** [ThePhD/sol2#1092]
Hello,

I am trying to find a way to set the work directory of the lua state so that calling `do_file` always looks in that specific directory and not the location of the executable.

What is the proper way of handling this?

Best,
Max

**Comment by ThePhD** [comment]
The working directory is the C working directory. That is, it is the working directory of the program. You need to use platform APIs to change this: sol2 doesn't have this. The C++ standard with `std::filesystem` does: https://en.cppreference.com/w/cpp/filesystem/current_path

Be warned that it changes it for the whole directory. There is no "changing it for the Lua State".
