### ISSUE TITLE
Retaining a table

### ISSUE THREAD

**Issue by 5ladimir** [ThePhD/sol2#1093]
Hi, 

So, finally, the solution was:

class Foo
{
	// sol::table m_table;
	sol::**main_table** m_table;  // Now the table referenced "properly", at least faults are rare
};

...
m_table = GetTableFromSomewhere();

Looking up the source, the difference is `basic_reference<false>` vs `basic_reference<true>`. Still it is vague. It would be nice to have docs about sol::table, sol::main_table, sol::stack_table etc

Vladimir

_Originally posted by @5ladimir in https://github.com/ThePhD/sol2/issues/994#issuecomment-749748956_

**Comment by ThePhD** [comment]
Yeah, I have a lot of docs to re-add.

But I'm also working on an entirely new documentation system altogether. (... Okay, it won't be so different: the same rST source, just placed inside a different generator with some new tools to parse the code and tie the 2 together a little better.)
