### ISSUE TITLE
Accessing globals table via raw_get segfaults

### ISSUE THREAD

**Issue by doubleday** [ThePhD/sol2#1095]
I hoped to be able to bypass meta functions on `_G` via `raw_get` from the C++ side but it always segfaulted.

Maybe it is not supposed to be used that way ...

I reproduced my issue with a minimal test here:

https://github.com/doubleday/sol2/commit/28530f9e35b4f58c851cb700ccabbc9a08e5a9bd
```cpp
lua["testval"] = "testval";
REQUIRE(lua.globals().get<std::string>("testval") == "testval");
REQUIRE(lua.globals().raw_get<std::string>("testval") == "testval");
```

Run test:

```
Test project .../sol2/build
    Start 1: runtime_tests
1/5 Test #1: runtime_tests ....................***Exception: SegFault  1.16 sec
    Start 2: compile_tests
2/5 Test #2: compile_tests ....................   Passed    0.00 sec
    Start 3: config_function_pointers_tests
3/5 Test #3: config_function_pointers_tests ...   Passed    0.00 sec
    Start 4: regression_1011_tests
4/5 Test #4: regression_1011_tests ............   Passed    0.01 sec
    Start 5: regression_tests
5/5 Test #5: regression_tests .................   Passed    0.00 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =   1.19 sec

The following tests FAILED:
	  1 - runtime_tests (SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by ThePhD** [comment]
There was a lot of tenuously duplicated logic for the sake of refusing to push the table if it was global and there were shortcut APIs that enabled additional speed. We folded that logic down into one consistent place (`stack_field.hpp`) and now everything uses it and there's no more derps like this.

Check latest; thanks for reporting!
