### ISSUE TITLE
insert functions in table with not bool return type

### ISSUE THREAD

**Issue by sr-tream** [ThePhD/sol2#1096]
Example 1:
```cpp
lua["test"] = lua.create_table_with( "value", []{ return 3.14159f; } );
```
```lua
print( test.value() )
```
Output: true

Example 2:
```cpp
float test_value(){
    return 3.14159f;
}
// ...
lua["test"] = lua.create_table_with( "value", test_value );
```
```lua
print( test.value() )
```
Output: true

Example 3:
```cpp
lua["test"] = lua.create_table_with( "value", []() -> float { return 0.0f; } );
```
```lua
print( test.value() )
```
Output: false

It work correctly without table:
```cpp
lua["test_value"] = [] { return 3.14159f; };
```
```lua
print( test_value() )
```
Output: 3.14159

**Comment by ThePhD** [comment]
Well, this absolutely shouldn't be happening. Let me dive in to see what's going on...

**Comment by ThePhD** [comment]
Everything works for me. What version of sol2 are you using? Maybe try the latest branch? What compiler, etc...

**Comment by sr-tream** [comment]
> What version of sol2 are you using
master branch
> What compiler
MinGW 10.1

**Comment by ThePhD** [comment]
There is no `master` branch. Do you mean `develop`, or are you using the (out of date) `main` branch?

**Comment by ThePhD** [comment]
To be clear, I am using the latest `develop` and using this as a test:

```cpp
sol::state lua;
lua.open_libraries(sol::lib::base);

lua["test0"] = lua.create_table_with("value", [] { return constant_float_v; });
lua["test1"] = lua.create_table_with("value", [] { return constant_float_v; });
lua["test2"] = lua.create_table_with("value", [&] { return constant_float_v; });
lua["test3"] = lua.create_table_with("value", test_value);
lua["test4"] = lua.create_table_with("value", &test_value);
lua["test5"] = sol::create;
lua["test6"] = sol::create;
lua["test7"] = sol::create;
lua["test5"]["value"] = [] { return constant_float_v; };
lua["test6"]["value"] = [] { return constant_float_v; };
lua["test7"]["value"] = [&] { return constant_float_v; };
```

It works for me when I go into each of these tables and call `testNUMBER.value()`.

**Comment by ThePhD** [comment]
(I am using MinGW 10.2.0, on Windows 10, if that helps at all. I tested both x86 and x64.)

**Comment by ThePhD** [comment]
(I'm going to mark this one as fixed since I can't reproduce this on any machine/compiler combination. If you find something that changes, please let me know. For what it's worth, these exact test cases are now included as part of sol2's mini-regression testing suite, to make sure I don't accidentally break it in the future: https://github.com/ThePhD/sol2/blob/develop/tests/regression_tests/simple/source/1096%20-%20functions%20binding%20wrong.cpp#L15)

**Comment by sr-tream** [comment]
> There is no master branch
Sorry, I'm using default branch - develop

> It works for me when I go into each of these tables and call testNUMBER.value()
I'm took lua51.dll from other project, not from lua.org. May be it reason of my problem

Sorry for the time taken away
