### ISSUE TITLE
Calling a method wrapping the variable in parenthesis

### ISSUE THREAD

**Issue by raphasampaio** [ThePhD/sol2#1099]
Hello all, happy new year!
I'm getting an error when I wrap my variable in a parenthesis.
I don't know if I forgot to set an operator or this is the expected behavior. When I call my method straightly (`a:method()`), it works but doesn't work if I wrap it in parenthesis (`(a):method()`). 

```
#define SOL_ALL_SAFETIES_ON 1

#include <sol/sol.hpp>

class MyClass {
private:
    int* expression;

public:
    MyClass() : expression(new int[1]) {}
    MyClass(int* expression) : expression(expression) {}

    MyClass(const MyClass& other) : expression(other.expression) {}
    MyClass(MyClass&& other) : expression(other.expression) {}

    MyClass& operator=(const MyClass& other) { this->expression = other.expression; return *this; }
    MyClass& operator=(MyClass&& other) { this->expression = other.expression; return *this; }

    MyClass method() { return MyClass(this->expression); }
};


int main(int argc, char** argv) {
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.new_usertype<MyClass>("MyClass",
        sol::constructors<MyClass()>(),
        "method", &MyClass::method
    );

    lua.script(R"(
        a = MyClass.new()
        a:method() -- WORKS

        b = (a)
        b:method() -- WORKS

        (a):method() -- ERROR
    )");

    return 0;
}
```

This is a simplified example; in my application, I can do several operations with the class, for example, `(a + a): method()`. I'm using Visual Studio 2019 (v16.7.2), lua 5.4.2, and sol2 v3.2.3. The error I get is the following:

> [sol3] An error occurred and has been passed to an error handler: sol: runtime error: [string "..."]:6: attempt to call a sol.MyClass value
> stack traceback:
>         [string "..."]:6: in main chunk

**Comment by ThePhD** [comment]
```
        b = (a)
        b:method() -- WORKS

        (a):method() -- ERROR
```

I am willing to bet one (1) WHOLE dollar that your problem is Lua is parsing this as `b:method()(a):method()`.

**Comment by atom0s** [comment]
You can overload the function call operator to make it work like this:

```cpp
MyClass& operator()() { return *this; }
```

**Comment by ThePhD** [comment]
So, like. There's nothing I can do for you, here; this is a Lua problem. Whitespace is insignificant and it's reading that as a function call, not a parenthesized expression.

You need a local variable store or something to break it up. Or maybe Lua allows `;` as a statement separator: I don't know. In either case, this is not something sol2 can solve, and I wouldn't recommend @atom0s's solution because, while it gets the job done, it's misleading both yourself and Lua using a syntax that's not really necessary.

Sorry!!

**Comment by raphasampaio** [comment]
Thank you, guys; I got the semicolon solution
