### ISSUE TITLE
Usertype: Breaking Change for Speeeeeed

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#110]
So, nearly done with this refactor. And things are speedier, and generally. PROBLEM: `usertype<T>` is going to have to be deprecated for what will essentially become `usertype<T, Tuple>`, where `Tuple` is all of the functions and member variables and properties passed by the user during creation.

This makes it so `Sol2` is about to eat a breaking change, and will likely make the big frownies since we're a bit too far along and this is a bit too user-facing of a class to just change it and quietly expect everyone to come along.

The good news is, people who use `new_usertype<T>` function will be basically immune to this change. Older framework users from Sol 1.0 who wanted to "customize" usertypes by instantiating it first and then passing it through (a small margin) of things that were previously unusable in `new_usertype<T>` like a special constructor type won't be able to play ball because `usertype<T>` is gonna not exist anymore. :v

`Sol 3.0` milestone, here we come...? I can't justify doing this any other way because this cuts out the virtual function calls nearly entirely and the speed boost is not negligible, bringing us about as close as we can get to Macro Macro Funland libraries like OOLua, Luwra, and others. I problematically do not wish to support "older versions" of sol, because I am an Bleeding-Edgelord kind of developer.

Help.

**Comment by Nava2** [comment]
Seems reasonable, but you should probably support the most recent previous version too with some of the easy updates.

**Comment by ThePhD** [comment]
Ooh, idea. I can use erased storage to keep the `usertype<T>` type, instantiate the new `usertype_metatable<T, Tuple>` type on the inside, and then just forward the push function to the type-erased version that will register the faster, better `usertype_metatable<T, Tuple>` bits internally.

This will prevent deprecation of the old interface being a problem, and will allow me to use the new bits for everyone without maintaining 2 interfaces.
