### ISSUE TITLE
Latest Develop Branch No Longer Compiles Successfully (VS2019)

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#1104]
**sol version:** 68fd0c0166ffda2bd2a0293ce9adcaf8f36f9382
**Lua version:** https://github.com/AshitaXI/moonjit
**Compiler:** Visual Studio 2019 16.8.3 (C++17 enabled.)

Updating to the latest upstream has completely broken compiling on my setup. Previous commits were fine.

sol is being used/compiled with:

```cpp
#pragma warning(push)
#pragma warning(disable : 26439) // This kind of function may not throw. Declare it 'noexcept'.
#pragma warning(disable : 26495) // Variable uninitialized; always initialize a member variable.
#pragma warning(disable : 26812) // The enum is unscoped. Prefer 'enum class' over 'enum'.
#pragma warning(disable : 26819) // Unannotated fallthrough between switch labels.

#define SOL_ALL_SAFETIES_ON 1
#define SOL_EXCEPTIONS_ALWAYS_UNSAFE 0
#define SOL_EXCEPTIONS_SAFE_PROPAGATION 1
#define SOL_NO_RTTI 1

#pragma comment(lib, "lua51.lib")
#include <sol/sol.hpp>

#pragma warning(pop)
```

Nothing else in the project has changed and was working fully fine before the latest commit. 
The errors (5610 of them now) are all template related things.
 I'd guess a bad/mismatched `#define / #ifdef / #endif` block somewhere.

---
Edit:

Stepping through the recent commits since the last time I updated; the one in question causing the break is: b9115623b248fd967da9e26d70e08bae174d0745

Soon as I fetch and merge to this, it dies.

**Comment by atom0s** [comment]
Found the error. Would be due to: `include/sol/stack_field.hpp`
https://github.com/ThePhD/sol2/blob/b9115623b248fd967da9e26d70e08bae174d0745/include/sol/stack_field.hpp#L60

There is no actual semi-colon happening if the conditions are not met.

Fix:
```cpp
#if SOL_LUA_VESION_I_ >= 502
			|| (!global && raw && (std::is_pointer_v<T> && std::is_void_v<std::remove_pointer_t<T>>))
#endif // void pointer keys 5.2 or better
			;
```

**Comment by ThePhD** [comment]
Fixed in latest. https://github.com/ThePhD/sol2/commit/e892aa347048136b24c42c119dddaf13a894f254
