### ISSUE TITLE
sol::function gets invalidated, help needed

### ISSUE THREAD

**Issue by D3athBell** [ThePhD/sol2#1107]
Hi
I'm trying to write an event system.
In Script::connect() I copy the sol::protected_function listener (which is passed from Lua) to the member variable on_tick which is also a sol::protected_function. Both the on_tick and the listener functions are completely valid and call the correct Lua function in Script::connect(), however variable on_tick gets invalidated and crashes the program when I try to call it later most likely because listener got destroyed earlier. I have no idea what I'm supposed to do here.

Thanks!

Lua
```
function tick()
    print("ticking")
end

script.connect(events.on_tick, tick)
```

C++
```
void Script::connect(int event_id, sol::protected_function listener)
{   
    //Events is just an enum class currently
    switch (static_cast<Events>(event_id)) {
    case Events::on_tick:
        on_tick = listener;
        if (!on_tick.valid()) {
            spdlog::error("Function on_tick() is not valid");
        }
        //on_tick() is valid and calls the correct Lua function here
        on_tick();
        break;
    default:
        spdlog::error("Event id did not match any known value");
        break;
    }
}
```
```
void Script::tick() const
{
    //Lua function isn't valid here
    if (!on_tick.valid()) {
        spdlog::error("Function on_tick() is not valid");
    }
   //This crashes the program
    on_tick();
}
```

**Comment by atom0s** [comment]
Check out this example:
https://github.com/ThePhD/sol2/blob/develop/examples/source/coroutine_state.cpp#L13

I had to deal with this similar situation in my event callback system as well, and doing this was the fix for me.

Mainly the `std::move(mainState, callback)`.

**Comment by ThePhD** [comment]
This should've been fixed on both Copy and Move, though, so this is probably a valid bug report anyways....

**Comment by D3athBell** [comment]
I got it working by replacing the member function with a lamda in the constructor, as in the example. Though I don't really know how it's functionally different than before. Thank you regardless.
