### ISSUE TITLE
Requesting Const Reference Of 'this_state' Causes Invalid Bindings

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#1110]
**sol version:** f275ad2fc468365e691e05a944e92310e548dbff
**Lua version:** MoonJIT (https://github.com/AshitaXI/moonjit)

Godbolt link to an example of the issue:
https://godbolt.org/z/h6raGE

When requesting a const reference of `sol::this_state` in a binding, sol will compile the binding fine but attempting to call it results in a mismatched signature error. 

`const sol::this_view& s` errors.
`const sol::this_view s` works fine.

_Unsure if this is the expected behavior of sol or if this would be considered a bug._

**Comment by ThePhD** [comment]
These are supposed to be used as values. `const sol::this_view&` should, nevertheless, still work, so just another thing to pile on the list.

**Comment by atom0s** [comment]
Unsure if this is related, but this is another similar issue I noticed:

Requesting a const& string_view works fine, but not if it's requested as an optional.

```cpp
const std::string_view str                 // ok
const std::string_view& str                // ok
sol::optional<const std::string_view> str  // ok
sol::optional<const std::string_view&> str // error
```

**Comment by ThePhD** [comment]
Yes, the last one is bad because of the way optional stores references. You'd be asking for a reference to a non-existent, non-lifetime-extended entity. Don't do that.

**Comment by ThePhD** [comment]
Fixed in latest.
