### ISSUE TITLE
Script doesn't get executed when calling 'safe_script' after 'require_file'

### ISSUE THREAD

**Issue by jschauss** [ThePhD/sol2#1111]
**OS:** Linux
**sol version:** tried with v3.2.1 and 3.2.3
**lua version:** 5.3
**C++ version:** 20

Hi,

in a project I use sol, I include my lua library as a file with the `require_file` function.  I execute my script afterwards with the `safe_script` function, passing the script as string parameter to the function. The `safe_script` function is executed and the return value of the function is valid, but for some reason my script was not executed. Here is a small example that you can use to reproduce the problem.

C++ Code:
```
#include <iostream>
#include <sol/sol.hpp>

int main() {
    sol::state lua;
    lua.open_libraries(sol::lib::package, sol::lib::base);

    lua.set_function("print_to_console", [](std::string const& message) { std::cout << message << std::endl; });

    lua.require_file("require_test", "require_file.lua", false);
    
    try {
        lua.safe_script(R"(
require ("require_test")
print_to_console("message from script"))");

    } catch (sol::error& error) {
        std::cout << "An error occurred while running the script: " << error.what() << std::endl;
    }
}
```

Lua script:
```
print_to_console("message from required file")
```

This is what I expected:
```
message from required file
message from script
```

This is what I get:
```
message from required file
```

As a workaround, I run `safe_script` with an empty script before I run my actually script with `safe_script`. Then I get the expected output.

**Comment by ThePhD** [comment]
This does not work because `require_file` - and the "requires" package in Lua - expect that you return something from the script to be used as the "module" for that and any subsequent calls to `require`. Right now it's just failing because you didn't return anything.

I could insert some bogus key but that's not going to be helpful, because subsequent `require("foo")` calls will just return the bogus key....

**Comment by ThePhD** [comment]
Decided to support this case anyways. We insert a red-herring into the package loader for scripts that don't return anything, so if you do that, it's on you to know why you did something silly!
