### ISSUE TITLE
new_usertype Requires Constructor To Exist Even If sol::no_constructor Is Used

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#1112]
**sol version:** f275ad2fc468365e691e05a944e92310e548dbff
**Lua version:** MoonJIT https://github.com/AshitaXI/moonjit/commit/8827354e537a03e404134a54caa1c8649e46172a

I am working through moving a big project with lots of bindings from Luabind to sol3. I ran into a small snag that I'm not sure is potentially a bug or just a result to how things are done in sol. 

The bindings are within a plugin for a project. The main project owns the objects I am binding to as interfaces / structures. The plugin does not own the types or expose any of the actual method bodies inside of it. However, some of the types do have method definitions to outline calls. Binding these interfaces all work fine, but structs that have an empty constructor do not.

In Luabind, I am able to avoid any issues with this and the constructor is not needed, used or requested at compile time by the bindings. In sol though, this is not the case. Just creating a usertype, even while using `sol::no_constructor` still causes the types constructor to exist in the local codebase.

```cpp
// Example via Luabind, no constructor required and compiles fine..
void setup_binding(lua_State* L)
{
    using namespace luabind;

    module(L)[
        class_<ImGuiIO>(u8"ImGuiIO")

    // bind properties and methods here..
    ];
}

// Example via sol, causes an error complaining ImGuiIO::ImGuiIO does not exist..
void setup_binding(void)
{
    m_LuaState.new_usertype<ImGuiIO>(u8"ImGuiIO"); // errors
    m_LuaState.new_usertype<ImGuiIO>(u8"ImGuiIO", sol::no_constructor); // errors

    // bind properties and methods here..
}
```

` error LNK2001: unresolved external symbol "public: __thiscall ImGuiIO::ImGuiIO(void)" (??0ImGuiIO@@QAE@XZ)`

**Comment by ThePhD** [comment]
Linker errors are not compiler errors, which leads me to believe `ImGuiIO` is still default-constructible (`static_assert(std::is_default_constructible_v<ImGuiIO>)` passes)?

**Comment by atom0s** [comment]
Oops meant to say link time, sorry about that. Yes, that `static_assert` passes.

**Comment by ThePhD** [comment]
This code should now work as expected with `sol::no_constructor` SPECIFICALLY passed in the original `new_usertype` call. Anywhere after and the Linker Error will still come uppercut you.

**Comment by atom0s** [comment]
Looks like current develop is broken from compiling even a basic example.

```cpp
1>  sol\include\sol\protected_function.hpp(280,48): error C2760: syntax error: unexpected token ')', expected 'expression'
1>  sol\include\sol\protected_function.hpp(376): message : see reference to class template instantiation 'sol::basic_protected_function<Base,aligned,Handler>' being compiled
1>  sol\include\sol\usertype_storage.hpp(662,3): error C3861: 'clear_usertype_registry_names': identifier not found
```

This is just trying to compile with:
```cpp
#include <sol/sol.hpp>

int32_t __cdecl main(int32_t argc, char* argv[])
{
    sol::state lua;
    lua.open_libraries();
    lua.script(R"(
print('test');
)");

    return 0;
}
```

**Comment by ThePhD** [comment]
I am having a hard time replicating this error...

**Comment by ThePhD** [comment]
Nevermind I lied I figured it out I'm just terrible at this.

**Comment by ThePhD** [comment]
NOW it's fixed.

**Comment by atom0s** [comment]
Still seeing a ton of errors with:

`sol2\include\sol\usertype_storage.hpp(662,3): error C3861: 'clear_usertype_registry_names': identifier not found`

Basic example of:
```cpp
#include <sol/sol.hpp>

int32_t __cdecl main(int32_t argc, char* argv[])
{
    sol::state lua;
    lua.open_libraries(sol::lib::base);
    lua.script(R"(
print('test');
)");

    return 0;
}
```

will generate this for me as well.

**sol2**:  a9ff1d4187bddb3bfeeb4b1dc4273237a6614436
**Lua**: https://github.com/AshitaXI/moonjit
**Compiler:** Visual Studio 2019 16.8.4
