### ISSUE TITLE
field 'metatable' has incomplete type

### ISSUE THREAD

**Issue by shingle-bells** [ThePhD/sol2#1114]
when I include ```"sol/sol.hpp"``` in my project I get this error: 
```
[build] [project directory]/include/sol/sol.hpp:24540:21: error: 'metatable' has incomplete type
[build] 24540 |     stack_lua_table metatable(m_L, abs_source_index);
[build]       |  
```
Additionally, I get this error for the line directly after it:
```
[build] [project directory]/include/sol/sol.hpp:24541:92: error: expected primary-expression before '>' token
[build] 24541 |     optional<protected_function> maybe_pairs_function = metatable.raw_get<optional<function>>(meta_function::pairs);
[build]       |                                                                                            ^~
```
I don't know what's going wrong, as I have lua successfully included in my project -- or at least I think I do, but cmake is giving me mixed signals since intellisense seems to know where it is but cmake doesn't. I'm still considering this as the potential issue. 

I'm using VS Code, with CMake 3.19 and GCC 9.2.0.

**Comment by ThePhD** [comment]
My bad! Fixed in latest.
