### ISSUE TITLE
Compile error with Apple Clang

### ISSUE THREAD

**Issue by kevincoghlan** [ThePhD/sol2#1115]
At the time of writing, Sol on `develop` branch (commit `d363ccd759b2c0335e046eedc0c71c0b8ecadc62`) doesn't compile for me with Apple Clang, on macOS Catalina 10.15.7.

I ran `single/single.py` to regenerate the Sol header files, and then encountered the following error when compiling my project:

`.../include/sol/sol.hpp:24575:16: error: non-const lvalue reference to type 'sol::function' (aka
      'basic_function<basic_reference<false>, false>') cannot bind to a value of unrelated type 'sol::basic_protected_function<sol::basic_reference<false>,
      false, sol::basic_reference<false> >'
                                        function& pairs_function = *maybe_pairs_function;`

Apple Clang version:
`~ ❯ clang -v
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

I took a look at the '[errors](https://sol2.readthedocs.io/en/latest/errors.html)' page in the Sol docs, but didn't spot anything applicable.

The previous commit that I had been using from `develop` branch (`68fd0c0166ffda2bd2a0293ce9adcaf8f36f9382`, 7 commits behind the latest) compiles fine on Apple Clang, so I have reverted to that for now.

Finally, thank you for your hard work on developing/maintaining this excellent library.

**Comment by ThePhD** [comment]
Sorry about that, fixed in latest!
