### ISSUE TITLE
load a lua file and call a function from that file

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [ThePhD/sol2#1119]
Hello, I'm trying to load a lua file and then call one of the functions in that file. This is what I've tried:

```cpp
Player my_player{};
sol::state lua;

  // make usertype metatable
  auto player_record = lua.new_usertype<Player>("Player",
    "GetName", &Player::GetName,
    "GetID", &Player::GetID,
    "GetHealth", &Player::GetHealth,
    "GetMaxHealth", &Player::GetMaxHealth,
    "SetHealth", &Player::SetHealth,
    "SetTexture", &Player::setTexture
  );
  
auto res = lua.load_file("main.lua");

if(res.valid()) {
   lua["load_player"](&my_player);
} else {
   sol::error error = res;
   std::cout << "problem: " << error.what() << std::endl;
}
```

my lua script looks the following:

```lua
function load_player(player) 
   player:SetName("Bob")
   player:SetHealth(100)
end
```

The script is loading the file fine according to my console output but the values of the object `my_player` are not changing?

**Comment by ThePhD** [comment]
`load_file` is a low-level function that only loads the code, but does not run it. You need to transform that `res` (a `sol::load_result` object) into a `sol::function`/`sol::protected_function` so it can be ran. You can see an example of that here:

https://github.com/ThePhD/sol2/blob/develop/examples/source/script_error_handling.cpp#L63

Alternatively, you can just call `lua.safe_script_file("main.lua");` and it will work instead. It's also much simpler. See, the Quick 'n' Dirty tutorial:

https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#running-lua-code

Good luck!

**Comment by TheMaverickProgrammer** [comment]
The docs seemed to suggest it was returning a function to be invoked, not a file that could invoke a defined function. I'll try to see if it works.

**Comment by ThePhD** [comment]
Yes, it _is_ returning a function (or, rather, function-like type called `sol::load_result`) that must be invoked to actually run the Lua code. In order for Lua to have access to `load_player`, the script needs to be run so it defines it. Once it's defined, then it can be accessed. That looks like this...

```cpp
Player my_player{};
sol::state lua;

// make usertype metatable
auto player_record = lua.new_usertype<Player>("Player",
    "GetName", &Player::GetName,
    "GetID", &Player::GetID,
    "GetHealth", &Player::GetHealth,
    "GetMaxHealth", &Player::GetMaxHealth,
    "SetHealth", &Player::SetHealth,
    "SetTexture", &Player::setTexture
);

// using [safe_]script_file instead of load_file here, which will load AND run the code 
auto res = lua.safe_script_file("main.lua", sol::script_pass_on_error);
if(res.valid()) {
   lua["load_player"](&my_player);
} else {
   sol::error error = res;
   std::cout << "problem: " << error.what() << std::endl;
}
```

If you want to do the individual load, check what goes wrong, and then do the individual run of the code (and also check what goes wrong), then you need to do:

```cpp
Player my_player{};
sol::state lua;

// make usertype metatable
auto player_record = lua.new_usertype<Player>("Player",
    "GetName", &Player::GetName,
    "GetID", &Player::GetID,
    "GetHealth", &Player::GetHealth,
    "GetMaxHealth", &Player::GetMaxHealth,
    "SetHealth", &Player::SetHealth,
    "SetTexture", &Player::setTexture
);

auto res = lua.load_file("main.lua");
if (!res.valid()) { // if it's not valid
   // print the error
   sol::error error = res;
   std::cout << "problem loading script/bytecode into Lua VM: " << error.what() << std::endl;
   exit(1);
}

sol::protected_function script_to_run = res.get<sol::protected_function>();
sol::protected_function_result script_result = script_to_run(); // invoke the script and get the result
if (!script_result.valid()) { // if it's not valid
   // print the error
   sol::error error = script_result;
   std::cout << "problem running script in Lua VM: " << error.what() << std::endl;
   exit(1);
}

// Everything is all set!
lua["load_player"](&my_player);
```

**Comment by TheMaverickProgrammer** [comment]
Ok I understand now. I have gotten the script to partially run. I do have some other questions but they belong in a separate ticket. Thank you!
