### ISSUE TITLE
Segfault on closing of sol::state

### ISSUE THREAD

**Issue by BluFedora** [ThePhD/sol2#112]
If I register a class with the "new_usertype" method (at any point in time) and the "sol::state" is destructed (when the application is closed) there is a segfault.

[Screenshot of the error](https://www.dropbox.com/s/8j2zjsn9ux5zcxc/Screenshot%202016-06-08%2000.25.11.png?dl=0)
[Screenshot of stacktrace](https://www.dropbox.com/s/og7po6r27a8a3ip/Screenshot%202016-06-08%2000.30.46.png?dl=0)
[Stacktrace in text](https://www.dropbox.com/s/fuad2pzo29adq53/stack.txt?dl=0)

I believe it may be related to this:
http://stackoverflow.com/questions/7427969/under-what-conditions-can-lua-close-raise-a-segmentation-fault-error

Code Example:
``` cpp

#include <sol.hpp>

class ship
    {
        public:
            int bullets = 20;
            int life = 100;

            bool shoot () {
                if (bullets > 0) {
                    --bullets;
                    // successfully shot
                    return true;
                }
                // cannot shoot
                return false;
            }

            bool hurt (int by) {
                life -= by;
                // have we died?
                return life < 1;
            }

            ~ship()
            {
            }
    };

int main(int argc, char *argv[])
    sol::state lua;

    lua.new_usertype<ship>(
                "ship",
                "shoot",        &ship::shoot,
                "hurt",         &ship::hurt,
                "life",         &ship::life,
                "bullet_count", &ship::bullets
                );

    return 0;
}
```
I am using the latest code from the repository. (Btw awesome library I love it)

**Comment by ThePhD** [comment]
Windows is okay for all versions of Lua (including JIT), so I'm gonna assume this is only for g++/linux machines. Gonna take me a bit to get the VM set up for this...

**Comment by BluFedora** [comment]
Hmmm that's odd this is happening for me then because I'm on windows 10.

**Comment by ThePhD** [comment]
Windows, with the VC++ compiler* . You're probably using clang or g++?

**Comment by BluFedora** [comment]
Yeah, I'm using g++.

**Comment by ThePhD** [comment]
Okay, I managed to repro, finally, on MinGW with Windows. Not sure what's going on. Time to open GDB...

**Comment by ThePhD** [comment]
Heyo. I managed to get this fixed. We were double-destructoring the usertype metatable and it was screwing things up: thanks for reporting this! It should be all set once I push.

**Comment by BluFedora** [comment]
Awesome thanks for fixing this!! I love this library and was really hoping this would not be too much of a detrimental bug.
