### ISSUE TITLE
What class types do I need to bind to ensure interopability?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [ThePhD/sol2#1120]
I have defined lua bindings on my texture manager like so:

```cpp
  auto textureresource_record = engine_namespace.new_usertype<TextureResourceManager>("TextureResourceManager",
    sol::constructor<TextureResourceManager()>(),
    "LoadTextureFromFile", &TextureResourceManager::LoadTextureFromFile
  );
```

This function returns a type `std::shared_ptr<sf::Texture>`

I've bound another object to take in that shared texture from lua:

```cpp
  auto player_record = engine_namespace.new_usertype<Player>("Player",
    "SetTexture", &Player::setTexture
  );
  
  // signature Player::setTexture(std::shared_ptr<sf::Texture>)
```

and I have a script that looks like this:

```lua
local textures = Engine.TextureResourceMananger.new()

function load_player(player)
    player:SetName("Player1")
    player:SetHealth(100)
    player:SetTexture(textures:LoadTextureFromFile("hero.png"))
end
```

When I run the script, I can see basic things like string names, integer health, etc have been correctly modified. However my shared pointers are remaining empty (nullptr).

I wondered, do I have to bind everything including the `sf::Texture` class in lua for it to work or if sol just passes along the memory that is allocated from the C++ side (the TextureResourceManager class returns the shared ptr from C++ so it's not like lua _needs_ to know...) ?

Thanks again for this awesome library. I'm pretty excited to use it.

**Comment by ThePhD** [comment]
You don't need to bind everything. What does the `SetTexture` method look like, what does the `LoadTextureFromFile` look like? Are you sure it's loading properly?

**Comment by TheMaverickProgrammer** [comment]
Ok my hunch was correct, the memory on the C++ side gets passed through. I was incorrectly calling a function when I had described it as a _property_ in my texture resource manager's lua bindings. We are rockin' and rollin'!
