### ISSUE TITLE
Use table iterator with boost range adaptors

### ISSUE THREAD

**Issue by gotschmarcel-ni** [ThePhD/sol2#1127]
First of all, thanks for all the effort put into sol, it's an awesome binder for Lua!

In our project we often want to use range adapters from the boost library together with the table iterator, to be able to filter out certain keys or collect only keys.

Example:

```cpp
#define SOL_USING_CXX_LUA 1
#include <sol/sol.hpp>

#include <boost/range/adaptor/filtered.hpp>

#include <iostream>
#include <string>

void example() {
    sol::state lua;
    const sol::table someTable = lua.create_table_with(22, "Hello", "key", "value");

    const auto isStringKey = [](const auto& entry) { return entry.first.template is<std::string>(); };
    for (const auto& [key, value] : someTable | boost::adaptors::filtered(isStringKey)) {
        std::cout << key.template as<std::string>() << std::endl;
    }
}
```

Sadly, this doesn't compile. Other iterators, e.g. from `std::vector` work just fine. Do you have an idea what is going on here?

Compiler Error:
```
error: binding reference of type 'pair<...>' to value of type 'const pair<...>' drops 'const' qualifier
[build]         { return *m_iterator; }
[build]                  ^~~~~~~~~~~
[build] /users/boost-v1.70.0/boost/iterator/iterator_facade.hpp:550:20: note: in instantiation of member function 'boost::iterators::iterator_adaptor<boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<(lambda at /users/some.cpp:86:29), bool>, sol::basic_table_iterator<sol::basic_reference<false> > >, sol::basic_table_iterator<sol::basic_reference<false> >, boost::use_default, boost::use_default, boost::use_default, boost::use_default>::dereference' requested here
[build]           return f.dereference();
[build]                    ^
[build] /users/boost-v1.70.0/boost/iterator/iterator_facade.hpp:656:42: note: in instantiation of function template specialization 'boost::iterators::iterator_core_access::dereference<boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<(lambda at /users/some.cpp:86:29), bool>, sol::basic_table_iterator<sol::basic_reference<false> > > >' requested here
[build]             return iterator_core_access::dereference(this->derived());
```

**Comment by ThePhD** [comment]
Probably that the `reference` type is always `const`? I don't have a boost handy for this, let's see...

**Comment by ThePhD** [comment]
This is fixed. Shame there's no better way to handle this, oh well.

`const_cast` unholiness it is!

**Comment by gotschmarcel-ni** [comment]
Awesome! Thanks for looking into this. In your commit you mentioned `table iterators are inefficient and terrible`, what is the more performant solution?

**Comment by ThePhD** [comment]
The more performant solution would be to use the `for_each` function on `table` with `stack_object` key and value arguments to the provided function.

Iterators impose a lot of overhead so that we can iterate "properly", and it relies on the state. You can't really store these iterators and do much else besides one-pass algorithms with them, because of the way C++ works with iterators. Plus, we can't use `table_iterator` + `table_sentinel` because that breaks legacy libraries such as Boost, where they expect the first and last iterators to be of the same type. (C++17 does not require that the begin/end iterators be the same for their ranged-for loops, and neither Boost nor the Standard Library has caught up to this invention yet.)

**Comment by gotschmarcel-ni** [comment]
Thanks for the explanation. The only problem I had so far with `for_each` is the limitation of not being able to exit early.
