### ISSUE TITLE
unique_ptr base type does not resolve during runtime

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [ThePhD/sol2#1130]
I need to be able to construct a class of type `ScriptedSpell` that derives from `Spell`. I do need to relinquish ownership like I've done before in another issue so this is a hint that I need `std::unique_ptr`. However, this time, I cannot seem to bind functions from lua to this unique_ptr. Here's my code:

```cpp
SOL_BASE_CLASSES(ScriptedSpell, Spell);

 auto& scriptedspell_record = battle_namespace.new_usertype<ScriptedSpell>("Spell",
    sol::factories([](Team team) -> std::unique_ptr<Spell> { // <--- note this line
      return std::make_unique<ScriptedSpell>(team);
    }),
    "SetHeight", &ScriptedSpell::SetHeight,
    "SetTexture", &ScriptedSpell::setTexture,
    "GetAnimation", &ScriptedSpell::GetAnimationComponent,
    "Tile", &ScriptedSpell::GetTile,
    "Field", &ScriptedSpell::GetField,
    "Move", &ScriptedSpell::Move,
    "SlideToTile", &ScriptedSpell::SlideToTile,
    "IsSliding", &ScriptedSpell::IsSliding,
    "SetSlideFrames", &ScriptedSpell::SetSlideTimeFrames,
    "ShowShadow", &ScriptedSpell::ShowShadow,
    "Teammate", &ScriptedSpell::Teammate,
    "Delete", &ScriptedSpell::Delete,
    "attackFunc", &ScriptedSpell::attackCallback,
    "deleteFunc", &ScriptedSpell::deleteCallback,
    "updateFunc", &ScriptedSpell::updateCallback,
    "canMoveToFunc", &ScriptedSpell::canMoveToCallback,
    "onSpawnFunc", &ScriptedSpell::spawnCallback,
    sol::base_classes, sol::bases<Spell>() // <-- base class added!
  );
```

If I run this with the following Lua script, nothing happens:

```lua
function Missile()
    local missile = Battle.Spell.new(Team.Blue)
    missile:SetTexture(texture, true)
    missile:SetSlideFrames(80)
    missile:SetHeight(20.0)
    missile:ShowShadow(true)

    local missileAnim = missile:GetAnimation()
    missileAnim:CopyFrom(anim)
    missileAnim:SetState("MISSILE", Playback.Loop, nonce)

    print("missile done")
    return missile
end
```

I never see "missile done" print onto the console. 

However, if I change the return type from my sol::factory to `std::unqiue_ptr<ScriptedSpell>` it does!

But that doesn't solve all the problems. My battle field has overloads to accept the std::unique_ptr from sol to relinquish ownership:

```cpp
  auto& field_record = battle_namespace.new_usertype<Field>("Field",
    "SpawnSpell", sol::resolve<Field::AddEntityStatus(std::unique_ptr<Spell>&, int, int)>(&Field::AddEntity)
  );
  
  Field::AddEntityStatus Field::AddEntity(std::unique_ptr<Spell>& spell, int x, int y)
  {
    Spell* ptr = spell.release();
    return AddEntity(*ptr, x, y);
  }
```

And so this Lua code fails:

```Lua
  field:SpawnSpell(Missile(), self:Tile():X(), self:Tile():Y())
  print("field spawn")
```

I thought maybe if I follow this issue and add the `SOL_BASE_CLASSES(ScriptedSpell, Spell);` macro it would solve the problem. Unfortunately it did not.
https://github.com/ThePhD/sol2/issues/654

So, to reiterate, I need to relinquish ownership therefore I use `std::unique_ptr`. If I return the child class `std::unique_ptr<ScriptedSpell>` from the table factory, I can use all my bound functions, the missile is created but I cannot spawn the missile.

If I DO return the base class instead from my factory `std::unique_ptr<Spell>` I cannot call any of the bound functions on the missile, and therefore renders the class useless.

What am I missing?

**Comment by TheMaverickProgrammer** [comment]
This is working but I do not think it is advised (hence the std::unique_ptr use in my original post)

```cpp
  auto& scriptedspell_record = battle_namespace.new_usertype<ScriptedSpell>("Spell",
    sol::factories([](Team team) {
      return new ScriptedSpell(team);
    }),
    ```
    
I use the factories to return a raw non-owning pointer and use the normal overloads from `Field` to deduce the type. Since the class `Field` deletes all entities when their HP reaches `0`, the memory is released. 

The only thing that could go wrong here is if we are not dealing with a Very Smart Programmer who decides, for whatever reason to allocate a bunch of `new` Spells into their scripts without putting them into the field...

**Comment by ThePhD** [comment]
The only problem with your code is this line:

```cpp
... (std::unique_ptr<Spell>& spell, ...)
```

You can't access a `std::unique_ptr<Derived>` like a `std::unique_ptr<Base>`. The 2 types are unrelated in the C++ inheritance hierarchy, and there's nothing sol2 can do to hand you a pointer to the base type from the derived type. What you're going to have to do is create one gigantic, ugly-as-sin overload block for each higher-level `std::unique_ptr<FooSpell>` type, and have a specific `->release()` call for each one. That can be done via `sol::overload`, just plain ol' `if/else` with `sol::object.is<std::unique_ptr<FooSpell>>()`, `sol::object.is<std::unique_ptr<BarSpell>>()`, etc.

There's unfortunately no magic I can do for you here. I hope that one day C++ gets reflection and I can just vomit all this boilerplate out for you at the drop of a hat, but I can't make the C++ Standards Committee go faster in this regard....

**Comment by TheMaverickProgrammer** [comment]
This ended up being the only viable solution but I still had to specify the base class otherwise I had sol panic exceptions thrown trying to convert from `Spell*` to `ScriptedSpell*`.
