### ISSUE TITLE
How can i save any value into userdata same as behavior of a table?

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1131]
I want to sava any value into a userdata,so:
```c++
class Test {
public:
    Test(int i):_i(i){};
    void PrintI() {
        std::cout << _i << std::endl;
    }
private:
    int _i = 0;
};
lua.new_usertype<Test>("Test",
    sol::factories([](int i) {return new Test(i);}),
    "PrintI",&Test::PrintI
);
```
```lua
local test = Test.new(3)
test:PrintI()--3
--i can call PrintI()

test.a = 1
test.b = "b"
test.self = test
test.t = {}
print(test.a,test,b,test.self,test.t)
-- but i can't do this
```

**Comment by ThePhD** [comment]
You must directly code that ability into the usertype itself. See this example for a "Dynamic Object" that lets you do exactly this with arbitrary values: https://github.com/ThePhD/sol2/blob/develop/examples/source/dynamic_object.cpp

To understand more how get/set works, also see: https://github.com/ThePhD/sol2/blob/develop/examples/source/usertype_dynamic_get_set.cpp

**Comment by wzhengsen** [comment]
Thanks very much!
