### ISSUE TITLE
When using sol to register a large number of types, compilation can cause some problems.

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1134]
* sol version: 3.2.3
* lua version: 5.4.2
* Visual Studio 2019
* Windows 10 x64

I generated a lot of type registration code using python(maybe 5000+ method register,and 200+ usertype register), which would take up 10G+ of my memory when compiling, and compile very very very slowly,and show me a "fatal error c1060" finally.
Here is part of the sample code:

The sample code file:[auto.zip](https://github.com/ThePhD/sol2/files/5987756/auto.zip)

![image](https://user-images.githubusercontent.com/30433761/108316012-3e3d5600-71f7-11eb-89f9-434f26c72b2c.png)

![image](https://user-images.githubusercontent.com/30433761/108045794-d5cb6900-707e-11eb-9596-f1a7dadfcec8.png)

**Comment by wzhengsen** [comment]
@ThePhD 
Please help me.
I have been troubled by this problem for several days, I tried to split the registration process into 480 files for separate registration (one file per class) and the link C1060 error has disappeared, but it generates a new link C1248 error.
I am at my wit's end.

**Comment by ThePhD** [comment]
So I actually can't find C1248 error from search, and MSVC's docs turn up only a handful of those errors: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999?view=msvc-160

Can you be more specific or show me more of the error?

Finally, in general it's best to make sure you're using the 64-bit Hosted toolset, so you can build using all your memory and all your codes. You can do that by following the advice here: https://sol2.readthedocs.io/en/latest/errors.html#compiler-out-of-heap-space

**Comment by ThePhD** [comment]
Oh, right, Linker Error. 

> The linker determined that the size of the output file will exceed the largest possible size for a 32-bit program image. You may want to make your program into multiple DLLs.
> - [
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1248?view=msvc-160](
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1248?view=msvc-160)

Try building the program as 64-bit? Do you need a 32-bit executable/DLL, specifically?

**Comment by wzhengsen** [comment]
@ThePhD 
> https://sol2.readthedocs.io/en/latest/errors.html#compiler-out-of-heap-space

Following the way on the link, I checked. I did use the 64bit compiler with vs2019, however, the compiler still runs very slowly (about 5-10 times slower than registering with tolua++) and still ends up reporting the C1060 error "compiler out of heap space".
 
![image](https://user-images.githubusercontent.com/30433761/108476381-eec95980-72cc-11eb-95e2-95c81c1a33cf.png)

**Comment by ThePhD** [comment]
The bane of sol2 here is that it uses a lot of template shenanigans and not pre-parsed code to make the bindings. So, there's a lot to compile.

I am unfortunately still working on making things better (and others have chipped in). Unfortunately I'm not sure how to help other than, quite literally, have you split the project up into **multiple** DLLs that all get linked into 1 final binary, which just sounds... horrible.

This is the price of hyper-templated code like sol2, I guess. :/

**Comment by ThePhD** [comment]
@OrfeasZ If you've got any recommendations, I would appreciate it. I never had to bind this many classes and end up in this problem...

**Comment by atom0s** [comment]
In my case, with a ton of bindings, I had to opt for breaking things into multiple files as well as altering how I was doing the binds. Which I mentioned a bit here: https://github.com/ThePhD/sol2/issues/1094#issuecomment-752320384

The main two things that would cause me to hit this same issue were:
 - `new_usertype` calls passing all binds into the the call directly.
 - `new_enum` calls passing all binds into the call directly.

For me, to fix this I changed all `new_usertype` calls to instead only ever pass in the name and basics such as `sol::no_constructor`. All other binds for functions and properties are instead manually added individually using the respective `set_function` and `set` calls as needed. For example:

```cpp
    auto party = this->m_LuaState.new_usertype<IParty>(u8"IParty",
        sol::no_constructor,
        // Get Raw Structures
        u8"GetRawStructure", &IParty::GetRawStructure,
        u8"GetRawStructureStatusIcons", &IParty::GetRawStructureStatusIcons);

    // Get Properties (Alliance)
    party.set_function(u8"GetAllianceLeaderServerId", &IParty::GetAllianceLeaderServerId);
    party.set_function(u8"GetAlliancePartyLeaderServerId1", &IParty::GetAlliancePartyLeaderServerId1);
    party.set_function(u8"GetAlliancePartyLeaderServerId2", &IParty::GetAlliancePartyLeaderServerId2);
    party.set_function(u8"GetAlliancePartyLeaderServerId3", &IParty::GetAlliancePartyLeaderServerId3);
    party.set_function(u8"GetAlliancePartyVisible1", &IParty::GetAlliancePartyVisible1);
    party.set_function(u8"GetAlliancePartyVisible2", &IParty::GetAlliancePartyVisible2);
    party.set_function(u8"GetAlliancePartyVisible3", &IParty::GetAlliancePartyVisible3);
    party.set_function(u8"GetAlliancePartyMemberCount1", &IParty::GetAlliancePartyMemberCount1);
    party.set_function(u8"GetAlliancePartyMemberCount2", &IParty::GetAlliancePartyMemberCount2);
    party.set_function(u8"GetAlliancePartyMemberCount3", &IParty::GetAlliancePartyMemberCount3);
    party.set_function(u8"GetAllianceInvited", &IParty::GetAllianceInvited);
```

For enums, I changed from direct passes to using the newer initializer_list constructor. For example:

```cpp
    // Ashita::LogLevel
    this->m_LuaState.new_enum<Ashita::LogLevel>(u8"LogLevel",
        {//
            {u8"None", Ashita::LogLevel::None},
            {u8"Critical", Ashita::LogLevel::Critical},
            {u8"Error", Ashita::LogLevel::Error},
            {u8"Warn", Ashita::LogLevel::Warn},
            {u8"Info", Ashita::LogLevel::Info},
            {u8"Debug", Ashita::LogLevel::Debug}});
```

This does land up creating a ton of .cpp files to hold everything seperated for each parent object being bound, but it does fix the issue for me at least. I also do recommend the platform toolset config to target the x64 compiler tools to help increase the max process memory space allowed while compiling. 

Another option too that I had to do while compiling in debug mode was add the custom C/C++ command line switch `/bigobj`.

**Comment by ThePhD** [comment]
Thanks for the insights here.

Fixing object and binary size is going to be part of my next big 4.0 push. Thanks for sharing your wisdom here.

**Comment by ocbjsys** [comment]
Sorry to gravedig, 
But this is important to me. 

I have a need to represent all keycodes in enum form. 
This is causing out of heap space on github actions builds. 

Hoping this gets the love and attention it needs.
