### ISSUE TITLE
Usertype with map

### ISSUE THREAD

**Issue by vpronin** [ThePhD/sol2#1136]
hello, please help me solve the problem of usertypes.
[](url)
Is it possible to create usertype so t[var1] == 2, like it works with standart types?
For example:.
t["var1"]=1
t["var2"]=2
print ( t["var1"] )

[usertype.txt](https://github.com/ThePhD/sol2/files/6001628/usertype.txt)

**Comment by ThePhD** [comment]
Yes.

https://github.com/ThePhD/sol2/blob/develop/examples/source/dynamic_object.cpp

https://github.com/ThePhD/sol2/blob/develop/examples/source/usertype_dynamic_get_set.cpp

**Comment by vpronin** [comment]
Thanks, but that's not really what I was asking. Is it possible to place an instance of a usertype in a lua table not by reference, but by value, by serializing it for example to_string.

**Comment by vpronin** [comment]
for example usertype - Date(y,m,d)
local d1 = Date.new(2021,2,19)
local d2 = Date.new(2021,1,1)
local t = {}
t[d1] =1
t[d2] =2
print[d1] - should be 2 and #t == 1 ?
thanks !

**Comment by ThePhD** [comment]
Oh, that example is a bit more clear.

No, that's not possible. Lua does not allow you to do that with a **normal** Lua table. Inserting into a table means reference comparisons, not value comparisons, even if you override `==` for the usertype (which sol2 lets you do).

So, you need to follow the examples above, replace `t` with a usertype that acts like a table, and then on `set` do a deep, by-value compare for types you know about.

**Comment by vpronin** [comment]
Thanks

пт, 19 февр. 2021 г. в 13:10, The Phantom Derpstorm <
notifications@github.com>:
