### ISSUE TITLE
Optional Issue

### ISSUE THREAD

**Issue by PhilCK** [ThePhD/sol2#114]
When I clone the repo, or download it the Optional directory is empty, as such I can't compile.

```
clang++ main.cpp -I./sol2 -I./sol2/sol -std=c++14 && ./a.out
```
Results in
```
./sol2/sol/optional.hpp:30:10: fatal error: '../Optional/optional.hpp' file not found
```

Tried C++11 got even more in the way of errors.

Clang 3.7
OSX El-Cap

**Comment by Nava2** [comment]
`git submodule update --init --recursive`

That will fix the error.

**Comment by PhilCK** [comment]
👍

**Comment by ThePhD** [comment]
Also see here for more details: http://sol2.readthedocs.io/en/latest/tutorial/getting-started.html#getting-started

**Comment by PhilCK** [comment]
Thanks.
