### ISSUE TITLE
A compile error was raised when creating the usertype.

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1141]
* sol version: 3.2.3
* lua version: 5.4.2
* Visual Studio 2019
* Windows 10 x64

> code:
```c++
struct Test1{};
sol::state lua = {};
std::string_view sv = "Test1";
lua.get<sol::table>("_G").new_usertype<Test1>(sv);//This code is right.
```

> another code:
```c++
struct Test1{};
sol::state lua = {};
std::string_view sv = "Test1";
lua.new_usertype<Test1>(sv);//Compile error.
```

**Comment by ThePhD** [comment]
This code does not produce a compiler error for me, Visual Studio 2019, Latest Release and Preview.

What are you seeing, exactly?

**Comment by ThePhD** [comment]
(I will note that I'm also using the latest `develop` branch from sol2, as well.)

**Comment by wzhengsen** [comment]
@ThePhD 
Thanks!
The error disappered when I use lastest version.
