### ISSUE TITLE
Passing parameters from c++ to a class function in lua

### ISSUE THREAD

**Issue by brendacrowe** [ThePhD/sol2#1145]
This is my luaFile.lua

```
function my_class:testFunction(formName, guid)
	-- LogMsg is a c++ function use to log messages
	LogMsg("1", "Testing formName " ..tostring(formName), "my_class:testFunction", 2)
	self:MyNameIs(formName);
end

obj = my_class.new("")

```

This is my c++ class

```
class my_class 
{
	
public:

	my_class()
	{
	}

	void MyNameIs(std::string formName)
	{
		std::string mynameis = formName;
	}
};

```
This is how I created my usertype (c++ side)

```
			sol::state solState;
			solState.open_libraries(sol::lib::base, sol::lib::string, sol::lib::package, sol::lib::table, sol::lib::io);

			solState.set_function("LogMsg", &LogMsg);

			sol::usertype<my_class> my_class_type = solState.new_usertype<my_class>("my_class", sol::constructors<my_class()>(),
				"MyNameIs", &my_class::MyNameIs); // the usual
			
			auto result = solState.safe_script_file(std::string("C:\\Users\\brend\\Desktop\\sc2.lua"), sol::script_pass_on_error);

			if (!result.valid())
			{
                                sol::error solErr = result1;
				CString strErr = solErr.what();
			}
```

My question is how do I call function in lua "my_class:testFunction(formName, guid)"  from c++.  I have not been successful at  passing parameters to lua this way.  I was able to call the function but, the parameters come out empty.  The only way I have been able to make it work is to add a function in lua as follow:

```
function testFunction(formName, guid)
	obj:testFunction(formName, guid)
end
```
Is there away to avoid this?   

Thank you in advanced!

**Comment by ThePhD** [comment]
You need to pass "self", manually, after getting the function.

```cpp
sol::protected_funtion testfunc = lua["my_class"]["testFunction"];
sol::object my_object = lua["obj"];
testfunc(obj, // very important
     formName,
     guid
);
````

**Comment by brendacrowe** [comment]
Thank you so much!  That worked!  I'm sorry, I just realized that I posted this under issues, when it wasn't really an issue, it was more of a question.

**Comment by ThePhD** [comment]
This is the right place to ask questions; feel free to come back with more, or send an e-mail if you feel like it's special or whatever (though I reserve the right to not patch commercial codebases with what little energy and time sick-me has right now).
