### ISSUE TITLE
[CLANG] Swapped parameters in tutorial code

### ISSUE THREAD

**Issue by Ishiguro96** [ThePhD/sol2#1148]
Hi

I'm trying to learn using Sol library and currently I'm following tutorials on wiki. I have encountered a problem, where parameters for `std::string` params are swapped, thus creating non valid object.

The problem exists here: https://raw.githubusercontent.com/ThePhD/sol2/develop/docs/source/tutorial/functions.rst in first code snippet. `my_function` creates an invalid object of `std::string` while returning.

Also the `std::string` parameter `b` passed to `my_function` could be a `const std::string& b` ;)

I really appreciate your work, usage of Sol lib is a way better than using core C Lua lib.

**Comment by ThePhD** [comment]
I cleaned this up and a few other things. I'm going to be overhauling the docs soon.

Still, thanks for pointing it out!
