### ISSUE TITLE
I can't register static method with sol 4.0.0-alpha

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1149]
* sol version: 4.0.0-alpha
* lua version: 5.4.2
* Visual Studio 2019
* Windows 10 x64

```c++
struct Test {
    static Test* staticCreate() {
        return new Test();
    }
    Test* create() {
        return new Test();
    }
};

int main() {
    sol::state lua = {};
    auto T = lua.new_usertype<Test>("Test");
    // compile ok.
    T.set_function("create", &Test::create);
    // compile error.
    T.set_function("staticCreate", &Test::staticCreate);
    return 0;
}
```

**Comment by ThePhD** [comment]
What is the compiler error, exactly?

**Comment by wzhengsen** [comment]
![image](https://user-images.githubusercontent.com/30433761/110234071-8a142d00-7f63-11eb-81a2-b1291edb218c.png)

This is it,sorry,but i using a chinese system.

**Comment by wzhengsen** [comment]
The first line chinese means "No matching overloaded function found".

**Comment by ThePhD** [comment]
It's fine to use a chinese system! I can tell what it is from the "shape" of the failure, and the error number (C2672) also gives me a good hint to reproduce it.

**Comment by ThePhD** [comment]
Hey, this should be fixed now!
