### ISSUE TITLE
luaJIT compatible issue? Linker errors

### ISSUE THREAD

**Issue by k12Sergey** [ThePhD/sol2#1152]
Hi!
i'm trying to use lua sol with luajit builded from source, which is worked as standalone luajit.exe.
If i link luajit.lib in exchange of lua51.lib (both produced during luajit build) the following linker errors occur. 

`main.obj:-1: error: LNK2019: unresolved external symbol lua_close referenced in function "public: void __cdecl sol::detail::state_deleter::operator()(struct lua_State *)const " (??Rstate_deleter@detail@sol@@QEBAXPEAUlua_State@@@Z)`
`main.obj:-1: error: LNK2019: unresolved external symbol lua_gettop referenced in function "int __cdecl kp_compat53_absindex(struct lua_State *,int)" (?kp_compat53_absindex@@YAHPEAUlua_State@@H@Z)`

and many others.

Seems like the issue is a version, but it worked with lua51.lib.
Should i use some specific defines which deactivate some lua 5.3 or higher functionalities in case of lua jit?

Thanks

**Comment by ThePhD** [comment]
sol2 works with LuaJIT. These linker errors mean you have problems with your build. PLease make sure `SOL_LUAJIT` is on, as specified here: https://sol2.readthedocs.io/en/latest/safety.html

And make sure you are linking against the appropriate libraries.

**Comment by k12Sergey** [comment]
Thanks for your advice!
try to manually add
`#define SOL_LUAJIT 1`
and link to both luajit.lib and lua51.lib builded with luajit installation procedure. 
And it is worked! 
I managed to write from lua script version of luajit 
`print(jit.version)`
As is marked in config instruction of sol - if LUAJIT_VERSION  is detected SOL_LUAJIT should be turned on by default. But search in lua sol folder files didnt find code for such behaviour (i simply use ide search in folder files, maybe it wrong). 
And in luajit.h following define were found (this header included in lua.hpp of luajit include files):
`#define LUAJIT_VERSION		"LuaJIT 2.0.5"`

**Comment by ThePhD** [comment]
I don't remember having to link with both lua51.lib and luajit.lib, but.... if it works, it works I guess...!

Also remember that if you have "include" flags passed to your compiler that include the old Lua directories, those can get picked up over what LuaJIT is providing.

We also do check for `LUAJIT_VERSION` and turn it on automatically, which makes me think you're not configured properly or your Include Search Paths are not properly set: https://github.com/ThePhD/sol2/blob/develop/include/sol/compatibility/lua_version.hpp#L45

(We turn on an "internal" macro, not `SOL_LUAJIT` directly. We then use that internal macro.)

Also, what do you mean by "interpreter"? Do you mean `lua.exe`/`luajit.exe`, or your custom program?

**Comment by k12Sergey** [comment]
Thanks a lot!
I should recheck what i actually searched for, because i found the code you mention with external tools.
I still should manually set define, but it  seems like a problem i produce from nowhere.
