### ISSUE TITLE
Get speedup mention in getting performance

### ISSUE THREAD

**Issue by k12Sergey** [ThePhD/sol2#1154]
Thanks to ThePhD i manage to run luajit and watch it performance a little.
And i got unexpected behaviour.  lua code much faster than binded from c++ code, and ffi calls are the same speed as pure c++!
Im trying the following code:
`add = function (a,b)`
`	return a + b + b + b`
`end`
`local y = os.clock()`
`a = 0`
`for i=1,1000000000 do `
`	a = add(a,1)`
`end`
`print(string.format("elapsed time: %.2f", os.clock() - y))`
and it show about 2 sec! Amazing! (pure lua 5.3 took 45 sec)
luajit ffi version and run with c++ only show the same result about 1.1 sec.
But binding  function from c++ took about 51 seconds!!!!
`lua.set("madd", sol::c_call<decltype(&add), &add>);`
`local x = os.clock()`
`a = 0`
`for i=1,1000000000 do `
`	a = madd(a,1)`
`end`
`print(string.format("elapsed time: %.2f", os.clock() - x))`
`print(a)`
which binded with:

Maybe my times estimation method is too straightforward, but it always so. 
I read [https://sol2.readthedocs.io/en/latest/performance.html](url) and try some, and some didnt understand yet (i dont know how really pure lua calls happens) . It was noted about 10 ns overhead, but function elapsed time is only 1-2 ns, and binding overhead is 50 sec, which meant 50 ns for a single call.

According to benchmark - call to member function it took 200 ns for lua sol and it is good! 
Member function goes trough search procedure, so then my 50 ns overhead is ok. And luajit did amazing optimization.  
And it is impossible to optimize calls to c++ functions.

**Comment by ThePhD** [comment]
Leaving Lua has a cost. For the LuaJIT code, that likely gets compiled down to a pretty fast assembly representation by the JIT compiler. On the contrary, doing the add from C++ means there is no optimization potential.

If your concern is millions of tiny C++ calls scattered throughout your application, then my suggestion is to leave Lua only for the things that should or must be done in C++ or with C++. Otherwise, this is the smallest overhead you can have.

**Comment by k12Sergey** [comment]
Thanks! I wondering why is it so.  Since you confirm it is almost best possible, i follow you proposition and leave lua for global algorithm with viewer calls to c++ functions. Amazing performance of lua cod with luajit make me think of strange things.
Sorry about not important question and almost flood in forum.

**Comment by ThePhD** [comment]
No problem; good luck with your project!
