### ISSUE TITLE
Can I add private member of class in my class bind?

### ISSUE THREAD

**Issue by Enem-20** [ThePhD/sol2#1155]
Hello. I searched in docs, examples and issues answer on my question. Can i do private member?

**Comment by atom0s** [comment]
Directly binding to a private member, no. That is a restriction/rule of C++ itself. 

You can, however, create get/set function helpers that access the private member and bind to those as a property instead.

```cpp
class Example
{
    int32_t m_Number = 0;

public:
    Example(void) { }
    ~Example(void) { }

    int32_t getNumber(void) const { return this->m_Number; }
    void setNumber(const int32_t n) { this->m_Number = n; }
};
```

```cpp
    sol::state lua;
    lua.open_libraries();

    lua.new_usertype<Example>(
        "Example",
        "number", sol::property(&Example::getNumber, &Example::setNumber)
        );

    lua.script(R"(
    local e = Example.new();
    e.number = 12;
    print(e.number); -- Prints 12
    e.number = 33;
    print(e.number); -- Prints 33
)");
```

**Comment by ThePhD** [comment]
If you put the binding stuff inside a member method or `friend`-ed the function that does the binding, that could also work too.

**Comment by Enem-20** [comment]
> If you put the binding stuff inside a member method or `friend`-ed the function that does the binding, that could also work too.

No, i mean use binded field like private in lua

**Comment by Enem-20** [comment]
> Прямая привязка к частному члену, нет. Это ограничение / правило самого C ++.
> 
> Однако вы можете создать помощников функций get / set, которые обращаются к частному члену и вместо этого привязываются к нему как к свойству.
> 
> ```c++
>  пример класса
> {
>     int32_t m_Number = 0 ;
> 
> public: 
>     Example ( void ) {}
>      ~ Example ( void ) {}
> 
>     int32_t  getNumber ( void ) const { вернуть  это -> m_Number ; }
>      void  setNumber ( const  int32_t n) { это -> m_Number = n; }
> };
> ```
> 
> ```c++
>     sol :: state lua;
>     lua.open_libraries ();
> 
>     lua.new_usertype <Пример> (
>         « Пример » ,
>          « число » , sol :: property (& Example :: getNumber, & Example :: setNumber)
>         );
> 
>     lua.script ( R "(
>      local e = Example.new (); 
>     e.number = 12; 
>     print (e.number); - печатает 12 
>     e.number = 33; 
>     print (e.number); - печатает 33 
> ) " );
> ```

Thanks for answer. But that's not what i mean
