### ISSUE TITLE
/usr/local/include/sol/traits.hpp:482:53: fatal error:  no member named 'variant' in namespace 'std'

### ISSUE THREAD

**Issue by sagunkho** [ThePhD/sol2#1156]
Build - https://travis-ci.org/github/horizonxyz/horizon/jobs/762615883#L5800

**Comment by ThePhD** [comment]
You can turn off variant by defining the `SOL_STD_VARIANT` macro to `0`.

**Comment by ThePhD** [comment]
I forgot to make this required, so I patched the latest. Grab the latest and this should be okay.
