### ISSUE TITLE
How can I call a specific function when accessing separate components of a usertype?

### ISSUE THREAD

**Issue by Wantcha** [ThePhD/sol2#1162]
```
void LuaManager::BindMath()
	{
		m_State.new_usertype<glm::vec2>("Vector2", sol::constructors<glm::vec2(float, float)>(),
			"x", &glm::vec2::x,
			"y", &glm::vec2::y,
			sol::meta_function::addition, [](const glm::vec2& l, const glm::vec2& r) { return glm::vec2(l.x + r.x, l.y + r.y); },
			sol::meta_function::subtraction, [](const glm::vec2& l, const glm::vec2& r) { return glm::vec2(l.x - r.x, l.y - r.y); }
			);

		m_State.new_usertype<glm::vec3>("Vector3", sol::constructors<glm::vec3(float, float, float)>(),
			"x", &glm::vec3::x,
			"y", &glm::vec3::y,
			"z", &glm::vec3::z,
			sol::meta_function::addition, [](const glm::vec3& l, const glm::vec3& r) { return glm::vec3(l.x + r.x, l.y + r.y, l.z + r.z); },
			sol::meta_function::subtraction, [](const glm::vec3& l, const glm::vec3& r) { return glm::vec3(l.x - r.x, l.y - r.y, l.z - r.z); }
		);
	}
	void LuaManager::BindECS()
	{
		auto transformComponent_type = m_State.new_usertype<TransformComponent>("TransformComponent", sol::no_constructor,
			"position", sol::property( &TransformComponent::GetPosition, &TransformComponent::SetPosition),
			"rotation", sol::property(&TransformComponent::GetRotation, &TransformComponent::SetRotation),
			"scale", sol::property(&TransformComponent::GetScale, &TransformComponent::SetScale));
```

Transform position, rotation, and scale are glm::vec3. With this current setup, the only time the TransformComponent::SetPosition is called is when I do ` transform.position = value `. What I want to be able to do is ` transform.position.x = value ` and have the SetPosition function be called. How can I achieve that?

**Comment by Rochet2** [comment]
A bit of an issue I see here is that you don't have access to TransformComponent when you do `transform.position.x = value`.
Think of a situation like this:
```lua
local pos = transform.position
pos.x = value
```
You expect this to call SetPosition on transform on the second line even if there is no access to transform.
How did you plan on achieving access to the transform object? I'm not familiar with ECS or such techniques, so maybe there is some underlying way to achieve this.

Access to TransformComponent would probably need to be stored to `position` in one way or another.
This would result in it not being a vec3 but instead, it would maybe be something that extends it. Or maybe some kind of proxies could be used that store the breadcrumbs until the value assignment when everything is finally evaluated.
In my opinion, the problem should be solved in some other way than trying to access SetPosition from Vec3.

**Comment by Wantcha** [comment]
> A bit of an issue I see here is that you don't have access to TransformComponent when you do `transform.position.x = value`.
> Think of a situation like this:
> 
> ```lua
> local pos = transform.position
> pos.x = value
> ```
> 
> You expect this to call SetPosition on transform on the second line even if there is no access to transform.
> How did you plan on achieving access to the transform object? I'm not familiar with ECS or such techniques, so maybe there is some underlying way to achieve this.
> 
> Access to TransformComponent would probably need to be stored to `position` in one way or another.
> This would result in it not being a vec3 but instead, it would maybe be something that extends it. Or maybe some kind of proxies could be used that store the breadcrumbs until the value assignment when everything is finally evaluated.
> In my opinion, the problem should be solved in some other way than trying to access SetPosition from Vec3.

I understand what you're saying, but my problem is that I don't know what kind of workaround I could implement in order to achieve that effect. The reason I need to call the `SetPosition()` function is that it includes a `RecalculateTransformMatrix()` function. Right now, when I return the transform matrix of the object, I have to reconstruct each time, which is not ideal. What I would like to do is have it recalculated only when the transform is actually modified and not every frame. Do you have any idea how can I achieve that?

**Comment by Rochet2** [comment]
One way could be to store the input data from which the matrix is calculated. Then when you get the matrix, you simply test if the input data has changed and recalculate it if it has:
```cpp
Matrix GetMatrix() {
    if (old != std::make_tuple(x,y,z)) // test if input data changed since last time
    {
        // recalculate and save new input data
        old = std::make_tuple(x,y,z);
        matrix = RecalculateTransformMatrix(x,y,z);
    }
    return matrix; // return whatever matrix we have
}
```

Another way is to rework the API so that you don't directly edit the vec3. For example by having `transform:SetPositionX(1)`, which then can do whatever is necessary. I'm sure there are many other approaches also.

**Comment by ThePhD** [comment]
You can rig your `transform.position` to return a proxy-structure, whose sole existence is to store where it came from and propagate effects up the stack.

Pros: It does your use case.
Cons: It generates a stupidly high amount of garbage.

```cpp
struct position_proxy {
     TransformComponent* component;
     
     void set_x( float val ) noexcept {
          component->SetX(val);
     }
     
     void set_y( float val ) noexcept {
          component->SetY(val);
     }
     
     float get_x( ) noexcept {
          component->GetX();
     }
     
     float get_y() noexcept {
          component->GetY();
     }
};

lua.new_usertype<position_proxy>("position_proxy",
     "x", sol::property(&position_proxy::set_x, &position_proxy::get_x),
     "y", sol::property(&position_proxy::set_y, &position_proxy::get_y)     
);
```

Further optimizations can be done with customization points to produce less garbage, such as storing the `position_proxy` in its entirety as a `void*`, and ripping the `TransformComponent*` out of it to do work.

```cpp
	void LuaManager::BindECS()
	{
		auto transformComponent_type = m_State.new_usertype<TransformComponent>("TransformComponent", sol::no_constructor,
			"position", sol::property( &TransformComponent::GetPositionProxy, &TransformComponent::SetPositionProxy),
			"rotation", sol::property(&TransformComponent::GetRotation, &TransformComponent::SetRotation),
			"scale", sol::property(&TransformComponent::GetScale, &TransformComponent::SetScale));
        }
```

"GetPositionProxy" and "SetPositionProxy" left as an exercise to the reader.
