### ISSUE TITLE
Interactive mode?

### ISSUE THREAD

**Issue by raphasampaio** [ThePhD/sol2#1163]
Is it possible to use lua's interactive mode (REPL) with sol2? I'm simulating the basic one line REPL manually, however there are several scope problems doing this way:

```
std::string line;
while (std::cout << "> " && std::getline(std::cin, line)) {
    try {
        auto result = lua.safe_script(line, sol::script_throw_on_error);
    } catch (const sol::error& e) {
        Logger::error(e.what());
    }
}
```

**Comment by Rochet2** [comment]
The implementation of the repl is available in lua.c in the lua source code.
Its less than 400 lines of code, and the relevant parts is probably a lot less lines.
Maybe you could take a look at that and use the existing implementation almost directly. Or you could try to follow it and implement it using sol.

There are also many other avenues you could take, such as implementing it in lua or trying to find an existing implementation. You could also make a bubblegum fix where there is a specific character sequence you look for in the repl. For example lets say you store each line to memory until a line contains $$$ at the end of it, in which case all the stored code is concatenated and run at once.

**Comment by raphasampaio** [comment]
Thanks, @Rochet2. I suspected that I would need to do something like that; no problem, it's super simple. Thanks!
