### ISSUE TITLE
sol is trying to delete a unique_ptr user type of something I've already release'd

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [ThePhD/sol2#1164]
The code is long and ugly so I'll do my best to trim it. This is something you've helped me with before but after letting the game run for longer than I had previously it produces a crash.

```lua
function Missile(boss)
    local missile = Battle.Obstacle.new(Team.Blue)
    missile:SetHealth(20)
    missile:SetTexture(texture, true)
    missile.waitTimer = 1 -- in seconds

    missile.updateFunc = function(self, dt) 
        print("updating missile")

        self.waitTimer = self.waitTimer - dt
        if(self.waitTimer > 0) then 
            return 
        end

        if self:IsSliding() == false then
            if self:Tile():IsEdge() then 
                self:Remove()
            end

            -- otherwise keep sliding
            local dest = self:GetTile(Direction.Left, 1)
            self:Slide(dest, frames(20), frames(0), ActionOrder.Voluntary, nonce)
        end 

        -- every frame try to attack shared tile
        self:Tile():AttackEntities(self)
    end

    missile.attackFunc = function(self, other) 
        local explosion = Battle.Explosion.new(1, 1)
        self:Field():Spawn(explosion, self:Tile():X(), self:Tile():Y())
        self:Delete()
    end

    missile.deleteFunc = function(self) 
        local explosion = Battle.Explosion.new(1, 1)
        self:Field():Spawn(explosion, self:Tile():X(), self:Tile():Y())
    end

    missile.canMoveToFunc = function(tile)
        -- missiles fly over any tiles
        return true
    end

    return missile
end
```

This script creates a `ScriptedSpell` and gives it lua functions as callbacks so I can use the same internal battle systems with newly produced content from scripts!

Here's how I bind `ScriptedSpell` objects to lua from C++:

```cpp
  auto& scriptedspell_record = battle_namespace.new_usertype<ScriptedSpell>("Spell",
    sol::factories([](Team team) -> std::unique_ptr<ScriptedSpell> {
      return std::make_unique<ScriptedSpell>(team);
    }),
    sol::meta_function::index,
    &dynamic_object::dynamic_get,
    sol::meta_function::new_index,
    &dynamic_object::dynamic_set,
    sol::meta_function::length,
    [](dynamic_object& d) { return d.entries.size(); },
    "GetID", &ScriptedSpell::GetID,
    "SetHealth", &ScriptedSpell::SetHealth,
    "SetHeight", &ScriptedSpell::SetHeight,
    "SetTexture", &ScriptedSpell::setTexture,
    "GetTile", &ScriptedSpell::GetTile,
    "Tile", &ScriptedSpell::GetCurrentTile,
    "Field", &ScriptedSpell::GetField,
    "Slide", &ScriptedSpell::Slide,
    "IsSliding", &ScriptedSpell::IsSliding,
    "Delete", &ScriptedSpell::Delete,
    "Remove", &ScriptedSpell::Remove,
    "attackFunc", &ScriptedSpell::attackCallback,
    "deleteFunc", &ScriptedSpell::deleteCallback,
    "updateFunc", &ScriptedSpell::updateCallback,
    "canMoveToFunc", &ScriptedSpell::canMoveToCallback,
    "onSpawnFunc", &ScriptedSpell::spawnCallback,
    sol::base_classes, sol::bases<Spell>()
  );
```

This makes use of your `dynamic_object` struct in the tuts so I can add the lua variable `waitTimer` to the missile and reference it in the callback functions e.g.  `self.waitTimer > 0`

Here's the definition for that:

```cpp
#pragma once

/**
 * @class dynamic_object
 * @brief allows sol representations of classes have dynamic properties
 */
struct dynamic_object {
  std::unordered_map<std::string, sol::object> entries;

  void dynamic_set(std::string key, sol::stack_object value) {
    auto it = entries.find(key);
    if (it == entries.cend()) {
      entries.insert(it, { std::move(key), std::move(value) });
    }
    else {
      std::pair<const std::string, sol::object>& kvp = *it;
      sol::object& entry = kvp.second;
      entry = sol::object(std::move(value));
    }
  }

  sol::object dynamic_get(std::string key) {
    auto it = entries.find(key);
    if (it == entries.cend()) {
      return sol::lua_nil;
    }
    return it->second;
  }
};
```

So the `Field` class is what is responsible for spawning and removing things. When something is added to the field it will be cleaned up by my program (not lua!) so you helped me come up with this working solution a while back:

```cpp
  auto& field_record = battle_namespace.new_usertype<Field>("Field",
    "TileAt", &Field::GetAt,
    "Width", &Field::GetWidth,
    "Height", &Field::GetHeight,
    "Spawn", sol::overload(
      sol::resolve<Field::AddEntityStatus(Spell&, int, int)>(&Field::AddEntity),
      sol::resolve<Field::AddEntityStatus(Artifact&, int, int)>(&Field::AddEntity),
      sol::resolve<Field::AddEntityStatus(std::unique_ptr<ScriptedSpell>&, int, int)>(&Field::AddEntity),
      sol::resolve<Field::AddEntityStatus(std::unique_ptr<ScriptedObstacle>&, int, int)>(&Field::AddEntity)
    )
  );
  
  //... in Field.cpp
  Field::AddEntityStatus Field::AddEntity(std::unique_ptr<ScriptedSpell>& spell, int x, int y)
  {
    Spell* ptr = spell.release();
    return AddEntity(*ptr, x, y);
  }

  Field::AddEntityStatus Field::AddEntity(std::unique_ptr<ScriptedObstacle>& obst, int x, int y)
  {
    Obstacle* ptr = obst.release();
    return AddEntity(*ptr, x, y);
  }
```

Which has been working. The spells spawn from my lua scripts and I've been able to make some custom content. Except I've been letting it run and I think the garbage collection is still trying to delete the unique ptr.

After a minute or so I get this crash:
```
ScriptedSpell::~ScriptedSpell()
[External Code]
sol::detail::usertype_unique_alloc_destroy<ScriptedSpell, unique_ptr<ScriptedSpell, std::default_delete<ScriptedSpell>>> (void* memory)
sol::detail::unique_destroy<ScriptedObstacle>(lua_State* L)
[External Code]
sol::stack::unqualified_pusher<sol::closure<>, void>::push(lua_State* L, sol::closure<> cc)
...etc
```

The stack frames unfortunately do not show the correct order since there is `[External code]` being called and it doesn't make sense. I can see my code being correctly invoked by sol pushing the functions onto the lua stack but it'll end with `~ScriptedSpell()` on garbage data (it's been release()'d). The stack is also inconsistent which makes me think it's the garbage collector. I've tried recreating the exact time this crash happens and it's different each time.

As you can see the only "point of entry" for the unique_ptr adding to the field via `Spawn(...)` always begins with `.release()` so I'm confused why lua tries to garbage collect this at all.

**Comment by ThePhD** [comment]
So this bug report doesn't make sense to me because, yes, `std::unique_ptr` should still be destructible if you call `.release()`. The original pointer contained in the script that gets garbage collected should call the destructor, and it's internal pointer should be `nullptr`, and so the destructor should be a no-op.

Are you sure you're calling `.release()` and not `.get()` somewhere?

**Comment by ThePhD** [comment]
(When I say, "Lua is the only one that can delete it at that point", what I mean is that it's the only one that can delete the `std::unique_ptr` object itself. Note that calling `.release()` takes the stored pointer out of Lua's care, but leaves the `unique_ptr` object in there for the destructor to fire and be deleted. If the value still has a pointer in it something has gone very, very wrong.)

**Comment by TheMaverickProgrammer** [comment]
I didn't know this thank you for sharing how this works under the hood. 

I'm referencing[ this help desk issue](https://github.com/ThePhD/sol2/issues/1122#issuecomment-772147735) where you helped me use `release` to get the pointer because I needed to `delete` it in my engine as that's how the code is written.

> Essentially, I want to use scripting to return a UDT from lua and release ownership from the data created there. In my codebase, I have a very specific pipeline that ends with a pointer being de allocated a specific way. (think of a conveyor belt with no return!)

I take it this is an impossible ask from sol2 after all?

**Comment by ThePhD** [comment]
No, it's not impossible; I'm just saying that a `std::unique_ptr` calling its destructor should be fine if there's no pointer inside (that is, if it's been `.release()`d it'd be a `nullptr` inside and that makes the destructor a no-op).

My contention here is that, somewhere in the programming stack, you are either not calling `.release()` or there is a copy of this point value somewhere that's causing a double-deletion. From the code you showed me, it _looks_ fine and should delete fine. I'm trying to dig into things to see if I have an accidental double-delete bug somewhere...

**Comment by TheMaverickProgrammer** [comment]
gotcha! I'd think that if there was a double delete on my end, my game would have been crashing a lot sooner. I'm always `release()`ing because those 2 functions are the only way a `unique_ptr` type is able to be added to the Field. I'll continue to keep an eye out in my code as well. thank you

**Comment by Smertig** [comment]
@TheMaverickProgrammer BTW, you are passing dereferenced `release()`d pointer in your functions. That's really strange, because you should do something like `delete &ref` later (looks weird). I think, you have memory leak here.

**Comment by TheMaverickProgrammer** [comment]
> 
> 
> @TheMaverickProgrammer BTW, you are passing dereferenced `release()`d pointer in your functions. That's really strange, because you should do something like `delete &ref` later (looks weird). I think, you have memory leak here.

It is strange but that's exactly what I'm doing right now. I recognize it's not standard or clean to do but it solved a polymorphic problem I was facing. Without script support the game runs fine so there's no leak there.

**Comment by protoBASILISK** [comment]
There was a bit of a mixup at one point that tangled things up, it was ending up bypassing the pointer `release()` but now it works fine that the tangle got sorted out; sol in fact doesn't try to delete smart pointers that had `release()` called on them.
Thanks for the insights on it though.

**Comment by TheMaverickProgrammer** [comment]
Yes it ended up being my own fault. I had overloads for the function to take in the scripted enemy type specifically for sol - and the order ended up putting the wrong object type in the wrong overload causing this issue. The docs DO mention order matters but I am blind.
