### ISSUE TITLE
How can I bind a static instance of a class?

### ISSUE THREAD

**Issue by Wantcha** [ThePhD/sol2#1165]
I have a static SceneManager that I retrieve with SceneManager::Get(). Is it possible to create a binding similar to `SceneManager.LoadScene()` in Lua that calls `SceneManager::Get().LoadScene()`?

**Comment by ThePhD** [comment]
You can create a getter, and checker (no pusher) that only references the static class:

https://github.com/ThePhD/sol2/blob/develop/examples/source/customization_global_transparent_argument.cpp

Then, every time sol2 interacts with it, it'll just yoink it from global storage. You can fill the `pusher` in that example with whatever you like, or just remove it and it should work too...

**Comment by Wantcha** [comment]
> You can create a getter, and checker (no pusher) that only references the static class:
> 
> https://github.com/ThePhD/sol2/blob/develop/examples/source/customization_global_transparent_argument.cpp
> 
> Then, every time sol2 interacts with it, it'll just yoink it from global storage. You can fill the `pusher` in that example with whatever you like, or just remove it and it should work too...

Sorry to return to a thread you've closed, but I'm not sure I understand what is happening in the code you linked. The getter, pusher and checker are never called, so how are they being used? Not only that, but in the Lua script run in `main()`, I'm not seeing how I can use the syntax mentioned in my issue.

**Comment by ThePhD** [comment]
> "The getter, pusher, and checker are never called, ..."

I ran the example, and it is running for me:

![G6V4Gmk](https://user-images.githubusercontent.com/2886436/113511354-683fa300-952d-11eb-8d03-6d1a0fb89179.png)
![KG9RvMd](https://user-images.githubusercontent.com/2886436/113511355-683fa300-952d-11eb-9753-8f935114e66b.png)
![APWB1di](https://user-images.githubusercontent.com/2886436/113511356-683fa300-952d-11eb-9003-83473188f3ee.png)

Your issue, as I understand it, is that you need the ability to, whenever you get a `SceneManager*` or `SceneManager&` to interact with Lua, you need to call `SceneManager.get()`. The point of the example is that you can override the `sol_lua_get` customization point to retrieve `SceneManager*` (and you will also have to write one for `SceneManager&`). You can then just do `return SceneManager::get()` from the `sol_lua_get` function.

Does that make sense?

Also, I'm slightly worried you're using a (very outdated) version of sol2, if the customization points are never called. You need to be using version 3.x or better; I don't offer support for the older versions (version 2.x) here.

**Comment by Wantcha** [comment]
What I meant is that I don't understand how they are called. You define those functions, but you never call them in main. How does the program know about them?

**Comment by ThePhD** [comment]
These are called "extension points". In templated code, you can do things like call a function, but it's actually resolved when you use types with it. By defining these extension points ahead of time, other code can check to see if these functions exist and, if they do, call them.

There's whole libraries built around the ability to write extension methods. You use them all the time, too, even if you don't know it. For a high-speed overview of many different kinds of extension points, see:

https://www.youtube.com/watch?v=aZNhSOIvv1Q

**Comment by ThePhD** [comment]
(If you need something more fundamental to teach you, I don't have that; I learned by breaking my face against the C++ tide again and again, being wrong, embarrassing myself utterly and generally being a, and I mean this in the best possible way, fucking stupid idiot.

I don't have any good book recommendations or anything. Though, other people might: https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list)
