### ISSUE TITLE
how to bind sol2 with SQL to return table of tables

### ISSUE THREAD

**Issue by etorth** [ThePhD/sol2#1166]
Thanks for the sol2 repo, this is the best lua-bind I ever used.

Currently I am trying to let my script to support SQL. I would like to return ```a table of tables``` from C++ to lua.
But during test, I found in lua the returned value is just a ```nil```.

I tried all types I know in sol like ```sol::nested```, ```sol::as_table_t```, like following, but none works for me.
```cpp
sol::nested<std::vector<std::map<std::string, sol::object>>> queryResult; // used to return to lua, represent the table of tables
```

The broken code is here: [database API: dbQueryString](https://github.com/etorth/mir2x/blob/ea8303990ecadf3965183d67f431e93884df860d/server/monoserver/src/serverluamodule.cpp#L87-L128)

In the databse, what I have and already stored in the ```queryResult``` is:
```text
fld_dbid    fld_account  fld_password
----------  -----------  ------------
1           admin        admin
2           test         123456
3           good         123456
```

What I would like C++ returns to lua is a table of tables:

```lua
{
    {fld_dbid=1, fld_account='admin', fld_password='admin'},
    {fld_dbid=2, fld_account='test', fld_password='123456'},
    {fld_dbid=3, fld_account='good', fld_password='123456'},
}
```

what C++ type I should use for the ```queryResult```?

Thanks,
Etorth

**Comment by ThePhD** [comment]
It should just be `sol::as_nested(std::move(query_result))`, and that should be it... though, I actually don't remember if I pushed things...

**Comment by etorth** [comment]
aha, my bad, I am doing something like this:

```lua
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> local x = 12
> print(x)
nil
```
