### ISSUE TITLE
how to require one lua from another lua

### ISSUE THREAD

**Issue by uniqss** [ThePhD/sol2#1169]
hello! I wrote some code to execute a lua file, it works. Today I tried to require another lua in the previous lua file, it failed.
cpp:
`
int test_globals(sol::state_view lua)
{
	lua.script_file("test_globals.lua");
	return 0;
}
`
test_global.lua:
`
local hello = require("hello.lua")
local world = hello.world()
print(world)
`
hello.lua:
`
local Module = {}
print(" helo.lua begin ============================")
function Module.world()
	ret = 1234
	return ret
end
print(" helo.lua end ============================")
return Module
`
I tried `require "hello"` , `require "hello.lua"`, `require("hello")`, `require("hello.lua"`, all failed. Any help appreciated!

**Comment by uniqss** [comment]
my code is here:
https://github.com/uniqss/jasslua.git

**Comment by uniqss** [comment]
![image](https://user-images.githubusercontent.com/48117715/114148881-da105600-994c-11eb-93c1-b7f3f80437f6.png)
Problem solved！ Thanks anyway!

**Comment by ThePhD** [comment]
I was about to say: yes, you can add the current directory to search path or [add a "loader"](https://github.com/ThePhD/sol2/blob/develop/examples/source/require_override_behavior.cpp#L48).
