### ISSUE TITLE
Clarity in the docs about isolated/not isolated execution.

### ISSUE THREAD

**Issue by billw2012** [ThePhD/sol2#117]
In the reference docs about state (http://sol2.readthedocs.io/en/latest/api/state.html), it isn't really clear how one *does* run isolated code (script function just specifies that the code run is NOT isolated). Also it kind of looks like an editing mistake in the docs for load/load_file, perhaps something was accidentally cut out:
`it returns a load_result proxy that can be called, turned into a sol::function,. or similar, will run the loaded code.`

**Comment by ThePhD** [comment]
I'll improve those docs. There's no abstraction for isolated code execution (yet). It was sort-of thought up here: #50. To be clear (and what I will write there) is that each `sol::state` is not isolated from the code that gets run inside of itself. By default, it will be called and it will affect all of the environment within the `lua_State*` it represents.

**Comment by ThePhD** [comment]
Fixed in https://github.com/ThePhD/sol2/commit/69b45e4d66e38e2668decb0eab87e6471730fe1f

**Comment by billw2012** [comment]
Ah okay so it is still isolated to a single sol::state, which is what I expected before I read the docs more closely and noticed this. I assumed the docs for the script function meant that it WASN'T isolated to that state object. Thanks for the extra info!
