### ISSUE TITLE
`size_t` / `lua_Integer` conversion problem

### ISSUE THREAD

**Issue by timblechmann** [ThePhD/sol2#1178]
i'm trying to port some code from `luabind` to `sol`. however there's one issue where i'm not sure how to resolve: some of this code return `size_t(-1)` to represent "invalid" indices, similar to `std::string::npos`.

the problem is that `unqualified_pusher::push` performs a range check on the integer (`stack_detail::integer_value_fits`) and for my out-of-range values it would convert the value to `lua_Number`. i wonder what's a good approach for such a use-case? i could remove the `std::is_signed_v<T>` check from `integer_value_fits`, but maybe there's a better way to achieve this?

_Originally posted by @timblechmann in https://github.com/ThePhD/sol2/discussions/1176_

**Comment by timblechmann** [comment]
@ThePhD wrote:
> By the time the number gets to me (is handed to sol2), it's an unsigned value. I can't tell that the "intent" is for it to be a sentinel value of -1; I just see a heckin' gigantic positive number.

yes, i know it's a tricky issue and there are good reasons for the current behaviour. unfortunately i cannot easily migrate the codebase away from using `size_t(-1)`

> Lua since Lua 5.3 has LUA_MAXINTEGER and LUA_MININTEGER and a concept of 63-bit unsigned integers. What version of Lua are you using? Maybe there's something I can do to specialize for Lua 5.3 and above to give pass-through integer access here.

i'm trying to port from luabind/lua5.1 to sol/lua5.4. so lua-5.3 would possible. are you thinking about exposing `LUA_UNSIGNED` to sol?

-----

my current approach:
```
diff --git a/include/sol/stack_push.hpp b/include/sol/stack_push.hpp
index afb9985..0c7a736 100644
--- a/include/sol/stack_push.hpp
+++ b/include/sol/stack_push.hpp
@@ -45,7 +45,11 @@ namespace sol { namespace stack {
        namespace stack_detail {
                template <typename T>
                inline bool integer_value_fits(const T& value) {
+#if defined(SOL_LUAINTEGER_SIZET_SUPPORT)
+                       if constexpr (sizeof(T) < sizeof(lua_Integer) || (sizeof(T) == sizeof(lua_Integer))) {
+#else
                        if constexpr (sizeof(T) < sizeof(lua_Integer) || (std::is_signed_v<T> && sizeof(T) == sizeof(lua_Integer))) {
+#endif
                                (void)value;
                                return true;
                        }
```

**Comment by ThePhD** [comment]
Seems reasonable enough, lemme push something out quickly before the end of today.

**Comment by ThePhD** [comment]
"I'll push something tonight" ahhahahahhahaaaaaaaaaaaaa

aah.... sorry.

It's fixed, define `SOL_ALL_INTEGER_VALUES_FIT` to `1` to get this turned up!
