### ISSUE TITLE
Passing derived userdata instance to function that takes base class throws when SOL_CHECK_ARGUMENTS is defined.

### ISSUE THREAD

**Issue by billw2012** [ThePhD/sol2#118]
The below throws on the last line of the script (when SOL_CHECK_ARGUMENTS is defined), where I pass a script created instance of the derived class to a function that expects a pointer to the base class. I think this should work, and indeed I get the expected results when the macro is not defined.
(define MY_INFO to printf and this should compile for you as is)

```C++
struct Base
{
	Base(int y) : y(y) {}

	void base_func()
	{
		MY_INFO("Base::base_func()");
		x = 1;
	}

	virtual void func()
	{
		MY_INFO("Base::func()");
		z = 1;
	}

	int x = 0;
	int y = 0;
	int z = 0;
};

struct Derived : Base
{
	Derived(int y) : Base(y) {}

	void derived_func()
	{
		MY_INFO("Derived::derived_func()");
		x = 5;
	}

	virtual void func()
	{
		MY_INFO("Derived::func()");
		z = 2;
	}
};

void test_func(Base* obj)
{
	MY_INFO("test_func(Base *obj): %d, %d, %d", obj->x, obj->y, obj->z);
}

void test_inheritance()
{
	using namespace sol;

	state lua;
	lua.set_function("print", [](std::string str) {
		MY_INFO("lua print: %s", str.c_str());
	});
	lua.new_usertype<Base, int>("Base", 
								"base_func", &Base::base_func, 
								"func", &Base::func);
	lua.new_usertype<Derived, int>("Derived",
								   "derived_func", &Derived::derived_func,
								   "base_func", &Base::base_func,
								   "func", &Derived::func);
	lua.set_function("test_func", test_func); // ] = sol::overload([](Derived& obj) { test_func(obj); }, test_func);

	lua.script(R"__(
base_inst = Base.new(2)
base_inst:base_func()
base_inst:func()
derived_inst = Derived.new(3)
derived_inst:base_func()
derived_inst:derived_func()
derived_inst:func()
test_func(base_inst)
test_func(derived_inst)
)__");
}
```

**Comment by ThePhD** [comment]
That's because you don't specify bases. SOL_CHECK_USERTYPES can't be sure you've done the right thing because not only do the metatable names not match but you've specified no bases.

This is catastrophic for other reasons too. If you had 2 base classes (e.g., multiple inheritance) and that cast went through unchecked, you could get mis-matched base pointers, in which case you'd be truly screwed. Try adding `sol::bases<Base>` to the `new_usertype<Derived>( ... )` function.

**Comment by billw2012** [comment]
I swear the docs used to recommend using automatic inheritance management except in the case of disabled exceptions, which I presumed would extend to this as well. Sorry, I should have rechecked (or read better in the first place)!

**Comment by ThePhD** [comment]
Oh no, don't blame yourself. Things have been flip-floppy since I've started to try to work on management of classes and inheritance and speed (see #116). I am trying to work towards and implementation that will scale infinitely (like I had before) but the speed cost is driving me up the wall. :(

**Comment by ThePhD** [comment]
It also doesn't help that VC++ and clang++ haven't implemented the equivalent of g++'s `__bases` compiler-intrinsic, which lists all base classes as a parameter pack in C++. If I had that, I could EASILY do the derived mumbo-jumbo without having the user to explicitly specify it all the time...

**Comment by ThePhD** [comment]
Temporarily fixed, but might change in the future as we continue to examine what makes for the best speed.
