### ISSUE TITLE
Can we force the property setter to run when the property's internal variables are changed?

### ISSUE THREAD

**Issue by ChronicallySerious** [ThePhD/sol2#1181]
```cpp
// Bind the property `position` to a 3 dimensional vector returned and set by the accessors
sol::usertype<TransformComponent> transformComponent = rootex.new_usertype<TransformComponent>(
    "TransformComponent",
    sol::base_classes, sol::bases<Component>(),
    "position", sol::property(&TransformComponent::getPosition, &TransformComponent::setPosition));
```
Then inside Lua:
```lua
-- This is currently NOT using `TransformComponent::setPosition` to update the value back inside the component
transform.position.x = 0.5 
```

Is there a way to make this work?

Should `TransformComponent::getPosition()` return the position by value or by reference? How can I ensure that `TransformComponent::setPosition` still gets to handle the change?

The reason why I ask this is that I am wanting to use a Lua [tweening library](https://github.com/rxi/flux) and getting this to work will reduce a lot of the surrounding code we'd need to write to get basic tweening working on the native components:

```lua
--[[
This will change the value of `entity.transform.position.x` to 3.0 within 4 seconds. 
If setting the value of `position.x` also called into 
`TransformComponent::setPosition` then this would be very syntax efficient.
--]]
flux.to(entity.transform.position, 4, { x = 3 })

-- Otherwise, we have to do this hack
position = RTX.Vector3.new()
flux.to(position, 4, { x = 3 })

--[[
In addition to the line above, we will also need to do this 
in the update loop to ensure that the position value was updated
--]]
entity.transform.position = position
```

Compiler: MSVC (VS 2019)
OS: Windows 10

Thank you for your work on this awesome library!

**Comment by ThePhD** [comment]
This looks very similar tot his request: https://github.com/ThePhD/sol2/issues/1162#issuecomment-813041981

This might have to be something I wrote an example for...

**Comment by ChronicallySerious** [comment]
Ah thank you for linking that. It's probably the exact same scenario with just different names (I also happen to have something which needs to recalculate the matrix whenever the position is changed)
