### ISSUE TITLE
How to refer to the project?

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#1186]
Hi,

I noticed your preparing a v4 release. Super awesome. Do you plan on referring to this release as Sol4? The naming seems to have become problematic. Since there are no other active forks of the original Sol project, perhaps you could go back to Sol? I think at this point the project deserves to take the title. I understand leaving the repository as sol2. Alternatively you could set up a sol repository and make sol2 a mirror.

Just some thoughts. 

Regards,
Russ

**Comment by RussellHaley** [comment]
`Sol v4` sounds cool to me. :-)

**Comment by ThePhD** [comment]
Yeah, maybe I should just do `sol`? idk. It's a sort-of common name in places, and I think a lot of package managers already have it taken? At the very least, I'd need to check conan, vcpkg, build2 and cargo.

**Comment by ThePhD** [comment]
(cargo, for the eventual Rust version of this.

Also, RIP: https://crates.io/crates/sol)

For the `sol` name:

| Conan | Not taken |
|-|-|
| Cargo  | Unavailable |
| vcpkg  | Available |
| build2  | Available |

**Comment by Spammed** [comment]
Yes, but the name has changed:

> Revision: 69ecbbae10e837a2fc5f0b62ce886db82291df8e
> Author: Will Usher <willusher.life@gmail.com>
> Date: 14.02.2019 05:45:55
> Message:
> Name change to embree-rs

According to the git log from [github.com/Twinklebear/embree-rs](https://github.com/Twinklebear/embree-rs), which can be found at [crates.io/crates/sol](https://crates.io/crates/sol), it has been renamed to 'embree-rs'.
Maybe because 'Sol' already existed for a Lua-C++ interface?
It is certainly worth asking the developer.

**Comment by Twinklebear** [comment]
Hi folks, my Embree bindings moved to the https://crates.io/crates/embree crate name some time ago (that crate was originally taken when I started the project, so I similar situation as here). Anyways, that project uses the 'embree' name, so the sol crate name is unused and I'm happy to pass the crate name on to this project.

Who should I add as an owner of the crate? I tried to add @ThePhD just now but there doesn't seem to be a user with that name on crates.io

**Comment by ThePhD** [comment]
Oh! I can register myself on it lickety split and take the name if you like!!!

**Comment by ThePhD** [comment]
... Huh, that was easy. @Twinklebear I should be @ThePhD there, now!

**Comment by Twinklebear** [comment]
Great! You should get an invite from crates.io to become an owner of the crate, then I can remove myself after you accept.

**Comment by ThePhD** [comment]
Woo, I got it!

Thank you so much!!! 💚💚💚💚

**Comment by RussellHaley** [comment]
Thanks @Twinklebear!
