### ISSUE TITLE
Idea for improving compilation times

### ISSUE THREAD

**Issue by ChronicallySerious** [ThePhD/sol2#1189]
Is it feasible to output the pure Lua C binding code which  is equivalent to a bit of sol3 code?

E.g. Creating a new user type and binding functions to it through sol3 is easy. However I assume that the compilation time is mostly sunk inside the template magic. 

So can we expand all the templates manually or through some tool before sending the template instantiations to the compiler? This means there'd only be Lua C API code being sent to the compiler. And this Lua C API regenerated code would be reused again and again unless the programmer orders a refresh (if the binding code was needed to change). 

Thus is of course only doable once the development of the Lua bindings has stagnated according to the programmer. However it would be even better to regenerate the Lua C API code on demand.

**Comment by ThePhD** [comment]
That may help but honestly there's a lot of places I could probably fix without forcing to spill it out. One of the ways to get what you want is to stick the binding code in separate `.cpp` files and let it only regenerate when the impacted or specific headers are affected.
