### ISSUE TITLE
usertype new_index and index no longer work for integer indices

### ISSUE THREAD

**Issue by tfgast** [ThePhD/sol2#119]
They appear to have been broken in the mega commit e62740b

The following code fails, after throwing a sol::error with contents
lua: error: [string "v = vector.new()..."]:2: stack index -1, expected string, received number.
It works correctly if SOL_CHECK_ARGUMENTS is not defined.

```c++
  #define SOL_CHECK_ARGUMENTS
  #include "sol.hpp"
  using namespace sol;

  class vector {
     public:
      double data[3];

      vector() : data{0,0,0} {}

      double& operator[](int i)
      {
         return data[i];
      }
  };

  double my_index(vector& v, int i)
  {
     return v[i];
  }

  void my_new_index(vector& v, int i, double x)
  {
     v[i] = x;
  }


  int main() {
      state lua;
      lua.open_libraries(lib::base);
      lua.new_usertype<vector>("vector", constructors<types<>>(),
            meta_function::index, &my_index,
            meta_function::new_index, &my_new_index);
      lua.script("v = vector.new()\n"
            "print(v[1])\n"
            "v[2] = 3\n"
            "print(v[2])\n"
            );

      return 0;
  }
```

**Comment by ThePhD** [comment]
Erk. In the back of my head, I wondered... "but what if the user gives us string keys"? And then I backburner'd it while trying to do the performance stuff.

I'm all over it.

**Comment by ThePhD** [comment]
This should be all set with latest. Lemme know if something snaps that shouldn't have.
