### ISSUE TITLE
Append to table?

### ISSUE THREAD

**Issue by EliasD** [ThePhD/sol2#120]
Sorry if it has been asked before, but is it possible to append stuff to tables?  It's useful when adding elements into array-like tables. For example:
```c++
std::vector<int> someVector = {1, 2, 3, 4};
sol::table someTable = lua.create_table();
for(auto& elem : someVector) {
    someTable.append(elem);
}
```

**Comment by ThePhD** [comment]
That is not something that's possible, unfortunately. I can't think of a good way to implement it either, except by iterating through all of the values already in the table, keeping track of the highest number index in the Lua table, and then "adding" to it with the `highest index++;` and so on through the loop...

Just talking about it makes me think the actual performance would be kind've dirt.... Also, tables may even have [holes in them](http://stackoverflow.com/a/6112987/5280922) which is why you'd have to loop over every key to know for sure... and even then it's not clear whether you can achieve the full iteration and get the "True Last Index". It's a really unfortunate situation.

**Comment by EliasD** [comment]
LuaBridge has this functions implemented [like this](https://github.com/vinniefalco/LuaBridge/blob/04b47d723d35b47ff8efce63d54ef264a59152b5/Source/LuaBridge/detail/LuaRef.h#L957). I'm not sure how it works and it will probably fail for table with holes, but it's still useful to have this function and it looks pretty efficient. 

This works:
```c++
sol::table arr = lua.create_table();
for (int i = 0; i < 10; ++i) {
    auto L = lua.lua_state();
    sol::stack::push(L, arr);
    sol::stack::push(L, i); // will work as arr[i + 1] = i;
    luaL_ref(L, -2);
    lua_pop(L, 1);
}
```

This can be optimized by adding function like append(Args&&... args) which will push the table and then continuously append stuff to the table without popping the table itself. Something like this (but with variadic args):
```c++
auto L = lua.lua_state();
sol::table arr = lua.create_table();
sol::stack::push(L, arr);
for (int i = 0; i < 10; ++i) {
    sol::stack::push(L, i);
    luaL_ref(L, -2);
}
lua_pop(L, 1);
```
I checked out what happens if you do it for table with holes: Lua tries to fill all holes in array part. For example if you have arr with arr[3] and arr[5] set, it will insert new stuff into 1, 2, 4, 6, etc. positions.
This is pretty strange. :D

**Comment by ThePhD** [comment]
Maybe a more accurate name would be `table::fill( T v )`? That way, we don't need to have the hard-guarantee of "append", but someone does get to just "stuff a value in this table here".

**Comment by EliasD** [comment]
Yeah, sounds good, but I can see that it may be confusing for users, because "fill" sounds like it may overwrite some previous stuff (especially when inserting lots of values at once) or fill in some range. Something like `insert_into_free_index` sounds better, but it's too long, so we should look for the name which has the same meaning. 
Maybe even `table::insert` will do if we'll write something like "inserts value into free array index" in docs.

Btw, I'm still not sure that this approach has some drawbacks or fail situations, so I'll take a closer look at it later.

**Comment by ThePhD** [comment]
This `add`/`insert` thing is really volatile:

![Really, really volatile](http://i.imgur.com/krVVAni.png)

It will definitely add the thing, but sure as hell it doesn't behave the same between lua versions and impls apparently. And with purposefully inserted nils, things get even funnier:

![Hah](http://i.imgur.com/rNSPoa7.png)

But, that behavior is not... too bad, still! Just have to note that holes in the table lead to weird behavior.

**Comment by EliasD** [comment]
Yeah, that's weird... any idea why it works like this? So far I don't have a clue. :D

Btw, you can look at it this way: for `table::size` to work properly, you have to have continuous sequence. And this requirement is okay, so why not make it same for `table::insert`/`append`?

**Comment by ThePhD** [comment]
Sure, why not. I'll add it in: can't really hurt.

**Comment by EliasD** [comment]
Awesome, thanks :D

**Comment by ThePhD** [comment]
Now part of this release: https://github.com/ThePhD/sol2/releases/tag/v2.8.5

**Comment by EliasD** [comment]
Neat! (Btw, generated header has stray endif on 346th line for some reason)

One common use case for it is to convert ```std::vector<T>``` to Lua array. Of course, I can do this:
```c++
for(auto& elem : vec) {
    table.add(elem);
}
```
But that's not the most efficient way to do it because of table being pushed and popped again and again. Using variadic stuff is not possible here. Maybe there's some way to optimize it using what we have or maybe it'll be good to introduce some overload/function which will convert ```std::vector``` to Lua array? (it can also preallocate vec.size() elements) Something like: 
```c++
auto table = lua.create_from_vector(vec);
```

**Comment by ThePhD** [comment]
`lua["my_arr"] = vec;`

Does it for you automatically.

**Comment by ThePhD** [comment]
Release has been updated; sorry about that stray `#endif`.

**Comment by EliasD** [comment]
Wow, that's cool :D
How do I do something like this, though?
```c++
sol::table arr = lua.create_table();
arr = vec; // doesn't work!
```

**Comment by EliasD** [comment]
Huh, that's awesome! Though, it's somewhat not what I'm used to... :D
I think there needs to be some stuff about std::vector/STL stuff possible in docs. 
Once I figure out some stuff about sol2, I'm probably going to write some tutorials which are really needed to show users that such stuff is possible. :)

**Comment by Mark-Joy** [comment]
When assign: `lua["my_arr"] = vec;` table's index start from 1. How to make it start from 0?

**Comment by ThePhD** [comment]
@Mark-Joy You don't. `ipairs()` function iterates from 1, all other manner of Lua functions start from index 1: starting from 0 will break Lua. It's not worth it.

**Comment by Mark-Joy** [comment]
@ThePhD 
Thank you.
I tried the below code but got error in lua, how to fix this?
in c++:
```
vector<double> vec{ 1,3,5,7,9 };
lua["vec"] = vec;

```
in lua:
```
for i, value in ipairs(vec) do
...
end
```
ERROR " bad argument #1 to 'ipairs' (table expected, got userdata)"

**Comment by ThePhD** [comment]
You're using Lua 5.1: Lua 5.1 does not support anything other than tables to `ipairs` or `pairs`. Either upgrade to Lua 5.2 or 5.3, or force your vector to be degraded down to a table by using `as_table`:

````
vector<double> vec{ 1,3,5,7,9 };
lua["vec"] = as_table( vec );
````

This is mentioned in the container documentation, beneath the complete example: http://sol2.readthedocs.io/en/latest/api/containers.html#a-complete-example

Note that a "manual iteration scheme" mentioned looks like this:
````
for i=1,#vec do 
     print(i, vec[i]) 
end
````

**Comment by Mark-Joy** [comment]
Thanks again! I got it working now
