### ISSUE TITLE
Incorrect path to Project.cmake?

### ISSUE THREAD

**Issue by sponji** [ThePhD/sol2#1200]
I have added sol2 as a subdirectory in my project and seems like CMakeLists.txt line 27 should use `CMAKE_CURRENT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR`, or am I missing something? https://github.com/ThePhD/sol2/blob/430b55a49609daacea6fd3ee2c9d137db4db9c83/CMakeLists.txt#L27

**Comment by ThePhD** [comment]
Yep, this is covered in #1196 - gotta merge it in a hot second.

**Comment by sponji** [comment]
Ah, didn't look at pull requests. Works fine now, thank you!

**Comment by ThePhD** [comment]
No problem, hope it works great for you! 🎉
