### ISSUE TITLE
Can't use lua_State* as an arg when calling member functions

### ISSUE THREAD

**Issue by poopings** [ThePhD/sol2#1201]
```cpp

class entity {
public:
	int get(lua_State* L) {
		int n = lua_tointeger(L, 1);
		printf("working, %i\n", n);
		return 1;
	}
};

entity* ent = new entity;

int main() {
	sol::state lua;
	lua.open_libraries();

	lua["ent"] = ent;
	lua.new_usertype<entity>("entity",
        	"get", &entity::get
	);

	lua.script("ent:get(20)");
}
```

Essentially the problem is that the function is never called, or throws an exception somewhere. Is there any way to avoid this? Using a global function/non-member function works fine.

**Comment by ThePhD** [comment]
Replace `lua_State*` with `sol::this_state`. - https://sol2.readthedocs.io/en/latest/api/this_state.html
