### ISSUE TITLE
A compiling warning-C4172

### ISSUE THREAD

**Issue by wzhengsen** [ThePhD/sol2#1207]
* Windows64
* sol2-4.0-alpha
* Lua54
* vs2019
* Compile with Release (In debug mode, I didn't find this warning)

>Screenshots:
![image](https://user-images.githubusercontent.com/30433761/120097461-287aed80-c163-11eb-8d43-3332f9c7b20a.png)

**Comment by Spammed** [comment]
This one:
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4172
`returning address of local variable or temporary`
Tip:
`Redesign the function so that it does not return the address of a local object.`
