### ISSUE TITLE
Pushing arguments into Lua call from vector.

### ISSUE THREAD

**Issue by Tonyx97** [ThePhD/sol2#1208]
Hi, I'm wondering if there is any way using sol to push arguments properly and then do my call normally using 'call' method or '()' operator. The problem is that the arguments I push manually using sol::stack::push are left behind due to base_t::push (I don't really know what's this) and other pushes. I have a simple method that pushes all arguments properly using variadic templates.

```cpp
template <typename... A>
	void call_fn(const std::string& name, A&&... args)
	{
		if (!is_running())
			return;

		if (sol::safe_function fn = (*vm)[name]; fn.valid())
			if (auto res = fn(args...); !res.valid())
				dispatch_error(res);
	}
```

I use this function from native C++ code so it's not a problem when pushing arguments, the problem comes when I don't know which parameters I'm pushing in compile-time. In my case this is a networking situation:
-1. Server pushes all arguments to a packet.
-2. Client reads all arguments and pushes them into a std::vector<std::any>.

Now the only thing I have here is the vector of parameters.

```cpp
void script::call_fn_va(const std::string& name, const std::vector<std::any>& va)
{
	if (!is_running())
		return;

	if (sol::safe_function fn = (*vm)[name]; fn.valid())
	{
		auto L = vm->lua_state();
		
		for (const auto& arg : va)
		{
			sol::stack::push(L, std::any_cast<bool>(arg));
		}

		if (auto res = fn(); !res.valid())
			dispatch_error(res);
	}
}
```

I started with this function (I only send bools for testing purposes), now, since "fn()" is "destroying" the parameters I push, is there any way to call the function without appealing to lua raw functions? I want to be able to dispatch errors as well and doing that in raw lua is kinda annoying, I rather stick to sol and leave the abstractions to the library itself. Thanks.

**Comment by ThePhD** [comment]
You need to combine 2 things.

## `sol::as_args`

As seen here: https://github.com/ThePhD/sol2/blob/f56b3c698c2116f41aad3bf731ba8400e68c498b/examples/source/args_from_container.cpp#L10

And documented here: https://sol2.readthedocs.io/en/latest/api/as_args.html

Then, you need to... 

## Write a pusher/getter/checker for `std::any`

Someone else did some of that work here for [writing a customization point for std::any to serialize things](https://github.com/ThePhD/sol2/discussions/1182). Make sure to read the whole discussion so you can also add the tag type too.
