### ISSUE TITLE
Error messages seem to be printing incorrectly

### ISSUE THREAD

**Issue by DeathEgg** [ThePhD/sol2#1216]
I've been having issues with sol2's error printing. The error messages seem to be printing the the beginning line of whatever script was given to it instead of the name of whatever variable or function is going wrong a lot of the time. A short example code snippet is posted:

```cpp
#include <fstream>
#include <sol/sol.hpp>

void PrintError(sol::protected_function_result const &result)
{
	if (!result.valid())
	{
		sol::error err = result;
		std::cerr << err.what() << std::endl;
	}
}

int main(int, char **)
{
	// set global lua state
	sol::state lua;

	lua.open_libraries(sol::lib::base, sol::lib::math);

	std::string script;

	// read in script and save it as string
	if (std::ifstream istrm("../test.lua", std::ios::binary); istrm.is_open() && istrm.good())
	{
		std::stringstream ss;
		ss << istrm.rdbuf();

		istrm.close();

		script = ss.str();

		// run without environment
		auto const result1 = lua.safe_script(script);
		if (result1.valid())
		{
			auto const result2 = lua["Test"]();
			PrintError(result2);
		}

		// load environment
		sol::environment env(lua, sol::create, lua.globals());

		// run with environment
		auto const result3 = lua.safe_script(script, env, sol::script_pass_on_error);
		if (result3.valid())
		{
			auto const result4 = env["Test"]();
		}
	}

	return 0;
}
```

My test Lua file, "test.lua":

```lua
local thisIsHereToShowThatItsPrintingTheWholeScript = 2

function TestTest()
	wrong()
end

function Test()
	TestTest()
end
```

And the outputted error message:

```
[string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: global 'wrong' is not callable (a nil value)
stack traceback:
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: in function 'base.TestTest'
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:12: in function 'base.Test'
[string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: global 'wrong' is not callable (a nil value)
stack traceback:
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: in global 'TestTest'
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:12: in function <[string "local thisIsHereToShowThatItsPrintingTheWhole..."]:10>
```
        
I'm using Visual Studio 2019 (v142) with MSVC using /std::c++17 to compile for x64. I don't know if these are how the error messages are supposed to appear or if there's something I'm doing wrong.

**Comment by ThePhD** [comment]
That's the basic behavior. When you don't give sol2 the file name directly, it reads a portion of the script to tag the name. The stack trace still has the function you called, though:

```cpp
stack traceback:
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: in global 'TestTest'
        [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:12: in function <[string "local thisIsHereToShowThatItsPrintingTheWhole..."]:10>
```

If you mean "I want a traceback from C++", that is beyond the scope of what I can provide. C++ only got tracebacks in C++23 (the upcoming 2023 version of the standard: http://eel.is/c++draft/stacktrace), and this is a C++17 library: you'll need to write a default error handler yourself, and then see if you can't use it to extract stack trace information relevant to C++. It will only provide Lua stack trace information for now.

**Comment by DeathEgg** [comment]
> 
> 
> That's the basic behavior. When you don't give sol2 the file name directly, it reads a portion of the script to tag the name. The stack trace still has the function you called, though:
> 
> ```c++
> stack traceback:
>         [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:6: in global 'TestTest'
>         [string "local thisIsHereToShowThatItsPrintingTheWhole..."]:12: in function <[string "local thisIsHereToShowThatItsPrintingTheWhole..."]:10>
> ```
> 
> If you mean "I want a traceback from C++", that is beyond the scope of what I can provide. C++ only got tracebacks in C++23 (the upcoming 2023 version of the standard: http://eel.is/c++draft/stacktrace), and this is a C++17 library: you'll need to write a default error handler yourself, and then see if you can't use it to extract stack trace information relevant to C++. It will only provide Lua stack trace information for now.

Gotcha. Is there any way to replace the portion of the script with my own name instead?
