### ISSUE TITLE
there is not a safe_require_file api.

### ISSUE THREAD

**Issue by Patrick08T** [ThePhD/sol2#1220]
When I use the require_file api in my project, it will call lua_error(L), if the file is not exist.

`object safe_require_file(const std::string& key, const std::string& filename, bool create_global = true, load_mode mode = load_mode::any) {
		...
                no lua_error
		}`
if there is any function like this?

**Comment by ThePhD** [comment]
... Huh. You know, I should probably add this. At the moment, you can get around this by using `require` without the `_file` bit, and pass in the script blob directly.

**Comment by Patrick08T** [comment]
Thanks a lot. I write a function with no lua_error by my self. And now, it's running in my project.
