### ISSUE TITLE
Problem with new_usertype

### ISSUE THREAD

**Issue by MininDMhvh** [ThePhD/sol2#1229]
I have a class where 1 variable is another class. How can I bind access to the field of this class?
My class and how I try bind :
```

class CUserCmd_lua
{
	
public:
	CUserCmd* cmd;
}

this->m_state.new_usertype<CUserCmd_lua>("usercmd"),
		"command_number", &CUserCmd_lua::cmd->command_number
);

```

and I got E0245 error in VS

**Comment by Rochet2** [comment]
This is a similar issue: https://github.com/ThePhD/sol2/issues/1162#issuecomment-813041981

**Comment by ThePhD** [comment]
Yes, either that or use `sol::property` to set up access.

**Comment by ThePhD** [comment]
You can find some docs on properties here: https://sol2.readthedocs.io/en/latest/api/property.html
