### ISSUE TITLE
Add search to Documentation

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#123]
Currently, the documentation has no search feature. It'd be really useful to have it.

**Comment by EliasD** [comment]
http://sol2.readthedocs.io/en/latest/search.html
You can search for stuff here

**Comment by Nava2** [comment]
I have no idea how I missed it at the bottom. I wish it was in the footer. :+1:

**Comment by ThePhD** [comment]
I unfortunate am not an expert in ReadTheDocs layouts. If someone knows a good one or knwos how to modify one to be good, I'm all ears.
