### ISSUE TITLE
How to construct a userdata of vector<double>  in lua

### ISSUE THREAD

**Issue by oPiZiL** [ThePhD/sol2#1232]
```
sol::state lua;
lua.set_function("test", [](const std::vector<double> &input) {
    return 0;
});

```

in lua

```
test({1,1,1})
```

> stack index 1, expected userdata, received number: value is not a valid userdata (bad argument into 'int(const std::vector<double>&)')

**Comment by oPiZiL** [comment]
https://github.com/ThePhD/sol2/issues/1054

**Comment by wzhengsen** [comment]
```c++
#define SOL_NO_CHECK_NUMBER_PRECISION 1
#include "sol/sol.hpp"
#include "lua.hpp"
#include <vector>

int main() {
    sol::state lua = {};
    lua.open_libraries();
    lua["test1"] = [](const std::vector<double> input) {
        double count = 0;
        for (auto d : input) {
            count += d;
        }
        return count;
    };
    lua["test2"] = [](const std::vector<double>& input) {
        double count = 0;
        for (auto d : input) {
            count += d;
        }
        return count;
    };
    lua.script("print(test1({1,2,3}));");// ok,output:6.0
    lua.script("print(test2({1,2,3}));");// error
    return 0;
}
```

**Comment by oPiZiL** [comment]
> ```c++
> #define SOL_NO_CHECK_NUMBER_PRECISION 1
> #include "sol/sol.hpp"
> #include "lua.hpp"
> #include <vector>
> 
> int main() {
>     sol::state lua = {};
>     lua.open_libraries();
>     lua["test1"] = [](const std::vector<double> input) {
>         double count = 0;
>         for (auto d : input) {
>             count += d;
>         }
>         return count;
>     };
>     lua["test2"] = [](const std::vector<double>& input) {
>         double count = 0;
>         for (auto d : input) {
>             count += d;
>         }
>         return count;
>     };
>     lua.script("print(test1({1,2,3}));");// ok,output:6.0
>     lua.script("print(test2({1,2,3}));");// error
>     return 0;
> }
> ```

so how can I construct `input` for test2 in lua

**Comment by ThePhD** [comment]
`test1` works because sol2 has special logic when you take a parameter by-value. It does a **conversion** from a table to a vector. It will do that conversion every time, and make you pay for it each time you call that function.

`test2` does not work because sol2 cannot take a Lua Table and turn it into a Pointer To `vector` (and then dereference it to give you a `vector&` or `const vector&`). In this case, you would need a function that explicitly creates a `vector` from a table, and then passes it to `test2`.

**Comment by ThePhD** [comment]
For example:

```
#define SOL_NO_CHECK_NUMBER_PRECISION 1
#include "sol/sol.hpp"
#include "lua.hpp"
#include <vector>

int main() {
    sol::state lua = {};
    lua.open_libraries();
    
    lua.set_function("to_vector_of_double", [](std::vector<double> vec) { return vec; } );

    lua["test1"] = [](const std::vector<double> input) {
        double count = 0;
        for (auto d : input) {
            count += d;
        }
        return count;
    };
    lua["test2"] = [](const std::vector<double>& input) {
        double count = 0;
        for (auto d : input) {
            count += d;
        }
        return count;
    };
    lua.script("print(test1({1,2,3}));");// ok,output:6.0
    lua.script("print(test2(to_vector_of_double({1,2,3})));");// error
    return 0;
}
```
