### ISSUE TITLE
Comparing function pointers

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#124]
What I'm trying to do:

```c++
const auto func1 = [](const int) -> int {};
const auto func2 = [](const int) -> int {};

lua.set_function("func1", func1);
lua.set_function("func2", func2);

lua.script("a = func1");

const sol::function& a = lua["a"];
if (a == func1) {
} else if (a == func2) {
} else { }
```

Currently, this fails to compile: 
`Invalid operands to binary expression ('const sol::function' (aka 'const basic_function<sol::reference>') and 'const (lambda at Test.cpp:65:9)')`

Is there a valid way to do this?

**Comment by ThePhD** [comment]
Yes: 

![Just store it in a Lua function first](http://i.imgur.com/g8hbh9L.png).

Lua only knows how to compare objects inside of its VM. If you want to compare directly to the function itself, however, you're out of luck: that stuff gets type-erased / value-erased behind a `lua_CFunction`.

**Comment by Nava2** [comment]
That works for me, I figured that was the case.

**Comment by Nava2** [comment]
I'd like to reopen this, this example fails:

```cpp
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    const auto& check_func = [&](const sol::object&) {};
    lua.set_function("check_func", check_func);
    const sol::function& s_check_func = lua["check_func"];

    const auto& accept_func = [&](const sol::function& f, const sol::object&) {
        if (f == s_check_func) // exception
        {
            std::cout << "yay\n";
        }
        else
        {
            std::cout << "oh no.\n";
        }
    };
    lua.set_function("accept_func", accept_func);

    lua.script("accept_func(check_func, {})");
```

The stack gets screwed up and for some reason the `operator==()` breaks.

**Comment by Nava2** [comment]
Interestingly, this passes: 

```C++
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    const auto& check_func = [&](const sol::object&) {};
    lua.set_function("check_func", check_func);
    const sol::function& s_check_func = lua["check_func"];

    const auto& accept_func = [&](const sol::function& f, const sol::object&) {
        if (s_check_func == f)
        {
            std::cout << "yay\n";
        }
        else
        {
            std::cout << "oh no.\n";
        }
    };
    lua.set_function("accept_func", accept_func);

    lua.script("accept_func(check_func, {})");
```

**Comment by ThePhD** [comment]
No repro in VC++ with lua 5.3.2: both work. What lua env, what compiler?

**Comment by Nava2** [comment]
Both Clang on OSX and VC++ 2015 Update 2. Lua 5.3.2, I believe. Will have to verify the Lua versions exactly, but definitely 53.

**Comment by Nava2** [comment]
Oh, this is on the latest tag of yesterday.

**Comment by Nava2** [comment]
So, I can't manage to reproduce this. However, when trying to get a better example, I realized that passing the `sol::function&` references by reference within a lambda is probably bad and swapped them for using the `[=](..)` notation and all seems well.
