### ISSUE TITLE
Getting an Exception Unhandled when closing my application (Script works though!) 

### ISSUE THREAD

**Issue by LedLoaf** [ThePhD/sol2#1245]
Hello,

So I am following a course that walks you through using Sol with an SDL Engine. It has been great. But I've come across an issue that I'm not sure how to fix?

The script works just fine, but when I close the application I get an error from Lua about how a "table is expected." 

```
Exception Unhandled 
Unhandled exception thrown: read access violation 
t was 0xFFFFFFFFFFFFFFF

lapi.c
static Table *gettable (lua_State *L, int idx) {
  TValue *t = index2value(L, idx);
  api_check(L, ttistable(t), "table expected");
  return hvalue(t);
}
```
Now there wasn't a lot changed since the code wasn't getting this error.

```
struct ScriptComponent
{
	explicit ScriptComponent(const sol::function func = sol::lua_nil)
		: func(func) { }

	sol::function func;
};
//////////////////////////////
class ScriptSystem : public System
	{
	public:
		explicit ScriptSystem(SharedContext* context)
			: m_context{context}
		{
			requireComponent<ScriptComponent>();
			requireComponent<TransformComponent>();
		}

		// Create all the bindings between C++ and Lua functions
		void createLuaBindings()
		{
			// Create the "entity" user type so Lua knows what an entity is
			m_context->lua->new_usertype<Entity>(
											"entity",
												 "get_id", &Entity::getId,
												 "destroy", &Entity::destroy,
												 "has_tag", &Entity::hasTag,
												 "belongs_to_group", &Entity::belongsToGroup
												);
			m_context->lua->set_function("set_position", setEntityPosition);
		}

		void update(double dt, int elapsedTime)
		{
			// Loop all entities that have a script component and invoke their Lua function
			for (auto entity : getEntities()) {
				const auto script = entity.getComponent<ScriptComponent>();
				if(script.func.valid())
				{
					script.func(entity, dt, elapsedTime);   // here is where we invoke a sol::function
				}
			}
		}

	private:
		SharedContext* m_context;
	};
```

Lua File.
```
 on_update_script = {
                    [0] =
                    function(entity, delta_time, elapsed_time)
                        -- print("Executing F-22 Lua script!")
                        
                        -- change the position of the the airplane to follow a sine wave movement
                        local new_x = elapsed_time * 0.09
                        local new_y = 200 + (math.sin(elapsed_time * 0.001) * 50)
                        set_position(entity, new_x, new_y) -- set the new position
                        
                    end
                }
```

This is from the courses code for the most, part except he just uses UpperCamelCase really. As soon as I hit escape to close the application the exception comes up. The instructor doesn't seem to know, otherwise I would have got a reply by now (6 days) and he uses Unix anyways so sometimes he doesn't get the same problems (Windows 10 VS2019 here). 

Any help would be greatly appreciated. I would like to continue, but I think it's important I find out the cause here first.

**Comment by Rochet2** [comment]
A call stack could help diagnose the issue.
Also, a common issue is deleting the lua state before all other sol objects, like `sol::function`.
For example, which is deleted first: the entities/components that contains `sol::function` or the lua state?

**Comment by LedLoaf** [comment]
Hello,

Appreciate the attempt to help. So you might have already got me somewhere thinking about what is deleted first. I'll have to really go through it all again. For now you asked for the call stack. 

[https://ibb.co/ssg67T4](https://ibb.co/ssg67T4)

I've spent hours on this. But going to try to figure out where what is being deleted. Here is a quick question, because I don't delete the lua_state at any point, nor did I see any documentation about manually doing that.

**Comment by Rochet2** [comment]
When you create sol::state, the Lua state is created. When that variable is destroyed, the state is destroyed as well.
There are other ways of creating the state as well, but we cannot know which one you use without you telling us.

Having a crash can be caused for example the following:
```
struct Object {
    sol::function func;
    sol::state state;
}
```

because the function is destroyed after the state based on object member variable rules. https://stackoverflow.com/a/2254306/3586583

If my guess is right based on reading the call stack, the `Registry` is destroyed after the `sol::state` and the registry contains script component pool that holds `sol::function` objects.
I assume that the Lua state lives in the `Game` -object, so you may want to check the order of the member variables of that object.

Could be that I am entirely wrong though.

**Comment by LedLoaf** [comment]
Hey,

Thanks for the information and sorry to get back late. Been dealing with these damn fires! Wow! That was it! Thank you very much man, I spent hours on this. I was actually responding to say I still haven't figured it out and decided to remove the sol::state from Game.h and bingo! All solved.

Truly appreciate it.
