### ISSUE TITLE
sol::overload issue

### ISSUE THREAD

**Issue by RDSM243** [ThePhD/sol2#1248]
Hello i'm trying to implement two template functions, but i'm having a few problems with sol::overload.

![Screenshot_4](https://user-images.githubusercontent.com/78105875/133356939-20a59bc8-8e34-4f72-b576-e1083f7665ba.png)

My hasComponent is working only when i'm looking for transform component, when i try to use sol::overload and pass other component types i have this error(and the getComponent is not working by the same problem):

`sol: no matching function call takes this number of arguments and the specified types`

Here are my template functions:

![Screenshot_3](https://user-images.githubusercontent.com/78105875/133356625-8e428972-b889-430d-9996-a8602aefd7ec.png)

**Comment by ThePhD** [comment]
`sol::overload` does not work here because there exists no way for Lua (and sol2) to differentiate between the function calls. You need to pass in some kind of argument to act as a discriminator: `sol::overload` uses argument information to decide which one to call. `GetComponent`/`HasComponent` takes no arguments, so it matches no calls.

You need to write a version that takes some kind of indicator. A string name, various different special structures you inject into Lua to make the difference clear - something. What are you passing in right now to differentiate?

**Comment by RDSM243** [comment]
> `sol::overload` does not work here because there exists no way for Lua (and sol2) to differentiate between the function calls. You need to pass in some kind of argument to act as a discriminator: `sol::overload` uses argument information to decide which one to call. `GetComponent`/`HasComponent` takes no arguments, so it matches no calls.
> 
> You need to write a version that takes some kind of indicator. A string name, various different special structures you inject into Lua to make the difference clear - something. What are you passing in right now to differentiate?

I pass the class type like this:
![Screenshot_5](https://user-images.githubusercontent.com/78105875/133367852-d845638d-9ed5-495c-a8de-6423a352a70e.png)

**Comment by ThePhD** [comment]
That passes a `sol::metatable` to a function named `HasComponent`. That does not match the `HasComponent` function you have. You need to write a single function which takes a `HasComponent(sol::metatable)` and then check the class name and map it to a specific class type, or some other form of identification.

**Comment by RDSM243** [comment]
> That passes a `sol::metatable` to a function named `HasComponent`. That does not match the `HasComponent` function you have. You need to write a single function which takes a `HasComponent(sol::metatable)` and then check the class name and map it to a specific class type, or some other form of identification.

Thank you, it's working now
