### ISSUE TITLE
Add returns in script_file/load_file?

### ISSUE THREAD

**Issue by EliasD** [ThePhD/sol2#125]
It's useful to return local stuff from scripts. Suppose I have a script like this:
```lua
-- script.lua
local someTable = {...}
local someTable2 = {...}
return someTable, someTable2
```

It would be great if I was able to do this (and same stuff after calling `load_file` and then executing the chunk):
```c++
sol::table someTable1, someTable2;
sol::bond(someTable1, someTable2) = lua.script_file("script.lua");
```

That shouldn't be hard to implement as scripts loaded in Lua kinda work like functions: they push returns on the stack which I usually want to get (and do so by using `sol::stack::pop` at the moment).

**Comment by ThePhD** [comment]
````
sol::load_result fx = lua.load_file("script.lua");
sol::tie( a, b ) = fx();
````

**Comment by ThePhD** [comment]
I will look into adding `script_result` somewhere.
