### ISSUE TITLE
Reading a table with no name

### ISSUE THREAD

**Issue by LedLoaf** [ThePhD/sol2#1250]
Hello,

I was wondering how you would read something like this:

`lua.script(R" return { x = 5, y = 10 }");`

I'm trying to parse a Tiled Editor lua file and they present the whole file like this and this is just a simplified version because I'm just trying to read the first variable and I should be good to go from there.

Now I can easily just do :

`lua.script(R" Map = { x = 5, y = 10 }");  `

and simply read it like all the examples show. But I'm curious how I would do this for learning purposely and the fact that I don't like that you would need to manually edit the export file, despite how ridiculously minor it is. I figured that there might be something in the future where knowing how to respond to this would be valuable.

Any help would be greatly appreciated and perhaps a simple example. Be safe.

**Comment by ThePhD** [comment]
Just like a normal function call, an object returned by a script can be referenced and used.

```cpp
sol::table t = lua.script(R" return { x = 5, y = 10 }");
```

Working example: https://godbolt.org/z/1nzva6cEG
