### ISSUE TITLE
Can't register functions with abstract const reference as return type

### ISSUE THREAD

**Issue by deadlocklogic** [ThePhD/sol2#1265]
Hello there,
Sorry to bump an old thread but I believe my issue is relatable:
Consider a slightly modified variation:
```C++
class A {
public:
    virtual const A& a(const A&) = 0;
};

class B : public A {
public:
    virtual const A& a(const A&) override {
        return *this;
    }
};

int main()
{
    sol::state state;
    state.new_usertype<A>("A", "a", &A::a);
    state.new_usertype<B>("B", sol::base_classes, sol::bases<A>());
}
```
With MSVC I get:
`C2259: 'A': cannot instantiate abstract class`
I am missing something there? Or this isn't feasible?

_Originally posted by @deadlocklogic in https://github.com/ThePhD/sol2/issues/213#issuecomment-955837873_

**Comment by deadlocklogic** [comment]
For now I am solving this with a funny solution:
```C++
    state.new_usertype<A>("A", "a", [](A& self) { return &self.a(self); });
```
Is is the best approach?

**Comment by deadlocklogic** [comment]
Also note, returning concrete const reference to types with deleted copy constructor fails to compile too. So basically, whenever we hit a non-copiable type we should rely on pointer semantics, right?

**Comment by ThePhD** [comment]
Returning a const reference basically pushes sol2 to make a copy. It's not ideal given most chaining-based methods use these kinds of things for builder methods and what not.

You can get around this by wrapping it to return a `std::ref(*this)`, which is a `std::reference_wrapper<A>` instead. I should probably make this much simpler at some point...

**Comment by deadlocklogic** [comment]
Right, Thanks!
Just another little question, is there any kind of mechanism to protect against  `nil` passed from lua to C++ function expecting value/reference semantics and not pointers/wrappers?

**Comment by deadlocklogic** [comment]
Ok I found it.
`#define SOL_ALL_SAFETIES_ON 1` does the trick.
