### ISSUE TITLE
Weird table behavior with Lua 5.4.3

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#1266]
I'm not sure exactly what's going on here, but I'm noticing some weird behavior with adding entries to a table in Lua 5.4.3. This issue is specific to 5.4.3 and I cannot reproduce it with other versions of lua. It also doesn't appear to have been introduced with a recent commit of sol (I went a year back and I could still repro), so I'm not entirely sure if this is an issue with sol or lua.

After creating a table and doing `.add()` to it, an item at index `3` is added with the value 0. This seems to happen with tables both created using sol and ones created using the raw lua api. Example attached below:

```cpp
sol::state lua;
lua.open_libraries(sol::lib::base);

// Create and add using sol.
sol::table table = lua.create_table();
table.add("item");
lua["table"] = table;

// Create and add using C API.
lua_createtable(lua.lua_state(), 0, 0);
lua_pushstring(lua.lua_state(), "item");
lua_rawseti(lua.lua_state(), -2, 1);
lua_setglobal(lua.lua_state(), "table2");

// Create using C API and add using sol.
lua_createtable(lua.lua_state(), 0, 0);
lua_setglobal(lua.lua_state(), "table3");
sol::table table3 = lua["table3"];
table3.add("item");

lua.script("for k, v in pairs(table) do print(tostring(k) .. ' => ' .. tostring(v)) end");
lua.script("for k, v in pairs(table2) do print(tostring(k) .. ' => ' .. tostring(v)) end");
lua.script("for k, v in pairs(table3) do print(tostring(k) .. ' => ' .. tostring(v)) end");
```

Here I would expect the following output:

```
1 => item
1 => item
1 => item
```

But instead I get this:

```
1 => item
3 => 0
1 => item
1 => item
3 => 0
```

**Comment by deadlocklogic** [comment]
A quick notice (without even digging any further), try to push the table with a different name as plain `table`, because `table` is lua specific and sol may be using its functionality internally, so you may be overriding default behavior.

**Comment by OrfeasZ** [comment]
You're right, but in this case it doesn't actually make a difference. Issue still persists with different variable names.

**Comment by deadlocklogic** [comment]
Ok, then there is an even minimal test:
```C++
sol::state lua;
lua.open_libraries(sol::lib::base);

sol::table table = lua.create_named_table("table1");
table.add("item");

lua.script("for k, v in pairs(table1) do print(tostring(k) .. ' => ' .. tostring(v)) end");
```
Expected:
```lua
1 => item
```
Actual:
```lua
1 => item
3 => 0
```
Hope it makes it easier on @ThePhD to debug.

**Comment by edunad** [comment]
Getting the same issue :(

**Comment by eric-2** [comment]
table.add actually uses Luas reference system http://www.lua.org/manual/5.4/manual.html#luaL_ref .
In 5.4 the implementation changed to https://www.lua.org/source/5.4/lauxlib.c.html#luaL_ref .
The key 3 in the table is actually the freelist of the reference system which now always gets initialized by luaL_ref.

**Comment by lionkor** [comment]
Getting the same issue.

**Comment by raphasampaio** [comment]
Same issue here

**Comment by lionkor** [comment]
A workaround for 
```cpp
table.add("item");
```
not working is 
```cpp
table[table.size() + 1] = "item";
```
Yes, that's **+** 1, it's a Lua idiom :tm:

**Comment by ThePhD** [comment]
Sorry for the long wait: fixed in latest.

**Comment by lionkor** [comment]
Thank you!!!! Absolutely love the work you're doing!!
