### ISSUE TITLE
Template member?

### ISSUE THREAD

**Issue by PhilCK** [ThePhD/sol2#127]
Is it possible to bind a template member function?

I'm trying to bind a varient class.

I've tried

```cpp
  m_lua.new_usertype<Test::Param>(
    "Param",
    "get_bool", &Test::Param::get<bool>
  );
```
That produces error, `expecting 3 arguments` on MSVS

and (although I didn't have hope in this one.)
```cpp
  m_lua.new_usertype<Test::Param>(
    "Param",
    "get_bool", static_cast<bool (Test::Param::*) ()>( &Test::Param::get<bool> )
  );
```

**Comment by ThePhD** [comment]
I don't know what `Test::Param` looks like. So the most I can do is guess. I'm going to assume it looks like this:

````cpp
struct Test {
     struct Param {
         template <typename T>
         T get () { return T(); }
     }
};
````

Or something similar. To bind that, you need to do...

````cpp
m_lua.new_usertype<Test::Param>(
    "Param",
    "get_bool", &Test::Param::template get<bool>
);
````

Probably. Or something.

Please also see [this example](http://sol2.readthedocs.io/en/latest/tutorial/functions.html#writing-templated-functions-the-func) and maybe [this example](http://sol2.readthedocs.io/en/latest/api/resolve.html) if the function you're binding is also overloaded.

**Comment by PhilCK** [comment]
Ah sorry.

I did see those examples.

```cpp
namespace Test {
template<typename ... Ts>
class Variant {

template<T>
T& get() { return *reinterpret_cast<T*>(&m_data);

};
} // ns
```

**Comment by PhilCK** [comment]
No still get the same error. I worked around it though by just making a Wrapper class with non templated functions.

**Comment by ThePhD** [comment]
What _is_ the error? Is it a compiler error or a runtime error?

**Comment by ff2000** [comment]
On Thu, 23 Jun 2016 09:46:50 -0700, Phil Cooper-King <notifications@github.com> wrote:
> Ah sorry.
> 
> I did see those examples.
> 
> ```cpp
> namespace Test {
> template<typename ... Ts>
> class Variant {
> 
> template<T>
> T& get() { return *reinterpret_cast<T*>(&m_data);
> 
> };
> } // ns
> ```

Ah! So this is a nonstatic member function template of a _class template_.
You IMHO also need to specify params (Ts) for Variant.
Test::Variant is not a type but Test::Variant<std::string> is.

> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ThePhD/sol2/issues/127#issuecomment-228110841
> 
--

**Comment by ThePhD** [comment]
It seems like you found a satisfactory solution. I'm going to mark this as closed.

**Comment by PhilCK** [comment]
Sorry I was quite, I got sidetracked. I didn't realize but it was an overloaded function `T* get()` and const `T* get() const` I'm going to stick with the wrapper though as it makes the template mess alitle more bareable.

Thanks.
