### ISSUE TITLE
Proper container detection customization

### ISSUE THREAD

**Issue by deadlocklogic** [ThePhD/sol2#1279]
Hi, I am trying to make a type behave like a container. The type has `begin()/end()/iterator` defined but doesn't have `value_type`.
So I am trying the following (as a simple example, my case is more complex and I can't easily change the code of the lib)
```C++
struct my_vec {
    std::vector<int> arr;

    typedef std::vector<int>::iterator iterator;

    my_vec(std::initializer_list<int> list) : arr(list) {
    }

    auto begin() {
        return arr.begin();
    }

    auto end() {
        return arr.end();
    }
};
```
What I did is specializing like this:
```C++

namespace sol {

template <>
struct is_container<my_vec> : std::true_type {};

template <>
struct usertype_container<my_vec> {
    static int size(lua_State* L) {
        my_vec& v = sol::stack::get<my_vec&>(L, 1);
        return stack::push(L, v.arr.size());
    }

    static auto begin(lua_State*, my_vec& self) {
        return self.arr.begin();
    }
    static auto end(lua_State*, my_vec& self) {
        return self.arr.end();
    }

    static std::ptrdiff_t index_adjustment(lua_State*, my_vec&) {
        return 0;
    }
};
```
But this isn't working properly
```C++
    lua["c"] = my_vec{0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

    auto result1 = lua.safe_script("for i=0,9 do assert(i == c[i]) end", sol::script_pass_on_error);
    REQUIRE(result1.valid());
    auto result2 = lua.safe_script("assert(c[10] == nil)", sol::script_pass_on_error);
    REQUIRE(result2.valid());
    auto result3 = lua.safe_script("assert(c[-1] == nil)", sol::script_pass_on_error);
    REQUIRE(result3.valid());
    auto result4 = lua.safe_script("assert(#c == 10)", sol::script_pass_on_error);
    REQUIRE(result4.valid());
```
It gives:
```
[string "for i=0,9 do assert(i == c[i]) end"]:1: assertion failed!
[string "assert(#c == 10)"]:1: attempt to get length of a sol.my_vec value (global 'c')
```
What I am doing wrong here?

**Comment by OrfeasZ** [comment]
Your `my_vec` type needs to have a `value_type` defined for sol to be able to automagically have it work as a container type. If you don't have control of the container type then you have a couple of options: 

### 1. Create your own wrapper type that provides `value_type`, `iterator`, `begin()`, and `end()`

For example:

```cpp
struct my_vec_wrapper {
    my_vec vec;

    using iterator = my_vec::iterator;
    using value_type = int;

    my_vec_wrapper(my_vec wrapped_vec) : vec(std::move(wrapped_vec)) {}

    auto begin() {
        return vec.begin();
    }

    auto end() {
        return vec.end();
    }
};
```

With this option you don't have to specify any special container traits and you can just pass values of this type as per usual to sol and everything should just work. If you want to index starting at 0, then you can basically use the same `usertype_container` code you have above. No need for `is_container`.

### 2. Implement all the `usertype_container` methods you need manually

This is a bit more involved, but affords you a lot more control over how sol binds your container. For example, to get the assertions in the sample you have above to pass, you can do something like this:

```cpp
namespace sol {
    template <>
    struct is_container<my_vec> : std::true_type {};

    template <>
    struct usertype_container<my_vec> {
        static int size(lua_State* L) {
            my_vec& v = sol::stack::get<my_vec&>(L, 1);
            return stack::push(L, v.arr.size());
        }

        static int get(lua_State* L) {
            my_vec& v = sol::stack::get<my_vec&>(L, 1);
            std::ptrdiff_t idx = sol::stack::unqualified_get<std::ptrdiff_t>(L, 2);

            if (idx < 0 || idx >= v.arr.size())
                return sol::stack::push(L, sol::lua_nil);

            return sol::stack::push(L, v.arr[idx]);
        }

        static int index_get(lua_State* L) {
            return get(L);
        }
    };
}
```

This however only implements size checks and getting values by index or using the `:get()` method. To support more operations, you'll have to implement the rest of the functions detailed [here](https://sol2.readthedocs.io/en/latest/containers.html?highlight=is_container#container-operations) similarly.

Keep in mind that in the example above we don't define `index_adjustment` since we grab the raw index directly from the stack. If you want to maintain lua 1-based indexing you'd subtract `-1` from the `idx` variable.

**Comment by deadlocklogic** [comment]
Thanks for replying.
Actually using option 1 means more wrapping because I won't be able to pass regular function pointers when `my_vec` is involved but wrappers around `my_vec_wrapper` unless I use a customization in `sol_lua_push` with `my_vec` as `my_vec_wrapper` and reverse it in `sol_lua_get`.
Option 2 seems more clean/straightforward (actually this is what I am trying to implement) but I am still getting the same runtime error
```
[string "for i=0,9 do assert(i == c[i]) end"]:1: assertion failed!
[string "assert(#c == 10)"]:1: attempt to get length of a sol.my_vec value (global 'c')
```

**Comment by OrfeasZ** [comment]
Here's my full repro for the code I posted above, which passes all assertions as expected (with latest sol, lua 5.4.2). Does this work for you?

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

struct my_vec {
    std::vector<int> arr;

    typedef std::vector<int>::iterator iterator;

    my_vec(std::initializer_list<int> list) : arr(list) {
    }

    auto begin() {
        return arr.begin();
    }

    auto end() {
        return arr.end();
    }
};

namespace sol {
    template <>
    struct is_container<my_vec> : std::true_type {};

    template <>
    struct usertype_container<my_vec> {
        static int size(lua_State* L) {
            my_vec& v = sol::stack::get<my_vec&>(L, 1);
            return stack::push(L, v.arr.size());
        }

        static int get(lua_State* L) {
            my_vec& v = sol::stack::get<my_vec&>(L, 1);
            std::ptrdiff_t idx = sol::stack::unqualified_get<std::ptrdiff_t>(L, 2);

            if (idx < 0 || idx >= v.arr.size())
                return sol::stack::push(L, sol::lua_nil);

            return sol::stack::push(L, v.arr[idx]);
        }

        static int index_get(lua_State* L) {
            return get(L);
        }
    };
}

int main()
{
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua["c"] = my_vec{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

    auto result1 = lua.safe_script("for i=0,9 do assert(i == c[i]) end", sol::script_pass_on_error);
    assert(result1.valid());
    auto result2 = lua.safe_script("assert(c[10] == nil)", sol::script_pass_on_error);
    assert(result2.valid());
    auto result3 = lua.safe_script("assert(c[-1] == nil)", sol::script_pass_on_error);
    assert(result3.valid());
    auto result4 = lua.safe_script("assert(#c == 10)", sol::script_pass_on_error);
    assert(result4.valid());
}
```

**Comment by deadlocklogic** [comment]
Ah, at some point I am registering the type with:
```C++
lua.new_usertype<my_vec>("my_vec", ...);
```
When I comment this snippet it works fine. So the problem now is how do I add extra methods to this container-like type if I can't register it via `new_usertype`?

**Comment by OrfeasZ** [comment]
In this case you'd probably want to skip defining container traits altogether and instead implement the various relevant metamethods for your usertype. Here's a minimal example below:

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

struct my_vec {
    std::vector<int> arr;

    typedef std::vector<int>::iterator iterator;

    my_vec(std::initializer_list<int> list) : arr(list) {
    }

    auto begin() {
        return arr.begin();
    }

    auto end() {
        return arr.end();
    }

    size_t size() const {
        return arr.size();
    }

    std::optional<int> index_get(const sol::stack_object& key) const {
        if (!key.is<lua_Integer>())
            return std::nullopt;

        auto idx = key.as<lua_Integer>();

        if (idx < 0 || idx >= arr.size())
            return std::nullopt;

        return std::make_optional(arr[idx]);
    }

    void some_function() const
    {
        std::cout << "nice!" << std::endl;
    }
};


int main()
{
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.new_usertype<my_vec>("my_vec",
        sol::meta_function::index, &my_vec::index_get,
        sol::meta_function::length, &my_vec::size,
        "some_function", &my_vec::some_function
    );

    lua["c"] = my_vec{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

    auto result1 = lua.safe_script("for i=0,9 do assert(i == c[i]) end", sol::script_pass_on_error);
    assert(result1.valid());
    auto result2 = lua.safe_script("assert(c[10] == nil)", sol::script_pass_on_error);
    assert(result2.valid());
    auto result3 = lua.safe_script("assert(c[-1] == nil)", sol::script_pass_on_error);
    assert(result3.valid());
    auto result4 = lua.safe_script("assert(#c == 10)", sol::script_pass_on_error);
    assert(result4.valid());
    auto result5 = lua.safe_script("c:some_function()", sol::script_pass_on_error);
    assert(result5.valid());
}
```

**Comment by deadlocklogic** [comment]
Yeah, this is exactly what I am doing right now, but it would've been great if `sol` exposed a way to use its default implementation regarding these functions. I know they are kinda easy to implement, but when it comes to `pairs` for instance I have to check lua's documentation about stateless iterators to correctly implement `next`.

I will keep this open if the @ThePhD has something to say about this (exposing default implementation of containers function?) and close it.

**Comment by ThePhD** [comment]
If you want to implement `pairs` and `next`, we have examples for that using both the cushy sol2 API and raw with less involvement from the `sol:`: namespace:

https://github.com/ThePhD/sol2/blob/develop/examples/source/pairs.cpp
https://github.com/ThePhD/sol2/blob/develop/examples/source/pairs_with_raw_functions.cpp

I can't really do this for you beyond container detection because of how metatables are set up, so if the defaults aren't good enough you've got to roll some of you own. 🤷‍♀️
