### ISSUE TITLE
Bad '.' access, only after garbage collection

### ISSUE THREAD

**Issue by Leadwerks** [ThePhD/sol2#1291]
The "editor" variable is a shared_ptr.

This works fine:
```
ExecuteString("a = editor.sidepanel"); // this uses safe_script
```
This works fine
```
CollectGarbage();
ExecuteString("a = editor");
```
This produces a sol error:
```
CollectGarbage();
ExecuteString("a = editor.sidepanel");
```
Here is the error text:
> 
_Error: sol: runtime error: [string "a = editor.sidepanel"]:1: sol: 'self' argument is lua_nil (bad '.' access?)_
> 
"editor" is a global variable. It is not being collected. I have tested it like this:
```
if editor == nil then Print(1) end
```
But editor.sidepanel becomes inaccessible, with the above error, only after garbage collection is run.

The C++ class looks like this:
```
class Editor
{
shared_ptr<SidePanel> sidepanel
};
```
And here is the sol binding code:
```
	L->new_usertype<SidePanel>
	(
		"SidePanel",
		sol::base_classes, sol::bases<Object>(),
		"tabber", &SidePanel::tabber
	);

	L->new_usertype<Editor>
	(
		"Editor",
		sol::base_classes, sol::bases<Object>(),
		"scene", &Editor::scene,
		"sidepanel", &Editor::sidepanel
	);
	L->set("editor", editor);
```
Any ideas what is wrong? This is using the current build of sol and Lua 5.1.

**Comment by Leadwerks** [comment]
I also tried changing the binding code to use a sol::property for the member, but it made no difference. So it looks like it is more a problem of the shared_ptr "editor" using the '.' accessor:
```
	L->new_usertype<Editor>
	(
		"Editor",
		sol::base_classes, sol::bases<Object>(),
		//"sidepanel", &Editor::sidepanel
		"sidepanel", sol::property([](Editor& r) { return r.sidepanel; })
	);
```

**Comment by Leadwerks** [comment]
In fact the same thing happens when the member is just a simple integer value, like the ObjectBarWidth member:
```
	L->new_usertype<Editor>
	(
		"Editor",
		sol::base_classes, sol::bases<Object>(),
		"ObjectBarWidth", &Editor::ObjectBarWidth,
		"sidepanel", &Editor::sidepanel
	);
```

**Comment by Leadwerks** [comment]
Setting the variable with the raw pointer made no difference:
```
L->set("editor", editor.get());
```
So it looks like the garbage collection is stripping the object of class information somehow?

**Comment by Rochet2** [comment]
Cant see directly what is wrong, but maybe you could try to replicate it here with a small example: https://godbolt.org/z/8cY3zhrWY
This uses different lua and sol version though.

How are you creating `editor` variable?

**Comment by Leadwerks** [comment]
It's a shared_ptr, but it doesn't seem to make any difference.

This code works fine:
https://godbolt.org/z/MTfq3eqrb

I am searching now for the cause...

**Comment by Leadwerks** [comment]
This was caused app by declaring the Editor class twice in sol. I was not able to recreate this in the web app above, but no matter.
