### ISSUE TITLE
Questions on design

### ISSUE THREAD

**Issue by JekiTheMonkey** [ThePhD/sol2#1293]
I'm trying to understand how to embed a scripting language into own C++ projects, but I have some problems.

To practice this aspect I decided to make a very simple project. It consists in showing some moving animations in a window. The update and draw functions will be located in scripts, while the host application as the API will provide functions such as `loadSprite`, `moveSprite` and `setSpriteRect`. But I faced a problem on `loadSprite` creation - it is not possible to provide a class member function to a VM. I'm wondering how can I stick to OOP while using some scripting language.

My class which manages this simulation has the VM and texture/sprite containers. How can I load a texture and create a sprite using it if member functions are not allowed to be used in scripts?

I would appreciate any source to learn these design patterns, though a book would be way more better than anything else.

**Comment by ninnghazad** [comment]
you can use member-functions and OOP in Lua, and in many other scripting languages. 
with sol3 for example you can register your classes as "usertype"s. 
check the examples for sol - like this here: https://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html
if you have like one big class for most of the stuff of your game/application and want to use a member-function of that without using the whole class, you can do that too. for example by binding or registering a lambda. 
guessing from what you wrote, you will probably have to read up quite a bit. 
start with the sol tutorial, check out the examples.

**Comment by JekiTheMonkey** [comment]
Thank you, I somehow missed the part about binding methods to Lua
