### ISSUE TITLE
[question]how to make "set_function" key support localized language (like chinese)?

### ISSUE THREAD

**Issue by nblog** [ThePhD/sol2#1299]
example:
```
#include <sol/sol.hpp>
#include <cassert>

int main() {
    sol::state lua;
    lua.set_function("功能1", [](std::string c) { printf(c.c_str()); });
    lua.script("功能1(\"输出内容\")");
}
```

when key is "功能1", it does not take effect. what should I do?
hope to ask for help, thank you. 🙏

**Comment by ThePhD** [comment]
There's nothing you can do. Lua doesn't parse UTF-8 for its source code. It parses `[A-Za-z][A-Za-z0-9_-]+`; e.g., ASCII letters + Arabic digits only. It fails on anything it can't recognize as part of that regex. From the manual:

> Names (also called identifiers) in Lua can be any string of Latin letters, Arabic-Indic digits, and underscores, not beginning with a digit and not being a reserved word. Identifiers are used to name variables, table fields, and labels.

Sorry. Lua just doesn't support you or your language and the only way to fix that is to hack Lua directly.
