### ISSUE TITLE
Save function from LUA for later as callback

### ISSUE THREAD

**Issue by pokeemerald** [ThePhD/sol2#1303]
Hello there!

I assume a question of this type was already asked, however I've been skimming google and the past issues for the past hours and can't seem to figure out how to solve the problem.

What I'm attempting to write is a simple event system of this sort:
LUA:
```lua
onLogin(function() print("hello world") end)
```

And the according C++ code for this:
```c++
// Container for the callback function
class LuaAPI {
private:
    sol::function onLogin;
    bool onLoginSet; // Only used right now for easier clarification, will later be removed
}
```

I've tried defining the `onLogin` function in C++ several ways and tried the solution in this issue as well: https://github.com/ThePhD/sol2/issues/1107 with no success.

Both ways I attempted to store the function for later use:
```c++
// "table" is a table created one the sol::state
table.set_function("onLogin", [this](sol::protected_function handler) {
    onLogin = handler;
    onLoginSet = true;
 });

// "lua" is the sol::state stored as a member
table["onLogin"] = [this](sol::object t, sol::this_state this_L) {
    onLogin = sol::function(lua, t);
    onLoginSet = true;
};
```

I know that the issue arises when leaving the lua function's scope.
That means at a later time I'd like to call `onLogin()`, which however crashes.

```c++
// .... code for when to call the stored function
if (onLoginSet)
    onLogin();
```

Thank you very much in advance!

**Comment by Rochet2** [comment]
Can you show a full example?
Here is an example that works and uses the same codes you posted: https://godbolt.org/z/s9acjhG3r

What I think is missing here that is very relevant is your handling of LuaAPI object. For example, where does it live? How do you create it and access it?

**Comment by pokeemerald** [comment]
That's very surprising. The application is a rather large modification for a game that is injected as a DLL.
Let me give you a hopefully complete enough rundown of the general architecture.

1. LuaModule
On the main thread several "modules" are allocated on the heap, one of which is the `LuaModule`. Currently it only serves one purpose: allocating a `LuaScript` on the heap.

2. LuaScript
A lua script creates a new `sol::state` which lives as a member. It also instantiates several `LuaAPI` objects which receive the `sol::state` as a reference like this:
```c++
class LuaScript {
private:
	sol::state lua;
	PkLuaAPI* pk;
public:
	LuaScript();
	~LuaScript();
};

LuaScript::LuaScript() {
  template <typename T> T* LoadAPI(sol::state& lua) {
    T* api = new T(lua);
    api->LoadFunctions();
      
    return api;
  }
  
  lua = sol::state{};
  lua.open_libraries(sol::lib::base, sol::lib::string, sol::lib::table, sol::lib::math);
  
  pk = LoadAPI<PkLuaAPI>(lua);
}

LuaScript::~LuaScript() {
  delete pk;
}
```
The template is used to call the pure virtual `LoadFunctions` method as all actually used `LuaAPI` objects are derived.
Afterwards I run a basic lua string in the constructor of the above `LuaScript`:
```c++
try {
  lua.script(R"(
    pk.onLogin(function()
      -- This call does not crash since it calls a static c++ method, senidng something into the game chat
      samp.sendChat("Logged in from LuaScript!")
    end)
  )");
} catch (const sol::error& e) {
  /* Code that outputs the lua error into the game's chatbox */
}
```

3. LuaAPI
The `LuaAPI` class is derived from and is used to offer several functionality to the lua script.
One example is registering events from the base game we inject into.
It's currently basic design is as following:
```c++
class LuaAPI {
protected:
	sol::state& lua;
	std::string name;
	sol::table table;
public:
	LuaAPI(sol::state& lua, std::string name);

	virtual void LoadFunctions() = 0;
};

LuaAPI::LuaAPI(sol::state& lua, std::string name): lua(lua), name(name) {
	table = lua.create_named_table(name);
}
```
The idea behind this is to create multiple tables for the different APIs so we can use them in LUA like a "package".

Now for the actual implementation of one LuaAPI, the `PkLuaAPI` which is instantiated in the `LuaScript` above.
```c++
PkLuaAPI::PkLuaAPI(sol::state& lua): LuaAPI(lua, "pk") {
	subscribedLogin = false;

	eventGGameLogin = EventBus::Subscribe(G_LOGGEDIN, [this](Event* event) {
		if (subscribedLogin)
			onLogin();
	});
}

PkLuaAPI::~PkLuaAPI() {
        // This log is never created, pretty much verifying that the API is not destructed
	Logger::Log("LUA:PkAPI", "Unsubscribing from EventBus");

	EventBus::Unsubscribe(eventGGameLogin);
}

void PkLuaAPI::LoadFunctions() {
	table.set_function("onLogin", [this](sol::protected_function handler) {
		onLogin = handler;
		subscribedLogin = true;
	});
}
```

Somewhere else in the code a call to the `EventBus` with `G_LOGGEDIN` is made, triggering the subscribed event in the `PkLuaAPI` class. This happens on the main thread, so a multithreading issue is not possible. Attempting to call the `onLogin` function then leads to a crash. Here is the crash the stacktrace:
Exception at: https://pke6.de/uploads/devenv_7ZBKRhT7Pe.png
Stacktrace: https://pke6.de/uploads/stacktrace.png

This architecture had no issues with lifetimes of objects and since the criticaö parts live on the heap it should not be destructed accidentally.
Thank you a lot for your help!

**Comment by pokeemerald** [comment]
Okay.. it seems like the contents of `onLogin()` actually crashed the application. I've changed the lua code than is ran in the callback from `sendChat` to another c++ function and it now worked. I'm stupid. 😸

If some new issue arises with this stuff I'll let you know. Thank you again very much though!
