### ISSUE TITLE
std::ref doesn't work with sol::table if class doesn't have operator()

### ISSUE THREAD

**Issue by EliasD** [ThePhD/sol2#131]
There's an example in docs of how to pass reference to C++ object in Lua. Passing pointer works, however passing ```std::reference_wrapper``` somehow tries to access missing operator(). Is this a bug or is std::ref no longer usable for this stuff?
```c++
SomeClass someVar;
sol["someVar"] = &someVar; // ok
sol["someVar2"] = std::ref(someVar); //not ok,
// typedef in struct functor_function tries to get type of &SomeClass::operator()
```

**Comment by ThePhD** [comment]
If the class has the function call operator, `table["key"] = value` in C++ it treats it like you called `table.set_function( "key", value );` instead. Still, this is an oversight on my part: I'll make sure the `set_function` version doesn't trigger on `std::ref`.
