### ISSUE TITLE
Not compiling with devkitPPC GCC 11.2.0

### ISSUE THREAD

**Issue by HTV04** [ThePhD/sol2#1310]
So, I'm trying to compile sol2 for a Wii homebrew project I'm working on (I redacted its name from the following error log because it's unreleased). However, when I try to compile it, I get a lot of strange errors that no one else seems to have gotten.

The compiler devkitPPC uses is GCC 11.2.0, and as far as I know, it doesn't seem to have any weird quirks compared to normal GCC. According to the __cplusplus variable from a compiled program, it is also using C++ 17. I tried the latest stable release, 3.2.2, along with the latest stable tag, 3.2.3, and even the latest commit, and nothing's working. I'm totally lost as to why this is happening, and I'm hoping this is just a configuration issue on my end.

Here is the full, very long, error log with sol's latest commit. It seems to have some GRRLIB errors mixed in which weren't there before I added sol2 to my project, so I'm wondering if something's wrong with the global namespace after adding sol2: [errorlog.zip](https://github.com/ThePhD/sol2/files/8103489/errorlog.zip)

**Comment by HTV04** [comment]
After a lot of testing, it turns out that sol2 and GRRLIB seem to be conflicting with each other, which explains why the myriad of errors included GRRLIB. One compiles if the other one isn't present.

I have no idea why they're conflicting with each other. I noticed a lot of references to an "R" macro, maybe that's it?

**Comment by HTV04** [comment]
TIL that the include order of libraries can matter A LOT. Including sol2 before GRRLIB fixed the issue for both libraries :grin:

But now one issue remains, sol2 compiles but throws a strange error when attempting to use sol::state:
```
error: use of deleted function 'sol::state::state(const sol::state&)'
```

**Comment by Rochet2** [comment]
Not too familiar with the error, but are you perhaps trying to pass sol::state as a value to functions?
Could be copy construction is triggered when passing by value causing the error even if you don't actually copy construct explicitly in your code. Just a hunch, given there is no code to inspect.

**Comment by HTV04** [comment]
I do have a function in a different script that takes a sol::state as an argument, could that be it?

**Comment by ThePhD** [comment]
Thanks for helping him figure it out, @Rochet2!

I feel bad for not getting to a lot of these questions faster, but I have way too much to do. I should really clean up this library and the docs and make it easier for people to contribute fixes 😭
