### ISSUE TITLE
How do you overload a non-static member function?

### ISSUE THREAD

**Issue by maxdemarzi** [ThePhD/sol2#1312]
I have a bunch of member functions that I want to rename and overload. 

```
lua.set_function("NodeGetLinks", &Shard::NodeGetLinksViaLua, this);
lua.set_function("NodeGetLinksById", &Shard::NodeGetLinksByIdViaLua, this);
```
However I can't figure out what the write syntax is to pass "this" into sol::overload to get it to work.
I even tried using lambdas which at least compiles, but I get null for results.
```
        lua.set_function("overloaded",
             sol::overload(
               [this](uint64_t id) {this->NodeGetLinksByIdViaLua(id);}
               ,[this](std::string type, std::string key) {this->NodeGetLinksViaLua(type, key);}));
```

How do you overload a non-static member function?

**Comment by Rochet2** [comment]
> I even tried using lambdas which at least compiles, but I get null for results.

The lambdas are not returning any value, but it sounds like you expect them to return something.
```cpp
lua.set_function("overloaded", sol::overload(
    [this](uint64_t id) { return this->NodeGetLinksByIdViaLua(id); },
    [this](std::string type, std::string key) { return this->NodeGetLinksViaLua(type, key); }
));
```
Seems to work just fine. Remember to make sure that "this" lives long enough.
Here is a full example: https://godbolt.org/z/eT6MjY64d

**Comment by maxdemarzi** [comment]
OMG You are right I forgot the return. I was about to start tearing my hair out. Thank you!
