### ISSUE TITLE
How to create iterator for std::vector?

### ISSUE THREAD

**Issue by HTV04** [ThePhD/sol2#1314]
I would like to make a function that returns an iterator that can be used with a Lua for loop. It would iterate over the contents of an std::vector.

I managed to make a function that itself works as an iterator, but I was wondering if there was a cleaner way to do this with sol2.

**Comment by otristan** [comment]
you mean like that 
https://github.com/ThePhD/sol2/blob/develop/examples/source/container_usertype_as_container.cpp
?

**Comment by HTV04** [comment]
No, I mean something like `ipairs`, which returns an iterable function for a `for` loop.

**Comment by ThePhD** [comment]
`std::vector` should come with one of those already if you use it inside of sol2.

But, if you want to do it in-general, you can find examples for making pairs-style iterators at these places:

- https://github.com/ThePhD/sol2/blob/develop/examples/source/pairs.cpp
- https://github.com/ThePhD/sol2/blob/develop/examples/source/pairs_with_raw_functions.cpp

**Comment by Rochet2** [comment]
@HTV04 sol implements the pairs and ipairs with the metamethods `__pairs` and `__ipairs`. When calling pairs and ipairs, lua will try to find those metamethods and use them if they exist (see https://www.lua.org/manual/5.2/manual.html#pdf-ipairs). So you can loop through them like a table by calling ipairs on the vector for example. Additionally there seem to be functions called pairs and ipairs as member functions, so you can call those directly also.
```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>
#include <vector>

int main() {
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::package);

    std::vector<int> vec = {5,6,7,8};
    lua["vec"] = vec;
    lua.script("for k,v in pairs(vec) do print(k,v) end");
    lua.script("for k,v in ipairs(vec) do print(k,v) end");
    lua.script("for k,v in vec:pairs() do print(k,v) end");
    lua.script("for k,v in vec:ipairs() do print(k,v) end");
    return 0;
}
```

It seems though, that calling `vec:ipairs()` causes an error for me on godbolt. Maybe sol is outdated there, or maybe it is a bug, hmm. https://godbolt.org/z/M5n7Pa7zb
```
Program returned: 139
[sol3] An error occurred and has been passed to an error handler: sol: runtime error: stack index -1, expected number, received string: not an integer 
stack traceback:
	[C]: in metamethod '__index'
	[string "for k,v in vec:ipairs() do p..."]:1: in main chunk
terminate called after throwing an instance of 'sol::error'
  what():  sol: runtime error: stack index -1, expected number, received string: not an integer 
stack traceback:
	[C]: in metamethod '__index'
	[string "for k,v in vec:ipairs() do p..."]:1: in main chunk
```
