### ISSUE TITLE
Test failure with lua 5.4.4 and musl

### ISSUE THREAD

**Issue by DarthGandalf** [ThePhD/sol2#1316]
Linux, gcc 11, amd64

The test which fails is `tests/runtime_tests` in sol2's directory. It's working fine with lua 5.4.2, but fails with lua 5.4.4

```
[C++] ~depends_on_reference
[C++] ~composition_related
[C++] ~holder
this is a string
this is a string
this is a string
this is a string
[sol3] An error occurred and panic has been invoked: stack index -1, expected number, received nil: not a numeric type that fits exactly an integer (number maybe has significant decimals) 
[sol3] An error occurred and panic has been invoked: attempt to call a nil value
terminate called after throwing an instance of 'sol::error'
  what():  lua: error: attempt to call a nil value
```

The full log is at [build.log](https://834070.bugs.gentoo.org/attachment.cgi?id=765849) and [LastTest.log](https://834070.bugs.gentoo.org/attachment.cgi?id=765850)

Ref https://bugs.gentoo.org/834070

**Comment by ThePhD** [comment]
This might be related to something fixed on the latest branch; 3.2.2 is old as sin and had some destructor issues. I still have to cut a new release after doing more bugfixes but I've got a lot of other stuff to do. x.x

If swapping to using ~latest doesn't quite get rid of the bug, it might be something I need to investigate.

**Comment by DarthGandalf** [comment]
I used 3.2.2 because it's the latest release created as "release" on github, I didn't notice 3.2.3 which is just a tag.

But same happens on the latest release 3.2.3.

I tried 4.0.0-alpha, but it doesn't work with different error (even on glibc): 
[LastTest.log](https://github.com/ThePhD/sol2/files/8308912/LastTest.log)

I also tried 50b62c9346750b7c2c406c9e4c546f96b0bf021d but it also fails on glibc (so I didn't get to test it on musl):
[LastTest.log](https://github.com/ThePhD/sol2/files/8308928/LastTest.log)
[build.log](https://github.com/ThePhD/sol2/files/8308929/build.log)

**Comment by DarthGandalf** [comment]
Cannot reproduce this with 3.3.0
