### ISSUE TITLE
How to return any type?

### ISSUE THREAD

**Issue by HTV04** [ThePhD/sol2#1317]
I'm trying to make an event handler that returns a string and 6 other random types via a tuple when calling a function. The types can be a C++ primitive, a string, or sol::nil.

However, I'm having trouble implementing this. There doesn't seem to be a "catch-all" sol type for functions. I tried sol::object, but it only works with sol::nil.

**Comment by OrfeasZ** [comment]
You should be able to use `sol::object`, but not by constructing it directly. You can use `sol::make_object(lua_state, your_object);`, where `lua_state` is your `sol::state` / `lua_State*` and `your_object` is an instance of your object (eg. string, primitive, etc.). If you don't have the state available in the method you are returning this from, you can add a `sol::this_state` parameter, which will automatically provide the state object to you.

**Comment by HTV04** [comment]
Where do I add the sol::this_state parameter?
