### ISSUE TITLE
set_function function that takes a reference argument

### ISSUE THREAD

**Issue by treytencarey** [ThePhD/sol2#1323]
I'm trying to use some functions from an API, which I can't modify, in Lua so I have to pass my argument by reference.
Here's a minimum example I'm trying to solve:

    void test(int& t)
    {
    }
    int main()
    {
        sol::state lua;
        lua.open_libraries();
        lua.set_function("test", &test);
        return 0;
    }

Results in:

    Severity	Code	Description	Project	File	 State
    Error	C3169	'decltype(auto)': cannot deduce type for 'auto' from 'void'	69	
    Error	C2664	'void (int &)': cannot convert argument 1 from '_Ty' to 'int &'	70
    Error	C2664	'void (int &)': cannot convert argument 1 from '_Ty' to 'int &'	70	

I have also tried `lua.set_function("test", std::function<void(std::reference_wrapper<int>)>(&test));` I read somewhere, which results in an access violation.

**Comment by Rochet2** [comment]
You can wrap the function like this
```cpp
lua.set_function("test", [](int t){ return test(t); });
```

Some cpp template magic could also probably be used to automatically do this.

**Comment by treytencarey** [comment]
> You can wrap the function like this
> 
> ```c++
> lua.set_function("test", [](int t){ return test(t); });
> ```
> 
> Some cpp template magic could also probably be used to automatically do this.

This won't work as expected. While it does compile, consider this:

'''c++
void test(int& t)
{
    t = 10;
}

// ...
lua.script(MULTILINE(
    t = 3
    test(t)
    print(t)
));'''
If function test() sets t to a new value, print(t) will always print 3 regardless; it needs to update the value by reference.

**Comment by Rochet2** [comment]
Didn't know it was supposed to be an output parameter.
Lua does not have references for primitive values, so Sol does not and cannot directly support them like that.

There are several different approaches that you can take.
1. You can return changed values and then assign them
2. You can pass in a table that contains the parameters to which you then change (assign) the changed value. As tables are passed by reference, you can see the change in the original table.
3. You can make an integer usertype that then basically implements integer references

There are probably other approaches as well, but generally you need to figure out some workaround for directly modifying a normal lua integer.

Here is an example of 1 and 3 https://godbolt.org/z/P4qM4dP86
I find approach 3 somewhat elegant, but maybe its not the most efficient if you want to avoid garbage collection for example.

<details>

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

void test(int& t)
{
    t = 10;
}

template<typename T>
struct Ref {
    Ref(T value) : value(value) {}
    T value;

    operator const T&() const { return value; }
    operator T&() { return value; }
};

int main() {
    sol::state lua;
    lua.open_libraries();

    {
        lua.set_function("test1", [](int t){
            test(t);
            return t;
        });

        lua.script(R"(
            t = 3
            t = test1(t)
            print(t)
        )");
    }

    {
        auto usertype = lua.new_usertype<Ref<int>>("int");
        usertype["new"] = sol::constructors<Ref<int>(int)>();
        usertype["value"] = &Ref<int>::value;
        lua.set_function("test3", [](Ref<int>& t){ return test(t); });

        lua.script(R"(
            t = int.new(3)
            test3(t)
            print(t.value)
        )");
    }
    return 0;
}
```

</details>

**Comment by treytencarey** [comment]
Alright, was hoping it could support it by default but that's okay. Thanks!
