### ISSUE TITLE
gcc-11 error

### ISSUE THREAD

**Issue by etorth** [ThePhD/sol2#1328]
b_release/3rdparty/sol2/single/sol/sol.hpp:7192:88: error: incomplete type ‘std::numeric_limits<long unsigned int>’ used in nested name specifier
 7192 |                                 std::size_t space = (std::numeric_limits<std::size_t>::max)();
      |                                                                                        ^~~
compilation terminated due to -Wfatal-errors.

**Comment by Rochet2** [comment]
> There is a missing `#include <limits>`. This is true for the version godbolt is using (v3.2.1) and the latest v3.2.2 release. Adding the include before the sol header will fix the issue. The issue has been fixed in https://github.com/ThePhD/sol2/commit/e5e6466e09b632677d24a8f204d6a0ea0a8862b1 and is a part of v3.2.3 which tagged but not released like v3.2.2 is.

https://github.com/ThePhD/sol2/issues/1308#issuecomment-1046118288

**Comment by ThePhD** [comment]
This should be fixed in latest.
