### ISSUE TITLE
Suspicious changes to `is_cstr` / `is_cstr_or_string`

### ISSUE THREAD

**Issue by cschreib** [ThePhD/sol2#1330]
I have been using the `v4.0.0-alpha` branch for a while, and thought I would upgrade to the tip of the `develop` branch to get the latest fixes and improvements. Unfortunately there seems to be a regression, because my project no longer runs correctly. I have struggled to debug what the issue exactly is, and to reproduce a minimal example, so instead I just investigated with a `git bisect` in sol2.

I narrowed it down to https://github.com/ThePhD/sol2/commit/ff783a150cbfd4ccd8ea46608c01037c88bfe797, which changes `meta::is_cstr_of` to not include `std::string`. 

I noticed a few things that looked suspicious to me, and after fixing them, my issues disappear. Some of it might be my misunderstanding of what the code does, sol2 is very complex, but it seems to have done the trick.

1. Although most occurences of `is_cstr_v` in "stack_field.hpp" were changed to `is_cstr_or_string_v`, there was one line that used to be
https://github.com/ThePhD/sol2/blob/7aae1aaaaa1bbcc03fd059fe38075cfe3f4b2e90/include/sol/stack_field.hpp#L215
and got changed to just
https://github.com/ThePhD/sol2/blob/50b62c9346750b7c2c406c9e4c546f96b0bf021d/include/sol/stack_field.hpp#L215
That seems like an omission to me, so I changed it to `is_cstr_or_string_v<T>`.

2. In "usertype_storage.hpp", the code now reads
https://github.com/ThePhD/sol2/blob/50b62c9346750b7c2c406c9e4c546f96b0bf021d/include/sol/usertype_storage.hpp#L66-L75
I assume this code is meant to transform stuff like `Fq=char[26]` into `const char*` for storage. But this looks weird, as it would turn `Fq=std::string` into `F=const std::string*`, which would lead to a dangling pointer once the `std::string` goes out of scope. I changed it to use `is_c_str_of` only.

3. In "traits.hpp"
https://github.com/ThePhD/sol2/blob/50b62c9346750b7c2c406c9e4c546f96b0bf021d/include/sol/traits.hpp#L701-L702
Looks wrong. I changed it to `= is_c_str_or_string<T>::value`.

It was after fixing point 3 that my problem disappeared.

**Comment by ThePhD** [comment]
Hey, thanks for reviewing this. The (1) one was intentional on my part. The rest I'll merge!
