### ISSUE TITLE
How to specify function to execute from load_result/load_file?

### ISSUE THREAD

**Issue by sigmareaver** [ThePhD/sol2#1334]
I apologize if this isn't the right place to ask questions, but I didn't see any other places to ask. I've been reading through the documentation, but am having trouble wrapping my head around what it is I'm trying to achieve.

I would like to use Lua to define my GUI window layouts (Dear Imgui). I already have in my engine, a GUI system that wraps Imgui for organizational purposes (e.g. a GUI manager singleton, a window class to derive from, and a layer class that contains a list of windows to be rendered with an interface OnGUI(float deltaTime)).

I have derived a `LuaWindow` class from my `Window` class. My initial design is to `load_file` a Lua script that contains a function I want to call. Like so:
```lua
function OnGUI(deltaTime)
    -- Draw GUI here.
    return true;
end
```
```cpp
LuaWindow::LuaWindow()
{
    auto result = lua.load_file("my_window.lua");
    if (result.valid())
    {
        m_draw_func = result.get<sol::protected_function>();
    }
}
```

If I'm not mistaken, this stores the whole script in `m_draw_func`, but it seems like I can't get a specific Lua function from the `load_result`. If I understand correctly, I can get the function like so: `m_draw_func = lua["OnGUI"];`

But this has me worried, because I'm using this interface style design of using the same function name for every script file (e.g. `log_window.lua`, `character_window.lua`, `inventory_window.lua`, etc). Will sol become confused about which `OnGUI` is which, or worse overwrite the previous ones?

My goal is to store the `OnGUI` function for each unique window script inside it's own C++ LuaWindow class, and then when the GUI manager iterates over each window, it should execute that Lua function.

**Comment by Rochet2** [comment]
Lua scripts act like functions.
* You can modify/create global variables in the function/script
* You can return data from the function/script
* You can pass in data by reference that you then modify, like a table or userdata

After the function/script call you can access the global data, the returned data or the data you passed in by reference.

In your example Lua code you create a global function `OnGUI`. When the script is run, it acts like a function, which means that it will not return a value. If you want to access `OnGUI` you need to access it with `lua["OnGUI"]` as you mention.
If you store the function reference into C++ and a new lua script overwrites it in Lua, your stored reference will still point to the original function even if the global OnGUI has changed.

You can also use lua environments to isolate the global scope of each script. If you instead would like to access the lua functions without using global scope, you could use input or output of the function.
Here are some examples: https://godbolt.org/z/hxK661x9E

<details>

```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

int main() {
    sol::state lua;
    lua.open_libraries();
    
    // Option 1
    // Use global variables
    {
        auto result = lua.load(R"STR(
            function OnGUI() print("Hello") end
        )STR");
        if (result.valid() && result().valid()) { // If loading code was success and if executing code was success
            sol::function ref = lua["OnGUI"]; // store reference to the function somewhere
            ref();
        }
    }
    
    // Option 2
    // Return the function from the script. Could also return a table of functions
    {
        auto load_result = lua.load(R"STR(
            local function OnGUI() print("Hello") end
            return OnGUI
        )STR");
        if (load_result.valid()) { // If loading code was success
            auto call_result = load_result();
            if (call_result.valid()) { // and if executing code was success
                sol::function ref = call_result; // store reference to the function somewhere
                ref();
            }
        }
    }
    
    // Option 3
    // Pass table into the script as parameter and populate it
    {
        auto result = lua.load(R"STR(
            local T = ...
            function T.OnGUI() print("Hello") end
        )STR");
        auto T = lua.create_table(); // Table we pass into the script/function
        if (result.valid() && result(T).valid()) { // If loading code was success and if executing code was success
            sol::function ref = T["OnGUI"]; // store reference to the function somewhere
            ref();
        }
    }
    
    // Option 4
    // Use lua environment, basically isolating the script's global environment
    {
        auto result = lua.load(R"STR(
            function OnGUI() print("Hello") end
        )STR");
	    sol::environment my_env(lua, sol::create, lua.globals());
        if (result.valid() && result(my_env).valid()) { // If loading code was success and if executing code was success
            sol::function ref = my_env["OnGUI"]; // store reference to the function somewhere
            ref();
        }
    }
    return 0;
}
```

</details>

**Comment by sigmareaver** [comment]
Thank you so much! And also thank you for letting me know that sol2 is on Godbolt. This thoroughly answered my question.
