### ISSUE TITLE
How to manage closures (Lua functions returning Lua functions)?

### ISSUE THREAD

**Issue by GreedyTactician** [ThePhD/sol2#1336]
I am new to Lua's C API and Sol2. 
This is not a feature request.

What are the current tools in this library that can help tackle Lua closures?

Let's say you had the following Lua code:
```
function f(x)
     return function(y) return x+y end 
end 
```

And let's say you wanted to do the following in C++
```
g = f(5)
x = g(4)
assert(x == 9)
```

My attempt of my imagined C++ sol2 solution:
```

#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <assert.hpp>

int main(int, char*[]) {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.script("function f(x) return function(y) return x+y end end");

	sol::function fx = lua["f"];

	??? = fx(5);

	sol::function gx = ???

	int is_nine = gx(4);

	c_assert(is_nine == 9);

	return 0;
}

```

**Comment by Rochet2** [comment]
You can do it very similar way compared to the lua code:
https://godbolt.org/z/4x31G69T1
```cpp
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>
#include <cassert>

int main() {
    sol::state lua;
    lua.open_libraries();

    lua.script("function f(x) return function(y) return x+y end end");

    sol::function f = lua["f"];
    sol::function g = f(5);
    int x = g(4);

    assert(x == 9);

    return 0;
}
```

However, if you want to check for errors at each step, you are going to need to test that f is indeed a function, g is a function and that x is an integer. Here is an example below

```cpp
    sol::optional<sol::function> f = lua["f"];
    assert(f);
    sol::optional<sol::function> g = f.value()(5);
    assert(g);
    sol::optional<int> x = g.value()(4);
    assert(x);

    assert(x.value() == 9);
```

This might not be the only or best way to handle the errors though. But I think its fairly clean. And it should avoid errors during the function calls as well as invalid type return values. I think the error message is lost in this method though.

**Comment by GreedyTactician** [comment]
Oh, that's super straight forward. Not sure why I didn't guess that.
Thank you!
