### ISSUE TITLE
How to use usertypes in lua?

### ISSUE THREAD

**Issue by GreedyTactician** [ThePhD/sol2#1342]
I stared at the [documentation](https://sol2.readthedocs.io/en/latest/api/usertype.html?highlight=usertype ) and the [examples](https://github.com/ThePhD/sol2/tree/develop/examples/source) for a while and I figured I'd just ask because nothing seems to cover this basic case.

```
typedef struct
{
	float x;
	float y;
} vec2;

auto test = [](float x, float y)
{
	return vec2{x, y};
};

lua["f"] = test;
lua.script("a = f(2, 3)");
```

a is now a usertype. How do I access x and y? `print(a.x)` doesn't work. 

Do I need to do shenanigans in C++ with `lua.new_usertype<name>`?

The documentation says the following 

> If the type is [default_constructible](http://en.cppreference.com/w/cpp/types/is_constructible), sol will generate a "new" member on the usertype for you.

But my brain is too smooth to understand the information that follows.

**Comment by Rochet2** [comment]
> Do I need to do shenanigans in C++ with `lua.new_usertype<name>`?

Yes, exactly. See [the basic tutorial](https://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html) and [the rest of the usertype documentation](https://sol2.readthedocs.io/en/latest/usertypes.html).

There is no reflection in C++, so sol cant really generate code on its own for arbitrary structs and classes with just C++.
However, it is possible to hardcode functionality with templates if you know, for example, the function signature beforehand. So sol has hardcoded support for default constructor (and some other things, like to_string).

**Comment by GreedyTactician** [comment]
Ah, I see. I was hoping to avoid that.
Thank you

**Comment by Rochet2** [comment]
There are some generators around that can try to read through C++ code and then make the bindings for lua.
I know of at least one generator for sol. I think it is this one https://github.com/ObEngine/Obidog
Have not tried it though, but looked pretty cool when I was looking for something similar few years back.
