### ISSUE TITLE
[MSVC] 2 tests crash on MSVC release mode

### ISSUE THREAD

**Issue by QuellaZhang** [ThePhD/sol2#1359]
There are 2 tests always fail in release mode but passed in debug mode on MSVC, I've confirmed internally that this is not a compiler bug.

The developer did some more research, it looks like this is due to a newly added test [sol2/1211 - protected_function_result nullptr.cpp at develop · ThePhD/sol2 (github.com)](https://github.com/ThePhD/sol2/blob/develop/tests/regression_tests/simple/source/1211%20-%20protected_function_result%20nullptr.cpp)

The problem is that the default constructor does not initialize LUA State to nullptr. So we are crashing here when we call the destructor, so ensure the default constructor initializes L to nullptr.

Here is the original issue [protected_function_result, destructor SEGFAULT with blank initialisation · Issue #1211 · ThePhD/sol2 (github.com)](https://github.com/ThePhD/sol2/issues/1211).

**Repro steps:**

1. git clone https://github.com/ThePhD/sol2
2. cd sol2
3. mkdir build_x86_Release && cd build_x86_Release
4. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DSOL2_LUA_VERSION=5.3.5 -DSOL2_CI=ON -DSOL2_BUILD_LUA=ON -DBUILD_LUA_AS_DLL=ON -DSOL2_TESTS=ON -DSOL2_EXAMPLES=ON -DSOL2_TESTS_EXAMPLES=ON -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /GR /EHs" ..
5. msbuild /m /p:Platform=Win32 /p:Configuration=Release sol2.sln /t:Rebuild
6. ctest -C Release --output-on-failure

**Failed cases:**
x64|release
The following tests FAILED:
151 - sol2.tests.regression.simple (SEGFAULT)
152 - sol2.tests.regression.simple.SOL_ALL_SAFETIES_ON (SEGFAULT)

x86|release
The following tests FAILED:
151 - sol2.tests.regression.simple (SEGFAULT)

**Comment by ThePhD** [comment]
These tests should no longer crash in latest.
