### ISSUE TITLE
Is there a penalty to runtime functions?

### ISSUE THREAD

**Issue by SirNate0** [ThePhD/sol2#1368]
Working on binding some code from a game library with 100+ functions in a class (probably a number of them). Compiling the binding code for just one of these classes took several minutes and used ~4GB RAM, and even then still just failed*. The error messages were also not particularly helpful, all pointing to the exact same line, and not the actual line within the new_usertype call. By no means a big deal, as the fix is still clear, but it does leave me wondering:

Is there a penalty to runtime functions? Like is described [here](https://sol2.readthedocs.io/en/latest/api/usertype.html#runtime-functions) - binding the functions on following lines to the user type rather than in the new_usertype call itself. I haven't tested it, but I'm hopeful that will cut down on the compile resources (time and/or memory) by not having to deal with the 200+ arguments to the function, in addition to possibly giving clearer error messages. Mainly my concern about the penalty would be during the running of actual lua code, as opposed to when the binding code is being run during the setup, though I suppose that is also important.

In terms of code:
```
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <iostream>

struct object { 
	int value = 0; 
};

int main (int, char*[]) {

	sol::state lua;
	lua.open_libraries(sol::lib::base);

// IS THIS WAY BETTER
	lua.new_usertype<object>( "staticObject" 
            , "func", [](object& o) { return o.value; }
        );

// THAN THIS WAY?
	lua.new_usertype<object>( "runtimeObject" );
	// runtime additions: through the sol API
	lua["runtimeObject"]["func"] = [](object& o) { return o.value; };

	return 0;
}
```

---
*Failure was just a user error, not what the issue was about: `/usr/include/c++/9/type_traits:1294: error: invalid use of incomplete type ‘class Urho3D::Scene’`, etc. - I didn't include all the relevant headers it seems, leaving just some forward declarations.

**Comment by SirNate0** [comment]
An update: Using the "runtime" style binding vastly improved the compilation speed (down to around 10-20 seconds rather than minutes) and also decreased the memory requirement (around 1/3 the amount from before). No comment on the performance of the bindings at runtime, but it certainly is helping the compilation to use the runtime form.

---

This is using `x86_64-linux-gnu-g++-9 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` called as 
`/usr/bin/c++  -mtune=generic  -std=gnu++11 -Wno-invalid-offsetof -march=native -msse3 -pthread -fdiagnostics-color=auto -g -DDEBUG -D_DEBUG   -std=gnu++17 -o test-out.cpp.o -c test-out.cpp`

**Comment by ThePhD** [comment]
We go through a hell of a lot to prevent runtime degradation where possible. Whether there are hits or not is left up to how good the optimizer is and a lot of other factors I can't answer without profiling things aggressively.

I don't think it's worth the pain of trying to bind everything using the `new_usertype` way, with everything in one function call. A better way which might still preserve the speed would be:

```cpp
// …
	auto staticObject_lua_class = lua.new_usertype<object>( "staticObject" 
            , "func", [](object& o) { return o.value; }
        );
	staticObject_lua_class["func"] = [](object& o) { return o.value; };
// …
```
