### ISSUE TITLE
Unexpected Behavior of "std::shared_ptr"

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#138]
I know that something similar was already issued with #129. And you told that the destructor should be invoked when the `sol::state` is destroyed. But, consider the following case, the destructor is never called:

```
#include <sol.hpp>
#include <iostream>
#include <memory>

class Test
{
public:
	Test() { std::cout << "Test::Test()" << std::endl; }
	~Test() { std::cout << "Test::~Test()" << std::endl; }
};

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	lua.new_usertype<Test>(
		"Test",
		"Create", []() -> std::shared_ptr<Test> {
			auto ptr = std::make_shared<Test>();
			return ptr;
		});
	try
	{
		lua.script(R"R(
print("script start")
test = Test.Create()
test = nil
collectgarbage()
print("script end")
)R");
	}
	catch (sol::error &e)
	{
		std::cerr << e.what() << std::endl;
	}
	return 0;
}
```

The output is:

```
script start
Test::Test()
script end
```

The only difference from #129 is returning the `std::shared_ptr<>` from a function. How can I correct this behaviour?

Thank you.

Note: My system is: Lua 5.3.3, GCC 6.1.1, Arch Linux x86_64.

**Comment by ThePhD** [comment]
This is my bad, I derped in the framework. It's a subtlety where the unique usertype metatable (for shared_ptr/unique_ptr/...) gets registered before the default push one, and it doesn't contain the proper `__gc` method. Fixing now, and will push a 2.9.1 tag to let everyone know.

**Comment by ThePhD** [comment]
Thanks for reporting this. Added new tests to make sure it won't happen again in this specific way.

Got you covered, fam: https://github.com/ThePhD/sol2/releases/tag/v2.9.1

**Comment by jnbrq** [comment]
Thank you.
