### ISSUE TITLE
Strange crash with "lua::state", registered two types and fails when destructing

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#139]
Hello, I am experiencing a crash. My system properties are: Lua 5.3.3, GCC 6.1.1, Arch Linux x86_64.

I first got this crash when I try to invoke `reset()` twice. After some debugging, I thought that the bug occurs when destroying the `sol::state`. The following code demonstrates it. It seems like you try to invoke a null function pointer.

```
#include <sol.hpp>
#include <iostream>

struct CTypeA
{
	int x;
};

struct CTypeB
{
	int y;
};

void RegisterTypeA(sol::state &lua)
{
	lua.new_usertype<CTypeA>("TypeA", "x", &CTypeA::x);
}

void RegisterTypeB(sol::state &lua)
{
	lua.new_usertype<CTypeB>("TypeB", "y", &CTypeB::y);
}

void reset(sol::state &lua)
{
	lua = sol::state();
	std::cout << "  lua state assigned" << std::endl;
	RegisterTypeA(lua);
	std::cout << "  RegisterTypeA done" << std::endl;
	RegisterTypeB(lua); // if I do not register the second type,
						// everything is fine
	std::cout << "  RegisterTypeB done" << std::endl;
}

int main()
{
	sol::state lua;
	std::cout << "lua state created" << std::endl;
	reset(lua);
	std::cout << "reset done" << std::endl;
	return 0;	// returns non-0, crashes
				// I think you try to invoke a null function pointer
				// when destroying the sol::state object
}
```

Thank you for your interest.

**Comment by jnbrq** [comment]
Note: The crash does not occur with v2.5.8 .

**Comment by ThePhD** [comment]
Cannot repro. Do you have a screenshot of the error code or the SEGFAULT message?

**Comment by ThePhD** [comment]
Oh, managed to repro with specific conditions, I think I know why it's breaking. I'll try to push a fix in a little bit.

**Comment by ThePhD** [comment]
Figured it out. Was a double-delete from a key-name derp I did. Everything should be in order in a bit; will retroactively re-release 2.9.0 and 2.9.1 and a new tag 2.9.2 since this is a pretty critical harsh bug.

**Comment by ThePhD** [comment]
This is taken care of. Thanks for vetting the library: I've added a test to make sure this won't happen again as well.

https://github.com/ThePhD/sol2/releases/tag/v2.9.2

**Comment by jnbrq** [comment]
Thank you for fixing this.
