### ISSUE TITLE
Registering String Types

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#140]
This is not a bug report, just a question. Your library handles `std::string` very well. But I have another type of strings: `wxString` from wxWidgets. Can Sol2 and new string types work well together? How could I register them to a `sol::state`?

Thank you.

**Comment by ThePhD** [comment]
You'd need to customize several points to make this work for you.

It'd look something like the following:

````cpp
#include <sol.hpp> // or whatever you currently are using to include sol

namespace sol { namespace stack {
     template <>
     struct pusher< ::wxString > { // or whatever the full qualified name is
          static int push ( lua_State* L, const ::wxString& str ) { 
               return stack::push(L, str.c_str()); // or whatever would need to be done
               // documentation for wxString suggests that data can be stored UTF8/16/32, depending on compiler flags
               // You will need to find out how you want to handle that (we don't handle wchar_t or char16_t or char32_t strings since that means we'd need to also build into Sol unicode conversion routines
           }
     };

     template <>
     struct getter< ::wxString > {
          static ::wxString get ( lua_State* L, int index ) { 
               const char* luastr = stack::get<const char*>(L, index);
               // Lua generally works with ASCII or UTF8 strings, so you'd need to convert internally to what ::wxString offers
          }
     };
} // stack

template <>
struct lua_type_of< ::wxString > : std::integral_constant<type, type::string> {};
} //sol

````

That does look like a lot of work, though... I should consider making things more extensible for other basic types (like the many string types).

Either way, that's how you'd get wxString to get pushed into Lua like a string and read from Lua like a string. You're going to need to full in the blanks, as I don't know what you're compiling for wxWidgets and if you're going to need to do conversions. My hope is that you're doing UTF8, which means you'll be able to just `c_str()` and pass it off to the internal implementation.

**Comment by jnbrq** [comment]
Woww! That looks great! Thanks for fast reply! I will try it right now. :+1: :D

**Comment by jnbrq** [comment]
After the latest release, applying this method causes a lot of compiler problems. What should I change?

**Comment by ThePhD** [comment]
Oops, right. I forgot to mention this.

I formalized the getter/pusher/checker architecture and documented it, so your changes would be minimal (you just need to handle the `record& tracking` parameter in all of them now as well): http://sol2.readthedocs.io/en/latest/tutorial/customization.html

It would probably look like this:

````cpp
namespace sol { namespace stack {
     template <>
     struct pusher< ::wxString > {
          static int push ( lua_State* L, const ::wxString& str ) { 
               // same as before
           }
     };

     template <>
     struct getter< ::wxString > {
          static ::wxString get ( lua_State* L, int index, record& tracking ) {
               tracking.use(1); // THIS IS THE ONLY BIT THAT CHANGES
               const char* luastr = stack::get<const char*>(L, index);
               // same as before
          }
     };
} // stack

template <>
struct lua_type_of< ::wxString > : std::integral_constant<type, type::string> {};
````
