### ISSUE TITLE
visual studio 2019 include is broken.

### ISSUE THREAD

**Issue by 7331eraCkcuFetHwoD** [ThePhD/sol2#1413]
Read these guidelines. They are relatively simple and will allow me to help you better!

For Error Reports:

1. Produce a simple, short, compilable test case that reproduces your problem.
2. Make a descriptive title that summarises the bug as a whole.
3. Explain the bug in as much detail as you can in the body of the issue. 
4. Include Compiler/IDE (Visual Studio, XCode...), Build and Deployment System, Language (C++, Objective-C++), and any special defines you have set.

If you want to request a feature:

1. Produce any relevant imaginary code that illustrates what you would like or desired behavior.
2. Include a description and title of what you would like.
3. Annotate and describe the behavior through comments, asserts or just a small write up.

Thanks for helping sol2 grow!

**Comment by OrfeasZ** [comment]
If you have an issue with the library you should explain the steps you took and the issue you're having, and someone will help you. Coming in here without putting any effort in reading even the things you post and complaining about the hard work someone's put in and is providing to you for free doesn't help anyone.

**Comment by 7331eraCkcuFetHwoD** [comment]
#define SOL_ALL_SAFETIES_ON 1

#include <sol/sol.hpp>

int main()
{
   sol::state _lua;
}

C++ incomplete type is not allowed

**Comment by ThePhD** [comment]
> Opened this issue (their first ever)

Poor dear. You came to the wrong library to be a piece of shit.

Good luck elsewhere. (Sorry for the trouble, @OrfeasZ - I do need to update the tutorial section and getting started, but I'm still busy trying to hammer down the Standard C and C/C++ text stuff at the moment! I'm hoping to come back to sol2 when I start my official I Am Not Doing Anymore Work On Standard Things come 2023, which I blocked the whole year off for relaxation / vanity projects, which sol2 is on the list!)
