### ISSUE TITLE
Correct way to bind nested classes

### ISSUE THREAD

**Issue by deadlocklogic** [ThePhD/sol2#1419]
Code:
```cpp
struct type1 {
    struct type2 {
    };
};
```
Binding:
```cpp
auto utype1 = state.new_usertype<::type1>(
    "type1"
);
auto utype2 = state["type1"].get<sol::table>().new_usertype<::type1::type2>(
    "type2"
);
```
This works thought but the indirection feels smelly, is there a cleaner way to do so?
Thanks.

**Comment by ThePhD** [comment]
At the moment, this is the way to handle it, yes. It is clunky, and it would be nice if there was a relationship I could automatically build here, but unfortunately the way this work is that each of those types are entirely different even though they're visually / lexically "related" by one being nested in another.
