### ISSUE TITLE
register vector of pointers

### ISSUE THREAD

**Issue by cgloeckner** [ThePhD/sol2#142]
Hi it's me again :D I fail at using a vector of pointers. Using a vector of a registered type works. Once I pass a vector of pointers (to my registered type), if fails:
``` attempt to index local 'vec' (a userdata value)```

```c++
#include <sol.hpp>
#include <vector>

struct Vec {
	int x, y, z;
};

int main() {
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	lua.new_usertype<Vec>("Vec", "x", &Vec::x, "y", &Vec::y, "z", &Vec::z);
	lua.script_file("test.lua");
	
	Vec vec;
	vec.x = 1;
	vec.y = 2;
	vec.z = -3;
	
	std::vector<Vec> foo;
	foo.push_back(vec);
	
	std::vector<Vec const *> bar;
	bar.push_back(&vec);
	
	
	lua["func"](foo); // works
	lua["func"](bar); // fails
}
```
and
```lua
func = function(vecs)
	for i, vec in ipairs(vecs) do
		print(i, ":", vec.x, vec.y, vec.z)
	end
end
```
What am I doing wrong this time? XD

**Comment by ThePhD** [comment]
It's not that they're pointers, it's that I was a Derp and didn't remove the `const` when getting the Usertype Table that allowed you to index stuff.

It's fixed, just gonna run the tests to make SURE it's fixed...

**Comment by ThePhD** [comment]
Should be okay: https://github.com/ThePhD/sol2/releases/tag/v2.9.3
