### ISSUE TITLE
Question: Iterate over userdata properties / members

### ISSUE THREAD

**Issue by BluFedora** [ThePhD/sol2#146]
I was wondering if there is a way for me to iterate over the registered members of a userdata variable. 

I do know of iterating over the metatable:
```lua
local myUserData = Somthing.new();

for k, v in pairs(getmetatable(userDatavar)) do
    print(k, type(v)); -- btw it crashes if the value of v is being printed out.
end
```
but the problem is I don't know how I would use the metatable to "inspect" the variable.

So I'm making a property inspector (so far works for tables, string, etc) and would like a list of members registered to a variable . How would I get this info without know the variable's type?

I suppose this is more of a core Lua issue but I was wondering if there is a way to get this type info using this library.

Thanks in advance if anyone can help.

**Edit:** Oh yeah and it doesn't matter if the type info is on the C++ or Lua side.

**Comment by ThePhD** [comment]
So! The answer might actually change based on which version of Lua you're using (if I'm remembering the Lua Docs correctly) and in which style you register things.

For `lua.new_usertype<things...>( stuff... )`, it might not work below Lua 5.3. The reason being, ipairs / pairs does not consult the "__index" metamethod, which is used to link variable names and stuff.

If there's no variables or you use `lua.new_simple_usertype<things...>( stuff... )`, it might do a "simple" registration, and the "name" <-> function mapping will be there. How it behaves with pairs / ipairs is beeeyoooond me. Again, using `__index` to look things up in this case might work, or it might do raw access (which ignores the `"__index"` metamethod). I really haven't looked too much into this!

As far as C++ access goes, we don't really keep that data around in C++. It gets serialized to Lua and then left alone. Exposing it in C++ would take... quite a bit of effort on your or my part, and probably not yield very much helpful information.

**Comment by BluFedora** [comment]
I'm using Lua 5.3 and registering with ```lua.new_usertype<things...>( stuff... )```. Thanks for explaining some stuff. Ehh this does seem to be very difficult. If we can't find a solution I'll just resort to using tables for inspectable objects.

**Comment by ThePhD** [comment]
So I went back and checked through the metatables of the bound types. It seems like they're iterable with `pairs` just fine:

![Looks okay?](http://i.imgur.com/fq4zzaR.png)

As you can see, most everything's just a function (except for some GC entries and what not). You may want to instead look into iterating over the userdata itself, which may yield more useful results as far as inspection / reflection goes.

**Comment by ThePhD** [comment]
... Except you can't iterate over the userdata itself, right!

So, you'd just have to manually call the functions / variables, and you'd have to know which ones you bound as functions / variables and what arguments that you'd need to call it with.

I'm still not sure how this would be useful for you, though.

**Comment by BluFedora** [comment]
That should be helpful, all I need really is a list of variables *names*. Maybe I can use that list and ignore all that start with "__". 

How would I get the metatable of userdata in C++?

**Comment by BluFedora** [comment]
Ok, got it working for what I need:

```cpp
bool startsWith(const std::string &key, const std::string &prefix)
{
    return (key.size() >= prefix.size()) && (key.compare(0, prefix.size(), prefix) == 0);
}

int main()
{
    struct Vec {
            int x, y, z;
    };

    static const std::string metaPrefix = "__";

    sol::state lua;
    lua.open_libraries(sol::lib::base);
    lua.new_usertype<Vec>("Vec", "x", &Vec::x, "y", &Vec::y, "z", &Vec::z);

    lua["testTable"] = Vec{100, 200, 300};

    sol::table testTable    = lua["testTable"];
    sol::table metaTable    = testTable[sol::metatable_key];

    std::vector<std::string> keys   = {};
    std::vector<int> values         = {};

    for (const auto &pair : metaTable)
    {
        const std::string key = pair.first.as<std::string>();

        if (!startsWith(key, metaPrefix))
        {
            keys.push_back(key);
            std::cout << key << ", ";

            if (key != "new")
            {
                values.push_back(testTable[key]);
            }
        }
        else
        {
            // The Meta Methods and stuff here
        }
    }

    std::cout << std::endl;

    // Should Print Out: "x, y, z, new,"

    return 0;
}
```

I do hope this solution isn't too fragile given such hard coded checks.

(Btw not at all how my property inspector works but this just shows the principle of extracting a property list lol)

Should I close this issue or should a better solution be thought up?

**Comment by ThePhD** [comment]
Well, you're able to store the values in a vector of ints because you know -- ahead of time -- that it's going to be a vector of ints.

So, unless you remember all the bindings you do, it's going to be a bit difficult to store things...

Perhaps I should look into providing some additional runtime type information that tells people what each key is for, and what it's supposed to yield? Nevertheless, this is a feature that's way off from happening and will take quite a bit of finesse to do.

**Comment by BluFedora** [comment]
Can't you just store the value (gotten from the table) in a ```sol::object``` and use the ```sol::object::is<T>``` method? That's what I'm doing currently and it seems to be working. 

I first to see if check the object is ```== sol::nil```, then I check in an if else chain against ```double, bool, std::string, sol::function, sol::userdata, sol::table, and sol::thread```

making sure to put  ```std::string``` as the last of the primitives since as quoted (2.2.1 – Coercion of the manual):
"Lua provides automatic conversion between string and number values at run time"

and making sure to put ```sol::userdata``` before ```sol::table``` because userdata apparently can be converted / used as a table (I don't know if this is a *sol2* thing or a *Lua* thing).

**Comment by ThePhD** [comment]
It's a _both_ thing. If you give a userdata to Lua, except in cases where they do explicit type checks (like `pairs( ... )`), overriding __index and __newindex basically allows a userdata to behave like a regular table. Also, userdata and tables can be made to behave like functions with the `__call` metamethod, so `sol2` does not force an error on those either.

It may be more beneficial to do a `sol::object::get_type();`, and then switch on that to be as specific as you like, as it will save you quite a few checks from repeatedly calling `is`.

After that, feel free to convert as you want to, yes!

**Comment by ThePhD** [comment]
Going to mark this as done for the time being, since it seems you're getting along just fine.

If you think this is something I should add to the docs, feel free.

**Comment by BluFedora** [comment]
Oh yeah that seems good, I did switch to using a switch statement using ```sol::object::get_type();``` and everything seems to work out just fine. Thanks.
