### ISSUE TITLE
attempt to index a nil value (global 'debug')

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#148]
When I run a lua file with **script_file**, in the lua file can not use debug.traceback(), which _**attempt to index a nil value (global 'debug')**_, but debug is lua library, why I can't use it ?

**Comment by ThePhD** [comment]
Standard libraries must be opened on the Lua state.

````cpp
sol::state lua;
// lua.open_libraries( sol::lib::base, sol::lib::debug ); // open specific libraries
lua.open_libraries(); // opens everything
````

A fresh Lua state has no libraries opened (easy environment control, etc.).

**Comment by aiplay** [comment]
Yes, I only open_libraries(sol::lib::base), if I open debug library, debug can work. Thanks! 
Please closed issue.
