### ISSUE TITLE
Build problems on Clang

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#15]
I saw the listed support for Clang 3.6, however, the current state does not compile against it. 

Here is my build [log](https://gist.github.com/Nava2/c9775f4ad3ba87e6b857). 

I'm happy to help, but if I'm honest, I'm not that well versed in the level of templates used here. 

```
$ clang++ --version
Ubuntu clang version 3.6.2-1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

I haven't tried this against MSVC, but as of late, they're [pretty good](https://msdn.microsoft.com/en-us/library/hh567368.aspx#cpp14table) with C++11 things and lacking a *bit* on C++14. 

The build badge for travis is misleading, the project doesn't build on Travis at the moment, that should probably be adjusted.

**Comment by nabijaczleweli** [comment]
Re: badge: It points to `Rapptz/sol`

**Comment by Nava2** [comment]
Much better [gist](https://gist.github.com/Nava2/9597602e7d757a9fa145), built the tests against clang 3.6.

**Comment by ThePhD** [comment]
Opening up a new Travis CI build (apologies).
Most of these errors are due to my recent refactoring: VC++ bites me in the ass here because it doesn't throw errors on template that aren't explicitly compiled, and there's a feew code bits (like `resolve.hpp`, where you're getting the errors) that are provided as utils for the user to use if they need them (but its rare).

**Comment by Nava2** [comment]
I find it odd that GCC passes it too, though. That being said, it sounds like it's known *where* the issues are happening. 

I'm going to open a PR to make the travis build friendlier.

**Comment by ThePhD** [comment]
Should be fixed now: https://github.com/ThePhD/sol2/commit/9c21d11b8c5aa6bfd885d6dd0278559e5299a279

**Comment by nabijaczleweli** [comment]
@ThePhD Why don't you close issues with your commits?
