### ISSUE TITLE
Question: Sol2 way to manipulate the Lua registry

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#151]
Consider the examples here: https://www.lua.org/pil/27.3.1.html

Are there any way to alter the registry, just like in that article, but in a prettier way using Sol2?

Thank you.

**Comment by ThePhD** [comment]
````cpp
sol::state lua;
sol::table registry = lua.registry();
````

http://sol2.readthedocs.io/en/latest/api/state.html#function-global-table-registry-table

Have fun!

**Comment by jnbrq** [comment]
Thank you.
