### ISSUE TITLE
how to use Sol with lua dll?

### ISSUE THREAD

**Issue by Intervel** [ThePhD/sol2#1533]
what macro to use?

i download lua from the official.

https://luabinaries.sourceforge.net/download.html
i chose Windows x64 DLL and Includes(MingW-w64 6 Built)

got this binary dll

![1](https://github.com/ThePhD/sol2/assets/86478025/1cf79fd2-75cf-4cdb-adb0-5ccd56ce7025)

no lib file,  only dll.

**Comment by congard** [comment]
sol is a CMake project. So the easiest way to use Lua is to use it [via CMake](https://github.com/walterschell/Lua).

Then just create `CMakeLists.txt` like this:

```cmake
cmake_minimum_required(VERSION 3.26)
project(Sol2Test LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)

add_subdirectory(Lua)
include_directories(Lua/lua-5.4.6/include)

add_subdirectory(sol2)
include_directories(sol2/include)

add_executable(Sol2Test main.cpp)
```
