### ISSUE TITLE
VS14

### ISSUE THREAD

**Issue by aDevilInMe** [ThePhD/sol2#154]
The docuemenation, on github, does state that the library requires c++14 features but it also states that it support VS14. I have a default install of VS14 and the library is erroring. [1]. I know that you, at least at times, are using VS so I assume this requires a service pack to be installed. Would I be correct in assuming it requires SP2? If it does could you state this in the documentation please?
Thanks.

... \sol.h(8970): error C3520: 'I': parameter pack must be expanded in this context
... \sol.h(8969): note: while compiling class template member function 'bool sol::usertype_metatable<T,std::integer_sequence<_Ty,0x00,0x01,0x02,0x03>,const char (&)[4],int (__cdecl &)(lua_State *),const char (&)[4],int (__cdecl &)(lua_State *),const char (&)[4],sol::constructor_list<sol::types<>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::contains_variable(void)'
1>          with
1>          [
1>              T=Set_get,
1>              _Ty=size_t
1>          ]

**Comment by Nava2** [comment]
Do you mean VS2014 or VS14? I think VS2015 is required, which is version 14 (oddly).

**Comment by ThePhD** [comment]
The library utilizes some C++14 and some C++17. But, I develop purely in VS (and compile after with clang and g++ to eliminate errors and ensure tests are working).

I don't know what "SP2" is as far as VS14 is concerned: the lowest supported version is Visual Studio 2015 Community Edition, with whatever updates come along with it. It _shouldn't_ error with VS 2015 Community Edition with no updates, but I don't check that, just the latest, and travis-ci checks all the versions of g++ and clang++ we care about.

**Comment by aDevilInMe** [comment]
@Nava2 VS14 is vs 2015 there was no vs 2014.
@ThePhD SP2 was referring to service pack 2, from all account sp3 (or update 3) is a nightmare. With regards to using VS14 without updates it does error, that is what I was reporting.
