### ISSUE TITLE
Runtime error : no matching function call takes this number of arguments and the specified types

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#155]
Here is my code : 

```
#include "sol.hpp"
class A {
public:
    A() {};
    ~A() {};
};

class B {
public:
    B() {};
    ~B() {};
    A* getA()
    {
        return new A();
    }
    void foo(const A* a) {
        // printf("B foo !!\n");
    }
    void foo(const char* name)
    {
        // printf("name : %s\n", name);
    }
};

int main(void)
{
    sol::state lua;
    lua.new_usertype<B>(
        "B",
        "getA", &B::getA,
        "foo", sol::overload(sol::resolve<void(const A*)>(&B::foo), sol::resolve<void(const char*)>(&B::foo))
    );
    lua.script("local b = B.new(); local a = b:getA(); b:foo(a)");
    return 0;
}
```

The detail error print ：
libc++abi.dylib: terminating with uncaught exception of type sol::error: lua: error: [string "local b = B.new(); local a = b:getA(); b:foo(..."]:1: sol: no matching function call takes this number of arguments and the specified types

But， the sol 2.9 is ok for the same code.

**Comment by ThePhD** [comment]
My bad here. I forgot to add the appropriate const-removal from the pointer checker, not just the getter.

Grab the new single file here: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
