### ISSUE TITLE
in sol3 an error occurs when working with 64-bit numbers

### ISSUE THREAD

**Issue by S1NGer-iwni** [ThePhD/sol2#1553]
I work with lua 5.3 and sol3. When working with 64-bit numbers, an error occurs, but if I use luajit, then there is no error, AFAIK lua 5.3 supports 64-bit numbers, how can I fix this problem?

error text:
sol: syntax error: [string "return 10000152ull"]:1: <eof> expected near 'ull'
P.S.
unfortunately I don't have the opportunity to use luajit on a permanent basis

**Comment by Rochet2** [comment]
Lua 5.3 supports 64-bit SIGNED integers ([ref](https://github.com/ThePhD/sol2/issues/590#issuecomment-366031122)).
So unsigned integers are not supported and `return 10000152ull` is not valid lua as you can see from the error.

Luajit has its own support for these integers. While they appear to be a part of the language, they are actually wrapped into cdata objects. See [this](https://luajit.org/ext_ffi_semantics.html#convert_tolua).

Some alternatives are outlined in [here](https://github.com/ThePhD/sol2/issues/677#issuecomment-399792011).
Also, a wrapper approach is looked at [here](https://github.com/ThePhD/sol2/issues/782) as the customization points allowed one to customize how a type is passed into and out of sol.

**Comment by S1NGer-iwni** [comment]
okay thx
