### ISSUE TITLE
How to return anything from a function in Sol3?

### ISSUE THREAD

**Issue by GasimGasimzada** [ThePhD/sol2#1557]
I want to create the following interface:

```lua
local entity_query = game:get("EntityQuery")
local entity_spawner = game:get("EntitySpawner")
```

To make the code more maintainable, I want to create a function that returns anything and internall, return the needed user types and tables:

```cpp
sol::object GameLuaTable::get(String name) {
  // I am planning to dynamically identify all these services
  // using some form of map
  if (name == "EntityQuery") {
    return EntityQueryLuaTable(state);
  }

  if (name == "EntitySpawner") {
    return EntitySpawnerLuaTable(state);
  }

  // ...
}
```

Currently, I need to return `std::variadic` for this but I do not want to think about this part and want to just return anything. Is it possible to do it in Sol?

**Comment by Rochet2** [comment]
If you dont want to explicitly declare the return types with `std::variant` (which should also work AFAIK), you can create a `sol::object` with `sol::make_object(lua, anything_here)`.
And you can get lua from within a function bound with sol by using `sol::this_state`.
Here is an example that should work

```cpp
struct Foo {};

sol::object exampleFunction(sol::this_state const& s, int value)
{
    sol::state_view lua(s);
    if (value == 1)
        return sol::make_object(lua, "something");
    if (value == 2)
        return sol::make_object(lua, 123);
    if (value == 3)
        return sol::make_object(lua, new Foo());
    return sol::make_object(lua, sol::lua_nil);
}
```

Though, doesnt variadric return also work for you?

**Comment by GasimGasimzada** [comment]
Thank you!
