### ISSUE TITLE
Class hierarchies

### ISSUE THREAD

**Issue by aDevilInMe** [ThePhD/sol2#156]
I have the following class hierarchy[1] that I am trying to bind in Sol2 using the code [2]. I have tried reading the documentation, looking at the examples and tests to find what I am missing, yet I am struggling to get the code to work. The base class functions are not available in the derived class instances. What am I missing? Thanks.

[1] https://bitbucket.org/liamdevine/oolua/src/37ebf2398265cff5d153cdac85f9d26e1f5bf2d7/profile/hierarchy.h?at=default&fileviewer=file-view-default
[2] https://gist.github.com/aDevilInMe/a487b0a62c9823da226b6213d66e0433

**Comment by Nava2** [comment]
Can you show the Lua code you're having problems with as well?

**Comment by aDevilInMe** [comment]
@Nava I have modified the factory functions to provide a Sol constructor for the objects[1] and I then use the following file [2]
Thanks

[1] https://bitbucket.org/liamdevine/oolua/src/37ebf2398265cff5d153cdac85f9d26e1f5bf2d7/profile/binding_compare.lua?at=default
[2] https://bitbucket.org/liamdevine/oolua/src/37ebf2398265cff5d153cdac85f9d26e1f5bf2d7/profile/compare.lua?at=default

**Comment by ThePhD** [comment]
It seems like (? not exactly sure) that you're expecting Sol to bind base class members when you bind derived members. Unfortunately, Sol doesn't do that right now: you'd have to bind the  member functions for each class for that binding specifically.

It's on my list of things to look into a performant way of handling, but at the moment I'm not sure yet. Right now Sol doesn't enforce that bindings between every created `lua_State*` are equal, and I don't have a way to quickly do a back-tracking lookup on base classes that wouldn't incur a degree of overhead just yet.

I was simply hoping to wait until C++2x, when they finally will (hopefully) get compile-time reflection and I get to do all this for free without me having to bother explicitly. That's... probably wishful thinking, though.

**Comment by aDevilInMe** [comment]
Thanks for the reply. I added the functions to the derived classes, if you are interested the results they are below. The first value being a cached value and the second being a self call.
| | | |
| OOLua mfunc | 6.75e-08 | 9.08e-08 |
| OOLua vfunc | 7.34e-08 | 9.39e-08 |
| OOLua class param | 1.061e-07 | 9.99e-08 |
| | | |
| Sol2 mfunc | 1.077e-07 | 1.347e-07 |
| Sol2 vfunc | 7.57e-08 | 1.053e-07 |
| Sol2 class param | 4.492e-07 | 4.55e-07 |

**Comment by ThePhD** [comment]
Yeah, those numbers look about right. The difference observed between the times is the serialization cost Sol pays: while all of those functions are basically compile-time names, when they get put into the `new_usertype` or `usertype` constructors it essentially turns them into runtimes values, <Insert long rant about wanting constexpr arguments>.

Basically, to achieve speeds that'd probably look a bit more similar it might be interesting to turn those additional calls into `sol::c_call` bindings, like [so](http://sol2.readthedocs.io/en/latest/api/c_call.html).

Of course, it is not even remotely pretty, hencewhy the recommendation on the page is to stick with the clarity.

Good news: in the last C++ meeting they approved `template <auto X>`. Which means that ugly, nasty syntax will become `sol::c_call<my_func>`, with no need to specify the type, and that'll be that!

**Comment by aDevilInMe** [comment]
I will give that a shot. To be honest with you, Sol2 is the first binding library that I have compared against where I have had to disable runtime checks in OOLua, so credit to you for that.

**Comment by ThePhD** [comment]
I'm going to mark this issue as resolved, unless there's something special that needs to be done in addition (I opened up the automatic registration of base class metatables in another issue). Thanks for letting me know about this data and your work!
