### ISSUE TITLE
Automatically bind Base Class Metatables to Derived Classes

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#157]
As it stands, derived classes need to re-specify base members already bound. It would make sense if there was some degree of retroactive backwards-compatible lookup for base functions so that a person did not need to register them explicitly.

Performance might be a concern at first, but just having the feature might be more worth it.

**Comment by ThePhD** [comment]
https://github.com/OrfeasZ/sol2/tree/member-inheritance

Remember to look through this more thoroughly.

**Comment by ThePhD** [comment]
@OrfeasZ So, I took a stab at implementing my member inheritance and added a benchmark (just for Sol2 right now, will do the other frameworks later). For my version, the cost looks like this:

![Not too bad, I guess?](http://i.imgur.com/8pmYEfk.png)

I'm using [lua bench](https://github.com/ThePhD/lua-bench) to do my benchmarking. In a moment, I'll pull your version of sol2 and run it to see what the performance looks like.

As a side note, note that my implementation doesn't require any state held C++-side, though it ostensibly costs us in lookup time (e.g., see the execution time of just calling a member function we know is there):

![Pretty decent](http://i.imgur.com/blsTuvS.png)

**Comment by OrfeasZ** [comment]
Keep in mind that my branch still has the copy constructor issue I reported a few days ago. Not sure if that changes anything.

**Comment by ThePhD** [comment]
Problem with my approach, as well:

Calls to a base function cast to `Base*` to do the call from the `void*` stored as a Lua userdata. This means that vtables and other important information, if that `void*` was originally a `Derived*`, get misaligned. This results in funky accesses and bad crashes at horrible times.

Not sure how to fix.

**Comment by ThePhD** [comment]
And I've fixed it by keeping the casting logic in the `getter` for usertype. So everything seems to work out now.

**Comment by ThePhD** [comment]
Haaaahahaha it's terrible *sobbing noises*

![SOB.](http://i.imgur.com/B9ODA3e.png)

**Comment by ThePhD** [comment]
We'll release it but this issue stays open 'till we figure out a better way to do it.

**Comment by OrfeasZ** [comment]
Can you share the benchmarking code you used so I can take a look when I have the chance?

**Comment by ThePhD** [comment]
https://github.com/ThePhD/lua-bench

There's a sol submodule -- after cloning (and recursively init / update submodules), just point the sol submodule at your fork's url and the commit.

**Comment by OrfeasZ** [comment]
Thanks, I'll give it a try when I'm back from my holidays.
