### ISSUE TITLE
Can not get the global table from c++ code

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#158]
Here is my code:
```
int main(void)
{
    sol::state lua;
    lua.open_libraries();
    lua.script("a = { 3, 5 }");
    sol::table t = lua["a"];
    printf("t[1] : %d\n", t[1]);
    return 0;
}
```
The print result is 1435718280 instead of 3.

**Comment by ThePhD** [comment]
When working in VC++: `main.cpp(10): warning C4477: 'printf' : format string '%d' requires an argument of type 'int', but variadic argument 1 has type 'sol::proxy<sol::basic_table_core<false,sol::reference> &,int>'`

`t[1]` is not an integer. It is a `sol::proxy<...>`. `printf` does not take hard types, therefore it will pass `sol::proxy<...>` direct, interpret its raw bits as an integer, and then print it. This means it fails.

Try using `t[1].get<int>()`
