### ISSUE TITLE
How to pass Lua Closures into C++ Functions in Sol3 ?

### ISSUE THREAD

**Issue by theanimatorspal** [ThePhD/sol2#1583]
This is inside a new_usertype
```
		"SetDrawCallback",
		[](Jkr::WindowMulT& inWindow, sol::function& inFunction) {
			inWindow.SetDrawCallBack([&inFunction](void*) { inFunction(); });
		},
```

but it isn't working. I also tried setting sol::function instead of sol::function&, it compiled but gave runtime error in lua_gettop() function.

**Comment by theanimatorspal** [comment]
Yup. " I also tried setting sol::function instead of sol::function&," I said.

**Comment by skaarj1989** [comment]
>  I also tried setting sol::function instead of sol::function&,

This means that you have a temporary argument `sol::function inFunction` and then you capture that temporary argument by reference in the next lambda (`inWindow.SetDrawCallBack`).

**Comment by theanimatorspal** [comment]
Ah man, thank You.
