### ISSUE TITLE
Behavior of returning nullptr not explained clearly

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#159]
In my application there are some cases where I'm returning pointers to objects from bound C++ functions like so:

```cpp
std::shared_ptr<SomeType> MyFunction()
{
    return std::make_shared<SomeType>(1, 2, 3);
}
```

However, there are some other cases where said functions can return `nullptr` (or an empty `shared_ptr`) like so:

```cpp
std::shared_ptr<SomeType> MyFunction()
{
    if (!something)
        return nullptr; // or std::shared_ptr<SomeType>();

    return std::make_shared<SomeType>(1, 2, 3);
}
```

Reading the [docs](http://sol2.readthedocs.io/en/latest/tutorial/ownership.html), it is unclear whether this behavior will be properly handled by Sol or not. Even though it's stated that returning nullptr is detected and handled, the example below seems to frown upon doing so (even though it uses a standard C pointer instead of a smart pointer in that case).

Does my code need adapting or will Sol properly handle ownership of objects on the Lua side and automatically de-allocate them when required?

**Comment by Nava2** [comment]
It will store a nil value if the pointer is nullptr in my experience. This
makes sense, but if it's not written in the docs clearly, it should be
updated!

**Comment by ThePhD** [comment]
I do need to make a big list of the out-of-the-box provided handles for `getter`/`setter` in a well-defined list somewhere.

There's a lot of places where I need to write the docs better, like a few more pointed top-level categories that address user's questions. I should also make a `performance` toplevel category to inform people of things like `sol::c_call`.

.... Ahhhh my fingers hurt just thinking about all the work I need to do. ;~;

**Comment by ThePhD** [comment]
Oh, right. I didn't answer the question proper.

Yes.

We do `if (X == nullptr)` as a check by default for pointer types. For `unique_usertype`s, which include `std::shared_ptr`, `std::unique_ptr`, and any other `ptr`s you can imagine (like `boost::shared_ptr`), we also do this check, but it can be [overridden](http://sol2.readthedocs.io/en/latest/api/unique_usertype_traits.html) for the purposes of customization.
