### ISSUE TITLE
Passing nil as userdata to C++ to reset a variable

### ISSUE THREAD

**Issue by diath** [ThePhD/sol2#1592]
Hi, I have a C++ function that accepts `std::shared_ptr<Type>` as an argument, I want to also be able to call the function with `nil` from Lua, to reset the said pointer, however it's not possible because sol expects actual userdata type on the stack, is there a way to work around this without adding a separate function for resetting the pointer?

Example: https://godbolt.org/z/s964fx36e

**Comment by diath** [comment]
I can change the API, so that works, just a bit unfortunate that I need to include the sol header in that class now which adds a bit of compile time overhead. Thanks.

**Comment by Rochet2** [comment]
You can also just do this instead to avoid the compile overhead but have a wrapper.
```cpp
state["setActiveWidget"] = [](sol::optional<std::shared_ptr<Widget>> w){ return setActiveWidget(w ? *w : std::shared_ptr<Widget>()); };
```
