### ISSUE TITLE
Question: how did lua code got a string from c++ function

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#160]
For example:

```
#include <sol.hpp>
#include <string>

std::string f()
{
    return string("hello");
}

int main(void)
{
    sol::state lua;
    lua.set_function("f", f);
    lua.script("print(f())");
    return 1;
}
```

My question is : how lua code can get the exactly string from f(), where push the result of f() into the lua stack?

**Comment by ThePhD** [comment]
You can insert a breakpoint in `f` and step-through the code since it's header only, if you want the nitty-gritty details.

Basically: a Lua C Function that serves as a wrapper is called. C Function works like this:

```` cpp
int sol_generated_wrapper( lua_State* L ) {
     // retrieve function `f`
     // pull any arguments off stack (there are none in your example)
     // push all results on stack
}
````

Roughly speaking,

```` cpp
int sol_generated_wrapper( lua_State* L ) {
     typedef std:string(*Fx)();
     Fx fx = /* blah blah serialization */;
     // no arguments
     // Call function, get results
     decltype(auto) r = fx();
     // Perfectly forward into Lua stack
     int number_pushed = sol::stack::push(L, std::forward<decltype(r)>(r));
     return number_pushed;
}
````

We're glossing a lot of details because they're boring. Why do you ask?

**Comment by aiplay** [comment]
Thanks a lot! I'm very interested about sol2, and want to know how it works. By the way, in case of any problems encountered, I can fix it by myself first and help to perfect sol2.

**Comment by ThePhD** [comment]
That'll be great. There's a few things on my mind that I'd like to try to add / fix sometime soon: they're mostly contained in the issues. Remember that you don't always have to use the raw Lua API when implementing stuff: `sol::stack` provides a lot of useful, easy-to-use abstractions around the C API that are just as performant.
