### ISSUE TITLE
Why sol3 is slower than Luabridge3 when both using LuaJIT, 

### ISSUE THREAD

**Issue by qiuxinyun2010** [ThePhD/sol2#1600]
The test case is to sum to 10000000. 

execution time:

- C++ native: 6ms
- Sol3.3.1 + lua5.4.4: 253ms
- LuaBridege3 + lua5.4.4: 284ms
- Sol3.3.1 + luajit2.0.5: **56ms**
- LuaBridege3 + luajit2.0.5: **7ms**

```
lua.script(R"(
        x = 0;
        for i = 1, 10000000 do
            x = x+i;
        end
 )");
// sol took 56 ms
// luabridge took 7ms

int x = 0;
for (auto i = 0; i < 10000000; i++)
{
  x0 += i;
}
// took 6ms
```

**Comment by hfn92** [comment]
did you load the jit module with `lua.open_libraries(sol::lib::jit)`?
