### ISSUE TITLE
Questions regarding Usertype inheritance

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#163]
Documentation states `Please be advised that this was a breaking change from before: previously, with the power of exceptions we did not need to list base classes. This unfortunately came at the cost of quite a bit of performance, and therefore it is not adivsable / required to specify all of your base classes, exceptions or no exceptions, RTTI or not: always specify your bases.` when it comes to inheritance. However, this sentence makes no sense. Do we need to specify everything using `sol::base_classes, sol::bases<A, B, ..>`, or not?

**Comment by OrfeasZ** [comment]
Additionally, for multi-level inheritance, ie:
```cpp
class A {}
class B : public A {}
class C : public B {}
class D : public C {}
```

When specifying class `D` as a usertype through Sol, do we need to specify all inherited classes in the chain (`sol::bases<C, B, A>`), or only the top level one (`sol::bases<C>`)?

**Comment by ThePhD** [comment]
Unfortunately, you have to specify all of them right now. This is something I can't change until C++21 (I really hope) gets reflection.

**Comment by ThePhD** [comment]
I should add a note to the documentation.

**Comment by OrfeasZ** [comment]
Specifying all of them is fine, I just think the documentation needs to be updated to reflect that.

**Comment by ThePhD** [comment]
Added it. Will throw it in next push: right after I try to get around variables and demangling improvements.

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/usertype.html#inheritance

Added as a note there.

**Comment by OrfeasZ** [comment]
Awesome. Please check your e-mail when you get a chance.
