### ISSUE TITLE
Inheriting usertypes don't inherit children properties and functions

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#164]
I'm not sure if this is supposed to be standard behavior, but all in my attempts to define a usertype that inherits from another usertype (or multiple) I have been unable to access properties and/or functions defined for the children usertypes when handling the parent one.

See the following example:
```cpp
class A
{
    int a = 1;
    int GetA() { return a; }
}

class B
{
    int b = 2;
    int GetB() { return b; }
}
```

```cpp
state.new_usertype<A>("A",
    "a", sol::property(&A:GetA)
);

state.new_usertype<B>("B",
    sol::base_classes, sol::bases<A>(),
    "b", sol::property(&A:GetB)
);
```

In lua land, having an object of type `B`, one would expect to be able to access all inherited properties, ie:

```lua
local obj = (... instance of B usertype ...)
do_something_with(obj.a)
```

However, this seems to result in the following exception:
`sol: attempt to index (get) nil value "a" on userdata (bad (misspelled?) key name or does not exist)`

Same applies to functions and readonly properties.

**Comment by ThePhD** [comment]
Yeah, this is what #157 is all about.

**Comment by OrfeasZ** [comment]
Ah, sorry. Didn't notice it was the same issue.
