### ISSUE TITLE
Undefined behavior when usertype copy constructor is defined

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#166]
Take for instance the following classes and usertype definitions:

```cpp
class class01 {
public:
	class01() {}
	class01(const class01& other) {}
};

class class02 {
public:
	class02() {}
	class02(const class02& other) {}
	class02(const class01& other) {}
};

lua.new_usertype<class01>("class01",
	sol::call_constructor, sol::constructors<sol::types<>, sol::types<const class01&>>()
);

lua.new_usertype<class02>("class02",
	sol::call_constructor, sol::constructors<sol::types<>, sol::types<const class02&>, sol::types<const class01&>>()
);
```

The following lua code produces the error `sol: attempt to index (get) nil value "├óΓäó┬ío├»┬╜┬í.(├ó┼ô┬┐├á┬╕┬║├»┬╜┬í ├ó┼ô┬┐├á┬╕┬║)" on userdata (bad (misspelled?) key name or does not exist)`:

```lua
x = class01()
y = class02(x)
```

Note: This issue seems to have been introduced after [this](https://github.com/ThePhD/sol2/commit/dc05552e8115e37c5d689f27c801d539397221d0) commit. Any tests performed using previous commits did not present this issue.

**Comment by OrfeasZ** [comment]
Upon further inspection it appears that it's [this](https://github.com/ThePhD/sol2/blob/develop/sol/usertype_metatable.hpp#L408-L411) code that causes the issue. Not quite sure as to why.

**Comment by ThePhD** [comment]
Feexed https://github.com/ThePhD/sol2/commit/9c67e9310e9aa37a5d836c9fe6da527f1dfb3a4c

**Comment by OrfeasZ** [comment]
This issue appears to have been re-introduced in a later version, but seems to occur under different circumstances. I'll see if I can produce a valid test-case for reproduction and update this issue.

**Comment by ThePhD** [comment]
Just open a new issue so I can track this better and maybe refer back to this issue if necessary.

**Comment by OrfeasZ** [comment]
Gotcha. I'll do so when I have more info.
