### ISSUE TITLE
How did a function return sol::table but sometimes maybe return sol::nil？

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#167]
Here is my code:
```
auto multiply(sol::table a, sol::table b)
{
    if (! a.valid() || ! b.valid())
        // I want return nil here
    sol::state state;
    return state.create_table();
}
```
1. Because this function maybe return different type, so compile is fail;
2. Sometimes, I need to check the parameter, in lua code maybe pass a nil value instead of table, in this case, I want to return a special value to tell where call this function has something wrong.

**Comment by ThePhD** [comment]
Your code is a little unsafe.

First off, you create a brand new `sol::state`. That is a completely different `lua_State*` from the one that calls your function. Returning that is bound to create problems.

Secondly, you can return a `sol::object` to return anything that can be represented as a Lua object (i.e., everything). Here's some modification of the function using a few more advanced features of Sol. Try it like so:

````cpp
sol::object multiply(sol::table a, sol::table b, sol::this_state thislua) {
     if (! a.valid() || !b.valid())
          return sol::make_object(thislua, nil);
     sol::state_view existing_state = thislua;
     return existing_state.create_table();
}
````

If you need to do something more complicated, you can use `sol::table::create( existing_state, ... )` static function to aid in complex table creation. You can also make objects out of values easily by using [make_object](http://sol2.readthedocs.io/en/latest/api/make_reference.html).

**Comment by ThePhD** [comment]
See also the new tutorial added: http://sol2.readthedocs.io/en/latest/tutorial/functions.html#any-return-to-and-from-lua

**Comment by aiplay** [comment]
Thank you !!!
