### ISSUE TITLE
Read data from file， how to get the whole file data in the Lua?

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#171]
I write a c++ function to read file content data which return a const char *.
As we know, file may has a "\0" in any where, so need to know the size of the return pointer.
But if I bind a this function with sol, lua will get a incomplete result.
For a simple exaple:

```
sol::object getFileData(sol::this_state l)
{
    // just like read from a file
    const char* s = "xjh\0ssh";
    sol::object o = make_object(l, s);
    return o;
}
```

Lua code
```
local s = getFileData()
print(s)
```
The result is only xjh

How can I pass the exactly size, let sol2 to know when use lua_pushlstring.

**Comment by ThePhD** [comment]
Option 1: Read it as a `std::string`, get the size paramter for free.
Option 2: pull the latest from sol, do `sol::object o = sol::make_object<const char*>(l, s, 7);` (or whatever the size is).
