### ISSUE TITLE
Possibility to panic to console instead of an exception?

### ISSUE THREAD

**Issue by Murloc992** [ThePhD/sol2#173]
Hello,

I love this library so far, but one thing I would love now, would be panicking "silently" and printing to the console, saying what went wrong. Is this a possibility at the moment?

So far I have found that defining SOL_NO_EXCEPTIONS skips and does not throw any exceptions, but it also doesn't show any information at all.

Hope you can help me achieve this small feature. :)

Having SOL_CONSOLE_ERRORS or something to define would be nice!

**Comment by ThePhD** [comment]
`sol::state lua(my_panic_function);`, when creating the state.

`my_panic_function` needs to have the signature of a `lua_CFunction` and be a function pointer. So, just make it a plain function:

````cpp
int my_panic_function( lua_State* L ) {
     		const char* message = lua_tostring(L, -1);
		std::string err = message ? message : "An unexpected error occurred and forced the lua state to call atpanic";
		std::cerr << err << std::endl;

}
````

**Comment by ThePhD** [comment]
I added [an example to the no-exception documentation](http://sol2.readthedocs.io/en/latest/exceptions.html#regular-panic-function). Hopefully this will make it easier for people to handle.

I don't want to drag in `iostream` or `cstdio` by default just yet; it's a thick header and I'd like to let people opt-in to the behavior. Sorry if it seems like a tiny bit more setup than you'd like!
