### ISSUE TITLE
Adding wide string support?

### ISSUE THREAD

**Issue by Murloc992** [ThePhD/sol2#176]
Hello again. :)

In my application I tend to use a lot of national characters in wide character format, mainly in interface element placement. Apparently I cannot use methods that take a `std::wstring` or just `const wchar_t *` as LUA state just panics when I try to use them.

Basically I can have methods like:

```cpp
void PrintWide(const wchar_t * characters)
{
    wprintf(L"%s", characters);
}

void PrintWideStr(std::wstring str)
{
    wprintf(L"%s", str.c_str());
}
```

And then call it from LUA like:
```lua
PrintWide("ąčęėįšųū")
PrintWideStr("ąčęėįšųū")
```

and it just fails with wrong userdata.

What are the solutions to add such support?

Thank you very much for such a great library, too. :)

**Comment by Nava2** [comment]
Would #140 be helpful?

**Comment by ThePhD** [comment]
#140 would be a one-person, one-time fix. I'm working on adding it in for everyone, albeit it's hard with codecvt and locales not always playing nice.

**Comment by ThePhD** [comment]
As a side note, `wstring` is not a Unicode string. You should be using `std::u16string` or `std::u32string` to handle localization. `wstring` is an implementation-defined string of `wchar_t` which can have any encoding that the implementation/locale sees fit.

**Comment by Murloc992** [comment]
Thanks for the sugestions. :) I might be too old-schooled at that. I will investigate both #140 and the strings for now. :)

**Comment by ThePhD** [comment]
Codecvt is a piece of shit: ![>:C](http://i.imgur.com/hEYD7HW.png)

**Comment by ThePhD** [comment]
Support is in now: https://github.com/ThePhD/sol2/releases/tag/v2.11.3

The code you wrote at first should work.

**Comment by Murloc992** [comment]
Awesome! It does work. :)
