### ISSUE TITLE
Usertype Inheritance Problem

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#177]
Consider the following code:

```
#include <iostream>
#include <sol.hpp>

struct A
{
    int a {32};
};

struct B : public A
{
    int b {33};
};

int main()
{
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.new_usertype<A>("A", "a", &A::a);
    lua.new_usertype<B>("B", "b", &B::b, sol::base_classes, sol::bases<A>());

    try { lua.script(R"RAW(

print("create object:")
b = B.new()

print("print member 'a':")
print(b.a)

print("print member 'b':")
print(b.b)

print("set member 'b':")
b.b = 10
print("ok")

print("set member 'a':")
b.a = 10
print("ok")

    )RAW"
    ); }
    catch (sol::error &e) { std::cerr << e.what() << std::endl; }

    return 0;
}
```

It compiles but doesn't work. Outputs:

```
create object:
print member 'a':
32
print member 'b':
33
set member 'b':
ok
set member 'a':
lua: error: [string "..."]:17: stack index -1, expected string, received number
```

System:

Arch Linux x86_64
g++ 6.1.1
lua 5.3.3
(using the latest revision of Sol2 as the time of writing)

**Comment by ThePhD** [comment]
Automatic inheritance is not fully documented or supported just yet because it's a work in progress and the performance is quite bad.

It is advisable that you instead place all member functions/variables -- including those of the base classes -- in each usertype declaration.

That being said, I'll try to fix this.

**Comment by jnbrq** [comment]
OK, thank you.

**Comment by ThePhD** [comment]
Fixed in latest, and documentation updated to clarify how much we don't support this:

http://sol2.readthedocs.io/en/latest/api/usertype.html#inheritance

**Comment by jnbrq** [comment]
Great! :+1:
