### ISSUE TITLE
Proper example of how to instantiate a `usertype` with no constructor generated

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#179]
I've been fighting with creating custom constructors by overriding the `new` static method with factory functions manually (needed for error checking). 

However, I can not grasp the syntax for this. The documentation states to use `"{name}", sol::no_constructor`, however its [different](https://github.com/ThePhD/sol2/blob/develop/test_usertypes.cpp#L985-L988) in `test_usertype.cpp`. 

Which is correct? The former *sometimes* will cause `make_shim` errors (I think it might be compiler dependent).

**Comment by ThePhD** [comment]
`"{name}"` is probably misleading: you can put an empty string there, `sol:;call_constructor`, `"warblegarblebuahaha"` even... really, it doesn't matter. If you specify any name + `sol::no_constructor`, Sol SHOULD not generate one. My suggestion is just `"new", sol::no_constructor` in the list.

If that doesn't work, let me know (error or unexpected behavior).

Meanwhile, need to figure out how to make the docs more clear...

**Comment by Nava2** [comment]
My intention is to override the `new` method to use my factory functions, so I think use passing `call_constructor` should be adequate?

Also, since I keep running into a lot of "compiler" errors (user spec errors..), I've noticed many are *very* missleading with what the cause is. I'm trying to figure out where to add `static_asserts` that could find common errors.

**Comment by ThePhD** [comment]
Oh. You're supposed to use `"new", sol::initializers( ... );`, and that will use factory functions. I need a tutorial for some of the usertype creation syntax, it seems, since it's not very clear...

Hell, that whole usertype page should probably be split up into sub-pages, so that people have an easier time with it and the examples. Anywho, [here's a cheesy example](https://github.com/ThePhD/sol2/blob/develop/test_usertypes.cpp#L604) from the tests. The class is at the top (sorry for making you scroll!).

**Comment by Nava2** [comment]
Are the `initializers()` method giving an unallocated reference? Thus why you needed to call `operator new()` syntax? I ask because part of my "factory" work is to verify if it was created properly, if it fails, I want to have it load a `nil` value into sol. I currently do that via a factory function that just returns a `shared_ptr` that is `null` if it was invalid.

**Comment by ThePhD** [comment]
Oh, so you want to control the memory with a `shared_ptr`. Well, then, in that case, you need to combine `"new", sol::no_constructor` and `"my_factory_function_name", &factory_function`, just like that.

**Comment by ThePhD** [comment]
Added documentation describing your use case specifically, albeit no "proper example: http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-constructor-options

**Comment by Nava2** [comment]
Would there be a way to just override the `"new"` method? I want to try to be as "lua-like" as possible -- **without** coupling sol code with the objects it's creating.

**Comment by Nava2** [comment]
So, I was asking these questions due to a problem with compiling my own code that was a typo. I now do: 

```c++
template <typename T, typename NewFn>
    inline sol::usertype<T>&& make_foo_ut(const NewFn& new_fn)
    {
        return std::move(sol::usertype<T>(
                                          "new", new_fn
                                          // other properties
                                ));
    }
// later
sol::usertype<foo_t> foo_ut(make_foo_ut<foo_t>(
        [](const sol::table& table) -> std::shared_ptr<foo_t> {
            return foo_t_details_::fromTable<foo_t>(table, vd);
        }));
    lua.set_usertype(foo_ut);
```

Which lets me do as I expected. The problem was the way that I was killing the constructor, instead of just overriding it.

**Comment by Nava2** [comment]
However, apparently this creates a "null" `usertype_detail::registrar` within the `metatableregister`.

**Comment by ThePhD** [comment]
Returning `sol::usertype<T>&&` is probably a mistake. You would just want to return the value, as right now you're returning a reference to what is technically a temporary and depending on how you use it, you will essentially create a dangling reference which will screw you all kinds of ways.

**Comment by ThePhD** [comment]
Backported: https://github.com/ThePhD/sol2/releases/tag/v2.11.3
