### ISSUE TITLE
sol must compile with c++17 without single/sol/sol.hpp ?

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#180]
Since I update the code, found compile fail, new code use such as std::in_place_tag, but my xcode config is compile with c++14.

**Comment by ThePhD** [comment]
Sol is currently providing the alternatives to `std::in_place_tag` in the code itself; it shouldn't be requiring it of you, and should be accessible with `sol::in_place` and friends. I might have messed up something, however... what do the clang error messages say?
