### ISSUE TITLE
compile with luajit 2.0.4 fail

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#184]
I compile a cpp file with luajit instead of lua, but failed.
My compile command is : **g++ test.cpp -Isolpath -std=c++14 -lluajit-5.1**

Here is the error stack:
```
Undefined symbols for architecture x86_64:
  "_luaL_setfuncs", referenced from:
      sol::stack::pusher<sol::usertype_metatable<B, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul>, char const (&) [5], A* (B::*)(), char const (&) [4], sol::overload_set<void (B::*)(A const*), void (B::*)(char const*)>, char const (&) [5], void (*)(), char const (&) [4], sol::constructor_list<sol::types<> >&, char const (&) [5], sol::destructor_wrapper<void> const&>, void>::push(lua_State*, sol::usertype_metatable<B, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul>, char const (&) [5], A* (B::*)(), char const (&) [4], sol::overload_set<void (B::*)(A const*), void (B::*)(char const*)>, char const (&) [5], void (*)(), char const (&) [4], sol::constructor_list<sol::types<> >&, char const (&) [5], sol::destructor_wrapper<void> const&>&&) in test-690367.o
  "_lua_absindex", referenced from:
      sol::stack_reference::stack_reference(lua_State*, int) in test-690367.o
  "_lua_compare", referenced from:
      sol::stack::get_call_syntax(lua_State*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in test-690367.o
  "_lua_getglobal", referenced from:
      void sol::stack::field_getter<char const*, true, false, void>::get<char const*&>(lua_State*, char const*&&&, int) in test-690367.o
  "_lua_pcallk", referenced from:
      sol::stack::script(lua_State*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in test-690367.o
  "_lua_setglobal", referenced from:
      void sol::stack::field_setter<char const*, true, false, void>::set<char const*&, sol::stack_reference&>(lua_State*, char const*&&&, sol::stack_reference&&&, int) in test-690367.o
      void sol::stack::field_setter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, true, false, void>::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, sol::usertype<B>&>(lua_State*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, sol::usertype<B>&&&, int) in test-690367.o
      void sol::stack::field_setter<char [2], true, false, void>::set<char const (&) [2], sol::function_arguments<sol::function_sig<>, void (&)(int)> >(lua_State*, char const (&&&) [2], sol::function_arguments<sol::function_sig<>, void (&)(int)>&&, int) in test-690367.o
  "_lua_tointegerx", referenced from:
      sol::stack::getter<int, void>::get(lua_State*, int, sol::stack::record&) in test-690367.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by aiplay** [comment]
I add macro define 
```
#ifndef LUAJIT_VERSION
#define LUAJIT_VERSION
```
And compile also fail, here is the error stack:
```
../sol/stack.hpp:209:50: error: use of undeclared identifier 'LUAJIT_MODE_ON'
                        luaJIT_setmode(L, -1, LUAJIT_MODE_WRAPCFUNC | LUAJIT_MODE_ON);
                                                                      ^
../sol/stack.hpp:218:26: error: use of undeclared identifier 'LUAJIT_MODE_WRAPCFUNC'
                        luaJIT_setmode(L, -1, LUAJIT_MODE_WRAPCFUNC | LUAJIT_MODE_OFF);
                                              ^
../sol/stack.hpp:218:50: error: use of undeclared identifier 'LUAJIT_MODE_OFF'
                        luaJIT_setmode(L, -1, LUAJIT_MODE_WRAPCFUNC | LUAJIT_MODE_OFF);
                                                                      ^
In file included from test.cpp:1:
In file included from ../sol.hpp:27:
In file included from ../sol/state.hpp:25:
../sol/state_view.hpp:167:32: error: use of undeclared identifier 'luaopen_bit'
                                        luaL_requiref(L, "bit32", luaopen_bit, 1);
                                                                  ^
../sol/state_view.hpp:195:30: error: use of undeclared identifier 'luaopen_ffi'
                                        luaL_requiref(L, "ffi", luaopen_ffi, 1);
                                                                ^
../sol/state_view.hpp:201:30: error: use of undeclared identifier 'luaopen_jit'; did you mean 'luaopen_io'?
                                        luaL_requiref(L, "jit", luaopen_jit, 1);
                                                                ^~~~~~~~~~~
                                                                luaopen_io
/usr/local/include/lualib.h:24:17: note: 'luaopen_io' declared here
LUAMOD_API int (luaopen_io) (lua_State *L);
                ^
In file included from test.cpp:1:
../sol.hpp:22:2: error: unterminated conditional directive
#ifndef SOL_HPP
 ^
8 errors generated.
```

**Comment by ThePhD** [comment]
What is `LUAJIT_VERSION` and why are you defining it....?

**Comment by aiplay** [comment]
I found the code in the compatibility/version.hpp
```
#ifdef LUAJIT_VERSION
#ifndef SOL_LUAJIT
#define SOL_LUAJIT
#endif // sol luajit
#endif // luajit
```

**Comment by ThePhD** [comment]
Okay. So what I'm gathering from your error messages is that you need to properly point yourself at the luajit include paths. LuaJIT defines LUAJIT_VERSION and all of those things: you're pointed at the solpath, and I'm GUESSING the Lua includes happen to just be sprinkled about somewhere, but you're missing the proper include directory that specifically points to LuaJIT stuff.

**Comment by ThePhD** [comment]
E.g.: `g++ -std=c++14 test.cpp -lluajit -I"path/to/luajit/include" -L"path/to/luajit/lib"`, where `"path/to/luajit"` needs to be replaced with whatever the path is to your luajit files and things. Unless, you're not actually giving me the whole command line?

**Comment by aiplay** [comment]
I make install the luajit from github, and luajit in the path /usr/local/bin/
but -lluajit tell me **ld: library not found for -lluajit**
my whole command line is : **g++ test.cpp -std=c++14 -I/Users/xujh/open/sol2 -lluajit**

**Comment by ThePhD** [comment]
Point yourself at the LuaJIT directory, you need a specific `-I/wherever/luajit/source/is/include`, or wherever the `lua.hpp` and `lua.h` files are.

**Comment by Nava2** [comment]
Likely, the normal lua headers are shadowing the luajit versions. If you have both installed, install them into separate places so they don't collide.

**Comment by aiplay** [comment]
You're right, I should sepatate lua and luajit;
Also, complie on the mac have to add link flags with **-pagezero_size 10000 -image_base 100000000** ??

**Comment by Nava2** [comment]
> You're right, I should sepatate lua and luajit;
> Also, complie on the mac have to add link flags with -pagezero_size 10000 -image_base 100000000 ??

I don't have to do this, I'm unsure why you'd need to. Any reason why it was needed? What Xcode version?

**Comment by aiplay** [comment]
Xcode version is 7.3.1 ， if I didn't add that link flags,  luaL_newstate() always return NULL.
And, luajit version is 2.1

**Comment by Nava2** [comment]
Hmm, I haven't run with luajit in awhile. Lua 5.1-5.3 work just fine for me, though. Sorry I'm not more help.

**Comment by addictgamer** [comment]
Just encountered the same issue, I was getting a small amount of errors (which meant it was finding _some_ LUA bindings, otherwise I would have gotten a plethora of errors) such as: `sol.hpp:15117: undefined reference to `lua_setglobal'`

The issue was that I have both LUA and LUAJIT installed (I'm running on Arch Linux for what it's worth), it was likely picking up lua.h from `/usr/include/lua.h` when luajit was in `/usr/include/luajit-2.0/`.
That's the nature of the FindLUAJIT CMake module I was running: When I forced it to look in `/usr/include/luajit-2.0/` via an environment hint (LUAJIT_DIR in my script), then everything started working because it picked up the right header to match the library I was linking against.
