### ISSUE TITLE
in_place_t missing without boost.

### ISSUE THREAD

**Issue by minirop** [ThePhD/sol2#185]
hello,
I just download the latest release (2.11.4) but it does not compile if you don't set SOL_USE_BOOST because in_place_t is missing.
I'm using g++-5.4.0

**Comment by ThePhD** [comment]
Not sure why this is happening. I rearranged a few things and pushed a 2.11.5... seems to work without boost now, across all compilers. Sorry about that! Try this: https://github.com/ThePhD/sol2/releases/tag/v2.11.5

**Comment by minirop** [comment]
It works!
