### ISSUE TITLE
Passing a C++ usertype as an argument to a Lua function

### ISSUE THREAD

**Issue by Grant1219** [ThePhD/sol2#187]
Maybe I'm just not understanding the documentation or don't understand Lua, but I cannot get the following script code working:
```lua
-- a test script

function my_function(entity)
    print("Hello there!")
    -- get_name returns a string
    print(entity:get_name())
end
```

I have registered my Entity class on the `sol::state` as follows:
```c++
lua.new_usertype<Entity>("Entity",
    "new", sol::no_constructor,
    "get_name", &Entity::GetName
);
```

The `sol::no_constructor` part is intentional because I don't want the Lua to ever create its own instance of the class, I will only be passing a std::shared_ptr<Entity> through to Lua as a function argument.

After I have loaded my script with `lua.script_file("data/scripts/test_script.lua");` I then grab the Lua function from it into C++ and try to call it.

```c++
auto ent = std::make_shared<Entity>();
sol::function my_func = lua["my_function"];

if (my_func)
    my_func(ent);
```

The first simple print statement outputs just fine, but then I get the following error:
`what():  lua: error: data/scripts/test_script.lua:5: attempt to index a userdata value (local 'entity')`

Is the issue that the `entity` doesn't exist in the scope, or am I not registering my Entity type correctly?
Thanks in advance. :smiley:

**Comment by ThePhD** [comment]
Thanks for reporting, subtle bug with how we treated unique_usertypes (shared_ptr, unique_ptr, etc.) and their reference properties when pushed. They're now properly forwarded.

Get the fix here: https://github.com/ThePhD/sol2/releases/tag/v2.11.6

**Comment by Grant1219** [comment]
Hey thanks for the fast fix, but unfortunately I am still having the same issue. :cry: 

Here is the full code I am using to produce the error:
```c++
#include <string>
#include <memory>

#include <sol2/sol.hpp>

class Entity {
    public:
        std::string GetName() {
            return "Charmander";
        }
};

int main(int argc, char** argv) {
    sol::state lua;
    lua.open_libraries(sol::lib::base, sol::lib::math, sol::lib::string, sol::lib::io);

    lua.new_usertype<Entity>("Entity",
        "new", sol::no_constructor,
        "get_name", &Entity::GetName
    );

    auto ent = std::make_shared<Entity>();
    //Entity ent;

    lua.script_file("test_script.lua");

    sol::function my_func = lua["my_func"];

    if (my_func)
        my_func(ent);

    return 0;
}
```

And the script:
```lua
-- test script

function my_func(entity)
    print("INSIDE LUA")
    print(entity:get_name())
end
```

If I comment out the `make_shared` line and uncomment `Entity ent;` line it works as expected.
Let me know if I can help you further debug this issue.

**Comment by ThePhD** [comment]
Oops, I had a derp. NOW it's there, proper: https://github.com/ThePhD/sol2/releases/tag/v2.11.6

**Comment by Grant1219** [comment]
You're awesome! Thanks again for the fix. :wink:
