### ISSUE TITLE
Coroutine Support

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#19]
Because someone's going to ask us for this eventually.

**Comment by ThePhD** [comment]
Implemented in https://github.com/ThePhD/sol2/commit/251e350539c914be8a1cee14535699fa23a82393 .

**Comment by Nava2** [comment]
In your commit messages, write `Closes #19` and it'll automatically close it when you merge the commit.

**Comment by nabijaczleweli** [comment]
PhD sucks at software
