### ISSUE TITLE
Return from require_file is not table (nil)

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#193]
I can't seem to create a working version that causes this bug. 

For some reason, this section:
```C++
// state_view.hpp:54
optional<object> is_loaded_package(const std::string& key) {
			auto loaded = reg.traverse_get<optional<object>>("_LOADED", key); // nil if the file isn't loaded
			bool is53mod = loaded && !(loaded->is<bool>() && !loaded->as<bool>());
			if (is53mod) // <- always true
				return loaded;
```

This returns an `object` that stores `nil`. Regardless if the module has been previously loaded. 

Later, 

```C++
// stack_view.hpp: 95
template <typename Fx>
		object require_core(const std::string& key, Fx&& action, bool create_global = true) {
			optional<object> loaded = is_loaded_package(key);
			if (loaded) // should this be: if (loaded && loaded->valid())
				return std::move(*loaded);
			action();
			auto sr = stack::get<stack_reference>(L);
			if (create_global)
				set(key, sr);
			ensure_package(key, sr);
			return stack::pop<object>(L);
		}
```

This returned nil value (which is a valid `optional`) has the `nil` value moved into the result. Thus giving a bad value. 

Seems like line 98 should check if the result is a valid value not just that it's present.

**Comment by ThePhD** [comment]
This might be a consequence of me changing some `stack_check` things and making it so `object` can point at something that contains `nil` without exactly checking... let me look over the code after I deal with another bug.

**Comment by Nava2** [comment]
That's exactly the cause, my suggested fix worked so I opened a PR.

**Comment by Nava2** [comment]
Oddly, now if the "required" file does not compile, I get a segfault:

```C++
// proxy.hpp
bool valid() const {
			stack::push_pop(tbl);
			auto p = stack::probe_get_field<std::is_same<meta::unqualified_t<Table>, global_table>::value>(tbl.lua_state(), key, lua_gettop(tbl.lua_state())); // here
			lua_pop(tbl.lua_state(), p.levels);
			return p;
		}
```

Which means, the invalid code is passing: 

```C++
// stack.hpp:199
		inline void script_file(lua_State* L, const std::string& filename) {
			if (luaL_dofile(L, filename.c_str())) {
				lua_error(L);
			}
		}
```

The *reason* the code is invalid is because it returns a `userdata` from the module (which doesn't appear to be valid). Perhaps this is a lua issue then? sol tries to set `"_LOADED"` on the module result which in not a `table`.

**Comment by ThePhD** [comment]
This is probably an error, but I cannot be exactly sure. In order to use the `require` functionality, one has to generally open `sol::lib::require` first. If you're not doing that then the `_LOADED` table and such might not exist in the registry or within the globals. Are you opening the `require` lib with `sol::state::open_libraries( sol::lib::require )` ?
