### ISSUE TITLE
Binding functions containing references to `std::vector<T>`

### ISSUE THREAD

**Issue by jnbrq** [ThePhD/sol2#196]
Consider the following code:

```
#include <vector>
#include <sol.hpp>

int main(int argc, char **argv)
{
	typedef std::vector<double> V;
	sol::state lua;
	lua.new_usertype<V>(
		"Test",
		sol::constructors<
			sol::types<>,
			sol::types<std::size_t>,
			sol::types<const V&>
		>()
	);
	// lua["test_01"] = [](V &v) {}; // does not compile
	lua["test_02"] = [](V *v) {}; // compiles
	return 0;
}
````

When I try to register functions having references to `std::vector<double>` , it does not compile. The same thing also happens when trying to register them as member functions. No problem with constructors with references.

Happens on both Windows and Arch Linux.

for arch linux:
gcc version 6.1.1 20160802 (GCC)
lua 5.3.3

on Windows using MSYS2

This issue happens with the current version of single header version of the library.

With some previous version, it didn't happen. I do not remember the version of that revision, so I upload the header to ubuntu pastebin:

[Ubuntu pastebin link](http://paste.ubuntu.com/23081218/)

**Comment by ThePhD** [comment]
This is a known regression (known as of a little bit ago, but known).

It was the primary problem with serializing vector -> table upon push, and allowing deserializing from a table as well. I bit the bullet and added it, but now I'm in... well, this conundrum!

I'm going to have to put a fair amount of work in to make this behave proper.

**Comment by ThePhD** [comment]
Better handled now, try the latest: https://github.com/ThePhD/sol2/releases/tag/v2.12.0

**Comment by jnbrq** [comment]
Thank you :+1:

**Comment by Nava2** [comment]
Not sure if it was considered, but sol fails to properly bind `std::set`.

**Comment by ThePhD** [comment]
Yeah, `std::set` was ignored because it's a speshul snowflake. I feel like I'd have to write an explicit overload just for it.

**Comment by ThePhD** [comment]
Particularly: how do you make a table or a table-alike for `std::set`? It only contains keys, not values, so the table structure of Lua does not fit its mental model. Furthermore, even if we DID try to force it to work (assuming we banned the syntax `mytable["key"] = value;` from being legal), what does `local val = mytable["key"];` return? `true` if it exists, `false` if it doesn't? That's... really not a useful thing to have, honestly.

**Comment by ThePhD** [comment]
Backported because WHY NOT

[¯\_(ツ)_/¯](https://github.com/ThePhD/sol2/releases/tag/v2.12.1)

**Comment by nabijaczleweli** [comment]
`set<T>` is m`ap<T, T>` so no

**Comment by Nava2** [comment]
You're right about the semantics. They don't make sense logically, so that's my mistake. It's odd that it worked before but not after the container changes. 

Perhaps having a specialization that just static asserts out as a failure would make more sense?

**Comment by ThePhD** [comment]
It's working now, it just has it so that the following fails with an error in Lua: `myset["bark"] = 24; -- errors out`

**Comment by Nava2** [comment]
Oh, that's even better. Logically, `set` and `unordered_set` make sense to go from stl -> lua, but not the other way around. But the implications are annoying. 

Thanks for supporting my 2AM sleep-deprived musings. :+1:

**Comment by Nava2** [comment]
`std::set` doesn't work with `sol::property()`. Was this intentional? I'm okay with not allowing `set`s to be read from `Lua`.

**Comment by Nava2** [comment]
Strangely, this works: 

```
, "bars", sol::property([](Foo& f) -> std::unordered_map<std::string, std::shared_ptr<Bar>> 
            {
                return f.bars();
            })
```

This fails:

```
, "bars", sol::property(&Foo::bars)
```

**Comment by ThePhD** [comment]
No repro on VC++. I need compiler information, build environment, etc... Guessing `linux` and `g++` from the vagrant error.

Also, you may want to open a new issue for this.
