### ISSUE TITLE
Compile fail with sol 2.12.1 on the android platform

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#199]
When I update the sol, I found my project can not compile success.
usertype_metatable.hpp use the std::to_string, but ndk can't found to_string in the std,
and some other problem so on ...

**Comment by ThePhD** [comment]
I don't have the NDK handy, so I can't reproduce this problem. I looked for instances of `std::to_string and removed them.

Is there anything else that appears in the errors? Having a snippet of those will help me help you.

**Comment by aiplay** [comment]
Yes，there is some other error:
usertype_metatable.hpp:110:85: error: invalid use of 'auto'
usertype_metatable.hpp:110:85: error: use of 'decltype(auto) sol::detail::deref(T&&) [with T = irr::gui::IGUIEnvironment&]' before deduction of 'auto'
       return stack::push(L, (detail::ptr(l) == detail::ptr(r)) || op(detail::deref(l), detail::deref(r)));

**Comment by ThePhD** [comment]
Try 2.12.2: https://github.com/ThePhD/sol2/releases/tag/v2.12.2
