### ISSUE TITLE
Build issue with clang++ and g++

### ISSUE THREAD

**Issue by hdt80** [ThePhD/sol2#20]
I'm using Lua 5.3.2

clang++ --version outputs:
```
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
```
g++ --version outputs: 
g++ (GCC) 5.3.0
```

I'm getting the following errors when building with g++: http://termbin.com/c4e7
With clang++: http://termbin.com/dqoz

I don't know where to begin deciphering those error messages so I was hoping I could have some help in fixing this issue. If I should provide more information let me know and I'll get that to you as soon as I can.

**Comment by ThePhD** [comment]
You need to build with `-std=c++14` in the command line.
