### ISSUE TITLE
set_function static function

### ISSUE THREAD

**Issue by F4r3n** [ThePhD/sol2#201]
Hi,
When I bind a static function with "set_function" nothing happens, my function is never called.
`lua.set_function("keyIsPressed", Input::keyIsPressed);`

`bool Input::keyIsPressed(int key) {
	return InputManager::getInstance().keyIsPressed(key);
}`

**Comment by ThePhD** [comment]
Do you call the function in Lua code? Binding only makes the function available in a Lua script, and as far as I can tell (if it's not error-ing out) then everything is binding properly.

**Comment by F4r3n** [comment]
Yes i call the function in lua code

**Comment by ThePhD** [comment]
I cannot reproduce the trouble you're having: some example code. You'll need to tell me if you get an error, if something specific happens, etc...

Are you naming the function correctly? Sometimes a simple typo can make these things hard to pin down.

![It works?](http://i.imgur.com/CWf7UTj.png)

**Comment by F4r3n** [comment]
I managed to make it works, it was my mistake, thanks.
