### ISSUE TITLE
Reduce algorithmic complexity of template instantiations

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#202]
Yet again, people are annoyed at the (exponential?) amount of code generated from templates. While we addressed this in small ways once (with `simple_usertype`), we did not vet the entire implementation to its fullest.

Some steps we could take to improve performance and cut down on template instantiations:

- [ ] Evaluate which templates have extraneous information in their signatures (this will fold instantiations down)
- [ ] Look for uses of recursion that we can hack down into dumber `swallow`/'fold' expressions (until next year or the year after where we can formally declare ourselves a C++17 implementation and tell everyone to upgrade so we can use real fold expressions and eliminate half of the crusty recursive implementations we use for ordering guarantees)
- [x] Aside: figure out `this` pointer storage/propagation so we can avoid lookup cost to member variables when both member functions / member variables are used in the same usertype binding

**Comment by Nava2** [comment]
Thanks for looking into this.

Is there a reason you don't want to push the version to C++14? Aren't the big 3 already there? Just branch the library and maybe backport bugs? Clang 3.4+, GCC 5+ and MSVC 14 support C++14.

**Comment by ThePhD** [comment]
VC++ does not have it and I am unsure if VSNext will have it. Since VC++ is basically the bottom of the barrel, I will have to commit to keeping it VS 2015 compatible for a while, unless VSNext brings such good features that I am okay with dumping 2015 users.

**Comment by Nava2** [comment]
Looks like relaxed `constexpr` is the only thing missing: http://en.cppreference.com/w/cpp/compiler_support.

**Comment by ThePhD** [comment]
Fold Expressions is red and not in the VS 15 Preview 4.

**Comment by Nava2** [comment]
Oh, your initial post has C++14 when it should say C++17, sorry for the confusion. :+1:

**Comment by ThePhD** [comment]
So I just found out for bullet 3, that the speed difference I was seeing between Sol and OOLua was because I wasn't actually measuring anything with OOLua. Again.

OOLua doesn't support member variable syntax `obj.a = 24`. But the code produces no errors when you do that. So it just kind of silently allowed you to write that, expect the side-effect happened, but it never really changed the value on the userdata itself.

Meaning, sol2 has almost no competition in speed with regards to that syntax. It can only get faster by literally being stripped down to hand-written, per-variable member checks. Hoo... rah?

**Comment by Nava2** [comment]
Doesn't that also imply that it could be considered for the trade-off for binary size vs speed? While *still* being significantly faster?

**Comment by ThePhD** [comment]
Hold on, there. We're not THAT much faster than everyone else:

![SWIG still on our tail](https://raw.githubusercontent.com/ThePhD/lua-bench/master/lua%20-%20results/lua%20bench%20graph%20-%20member%20variable.png)

We still have some work to do to catch up to the plain C API, albeit SWIG is far, far behind.

**Comment by Nava2** [comment]
Isn't the benchmark to get to be equally as fast as the c-api? I'm confused how one could beat it. 

Are the errorbars 1 stdev? If so, sol2 is significantly ahead of SWIG.

**Comment by ThePhD** [comment]
I still have to benchmark it, but v 2.14.0 is going to have simple_usertypes which can do everything. I think the implementation is about as fast as I can have it be, while still hiding things behind compile-time barriers: https://github.com/ThePhD/sol2/releases/tag/v2.14.0

As I said, gotta benchmark simple usertypes to see how it shakes out, though.

**Comment by ThePhD** [comment]
Benchmarks are in, and oh boy did I optimize the crap out of `simple_usertype`. These graphs compare the regular implementations of everything for member functions / member variables vs. sol's simple_usertype:

![Dayum](https://raw.githubusercontent.com/ThePhD/lua-bench/master/lua%20-%20results/lua%20bench%20graph%20-%20member%20variable%20(simple).png)

![Dayum](https://github.com/ThePhD/lua-bench/blob/master/lua%20-%20results/lua%20bench%20graph%20-%20member%20function%20calls%20(simple).png)

These results are pretty goddamn great. It's obviously not EXACTLY as fast as `usertype` but this gets a pretty nifty close second, and we've enabled it so that `simple_usertype` supports almost every `usertype` does natively.

I'm going to close this and say that if people have compile-time issues, they should just switch to `simple_usertype`.

**Comment by OrfeasZ** [comment]
That's awesome! Can you please take a look at [this](https://github.com/ThePhD/lua-bench/issues/10) issues on the `lua-bench` repo? I've been trying to do some benchmarks of my own but I've been having issues getting my environment setup to be similar to yours.
