### ISSUE TITLE
Usertypes with many members become too complex for the compiler

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#203]
I'm experiencing this issue under MSVC140 (Update 3) on the 64-bit toolchain.

I have a usertype which has 147 property members (`sol::property`), a call constructor, and two base classes, and during compilation I'm getting the following errors:

```
2>I:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(1016): fatal error C1202: recursive type or function dependency context too complex (compiling source file CustomUsertypeClass.cpp)
2>  I:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(1035): note: see reference to class template instantiation 'std::_Choose_conjunction<true,_Lhs,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<sol::property_wrapper<bool (__cdecl CustomUsertypeClass::* )(void) const,void (__cdecl CustomUsertypeClass::* )(bool)>,_Ty>,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[30],const char (&)[30]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[16],const char (&)[16]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[15],const char (&)[15]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[20],const char (&)[20]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[34],const char (&)[34]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[28],const char (&)[28]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[32],const char (&)[32]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[18],const char (&)[18]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[23],const char (&)[23]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[24],const char (&)[24]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty,_Ty>,std::is_constructible<const char (...
```

This could be associated to #202 but since it's an actual issue I'm posted it here for reference.

**Comment by OrfeasZ** [comment]
Same thing happens with a `create_named_table(...)` call with 130+ keys.

**Comment by ThePhD** [comment]
I would say "if you're not using variables, just use `new_simple_usertype` instead", but since you're using properties I'm assuming you want dot syntax and variable-like syntax in Lua (e.g., `obj.a = 24`). So far, I have not figured out a way to do this; therefore, the complicated table registration remains.

In the old world, we used to put members into a `std::unordered_map` and type-erased the functions with `sol::detail::base_function`. This cost us both space and time and is what made our implementation much slower than the others in the old days (when competing against the best libraries like OOLua in this regard).

**Comment by ThePhD** [comment]
The only way to fix this is to properly handle #202, or to perhaps address the third bullet.

At the moment, I would recommend splitting things up or forcing yourself to get comfy with the function-only syntax `new_simple_usertype` requires.

**Comment by ThePhD** [comment]
As for the table bits, well, that's probably part of #202 as well. I'll make a note of it there too. As a side note, we already use the `swallow` trick and do not process things sequentially. clang++ has an intrinsic to unpack parameters linearly and perform something, but neither g++ nor VC++ has such an intrinsic, so there's really not much more efficiency I can put into the system. It's being processed 1 by 1.

**Comment by OrfeasZ** [comment]
The reason I'm using `sol::property` and not turning everything into a function is because of backward compatibility with when I was still using luabind. You recommended splitting things up, but how would I do that for a usertype and/or a table?

**Comment by ThePhD** [comment]
That's the right workaround for tables, yes. For usertypes, you'd have to hand-roll a `__index` function, stick a `std::unordered_map` in there, put all the (`string`? Or perhaps your version of a `variant` if you need more than one key type too) keys in there, and then map them to the right member functions.

I might make `simple_usertype` do something like that, but there's no `std::variant` type in C++14, so I'd have to try two things. First, is upgrade the library to C++17 and force usage of `std::variant`, which is appearing in all recent iterations of all compilers (including VS "15" coming soon). This is a bad idea and something I won't be doing, so that leaves option 2: use a `std::string` key, convert all of the typical keys into that (with some form of canonical representation for things like `sol::no_constructor`), and then perform a runtime lookup and dispatch to a type-erased `std::function<int(lua_State*)>` or similar.

This is actually similar to the old style of preserving classes was done. We were again not too fast there and paid for it in member function calls and other benchmarked tests. I'm loathe to make this kind of change, since after correctness speed _is_ a very important goal for Sol.

**Comment by OrfeasZ** [comment]
If I were to introduce my own `__index` meta function, would I still be able to use things like `sol::call_constructor` and so on, or would those get "overridden" too? I realize that doing so isn't a real solution, so even though I might do so temporarily I will be looking for other alternatives in the meantime.

On Wed, Aug 31, 2016 at 8:57 AM, The Phantom Derpstorm < notifications@github.com [notifications@github.com] > wrote:
That's the right workaround for tables, yes. For usertypes, you'd have to hand-roll a __index function, stick a std::unordered_map in there, put all the ( string ? Or perhaps your version of a variant if you need more than one key type too) keys in there, and then map them to the right member functions.

I might make simple_usertype do something like that, but there's no std::variant type in C++14, so I'd have to try two things. First, is upgrade the library to C++17 and force usage of std::variant , which is appearing in all recent iterations of all compilers (including VS "15" coming soon). This is a bad idea and something I won't be doing, so that leaves option 2: use a std::string key, convert all of the typical keys into that (with some form of canonical representation for things like sol::no_constructor ), and then perform a runtime lookup and dispatch to a type-erased std::function<int(lua_State*)> or similar.

This is actually similar to the old style of preserving classes was done. We were again not too fast there and paid for it in member function calls and other benchmarked tests. I'm loathe to make this kind of change, since after correctness speed is a very important goal for Sol.

**Comment by ThePhD** [comment]
No, they should not get overridden. Below is a complete example with explanatory comments:

````cpp
#define SOL_CHECK_ARGUMENTS
#include <sol.hpp>
#include <iostream>
#include <unordered_map>

struct custom {
};

sol::object custom_indexing(custom& obj, sol::stack_object key, sol::this_state s) {
	// this version of the function is for get-style of things
	// e.g., print(obj.key)
	static std::unordered_map<std::string, int> mapping;
	// initialize mapping statically or however you want to do it
	// you can retrieve the `lua_State*` to do manual operations from sol::this_state
	// you can check to see if `key` is a string, and if it is then try to lookup the property / function
	// and call it on / use it with the object

	// In the case of functions, you must return the function to be called
	// In the case of variables, you must return the variable value directly

	// You can also handle it some other way too
	return sol::object(s, sol::in_place, 24);
}

void custom_new_indexing(custom& obj, sol::stack_object key, sol::stack_object value, sol::this_state s) {
	// this version of the function is for set-style of things
	// e.g., obj.key = value
}

int main() {

	sol::state lua;
	lua.open_libraries();

	lua.new_usertype<custom>("custom",
		sol::call_constructor, sol::constructors<sol::types<>>(),
		"bark", [](custom&) { std::cout << "BARK" << std::endl; },
		sol::meta_function::index, custom_indexing,
		sol::meta_function::new_index, custom_new_indexing
	);

	lua.script(R"(
c = custom()
c:bark() -- will not call index, key is present already
c.woof = 100
print(c.woof)
)");

	return 0;
}
````

**Comment by ThePhD** [comment]
Apologies it took me so long, but I didn't like how using a custom __index method was the only solution to this problem.

I refactored simple_usertype. I think you will find that it won't choke on 190, 250, 400 properties. It also (tentatively) supports automatic inheritance and other things. Give it a try: https://github.com/ThePhD/sol2/releases/tag/v2.14.0

**Comment by ThePhD** [comment]
Docs have been updated to to reflect that this isn't a problem anymore: http://sol2.readthedocs.io/en/latest/api/simple_usertype.html

**Comment by ThePhD** [comment]
I'm gonna say this is more or less solved, since using `simple_usertype` should work for you now and its performance is acceptable: https://github.com/ThePhD/sol2/issues/202#issuecomment-246767629

**Comment by OrfeasZ** [comment]
Small typo in the documentation (`autoamtically`). I'll be taking a look at simple_usertype and evaluating its performance (and complexity) for my use cases. I'm currently using the following for my usertype definitions: `sol::call_constructor`, `sol::no_constructor`, `sol::property`, and `sol::base_classes`. Will all these work with `sol::simple_usertype`?

**Comment by ThePhD** [comment]
They will, yes.

**Comment by OrfeasZ** [comment]
Great. Please take a look at [this](https://github.com/ThePhD/lua-bench/issues/10) when you get a chance.

**Comment by ThePhD** [comment]
I've fixed it. If something comes up while you use `simple_usertype`s, just let me know in an issue and I'll get on it. Though, it might take a while: I've got a LOT of school to do...

**Comment by OrfeasZ** [comment]
You and me both... I'll most likely take a look later today and see if anything comes up. Thanks for all your awesome work!

**Comment by OrfeasZ** [comment]
It seems that the compiler still chokes with `simple_usertype` with many members. I'm using the `state.new_simple_usertype<T>("T", ...)` syntax, and it produces the following errors:

```
1>I:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(1016): fatal error C1202: recursive type or function dependency context too complex (compiling source file SomeFile.cpp)
1>  I:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(1035): note: see reference to class template instantiation 'std::_Choose_conjunction<true,_Lhs,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[30],const char (&)[30]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[16],const char (&)[16]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[15],const char (&)[15]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[20],const char (&)[20]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[34],const char (&)[34]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[28],const char (&)[28]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[32],const char (&)[32]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[18],const char (&)[18]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[23],const char (&)[23]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[24],const char (&)[24]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[23],const char (&)[23]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[30],const char (&)[30]>,std::is...
1>  I:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits(1016): note: see reference to class template instantiation 'std::_Conjunction<std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[27],const char (&)[27]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[30],const char (&)[30]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[16],const char (&)[16]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[15],const char (&)[15]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[20],const char (&)[20]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[34],const char (&)[34]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[28],const char (&)[28]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[32],const char (&)[32]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[18],const char (&)[18]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[23],const char (&)[23]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[21],const char (&)[21]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[24],const char (&)[24]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[26],const char (&)[26]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[25],const char (&)[25]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[23],const char (&)[23]>,std::is_constructible<_Ty &&,_Ty>,std::is_constructible<const char (&)[30],const char...
```

**Comment by OrfeasZ** [comment]
Maybe you could introduce a custom interface for adding members to simple_usertypes on runtime? Something like:

```cpp
sol::usertype<SomeType> myUsertype(
        ...
);

myUsertype.define("someMember", sol::property(&SomeType::A, &SomeType::B));
```

**Comment by jkbz64** [comment]
You can write directly to the table ```luaState["SomeType"]["someMember"] = ... ```

**Comment by ThePhD** [comment]
I still have to test this for when there's member variables involved (e.g., when indexing is forced), but doing `sol::table mt = lua["SomeType"];` and then modifying the table might be the fix for you here. Gotta test...

**Comment by OrfeasZ** [comment]
I have written my own fork which allows me to define members for a simple_usertype manually and one-at-a-time, before registering the usertype. You can find my code [here](https://github.com/OrfeasZ/sol2/commit/95ddf46b55d2314133e1ba5421210f925838810a) (if you want, I can also PR).

It works like this:
```cpp
sol::simple_usertype<SomeType> utype = lua.create_simple_usertype<SomeType>(
    ...
);

utype.add("hello", sol::property(&SomeType::GetHello, &SomeType::SetHello));
utype.add("world", &SomeType::world);
...

lua.set_usertype("SomeType", utype);
```

**Comment by ThePhD** [comment]
I'd probably change it to something like `set` instead of `add`, to be a tad more consistent (e.g., it will overwrite (or at least, it should), not append, if two keys collide).

Otherwise, that looks fine. Coupled with my recent changes to allow for runtime modification of a `simple_usertype` table, this probably covers all bases...

**Comment by OrfeasZ** [comment]
It currently doesn't replace, it only appends (if it doesn't already exist) since it's using the already existing underlying implementation of `simple_usertype_metatable::add`. Do you want me to PR it regardless in order to save you some time?

**Comment by ThePhD** [comment]
Sure, I can integrate it and fix it up.
