### ISSUE TITLE
stl container bindings fail to resolve as a function call

### ISSUE THREAD

**Issue by Nava2** [ThePhD/sol2#204]
cf76f6baa broke bindings and function resolution with `unordered_map`: 

```C++
        struct foo_t {};
        lua.new_usertype<foo_t>("foo", "new", [](const std::unordered_map<std::string, uint64_t>&) 
        {
            std::cout << "Worked!" << std::endl;
        });

        lua.script("foo.new({})");
```

Output: 

```FAILED:
due to unexpected exception with message:
  lua: error: [string "foo.new({})"]:1: sol: no matching function call takes
  this number of arguments and the specified types
```

I can't repo the issue I had in #196.

**Comment by ThePhD** [comment]
This is unfortunately a `by-design` issue: when I "fixed" the way STL containers bound, I "fixed" them by treating them -- essentially -- like usertypes. I just give them an extremely specific metatable that supports many of the basic table operations.

Thusly, when you do `{}` with a new usertype, it tries to get a usertype out of `{}`, which is just a table. This fails.

I wanted to do a check in the getter to basically do "table serialization" into the C++ type if it's a table, or non-table serialization if it's a usertype, but this presents a unique problem.

If the source from Lua is a Table, you need to create a new value, e.g.: `std::unordered_map<std::string, int>`. If it's a usertype, it's a _waste_ to do this, so the desired signature is: `std::unoredered_map<std::string, int>&`. The detection of a table vs. a userdata is a runtime decision: this is a compile-time decision. Either I lose table compat (the choice I made now) by returning a reference and letting people affect the data directly if it's a userdata type. OR,, I make everyone make copies all the time (wasteful) and always return a value, which works for both tables and container-userdata types.

I can perhaps try to sense when someone asks for the reference version versus the value version, but... well, that's a huge refactor.

**Comment by Nava2** [comment]
So, as a work around, could I use optional instead and just handle the nullopt case in c++ land? 

Also, this problem presents with multiparameter functions as well. If that changes anything.

**Comment by ThePhD** [comment]
`optional` would work, yes.

I don't know what you mean by "multiparameter functions", though.

**Comment by Nava2** [comment]
Sorry, missed this earlier, I meant for example `foo.new(1, {})`.

**Comment by ThePhD** [comment]
I'm unfortunately going to have to say that this is by-design for now... I can't really support `{}` to work juust yet, not until a huge refactor that detects the "original reference-ness" of all calls made to `stack::getter<T>`.

**Comment by Nava2** [comment]
That's reasonable! Thanks.
