### ISSUE TITLE
static luajit link failed

### ISSUE THREAD

**Issue by 11nk** [ThePhD/sol2#208]
with a error  _luaL_loadbufferx symbol redefined .
i am use msvc 2015 update3 
luajit version is 2.1 beta2 with build command msvcbuild.bat static

**Comment by 11nk** [comment]
I found some compatible code for old version lua in sol.hpp
```cpp
inline int luaL_loadbufferx(lua_State* L, const char* buff, size_t size, const char* name, const char*) {
    kepler_lua_compat_get_string_view ls;
    ls.s = buff;
    ls.size = size;
    return lua_load(L, kepler_lua_compat_get_string, &ls, name/*, mode*/);
}
```
But this function has already defined in lj_load.c file at 137 lines .

**Comment by ThePhD** [comment]
Well, I added some guards to prevent this from happening, so you should be all set.

Get it here: https://github.com/ThePhD/sol2/releases/tag/v2.12.3

**Comment by 11nk** [comment]
thanks.
