### ISSUE TITLE
Question: Sol2 support for "namespaces"?

### ISSUE THREAD

**Issue by demianmnave** [ThePhD/sol2#210]
I'm currently using Lua-Intf for bindings, but am seriously considering a switch to Sol2 just because of the overload support.

One of the main features I use from Lua-Intf is the "module" to group objects into Lua-side "namespaces" (e.g. std::experimental::optional -> std.experimental.optional).  A custom __index metamethod would probably work, but it seems to me that Sol2 must have a better way that isn't readily apparent to me from the docs or the issue tracker.

An explanation and/or example of how to do this in Sol2 would be much appreciated.

**Comment by ThePhD** [comment]
It's something I have to add to the docs in more explicit detail. But it's implied that you can do this because, as is shown by the docs, `sol::table` can do all the `new_usertype` and blah blah blah stuff that `sol::state` can do. Which means...

````
sol::state lua;
sol::table bark = lua.create_named_table("bark");
bark.new_usertype<my_class>( "my_class", ... ); // the usual

lua.script("obj = bark.my_class.new()" ); // this works
my_class& obj = lua["obj"]; // now exists
````

This extends to any operation that can be performed on `sol::table` (i.e., literally everything, including `new_enum`).

Have fun!

**Comment by ThePhD** [comment]
To address this, a new sample has been added: https://github.com/ThePhD/sol2/blob/develop/examples/namespacing.cpp

There's also a quick and dirty for namespaces in the "quick 'n' dirty" tutorials now: http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#namespacing

**Comment by demianmnave** [comment]
Those are the dots I couldn't connect, thanks.  This seals the deal, I'll be moving our code over to Sol2, which will definitely be fun.

Keep up the good work!

**Comment by ThePhD** [comment]
Let me know how it goes, @demianmnave ! Feel free to stop by issue #189 and tell me how it went when you're done, and on things I can improve.

**Comment by demianmnave** [comment]
Will do!
