### ISSUE TITLE
Setting extra data on a C++ user type from LUA?

### ISSUE THREAD

**Issue by paulsapps** [ThePhD/sol2#211]
LUA:

```
local mydata = {}
mydata.Test1 =
{
    key= 'value'
}

function init(self)
    print("init")
    self:Stuff()
    -- How can I make this work? In my "real" code I want to do self.test = some_big_table
    -- that I inited above update(self)
    self.test =mydata 
    print(self.test.key)
end

```

C++

```

static void Log(const char* s) { printf("%s\n", s); }

class MyThing
{
public:
   void Stuff() { Log("stuff"); }
    void Init()
   {
        mLuaState.set_function("print", Log);
        mLuaState.new_usertype<MyThing>("MyThing","Stuff", &MyThing::Stuff);
        mLuaState["init"](this);
    }
private:
   sol::state mLuaState;
};

void Test()
{
 MyThing t;
 t.Init();
}

```

Is there a way to set "extra" data on MyThing when its passed to lua as a user type? In update I want to set some dynamic properties on self. My use case for this is that I generate a large FSM table in lua, then I want set this table on my C++ via some init function.

Edit: I'm very new to LUA so this might be completely insane and make no sense :)

**Comment by ThePhD** [comment]
Add a `sol::table test` member to your class, bind it. You then have a table that can be set, get and also accessed in Lua code.

**Comment by paulsapps** [comment]
```
class MyThing
{
public:
    void Stuff() { }
    void Init()
    {
        mLuaState.new_usertype<MyThing>(
            "MyThing", 
                "Stuff", &MyThing::Stuff,
                "states", &MyThing::mStates
            );

        mLuaState.script(R"(
function init(self)
    self.states = {}

    self.states.StandingTurn = 
    {
        animation = 'dggfdgd'
    }

    --self.states.Active = states.Stand
    --self:SetAnimation(self.states.Active.animation)

    print("test")
end
)");

        mLuaState["init"](this);
    }
private:
    sol::state mLuaState;
    sol::table mStates;
};

void Test()
{
    MyThing t;
    t.Init();
}
```

Seems to crash burn?

**Comment by jkbz64** [comment]
You didn't include lua base libraries which have print function, so that's why it throws exception. And I think it should be also ```self.states["StandingTurn"] = { animation = 'dggfdgd' } ``` not ```self.states.StandingTurn```

**Comment by paulsapps** [comment]
Argh - thanks that was it! The real script is here: https://github.com/paulsapps/alive/blob/dev/data/scripts/abe.lua

I'm confused as to why `self.states.StandingTurn` would be wrong though? I thought that `self.states.StandingTurn` and `self.states["StandingTurn"]` are the same thing no?

**Comment by jkbz64** [comment]
It seems that they are the same thing, sorry for misleading. :cry:

**Comment by ThePhD** [comment]
:+1: Thanks for helping him get it. I appreciate it.
