### ISSUE TITLE
Can't register inherited to classes

### ISSUE THREAD

**Issue by jkbz64** [ThePhD/sol2#213]
There's problem with registering pure abstract classes using the newest version of sol, when using older version(from week ago, I believe) everything compiles fine.
Code to reproduce:
````
class A
{
public:
    virtual void a() = 0;
};

class B : public A
{
public:
    virtual void a() override { }
};

int main()
{
    sol::state state;
    state.new_usertype<A>("A", "a", &A::a);
    state.new_usertype<B>("B", sol::base_classes, sol::bases<A>());
}
```
The compiler throws out ```invalid abstract return type ‘A', blah blah blah, because the following virtual functions are pure within 'A'```

I have also found out another issue but i can't reproduce with newest version of sol until this gets fixed. Will create new.

**Comment by ThePhD** [comment]
The semantics of `std::optional` are stupid and they should not have changed the `boost::optional` interface.

Regardless, this is fixed now and you should be just fine. Get it here: https://github.com/ThePhD/sol2/releases/tag/v2.12.4
