### ISSUE TITLE
Small performance issue with simple_usertype.

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#216]
There's a small performance issue I noticed with `sol::simple_usertype`. You are using `std::map` for storing variables and functions and performing lookups, which even though works fine for a small number of elements, it starts degrading performance when it comes to larger usertypes, making it slightly slower than old sol.

Changing [these](https://github.com/ThePhD/sol2/blob/develop/sol/simple_usertype_metatable.hpp#L56) [two](https://github.com/ThePhD/sol2/blob/develop/sol/simple_usertype_metatable.hpp#L57) typedefs to use `std::unordered_map` instead provides a significant performance increase (as illustrated below). There are no benefits to using the ordered `std::map` implementation in this case anyway, so `std::unordered_map` would be the better choice.

With `std::map` and 4 member variables:
![](http://i.nofate.me/aSmKOEfvTZ.png)

With `std::unordered_map` and 4 member variables:
![](http://i.nofate.me/6JmTUhu3VG.png)

With `std::map` and 50 member variables:
![](http://i.nofate.me/d1hsWB3T2F.png)

With `std::unordered_map` and 50 member variables:
![](http://i.nofate.me/BbtBGy340m.png)

Please ignore the `plain C` results as I didn't adapt their benchmarking code.

**Comment by OrfeasZ** [comment]
I accidentally submitted this issue without a description. I've written the description now, sorry for that.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/releases/tag/v2.14.0

Backported. Thanks for checking it for me!

**Comment by Nava2** [comment]
This is going to sound strange, but you should initialize the unordered
maps with a size that "makes sense" given the average simple type. The
default implementation can lead to massive memory usage for no gain as more
are added over time. If necessary, make it configurable, if not, don't!
