### ISSUE TITLE
Update derived's base methods during runtime feature

### ISSUE THREAD

**Issue by jkbz64** [ThePhD/sol2#219]
Simple usertype are designed to be manipulated/modificated during runtime and what would be nice to have is ability to update derived's base methods during runtime.
Example code:
```
class A
{
public:
    virtual ~A() = default;
};

class B : public A
{
public:
    virtual ~B() = default;
};

int main()
{
    sol::state state;
    state.new_simple_usertype<A>("A");
    state.new_simple_usertype<B>("B", sol::base_classes, sol::bases<A>()); // OFFTOP: It crashes here because there's no stuff registered in A usertype( is it an issue? )
    state.set("b", std::make_unique<B>());
    state["A"]["method"] = [](){ };
    state.script("b:method()"); // exception thrown
} 
```
Is it even possible to update base methods during runtime? or after every modification? or is it only compilation time feature?

**Comment by ThePhD** [comment]
I had forgotten about the caveat that `simple_usertype` needs to be able to have items add-able to it later on. I'll take a look at what it would take to implement something like this. I would have honestly thought that this would work already, but I'm probably missing something.

Note I have like 2 papers and a project to do for school already, so I might be a while.

**Comment by ThePhD** [comment]
Oookay. So, this code works pretty much exactly as is. I still have some more checking to do but this is just fine as far as I can tell...

**Comment by jkbz64** [comment]
Sadly, it doesn't work for me at all.
First problem is that it won't compile if there's bare simple usertype, in this case 'A'. After adding whatever stuff to it - it compiles.
``` lua.new_simple_usertype<A>("A", "a", &A::a); ``` - Compiles
``` lua.new_simple_usertype<A>("A"); ``` Not compiling
Second problem is this code fails there ```lua["A"]["method"] = []() { return 200; };``` throwing this
```terminate called after throwing an instance of 'sol::error'
  what():  lua: error: lua: error: sol: attempt to index (set) nil value "method" on userdata (bad (misspelled?) key name or does not exist)```
Using fedora 24, gcc 6.1.1, latest version of sol.

**Comment by ThePhD** [comment]
Well, let me push my changes, maybe I inadvertently fixed something... who knows.

**Comment by ThePhD** [comment]
This is now ultra super duper fixed and checked in. It's also part of the tests for all platforms. If something snaps again, let me know.

https://github.com/ThePhD/sol2/releases/tag/v2.14.2
