### ISSUE TITLE
Is it possible to save a pointer to a Lua function?

### ISSUE THREAD

**Issue by chadlayton** [ThePhD/sol2#221]
My situation is roughly this:

```cpp
lua.set_function("set_on_collision_callback", [](std::function<void()>& callback) { 
// I can use callback now without problems
callback();
// But I want to cache it. This code jams a pointer to the callback in some userdata 
// so it can be called after a collision.
physics_body.set_on_collision_callback(&callback); });
```

But when I get around to trying to use the callback I get an access violation. From googling around a little it seems like this is possible using the reference system in Lua? But I'm hoping sol might provide some mechanism to do this safely.

**Comment by ThePhD** [comment]
That `std::function<void()>&` doesn't last beyond the duration of the function. You need to store it as a value and keep that value around somewhere.

**Comment by ThePhD** [comment]
As far as "can I save this callback?", you sort of can.

You can get a `lua_CFunction` from something that you know you serialized from C++. But an actual Lua function behaves differently. The `physics_body` callback thing, if you have control over it, should take an actual value. If you don't have control, you'l need to do some finagling or wrap up the physics body in some way to keep the callback stored somewhere.

**Comment by chadlayton** [comment]
Fair enough, thanks for the answer!
