### ISSUE TITLE
Functions within tables can't be passed a "self" argument

### ISSUE THREAD

**Issue by Manic0892** [ThePhD/sol2#223]
I can't figure out a way to pass a `self` argument to a member function of a Lua table.

Here's an example Lua script:

```
SomeTable = { someVal = 100 }

function SomeTable:AddToSomeVal(value)
    self.someVal = self.someVal + value
end

function PrintSomeVal()
    print(SomeTable.someVal)
end
```

Here's an example C++ program to call it:

```
#include <iostream>
#include "sol.hpp"

int main() {
    sol::state lua;

    lua.open_libraries(sol::lib::base, sol::lib::package, sol::lib::table);

    lua.script_file("repro_bug.lua");

    lua["PrintSomeVal"]();
    lua["SomeTable"]["AddToSomeVal"](10);
    lua["PrintSomeVal"]();


    return 0;
}
```

Expected output:
```
100
110
```

Output:
```
100
terminate called after throwing an instance of 'sol::error'
  what():  lua: error: repro_bug.lua:4: attempt to index a number value (local 'self')
Aborted
```

This reads to me as sol2 not calling a table's member function properly, which makes sense considering sol2 has no idea that `AddToSomeVal()` is a member function using the `:` operator.  However, I can't find anything in the docs about any way to call a member function as a member function.

One workaround is to write a different function to do this in Lua, e.g.
```
function CallFunctionInSomeTable(function_name, ...)
    return SomeTable[function_name](SomeTable, ...)
end
```

Calling in C++:
```
lua["CallFunctionInSomeTable"]("AddToSomeVal", 10);
```

This creates ugly syntax, and isn't an ideal solution.  Is there a different/better way to do it?

**Comment by ChickenNuggers** [comment]
I don't think there's a different way to do it. If there is, consider this my notification subscription for when someone says so. :P

**Comment by jkbz64** [comment]
Everything works fine, when you call it as ```lua.script("SomeTable:AddToSomeVal(10)");```. I think it's because ```lua["SomeTable"]["AddToSomeVal"](10);``` is turned into sol::function as free function, not a member one, and it doesn't know about 'self'.

**Comment by ThePhD** [comment]
It is turned into a free function and it needs a `self` argument.

````
sol::table t = lua["SomeTable"];
t["AddToSomeVal"]( t, 10 );
````

You need to pass the self argument yourself. Note that when you do `obj:function(stuff...)` in Lua, that gets translated -- at the source level -- to `obj.function( obj, stuff... );`. That is, it's just syntactic sugar. Lua doesn't understand what a "member function" is, because it has no member functions.

**Comment by ThePhD** [comment]
I'm gonna tag this as fixed. This question has come up before, however, so what I'm also going to do is make a note here to add an example to the docs and maybe the tutorial somewhere too.

**Comment by ThePhD** [comment]
Example here: http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#self-call
