### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by CodeMound** [ThePhD/sol2#224]
Hey,
I have the following C++ classes:

```
class IComponent 
{
virtual void Foo() = 0;
}

class ComponentA : public IComponent
{
void Foo() override;
}

class B 
{
void AddComponent(IComponent*);
}
```

This is how I register the types:
```
aState.new_usertype<B>("B", &B::AddComponent);
aState.new_usertype<IComponent>("IComponent");
aState.new_usertype<ComponentA>("ComponentA", sol::base_classes, sol::bases<IComponent>());
```

However, when calling in Lua:
`AnInstanceOfB:AddComponent(cp1)`

it crashses:
`_Container_proxy *_Parent_proxy = _Parent->_Myproxy;`
(File: xutility, Error: parent was nullptr)

Seems like abstraction is not yet fully supported?

**Comment by jkbz64** [comment]
You must be doing something wrong, it does work for me. Are you using the latest release?
```
class A
{
public:
    virtual void a() = 0;
};

class B : public A
{
public:
    virtual void a() override { }
};

class C
{
public:
    void wtf(A* a)
    {
        std::cerr << "wtf";
    }
};


int main()
{
    sol::state state;
    state.new_usertype<C>("C", "wtf", &C::wtf);
    state.new_usertype<A>("A");
    state.new_usertype<B>("B", sol::base_classes, sol::bases<A>());
    state.set("b", new B());
    state.set("c", new C());
    state.script("c:wtf(b)");  //Works
}
```

**Comment by ThePhD** [comment]
Can confirm this code works for me. You're going to need to tell me build settings and stuff so I can try to repro properly and get to the root of it.

**Comment by ThePhD** [comment]
Checked in fixes for inheritance, so more complex code where you were seeing the issue should behave better. Sorry about that:

https://github.com/ThePhD/sol2/releases/tag/v2.14.2

**Comment by CodeMound** [comment]
Hi,
sorry for replying late. 
I am currently using the latest version of Sol, which is v2.14.0.
The code was compiled using the visual studio 2015 c++ compiler.

Also sometimes (?) it breaks at _std::string err = message ? message : "An unexpected error occurred and forced the lua state to call atpanic";_ "Vector<T> too long."

**Comment by ThePhD** [comment]
The latest version is 2.14.2, which you should get and try your code. A link is in my earlier comment.

If you still have trouble, post back here and I'll attempt to help you.

**Comment by CodeMound** [comment]
Unfortunately, the latest version does not fix the error.

**Comment by ThePhD** [comment]
Ah, those are important details. If a template definition like that can screw things up, I have to be careful! Let me try to report with the original typedef, to see if I can catch what's going on.

**Comment by ThePhD** [comment]
Still no-repro. I tried to mock up something close to what you were doing by trying the following:

````
#define SOL_CHECK_ARGUMENTS

#include <sol.hpp>
#include <iostream>
#include <cassert>

struct IComponent {

	virtual ~IComponent() = default;
};

struct FZGameObject {
	std::string mName = "Woof";

	void AddComponent(IComponent* ic) {

	}
};

template <typename C>
struct Component : IComponent {
	C component;
};

struct MeshRenderer {
	int data = 20;
};

typedef Component<MeshRenderer> FZMeshRendererComponent;

int main() {
	sol::state lua;

	lua.new_usertype<FZGameObject>("GameObject", 
		"Name", &FZGameObject::mName, 
		"AddComponent", &FZGameObject::AddComponent
	);

	lua.new_usertype<IComponent>("IComponent");
	lua.new_usertype<FZMeshRendererComponent>("MeshRendererComponent", sol::base_classes, sol::bases<IComponent>());

	lua.script(R"(
	local go = GameObject.new()
	local comp = MeshRendererComponent.new()
	go:AddComponent(comp)
)");
}
````

`ic` in add-component works out just fine. Not sure what could be going wrong for the templates, honestly. I'm glad you found a work-around though, so I guess all's well that ends well?
