### ISSUE TITLE
Invalid destruction of usertypes causes crash

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#227]
A weird issue was introduced with commit 330df79, where sol2 will attempt to destroy usertype instances after GC, but it will instead fail, resulting in a crash (depending on the class definition).

Here's the code to reproduce the issue:
```cpp
class CrashClass
{
public:
	CrashClass()
	{
		std::cout << "Constructing! " << std::endl;
	}

	~CrashClass()
	{
		std::cout << "Destroying!" << std::endl;
		a = 10; // This will cause a crash.
	}

private:
	int a;
};
```

```lua
function testCrash()
    local x = CrashClass()
end
```

```cpp
lua.new_simple_usertype<CrashClass>("CrashClass",
    sol::call_constructor, sol::constructors<sol::types<>>()
);

for (int i = 0; i < 10000; ++i)
{
    lua["testCrash"]();
}
```

**Comment by ThePhD** [comment]
Graaahhh this problem again mother--

Okay, I'll get on it. But not for the next week, probably. Presentation and shit to do.

**Comment by OrfeasZ** [comment]
As mentioned in #226, the last sol2 location the debugger shows is `sol::detail::user_alloc_destroy<T>`, where `lua_touserdata(...)` returns a null pointer, and therefore the destructor of a null object is being called.

**Comment by OrfeasZ** [comment]
It should also be noted that this only happens for simple_usertypes.

**Comment by ThePhD** [comment]
Alright, this is fixed and a test has been added for it as well: https://github.com/ThePhD/sol2/releases/tag/v2.14.2
