### ISSUE TITLE
Unpacking multiple return values into tuple in incorrect order

### ISSUE THREAD

**Issue by henriquegemignani** [ThePhD/sol2#231]
Sol Version:  v2.14.2, as single header
Lua Version: 5.1.5
Compiler Version: Visual Studio 2015 Update 2. `Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x64`

Code:
```c++
#include "sol.hpp"
#include <tuple>

int main(int argc, char** argv) {
	sol::state l;
	l.script("function f() return '3', 4 end");

	std::tuple<std::string, int> result = l["f"]();
	auto s = std::get<0>(result);
	auto v = std::get<1>(result);
	printf("values: %s %d\n", s.c_str(), v);
	assert(s == "3");
	assert(v == 4);
    return 0;
}
```

Example Run:
```
C:\bleh>call "%VS140COMNTOOLS%VCVarsQueryRegistry.bat" 64bit
C:\bleh>call "%VCINSTALLDIR%vcvarsall.bat" amd64
C:\bleh>cl -Ilua main.cpp lua\*.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23918 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
*snip*

C:\bleh>main.exe
values: 4 3
Assertion failed: s == "3", file main.cpp, line 13
```

Meanwhile, running the same code works fine on GCC 4.9.2:

```
$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -std=c++14 -I/usr/include/lua5.1 -llua5.1 main.cc
$ ./a.out
values: 3 4
```

**Comment by ThePhD** [comment]
Oh boy. More tuple bugs. I can't wait to get in there...

**Comment by ThePhD** [comment]
Found the bug:
`return std::tuple<decltype(stack::get<Args>(L, index))...>{stack::get<Args>(L, index + tracking.used, tracking)...};`

That is supposed to evaluate things in a specific initialization order. It's instead doing it in some other crazy ordering. I'm going to assume this is some new stupid caveat with tuple constructors and returns using `{ ... }`, and not just bad behavior on MSVC's part. The good news is, I can probably fix it. The bad news is, more recursive template instantiations...

**Comment by ThePhD** [comment]
Thanks to @Naav for checking this and finding it faster than I can. Turns out this is a compiler bug and basic workarounds aren't helping:

> http://stackoverflow.com/questions/14060264/order-of-evaluation-of-elements-in-list-initialization#comment40614505_14060981

> In Update 2 we’re now calling initializer lists in order, according to the Standard. In places where we fail to do so—usually because of nontrivial dependencies between classes in the initializer list—we’ll emit a warning. - https://blogs.msdn.microsoft.com/vcblog/2016/02/11/compiler-improvements-in-vs-2015-update-2/

No warning, even. I guess I bite the dirt and write a recursive implementation to expand arguments, then pass it to the tuple constructor.

Thanks, MSVC.

**Comment by ThePhD** [comment]
Fixed here: https://github.com/ThePhD/sol2/releases/tag/v2.14.5

**Comment by ThePhD** [comment]
Thanks for reporting it! I appreciate it.

**Comment by henriquegemignani** [comment]
Wow, this was quick! You fixed this while I was sleeping, never mind returning from work!

```
C:\bleh>main.exe
values: 3 4
```
Seems to be working! :D

**Comment by ThePhD** [comment]
Glad you're happy with the fixes. Feel free to stop by #189 when you feel like it and dropping a note about how you're using sol2, if you ever get the chance to!

**Comment by ThePhD** [comment]
I will note that I actually repro'd the issue on VS 2015 Update 3, if that's of any help.

**Comment by henriquegemignani** [comment]
@Naav 
```
C:\bleh>cl -Ilua main.cpp lua\*.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
*snip*
C:\bleh>main.exe
values: 4 3
Assertion failed: s == "3", file main.cpp, line 13
```
Thanks for the heads up that Update 3 was released anyway.
