### ISSUE TITLE
Can't modify table

### ISSUE THREAD

**Issue by jkbz64** [ThePhD/sol2#232]
There's problem with modifying the table of object. It did work some releases ago. I did use the latest sol/single.hpp from master branch aswell as the one from Releases.
```
class A
{
public:
    void func() { }
};

int main()
{
    sol::state state;
    state.new_simple_usertype<A>("A");
    sol::table table = state["A"];
    table["func"] = &A::func; // table.set also doesn't work
    A a;
    state.set("a", &a);
    state.script("a:func()"); // exception thrown
}
```
```
terminate called after throwing an instance of 'sol::error'
  what():  lua: error: [string "a:func()"]:1: attempt to call a nil value (method 'func')
```
Maybe you could add a unit test to make sure it does work every release?
GCC 6.1.1

**Comment by ThePhD** [comment]
This is part of the tests. Something weird must be happening here.

**Comment by ThePhD** [comment]
Oh. This is biting me again.

So, there's 3 separate metatables generated when you create a usertype. One for values, one for pointers/references, and one for unique_usertypes.

The tables all clone the same things... on creation. When adding, things reference the original usertype table... except when it employs the table-indexing optmization for things that have no variable-style bindings (or that require indexing). This makes it NOT link the table items together, and thusly things get a bit wonky.

I think a bit of a refactor is necessary to make sure this gets done properly. It will take a little bit of time. For the moment, I'll see if I can't push some hacks later in the week (I have some projects due this week). I know it's rough, but you'll have to bear with me for a bit...! Sorry.

**Comment by ThePhD** [comment]
Here's a blunt-hammer fix that solves your problem, while avoiding the hard refactor on my part:

https://github.com/ThePhD/sol2/releases/tag/v2.14.8

Have fun! I'll try to remember to come back to this when there's not a project due in 3 hours. :V

**Comment by DanielAdolfsson** [comment]
This doesn't work when using sol::factories.

    _luaState.new_usertype<Object>("Object",  
        "Create", sol::factories([]() { return std::make_shared<Object>(); }));

    sol::table t = _luaState["Object"];
    t["Test"] = []()
    {
        std::cout << "Yep works" << std::endl;
        return 0;
    };

    _luaState.script("o = Object.Create();");
    _luaState.script("o:Test()");


> attempt to call a nil value (method 'Test')

**Comment by ThePhD** [comment]
Only `new_simple_usertype` is extensible. Change your declaration to use `new_simple_usertype`, and *not* `new_usertype`.

**Comment by DanielAdolfsson** [comment]
Ha! Look at that, it's even in the documentation.

Thanks!
