### ISSUE TITLE
std::vector member support

### ISSUE THREAD

**Issue by CodeMound** [ThePhD/sol2#233]
Hi again,
currently trying to figure out how std container are interpreted by sol.

```
class A
{
std::vector<B*> List;
}
```

Inside Lua, how to access elements within the container?
`sol::as_table` (http://sol2.readthedocs.io/en/latest/api/as_table.html) works for global variables, but not members.
`aState.new_usertype<FZTerrain, FZString>("Terrain", "DisplacementScale", &FZTerrain::mDisplacementScale, "Size", &FZTerrain::mSize, "DiffuseTextures", sol::as_table(&FZTerrain::mDiffuseTextures));` yields template compiler error.

Haven't found anything in the docs yet, but I keep digging...

**Comment by ThePhD** [comment]
Drop the `as_table`, bind it like a regular variable, and then access it with `a_obj.DiffuseTextures[2]` or whatever you like. Then you'll have access to the `B*` or the `Texture*` or whatever is in there.

If that code doesn't work, come back and let me know so I can help you go all the way.

**Comment by ThePhD** [comment]
Well, the Lua code as I showed you works. Here's a more complete example:

```` cpp
#include "sol.hpp"
#include <vector>
#include <cassert>

class A {
public:
	int a;
	A(int b = 2) : a(b) {};

	void func() { }
};

struct B {

	B() {
		for (std::size_t i = 0; i < 20; ++i) {
			a_list.emplace_back(static_cast<int>(i));
		}
	}

	std::vector<A> a_list;
};

int main() {
	sol::state lua;
	lua.new_usertype<B>("B", 
		"a_list", &B::a_list
	);

	lua.script(R"(
b = B.new()
a_ref = b.a_list[2]
)");

	B& b = lua["b"];
	A& a_ref = lua["a_ref"];
	assert(&b.a_list[1] == &a_ref);
};
````

Make sure you're using latest, just to be safe: https://github.com/ThePhD/sol2/releases/tag/v2.14.8

**Comment by CodeMound** [comment]
Ok. But how about assigning and pushing values into the vector?
Oddly `b.a_list[0] = foo` has no effect. (The vector was resized to 3)

Any way to make lua native table functions (e.g. table.insert) work with vectors?

**Comment by ThePhD** [comment]
Lua's indices are 1-based. [0] won't do anything for you, unfortunately.

**Comment by CodeMound** [comment]
Ooops. You're right. Should get some sleep.

**Comment by Redyz** [comment]
Maybe my lua is rusty but I am unable to extract the size of a vector created like that,

I'd expect something like:
`table.getn(b.a_list)`
But I believe that wouldn't work because it's probably a userdata type;

Maybe in conjunction with
`lua.new_usertype<B>("B", 
        "a_list", sol::as_table(&B::a_list)
    );
`
But I believe that was deprecated, so is there a way to get the .size() of STL containers from within Lua? Or do I have to wrap/expose each of those methods?

I've searched for this all night, maybe I'm just missing one bit of info.

**Comment by ThePhD** [comment]
Don't do `sol::as_table`. Just pass the member variable directly. Then use the length operator, `#`. So, `#(b.a_list)`. That's how it's done.

**Comment by Redyz** [comment]
I *am* rusty, It's been 5 years, incredible - thanks for the great tools and incredibly quick response.
