### ISSUE TITLE
Is it possible to get a modifiable reference to a variable that exists in Lua in C++?

### ISSUE THREAD

**Issue by Manic0892** [ThePhD/sol2#234]
For instance, say I had in Lua:

```
someTable = { someThing = "someString" }
```

Then in C++, I could say:

```
lua["someTable"]["someThing"] = "a different string";
```

But I would like to say:

```
sol::object someThingRef = lua["someTable"]["someThing"];
someThingRef = "a different string"; // Doesn't work because someThingRef doesn't support =
```

The reason for this is that it would be handy to save a reference to a Lua variable (even if it's inside a table), pass it to some other function that doesn't have a reference to the Lua table the variable is in, and let that function modify it.

Is there a way to do this?

**Comment by Manic0892** [comment]
Looking at it again, it seems like I basically want to use `sol::proxy`.  I know that it says in the docs that you don't recommend passing them between functions or classes--what's the reasoning behind that?

**Comment by ThePhD** [comment]
`sol::proxy` is templated beyond measure. You'd never be able to successfully hope to capture its type and keep it in a class or a function, unless you were just A-Okay with templating everything. And even if you were okay with it, you _shouldn't_.

It also stores a _reference_ to the table / table-alike it's accessing. So if that goes out of scope (e.g., you do anything more than look sideways at a class), your code will be irreversibly broken.

You can try `someThingRef = object(L, in_place, "a different string");` for now, while I try to figure out how to make that code compile without breaking something.

**Comment by Manic0892** [comment]
Hmm, I can't seem to make the code you suggested work in this case.  I'm basically generating a `std::map<std::string, sol::object>` to pass to another function; the game I'm working on has all of sol's functionality wrapped with utility functions, and the level editor would get this map and dynamically build a widget with the keys and value entry fields.  Example:

```
std::map<std::string, sol::object> Lua::GetMembers(sol::table& table)
{
    std::map<std::string, sol::object> map;

    for (auto& value : table)
    {
        map.emplace(value.first.as<std::string>(), value.second);
    }

    return map;
}
```

So basically what I need is a reference/pointer-like variable.  The table inside of Lua can be guaranteed not to be destroyed, but when someone using the editor changes a value in-editor, the Lua variable needs to be changed as well.  The usage I'm looking for is:

```
// Slimmed-down in-engine code.  The entity has a bunch of tables attached to it
// that store data, execute game logic, etc.
sol::table table = someEntity->GetScript("someTable");
std::map<std::string, sol::object> map = Lua::GetMembers(table);
map["someThing"] = "a different string";
```

The reason for all this being that the editor should never mess around with Lua directly, such as indexing into the state/table.  The editor should just pass data to the reference.

Am I overthinking this?  I don't want the editor dicking around in the table itself, mostly because there might be sub-tables and other crap--but if the type could be guaranteed correct and the table itself was guaranteed to exist, is there an easier way to do it?

**Comment by ThePhD** [comment]
Modifying exactly the same reference 'in-place' is absolutely impossible for Lua. This is why that `=` function is only there on `proxy`: you need the keys to refer to the variable you want to overwrite. Once you perform an operation and just get a direct handle to the value itself, you can't 'rewrite' that spot (unless it's by name). You may store a new object for that name and then when you serialize the map down again for that entity or for your editor, but ultimately modifying something 'in place' in Lua requires you have a key that tells Lua what that is.

To make the code compile, you'd need `map["someThing"] = sol::object(table.lua_state(), sol::in_place, "a different string");`.

That syntax is basically garbage, though, so I'm looking into pushing an update that allows your syntax to work, while not exactly updating the same object representation and basically doing the above...

**Comment by Manic0892** [comment]
Aha, OK, that makes a ton of sense!  That syntax may be workable if I hide it behind a preprocessor define or something. 

Thank you so much!

**Comment by ThePhD** [comment]
After a bit of review, I don't think I can make `sol::object ref( ... ); ref = "stuff";` actually compile, because it's a taaad misleading.

Specifically, you can't actually reference items in Lua this way (as I explained before, it requires the key-value lookup to do so). All this does is make a new object, and if you don't set it back on that key (or use `sol::proxy`), it will actually not 'update' the value the object originally pointed at. Ultimately, this will probably result in a lot of confusion.

I think I'll just have to let people manually update things and access the table in that manner themselves. I tried to dig deeply into the Lua C API, but couldn't actually find a way to change this behavior, which is a bit surprising... I might actually e-mail the Lua Mailing List about this, just out of curiosity.
