### ISSUE TITLE
State corruption upon calling is<protected_function> on a sol::object from a protected_function_result from a function returning a table

### ISSUE THREAD

**Issue by Philpax** [ThePhD/sol2#237]
This one was fun to track down (testing with latest LuaJIT and Sol2) - you can see there's a lot of conditions involved!
```cpp
#include "sol.hpp"
#include <iostream>

int main() {
	sol::state lua;
	lua.open_libraries();

	lua["f"] = [&] { return lua.create_table(); };

	sol::protected_function pf = lua["f"];
	sol::object obj = pf();

	if (obj.is<sol::protected_function>())
		std::cout << "PF" << std::endl;

	pf();
	pf();

	return 0;
}
```
When `is<sol::protected_function>` is called, calling `pf()` one more time will cause a memory read error (failed to read 0x10) at scope exit; calling it twice (as seen here) causes it to blow up within the second call deep within Lua.

I'm not sure if these are the only conditions that trigger it, but this is a minimised version of my real code. Commenting out the `is` results in no issues: the function runs to the end without any exceptions or crashes. From testing, it crashes on `is<sol::function>` and `is<sol::protected_function>`, but does not crash on anything else (`is<sol::table>`, `is<int>` works fine)

**Comment by ThePhD** [comment]
Thanks for reporting this. It's fixed now. https://github.com/ThePhD/sol2/releases/tag/v2.14.9
