### ISSUE TITLE
sol::protected_function does not return data correctly

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#238]
I've a problem with `sol::protected_function`, i can't get it to return anything useful, i'm trying to use methods close to your documentation for test cases.
http://sol2.readthedocs.io/en/latest/api/protected_function.html

Program/compiler : VS2015 VC++
Lua version : tested with Luajit 2.1.0 beta2 aswell as Lua 5.3.3
Sol version : 2.14.8 release, single header sol.hpp
No other engines/libraries, empty project

Using a lua function directly works fine, the variables are sent to lua and data gets returned without any problem.
However using a `sol::protected_function` returns either 0 (when trying to return a number from Lua to C++) or an empty string (if error or when returning a string from Lua to C++) if a `sol::protected_function_result` is used to store the returned data.
If  `sol::optional<T>`is used to get the returned data from the `sol::protected_function` then it seems to always fail, even if Lua was called correctly and tried to correctly return data.

Code example for all three test cases:
```C++
//setup sol/lua
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::string);
	
	lua.script("function ErrorHandler(msg) print('Lua created error msg : ' ..  msg) return msg end");
	lua.script("function stringtest(a)  print('Lua recieved content : ' .. a) return a end");

// test normal function
	std::string str = lua["stringtest"]("normal test");
	std::cout << "Back in C++, direct call result is : " << str << std::endl;

//test protected_function
	sol::protected_function Stringtest(lua["stringtest"]);
	Stringtest.error_handler = lua["ErrorHandler"];
	sol::protected_function_result stringresult = Stringtest("protected test");

	if (stringresult.valid())
	{
		std::string s = stringresult;
		std::cout << "Back in C++, protected result is : " << s << std::endl;
	}
	else
	{
		sol::error err = stringresult;
		std::string msg = err.what();
		std::cout << "error :" << msg << std::endl;
	}
//test optional
	sol::optional<std::string> opt_result = Stringtest("optional test");
	if (opt_result)
	{
		std::string s = opt_result.value();
		std::cout << "Back in C++, opt_result is : " << s << std::endl;
	}
	else
	{
		std::cout << "opt_result failed" << std::endl;
	}
```

Output :

```
Lua recieved content : normal test
Back in C++, direct call result is : normal test
Lua recieved content : protected test
Back in C++, protected result is :
Lua recieved content : optional test
opt_result failed
```
As you can see, `sol::protected_function_result stringresult` is valid, so Lua correctly recieves the string and sends it back to C++, however the result has no string content, resulting in an empty message on the printout. If i try to retrieve numbers instead, C++ gets always 0's back, regardless what number Lua tries to return.

Contrary to that, a check if `sol::optional<std::string> opt_result` is valid just fails, even if Lua seems to properly have recieved the data, so there seems to be something wrong during Lua returning data to C++ when using a `sol::protected_function`.

If i cause a deliberate error by changing the lua function name to call from `stringtest` to something like `string______test`, aka something that causes lua to not find the function, in order to provoke an error message return then the normal function call crashes the program (obviously, no problem here). However both the `protected_function` calls seem to correctly create the error message in Lua, but again, nothing valid gets returned, to C++, not even the error message (or it's an empty string). So calling Lua functions and working with data in Lua is no problem, getting the data back to C++ has a problem when using protected_functions.

Here is an output when deliberately calling an invalid function with both the protected_function calls (i left the crashing direct function call away, this is only the output for both protected_function calls):

```
Lua created error msg : attempt to call a nil value
error :
Lua created error msg : attempt to call a nil value
opt_result failed
```

This happens with both LuaJit 2.1.0 beta 2 aswell as Lua 5.3.3

**Comment by ThePhD** [comment]
Bizarre: I've got no idea what's going on. I'm going to set up a testbed with this code and then put it through the wringer to see what's going on, but it'll take me a ibt.

**Comment by ThePhD** [comment]
Fiiiiiiixed: https://github.com/ThePhD/sol2/releases/tag/v2.14.9
