### ISSUE TITLE
Adding Usertype Variables to New Table

### ISSUE THREAD

**Issue by Tresky** [ThePhD/sol2#241]
My application has a few singletons and I am trying to expose one of them to the Lua interpreter to be able to use. I was able to do this in LuaBridge and am trying to figure out how to replicate this in Sol2.

```
MyClass* MyClassObj = new MyClass();

// ...

sol::table namespace = lua.create_named_table("global");
namespace.new_usertype<MyClass>("MyClass",
  // ... functions registered
);
namespace["MyClassObj"] = &MyClassObj; // <---- Works in LuaBridge, but not here
```

The issue I'm having is that Sol2 throws the following error:

> terminating with uncaught exception of type sol::error: lua: error: myfile.lua:39: attempt to index field 'MyClassObj' (a userdata value)

As a reference, in LuaBridge I was able to do this:

```
.beginNamespace("global")
  .addVariable("MyClassObj", &MyClass) // <---- This line successfully adds to the table
  .beginClass<MyClass>("MyClass")
    .addFunction(/* ... */)
  .endClass();
```

Thoughts?

Thanks a lot,
Tresky

**Comment by ThePhD** [comment]
That code looks fine to me and runs on my machine, albeit with one change:

`namespace["MyClassObj"] = MyClassObj;`

`MyClassObj` is already a pointer, in your example. You're giving sol2 a pointer to a pointer (`MyClass**`), whereas (I'm assuming) `MyClass` in the LuaBridge example is just a regular object (that somehow isn't colliding with the `MyClass` definition, but we're going to pretend it's valid).

sol2 does not automatically unpack / handle `T**` values. At that point we assume you have some crazy handler scheme and it's up to you to do the right thing. So, just pass regular pointers and regular objects.

Good luck!

**Comment by Tresky** [comment]
Thanks so much for your reply. The example in the LuaBridge code I provided also uses a pointer, just as my code for Sol2 does. However, I tried to remove the & as you suggested, but I get a different error whenever I execute my script.

> terminating with uncaught exception of type sol::error: lua: error: lua: error: myfile.lua:43: sol: received null for 'self' argument (use ':' for accessing member functions, make sure member variables are preceeded by the actual object with '.' syntax)

I am really unsure what this means, but the line that it is failing on looks as such:
```
unrelatedObject:SetPosition(144, 144);
```
However, it is completely unrelated to the issue from before; at least that's how it seems. I am not really sure.

Thanks again!

**Comment by ThePhD** [comment]
make sure `unrelatedObject` has the proper usertype and has the function `SetPosition` on it, otherwise it's going to bork like that.

**Comment by Tresky** [comment]
Hmmm, I checked the function registrations and it's definitely registered with the right usertype and function. I am unsure why it is borking. What is the 'self' argument thing referring to?

Could my issues have to do with me registering static functions on my classes? In LuaBridge, there was a specific `registerStaticFunction()` method. Is this also true in Sol2, or are statics treated just like regular methods?

Also, here is the inheritance structure of the usertypes. Maybe I'm doing inheritance incorrectly?

```
map_mode_namespace.new_usertype<Object>("Object",
  "SetPosition", &MapObject::SetPosition
);
map_mode_namespace.new_usertype<VSprite>("VSprite",
  sol::base_classes, sol::bases<Object>()
);
map_mode_namespace.new_usertype<MSprite>("MSprite",
  "Create", &MapSprite::Create,                   <--- Static function
  sol::base_classes, sol::bases<Object>(),
  sol::base_classes, sol::bases<VSprite>()
);
```

```
unrelatedObject = namespace.MSprite.Create();     <--- Static function
unrelatedObject:SetPosition(144, 144);
```
