### ISSUE TITLE
help: lua_lock, multithreading, oh my

### ISSUE THREAD

**Issue by niv** [ThePhD/sol2#245]
hey!

I'm working on embedding lua+sol somewhere and my current design shows many, many lua_state instances that run in parallel. They don't share unguarded state; thus, so far so good.

However, I'm quite unclear on how sol deals with multiple threads accessing a sol::state concurrently. As far as I can tell from skimming the sources, it doesn't - so I'm just guarding each sol::state with a mutex. This could be more efficient though, I'm sure.

However 2, I've read in the lua C api docs that there's some kind of mechanism (https://www.lua.org/manual/2.1/subsection3_5_6.html & http://lua-users.org/wiki/ThreadsTutorial) that makes lua deal with locking more efficiently than a GIL. Is that supported by sol?  I tried defining them before including my lua code (and sol) just to play with what they do, but they aren't even called.

As I understand it though, even lua_newthread can't actually allow *concurrent* code execution in the same lua_state; only that it has a separate stack and can interleave with other execution in the same space. So that's maybe what sol is already doing with it's function interface?

Sorry for the apparent cluelessness about this. :)

**Comment by ThePhD** [comment]
`sol::state` doesn't deal at all (because Lua doesn't deal). You need to synchronize access and the like yourself.

I don't know much about this topic at all, unfortunately. I know how to handle coroutines and set up a concurrent design, but the actual parallelism bits you'd need to figure out for yourself.

**Comment by niv** [comment]
Hey, thanks for getting back to me.

I've dug into the matter and here's what I found:

* lua in itself is not threadsafe as a default. This comes as no surprise.

* lua 5.x provides macros for lua_lock/lua_unlock that allow optionally guarding against multithreaded access to the same lua_State. These need to be defined at lua compile time.

* Guarding access to a sol::state with a mutex works fine, HOWEVER:

sol::reference calls luaL_ref and friends in the **copy ctor** (and dtor). While obvious in hindsight, this is very hard to guard/protect against and easily results in very hard to track stack/state corruption when passing around references to functions, unless one recompiles lua with lua_lock defined. This isn't always an option and luajit provides no such primitives anyways.

I've run into this when keeping around a sol::function that is then later called into from another thread!

I wonder, would it be feasible/a good idea to add optional guard injection points to sol, at least for implicit things like copy ctors?

It would obviously have to be defined explicitly by the user, but it would be more explicit than just raking one's eyes out to find all copying code.
