### ISSUE TITLE
How to register overloaded member functions

### ISSUE THREAD

**Issue by Grant1219** [ThePhD/sol2#246]
If I have the following class:
```c++
class dummy {
    public:
        void fancy_func(int foo);
        void fancy_func(int foo, int bar);
};
```

How do I go about registering one, or both of those functions so Lua can call them?

Right now when I try there is a large template error that basically boils down to not being able to resolve which function I am referring to.

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/overload.html

**Comment by ThePhD** [comment]
To help pick the right one: http://sol2.readthedocs.io/en/latest/api/resolve.html
