### ISSUE TITLE
How to check the type of number . float or integer?

### ISSUE THREAD

**Issue by 11nk** [ThePhD/sol2#247]
`sol::object.is<double>()` seems .doesn't work ?

**Comment by ThePhD** [comment]
Sorry about that, we weren't using `lua_isinteger` because it wasn't available across all versions of Lua. I've added a compatibility shim for it, so that your check will properly discriminate an integer. Note that `sol::object.is<double>()` will work on essentially ALL number types, since Lua will report that an integer also is a number to a double.

Get the fix from the latest here: https://github.com/ThePhD/sol2/releases/tag/v2.14.11

**Comment by ThePhD** [comment]
More specifically:

````
sol::state lua;
lua["a"] = 50;
lua["b"] = 50.5;
sol::object a = lua["a"];
bool ai = a.is<int>(); // true
bool ad = a.is<double>(); // true

sol::object b = lua["b"];
bool bi = b.is<int>(); // false
bool bd = b.is<double>(); // true
````

**Comment by 11nk** [comment]
Thanks .Now `sol::object.is<int>()` works well

**Comment by ka0s420** [comment]
Hi, I'm sorry if this is an inappropriate place to ask, but I'm having some trouble with type checking also, and this is using the latest single header and lua 5.3.4 x86.

So I have this function:
`void Console::logToConsole(sol::variadic_args logMessage)
	{
		for (auto& m : logMessage)
		{
			auto& arg = sol::object(m);
			
			if (arg.is<int>())
				logToConsole(arg.as<int>());
			else if (arg.is<float>())
				logToConsole(arg.as<float>());
			else if (arg.is<double>())
				logToConsole(arg.as<double>());
			else if (arg.is<char*>())
				logToConsole(arg.as<char*>());
			else if (arg.is<std::string>())
				logToConsole(arg.as<std::string>());
			else
				logToConsole("couldn\'t deduce type of argument");
		}
	}`

its an overload in my console class, that I added to allow for sol:variadic_args so i could take multiple logs in one function call. 

I have arranged the checking of types based on your above comments.

In lua, when I type console.log("I am, " 100, " years old...", 100.1)
The output in the console shows the 100.1 as simply 100. At first it was the other way around, and no matter what int i tried to log, it would appear as a double, i.e 10 would appear as 10.0000 so i put the int check at the top of the checks and now doubles are coming out as ints.

Any suggestion as to what I could be doing wrong here? 

Again, sorry if this isn't the right place, it was the only mention i could find of this in google.

**Comment by ThePhD** [comment]
@ka0s420 Please define `#define SOL_SAFE_NUMERICS 1`. Please read the docs here, relevant section:

> **SOL_SAFE_NUMERICS** triggers the following changes:
> - Numbers will also be checked to see if they fit within a lua_Number if there is no lua_Integer type available that can fit your signed or unsigned number
> - You can opt-out of this behavior with SOL_NO_CHECK_NUMBER_PRECISION
> - **This option is required to differentiate between floats/ints in overloads**
> - Not turned on by default under any settings: this MUST be turned on manually

Finally, please open new issues. Having closed ones makes me lose track of things easily if I'm not paying attention to the discord at exactly that moment.
