### ISSUE TITLE
Support Forums?

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#249]
In the past, it's been recommended that I get a mailing list. I don't quite like mailing lists, so I turned the idea down. However, there's other options that may require less work on my part and be more interactive (and have less pitfalls than mailing lists).

*IRC*
Pros: real-time | lots of clients and webclients for it
Cons: tells everywhere from what ISP / network I connected from (thanks, IRC) | if it's empty, people get scared | does IRC save a transcript at all? Is it one of those extensions? | How the hell do we set up an IRC | old, almost as old as usenet

*Gitter*
Pros: real-time, if you two happen to be there at the same time | has good formatting | ChaiScript is on Gitter too and stuff
Cons: If there isn't lots of activity, may 'scare' people away from it ("oh I won't get support here", etc. etc.) | What's the search like it Gitter?

*Slack*
Pros: I don't know
Cons: I don't know (I only ever used it once)

*Some Forum I write*
Pros: None over Github Issues
Cons: I have to write a goddamn forum I'm having flashbacks to PHPBB aaahhhh | old style | not really much of an improvement over Github Issues | Search in all forums in p. bad

*Mailing List*
Pros: E-mail is forever | Will always ping the shit out of my phone | Can get a cozy 'dedicated' userbase
Cons: "I signed up for this mailing list but nobody's sending anything ded repo" etc. etc. | A sign of the old times

Thoughts? I won't be taking any one of these anytime soon and will still be using GH issues for a while, but I'm sure as sol2 gets more popular I can't have everything be an issue request...

**Comment by ChickenNuggers** [comment]
I personally recommend IRC; moving to a Freenode channel means that you can easily get help between the Lua channel, #lua, and whatever channel could be used for Sol2.

**Comment by kavika13** [comment]
The problem with Slack is it doesn't have a great seamless web interface. You need an account, you need to be "invited" to the server, I think you need some sort of third party daemon to support "invite on demand", etc.

Discord has a slightly better story here, but is sort of new and flaky.

The desktop apps for both of these are pretty hoggish.

**Comment by Nava2** [comment]
Setting up IRC is pretty easy. You just message `ChanServ` and request to register your channel. Also, on Freenode (and many others) you can just message `HostServ` and you can get your host hidden if you'd like. You would have to register your nick though with `NickServ`. 

Of all places, Wikipedia seems to be a decent resource for a tutorial: https://en.wikipedia.org/wiki/Wikipedia:IRC/Tutorial.

**Comment by kavika13** [comment]
> IRC is a bit complicated to use

By this, I mean that the client-side is sort of daunting. Adium and mirc are the ones I have experience with, and they are not use friendly in any way. These days people are used to "click a link, end up in a chat".

It's still a really popular way to do things though, and a lot of devs may already be used to this pain.

**Comment by ChickenNuggers** [comment]
> They might all be old-school and clunky though, not sure.

The Lounge is actually pretty neat and modern. IRCv3 support too.

**Comment by eliasdaler** [comment]
What about [Discourse](https://try.discourse.org/)? I think it looks and works pretty neat. It's very easy to set up.

**Comment by ThePhD** [comment]
I think I'm going to try and get it for Gitter, since it's probably the easiest for me to set up and get going. I'll see how it goes... hopefully nicely, but. Shrug...!

Issues will stay open of course, and so will my e-mail.

**Comment by ThePhD** [comment]
Weee: https://gitter.im/chat-sol2/Lobby

**Comment by amosbird** [comment]
So what's the lastest channel for sol2?

**Comment by ThePhD** [comment]
The readme has a permament discord link.
