### ISSUE TITLE
usertypes passed correctly to methods, but not to constructor

### ISSUE THREAD

**Issue by abeschneider** [ThePhD/sol2#252]
I've added stack code to allow Torch tensors to be used:

```
namespace sol {
    namespace stack {
        template <>
        struct getter<THFloatTensor *> {
            static THFloatTensor *get(lua_State *L, int index, record &tracking) {
                int absolute_index = lua_absindex(L, index);
                void *result = luaT_toudata(L, absolute_index, "torch.FloatTensor");
                tracking.use(1);
                return (THFloatTensor *)result;
            }
        };

        template <>
        struct pusher<THFloatTensor *> {
            static int push(lua_State *L, THFloatTensor *tensor) {
                luaT_pushudata(L, tensor, "torch.FloatTensor");
                return 1;
            }
        };
   }
}
```

And if I have a method that takes a `THFloatTensor` this works fine:
```
void get(THFloatTensor *tensor) {
//...
}
```

However, if I try to make a constructor take a `THFloatTensor` it fails:
```
    class DataLoader {
      DataLoader(THFloatTensor *storage) {
         // ...
      }
    }

    lua.new_usertype<DataLoader>("DataLoader",
                                 sol::call_constructor,
                                 sol::constructors<sol::types<THFloatTensor *>>());
```

when I run the code from Lua (I'm using this as a Lua library) I get:

```
sol: no matching function call takes this number of arguments and the specified types
stack traceback
```

**Comment by abeschneider** [comment]
I should add, I've gotten around this by creating an auxiliary function that has to be called after the constructor, but it would of course be better if everything can be done in the constructor.

**Comment by ThePhD** [comment]
What is "luaT_pushudata" ?

**Comment by ThePhD** [comment]
You've also forgotten to specialize `sol::stack::checker` to work with your userdata pointer. So when an overloaded set is called (e.g., the function call operator), the checker uses the default version on how to check whether your type matches.

Your function would also fail too if you had the safeties turned on (for at least debug builds): http://sol2.readthedocs.io/en/latest/safety.html

Out of curiosity, is there some reason the default pushers for userdata aren't enough? Why do you need to add one specifically for `THFloatTenstor*` ? If you just defined a `new_usertype<THFloatTensor>( .... );` and used the pointer regularly this code works perfectly fine. You're not doing anything that sol2 isn't already doing for you, with no additional effort on your behalf, if that `luaT_pushudata` call is just setting up a metatable and associating it with some `lua_newuserdata` stuff.

If there isn't some compelling answer to the above question, your issue becomes easy to fix: delete the customization point you defined and the code will work.

**Comment by abeschneider** [comment]
`luaT_pushdata` is the function provided by Torch for dealing with their `THTensor` struct. The type is already defined in Torch (via a `require 'torch'`), so I don't want to redefine the type -- I just want to allow Sol to properly push/remove is from the stack.

I also have a checker defined:
```
        template <>
        struct checker<THFloatTensor *> {
            template <typename Handler>
            static bool check(lua_State* L, int index, Handler &&handler, record &tracking) {
                int absolute_index = lua_absindex(L, index);
                bool success = luaT_checkudata(L, absolute_index, "torch.FloatTensor");
                tracking.use(1);
                return success;
            }
        };
```

which I hadn't mentioned previously because it doesn't change the behavior.

Both the `getter` and `pusher` work for any method that isn't a constructor, which makes me suspect the stack code work correctly, but may just be handled differently in the constructor.

Thanks!

**Comment by ThePhD** [comment]
Change the checker to

````
        template <>
        struct checker<THFloatTensor> {
            template <typename Handler>
            static bool check(lua_State* L, int index, Handler &&handler, record &tracking) {
                int absolute_index = lua_absindex(L, index);
                bool success = luaT_checkudata(L, absolute_index, "torch.FloatTensor");
                tracking.use(1);
                return success;
            }
        };
````

It will then recognize things better and not crash. Note that `sol2` considers `THFloatTensor` == `THFloatTensor*` == `THFloatTensor&`, as far as what the default checker implementation does to check objects.

**Comment by ThePhD** [comment]
Though, perhaps you won't have to change your code at all, with the new version I just pushed...

Either way, let me know how it goes: https://github.com/ThePhD/sol2/releases/tag/v2.14.12

Good luck.

**Comment by abeschneider** [comment]
Okay, it appears that I somehow didn't build correctly the previous time. What I had tried previously now works:

```
template <>
struct checker<THFloatTensor *> {
  template <typename Handler>
  static bool check(lua_State* L, int index, Handler &&handler, record &tracking) {
    int absolute_index = lua_absindex(L, index);
    bool success = luaT_checkudata(L, absolute_index, "torch.FloatTensor");
    tracking.use(1);
    return success;
  }
};
```

I tried changing it to `THFloatTensor` (no pointer), but it wouldn't compile.

Thanks for the help!
