### ISSUE TITLE
Protected function accepts wierd initialization method and breaks

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#253]
Here is a strange bug:
Apparently `sol::protected functon` isn't really strict when it comes to assigning it a proper function
As you know you can initialize it like this
```C++
	sol::protected_function func(lua["someLuaFunction"], lua["ErrorHandlerFunction"]);
```
which works perfectly fine.
But for some reason it also accepts this
```C++
// note the '='
	sol::protected_function func = (lua["someLuaFunction"], lua["ErrorHandlerFunction"]); 
```
Sol2 and the compiler won't complain about it and `sol::protected_function_result` will be evaluated as valid if that function is called, however the content of that `sol::protected_function_result` will be 0 or garbage.

While that bug does not make Sol2 not work (it works perfectly fine if the syntax is correct) it's something one should be aware of, because neither lua nor sol2 nor c++ will complain or throw any error messages if you use a `=` by mistake.

**Comment by ThePhD** [comment]
This is not a Lua or a Sol2 problem. This is a C++ problem. C++ has a comma operator, and what you're doing is evaluating the arguments of that comma operator, and then returning the last expression to be used in `protected_function`'s initialization.

This is just a code smell, and has nothing to do with Sol2. Static analysis tools may help eliminate this problem.
