### ISSUE TITLE
Container detection may be a bit too aggressive

### ISSUE THREAD

**Issue by daniel-j-h** [ThePhD/sol2#256]
The `has_begin_end` trait (see [here](https://github.com/ThePhD/sol2/blob/77a1ce76b599c9c3a49c7a8fabde02a6774fd173/sol/traits.hpp#L308-L309) and [impl. here](https://github.com/ThePhD/sol2/blob/77a1ce76b599c9c3a49c7a8fabde02a6774fd173/sol/traits.hpp#L265-L273) detect a type's `begin` and `end` functions.
Based on this trait implementations are being enabled or not [here](https://github.com/ThePhD/sol2/blob/2ac711b7f8f993a94128faa8fa2603a9a2beef10/sol/container_usertype_metatable.hpp#L362-L404) and [here](https://github.com/ThePhD/sol2/blob/2ac711b7f8f993a94128faa8fa2603a9a2beef10/sol/stack_push.hpp#L110-L116).
These implementations want to [alias](https://github.com/ThePhD/sol2/blob/2ac711b7f8f993a94128faa8fa2603a9a2beef10/sol/container_usertype_metatable.hpp#L70-L76) certain types, e.g. `value_type` and `iterator`.

However the presence of `begin` and `end` do not guarantee for these types to be available.

Here is a small self-contained test-case:

```cpp
#include "sol.hpp"

struct T {
  int x;

  void begin() { }
  void end() { }
};

int main() {
  sol::state lua;
  lua.new_usertype<T>("T", "x", &T::x);
  lua.script("function fn(v) end");
  sol::function fn = lua["fn"];

  T t;
  fn(t);
}
```

This fails to compile since there is neither a `value_type` nor `iterator` type defined inside `T`.

I understand it's preferable and very user-friendly to automagically deduce the type modelling the Container concept 99% of the time. Except when it isn't. Strictly speaking the presence of `begin` and `end` member functions give no further guarantees whatsoever.

As it is right now I can't disable this behavior --- it would be great to keep this default but maybe provide means to disable the detection.

Ref. https://github.com/osmcode/libosmium/issues/169

**Comment by ThePhD** [comment]
There's no real means of disabling detection, other to going full ham and writing a customization point. This is undesirable, so I'm going to input a type trait that will disable this, but by default relies on the same techniques. Will update here once I put it in: should be a quick fix, yeh.

**Comment by ThePhD** [comment]
It's in. Here's a complete example:

````
#define SOL_CHECK_ARGUMENTS
#include <sol.hpp>

struct not_container {
	void begin() {

	}
	void end() {

	}
};

namespace sol {
	template <>
	struct is_container<not_container> : std::false_type {};
}

int main() {
	sol::state lua;

	not_container nc;

	lua["nc"] = nc;
	lua["pnc"] = &nc;
	lua["rnc"] = std::ref(nc);

	not_container& lnc = lua["nc"];
	not_container& lpnc = lua["pnc"];
	not_container& lrnc = lua["rnc"];

	return 0;
}
````

**Comment by ThePhD** [comment]
Get it from the single file, or just pull latest: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp

**Comment by daniel-j-h** [comment]
Thanks for being so responsive - reminds me why I'm switching away from Luabind in the first place.

Keep up the good work! :+1:
