### ISSUE TITLE
Enumeration creation should check for valid (key, value) list

### ISSUE THREAD

**Issue by daniel-j-h** [ThePhD/sol2#257]
Quoting http://sol2.readthedocs.io/en/latest/api/table.html#new-enum

```cpp
template<bool read_only = true, typename... Args>
basic_table_core& new_enum(const std::string& name, Args&&... args);
```

> The arguments are expected to come in key, value, key, value, ... list.

This is not being checked, making it easy to screw up by accident.

Here is a small self-contained test-case:

```cpp
#include "sol.hpp"

int main() {
  sol::state lua;

  lua.new_enum("E"
      "x", 1 << 0,
      "y", 1 << 1);
}
```

Missing `,` after `"E"` --- compiles as string literal concatenation. Took me hours to find the missing `,` since I had reached a column limit where `clang-format` was breaking lines exactly like that.

I think a static assert on even sizeof Args parameter pack could do the trick here.

For the record, I haven't checked functions other than `new_enum` for this.

**Comment by ThePhD** [comment]
We check this in other places, and I thought we checked it for the function that this dispatches to internally. I'll look into it real quick.

**Comment by ThePhD** [comment]
We weren't, shucks. I'll push this after looking at the other bug you opened too.
