### ISSUE TITLE
Is it possible to do something similar to Lua's error "level" parameter in C++?

### ISSUE THREAD

**Issue by eliasdaler** [ThePhD/sol2#259]
Suppose I have a C++ function which needs to be called from Lua. It only accepts numbers which are more than zero:

```cpp
void cpp_f(int x) {
     if (x < 0) { ... // error handling? }
     ...
}
```

Suppose some Lua script calls it like this:
```lua
-- somewhere in script.lua
cpp_f(-20)
```
I want to get an error which will show me where in script.lua this wrong call was.

Lua has `error` function which allows you to specify who to blame on the error (e.g. `error("WHY DID YOU DO THIS", 2)` will point to the wrong function call. 

Is it possible to do something like this in C++?
I tried doing `lua.script(R"(error("You did bad!, 2)")` inside cpp_f, but this only shows the error message, not indicating where the error came from.

**Comment by eliasdaler** [comment]
Some short example:

script.lua:
```lua
local doCalc = function()
    cpp_f(-20)
end

doCalc()
```

and cpp_f:
```cpp
void cpp_f(int x, sol::this_state L)
{
    if (x < 0) {
        ... // ???
    }
}
```

Desired output is getting error like this:
"script.lua:2: X must be bigger than zero"

I managed to achieve it with this code (in cpp_f):
```cpp
luaL_where(L, 1);
std::string errorMessage = lua_tostring(L, -1);
errorMessage += "X must be bigger than zero";
lua_pop(L, 1);
throw sol::error(errorMessage);
```

But maybe there's a better solution? Maybe having wrapper in sol2 would be nice. (e.g. `throw sol::error("Message", 2);`)

**Comment by eliasdaler** [comment]
One more thought: throwing sol::error isn't the ideal behavior. Consider this script.lua:
```lua
local doCalc = function()
    cpp_f(-20)
end

local ok, msg = pcall(doCalc())
if not ok then print(msg) end
print("HELLO")
```

Doing this:
```cpp
try {
    lua.script("script.lua");
} catch (const sol::error& e) {...}
```
will cause script.lua to stop execution at doCalc, because of the throw. If I just did "error" call in Lua, I would be able to handle the error inside the Lua script... so I have no idea how to do it properly. :D

**Comment by ThePhD** [comment]
Throwing an error has the correct behavior when you use `pcall` and serialize a normal function (e.g., one not in the form of `lua_CFunction` with `int do_calc_raw_wrapper(lua_State* L) { ... }`. The reason your code fails is because you're not letting `pcall` call `doCalc`: you're calling it yourself with `doCalc()` (a subtle bug to miss, dynamic typing not helping you here, etc. etc.).

We unfortunately don't have a wrapper for `luaL_Where`. I don't think putting that code in the exception's constructor is the best idea either. I think maybe an explicit `sol::where` call might be useful, but I don't know other people's use cases for it, so I don't want to commit to a design just yet. I'll need to survey some Lua code...

**Comment by ThePhD** [comment]
`luaL_Where` makes me think of `luaL_traceback`, though. It seems like that might be more useful to wrap up and present?

**Comment by eliasdaler** [comment]
Oh yeah, I made a mistake with that pcall (because the book said `pcall(function() ... end)` and I didn't realize the function is just passed as an argument).

To be honest, I wasn't familiar with `luaL_Where` or `luaL_traceback` at all, so I can't tell which one is better. It's just the standard behavior of Lua's `error` and `pcall` which automatically append the source of the error to the beginning of the error message.

**Comment by ThePhD** [comment]
I'm not sure I can add this properly. C++ functions and Lua functions could be at arbitrary points in the stack: finding out where function calls actually went wrong might be a bit hard to do for this. I'm just going to let people continue to use `luaL_traceback` and friends.
