### ISSUE TITLE
Comparsion againts nullptr and sol::nil

### ISSUE THREAD

**Issue by VaderY** [ThePhD/sol2#261]
Hi,
I am 2 hours into the lib (so not all doc read yet) but i ran into the inconsistent behavior of nullptr and sol::nil if i wanna see if a lua variable is set or nil.

Moreover, it seams comparison with nullptr always returns as if the variable would be set. (both != and ==)

In one of the docs it is stated that "You can erase things by setting it to nullptr or sol::nil." which would suggest equal behavior for sol::nil and nullptr so i came to the conclusion it should be a bug.

```
	sol::state lua;
	std::cout << (lua["a"] == sol::nil); //1
	std::cout << (lua["a"] == nullptr); //1
	std::cout << (lua["a"] == 0); //1
	lua["a"] = 2;
	std::cout << (lua["a"] == sol::nil); //0
	std::cout << (lua["a"] == nullptr); //1 <-- Am i crazy?
	std::cout << (lua["a"] == 0); //0
```

Using:
Sol2 version: v2.14.12
Boost optional: 1.61.0
GCC: 5.4.0

Awesome library, big thanks for every contributor.

**Comment by ThePhD** [comment]
Under checked conditions, this would actually trigger a panic. Which isn't correct behavior either, but it's probably why I never saw it. Oops.

I'll fix this ASAP.

**Comment by ThePhD** [comment]
Fixed on latest: https://github.com/ThePhD/sol2/commit/0859af3203eb556df41f02f2c553f9db02288c63
