### ISSUE TITLE
document `do_string` and `do_file`

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#263]
Add these two to the tutorial and examples and show some use cases...

**Comment by ThePhD** [comment]
As a side note, people need more examples on how to call scripts and how scripts can return stuff. So that's more work to do. =/

**Comment by ThePhD** [comment]
All set (and now part of the framework which should make @EliasDaler happy):

http://sol2.readthedocs.io/en/latest/api/state.html#state-do-code
http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#running-lua-code

**Comment by eliasdaler** [comment]
Ha-ha, thanks. :D
Maybe add a note there that if do_string/do_file fails, you can turn `sol::protected_function_result` into `sol::error` and display what went wrong. It's very good to know.

Btw, I don't understand this part:

> It will run and returns a protected_function_result proxy that can be called to actually run the code, turned into a sol::function, a sol::protected_function, or some other abstraction.

So, if I do this:
```cpp
sol::protected_function_result r = lua.do_string("return 5");
```

will I get 5 or a function which runs `return 5`? If that's the case, that's not how `do_string` should work. It should return the result of chunk's execution, just like Lua's do_string does. If someone wants to have chunk as a function which can be called, they need to call `load("return 5")` instead.

**Comment by ThePhD** [comment]
Oops. That's what I get for doing my documentation right when I wake up.
