### ISSUE TITLE
Fails to build with exceptions disabled.

### ISSUE THREAD

**Issue by PhilCK** [ThePhD/sol2#264]
Have I missed something in the docs?

I have
```cpp
#define SOL_NO_EXCEPTIONS
#include <sol2/sol.hpp>
```

Which gives me a bunch of errors
```
code/3rdparty/sol/sol.hpp:1304:47: Cannot use 'throw' with exceptions disabled
code/3rdparty/sol/sol.hpp:1308:47: Cannot use 'throw' with exceptions disabled
code/3rdparty/sol/sol.hpp:1312:25: Cannot use 'throw' with exceptions disabled
code/3rdparty/sol/sol.hpp:1464:26: Cannot use 'throw' with exceptions disabled
```

All seem to be around use of optional.

```cpp
throw bad_optional_access("bad optional access")
```

System
Clang 3.7 / XCode / OSX

**Comment by ThePhD** [comment]
That should probably be blocked out; my bad.

Albeit, I think the only proper replacement for it is `std::abort();`

**Comment by ThePhD** [comment]
Oh, joy. `std::terminate`, `std::abort`, `std::exit` and `std::quick_exit` all are not `constexpr`. The `optional` implementation is `constexpr`. In other words, goddamnit C++.

**Comment by ThePhD** [comment]
Get the fixes by pulling from latest: https://github.com/ThePhD/sol2/commit/0a165dc5b4b1df019d78cae3ea6837301549b396

**Comment by PhilCK** [comment]
_Slow reply:_ All fixed for me.
