### ISSUE TITLE
Runtime extensible usertypes?

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#266]
Perhaps there's a way to extend the regular usertype to also be runtime-extensible without burning base-class lookup and other performance to the ground. This would once more close the gap between simple_usertype and usertype in terms of features, and then the only difference between the two would be compilation time shenanigans.

**Comment by ThePhD** [comment]
Note that `simple_usertype` already covers this case: we're just trying to figure out how to get it into the original without abysmal lookup times.

**Comment by ThePhD** [comment]
All usertypes are now runtime extensible, which is something @Unix4ever might appreciate!

**Comment by OrfeasZ** [comment]
@ThePhD What performance impact does this change have?

**Comment by ThePhD** [comment]
@OrfeasZ Not a clue, yet: I'm crunching the numbers and putting up fresh benchmark graphs in the usual place. Then I'll start finding out how much this impacts the common case, and whether or not I need to write some new benchmarks to tease out how much this costs to things like worst-case scenarios...

**Comment by ThePhD** [comment]
On a bright side, all the tests are beginning to pass, so at least it's correct... !

**Comment by Unix4ever** [comment]
Hooray! Thank you 👍

**Comment by ThePhD** [comment]
@OrfeasZ Benchmarks are in, we're not taking too terrible of a hit performance-wise for all kinds of usertypes, simple or otherwise: http://sol2.readthedocs.io/en/latest/benchmarks.html

Notably, the numbers are REALLY funky for Plain Function Calls through C: something weird is going on where there's some big penalty in the way the plain C code is written versus sol and others. I've... checked the code, and I have no good explanation for why it is that why. I'd need to have other people run the graphs and see what's going on...
