### ISSUE TITLE
Joynet, Visual Studio 2015 and sol2

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#269]
So there is apparently (???) an issue using `sol2` in Joynet. It seems to be a compiler error, as @IronsDu and @gigiyq are telling me in #147. This issue will be for pulling Joynet and attemping to put in a small bit of sol2 to compile it. When I am not swamped with a thousand bits of work.

Some things to do:
- Use `sol::state_view` to get access to the Sol abstractions.
- Attempt to initialize and use some userdata in the code
- Find out if and where any compiler faults happen, or if any runtime errors perk up.

**Comment by gigiyq** [comment]
@ThePhD 
I meet the problem with my own codes, not  sol2.
Thank you.

**Comment by IronsDu** [comment]
@ThePhD
Hi, I create Joynet dev branch :  [https://github.com/IronsDu/Joynet/tree/dev](https://github.com/IronsDu/Joynet/tree/dev), now it use sol2 instead of lua_tinker.

(Compiler error on visual studio 2015 update 1)

Please clone it, try compiler, whether  success.

Ps, please search TODO in Joynet.cpp, I write some question in code.

(Thank you, I really not have visual studio 2015 update 4/x )

**Comment by ThePhD** [comment]
I do not receive a compiler error in Visual Studio 2015, Update 4. I unfortunately can't test Visual Studio 2015, Update 1. To solve the compiler error, I think you have to update because of a Bug in VC++ compiler for that update. Is very unfortunate. To answer TODO question:

> /*  TODO::previous version, i want save a lua funciton in cpp, will(can) call it after some time  */

Try:

````
std::string my_error_function( std::string msg ) {
     // Customize error message, produce traceback with luaL_trackback, 
     // print to std::cerr, etc...
     return msg;
}

int64_t startLuaTimer(int delayMs, sol::protected_function callback)
    {
        auto id = mTimerIDCreator.claim();
        auto timer = mTimerMgr->AddTimer(delayMs, [=](){
            mTimerList.erase(id);
            sol::state_view lua(callback.lua_state());
            // You may want to save your error function into the Lua state, so you don't have to
            // keep making a new object with `sol::in_place`
            callback.handler = sol::object( lua, sol::in_place, my_error_function );
            callback( );
        });
        mTimerList[id] = timer;
        return id;
    }
````

More info at [docs](http://sol2.readthedocs.io/en/latest/api/protected_function.html), [examples](https://github.com/ThePhD/sol2/blob/develop/examples/protected_functions.cpp). In the code above, we set error handler every time: you can avoid this by using `sol::protected_function::set_default_handler( sol::object( lua, sol::in_place, my_error_function ) );` once during program start or Joynet `open` function.

> /* TODO::construction sol::state_view obj, is expend too much time ?
can i save a global sol::state_view obj ? reuse at here! is safe? */

`state_view` is **cheap** to construct. It costs almost nothing to make, should never cause a problem in your code ever. Use liberally and freely.


> /*  TODO::can you provide call funciton of sol::state_view ? */

I do not know what you mean? Putting into `sol::function enterFun` and then calling should be good enough: what syntax are you looking for? If you want `lua["__on_enter__"](msg->mServiceID, msg->mID)`, you can write that too. It will work and do what you want.

> /*  TODO:: can save lua obj to global ? */

`state_view` is cheap to construct, no need to worry about saving.

> /*  TODO:: must be a pointer ? obj is safe and correct(of my Joynet logic) ? */

` lua["CoreDD"] = new CoreDD;` is [will make memory leak, talked about in tutorial](http://sol2.readthedocs.io/en/latest/tutorial/ownership.html). Raw pointers do not own their memory (you can never be sure of them). Do one of following:

`lua["CoreDDObj"] = CoreDD{};`
or
`lua["CoreDDObj"] = std::make_unique<CoreDD>();`
or
`lua["CoreDDObj"] = std::make_shared<CoreDD>();`

We recommend first one. Second one is like first one, but allocates through `new` (not necessary). Third one makes a `shared_ptr`. None of these seem necessary from Joynet architecture and code. First one -- regular value -- is fine. sol2 takes ownership of values by copy or by move unless you `std::ref` or `&obj`. Plain `new Type();` is considered bad practice in modern C++ because cannot tell ownership semantics of `CoreDD*` type (is it shared? Is it single-owner? Who owns?). Value is good.

We change name to `"CoreDDObj"` because `"CoreDD"` is name of Metatable in Lua from: https://github.com/IronsDu/Joynet/blob/dev/src/Joynet.cpp#L684

Either change object name, or change type name in Lua (you will overwrite one if you set 2 things to the same name).

Hopefully this answers all questions.

**Comment by IronsDu** [comment]
Thank you very much, all answers is usefull.
Now, I am download Visual Studio 2015 Update 3.
I will  test my code refer to your suggestion when download completed.

1:
/* TODO::can you provide call funciton of sol::state_view ? */
In lua tinker, It provide:
auto result = lua_tinker::call<int>(L, "foo", args);

like : [https://github.com/IronsDu/Joynet/blob/master/src/Joynet.cpp#L412](https://github.com/IronsDu/Joynet/blob/master/src/Joynet.cpp#L412)

2:
lua["CoreDD"] = new CoreDD;
I know raw pointer isdanger. But don't know sol2 how control Lua obj and C++, I worry these obj is different  of Lua-Code between the obj of sol2 set. ^-^, So i use raw pointer temporarily.

3.
I surprised you how implement 
`
sol::function onDataFunc = lua["__on_data__"]; 
int consumeLen = onDataFunc();
// how to get the result to consumeLen , and none compiler error unexpectedly. Beacause C++ 14?
The return type is template, auto decision  ?
` .

I will study your code 

Thank you.

**Comment by IronsDu** [comment]
Hi, https://github.com/ThePhD/sol2/blob/develop/sol/function.hpp#L91 impletement `int consumeLen = onDataFunc();` ?

**Comment by IronsDu** [comment]
/* TODO::previous version, i want save a lua funciton in cpp, will(can) call it after some time */

I forget tell you, the `startLuaTimer` function is called in Lua  (C++ export it to Lua).(The callback arg is refer to a lua function), like this:
Lua code:
`
function foo()
end

CoreDDObj.startLuaTimer(1000, foo)
`

**Comment by ThePhD** [comment]
We use implicit conversions from `proxy` to `<arbitrary type>`. A good example of this is the proxy iterator for `vector<bool>`'s iterators, where you don't get a bool when you dereference, but a `bool_proxy` that can be cheaply converted to a boolean. This has been possible since C++ 2003. `auto` is actually bad to use with the return type of `sol::function` and docs [warn against it explicitly](http://sol2.readthedocs.io/en/latest/api/function.html) closer tot he bottom of the page.

The `sol::function`/`sol::protected_function` argument can handle Lua functions passed to it.

To understand how Sol2 sets out memory, see [documentation here](http://sol2.readthedocs.io/en/latest/api/usertype_memory.html).

If that's the `lua_tinker` syntax for calling functions, then `lua[ KEY ]( args... )` is exactly what you want.

**Comment by IronsDu** [comment]
Thank you very much, i forget  implicit conversions.
https://github.com/ThePhD/sol2/blob/develop/sol/proxy_base.hpp#L38 Very Good!

**Comment by IronsDu** [comment]
@ThePhD 
Now, It's OK. Very Good.
It's very simple and safety to use, although the benchmark No difference compare with Old Joynet(Use LuaTinker);

But I has a last question of protected_function call, about error handler.
**Please see**: https://github.com/IronsDu/Joynet/blob/dev/src/Joynet.cpp#L575
(I already read your doc, but ..., Thank you)

Moreover, I cache some callback(define in lua) in C++, But not obvious enhance on benchmark ^-^, I guess I think more . The code is here : https://github.com/IronsDu/Joynet/blob/dev/src/Joynet.cpp#L341

**Comment by ThePhD** [comment]
The whole point of sol2 is that you can write less code and still have the same performance as writing plain C code. If there's no change in the benchmark but you've written 50% less code to do the same thing, it's a win.

There are other things you can do for performance, some of them gnarly (like [`sol::c_call`](http://sol2.readthedocs.io/en/latest/performance.html)` and friends). There's also things that are far more fragile, like using `sol::stack_protected_function` to point to things that already exist on the stack (like that Lua callback you pass in) so you save a very small amount of time on not being as safe as `sol::protected_funtion` is.

I would not recommend doing any of these, however, as it does not seem like it will give you any significant benefit in the end for the larger potential error.

For `protected_function` and the error handler, your code will never reach the handler if the code never loaded properly in the first place. That is, certain bad forms of lua code don't error at protected_function execution time, they fail earlier than that: try loading your script with one of the safer versions of `load_file` or `do_file` on `state_view`, or if you're not using Sol to load them then make sure you check for errors there. When I error in lua code with `error("bad");` the protected handler gets called, and then I write subtly bad code (e.g. `print(does.not.exist);`) it gets called. It does not get called for something, like, e.g.:

````lua
function f
     bad.code
end
````

This will error in `lua_dostring` or `lua_dofile`, not `lua_pcall` (`sol::protected_function`).

**Comment by ThePhD** [comment]
Remember that in the general case of things going wrong, you can set a panic handler for ALL of Lua using Sol's [set_panic](http://sol2.readthedocs.io/en/latest/api/state.html#set-panic) on `sol::state_view` or by just using `lua_atpanic` call. For Sol, either function is fine: can also bind a more complicated panic handler that is not a raw Lua C function with:

````
void my_panic (sol::optional<std::string> maybe_msg) {
     if (maybe_msg) {
          const std::string& msg =maybe_msg;
          std::cerr << msg << std::endl;
     }
     // ...
}
````
then
````
lua_atpanic( L, sol::c_call<decltype(&my_panic)>, &my_panic> );
````
or
````
sol::state_view lua(L);
lua.set_panic( sol::c_call<decltype(&my_panic_call)>, &my_panic_call> );
````

The above code is now part of the [exceptions and error docs](http://sol2.readthedocs.io/en/latest/exceptions.html#typical-panic-function).

**Comment by ThePhD** [comment]
I'm going to consider this handled. If you need anymore help, do let me know.
