### ISSUE TITLE
new_usertype operator overload problem

### ISSUE THREAD

**Issue by shultays** [ThePhD/sol2#270]
In example:
https://github.com/ThePhD/sol2/blob/develop/examples/usertype_special_functions.cpp

it fails when I add more overloads for - operator. For example negate or subtracting a float
`
	vec operator-() const
	{
		vec cpy;
		cpy.x = -x;
		cpy.y = -y;
		return cpy;
	}
`
`
	vec operator-(const float& con) const
	{
		vec cpy;
		cpy.x = x - con;
		cpy.y = y - con;
		return cpy;
	}
`

add either to vec struct and visual studio 2015 gives error for me:

`
1>clipped.cpp(36): error C2535: 'vec vec::operator -(const float &) const': member function already defined or declared
1>  clipped.cpp(26): note: see declaration of 'vec::operator -'
1>clipped.cpp(86): error C2672: 'sol::state_view::new_usertype': no matching overloaded function found
1>clipped.cpp(86): error C2784: 'sol::state_view &sol::state_view::new_usertype(const std::string &,sol::constructor_list<Args...>,Args &&...)': could not deduce template argument for 'sol::constructor_list<Args...>' from 'sol::meta_function'
1>  c:\users\engin.mercan\desktop\bloodworks\game\sol.h(12314): note: see declaration of 'sol::state_view::new_usertype'
1>clipped.cpp(86): error C2784: 'sol::state_view &sol::state_view::new_usertype(const std::string &,Args &&...)': could not deduce template argument for 'Args &&' from 'overloaded-function'
1>  c:\users\engin.mercan\desktop\bloodworks\game\sol.h(12308): note: see declaration of 'sol::state_view::new_usertype'
1>clipped.cpp(90): error C2059: syntax error: ')'`

**Comment by ThePhD** [comment]
Try using [overload](http://sol2.readthedocs.io/en/latest/api/overload.html) helpers.

**Comment by ThePhD** [comment]
Also see [usertype special functions example](https://github.com/ThePhD/sol2/blob/develop/examples/usertype_special_functions.cpp#L37).

**Comment by ThePhD** [comment]
Specifically, you can use `sol::resolve` to choose the right operation, or can use `sol::overload` to have multiple operation overloads.

**Comment by shultays** [comment]
Whoops, my bad. Sorry.

Also thanks for this awesome library

**Comment by juncy** [comment]
@ThePhD I have another question about operator overload. 

`sp_mat operator+ (const sp_mat& a, const sp_mat& b) {`
` return a + b;`
`}`
In which `sp_mat` is a matrix type from Eigen (`typedef Eigen::SparseMatrix<double> sp_mat`).

I try the binding by `lua.set_function(sol::meta_function::addition, &::operator+);` but I got a runtime error as follows:
![1](https://cloud.githubusercontent.com/assets/3078809/21747245/35ffc100-d59b-11e6-8361-9526014d59b4.PNG)
And this is my lua script, in which line 11 and 12 got `sp_mat` value respectively.
![2](https://cloud.githubusercontent.com/assets/3078809/21747252/d2abef1a-d59b-11e6-87c4-5c1e678f07a6.PNG)


Do you have some comments on it? Thanks.

**Comment by ThePhD** [comment]
You cannot bind the global "+" operation to work with your types specifically. `sol::meta_function::addition` -- and others like it -- can only be specified with `new_usertype` bindings. That is, there is NO way in Lua to say "hey, make a free function that works like `operator+`.

At least, as far as I know. So, when you register your `sp_mat` type with `new_usertype`, give it a `sol::meta_function::addition, &::operator+` definition.
