### ISSUE TITLE
Userdata or some sort of state.

### ISSUE THREAD

**Issue by PhilCK** [ThePhD/sol2#274]
Hello,

Whats the best way to smuggle some state, ideally is it possible to give a default value to a constructor or some such.

```cpp
// So I can identifiy what Lua state I'm in, and track all cubes in a state.
Cube(int state_id);
```

and from lua

```lua
-- The id was bound earlier.
cube = Cube.new()
```

**Comment by ThePhD** [comment]
I

**Comment by ThePhD** [comment]
Woops. I fat-fingered like 5 different buttons: sorry. I was going to say, if you have something like this, you can pass in the Lua state directly by having `sol::this_state` as an argument to the constructor: http://sol2.readthedocs.io/en/latest/api/this_state.html

If you mean "some incremental ID", just stuff a static in the class itself. If you mean "arbitrary data I can pass around as an opaque handler in Lua", that's what a userdata is for.

**Comment by PhilCK** [comment]
Oh thats want I'm after, I was digging through the docs with some sortof default paramater in mind, but this works better.
