### ISSUE TITLE
How to check parameter type of function is valid or not?

### ISSUE THREAD

**Issue by Phongdq** [ThePhD/sol2#275]
This's my tiny code.

`
inline std::string make_string( std::string input ) { 
	return "string: " + input;
}
int main() 
{
	std::cout << "=== functions example ===" << std::endl;

	std::string fun1("print(CallMessage(1))");
	std::string fun2("print(CallMessage(a))");
	std::string fun3("print(CallMessage(\"a\"))");
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::package);
	lua.set_function("CallMessage", make_string);
	
	try 
	{
		lua.script(fun1);	
		lua.script(fun2);
		lua.script(fun3);
	}
	catch (sol::error& e)
	{
		return -1;
	}
	
	return 0;
}
`

Result: 
string:1
string:
string: a

Problem:
Parameter of function CallMessage is string, but when I pass a parameter is number to this function, the sol::script auto convert this to string. It make my program is fail. 

So, How do I check parameter's type of function is valid or not?

**Comment by ThePhD** [comment]
This isn't really `sol`'s fault as it is Lua's fault. Lua automatically converts from a number to a string without checking. The heavy-handed hammer approach is to use `#define SOL_CHECK_ARGUMENTS` as defined on the [safety page]().



The fine-tuned approach is to use [`sol::protecet( func )`](http://sol2.readthedocs.io/en/latest/api/protect.html). First, pull the latest to make sure you won't encounter any small bugs using it (the release was just updated, again: https://github.com/ThePhD/sol2/releases/tag/v2.15.1). Then, use `sol::protect`. Here's a full example of your code below:

````
#include <sol.hpp>

#include <string>
#include <iostream>

inline std::string make_string(std::string input) {
	return "string: " + input;
}

int main() {
	std::cout << "=== functions example ===" << std::endl;

	std::string fun1("print(CallMessage(1))");
	std::string fun2("print(CallMessage(a))");
	std::string fun3("print(CallMessage(\"a\"))");
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::package);
	lua.set_function("CallMessage", sol::protect(&make_string));

	try {
		lua.script(fun1);
		lua.script(fun2);
		lua.script(fun3);
	}
	catch (sol::error& e) {
		return -1;
	}

	return 0;

}
````

And the error:

> lua: error: [string "print(CallMessage(1))"]:1: stack index 1, expected string, received number

**Comment by Phongdq** [comment]
Thanks for fast feedback. 

I upgraded to newest version and try to use sol::protect(), but I got compile error (Im using VS2015):

`
1>d:\project\mfcapplication12\sol2\functions.cpp(48): warning C4101: 'e': unreferenced local variable
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(32): error C2039: '()': is not a member of 'sol::protect_t<std::string (__cdecl *)(std::string)>'
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\protect.hpp(46): note: see declaration of 'sol::protect_t<std::string (__cdecl *)(std::string)>'
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\types.hpp(224): note: see reference to class template instantiation 'sol::function_detail::functor_function<clean_fx>' being compiled
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(168): note: see reference to class template instantiation 'sol::user<Fx>' being compiled
1>          with
1>          [
1>              Fx=F
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(41): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::set_fx<F,_Ty>(lua_State *,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(41): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::set_fx<F,_Ty>(lua_State *,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(56): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<Sig,_Ty,>(std::false_type,sol::types<Sig>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(56): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<Sig,_Ty,>(std::false_type,sol::types<Sig>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(62): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<R,,_Ty,>(sol::types<Sig>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              R=void,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(62): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<R,,_Ty,>(sol::types<Sig>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              R=void,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(86): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<_Ty,>(sol::types<>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(86): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_convertible<_Ty,>(sol::types<>,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(124): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_member_variable<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(124): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_member_variable<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(143): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_member_function<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(143): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_member_function<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(161): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_function<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(161): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select_function<_Ty,>(std::false_type,lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(175): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select<_Ty,>(lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(175): note: see reference to function template instantiation 'void sol::stack::pusher<sol::function_sig<>,void>::select<_Ty,>(lua_State *,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(179): note: see reference to function template instantiation 'int sol::stack::pusher<sol::function_sig<>,void>::push<_Ty>(lua_State *,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(179): note: see reference to function template instantiation 'int sol::stack::pusher<sol::function_sig<>,void>::push<_Ty>(lua_State *,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(184): note: see reference to function template instantiation 'int sol::stack::push<T,_Ty,,void>(lua_State *,Arg &&)' being compiled
1>          with
1>          [
1>              T=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Arg=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(192): note: see reference to function template instantiation 'int sol::stack::pusher<sol::function_arguments<Sig,_Ty>,void>::push_func<0,sol::function_arguments<Sig,_Ty>>(std::integer_sequence<unsigned int,0>,lua_State *,FP &&)' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              FP=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(192): note: see reference to function template instantiation 'int sol::stack::pusher<sol::function_arguments<Sig,_Ty>,void>::push_func<0,sol::function_arguments<Sig,_Ty>>(std::integer_sequence<unsigned int,0>,lua_State *,FP &&)' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              FP=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types.hpp(191): note: while compiling class template member function 'int sol::stack::pusher<sol::function_arguments<Sig,_Ty>,void>::push(lua_State *,sol::function_arguments<Sig,_Ty> &&)'
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(173): note: see reference to function template instantiation 'int sol::stack::pusher<sol::function_arguments<Sig,_Ty>,void>::push(lua_State *,sol::function_arguments<Sig,_Ty> &&)' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(173): note: see reference to class template instantiation 'sol::stack::pusher<sol::function_arguments<Sig,_Ty>,void>' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_field.hpp(177): note: see reference to function template instantiation 'int sol::stack::push<_Ty,>(lua_State *,T &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              T=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(395): note: see reference to function template instantiation 'void sol::stack::field_setter<char [12],true,false,void>::set<const char(&)[12],_Ty>(lua_State *,Key,Value &&,int)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              Key=const char (&)[12],
1>              Value=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\stack_core.hpp(395): note: see reference to function template instantiation 'void sol::stack::field_setter<char [12],true,false,void>::set<const char(&)[12],_Ty>(lua_State *,Key,Value &&,int)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              Key=const char (&)[12],
1>              Value=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(97): note: see reference to function template instantiation 'void sol::stack::set_field<true,false,const char(&)[12],_Ty>(lua_State *,Key,Value &&,int)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              Key=const char (&)[12],
1>              Value=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(241): note: see reference to function template instantiation 'void sol::basic_table_core<true,sol::reference>::tuple_set<std::tuple<const char (&)[12],_Ty &&>,0>(std::integer_sequence<unsigned int,0>,Pairs &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              Pairs=std::tuple<const char (&)[12],sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>> &&>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(241): note: see reference to function template instantiation 'void sol::basic_table_core<true,sol::reference>::tuple_set<std::tuple<const char (&)[12],_Ty &&>,0>(std::integer_sequence<unsigned int,0>,Pairs &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>>,
1>              Pairs=std::tuple<const char (&)[12],sol::function_arguments<sol::function_sig<>,sol::protect_t<std::string (__cdecl *)(std::string)>> &&>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(395): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::set<const char(&)[12],sol::function_arguments<Sig,_Ty>>(const char (&)[12],sol::function_arguments<Sig,_Ty> &&)' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(395): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::set<const char(&)[12],sol::function_arguments<Sig,_Ty>>(const char (&)[12],sol::function_arguments<Sig,_Ty> &&)' being compiled
1>          with
1>          [
1>              Sig=sol::function_sig<>,
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(369): note: see reference to function template instantiation 'void sol::basic_table_core<true,sol::reference>::set_fx<_Ty,const char(&)[12],,sol::meta::enable_t::_>(sol::types<>,Key,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Key=const char (&)[12],
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\table_core.hpp(369): note: see reference to function template instantiation 'void sol::basic_table_core<true,sol::reference>::set_fx<_Ty,const char(&)[12],,sol::meta::enable_t::_>(sol::types<>,Key,Fx &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Key=const char (&)[12],
1>              Fx=sol::protect_t<std::string (__cdecl *)(std::string)>
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\state_view.hpp(425): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::set_function<const char(&)[12],_Ty>(Key,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Key=const char (&)[12]
1>          ]
1>  d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\state_view.hpp(425): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::set_function<const char(&)[12],_Ty>(Key,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=sol::protect_t<std::string (__cdecl *)(std::string)>,
1>              Key=const char (&)[12]
1>          ]
1>  d:\project\mfcapplication12\sol2\functions.cpp(37): note: see reference to function template instantiation 'sol::state_view &sol::state_view::set_function<sol::protect_t<std::string (__cdecl *)(std::string)>,const char(&)[12]>(Key,sol::protect_t<std::string (__cdecl *)(std::string)> &&)' being compiled
1>          with
1>          [
1>              Key=const char (&)[12]
1>          ]
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(32): error C2065: '()': undeclared identifier
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(33): error C2062: type 'unknown-type' unexpected
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(33): error C2238: unexpected token(s) preceding ';'
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(34): error C2062: type 'unknown-type' unexpected
1>d:\project\mfcapplication12\sol2\sol2-2.15.1\sol\function_types_stateful.hpp(34): error C2238: unexpected token(s) preceding ';'
[buildlog.txt](https://github.com/ThePhD/sol2/files/591644/buildlog.txt)

`

**Comment by ThePhD** [comment]
You are not using the latest (e.g., the code pushed some 20 minutes ago). The error of not calling `()` on a something that's not a function has already been fixed at Line 32: https://github.com/ThePhD/sol2/blob/develop/sol/function_types_stateful.hpp

Make sure you pull again.

**Comment by Phongdq** [comment]
Ok, got build success. 

But now I cant catch exception.

**Comment by ThePhD** [comment]
I'm not sure why you wouldn't be able to. Usually, the first exception gets caught... try defining a panic function, as shown here: http://sol2.readthedocs.io/en/latest/exceptions.html#typical-panic-function

**Comment by Phongdq** [comment]
I attach the image that program crash. I use the code you post and defined  SOL_CHECK_ARGUMENTS 
![exception](https://cloud.githubusercontent.com/assets/15854145/20308263/a4ed6252-ab75-11e6-88cd-a8d9057d983b.jpg)

**Comment by ThePhD** [comment]
I don't know what's different for you. It works for me. What Lua version are you using? How are you building all of this? If you continue from that code, you should hit the exception handler. What's the "err" you're receiving?

![Works for me](http://i.imgur.com/zCBBNIj.png)

**Comment by Phongdq** [comment]
I use LuaJIT version 2.0.4. 

I hit breakpoint in exception catch (sol::error& e){}. but it still crash.

**Comment by ThePhD** [comment]
I still cannot repro with LuaJIT 2.0.4 or 2.1.0:

![It works...](http://i.imgur.com/naNeh1t.png)

Try rebuilding everything -- including LuaJIT 2.0.4 -- and making sure everything matches up properly. Also try continuing past the crash, to see if it gets caught properly.

**Comment by Phongdq** [comment]
I catch exception by my panic, it does not work with default panic.
