### ISSUE TITLE
Call_constructor with initializer that takes arguments

### ISSUE THREAD

**Issue by cracyc** [ThePhD/sol2#276]
If I try to use sol::call_constructor with an initializer that takes an argument I get “sol: no matching function call takes this number of arguments and the specified types".  There's a simple workaround that I used but I was just wondering whether that is supposed to work or not.

**Comment by ThePhD** [comment]
My bad: there was a slight bug in the implementation here. It's fixed now and we have a test for it. Re-pull the latest of get it from here again: https://github.com/ThePhD/sol2/releases/tag/v2.15.1
