### ISSUE TITLE
get_or<int> ambiguous

### ISSUE THREAD

**Issue by stevetranby** [ThePhD/sol2#278]
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
```
// error: call to member function 'get_or' is ambiguous
int second_try = lua["exists"].get_or<int>(322);
// these compile OK (also char, float, and double compile OK)
short second_try2 = lua.get_or<short>("exists", 322);
short second_try3 = lua["exists"].get_or<short>(322);
```
Might be my build settings. Or XCode's clang doesn't support or conform to c++14 fully.

Also of note, the quick tutorial code (on page) seems to have a few syntax issues if copy/pasted.

**Comment by ThePhD** [comment]
That's because (unfortunately) 322 is a literal type of `int`, and so the definition conflicts. You'd either need to drop the `<int>` part or change what the type of `322` is. It's a bit of an unfortunate limitation of my code there: sorry!

Also, where are the copy-paste errors? I try to fix these things to keep the tutorial friendly and approachable.

**Comment by stevetranby** [comment]
Ah thanks. Good to know. Learn something everyday.

Just minor issues (hope this isn't annoying, might be compiler diffs):
```cpp
// missing `>` - e.g. just after int()>
bool is_it_really = function_obj.is<std::function<int()>(); // true
```

```cpp
// error, require 2 param (my guess is should have "exists" as 1st param)
// error2, ambiguous after adding "exists" as 1st param (same issue as similar)
int first_try = lua.get_or<int>( 322 );
int second_try = lua.get_or<int>( 322 );
// works
int first_try = lua.get_or( "exists", 322 );
int second_try = lua.get_or( "exists", 322 );
```

"multiple returns from lua"
```cpp
// comma, should be semicolon (or remove int)
int a; int b;
```

"multiple returns to lua"
```cpp
// missing semicolon
result2 = lua["f"](100, 200, "BARK BARK BARK!")
// comma, should be semicolon (or remove int)
int a, int b;
```
"C++ classes from C++"
```cpp
struct Doge {
        int tailwag = 50;
} // missing semicolon
```

Also, likely the same issue as I mentioned first, or of my build environment, but these error as well due to ambiguous:
```cpp
std::function<int()> a_std_function = lua["a_function"];
std::function<int(int, double, int, std::string)> stdfx = lua["f"];
```

**Comment by stevetranby** [comment]
Oh, and this run-time error (didn't catch at compile)
```cpp
// run-time error
int value = lua["value"]["value"];
// should probably be
int value = lua["some_table"]["value"];
```

**Comment by ThePhD** [comment]
Yeah, I'm not sure what's up with clang as far as the ambiguous errors go. It's really out of my control: Apple's clang often introduces ridiculous regressions in the compiler that make me quite sad: on vanilla clang, g++ and VC++, the code that says its ambiguous works just fine.

Thanks for those clerical fixes: I put every one in there and fixed a few other ones as well.
