### ISSUE TITLE
stack traceback for failed protected_function

### ISSUE THREAD

**Issue by ihamer** [ThePhD/sol2#280]
Is it possible to get a stack trace for a failed protected_function? I looked in the docs, and a bit through the code, but couldn't find a way.

**Comment by ThePhD** [comment]
We don't provide an abstraction for the thing that is present in the C API, which is [`luaL_traceback(L)`](https://www.lua.org/manual/5.3/manual.html#luaL_traceback) or, or in Lua itself, which is just [`debug.traceback()`](https://www.lua.org/manual/5.3/manual.html#6.10). Your job is to work with those yourself after registering an error handler using `protected_function`'s API: then, inside of the error handler, you will have the chance to get a traceback. I do not understand the mechanics of traceback fully, so if you figure out something that works nicely do let me know so I can consider adding it to the library in the future. A few other people talked about using luaL_traceback before, but nobody swung back around showing how they used it, and I haven't touched it in a lifetime...

**Comment by ThePhD** [comment]
I decided to add this as the default handler for `protected_function`. So now it provides a (very dumb) traceback. If you want it to be more advanced, you'll need to do what I mentioned above.

Pull the latest code or Get it here: https://github.com/ThePhD/sol2/commit/320276dabf930a9fb629ad0b7f0a99657c5e7a80
