### ISSUE TITLE
Allow bit32 library for Lua 5.3 with compatibility flags

### ISSUE THREAD

**Issue by nwhitehead** [ThePhD/sol2#282]
When building Lua 5.3 I define `LUA_COMPAT_5_2` to be able to use various modules that haven't been fully updated to 5.3 yet. In this scenario calling `open_libraries` with argument `sol::lib::bit32` does not work because of the `#if` version checks even though the library is available. I fix this for my own project by manually adjusting the version checks in `sol.hpp`, but there is probably a better way to fix this.

**Comment by ThePhD** [comment]
Probably. I'm presuming I should add a `#ifdef LUA_COMPAT_5_2` check to the bit32 library... any other libraries I should know about?

**Comment by ThePhD** [comment]
Fixed: https://github.com/ThePhD/sol2/releases/tag/v2.15.2
