### ISSUE TITLE
Memory leak in sol or wrong usage?

### ISSUE THREAD

**Issue by Strasser-Pablo** [ThePhD/sol2#284]
Hi,
I found a memory leak in sol however I'm not sure if its a wrong usage of sol.

The following code leak memory:
`#include <sol.hpp>
#include <iostream>

sol::state lua;
int main(int argc,const char* argv[]) {
    lua.script("function func() return {3} end ");
    sol::function func=lua["func"];
    sol::table a=func();
    while(true)
    {
            sol::table b=func();
            a=b;
    }
}`

The leak seem to come when affecting a non empty sol::table to another one.
Note that having a lua variable for the a variable as lua["a"] does not leak.
Does the leak come from the fact I don't use the lua stack?
I found the bug by creating torch Tensor in a loop and concanating them.

**Comment by Strasser-Pablo** [comment]
Thanks for your quick reply.
I also was thinking about dangling pointer in the assignement operator from sol2 however I don't know at all sol2 code.
Note that testing this variant of code, I only have the bug for function and table, not string nor int nor float.
`#include <sol.hpp>
#include <iostream>

sol::state lua;
int main(int argc,const char* argv[]) {
    lua.script("function func() return function() return 2 end end ");
    sol::protected_function func=lua["func"];
    sol::object a=func();
    sol::state lua2;
    while(true)
    {
            sol::object b=func();
            a=b;
    }
}

I also had no luck avoiding the leak by calling the garbage collector. 

The only workaround I found is to avoid assignement of already bound variable from c++ side and only do them by binding a lua variable to them by lua["a"]=b.
`

**Comment by ThePhD** [comment]
This is probably because to keep these objects "alive", we assign them to the Lua registry so that they get a unique reference ID (e.g., `func.registry_index();`).

I should perhaps look into why Lua isn't collecting from the registry table: when things go out of scope we call `luaL_unref`, and if its the last reference it should trigger deletion for Lua...

**Comment by ThePhD** [comment]
Fiiinally fixed this, goodness. This wasn't your fault. Copy operations (not copy constructors) were rigged...!

Get the fix here: https://github.com/ThePhD/sol2/releases/tag/v2.15.4

**Comment by ThePhD** [comment]
Thanks so much for reporting this.
