### ISSUE TITLE
xcode project include sol.hpp, compile fail for type::nil, Excepted class name and Excepted unqualified-id

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#288]
nil is the keyword for objective-c, is it matter ?
By the way, I only include sol.hpp in my file that named Node.h and source file is Node.cpp
How could I fix this error?

**Comment by ThePhD** [comment]
Can I have a more detailed log than just the title of this post? People have used sol2 and XCode successfully before, after modying their XCode flags to be set to use C++14 and such. sol2 is not meant to be included directly into objective-C code: we don't have an objective-C binding.

**Comment by aiplay** [comment]
I modify all 'nil' (include type::nil and struct nil_t) to 'luanil' can help me compile success.
Then I create a new ios application project, use sol is ok!
So this let me confused...
It looks like some settings of my work project think that there is conflict on semantics about sol nil and objective-c nil.

**Comment by ThePhD** [comment]
Wait, even `nil_t` was affected? That's.... bizarre.

If you could show me an error log or tell me all the symbols that trigger problems, I can probably make a #ifdef for all other iOS Objective-C++ users so that they don't have this problem as well.

**Comment by aiplay** [comment]
I have modified all the type::nil to type::luanil and "const nil_t nil{};" to "const nil_t luanil{};"
Also include 'stack:push(L, luanil)'  instead of 'stack:push(L, nil)' and so on.

**Comment by ThePhD** [comment]
There's a new define now that will undefine `nil` and `nil_t` on the OBJC platforms and instead present `lua_nil` and `lua_nill_t`.

Get it here: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
