### ISSUE TITLE
How to bind enum of a class??

### ISSUE THREAD

**Issue by aiplay** [ThePhD/sol2#291]
There is a enum as member of class A, how could I bind it let lua easy to use this enum?
Example Code:
``` cpp
class A
{
public:
    enum Event
    {
        BEGAN,
        MOVED,
        ENDED
    };
    // other codes
};
```

I don't want to global tables in case somewhere else use the same name table, it is best to use like this ：
``` lua
local a = A.new() -- create a 'A' instance
a.Event.BEGAN
```

OR, enum is readonly, can not modified by somewhere else.

**Comment by ThePhD** [comment]
You might be able to get away with `lua["A"].new_enum...` using [this API](http://sol2.readthedocs.io/en/latest/api/table.html#new-enum) for Sol.

If that doesn't work, you can also try just making a `sol::var( my_event_table );`, where you create a table, make it read-only, and then specify the constants BEGAN and stuff like that on that table.

I'm not sure adding explicit support for nested enums inside of a class is a thing I'll be capable of doing: you'll have to put together pieces of the library to do it. Take a look at [`var`](http://sol2.readthedocs.io/en/latest/api/var.html) to get a better idea.
