### ISSUE TITLE
coroutine from a function

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#296]
sol2 has a feature to create coroutine by the function name this way:
```cpp
sol::thread thread = sol::thread::create(lua);
sol::coroutine cr = thread.state()["test"];
cr();
```
and it works excellent.
but my need is to create coroutine from the sol::(protected_)function. like this:
```cpp
void createThread(sol::protected_function func)
{
  sol::thread thread = sol::thread::create(lua);
  sol::coroutine cr(thread.state(), func);
  cr();
}
```

i also tried to create coroutine by passing function's registry index and appropriate lua state in constructor `sol::coroutine(lua_State* L, int index)` in hope it will work. it doesn't (o rly?).
so my question is: is this possible? if yes - how? and if no - why?

**Comment by ThePhD** [comment]
`index` in all of the `reference`-derived types refers to a stack index, not a registry index.

I've been having issues with working with the registry easily too, so I'm trying to figure out a good API I can add to all the types for it, since it came up in #281 and for working with the main thread and such in Lua. It will take me a bit of time to handle properly.

**Comment by THE-FYP** [comment]
registry api will be great, but my question was how to create coroutine from a function - it doesn't matter with registry or not. i just looking for any solution that will work, and atm i have no idea how it can be done.

sorry for the wrong explanation.

**Comment by ThePhD** [comment]
`coroutine` doesn't have a constructor for this (yet). The way to do it right now would be:

````
sol::function f = ....;
f.push();
sol::coroutine cr = sol::stack::pop<sol::coroutine>(lua);
````

This is not ideal, however, for several reasons. I'll be working on this today, though, so maybe I can give you good news soon...

**Comment by ThePhD** [comment]
The code you want is there now, pull from the latest. It'd look like...

`sol::coroutine cr(thread.state(), sol::ref_index(pf.registry_index()));` or
`sol::coroutine cr(thread.state(), pf);`

The first is more explicit and will probably invoke less overload resolution headaches in the long run.
