### ISSUE TITLE
Delete unnamed table

### ISSUE THREAD

**Issue by talybin** [ThePhD/sol2#297]
This is not really an issue, more like asking for help. I'm pretty new to Lua binding and got stuck on, I'm sure, pretty simple thing. I'm trying to use Lua for various events passing optional userdata in between. The instance created/deleted outside Lua script and various events calling Lua functions. I do it this way:

C code:
```c++
sol::state lua;

class test {
public:
  test() { tbl = lua.create_table(); }
  ~test() {
    // remove userdata table ???
  }
  void on_event1() {
    // calling lua["on_event1"](this) ...
  }
  void on_event2() {
    // calling lua["on_event2"](this) ...
  }

  sol::table tbl;
};

void main() {
  lua.open_libraries();
  lua.script_file("test.lua");
  lua.new_usertype<test>("test",
    "userdata", &test::tbl
  );
  // run event pool creating/deleting several instances of test class
  ...
}
```

Lua code:
```lua
on_event1 = function (ev)
  ev.userdata = { somestate = "whatever" }
end
on_event2 = function (ev)
  print(ev.userdata.somestate)
end
```
I don't really want to name userdata table because I will have several instances at the same time and need, I guess, some unique name in this case. Is there a way to remove table created in constructor on test destruction? Or maybe there is a better solution?

**Comment by ThePhD** [comment]
The destructor for `sol::table` will de-reference that table you created and remove it from the registry (if it's the last reference).

There's no manual work required on your end at all: Lua will collect it in one of its next garbage collection sweep, or you can force garbage collection (in Lua using `collectgarbage()`, in C using `lua_gc( ... )`, and with sol2 using `my_state(_view).collect_garbage()` -- the last one is a function added to latest).

As a side note (semi-related to this if you do start naming things): if you name something, you can remove that name-value association with `name = nil` in Lua land or `lua["name"] = sol::luanil;` in C++ and sol2 land.

**Comment by talybin** [comment]
Good explained! Thank you!
