### ISSUE TITLE
-Wconversion not disabled in the single-header

### ISSUE THREAD

**Issue by jaredgrubb** [ThePhD/sol2#298]
Looks like maybe the single-header builder doesnt propagate the global "disable -Wconversion" patch correctly.

**Comment by ThePhD** [comment]
I'm not sure what you mean? Does it warn on things that it shouldn't?

**Comment by ThePhD** [comment]
Ah, sorry. I found out what was wrong, thanks for bringing it to my attention. Pull the latest or get the single header here:

https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
