### ISSUE TITLE
Unaligned memory access in optional_base

### ISSUE THREAD

**Issue by crsib** [ThePhD/sol2#299]
Currently optional_base<T> is defined like:

```c++
template <class T>
struct optional_base
{
	bool init_;
	char storage_[sizeof(T)];
        ...
};
```

This generally prevents the compiler from aligning the storage_ to the optimal alignment. While on x86 it results only in a performance penalty, which is not a problem in this part of the code, on other architectures aligned reads are critical and the code above relays on compiler ability to correctly generate the code for the memory access. This is currently broken, at least, in Emscripten (and probably on the ARM backend of Clang as well, but I had no chance to check it yet).

While the problem is definitely in the compiler backend, I guess it would be easier and quicker to patch it in the library. As a workaround we currently use the following definition:

```c++
template <class T>
struct optional_base
{
	union
	{
		size_t __;
		char storage_[sizeof(T)];
	};

	bool init_;
       ...
};
```

It works for us, but probably is not generic enough and I yet have not tested it on MSVC compiler.

**Comment by ThePhD** [comment]
Generally `std::size_t` is the width of the typical native word (x86 would be 32-bit, x64 would be 64-bit), so adding that in would probably make the compiler align things up properly.

I'll be sure to add this in ASAP and push it...

**Comment by ThePhD** [comment]
I wonder if the following would work out on your platform: 

````
template <class T>
struct optional_base
{
	char storage_[sizeof(T)];
	std::size_t init_;
       ...
};
````

It won't be optimally small in cases where the size of T is something like 3 or 2 or 1, but... well. That's the price to pay for speed, I guess?

**Comment by ThePhD** [comment]
I've added the `alignas` specifier, which from some basic testing suggests things get aligned to proper word or word-divisible boundaries and sizes. Get it here:

https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
