### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#3]
Despite examples and tests, we need it.

**Comment by ThePhD** [comment]
Sphinx looks like where we're going for docs, coupled with rtfd.org

**Comment by ThePhD** [comment]
Got it done: http://sol2.readthedocs.org/en/latest/

**Comment by Nava2** [comment]
Oddly, a lot of the links are broken in the docs. :cry: 

They look good, though. Also, there's no links on the left for some of the pages, e.g. exceptions.

**Comment by ThePhD** [comment]
Yeah, I'm still getting used to Sphinx. Shit's hard, yo.

**Comment by Nava2** [comment]
:smile: Learning new things.
