### ISSUE TITLE
Linker error on VS2015 when Lua is compiled as C++

### ISSUE THREAD

**Issue by zvrba** [ThePhD/sol2#306]
I have compiled all of Lua as C++ code by specifying the /TP compiler flag in order to use C++ exceptions instead of setjmp/longjmp. Compiling as C++ applies name mangling to symbols. When using Sol, I got a lot of undefined references to Lua functions during linking. I have traced this to Sol including `<lua.hpp>`; this header wraps Lua includes in `extern "C"`, which disables name mangling, causing linker errors.

I have fixed this by the following simple patch to Sol:

```
-#include <lua.hpp>
+#include <lua.h>
+#include <lualib.h>
+#include <lauxlib.h>
```

**Comment by ThePhD** [comment]
A better fix would probably be:

````
#ifdef SOL_CXX_LUA
#include <lua.h>
#include <lualib.h>
#include <luaxlib.h>
#else
#include <lua.hpp>
#endif // C++-compiler Lua
````

But yeah, that's a good idea. Thanks for sharing!

**Comment by ThePhD** [comment]
Fixed. The define is going to officially be `SOL_USING_CXX_LUA`, documented here: http://sol2.readthedocs.io/en/latest/errors.html#linker-errors

Get it here: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
