### ISSUE TITLE
Seg fault when calling .new_usertype

### ISSUE THREAD

**Issue by hdt80** [ThePhD/sol2#307]
Sadly I cannot get simple test case to showcase this issue, and I've tried for a while to reproduce this bug, but it seems to be specific to something my code is doing. 

When calling `.new_usertype` on an object I get the following error: http://pastebin.com/B9csA8Gm

The code is question is: 

```
void LuaScript::defineObject(sol::state& lua) {
	lua.new_usertype<Object> (
		"Object", sol::constructors<
				sol::types<Map*, float, float, Stats, int>>(),
		"getX", &Object::getX,
		"getY", &Object::getY,
		// Object methods
		"contains", &Object::contains,
		"applyStat", &Object::applyStat,
		"setStats", &Object::setStats,
		"getSpeed", &Object::getSpeed,
		"getRange", &Object::getRange,
		"setRange", &Object::setRange
	);
}
```

`LuaScript::defineObject(sol::state& lua)` is called from `LuaScript::defineClasses(sol::state& lua)`:

```
void LuaScript::defineClasses(sol::state& lua) {
	defineObject(lua);
	defineEnemy(lua);
	defineTarget(lua);
	defineMap(lua);
	defineStats(lua);
	definePerk(lua);
}
```

`LuaScript::defineClasses` is a static method called by the constructor of a Console:

```
Console::Console()
	: _cursorPos(0) {

	_lua.open_libraries(sol::lib::base, sol::lib::package, sol::lib::table);

	LuaScript::defineClasses(_lua);

	-- snip --
}
```

Commenting out `LuaScript::defineClasses(_lua);` in Console makes the seg fault go away, but `LuaScript::defineClasses` is still called from other locations, and doesn't cause a seg fault when its called from other places. 

The program used to create this bug can be found here: https://github.com/hdt80/Augmentum/tree/bug. 

This happens on both my Windows (using MinGW g++) and Linux machines (Using both g++ and clang++).

### Other info
sol version: Most recent (2.15 - `010b6bb`)
Windows compiler: `g++ (x86_64-posix-seh, Built by MinGW-W64 project) 6.1.0`
Linux compiler: `g++ (GCC) 6.2.1 20160830` and `clang++ clang version 3.9.0`
Lua: `5.3.3` (Version number `503`) 

If there is any other information I could provide let me know and I'll get back to you as soon as possible. 

Thanks for your help!

**Comment by ThePhD** [comment]
Because I have to essentially pull and figure out how to build Augmentum, this is going to take me a while to do and I probably won't get around to it in my usual 24-hour turn-around time.

**Comment by hdt80** [comment]
Understandable, thank you for being willing to do that. If there's anything I can help with let me know.

**Comment by hdt80** [comment]
I believe this happens due to the [static initialization order fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order). By refactoring my code to use the `Construct on First Use Idiom` I'm able to get rid of the seg fault happening. Thanks you for being willing to help me!
