### ISSUE TITLE
maybe a bug for variadic_args?

### ISSUE THREAD

**Issue by juncy** [ThePhD/sol2#310]
Hi, I try to use variadic_args with template:

![1](https://cloud.githubusercontent.com/assets/3078809/21763715/42c6a912-d69a-11e6-933b-e8ac6ba7fb97.PNG)

I got an runtime error when `ssl.test(1, 2, 3)`, the code seems ok for only one input value.
![2](https://cloud.githubusercontent.com/assets/3078809/21763770/895b2f6a-d69a-11e6-8d02-85a8fbf42edd.PNG)

Thanks for your response.

**Comment by juncy** [comment]
I also try to define two overload functions without using template, the error still the same, I suppose the problem may between variadic_args and the overload method.

**Comment by ThePhD** [comment]
Yeah, `variadic_args` doesn't play nice with `overload` because we don't do full overload ranking. We only do first-come-first-serve overloading. This isn't something I can really support in the current scheme without absolutely destroying the performance of runtime overload ranking.

**Comment by ThePhD** [comment]
Put a tiny little hack in that makes this work, for the most basic cases. Pull from the latest to get the fix.

Truly, be careful when working with this, however: I'm not committing to full-on runtime overload resolution, so this fix is tentative and hacky at best...!
