### ISSUE TITLE
Unable to recieve sol::table as argument to call constructor

### ISSUE THREAD

**Issue by Nomadluap** [ThePhD/sol2#311]
I'm currently using sol to wrap the Eigen matrix class, and I wan to make a call constructor to create matricies using the syntax such as `m = mat{{1, 0},{0, 1}}` to create the 2x2 identity matrix.

To that end, my usertype definition looks like, 
```
lua.new_usertype<MatrixXf>("mat"
, sol::call_constructor, &from_lua_table
/* more member functions defined that work as desired */
);
```
and `from_lua_table `has definition
```
MatrixXf from_lua_table(sol::table t)
{
    size_t cols = t.size();
    for(int i = 1; i <= cols; i++)
        /* use sub-tables as rows in matrix */
}
```

When I query `t.size()`, I always get zero, and any attempts to retreive a value from t cause the lua error
```
sol: attempt to index (get) lua_nil value "(unknown)" on userdata (bad (misspelled?) key name or does not exist)
stack traceback:
        [C]: in ?
        [C]: in function 'mat'
        stdin:1: in main chunk
        [C]: in ?
```
However, changing `from_lua_table` return type to void and binding it as a free function makes `t.size()` work as intended, producing the correct table size.

**Comment by Nomadluap** [comment]
Upon further inspection, my table returns `t.empty() == false` and evaluating
```
	t.for_each([](sol::object& key, sol::object& val)
	{
		cout << "k: " << (key.is<string>()) ? key.as<string>() : std::to_string(key.as<float>()) << endl;
	});
```
gives `k:true` for multiple entries

Also, when binding the factory to a non-constructor function like "from", everything works as expected.

**Comment by ThePhD** [comment]
As a temporary fix, wrap the function with `sol::factories`, like: `sol::call_constructor, sol::factories( &from_lua_table )`.

This is actually what is intended, but it would probably be nice if it worked both ways...

**Comment by ThePhD** [comment]
Fixed. Your code should work as-is, now: pull from latest.
