### ISSUE TITLE
can't use 'bitwise_and' binding.

### ISSUE THREAD

**Issue by juncy** [ThePhD/sol2#313]
I can use + - * / ^bindings, but failed at using `&` `|`.

On lua side, I got the rumtime error such as `lua: error: seq_block.lua:11: attempt to perform bitwise operation on ... `. Maybe it was not registered. Thanks for your help.

**Comment by ThePhD** [comment]
Medical exams. Will have to respond / look into later.

**Comment by juncy** [comment]
Good luck with your exams!

I am trying to describe my problem more clearly. 

I would like define a simple grammar as follows:
`seq{rf90, delay#, acq}` or `seq{rf90, delay*, acq}` or  `seq{rf90, *delay, acq}`

in which `delay` may be a table array of objects,  and `#` or `*` means do the ` seq{rf90, delay[i], acq}`  for  `#delay` times.

Its explicit call is 
`for i =1, #delay do`
`seq{rf90, delay[i], acq}`
`end`

It seems that we may need to define a special syntactic sugar?  I'd like to use  `#` or `*`  to keep user in mind that it means loop.  Maybe it now has nothing to do with Sol, but I am still looking forwards to your suggestions. Thanks.

**Comment by ThePhD** [comment]
You will probably have to define syntactic sugar or look into a newly released bit of Lua that allows you to hack a little bit on Lua's grammar and define your own sugar and other useful syntax things.

They have something for doing that here, where you can spit out tokens defining new and fun things: [ltokenp](http://lua-users.org/lists/lua-l/2016-05/msg00028.html).
