### ISSUE TITLE
Still Incompatible with UE4 4.14 (VS2015)

### ISSUE THREAD

**Issue by baddestagate414** [ThePhD/sol2#317]
I keep getting these linker errors whenever i declare a sol::state instance:

`1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_close referenced in function "public: __cdecl sol::state::state(int (__cdecl*)(struct lua_State *))" (??0state@sol@@QEAA@P6AHPEAUlua_State@@@Z@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_atpanic referenced in function "public: __cdecl sol::state::state(int (__cdecl*)(struct lua_State *))" (??0state@sol@@QEAA@P6AHPEAUlua_State@@@Z@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_settop referenced in function "int __cdecl sol::default_at_panic(struct lua_State *)" (?default_at_panic@sol@@YAHPEAUlua_State@@@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_pushvalue referenced in function "public: __cdecl sol::basic_table_core<0,class sol::reference>::basic_table_core<0,class sol::reference>(struct lua_State *,int)" (??0?$basic_table_core@$0A@Vreference@sol@@@sol@@QEAA@PEAUlua_State@@H@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_tolstring referenced in function "int __cdecl sol::default_at_panic(struct lua_State *)" (?default_at_panic@sol@@YAHPEAUlua_State@@@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_pushstring referenced in function __catch$??$trampoline@AEAP6AHPEAUlua_State@@@Z$$V@detail@sol@@YAHPEAUlua_State@@AEAP6AH0@Z@Z$0
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_rawgeti referenced in function "private: __cdecl sol::basic_table_core<1,class sol::reference>::basic_table_core<1,class sol::reference>(struct lua_State *,struct sol::detail::global_tag)" (??0?$basic_table_core@$00Vreference@sol@@@sol@@AEAA@PEAUlua_State@@Uglobal_tag@detail@1@@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol lua_error referenced in function "int __cdecl sol::detail::trampoline<int (__cdecl*&)(struct lua_State *)>(struct lua_State *,int (__cdecl*&)(struct lua_State *))" (??$trampoline@AEAP6AHPEAUlua_State@@@Z$$V@detail@sol@@YAHPEAUlua_State@@AEAP6AH0@Z@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol luaL_ref referenced in function "private: __cdecl sol::basic_table_core<1,class sol::reference>::basic_table_core<1,class sol::reference>(struct lua_State *,struct sol::detail::global_tag)" (??0?$basic_table_core@$00Vreference@sol@@@sol@@AEAA@PEAUlua_State@@Uglobal_tag@detail@1@@Z)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol luaL_unref referenced in function "public: __cdecl sol::basic_table_core<1,class sol::reference>::~basic_table_core<1,class sol::reference>(void)" (??1?$basic_table_core@$00Vreference@sol@@@sol@@QEAA@XZ)
1>LuaSol_TestPawn.cpp.obj : error LNK2019: unresolved external symbol luaL_newstate referenced in function "public: __cdecl sol::state::state(int (__cdecl*)(struct lua_State *))" (??0state@sol@@QEAA@P6AHPEAUlua_State@@@Z@Z)`

any idea why?

**Comment by ThePhD** [comment]
How does Unreal build Lua? In C++ mode? It might be looking for the C++ version of these function calls, but Sol has an expectation that it'll be C. Make sure you're using the latest and see: http://sol2.readthedocs.io/en/latest/errors.html#linker-errors

**Comment by baddestagate414** [comment]
Unreal cannot be used with only C code so yes C++ mode. 
sol is using ```lua.hpp``` header with the ```extern "C"``` directive

i'm using the latest versions of Lua, Sol2 and Unreal.

**Comment by ThePhD** [comment]
From the docs page:

> However, when the target Lua library is compiled with C++, one must change the calling convention and name mangling scheme by getting rid of the extern 'C' block. This can be achieved by adding `#define SOL_USING_CXX_LUA` before including sol2, or by adding it to your compilation’s command line.

Add `SOL_USING_CXX_LUA` before sol2, or add it to your commandline: this should make it work in C++ mode.

I'll probably add this to a separate "config" page later at some point.
