### ISSUE TITLE
Panic when using the same C++ type for different Lua classes.

### ISSUE THREAD

**Issue by Tobger** [ThePhD/sol2#319]
This code panics [here](https://github.com/ThePhD/sol2/blob/66ad18979706a6396bc67424e9e35e5262d60061/single/sol/sol.hpp#L12829):

```
#include "sol.hpp"
int main() {
	sol::state lua;
	lua.script(R"(
function run()
   local plot2d = ui.plot2d.new()
   plot2d:add(1, 2)
   local plot3d = ui.plot3d.new()
   plot3d:add(1, 2, 3)
end)");

	struct LuaPlot {
		void add_point_2D(double x, double y) {}
		void add_point_3D(double x, double y, double z) {}
	};

	auto ui_table = lua.create_named_table("ui");
	ui_table.new_usertype<LuaPlot>("plot2d", "add", &LuaPlot::add_point_2D);
	ui_table.new_usertype<LuaPlot>("plot3d", "add", &LuaPlot::add_point_3D);
	lua["run"]();
}
```
Adding `plot3d.add` seems to overwrite `plot2d.add`, even though they are different classes.
Is there a way to reuse the same C++ type for different Lua classes or is this just not supported?

**Comment by ThePhD** [comment]
This scenario is not supported. Use a strong type definition by subclassing LuaPlot into Plot2D and Plot3D, or combine the classes and use overloading to select the right point.

I've tried to add this feature in the past, but it only resulted in quite the headache for implementation and created a number of problems for seamlessly handling usertypes. Strongly-type your classes in C++ with the methods you need (e.g., __publically__ subclass LuaPlot into plot2D and plot3D and then bind those) and then bind those: it's easier, faster, and a lot less finnicky.
