### ISSUE TITLE
Tables with properties inside usertypes

### ISSUE THREAD

**Issue by emanuel15** [ThePhD/sol2#321]
Is it possible to add tables as they were just namespaces with properties? Ex:
`local player = Player.new("player name", 100, 100) -- x, y`
`print(player.name)`
`print(player.pos.x)`
`print(player.pos.y)`
So pos.x and pos.y would call getters or setters depending of the situation
`player.pos.y = 200 -- call c++ setter`

**Comment by Nomadluap** [comment]
I believe as long as you bind the underlying struct of the pos (eg as a vec2 or something), then it will be accessible through lua just as your player class.

**Comment by emanuel15** [comment]
Thank you, I got it working with [metatable_key](http://sol2.readthedocs.io/en/latest/api/metatable_key.html) =)
