### ISSUE TITLE
Compiler is out of heap space when registering large amount of functions

### ISSUE THREAD

**Issue by cafebabe0** [ThePhD/sol2#329]
I have about 5000 functions that i have to expose to lua, basically i wrote a generator to do that for me like that:

```
lua.set_function("func", func);
...
```
When im trying to compile it it takes 4gb of memory and then it fails with 
![](http://i.imgur.com/1mETXUd.png)

I tried splitting functions to separate .cpp files 500 in each and then it works, but is there other solution to that?

**Comment by OrfeasZ** [comment]
I have a similar issue, but I've worked around it by using the x64 toolset (this doesn't mean compiling an x64 binary, it just means that the compiler itself is the 64-bit version). This allows the compiler and linker to utilize more than 4GB of RAM.

There's multiple ways to use the x64 MSVC toolset, but the method I'm using is just setting the `PreferredToolArchitecture` environment variable value to `x64`.

You could also add the following under the `<Import .../>` statement in your `.vcxproj` file to use the x64 toolset only on a specific project:
```xml
<PropertyGroup>
    <PreferredToolArchitecture>x64</PreferredToolArchitecture>
</PropertyGroup>
```

**Comment by cafebabe0** [comment]
@OrfeasZ Now it takes 8gb but actually compiles. Thank you!

**Comment by OrfeasZ** [comment]
@cafebabe0 Glad to be able to help :)
