### ISSUE TITLE
Function is not inline or constant is not static.

### ISSUE THREAD

**Issue by Remotion** [ThePhD/sol2#33]
This prevent from using SOL2 in different *.cpp files.

inline free_function_cleanup

static const auto& base_class_check_key
static const auto& base_class_cast_key

**Comment by ThePhD** [comment]
Ah, these usually escape once in a while when I'm not looking. I think I'm going to split the tests into multiple files, just so I can more easily avoid this problem.

**Comment by ThePhD** [comment]
Fixed!
