### ISSUE TITLE
error C2665: 'sol::usertype_detail::is_indexer': none of the 4 overloads could convert all the argument types

### ISSUE THREAD

**Issue by black13** [ThePhD/sol2#330]
#include "sol.hpp"

int main()
{
	struct bark {
		int var = 50;
	};
	struct woof {
		bark b;
	};

	struct nested {
		const int f = 25;
	};

	struct outer {
		nested n;
	};

	sol::state lua;
	lua.new_usertype<woof>("woof",
		"b", &woof::b);
	lua.new_usertype<bark>("bark",
		"var", &bark::var);
	lua.new_usertype<outer>("outer",
		"n", &outer::n);
	lua.set("w", woof());
	lua.set("n", nested());
	lua.set("o", outer());
	lua.set("f", sol::c_call<decltype(&nested::f), &nested::f>); //issue
	lua.script(R"(
    x = w.b
    x.var = 20
    val = w.b.var == x.var
    v = f(n);
    )");

	woof& w = lua["w"];
	bark& x = lua["x"];
	nested& n = lua["n"];
	int v = lua["v"];
	bool val = lua["val"];

	return 0;
}

**Comment by ThePhD** [comment]
Given the error code (C2665), I am guessing this is Visual Studio 2015. I cannot repro on my machine, using Visual Studio 2015, latest update.

Do you have anymore information that can help me narrow this down?

**Comment by ThePhD** [comment]
I'm going to close this, since your code works exactly as advertised (copy-pasted into a .cpp file and compiled from both the command line and within Visual Studio itself).

If you have any more information, please do let me know.

**Comment by black13** [comment]
Understood.
