### ISSUE TITLE
Ability to search in documentation

### ISSUE THREAD

**Issue by traplol** [ThePhD/sol2#331]
Unless I have been missing something, it would be very nice to be able to search for terms in the documentation.

I've been using sol2 for about a week now and it works great. My only problem has been when I read something in the documentation and at some point later I remember reading about that thing but I cannot remember _where_ in the docs that was.

**Comment by traplol** [comment]
I just realized that http://sol2.readthedocs.io/en/latest/search.html exists, could that be made more visible or more accessible? For instance, put that at the top of each page of the documentation

**Comment by ThePhD** [comment]
Yeah, I need to choose a better theme or customize it, but documentation customization is not my fortre.

**Comment by ThePhD** [comment]
To anyone who's reading this: if you need a good Sphinx Theme I can choose that makes search easier, or have some information about how to customize a Sphinx theme, I could use that help.

**Comment by ThePhD** [comment]
Praise be to @OrfeasZ !
