### ISSUE TITLE
Usertype as module

### ISSUE THREAD

**Issue by Reewr** [ThePhD/sol2#332]
First off, thanks for creating and maintaining this library. Brilliant work.

I've been using this library as a part of the game engine that I'm making. In it, I'd like to expose a Lua API which should contain as few global variables as possible. I found the `require` functions that made this possible and they are almost perfect.

The only issue I have is that there doesn't seem to be a way to return usertypes instead of tables when using `require`. 

Example:

```cpp
struct some_class {
  some_class(int i) { bark = i; }
  int bark;
}

sol::table open_mylib(sol::this_state state) {
  sol::constructors<sol::types<int>> ctor;
  sol::usertype<some_class> s(ctor, "bark" &some_class::bark);
  
  sol::state_view lua(state);
  sol::table module = lua.create_table();
  module.set_usertype("some_class", s);

  return module;
}

int main(int, char**) {
  sol::state lua;
  
  lua.open_libraries(sol::lib::base, sol::lib::package);
  lua.require("my_lib", sol::c_call<decltype(&open_mylib), &open_mylib>, false);
}
```

With the example above, `some_class` is added to the table as `some_class`. In order to use it in Lua, you'll need to do the following:

```lua
local module = require 'my_lib'

module.some_class.new(5)
```

When ideally, what I want to do is this:

```lua
local some_class = require 'my_lib'

some_class.new(5)
```

I already know of a few work arounds to get this behaviour, but those methods aren't all that ideal. First one includes exposing a `new` function and the second one includes injecting Lua to return the usertype from that module only. 

Perhaps you have some suggestions on how I could do this?

**Comment by ThePhD** [comment]
`local some_class = module.some_class;`, as a quick and dirty.

Or just... return the usertype directly, which I believe should work. I've never really tried some semantics like that, and I'm honestly not too sure if it's a good idea.

**Comment by Reewr** [comment]
My reasoning for wanting to do is so that the usertypes doesn't clutter the global namespace but also so that they're convenient to use when needed.

>  Or just... return the usertype directly, which I believe should work. I've never really tried some semantics like that, and I'm honestly not too sure if it's a good idea.

I've tested what you suggested, as shown in the example below.

```cpp
#include <sol.hpp>
#include <assert.h>

// Very basic structure just with some more properties
// to test properly
struct Text {
  Text(float x, float y, std::string text) : x(x), y(y), text(text) {}
  float x;
  float y;
  std::string text;

  void draw() {}
};

// Create the library when requested, only returning the newly
// created usertype
sol::table openText(sol::this_state state) {
  sol::constructors<sol::types<float, float, std::string>> ctor;
  sol::usertype<Text> s(ctor,
    "x", &Text::x,
    "y", &Text::y,
    "text", &Text::text,
    "draw", &Text::draw);

  sol::state_view lua(state);
  sol::table module = lua.create_table();

  module.set_usertype("Text", s);

  return module["Text"];
}

int main(int, char**) {
  sol::state lua;

  lua.open_libraries(sol::lib::base, sol::lib::package);
  lua.require("Text", sol::c_call<decltype(&openText), &openText>, false);

  lua.script(R"(
local Text = require 'Text'

-- Make it global just for testing
foo = Text.new(512.0, 512.0, 'Bar')
  )");

  Text t = lua["foo"];
  assert(t.x == 512.0);
  assert(t.y == 512.0);
  assert(t.text == "Bar");

  return 0;
}
```

This works perfectly and is exactly what I wanted. I'm curious as to why you think this not a good idea though. Do you mind elaborating?

**Comment by ThePhD** [comment]
Inflexibility might be the biggest reason, really. If you return a usertype but, one day, want to do more than import a single "class type"... well. That's a lot of code you'll have to change to accommodate that?

It was really just a musing: since it seems to work well enough, you might as well go for it! Plus, you can always register additional static functions on the usertype if necessary, so it can still be extended. I just don't know if there's any situations where the table -- the conventional return type -- would handle some cases better.

If anything trips you up in the future, do let me know.

**Comment by Reewr** [comment]
Just as a side effect of this, I found out you can also just keep adding things to the usertype after it's been declared on a table. For instance, if I also want enums on the usertype, I can just do the following:

```cpp
// continuing from the example above inside openText
sol::state_view lua(state);
sol::table module = lua.create_table();

module.set_usertype("Text", s);
sol::table text = module["Text"];
text.create_named("Color", "Red", Text::RED);

return text;
```
You can even add new usertypes on the usertype, which was kind of neat. 

Thanks for the help!
