### ISSUE TITLE
Creating Shared Object for C++ classes using sol2

### ISSUE THREAD

**Issue by taobian89** [ThePhD/sol2#333]
Hi:

First, I’d like to thank you for writing this library. I am a PhD student trying to implement this library in a research project. I already have a C++ library, and am planning to generate a .so file using sol2, so that it can be directly imported and used in lua scripts. I know how to do this using lua’s default C API for some simple C functions/structures, but still couldn’t figure out how to do this using sol2. 

For example, I found the following C code from http://www.troubleshooters.com/codecorn/lua/lua_lua_calls_c.htm

```

//-----------------------------hellofunc.c----------------------------

#include <lua.h>                               /* Always include this */
#include <lauxlib.h>                           /* Always include this */
#include <lualib.h>                            /* Always include this */


static int isquare(lua_State *L){              /* Internal name of func */
	float rtrn = lua_tonumber(L, -1);      /* Get the single number arg */
	printf("Top of square(), nbr=%f\n",rtrn);
	lua_pushnumber(L,rtrn*rtrn);           /* Push the return */
	return 1;                              /* One return value */
}
static int icube(lua_State *L){                /* Internal name of func */
	float rtrn = lua_tonumber(L, -1);      /* Get the single number arg */
	printf("Top of cube(), number=%f\n",rtrn);
	lua_pushnumber(L,rtrn*rtrn*rtrn);      /* Push the return */
	return 1;                              /* One return value */
}

int luaopen_power(lua_State *L){
	lua_register(
			L,               /* Lua state variable */
			"square",        /* func name as known in Lua */
			isquare          /* func name in this file */
			);  
	lua_register(L,"cube",icube);
	return 0;
}
```

Then, I can compile the .so file using 

`gcc -Wall -shared -fPIC -o power.so -I/usr/include/lua5.1 -llua5.1 hellofunc.c
`

power.so can then be imported in lua interpreter via `require()`

I have searched through the document of sol2 and googled it online. But it is still not clear to me how to compile the .so file using sol. I wonder if you could provide a simple example on compiling the .so library for C++ classes using sol? Thanks!

**Comment by ThePhD** [comment]
Importing shared libraries is not something explicitly under sol2's control and is outside the scope of the project. The way the Lua interpreter pulls in files is very different from the way the Lua C API searches paths and tries to stitch together files: sol2 doesn't handle or deal with that because it's specific to the C API and C's defacto ABI on each platform.

There is no portable or easy way for me to handle this, other than writing a C function importer. And that's not something I have the time or energy to commit to.

**Comment by ThePhD** [comment]
As a side note, you could simply compile your `power.so` or whatever other Shared Object and then link it in directly to your C++ application, assuming you have control of compiling the C++ application. Then, you can just use whatever tools gcc/clang/VC++ have for accessing and calling shared object functions, which is usually the typical build the library, have the shared object file available, and then link against the `.lib` and include headers.

**Comment by taobian89** [comment]
Thank you for your kind reply! Maybe I didn't make myself clear. Suppose I have the following code using sol2 in a .cpp file:

```
struct player {
		player(){std::cout << "test" << std::endl;}
};


int main(){
	sol::state lua;
	lua.new_usertype<player>( "player",sol::constructors<sol::types<>>());
	lua.script( "p=player.new()");
	return 0;
}
```
I can compile the .cpp file using 

`g++ -std=c++14  test.cpp -I /usr/local/include -L /usr/local/lib -llua 
`

But I have to run the lua script from the `main()` function. Is it possible to do something like this

```
require("player")
p=player.new()
```
in the lua interpreter?


I tried to write the .cpp in the following way:

```
struct player {
		player(){std::cout << "test" << std::endl;}
};

int luaopen_player(lua_State* L ) {
        sol::state_view lua(L);
        lua.new_usertype<player>( "player",sol::constructors<sol::types<>>());
        return 0;
}
```
and compile the .so file like 

`g++ -std=c++14  -Wall -shared -fPIC -o player.so -I /usr/local/include -L /usr/local/lib -llua test.cpp 
`

But it doesn't work.

**Comment by irondoge** [comment]
Your code is working, you are juste missing `extern "C"` before your function name. It is because C and C++ do not encore symbols the same way into the binary object.

Here is the code I tried:
```cpp
#include <iostream>
#include <sol.hpp>

struct player {
  player() {
    std::cout << "test" << std::endl;
  }
};

extern "C" int luaopen_player(lua_State* L ) {
  sol::state_view lua(L);
  lua.new_usertype<player>("player", sol::constructors<sol::types<>>());
  return (0);
}
```
With the following compilation line: `g++ player.cpp -llua -shared -fpic -o player.so`
