### ISSUE TITLE
An unexpected error occurred and forced the lua state to call atpanic

### ISSUE THREAD

**Issue by R23MJ** [ThePhD/sol2#334]
I am making a simple dice rolling dilly, and when I try to call the roll function from Lua, the program shits itself. The error I get is the title. Here is my code reproducing the problem. A little info: Lua5.3 static linked. VS15, and I'm using the newest version of the single header version of Sol2. I followed the tutorials as closely as I could, so idk if this is a bug or what.

    sol::state Lua;
	Lua.open_libraries(sol::lib::base);

	//Dice usertype

	Lua.new_usertype<Player>("Player", sol::constructors<sol::types<std::string>>(),
		"getDiceFace", &Player::getDiceValue,
		"rollDice", &Player::rollDice,
		"giveDice", &Player::giveDice,
		"takeDice", &Player::takeDice
		);

	//Another usertype

	//Another irrelevant usertype

	Lua["LocalPlayer"] = Player("Local Player");
	Player& LocalPlayer = Lua["LocalPlayer"];

	LocalPlayer.giveDice();

	std::string script = R"(
		localPlayer:rollDice(1)
	)";

	Lua.script(script);
	std::cout << LocalPlayer.getDiceValue(1) << std::endl;

	system("PAUSE"); //Bad, don't do this

I thought the functions might be producing the problem, so I commented out the insides, they literally do nothing and it still errors. Hopefully I just missed something really obvious. Any help would be appreciated.

EDIT: Actually, one function does work, only giveDice(). The other functions cause the crash
EDIT2: When I debug build, I am getting the 'pudata is nullptr' error, but as from the code, you can see I am clearly using ':' not '.' I also get this error when using '.new()'

**Comment by ThePhD** [comment]
You mispelled the name of the variable.

`Lua["LocalPlayer"] = Player("Local Player");`
versus
`localPlayer:rollDice(1);`

> "LocalPlayer"
compared to
> localPlayer

(You have an uncapitalized letter.)

You should establish a consistent naming scheme and not switch based on what you're doing. I recommend that all your variables be lower case / snake case, and your class names continue to be uppercase. That will help you immediately spot problems like this.

**Comment by R23MJ** [comment]
Thank you, I found that just a few minutes ago also. I usually use camelCase, it was a silly mistake. Thank for Sol2 btw. Love this library, it's amazing.
