### ISSUE TITLE
lua environment is destroyed before sol::state_view and sol::table causes crash during destruction 

### ISSUE THREAD

**Issue by Mark-Joy** [ThePhD/sol2#335]
Hello,

I got into situation where lua environment is destroyed before sol::state_view and sol::table.
It causes my app crashes during the destruction of sol::state_view and sol::table. It took me almost a week to find out.

Is this behavior expected?

**Comment by ThePhD** [comment]
Yes.

`sol::state_view` requires that you keep the state that it's viewing alive. `sol::table` references an existing table within the Lua state. If you destroy the Lua state, then these things all die.

Consider moving the Lua environment construction up one level, to avoid having its destructor called before anything that relies on it.

**Comment by Mark-Joy** [comment]
Thank you for the answer.
Well, I can't do that because lua enviroment is not constructed in my C++ app.
Here is my situation

All of the below live in same processID:
- Lua app has Lua_Env1 and Lua_Env2
- Lua_Env1 call C_app1 --> Start a GUI
- Lua_Env2 call C_app2 --> Refer to the GUI --> Refer to some data class in C_app1 in which has sol::state_view and sol::table
- C_app1 and C_app2 now share the same GUI.

Now when user close the Lua app, all of them are destroyed. When C_app1 is destroyed before C_app2, during the destruction of C_app2, the app crashs.

Now to avoid crashing I used  ( `sol::state_view *` ) and replace sol::table with inplace code.

**Comment by ThePhD** [comment]
A possible fix would be ensuring a proper destruction order, which -- from what you've written -- seems like Lua_Env2, Lua_Env1, C_app2, C_app1. That way, the lua environments die first, and then the C applications die.

Using pointers can also be fine. I don't think I can really judge any further without knowing a bit more.

Good luck.
