### ISSUE TITLE
Memory leak when iterating over table

### ISSUE THREAD

**Issue by Tobger** [ThePhD/sol2#336]
This program produces a memory leak crashing the script with an out of memory error after a few seconds:

```
#include "sol.hpp"

int main() {
	sol::state lua;
	lua.script(R"(
function run()
	local record = {}
	for i=1,256 do
		record[i] = i
	end
	while true do
		fun(record)
	end
end)");

	lua["fun"] = [](const sol::table &t) {
		//removing the for loop fixes the memory leak
		for (auto &i : t)
			;
	};

	lua["run"]();
}
```

I am using [today's](https://github.com/ThePhD/sol2/commit/fe8b1c1c10232f5d92dc744ae1bb3ff5b168adef) `sol.hpp` and lua5.3 on Windows 7 with MinGW 5.3.0.

When not iterating over the elements of the table no memory leak occurs.

Calling `lua.collect_garbage()` in the lambda slows down execution time but does not fix the memory leak.

**Comment by ThePhD** [comment]
This is all fixed now. Grab the latest:

https://github.com/ThePhD/sol2/releases/tag/v2.15.8
