### ISSUE TITLE
Unexpected/inconsistent behavior with inheritence and SOL_SAFE_USERTYPE

### ISSUE THREAD

**Issue by squeek502** [ThePhD/sol2#337]
The code below runs successfully when `SOL_SAFE_USERTYPE` is not defined ('Release' build for me), but fails with `lua: error: caught (...) exception` when `SOL_SAFE_USERTYPE` is defined ('Debug' build for me). It's the `Thing()` call that triggers the error.

The test case:
```c++
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
#include <sol.hpp>

class A {
public:
	int Thing() const { return 123; }
};

class B : public A {
};

TEST_CASE("test")
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_simple_usertype<B>("B",
		sol::default_constructor,
		"Thing", &B::Thing
	);

	REQUIRE_NOTHROW(lua.script("B.new():Thing()"));
}
```

Some notes/caveats:

- I'm using Lua 5.1.5 and MSVC14.
- Stepping through, `luaL_error` gets called [here in sol.hpp](https://github.com/ThePhD/sol2/blob/66ad18979706a6396bc67424e9e35e5262d60061/sol/call.hpp#L281), but then the `...` exception that is caught and ultimately thrown seems to be coming from `luaM_realloc_` in `lmem.c`, although I could have that wrong (I'm not at all knowledgeable about how exceptions interact with Lua).
- It still fails the same way if `Thing` is bound using `&A::Thing` within the `B` usertype definition
- It *would* run successfully with `SOL_SAFE_USERTYPE` defined if `A` was bound first with `Thing` as a member function and then `B` was bound using `sol::base_classes, sol::bases<A>()`.

Let me know if you need any more information.

**Comment by ThePhD** [comment]
All fixed, friend: the code should not work as desired, with or without `SOL_SAFE_USERTYPE`. If anything similar like this pops up, let me know: I think I made sure to vet `simple_usertype` to make sure nothing bad happens for either member functions or member variables which come from a base class, and I added a new test as well.

Give it a spin:

https://github.com/ThePhD/sol2/releases/tag/v2.15.8

**Comment by squeek502** [comment]
Awesome, thank you! Can confirm 2.15.8 works as expected.
