### ISSUE TITLE
Segmentation fault when using lambda in usertypes

### ISSUE THREAD

**Issue by runtime-rnt** [ThePhD/sol2#338]
```c++
class Test
{
public:
  Test() { }
  void foo() { }
};

s.new_usertype("test",
  "foo", &Test::foo,
  "bar", [](Test &o) { o.foo(); }
);

```
lua code:

```lua

obj = test.new()

-- If we call:
obj.foo()
-- We get the normal error message:
-- sol: received nil for 'self' argument (use ':' for accessing member functions, make sure 
-- member variables are preceeded by the actual object with '.' syntax)

-- But if call the same function 'bar', we get Segmentation fault:
obj.bar()

-- Correct calls in both cases operate normally:
obj:foo()
obj:bar()
```

**Comment by ThePhD** [comment]
This is accurate. Member functions have a specific structure and signature that allow me to know you intended `obj:bar()`. When you pass in a lambda, I have no idea if that's meant to be a free function, or a member function. It could just take an object of `Test`, meant to be called with `test.bar(obj)`, or it could be an actual member function.

If you want safety, use `protect` or turn on safety features:

http://sol2.readthedocs.io/en/latest/api/protect.html
