### ISSUE TITLE
Binding functions with default parameters

### ISSUE THREAD

**Issue by squeek502** [ThePhD/sol2#340]
Currently, when a function that has default parameters is bound, calling it from Lua with the default parameters omitted calls the function with newly initialized values rather than the default values. No clue if this is fixable or not, so any clarification would be appreciated.

Test code:

```c++
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
#include <sol.hpp>

class DefaultParam {
public:
	int defaultParam(int param = 1) const { return param; }
};

int defaultParam(int param = 1) { return param; };

TEST_CASE("default parameters")
{

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	SECTION("simple")
	{
		lua.new_simple_usertype<DefaultParam>("DefaultParam",
			sol::default_constructor,
			"defaultParam", &DefaultParam::defaultParam
			);

		lua.script("x = DefaultParam.new():defaultParam(5)");
		int x = lua["x"];
		REQUIRE(x == 5);

		lua.script("y = DefaultParam.new():defaultParam()");
		int y = lua["y"];
		REQUIRE(y == 1);
	}

	SECTION("regular")
	{
		lua.new_usertype<DefaultParam>("DefaultParam",
			sol::default_constructor,
			"defaultParam", &DefaultParam::defaultParam
		);

		lua.script("x = DefaultParam.new():defaultParam(5)");
		int x = lua["x"];
		REQUIRE(x == 5);

		lua.script("y = DefaultParam.new():defaultParam()");
		int y = lua["y"];
		REQUIRE(y == 1);
	}

	SECTION("free function")
	{
		lua.set_function("defaultParam", defaultParam);

		lua.script("x = defaultParam(5)");
		int x = lua["x"];
		REQUIRE(x == 5);

		lua.script("y = defaultParam()");
		int y = lua["y"];
		REQUIRE(y == 1);
	}
}
```

Results:

```
-------------------------------------------------------------------------------
default parameters
  simple
-------------------------------------------------------------------------------
main.cpp
...............................................................................

main.cpp: FAILED:
  REQUIRE( y == 1 )
with expansion:
  0 == 1

-------------------------------------------------------------------------------
default parameters
  regular
-------------------------------------------------------------------------------
main.cpp
...............................................................................

main.cpp: FAILED:
  REQUIRE( y == 1 )
with expansion:
  0 == 1

-------------------------------------------------------------------------------
default parameters
  free function
-------------------------------------------------------------------------------
main.cpp
...............................................................................

main.cpp: FAILED:
  REQUIRE( y == 1 )
with expansion:
  0 == 1
```

**Comment by ThePhD** [comment]
If you turn on `SOL_CHECK_ARGUMENTS`, all of these functions simply explode with runtime errors. "Default" parameters don't exist beyond compile-time, and they only exist in C++. There is only one function generated (`int(int);` is the signature), and the compiler resolves default parameter nonsense at compile-time, and the thing you're passing to Lua is a function returning an integer, taking a single integer. Calling it without the 1 argument in Lua is basically invoking UB. (Lua in this case happens to initialize bad values retrieved from the system to 0).

The "Default parameter"-ness is not something a system can take advantage of. If you want "Default parameters" in Lua, use overloading.

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/overload.html

**Comment by ThePhD** [comment]
As a side note, I should write this down somewhere in the documentation, since you're the third, fourth? Person to ask about this...

**Comment by squeek502** [comment]
Thanks, figured that might be the case, but couldn't find anything about it in the docs or past issues, although I definitely should have tried it with `SOL_CHECK_ARGUMENTS`.

A note in the docs about it would be great.

**Comment by ThePhD** [comment]
There's a note in the docs, and it's pointed to by the tutorial and by the quick and dirty section:

http://sol2.readthedocs.io/en/latest/api/overload.html
