### ISSUE TITLE
sol::no_constructor with call_constructor compilation error in latest version

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#347]
I'm not exactly sure which commit caused this issue, but it started happening when I updated from `v2.15.7 (revision fe8b1c1)` to `v2.15.8 (revision 0c8ec82)`.

The following usertype definition (for a class that has no default constructors):
```cpp
lua.new_simple_usertype<SomeClass>("SomeClass",
	sol::call_constructor, sol::no_constructor,
	...
);
```

Causes the following compilation error:
```
21>xmemory0(737): error C2661: 'sol::no_construction::no_construction': no overloaded function takes 2 arguments (compiling source file SomeClass.cpp)
21>  sol.hpp(5996): note: see reference to function template instantiation 'void std::allocator<T>::construct<T,const sol::no_construction&,_Ty>(_Objty *,const sol::no_construction &,_Ty &&)' being compiled
21>          with
21>          [
21>              T=sol::no_construction,
21>              _Ty=sol::function_detail::call_indicator,
21>              _Objty=sol::no_construction
21>          ] (compiling source file SomeClass.cpp)
...
```

**Comment by OrfeasZ** [comment]
This might also be related to the test failing in #346

**Comment by squeek502** [comment]
Note that #346 still occurs with 2.15.7, so it's likely not related

**Comment by ThePhD** [comment]
Fixed: https://github.com/ThePhD/sol2/releases/tag/v2.15.9

**Comment by adriweb** [comment]
Note: for this to compile, if you have defined some constructors already, with `sol::constructors< ... >`, be sure to use `sol::call_constructor, sol::no_constructor` **only afterwards**.
