### ISSUE TITLE
Can I registe a usertype function,and It's return value is a enum

### ISSUE THREAD

**Issue by djbhsys** [ThePhD/sol2#351]
I trying to do this ,but I get a error when i compile my program.It's say: can not transfer value"EDir" to "EDir &".
Any idea how to do this?

**Comment by OrfeasZ** [comment]
Can you post your usertype registration code and the code of the function you're trying to bind?

**Comment by ThePhD** [comment]
What @OrfeasZ said.

The following code works flawlessly. Unless you can provide me with your program that doesn't compile, compiler version / IDE you're using (Visual Studio, XCode, something + gcc...), and any other helpful information, I don't think I'll be able to help you. Please be more specific.

````cpp
#include <iostream>
#include "sol.hpp"

int main() {

	enum class strict_t {
		e_a,
		e_b,
		e_c
	};

	enum norm_t {
		e_a = 4,
		e_b = 5,
		e_c = 6,
	};

	struct test_a {
		norm_t g() {
			return norm_t::e_a;
		}
	};
	struct test_b {
		norm_t g() {
			return norm_t::e_b;
		}
	};
	
	sol::state lua;

	lua.set_function("f", []() {
		return strict_t::e_a;
	}
	);
	lua.set_function("g", []() {
		return strict_t::e_b;
	}
	);
	lua.set_function("h", []() {
		return strict_t::e_c;
	}
	);
	lua.new_usertype<test_a>("test_a",
		"f", []() {
			return strict_t::e_b;
		},
		"g", &test_a::g
	);
	lua.new_simple_usertype<test_b>("test_b",
		"f", []() {
			return strict_t::e_c;
		},
		"g", &test_b::g
	);



	sol::function f = lua["f"];
	lua.script("v0 = f()");
	strict_t v1 = f();
	strict_t v0 = lua["v0"];
	assert(v0 == strict_t::e_a);
	assert(v1 == strict_t::e_a);

	lua.script("ta = test_a.new()");
	lua.script("tb = test_b.new()");

	lua.script("v2 = ta:g()");
	lua.script("v3 = tb:g()");
	norm_t v2 = lua["v2"];
	norm_t v3 = lua["v3"];
	assert(v2 == norm_t::e_a);
	assert(v3 == norm_t::e_b);
	return 0;
}
````

**Comment by ThePhD** [comment]
I'm... going to consider this solved. Post here again if you continue to have trouble, and we'll help troubleshoot your issue. Just make sure to be more specific about what you're using / doing.

Thanks for using sol2!
