### ISSUE TITLE
Copying variadic_args to lambda to call later

### ISSUE THREAD

**Issue by Aykelith** [ThePhD/sol2#357]
How could I transfer variadic_args to a lambda function in order to call the lambda function later?
Something like this:

    #include "sol.hpp"
    #include <iostream>
    #include <functional>

    std::function<void()> a;
    void connectToA(const sol::function& f, const sol::variadic_args& va) {
        a = [=](){
            f(va);
        };
    }

    int main() {
        sol::state lua;
        lua.open_libraries(sol::lib::base);
        lua.set_function("connectToA", connectToA);
        lua.script("function a(name)\nprint(name)\nend\nconnectToA(a, \"some name\")");
        a();
    }

**Comment by ThePhD** [comment]
`variadic_args` doesn't save anything. It leaves all arguments on Lua's stack, which gets modified after the function call (`connectToA`) completes.

The way to solve this is to use `std::vector<sol::object> args`, and then save all the arguments into that. Then, when calling the function, push all the elements of `args` onto the stack in preparation for calling `f`.

I'll see if I can drum up an example soon if these instructions don't make sense to you: at the moment, I have a few things I need to take care of.

**Comment by ThePhD** [comment]
Note to self: add this kind of example to the docs...

**Comment by Aykelith** [comment]
Thanks. I made it work. I just called the functions with `sol::as_args(args)`, args being `std::vector<sol::object>`.

**Comment by ThePhD** [comment]
Ahh, you just beat me to the punch! I'll still write up the example here, though, so I can have a point of reference and put it in the docs too:

````cpp
#include "sol.hpp"
#include <iostream>
#include <functional>

std::function<void()> function_storage;

void store_routine(const sol::function& f, const sol::variadic_args& va) {
	function_storage = [=, args = std::vector<sol::object>(va.begin(), va.end())]() {
		f(sol::as_args(args));
	};
}

int main() {
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	lua.set_function("store_routine", &store_routine);
	lua.script(R"(
function a(name)
	print(name)
end
store_routine(a, "some name")
)");
	function_storage();

	lua.script(R"(
function b(number, text)
	print(number, "of", text)
end
store_routine(b, 20, "these apples")
)");
	function_storage();
}
````
