### ISSUE TITLE
How to abort a LUA function ?

### ISSUE THREAD

**Issue by cgimenez** [ThePhD/sol2#358]
Hi all ! I'm new to Sol2, I've read the whole documentation and I've certainly missed this point : how can I do to stop/abort a LUA running function ?

Some of my LUA scripts will have long running functions, some with timers waits, some never returning until notified. How can I achieve this with Sol 2 ?

Thanks !

**Comment by ThePhD** [comment]
sol2 doesn't handle this. Lua does (or C/C++ does). You would need to investigate common Multi-threading and cooperative cancellation techniques (mutexes, condition variables, and synchronization tools), and what libraries are available to you in either Lua, or C++. C++'s standard library has primitives for synchronizing between threads and cooperative cancellation with a bit of effort on your part, see [here](http://en.cppreference.com/w/cpp/thread).
