### ISSUE TITLE
Handling errors from coroutines in LuaJIT

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#359]
Sol ideally handles all kinds of errors in LuaJIT when loading the script using `load`/`load_file` (there are some problems when loading the script via `script`/`script_load`), except for one - coroutines. Coroutine errors created from within the Lua are handles without any problems, but both C++ exceptions and just calling `luaL_error` leads to undefined behavior (i guess it corrupts the SEH chain, because program crashes with error `Invalid exception handler detected`). According to the information in the [documentation](http://sol2.readthedocs.io/en/latest/exceptions.html#luajit-and-exceptions), this should not be the case when the error is thrown from a function that is bound through conventional means of Sol. This also leads to a disruption of the `SOL_CHECK_ARGUMENTS` feature because `luaL_error` is called from the type checking function.

I did a lot of tests, but I still could not find a normal way to safely raise an error from the coroutine. I know that LuaJIT is not friendly with C++ exceptions in Windows x86, but in this particular case it's not clear - is it because of the LuaJIT feature or the problem is in Sol.

Test code (must be compiled for windows/x86): https://gist.github.com/THE-FYP/6a0b7574f974f26b0ca2b5db90a02993

**Comment by ThePhD** [comment]
I built and ran this code using Lua 5.3.3 in C mode (the default when including sol.hpp, which includes lua.hpp) with the latest Visual Studio. It does not cause the unhandled exception 'invalid exception handler'. I then changed this to be LuaJIT, 2.1.x or LuaJIT 2.0.x, and the problem arises, but __only__ with a WIndows/x86 build. As the LuaJIT documentation states, support for exceptions is not complete ("Limited"), and often things related to exceptions break.

I cannot help you. This is a LuaJIT problem entirely, and the only way to solve it is to avoid use of exceptions with coroutines for x86 builds or upgrade to distributing a 64-bit binary.
