### ISSUE TITLE
new_usertype lambda "this"

### ISSUE THREAD

**Issue by mutex36** [ThePhD/sol2#360]
Is it possible to write something like this:
```C++
a_State.new_usertype<CrScene>("Scene",
"AddNode", [](CrScene* this_, NodeT1* a_Node)
{
//do stuff with this_
//e.g. wrapper around template func: this_->AddNode<NodeT1>(a_Node);
},
"AddNode", [](CrScene* this_, NodeT1* a_Node)
{
//do stuff with this_
//e.g. wrapper around template func: this_->AddNode<NodeT2>(a_Node);
});
```

So a lambda function that provides the current instance of `CrScene` and takes additional arguments.
Basically, what I am trying to achieve is writing a wrapper that pins down various template functions by overloading them.

**Comment by mutex36** [comment]
> **"{name}", &free_function**
> If the first argument is T* or T&, then it will bind it as a member function

I think I just found the answer.

**Comment by ThePhD** [comment]
When in doubt, try it. If it doesn't do what you expect, then come smack me upside the head with a question / issue report,

Have fun!

**Comment by mutex36** [comment]
Hi again. I am still having trouble getting the right overload called.
This is how the overloads are registered:
```C++
a_State.new_usertype<CrScene>("Scene",
"AddNode", [](CrScene* thiz, CrSceneNode* node)
{ thiz->AddNode<CrSceneNode>(node); },
"AddNode", [](CrScene* thiz, CrMeshNode* node)
{ thiz->AddNode<CrMeshNode>(node); },
"AddNode", [](CrScene* thiz, CrTerrainNode* node)
{ thiz->AddNode<CrTerrainNode>(node); },
"AddNode", [](CrScene* thiz, CrCameraNode* node)
{ thiz->AddNode<CrCameraNode>(node); });
```
Inside Lua, `this` refers to the current instance of `CrScene`.

**Example A**
```Lua
cameraNode = CameraNode.Create(cameraTransform)
this:AddNode(cameraNode)
```
Calls `CrCameraNode `overload as expected.

**Example B**
```Lua
meshNode = MeshNode.Create(meshTransform)
this:AddNode(meshNode)
```
Also calls `CrCameraNode `overload. Same goes for all other types.

**Create()**
`"Create", [](CrTransform t) { return new CrSceneNode(t); }`
_Note: The pointer is managed by Scene._

Am I missing something? Why is the right overload not called?
Thanks for your help and time 👍

**Comment by adriweb** [comment]
Take a look at [`sol::overload`](https://sol2.readthedocs.io/en/latest/api/overload.html).

**Comment by ThePhD** [comment]
[functions example](https://github.com/ThePhD/sol2/blob/develop/examples/functions.cpp#L95) and the docs linked show how `sol::overload` can be used. It's a single name, and all the functions packed into the `sol::overload` call. We do not concatenate things with the same name at runtime: they are overwritten and/or given on a first-come, first-serve basis.
