### ISSUE TITLE
TEST_CASE("containers/readonly", "make sure readonly members are stored appropriately") when leaving scope of test case.

### ISSUE THREAD

**Issue by black13** [ThePhD/sol2#361]
This is building using Visual C++ Community: 
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
Installed Version: Community
Visual Basic 2015   00322-20000-00000-AA773
Microsoft Visual Basic 2015
Visual C# 2015   00322-20000-00000-AA773
Microsoft Visual C# 2015
Visual C++ 2015   00322-20000-00000-AA773
Microsoft Visual C++ 2015

I am linking against LuaJIT-2.0.4 version.

**Comment by black13** [comment]
[catch_sol2.zip](https://github.com/ThePhD/sol2/files/837061/catch_sol2.zip)

**Comment by black13** [comment]
is this related to SOL_EXCEPTIONS_SAFE_PROPAGATION define?

**Comment by ThePhD** [comment]
As a second question: is this a 64-bit build or a 32-bit build?

**Comment by ThePhD** [comment]
I managed to get this to repro on a 64-bit build. This might be a double-delete bug. I'll have to investigate further....

**Comment by ThePhD** [comment]
It's not a double-delete bug. The addresses are unique for the two metatables (in one run it was `0x00000288921c1940` and `0x0000000012107c50`) and their members properly move / copy elements.

The crash happens somewhere inside of Hash Map's iterator-orphaning debug code. To be perfectly honest, I'm not all that enthusiastic about making a small repro for this for the STL: ITERATOR_DEBUG stuff tends to have some wonky loops and bugs in it that I honestly do not want to touch.

I can tell you that sol is behaving properly. Ignore the crash in the test, unless this is specifically affecting you.

**Comment by 6lack13** [comment]
it is a 64 bit build and I can ignore.

**Comment by black13** [comment]
Is there a way to let the tests run and ignore exceptions?

**Comment by ThePhD** [comment]
Further testing reveals that "this script" is what triggers the failure:

````
auto result = lua.do_string(R"(
a.readonly_seq = value;
	)");
````

If LuaJIT suffers a failure, it invalidates parts of the memory that the VC++'s STL deletes ___only in the case where debug mode is on and it attempts to clean code using `_ITERATOR_DEBUG_LEVEL` defined to `2`___.

I'm chalking this up to the VC++ STL being overly aggressive in its iterator debug code. If you want to get around this problem, define `_ITERATOR_DEBUG_LEVEL` to be `0` in the tests just before running them.

**Comment by ThePhD** [comment]
This nagged me a little, so I took another look at it, and I found the root cause.

When an error is triggered in sol2 we use `luaL_error` to communicate said error. The problem with this is that it skips destructors. Which caused the iterator problems tot rigger in VC++.

**Comment by ThePhD** [comment]
This is no longer a problem
