### ISSUE TITLE
Neat Constructor Syntax

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#362]
The syntax I picked for constructors sucks:

````cpp
lua.new_usertype<thing>( "thing",
     // vomiting noises
     sol::constructors<sol::types<std::string, int>, sol::types<bool>, sol::types<>>(),
     ...
);
````

````cpp
lua.new_usertype<thing>( "thing",
     // happy smiley noises
     sol::constructors<void(string, int), int(bool), void()>()
     ...
);
````

The second syntax is better. Note that the return type of those function types should be ignored, as its only the arguments that matter (a constructor will always make a `thing`, no matter what, so the return type shouldn't matter... but, it might be good to demand it be like that anyhow).

**Comment by demianmnave** [comment]
There isn't much difference between them syntactically.

```
lua.new_usertype<thing>( "thing",
     sol::constructors<types(string, int), types(bool), types()>()
     ...
);

Is there a type detection benefit to the second?

**Comment by ThePhD** [comment]
One requires more typing, and I am abhorrent of having to do more keypresses than I absolutely need to. The other one actually looks like a function call, AND the second can actually take typedefs that would be functions (contemplating whether allowing function-pointer type names would also be useful / beneficial).

**Comment by demianmnave** [comment]
Definitely understand saving keystrokes.  Making the return type useful (or at least meaningful) would clarify usage and intent, though.  I suppose the user could at least make the return type meaningful (as in my example), but it seems more appropriate for the library to do this.

**Comment by OrfeasZ** [comment]
Would introducing this syntax break the previous syntax?

**Comment by ThePhD** [comment]
@OrfeasZ no, backwards-compatible.

Added as of latest commit.
