### ISSUE TITLE
Iterating usertype vector with ipairs causes crash

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#364]
I have not been able to create a reproduction test-case yet, but using `ipairs` to iterate an `std::vector<SomeClass*>` causes a crash in sol2 with the following exception:

```
Exception thrown: read access violation.
**std::forward<std::default_delete<sol::usertype_detail::callable_binding<SomeOtherClass,sol::property_wrapper<float **(__thiscall SomeOtherClass::*)(void)const ,void (__thiscall SomeOtherClass::*)(float)> > > >(...) returned nullptr.
```

This is the lua code in question:
```lua
for i, v in ipairs(GetValues()) do
    ...
end
```

`GetValues()` is a bound function that returns an `std::vector<SomeClass*>` and `SomeClass` is a bound usertype. The code inside the loop is never executed. It should be noted that this issue does not occur when using `pairs`.

**Comment by OrfeasZ** [comment]
I seem to be getting very inconsistent exception messages, presumably because of weird compiler optimizations. This time I got this:

```
Exception thrown: read access violation.

std::move<sol::simple_usertype_metatable<SomeOtherClass> &>(...) returned nullptr.
```

Even though the messages are inconsistent, all crashes occur in the same location:
```cpp
sol::stack::pusher<SomeClass*,void>::push<SomeClass *>(lua_State * L, SomeClass * && <args_0>)
```
which corresponds to this code:
```cpp
template<typename T>
struct pusher<T*, meta::disable_if_t<meta::all<is_container<meta::unqualified_t<T>>, meta::neg<meta::any<std::is_base_of<reference, meta::unqualified_t<T>>, std::is_base_of<stack_reference, meta::unqualified_t<T>>>>>::value>> {
	template <typename... Args>
	static int push(lua_State* L, Args&&... args) {
		return pusher<detail::as_pointer_tag<T>>{}.push(L, std::forward<Args>(args)...);
	}
};
```

**Comment by ThePhD** [comment]
I need more information to repro.

Lua version? Compiler/IDE?

**Comment by ThePhD** [comment]
I found the problem, anyhow. An SOL_SAFE_USERTYPE define was hiding a critical check. This is now fixed in the latest.

**Comment by OrfeasZ** [comment]
Okay, I'll give it a try and let you know if it's still happening.

**Comment by OrfeasZ** [comment]
Yep, from a first look it seems like it's fixed.
