### ISSUE TITLE
Not exporting functions when using sol2

### ISSUE THREAD

**Issue by Aykelith** [ThePhD/sol2#367]
I don't know if is from sol2 or from lua but I have last sol2 release and last lua release(5.3.4) and I'm using MinGW (6.3) and CMake and when I'm creating my library which contains a few places where I use lua and sol2 the MinGW doesn't export any function, but only the `lua_*` functions. If I comment the lines where I use sol2 then MinGW exports everything good. I'm using Dependency Walker for checking the functions in DLL. Have some ideas why? Thanks.

**Comment by ThePhD** [comment]
g++ (and MinGW) by default mark most / all functions as visible. If you need to fine-tune what is visible, you need to explicitly specify some compiler flags (`-fvisiblity-hidden`, or something?).

sol2 can't really control this because it's a header-only library. Where the functions show up is in response to compiler flags and how you use the functions. Obviously, in certain cases sol2 functions need to be part of your DLL, so that the thing you've built knows what to call, and where.

**Comment by Aykelith** [comment]
The problem is that my functions are all visible when I compile without sol2, but when I include sol2 all my functions are no more visible. I tried to include just lua and everything is ok, but when include sol2 all my functions are invisible and just lua_* functions are visible.

**Comment by ThePhD** [comment]
Oh, okay. I understand a lot more now! Sorry about not getting it.

I'll try to reproduce and see if I can figure out what's going on with Dependency Walker.

**Comment by Aykelith** [comment]
Here I make a project that reproduce problem: https://github.com/Aykelith/sol2_testbug

**Comment by ThePhD** [comment]
I was able to reproduce the problem. I'm not sure why GCC decides that your functions shouldn't be exported anymore after you use some of the other stuff. I'm going to guess it assumes that your stuff is local. I was able to get it to export the class functions by specifically marking them:

`__attribute__ ((dllexport))`

You can mark [them in other ways, too, and should follow this guide here to get it to work out](https://gcc.gnu.org/wiki/Visibility). This isn't necessarily a sol2 problem: including any non-trivial code triggers the same kind of problem. If you're building a library, it seems like you'll need to mark the functions explicitly to get them to export with newer compilers. That just seems to be the way it is.

Good luck!
