### ISSUE TITLE
Checking for the presence of an object that a script creates so on the C++ side it doesn't break..

### ISSUE THREAD

**Issue by HoraceWeebler** [ThePhD/sol2#368]
So in the tutorials the lua-instantiated object name is known each time, and what I mean by that is, for example:
  Doge& d1 = lua["dog"];  <-- the dog object MUST exist and be instantiated in the script for this to work.

All of the examples provided use the known name of the object, e.g., "dog", to bring a reference of the object into C++ or to otherwise manipulate objects.  However, what if you do not know the name of the object within the lua script?  The people I have writing scripts may instantiate the object with a different name.. or multiple objects with multiple different names.  Yet,  I want to bring them back into the c++ side.. so the following questions I am left with:

1. What is the most efficient way to lookup the objects that are addressable within the current lua state to make sure the object was instantiated in the script?  I suspect you will say a metatable lookup.. please provide some example code or a link to some I can look at.

2. How do you error check the above statement when the script fails to instantiate "dog"?  It doesn't throw an exception. **[EDIT, I figured this one out after I sipped coffee and stopped being an idiot.  lua["foo"] is of type sol:nill when its uninstantiated.  Only Q1 remains.]**

This library is excellent, thanks!

**Comment by ThePhD** [comment]
It's present in the quick and dirty tutorial. I should probably write a more dedicated example about [`sol::optional`](http://sol2.readthedocs.io/en/latest/api/optional.html) (the documentation is a bit lanky here, but it contains all the information you could need).

One example is in the quick and dirty tutorial: [Use sol::optional<the_type> to retrieve a specific type from the framework (second blurb underneath, talking going deep)](http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#tables).

From the "variables" tutorial: [safe and optional lookup](http://sol2.readthedocs.io/en/latest/tutorial/variables.html#id2).

From the benchmarks page, of the frameworks/libraries that support optional lookup [sol2 is the fastest](https://raw.githubusercontent.com/ThePhD/lua-bench/master/lua%20-%20results/lua%20bench%20graph%20-%20get%20optional.png). Obviously there's improvements to be made, but we're competitive on the order of nanoseconds: I'm not sweating any bullets.

**Comment by ThePhD** [comment]
As a side note, this works for getting more than just things like strings or doubles: if you want safety on any return, just slap a `sol::optional<>` around the return type, even a reference:

`sol::optional<Dog&> maybe_doge = lua["woofer"];` <--- does not copy, returns a reference, still safe.

**Comment by HoraceWeebler** [comment]
Thank you for pointing out the optional call.  But what if you don't know the object "woofer" was instantiated.  How does one go about traversing the objects the script created to find objects of type 'Dog'?  I want to be able to dynamically find objects instantiated in the script and then pull them into C++ for further manipulation.

Thanks for the quick response!

**Comment by ThePhD** [comment]
Iterate through the table and pick out what you want.

````cpp
#define SOL_CHECK_ARGUMENTS 1

#include <sol.hpp>
#include <string>
#include <memory>
#include <iostream>

int main(int argc, char** argv) {
	
	struct thing {
		int a = 20;
	};

	struct super_thing : thing {
		int b = 40;
	};

	struct unrelated {

	};

	sol::state lua;
	lua.new_usertype<super_thing>("super_thing",
		sol::base_classes, sol::bases<thing>()
	);
	lua["t1"] = thing{};
	lua["t2"] = super_thing{};
	lua["t3"] = unrelated{};
	lua["container"] = lua.create_table_with(0, thing{}, 1, unrelated{}, 4, super_thing{});

	
	std::vector<std::reference_wrapper<thing>> things;
	auto fx = [&lua, &things](auto& f, auto& tbl) -> void {
		for (auto key_value_pair : tbl) {
			const sol::object& key = key_value_pair.first;
			const sol::object& value = key_value_pair.second;
			sol::type t = value.get_type();
			switch (t) {
			case sol::type::table:
				f(f, value.as<sol::table>());
				break;
			case sol::type::userdata:
				if (value.is<thing>()) {
					if (key.is<std::string>()) {
						std::cout << "key " << key.as<std::string>() << " is a thing" << std::endl;
					}
					else if (key.is<int>()) {
						std::cout << "key " << key.as<int>() << " is a thing" << std::endl;
					}
					things.push_back(value.as<thing>());
				}
				break;
			default:
				break;
			}
		}
	};
	fx(fx, lua);

	return 0;
}
````

![Yay.](http://i.imgur.com/qAT2sXF.png)

**Comment by HoraceWeebler** [comment]
Yay! Christmas came early.  This is exactly what I want.   I think it is highly deserving of inclusion in your documentation and/or within an example cpp file.

I'm going to wrap this code into a helper so I can access created objects via an indexer, e.g., mycontainer.getobjectcount(), mycontainer.getobjectcountbytype(foo_type), mycontainer.getobject(x), mycontainer.getobjectsoftype(foo_type), etc.

Thanks for the assistance, you are quite prompt and I highly appreciate it.

**Comment by ThePhD** [comment]
Note that you can replace a lot of the `is/as` calls with a simple `sol::optional<thing&>` instead.

**Comment by HoraceWeebler** [comment]
When I run your code, without modification, I get a ton of compiler errors:

/bin/sh -c '/usr/bin/make -j2 -e -f  Makefile'
----------Building project:[ se7en - Debug ]----------
make[1]: Entering directory '/home/ken/git-repos/Se7enMud/se7enmudcl/se7en'
/usr/bin/g++  -c  "/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp" -g -O0 -std=c++14 -Wall -DAS_USE_STLNAMES=1 -DAS_STRING_OBJNAME=\"string\" -D_CRT_SECURE_NO_WARNINGS -DAS_NO_EXCEPTIONS  -o ./Debug/up_up_se7en_src_test_lua.cpp.o -I. -I. -I../../telnetpp/include -I../../terminalpp/include -I../../ttvfs/ttvfs -I../../odin/include -I../../se7en/include -I../../se7en/include/script -I../../se7en/include/scriptable_entities -I../../../cereal/include -I../../AngelscriptUtils/src -I../../sol2 -I../lua/src
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp: In instantiation of 'test1()::<lambda(auto:3&, auto:4&)> [with auto:3 = test1()::<lambda(auto:3&, auto:4&)>; auto:4 = sol::state]':
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:120:12:   required from here
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:102:6: error: no match for call to '(test1()::<lambda(auto:3&, auto:4&)>) (test1()::<lambda(auto:3&, auto:4&)>&, sol::basic_table_core<false, sol::reference>)'
     f(f, value.as<sol::table>());
      ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:95:51: note: candidate: test1()::<lambda(auto:3&, auto:4&)> [with auto:3 = test1()::<lambda(auto:3&, auto:4&)>; auto:4 = sol::basic_table_core<false, sol::reference>] <near match>
  auto fx = [&lua, &things](auto& f, auto& tbl) -> void {
                                                   ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:95:51: note:   conversion of argument 2 would be ill-formed:
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:102:6: error: invalid initialization of non-const reference of type 'sol::basic_table_core<false, sol::reference>&' from an rvalue of type 'sol::basic_table_core<false, sol::reference>'
     f(f, value.as<sol::table>());
      ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:107:49: error: use of 'decltype(auto) sol::basic_object<base_t>::as() const [with T = std::__cxx11::basic_string<char>; base_t = sol::reference]' before deduction of 'auto'
       std::cout << "key " << key.as<std::string>() << " is a thing" << std::endl;
                                                 ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:110:41: error: use of 'decltype(auto) sol::basic_object<base_t>::as() const [with T = int; base_t = sol::reference]' before deduction of 'auto'
       std::cout << "key " << key.as<int>() << " is a thing" << std::endl;
                                         ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:112:38: error: use of 'decltype(auto) sol::basic_object<base_t>::as() const [with T = test1()::thing; base_t = sol::reference]' before deduction of 'auto'
      things.push_back(value.as<thing>());
                                      ^
se7en.mk:136: recipe for target 'Debug/up_up_se7en_src_test_lua.cpp.o' failed
make[1]: *** [Debug/up_up_se7en_src_test_lua.cpp.o] Error 1
make[1]: Leaving directory '/home/ken/git-repos/Se7enMud/se7enmudcl/se7en'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
====7 errors, 2 warnings====
![virtualbox_ubuntu dev_19_03_2017_20_22_57](https://cloud.githubusercontent.com/assets/3701133/24086215/ffb581c4-0ce1-11e7-9615-1827533166c3.png)

**Comment by ThePhD** [comment]
The [cleaned up example is here](https://github.com/ThePhD/sol2/blob/develop/examples/optional_with_iteration.cpp). I had been bitten by the fact that VC++ has an extension which allows for non-const references to take values and will do some magic lifetime mumbo jumbo to keep things alive.

**Comment by HoraceWeebler** [comment]
Awesome, glad I wasn't missing something painfully obvious! Thanks

**Comment by HoraceWeebler** [comment]
Still barfing on cleaned up code...

/bin/sh -c '/usr/bin/make -j2 -e -f  Makefile'
----------Building project:[ se7en - Debug ]----------
make[1]: Entering directory '/home/ken/git-repos/Se7enMud/se7enmudcl/se7en'
/usr/bin/g++  -c  "/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp" -g -O0 -std=c++14 -Wall -DAS_USE_STLNAMES=1 -DAS_STRING_OBJNAME=\"string\" -D_CRT_SECURE_NO_WARNINGS -DAS_NO_EXCEPTIONS  -o ./Debug/up_up_se7en_src_test_lua.cpp.o -I. -I. -I../../telnetpp/include -I../../terminalpp/include -I../../ttvfs/ttvfs -I../../odin/include -I../../se7en/include -I../../se7en/include/script -I../../se7en/include/scriptable_entities -I../../../cereal/include -I../../AngelscriptUtils/src -I../../sol2 -I../lua/src
In file included from ../../sol2/sol/optional.hpp:30:0,
                 from ../../sol2/sol/types.hpp:25,
                 from ../../sol2/sol/reference.hpp:25,
                 from ../../sol2/sol/object.hpp:25,
                 from ../../sol2/sol/proxy.hpp:26,
                 from ../../sol2/sol/table_core.hpp:25,
                 from ../../sol2/sol/table.hpp:25,
                 from ../../sol2/sol/state_view.hpp:26,
                 from ../../sol2/sol/state.hpp:25,
                 from ../../sol2/sol.hpp:45,
                 from /home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:2:
../../sol2/sol/optional_implementation.hpp: In instantiation of 'constexpr T& sol::optional<T&>::value() const [with T = test1()::thing]':
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:141:42:   required from 'test1()::<lambda(auto:3&, auto:4&)> [with auto:3 = test1()::<lambda(auto:3&, auto:4&)>; auto:4 = sol::state]'
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:158:12:   required from here
../../sol2/sol/optional_implementation.hpp:781:54: error: invalid initialization of non-const reference of type 'test1()::thing&' from an rvalue of type 'test1()::thing'
     : throw bad_optional_access("bad optional access");
                                                      ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp: In instantiation of 'test1()::<lambda(auto:3&, auto:4&)> [with auto:3 = test1()::<lambda(auto:3&, auto:4&)>; auto:4 = sol::state]':
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:158:12:   required from here
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:143:49: error: use of 'decltype(auto) sol::basic_object<base_t>::as() const [with T = std::__cxx11::basic_string<char>; base_t = sol::reference]' before deduction of 'auto'
       std::cout << "key " << key.as<std::string>() << " is a thing -- ";
                                                 ^
/home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:146:41: error: use of 'decltype(auto) sol::basic_object<base_t>::as() const [with T = int; base_t = sol::reference]' before deduction of 'auto'
       std::cout << "key " << key.as<int>() << " is a thing -- ";
                                         ^
In file included from /usr/include/c++/5/memory:79:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/ken/git-repos/Se7enMud/se7en/src/test_lua.cpp:1:
/usr/include/c++/5/functional:406:7: error: 'std::reference_wrapper<_Tp>::reference_wrapper(_Tp&) [with _Tp = test1()::thing]', declared using local type 'test1()::thing', is used but never defined [-fpermissive]
       reference_wrapper(_Tp& __indata) noexcept
       ^
se7en.mk:136: recipe for target 'Debug/up_up_se7en_src_test_lua.cpp.o' failed
make[1]: *** [Debug/up_up_se7en_src_test_lua.cpp.o] Error 1
make[1]: Leaving directory '/home/ken/git-repos/Se7enMud/se7enmudcl/se7en'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
====8 errors, 2 warnings====

**Comment by ThePhD** [comment]
Right, sorry. You'll need to pull from the latest, that included a fix to stop C++ from deducing the type of an internal expression in the optional implementation from being a value versus a reference.

I should have mentioned that I made a fix a lot earlier. I should also do a new release soon with all these fixes in it...

**Comment by HoraceWeebler** [comment]
I'll pull down your latest. Header-only magic makes it minimally painful.

**Comment by HoraceWeebler** [comment]
Latest code works.  Can't thank you enough for seeing this through.  It happens to be a key feature to support the mudlib I am presently implementing.
