### ISSUE TITLE
Document SOL_CHECK_ARGUMENTS and other build params

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [ThePhD/sol2#37]
I propose to add section into API reference documenting SOL_CHECK_ARGUMENTS and any other build params if they are exist.

One particular thing that makes me cautious about Sol2 is your concentration on the speed, while reliability of applications using Sol is under question. In particular, it seems that without SOL_CHECK_ARGUMENTS, i.e. by default, i can export C++ function accepting string, call it from Lua with number and make a crash.

In another place you mention "Do NOT save the return type of a function_result with auto". It will be great to protect from such errors with some type machinery. Aa well as combine all the remaining warnings in the single documentation section.

**Comment by ThePhD** [comment]
There is, unfortuantely, nothing we can do to stop the user from `auto`-ing `function_result`. Not even a private class struct can stop the power of `auto`: private only means the programmer can't name it explicitly, `auto` doesn't obey the same rules as the programmer.

As for CHECK_ARGUMENTS and friends, yeah I need a section on that. Goes right along with defining SOL_NO_RTII or SOL_NO_EXCEPTIONS, but SOL_CHECK_ARGUMENTS is the only other one that's not really documented. Bundling them up in a single "config.rst" file would probably be for the best.

... When I have. :B

**Comment by Bulat-Ziganshin** [comment]
SOL_CHECK_ARGUMENTS is documented at http://sol2.readthedocs.org/en/latest/api/function.html

The question is only about bundling them all together

**Comment by ThePhD** [comment]
Right, but SOL_CHECK_ARGUMENTS needs to have its own place. NO_RTTI and NO_EXCEPTIONS basically have their own section. `Safety` should probably have its own top-level section there alongsinde `Exceptions` and `RTTI` as well. I also should probably generalize it to make sure every `stack::get` call is checked as well.

I've been considering looking up the debug-defined macros for VC++, g++ and clang++ and automatically defining these to be present if they're not already present. However, I believe most users are good at knowing what they want to call their functions with and in most cases get it right, so until I make the commit to make that the default and update the docs, I'll be leaving it as is.

**Comment by ThePhD** [comment]
It's done: http://sol2.readthedocs.org/en/latest/safety.html
