### ISSUE TITLE
optional_with_iteration.cpp, asplodes when you call 'lua.open_libraries(sol::lib::base)' before defining new user type

### ISSUE THREAD

**Issue by HoraceWeebler** [ThePhD/sol2#371]
The code below will crash hard with the inclusion of 'lua.open_libraries(sol::lib::base);' In particular, the table iterator seems to hit something it doesn't like..

`	std::cout << "=== optional and iteration example ===" << std::endl;

	struct thing {
		int a = 20;

		thing() = default;
		thing(int a) : a(a) {}
	};

	struct super_thing : thing {
		int b = 40;
	};

	struct unrelated {

	};

	sol::state lua;

	// Comment out the new_usertype call
	// to prevent derived class "super_thing"
	// from being picked up and cast to its base
	// class
    lua.open_libraries(sol::lib::base); // <-- INCLUDING THIS LINE RESULTS IN AN UNHANDLED EXCEPTION
	lua.new_usertype<super_thing>("super_thing",
		sol::base_classes, sol::bases<thing>()
	);

	// Make a few things
	lua["t1"] = thing{};
	lua["t2"] = super_thing{};
	lua["t3"] = unrelated{};
	// And a table
	lua["container"] = lua.create_table_with(
		0, thing{50}, 
		1, unrelated{}, 
		4, super_thing{}
	);

	std::vector<std::reference_wrapper<thing>> things;
	// Our recursive function
	// We use some lambda techniques and pass the function itself itself so we can recurse,
	// but a regular function would work too!
	auto fx = [&lua, &things](auto& f, auto& tbl) -> void {
		// You can iterate through a table: it has 
		// begin() and end()
		// like standard containers
		for (auto key_value_pair : tbl) {
			// Note that iterators are extremely frail
			// and should not be used outside of
			// well-constructed for loops
			// that use pre-increment ++,
			// or C++ ranged-for loops
			const sol::object& key = key_value_pair.first;
			const sol::object& value = key_value_pair.second;
			sol::type t = value.get_type();
			switch (t) {
			case sol::type::table: {
				sol::table inner = value.as<sol::table>();
				f(f, inner);
			}
			break;
			case sol::type::userdata: {
				// This allows us to check if a userdata is 
				// a specific class type
				sol::optional<thing&> maybe_thing = value.as<sol::optional<thing&>>();
				if (maybe_thing) {
					thing& the_thing = maybe_thing.value();
					if (key.is<std::string>()) {
						std::cout << "key " << key.as<std::string>() << " is a thing -- ";
					}
					else if (key.is<int>()) {
						std::cout << "key " << key.as<int>() << " is a thing -- ";
					}
					std::cout << "thing.a ==" << the_thing.a << std::endl;
					things.push_back(the_thing);
				}
			}
			break;
			default:
				break;
			}
		}
	};
	fx(fx, lua);

	std::cout << std::endl;`

**Comment by HoraceWeebler** [comment]
Additional output, note how stuck it is on xpcall are on the stack with the inclusion of base libraries.  It gets worse with a  bad::alloc if you add, for instance, sol::lib::package, sol::lib::math, sol::lib::table, and son.

&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function -- 
key xpcall is a function --

**Comment by HoraceWeebler** [comment]
And one more note, when you kill the recursive call:
                case sol::type::table: {
                    sol::table inner = value.as<sol::table>();
                   // f(f, inner);
                }
The exception goes away when you comment out the above-referenced recursive call.

**Comment by ThePhD** [comment]
This happens because `sol::lib::base`, and other things, are tables. They contain references to tables you already traverse. It begins an endless cycle that never breaks, and the hard crash come from out-of-memory / stack-overflow exceptions. Below is a basic amendment I added to the example to show how it can be changed to avoid this, albeit this hard-codes keys: there's better ways to track cyclical redundancies, but that's an exercise left to the reader!

````cpp
#define SOL_CHECK_ARGUMENTS 1

#include <sol.hpp>
#include <string>
#include <unordered_set>
#include <iostream>

int main(int argc, char** argv) {
	
	std::cout << "=== optional and iteration example ===" << std::endl;

	struct thing {
		int a = 20;

		thing() = default;
		thing(int a) : a(a) {}
	};

	struct super_thing : thing {
		int b = 40;
	};

	struct unrelated {

	};

	sol::state lua;
	lua.open_libraries();

	// Comment out the new_usertype call
	// to prevent derived class "super_thing"
	// from being picked up and cast to its base
	// class
	lua.new_usertype<super_thing>("super_thing",
		sol::base_classes, sol::bases<thing>()
		);

	// Make a few things
	lua["t1"] = thing{};
	lua["t2"] = super_thing{};
	lua["t3"] = unrelated{};
	// And a table
	lua["container"] = lua.create_table_with(
		0, thing{ 50 },
		1, unrelated{},
		4, super_thing{}
	);

	// These are all the table names
	// that can trigger an infinite lookup because
	// it contains references to other entities already being
	// traversed: exclude them from the lookup list
	std::unordered_set<std::string> base_library_names({
		"_G", // global table
		"base",
		"io",
		"os",
		"utf8",
		"jit",
		"package",
		"loaded",
		"preload",
		"coroutine",
		"string",
		"math",
		"table",
		"debug",
		"bit32"
	});
	std::vector<std::reference_wrapper<thing>> things;
	// Our recursive function
	// We use some lambda techniques and pass the function itself itself so we can recurse,
	// but a regular function would work too!
	auto fx = [&lua, &things, &base_library_names](auto& f, sol::table& tbl) -> void {
		// You can iterate through a table: it has 
		// begin() and end()
		// like standard containers
		for (auto key_value_pair : tbl) {
			// Note that iterators are extremely frail
			// and should not be used outside of
			// well-constructed for loops
			// that use pre-increment ++,
			// or C++ ranged-for loops
			const sol::object& key = key_value_pair.first;
			const sol::object& value = key_value_pair.second;
			sol::type t = value.get_type();
			switch (t) {
			case sol::type::table: {
				sol::optional<std::string> maybe_strkey = key.as<sol::optional<std::string>>();
				if (maybe_strkey) {
					std::string& strkey = maybe_strkey.value();
					std::cout << "key " << strkey << " is a table...";
					if (base_library_names.find(strkey) != base_library_names.end()) {
						std::cout << " built-in detected: skipping!" << std::endl;
						continue;
					}
					std::cout << std::endl;
				}
				sol::table inner = value.as<sol::table>();
				f(f, inner);
				break;
			}
			case sol::type::userdata: {
				// This allows us to check if a userdata is 
				// a specific class type
				sol::optional<thing&> maybe_thing = value.as<sol::optional<thing&>>();
				if (maybe_thing) {
					thing& the_thing = maybe_thing.value();
					if (key.is<std::string>()) {
						std::cout << "key " << key.as<std::string>() << " is a thing -- ";
					}
					else if (key.is<int>()) {
						std::cout << "key " << key.as<int>() << " is a thing -- ";
					}
					std::cout << "thing.a = " << the_thing.a << std::endl;
					things.push_back(the_thing);
				}
				break;
			}
			default:
				break;
			}
		}
	};
	
	sol::table globals = lua.globals();
	fx(fx, globals);

	std::cout << std::endl;

	return 0;
}
````

**Comment by HoraceWeebler** [comment]
Thanks.  Now on to finding more ways to consume your free time..
