### ISSUE TITLE
  sol::protected_function_result raises unhandled exception with malformed script text

### ISSUE THREAD

**Issue by HoraceWeebler** [ThePhD/sol2#372]
Malformed lua script text loaded either through do_string or do_file raises an unhandled exception.  

My script engine takes scripts written by other users and those scripts may include invalid lua code that shouldn't cause an exception if wrapped in the protected_function_result wrapper. 

The following code raises said unhandled-exception:

  sol::protected_function_result result1 = lua.do_string("p1: = 1");

        if (!result1.valid()) {
            sol::error err = result1;
            reason = err.what();
            //std::cout << "call failed, sol::error::what() is " << what << std::endl;
            return false;
        }

**Comment by ThePhD** [comment]
Use [`load_file/load_script`](http://sol2.readthedocs.io/en/latest/api/state.html#state-load-code) when the code itself cannot be expected to be well-formed. This will return another result which you can inspect to see if loading went well, then turn that into a `sol::function` or a `sol::protected_function` and perform a call on, to see if it executes properly.
