### ISSUE TITLE
Nested enums fail silently

### ISSUE THREAD

**Issue by squeek502** [ThePhD/sol2#377]
Not a big deal, but thought I'd report it anyway:

If you call `new_enum` on a table that was defined using `new_enum`, then the second, nested enum will never get created, even though there is no indication that this is the case until you try to access it. It might be nice to make readonly tables (like the ones resulting from new_enum) trigger compile errors if there are attempts to write to them in C++.

Test code:

```c++
#include <catch.hpp>
#include <sol.hpp>

namespace Text
{
	enum Enum
	{
		Default,
		Yellow
	};

	namespace Size
	{
		enum Enum
		{
			Default,
			Small
		};
	}
}

TEST_CASE("nested enums")
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	auto text = lua.new_enum("Text",
		"Default", Text::Default,
		"Yellow", Text::Yellow
	);
	text.new_enum("Size",
		"Default", Text::Size::Default,
		"Small", Text::Size::Small
	);

	REQUIRE_NOTHROW(lua.script("assert(Text.Default ~= nil)"));
	REQUIRE_NOTHROW(lua.script("assert(Text.Size.Default ~= nil)"));
}
```

Result:
```
-------------------------------------------------------------------------------
nested enums
-------------------------------------------------------------------------------
..\nested_enum.cpp(23)
...............................................................................

..\nested_enum.cpp(38): FAILED:
  REQUIRE_NOTHROW( lua.script("assert(Text.Size.Default ~= nil)") )
due to unexpected exception with message:
  lua: error: [string "assert(Text.Size.Default ~= nil)"]:1: attempt to index
  field 'Size' (a nil value)
```

**Comment by ThePhD** [comment]
I can't generate a compiler error for this. The most I could do is force a runtime error, maybe, but even at that point... is it really all that helpful?

**Comment by squeek502** [comment]
In that case, the current functionality seems fine. It's easy to find the cause with the current runtime error and it's easily avoidable if you think things through when using `new_enum` (which I clearly wasn't :)).
