### ISSUE TITLE
Error when compiling with Unreal 4. Solution inside.

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#379]
When compiling the current singleheader sol.hpp with Unreal 4 it'll throw tons of error messages. 

Solution :
At the bottom of the file, when you redefine Unreal 4s check macro, you forgot two lines, because Unreal 4 uses (for some reason <_<;; ) two kinds of check-macros, but you only redefine one in your sol.hpp.

You have to change
```C++
#ifdef SOL_INSIDE_UNREAL
#ifdef SOL_INSIDE_UNREAL_REMOVED_CHECK
#define check(expr) { if(UNLIKELY(!(expr))) { FDebug::LogAssertFailedMessage( #expr, __FILE__, __LINE__ ); _DebugBreakAndPromptForRemote(); FDebug::AssertFailed( #expr, __FILE__, __LINE__ ); CA_ASSUME(false); } }}
#endif 
#endif // Unreal Engine 4 Bullshit
```

to

```C++
#ifdef SOL_INSIDE_UNREAL
#ifdef SOL_INSIDE_UNREAL_REMOVED_CHECK
#if DO_CHECK
#define check(expr) { if(UNLIKELY(!(expr))) { FDebug::LogAssertFailedMessage( #expr, __FILE__, __LINE__ ); _DebugBreakAndPromptForRemote(); FDebug::AssertFailed( #expr, __FILE__, __LINE__ ); CA_ASSUME(false); } }
#else
#define check(expr) { CA_ASSUME(expr); }
#endif
#endif 
#endif // Unreal Engine 4 Bullshit
```

Btw, funny "Unreal Engine 4 Bullshit"-comments in the code, i had to laugh when i read it. XD

Keep up the good work, you're awesome! :D

**Comment by ThePhD** [comment]
Goddamn Unreal... Yeah, I'll patch this into the latest.

**Comment by ThePhD** [comment]
Integrated as part of the latest and the last release: https://github.com/ThePhD/sol2/releases/tag/v2.16.0
