### ISSUE TITLE
stack::check_get

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#38]
There should be a variant of `stack::get` and `stack::check` that combines both of them into one API, e.g. `stack::check_get`. `get` by default should use this if `SOL_CHECK_ARGUMENTS` is defined, and if not fall back to the regular `stack::get`. This allows the users to have maximum safety when they want it, but turn it off when they don't (e.g.: debug versus release).

API should look like:

````
optional<T> o = stack::check_get( L, -1, throw_error ); // base API
optional<T> o = stack::check_get( L ); // defaults -1 index, no_panic handler
optional<T> o = stack::check_get( L, -1 ); // defaults no_panic handler
````

I have been wary of providing this because `std::optional` is just getting support and I really don't think rolling our own `sol::optional` is wise, but if we want this safer API we might have to roll with it regardless. Thankfully, I already have an `optional` implementation that will handle this for us, and maybe I can hide it behind a `#define` that checks compiler versions? Bwuh.

**Comment by Nava2** [comment]
[`std::optional`](http://en.cppreference.com/w/cpp/utility/optional) is present in C++17, what about just `ifdef`'ing around the C++17 level? 

There is an implementation [here](https://github.com/akrzemi1/Optional) that could be dropped in for now.

**Comment by nabijaczleweli** [comment]
And `std::experimental::optional` is in, so a *using-decl* would suffice

**Comment by ThePhD** [comment]
This is technically a C++14-ish framework. If I use `std::optional` (or even experimental), I have to check whether clang 3.5/g++4.9 roll it.

**Comment by ThePhD** [comment]
Turns out VC++ doesn't ship an experimental optional. S i g h .

**Comment by nabijaczleweli** [comment]
Fun fact: nobody cares about VCpp

**Comment by ThePhD** [comment]
Probably a good chunk (at least 40%) of the users we have use VC++ and Visual Studio, based on what people have said in the old `sol` repo and on reddit.

**Comment by ThePhD** [comment]
Implemented.
