### ISSUE TITLE
Filling the vector of userdata from lua directly

### ISSUE THREAD

**Issue by tooheavymental** [ThePhD/sol2#381]
I want to move my config files to lua.
The typical situation is looks like that:

```c++
#include "sol.hpp"
#include <vector>
#include <cassert>

struct A {
    int a;
    A() : a(0) {};

};

struct B {

    B() {
    }

    std::vector<A> a_list;
};

int main() {
    sol::state lua;
    lua.new_usertype<A>("A", "a", &A::a);
    lua.new_usertype<B>("B","a_list", &B::a_list);
    lua.script(R"(
b = B.new()
b.a_list = {A.new(), A.new()}
)");

    B b = lua["b"];
// something useful here

};
```
I have class B that contains vector of A's and I want configure it directly from lua.
But when I run that code I got 'Segmentation fault'. 
It is possible somehow fix  that? Or is there another approach to this type of problem exists?

P.S.
Thank you for the awesome project

**Comment by ThePhD** [comment]
You cannot set a table using `=` to `std::vector`: Lua doesn't have the operators for that. Instead, you need to modify the vector one little bit at a time. There's an `add` function we automatically give to all list-types, as well as a `clear` method and an `insert` method...

````
	struct A {
		int a;
		A() : a(0) {}
		A(int a) : a(a) {}
	};

	struct B {

		B() {
		}

		std::vector<A> a_list;
	};

	sol::state lua;
	lua.open_libraries(sol::lib::base); // for `print`

	lua.new_usertype<A>("A", "a", &A::a);
	lua.new_usertype<B>("B", "a_list", &B::a_list);

	// sol2 by-default adds "insert", "clear", and "add"
	// methods to most containers
	lua.script(R"(
b = B.new()
b.a_list:add(A.new())
b.a_list:add(A.new())
	)");
	// If you need more containers, you can actually specialize it but that comes later

	// Getting a Reference (&) allows you to access the userdata values directly
	// in C++
	B& b = lua["b"];
	// Manipulate the list directly
	b.a_list.push_back(A(500));
	// Note how these changes are reflected
	// In Lua, since you manipulated it directly
	// Lua indexes from 1, not from 0
	lua.script(R"(
print(b.a_list[3].a)
	)");
````

Note that you can override the default add/append etc. for a specific type by doing `lua.new_usertype<std::vector<A>>( ... );` and setting it all up yourself, but that's a bit overkill honestly. There's also writing a function called `make_vector` that would allow you to take a `sol::table` and make a vector out of it: the choice is yours!
