### ISSUE TITLE
The referenced class object becomes immutable.

### ISSUE THREAD

**Issue by aki237** [ThePhD/sol2#382]
I have a text editor implementation in C++ and sol2.
Registering `Manager` class is like this in the constructor of Manager.
```c++
    lua.open_libraries(sol::lib::base, sol::lib::package);
    lua.new_usertype<Manager>("Manager",
			      sol::constructors<Manager(), Manager(std::string)>(),
			      "insetChar", &Manager::insertChar,
			      "insertText", &Manager::insertStdString,
			      "bkspcChar", &Manager::bkspcChar,
			      "deleteChar", &Manager::deleteChar,
			      "cursorUp", &Manager::cursorUp,
			      "cursorDown", &Manager::cursorDown,
			      "cursorLeft", &Manager::cursorLeft,
			      "cursorRight", &Manager::cursorRight);
    lua["manager"] = this;
```
So I intend to run a lua script for every char stroke.
So in the `insertChar` function :
```c++
lua["currentChar"] = c; // c is the current typed character.
lua.do_file("lua/pairBracket.lua"); // lua script.
```

and the lua script is as follows :
```lua
if currentChar == '(' then
   manager.insertChar(')')
   manager.cursorLeft()
else
   print ("Not matching a bracket")
end
```
Lua matches the typed char but doesn't do any of the manager methods.
While setting the variable up there, is it making the variable mutable? (lua["manager"] = this)

**Comment by ThePhD** [comment]
Please use `manager:method_name( args... )`. **Note the Semi-colon**. That is Lua's syntactic sugar for passing the `self` argument to a function. It translates to: `manager.method_name( manager, args... )`.

Finally, turn on `SOL_CHECK_ARGUMENTS` as described in the [docs](http://sol2.readthedocs.io/en/latest/safety.html#config) to have it noisily error your code when you make mistakes like this.

**Comment by aki237** [comment]
I did that too. manager:insertChar() no luck.

**Comment by ThePhD** [comment]
I don't know what is wrong, then. You will need to describe your problem in more detail. As the [docs](http://sol2.readthedocs.io/en/latest/api/state.html#state-do-code) describe, the method `do_file` will perform the action but also return an [object that describes whether or not your work succeeded, much like its friend `sol::protected_function`](http://sol2.readthedocs.io/en/latest/api/protected_function.html#protected-function). What is the return value, is `result.valid()` true? Please check these things and let me know.

**Comment by ThePhD** [comment]
If you need something that "fails hard", please use `.script_file` and `.script` instead of `do_file` and `do_script`. This will generally make the error explode in your face.

**Comment by HoraceWeebler** [comment]
Hi aki237,
To follow what PhD is saying, it looks like you have bad syntax in your lua script.

manager.insertChar(')')

should be:
manager:insertChar(')')

You can access member variables via the . operator, but not methods.  The lua state you are running that script in is throwing errors, but without wrapping the loading and execution of the script in a protected way you may not be able to see the errors.   Might I suggest you do the following:

``
   sol::load_result lr = lua.load_file(filename);


    if (!lr.valid()) { // This checks the syntax of your script, but does not execute it
        sol::error err = lr;
        std::string what = err.what();
        std::cout << "call failed, sol::error::what() is " << what << std::endl;
    }
    else
    {
        sol::protected_function_result result1 = lr(); // this causes the script to execute
        if(!result1.valid()) {
            sol::error err = result1;
            std::string what = err.what();
            std::cout << "call failed, sol::error::what() is " << what << std::endl;
        }
        else
            std::cout << "OK" << std::endl;
    }
``

**Comment by aki237** [comment]
Thanks I'll try
