### ISSUE TITLE
Casting to Grandparents (and beyond!)

### ISSUE THREAD

**Issue by alitteneker** [ThePhD/sol2#384]
After the better part of a day trying to figure out why some code that runs in C++ was crashing when run (theoretically) equivalently in Lua with Sol2, I think I've finally isolated the root of my confusion. Basically, strange things start to happen when attempting to cast an object from a child to any ancestor type more removed than its direct parent.

As an illustration, consider the following "Toy" example.
~~~~
struct Child;
struct Toy {
    Fun *fun;
    Toy() { fun = new Fun(); }
    ~Toy() { delete fun; }
    virtual void bePlayedWith(Child *kid) {
        fun->have();
    }
};
struct TruckToy : Toy {
    virtual void bePlayedWith(Child *kid) override {
        fun->have();
        Toy::bePlayedWith(kid);
    }
};
struct MonsterTruckToy : TruckToy {
    virtual void bePlayedWith(Child *kid) override {
        fun->have();
        TruckToy::bePlayedWith(kid);
    }
};
struct Child {
    virtual void play(Toy* toy) {
        toy->bePlayedWith(this);
    }
};

. . .

    luastate->new_usertype<Toy>("Toy");
    luastate->new_usertype<TruckToy>("TruckToy",
        LuaBases(Toy));
    luastate->new_usertype<MonsterTruckToy>("MonsterTruckToy",
        LuaBases(TruckToy));
    luastate->new_usertype<Child>("Child",
        "play", &Child::play);
~~~~

This lua code runs just fine,
~~~~
toy = TruckToy.new();
child = Child.new();
child:play(toy);
~~~~

while this lua code winds up with an access violation inside Child::play that toy is a nullptr.
~~~~
toy = MonsterTruckToy.new();
child = Child.new();
child:play(toy);
~~~~

_Does Sol2 **intentionally** not support casting to a grandparent type (or beyond) with properly registered types?_
If so, why? It seems like a pretty serious limitation, one I haven't seen mentioned in the documentation anywhere (though I could've missed it).

**Comment by squeek502** [comment]
[The inheritance docs might be helpful](http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-inheritance):

> Note

> You must list ALL base classes, including (if there were any) the base classes of A, and the base classes of those base classes, etc. if you want Sol/Lua to handle them automagically.

**Comment by ThePhD** [comment]
Basically what @squeek502 said. Base classes must be listed explicitly, all the way up the stack. It's a really annoying limitation, and one I hope to utterly destroy when C++2x (maybe even C++19?) gets reflection so that I can just iterate through all the base classes recursively and dump them in there, but for now you have to list them out using `sol::base_classes, sol::bases<TruckToy, Toy, ...>`

**Comment by alitteneker** [comment]
That fixes everything! I had completely misread the inheritance documentation.

Sorry for the confusion, and thanks for your help!
