### ISSUE TITLE
Method that returns a sol::table_t to a lua script causes crash..

### ISSUE THREAD

**Issue by HoraceWeebler** [ThePhD/sol2#385]
Maybe I'm doing something wrong here.  I have a member that returns a as_table_t that wraps a vector.  But from lua it is causing a crash deep within vector::size()
```
int test()
{
    struct a
    {
        
    };
    struct b
    {
        b()
        {
            m.insert( { "test", shared_ptr<a>(new a()) } );
        }
        const sol::as_table_t<std::vector<a*>>& GetCommands()
        {
                std::vector<a*> ret;
                for( auto& kvp : this->m )
                {
                    a * be = kvp.second.get();
                    ret.push_back(be);
                }
                return sol::as_table(ret);
        }
        std::map<string, shared_ptr<a>> m;
    };
    b test_obj;
    sol::state lua;
    lua.new_usertype<a>("a");
    lua.new_usertype<b>("b",
                        "GetCommands",
                        &b::GetCommands);

    sol::load_result lr = lua.script(R"(
            p1 = b.new () 
            cmds = p1:GetCommands()
        )");
    if(!lr.valid())
    {
        sol::error err = lr;
        std::string what = err.what();
        std::cout << "call failed, sol::error::what() is " << what << std::endl;
        // return 0;
    }
    else
    {
        sol::protected_function_result result1 = lr(); // lua.do_string("return 24"); // test to make sure it loaded correctly
        if(!result1.valid()) {
            sol::error err = result1;
            std::string what = err.what();
            std::cout << "call failed, sol::error::what() is " << what << std::endl;
        } else
            std::cout << "OK" << std::endl;
    }
return 0;
}
```

\nProgram
 received signal SIGSEGV, Segmentation fault.
0x0000000000420176 in std::vector<test()::a*, std::allocator<test()::a*> >::size(void) const (this=0x0) at /usr/include/c++/5/bits/stl_vector.h:655
655\t      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
Program Received signal SIGSEGV

**Comment by ThePhD** [comment]
Preliminary glance suggests this is the problem:

````
const sol::as_table_t<std::vector<a*>>& GetCommands()
        {
                std::vector<a*> ret;
                for( auto& kvp : this->m )
                {
                    a * be = kvp.second.get();
                    ret.push_back(be);
                }
                return sol::as_table(ret);
        }
````

You're returning a reference to not only the thing you return, but to the internal `std::vector<a*> ret`. Both of these are are values, and returning them by reference -- while allowed by C++ conversion rules -- results in a dangling reference. Most compilers should have warned you that you're returning a temporary or taking the address of a temporary. If it didn't, consider using your equivalent of `-Wall` `-Werror` (g++ flags) or having at least Warning Level 3 or above on (VC++).

**Comment by ThePhD** [comment]
As a side note, to avoid combinatorial explosion of reallocations as the vector resizes itself over and over again to fit the contents of your loop, consider using `ret.reserve(this->m.size());`

Good luck!

**Comment by HoraceWeebler** [comment]
Good call on reserve, I forgot about the resizing costs. I'm fixing the dangling reference now.

**Comment by HoraceWeebler** [comment]
Expected userdata, received no value is the crash now.  Perhaps I don't understand as_table_t well enough to be passing it around.  What am I missing here?  I just want to get my vector of objects into lua.

```
        sol::as_table_t<std::vector<a*>> GetCommands()
        {
                std::vector<a*> ret;
                ret.reserve(m.size());
                for( auto& kvp : this->m )
                {
                    a * be = kvp.second.get();
                    ret.push_back(be);
                }
                sol::as_table_t<std::vector<a*>>  t = sol::as_table(ret);
                return t;
        }
```

**Comment by ThePhD** [comment]
If you just want the `std::vector<a*>`, you can just return that as a plain value and it will be stored just fine. You use `sol::as_table_t` when you want the return to be a table, specifically.

**Comment by HoraceWeebler** [comment]
This compiles, but when I call the GetCommands() from lua a crash ensues.  I must be missing something obvious here. How does one insert a vector and then access that vector in lua to iterate it, etc.
```
        std::vector<a*> GetCommands()
        {
                std::vector<a*> ret;
                ret.reserve(m.size());
                for( auto& kvp : this->m )
                {
                    a * be = kvp.second.get();
                    ret.push_back(be);
                }
                //sol::as_table_t<std::vector<a*>>  t = sol::as_table(ret);
                return ret;
        }
```

**Comment by ThePhD** [comment]
You return the vector, but you have to make sure that you iterate it in a specific way. If you're using Lua 5.1, you're SOL because it doesn't understand iteration well when using a userdata-based container. If you're using Lua 5.2 or Lua 5.3, you can use the Shiny New Iteration Syntax and it will work without crashing your code. A bunch of discussion about this is in [this issue](https://github.com/ThePhD/sol2/issues/250), and some tips and tricks are mentioned on the [containers](http://sol2.readthedocs.io/en/latest/api/containers.html) code.

Be sure to try to trap errors and print them out so I can try to understand what is going wrong, were.

**Comment by HoraceWeebler** [comment]
what():  lua: error: stack index 1, expected userdata, received no value
```
int test()
{
    struct a
    {
        
    };
    struct b
    {
        b()
        {
            m.insert( { "test", shared_ptr<a>(new a()) } );
        }
        //sol::as_table_t<std::vector<a*>> GetCommands()
        std::vector<a*> GetCommands()
        {
                std::vector<a*> ret;
                ret.reserve(m.size());
                for( auto& kvp : this->m )
                {
                    a * be = kvp.second.get();
                    ret.push_back(be);
                }
               // sol::as_table_t<std::vector<a*>>  t = sol::as_table(ret);
                return ret;
        }
        std::map<string, shared_ptr<a>> m;
    };
    b test_obj;
    sol::state lua;
    lua.new_usertype<a>("a");
    lua.new_usertype<b>("b",
                        "GetCommands",
                        &b::GetCommands);
   // lua.set_function("GetCommands", &downcast<command>);
                        
    sol::load_result lr = lua.script(R"(
            p1 = b.new () 
            cmds = p1:GetCommands()
        )");
    if(!lr.valid())
    {
        sol::error err = lr;
        std::string what = err.what();
        std::cout << "call failed, sol::error::what() is " << what << std::endl;
        // return 0;
    }
    else
    {
        sol::protected_function_result result1 = lr(); // lua.do_string("return 24"); // test to make sure it loaded correctly
        if(!result1.valid()) {
            sol::error err = result1;
            std::string what = err.what();
            std::cout << "call failed, sol::error::what() is " << what << std::endl;
        } else
            std::cout << "OK" << std::endl;
    }
return 0;
}
```

**Comment by HoraceWeebler** [comment]
I'm an idiot.sol::load_result lr = lua.script is causing the crash

**Comment by ThePhD** [comment]
The error here in the fixed code is that you're doing `sol::load_result lr = lua.script( .... );`. `lua.script` does not return a `load_result`: it returns a `function_result`, because it executes the script and hands back everything to you. It cannot be properly coerced to a `load_result`, hence the application crashes.

A small copy/paste or typo error... mayhaps in the future I should write a function that takes the state, the script, and then an error function the user defines so they get that called when an error happens in either loading or running the script, instead of the manual C-style checking thing I have going on right now.

**Comment by HoraceWeebler** [comment]
Lol. yes, please add training wheels.  Sorry for that, it was a copy + paste error from a previous test I was running

**Comment by HoraceWeebler** [comment]
Everything works now, as expected.

**Comment by ThePhD** [comment]
I will keep this issue open to remind myself to add some training wheels.

**Comment by ThePhD** [comment]
No docs present, but at least it exists:

````cpp
sol::state lua;
auto result1 = lua.script( "bad.code", &sol::default_on_error );
auto result2 = lua.script( "bad.code", []( lua_State* L, sol::protected_function_result pfr ) {
     // pfr will contain things that went wrong, for either loading or executing the script
     // the user can do whatever they like here, including throw. Otherwise,
     // they need to return the protected_function_result
     return pfr;
});
````

This will allow people to throw more pointed or descriptive errors, and will allow people to more appropriately analyze what went wrong with their scripts.

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/state.html#state-script-function

https://github.com/ThePhD/sol2/blob/develop/examples/basic.cpp
