### ISSUE TITLE
User types may not have __index generated when defined from the constructor of a global

### ISSUE THREAD

**Issue by pushrax** [ThePhD/sol2#391]
I'm running into an issue with binding a seemingly simple member variable. ~~For some reason, the `__index` and `__newindex` metamethods are being named quite weirdly:~~ (found out why, still seems that `__index` is missing though?).

```
> print(vec2.new(1))
vec2(1.000000, 1.000000)

> print(vec2.new(1).x)
[err] [string "$"]:1: attempt to index a sol.glm::tvec2<float, glm::precision::highp> value

> for k,v in pairs(getmetatable(vec2.new(1))) do print(k,v) end
__sub	function: 0x7fe6f9601900
🌲.new_index	function: 0x7fe6f9601a50
__div	function: 0x7fe6f96019e0
__gc	function: 0x7fe6f9601b40
__mul	function: 0x7fe6f96019b0
🌲.index	function: 0x7fe6f9601a10
	function: 0x7fe6f9601ad0
__tostring	function: 0x7fe6f96018c0
__add	function: 0x7fe6f96017d0
__name	sol.glm::tvec2<float, glm::precision::highp>
new	function: 0x7fe6f9601b10

> print(vec2.new(1) + 2) -- operators work
vec2(3.000000, 3.000000)
```

Binding code (result of some templating that produces this):

```c++
lua.new_usertype<glm::vec2>("vec2",
	sol::constructors<glm::vec2(), glm::vec2(float), glm::vec2(float, float)>(),
	"x", &glm::vec2::x,
	"y", &glm::vec2::y,
	"__add", GLMAddVecFunc<glm::vec2, float>(),
	"__sub", GLMSubVecFunc<glm::vec2, float>(),
	"__mul", GLMMulVecFunc<glm::vec2, float>(),
	"__div", GLMDivVecFunc<glm::vec2, float>(),
	"__tostring", GLMToStringFunc<glm::vec2>()
);
```

Structure in glm:

```c++
template <typename T, precision P = defaultp>
struct tvec2
{
// ...
	union {T x, r, s;};
	union {T y, g, t;};
// ...
}

typedef tvec2<float, highp> highp_vec2;
typedef highp_vec2 vec2;
```

The operators all work fine. Any clue what could be going wrong? Is the `__index` bit a red herring? Lua 5.3.4, built as C++. `sol v2.16.0 (revision e27922e)`

**Comment by pushrax** [comment]
Some more info:

```
> print(getmetatable(vec2.new(1))['__index'])
nil

> print(getmetatable(vec2.new(1))['🌲.index'])
function: 0x7f7f62d05a20
```

So it's definitely named that.

Also with

```c++
	"xx", [](const glm::vec2 &v) { return v.x; },
```

I get:

```
> print(vec2.new(1):xx())
[err] [string "$"]:1: attempt to index a sol.glm::tvec2<float, glm::precision::highp> value

> print(getmetatable(vec2.new(1)).xx(vec2.new(1)))
1.0
```

Maybe I'm really not understanding something about Lua metatables?

**Comment by pushrax** [comment]
OK, I found `base_class_index_propogation_key` which explains the utf8 bit, still not sure about the original problem though.

**Comment by ThePhD** [comment]
Cannot repro. I try all of the code you have shown and it works, exactly as advertised, at least on the latest.

Pull from the latest, try the code again, let me know if something's still broken.

![Looks okay to me, Chief](http://i.imgur.com/RQGcyVT.png)

**Comment by pushrax** [comment]
Updating `sol.hpp` didn't change the outcome. I tried reproducing with a minimal external example using the real structures, and it worked fine linked against the exact same lua static lib. I also tried with my template-based binding code copied directly out of the project into that external example, and that worked fine too. Yet in my project this fails:

```c++
sol::state luatest;
usertypes::RegisterGLM(luatest);
luatest.script("print(vec2.new(1).x)");
// luatest is unused for anything else
```

`RegisterGLM(sol::state_view &)` is the same function that worked in my external test. I have it in a separate translation unit in both the real project and the external test. I tried putting the binding in the same translation unit in the real project, and interestingly it worked fine! Next I tried a minimal thing:

```
	void testRegisterGLM(sol::state_view &lua)
	{
		lua.new_usertype<glm::vec2>("vec2",
			sol::constructors<glm::vec2(float)>(),
			"x", &glm::vec2::x
		);
	}
```

in a new translation unit. This failed. Next, I put `testRegisterGLM` in the same translation unit as the state instantiation, and it worked. I then left that function there, switch back to the call to the original `RegisterGLM`, and it kept working! In fact, all the vector types started working (`vec3` etc), just by adding an unused function that bound part of only `vec2`.

I'm going to keep digging since I doubt this can be reproduced easily outside my project, but maybe you have some idea based on your knowledge of sol internals.

**Comment by pushrax** [comment]
Aha, I managed to reproduce it in a minimal example. It's happening because I was initializing the lua state in the constructor of a global. First file:

```c++
#include <sol.hpp>

void RegisterFoo(sol::state_view &lua);

struct Test
{
	Test()
	{
		sol::state lua;
		lua.open_libraries(sol::lib::base);
		RegisterFoo(lua);

		lua.script(R"(
			for k,v in pairs(getmetatable(Foo.new())) do print(k,v) end
			print(Foo.new().x)
		)");
	}
};

Test test;

int main(int argc, char **argv) { return 0; }
```

Second file:
```c++
#include <sol.hpp>

struct Foo
{
	int x = 5;
};

void RegisterFoo(sol::state_view &lua)
{
	lua.new_usertype<Foo>("Foo",
		sol::constructors<Foo()>(),
		"x", &Foo::x
	);
}
```

Output:
```
🌲.index	function: 0x7f8243404ee0
__gc	function: 0x7f8243405050
	function: 0x7f8243405230
__name	sol.Foo
🌲.new_index	function: 0x7f82434051b0
new	function: 0x7f8243405020
libc++abi.dylib: terminating with uncaught exception of type sol::error: lua: error: [string "..."]:3: attempt to index a sol.Foo value
```

**Comment by pushrax** [comment]
This actually looks very similar to this issue: https://github.com/ThePhD/sol2/issues/240

**Comment by ThePhD** [comment]
Oh boy, lemme try to repro it again and see which things it depends on that aren't being initialized...

**Comment by ThePhD** [comment]
Found the culprit, even if the code works fine in a global for me:
````
meta_function_names[static_cast<int>(mf)];
````

`meta_function_names` is a statically-initialized array not hidden inside of a function call. RIP.

**Comment by ThePhD** [comment]
This should be fixed for you, now. Pull the latest.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/releases/tag/v2.17.0

Weee.

**Comment by pushrax** [comment]
It's working perfectly now, thanks for the super quick fix and release.
