### ISSUE TITLE
Writing to the last element of std::vector in Lua increases vector size by 1 (push_back?)

### ISSUE THREAD

**Issue by Penguinum** [ThePhD/sol2#394]
Hello. I was trying to fill std::vector in Lua function and noticed that if you write value to vec[#vec], size of the vector increases by 1, and you actually write to the "new last" element. E.g. if your vector is {0, 0, 0} and you do vec[3] = 1 you get {0, 0, 0, 1}. Probably I'm missing something important, because I can't find anything similar in issues.
Tried both clang and g++, as well as lua5.3 and luajit-2.0. Linux+amd64 if that matters.
This is a working example:
```c++
// g++ test.cpp -std=c++14 -I/usr/include/lua5.3 -llua5.3 -o test
#include <iostream>
#include <vector>
#include "sol.hpp"

int main() {
  sol::state lua;
  lua.open_libraries(sol::lib::base);
  lua.script(
    R"(
    function Fill(vec)
      print("#vec in lua: " .. #vec)
      for k = 1, #vec do
        vec[k] = k
      end
      print("#vec in lua: " .. #vec)
    end
    )");
  std::vector<int> vec{-1, -1, -1};

  std::cout << "#vec in C++: " << vec.size() << std::endl;
  lua["Fill"](vec);
  std::cout << "#vec in C++: " << vec.size() << std::endl;

  for (int i = 0; i < vec.size(); ++i) {
    std::cout << vec[i] << std::endl;
  }
  return 0;
}
```

**Comment by ThePhD** [comment]
This was a failure on my part: I did the `--k` AFTER I did the check for the index being the same as the vector size. There's a test there specifically for this too, so it won't happen again.

Thanks for sharing.

Grab the latest / fix here: https://github.com/ThePhD/sol2/releases/tag/v2.17.0

**Comment by ThePhD** [comment]
Side note: `vec[#vec + 1] = stuff` is a valid (and encouraged) Lua idiom for `push_back`.

**Comment by Penguinum** [comment]
Big thanks for awesome library and for fixing.
