### ISSUE TITLE
Registering C++ class instance object and nonstatic functions

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#40]
**Note : Solved, solution is further down**

I've noticed registering C++ functions, at least the ways described in the API documentation and in the examples, only works if the function is either global or a static class member function.
I've tried it in many different ways Sol2 offers function registration, but so far nothing works. Here is an example:

```C++
class Object {
  Object() :lua() {
	//trying to register nonstatic functions
	this->lua.set_function("nonStaticFunction", &Object::nonStaticFunction); // doesn't work either

	//trying to register static functions
	this->lua.set_function("staticFunction", &Object::staticFunction); // works
  }
	void nonStaticMethod() {};
	static void staticMethod() {};
	sol::state lua;
}
```

I know in the other topic
https://github.com/ThePhD/sol2/issues/36
you told me how to register class instances by just saving a reference value to a lua table (thank you for that! :) ), and it's working fine, now i'd like to know if and how one can register nonstatic class functions.

In your example files you 
-register global C++ functions in Lua, 
-register static C++ class functions in Lua
-or functions of objects that you initialize in Lua, like here
https://github.com/ThePhD/sol2/blob/develop/examples/usertype.cpp
however there is no example of calling nonstatic class functions so when Lua calls a nonstatic C++ function the C++ function can access ```this```and nonstatic instance member variables.

**EDIT**:  **Solution below. i'll leave this here for people who might have the same problem/issue/question:**
I think there is a solution:
I've noticed on your site
http://sol2.readthedocs.org/en/latest/api/table.html
you mention futher down on that site 
```C++
template<typename Key, typename Fx>
state_view& set_function(Key&& key, Fx&& fx, [...]);
```
you mentioned that the this allows passing an object instance pointer and "a member function".
Not sure what you mean by additionally passing an additional member function, but by testing myself i found out that instead of
```C++
	this->lua.set_function("nonStatic", &Object::nonStaticFunction); // throws error
```
using this
```C++
	this->lua.set_function("nonStaticFunction", &Object::nonStaticFunction, this); // ok
```
allows the use of nonstatic functions, thanks to the additional ```this```.
In addition to that you can use lambdas, apparently this way:
```C++
	this->lua.set_function("nonStaticfunction", [this]() {this->nonStaticFunction();});
```
If you register class functions from outside that class i guess you can just replace ```this``` in the lambda/the set_function()-arguments with a pointer or reference to that class instance.

This was quite confusing as none of the example codes showed this (nonstatic functions and access to ```this```) in any way. You may use this for your soon-Tutorial. :)

Curious : is there any performance difference between the ""function", &Object::function, this"-solution and the lambda-solution?

**Comment by ThePhD** [comment]
You're registering a function that, in lua, is called with

```` lua
func( )
````

Nonstatic functions require that you need a `this` object in C++ `Object obj{}; myobj.nonStatic( );`: how would that translate to a  top-level function in lua? The answer is you'd need the `this` object to go with it. This is how `std::bind` and other function makers work. I'll remember to explicitly add a note about his this works in the docs.

**Comment by ThePhD** [comment]
As a side note, I don't know the performance difference offhand. I'll have to check.

Finally, it might be worth it to make it so if you register a function without `this`, that it requires you to pass the `this` when using the function from lua.

**Comment by Nava2** [comment]
Neat idea stemming from this, what about automatic registration by
registering a factory function?

I'm not sure if it'd be possible, but handy.

**Comment by ThePhD** [comment]
I don't get what you mean @Nava2 . The only idea I got from this is if someone registers a non-static member function without the `this`, is that I make it so the `this` has to be passed as the first argument in the lua code or something...

**Comment by Nava2** [comment]
I don't think I really explained myself well. In addition, what I meant is already present (I've even used it). I just had a sleep deprived thought. Oops. 

I was talking about what happens with `new_usertype` where it lets Lua associate a `this` argument.
