### ISSUE TITLE
Macro redefinition warning with LuaJIT 2.1.0-beta3 

### ISSUE THREAD

**Issue by menezes-** [ThePhD/sol2#403]
I was testing the new version of LuaJit and when compiling my program i got some macro redefinition warning that didn't happened with version -beta2. I haven't found any issues so far, the library seems to work as before.  

System: 
GCC 6.3.1 20170306
Arch linux 4.10.13-1-ARCH

Warning:
```
sol.hpp:1114:0: warning: "luaL_newlib" re-definido
 #define luaL_newlib(L, l) \
 
In file included from /usr/local/include/luajit-2.1/lua.hpp:5:0,
                 from sol.hpp:801,
                 from main.cpp:1:
/usr/local/include/luajit-2.1/lauxlib.h:125:0: note: essa é a localização da definição anterior
 #define luaL_newlib(L, l) (luaL_newlibtable(L, l), luaL_setfuncs(L, l, 0))
```

Test program:
```cpp
#include "sol.hpp"
#include <iostream>

int main(){
    sol::state lua;
    // open some common libraries
    lua.open_libraries(sol::lib::base, sol::lib::package);
    lua.script( "print('bark bark bark!')" );

    std::cout << lua_version(lua.lua_state()) << '\n'; // lua_version was added in beta3

    return 1;
}
```

Compile command: 
```bash
g++ -std=c++14 main.cpp -Ixxx -Lxxx -lluajit-5.1 -o main
```

**Comment by ThePhD** [comment]
That's unfortunate. I'll have to update the wrapper to handle the new LuaJIT beta changes... Hopefully hte LUAJIT_VERSION defines and macros have something I can use to tell that it's beta3 versus beta1/beta2.

**Comment by menezes-** [comment]
Not entirely sure if this applies to this problem but there was a discussion on the luajit mailing list about detecting the lua version maybe it helps:
https://www.freelists.org/post/luajit/ANN-LuaJIT210beta3,3

**Comment by ThePhD** [comment]
Added a basic check for LuaJIT 2.1.0. Note that it will fail beta2 users, as the major version number is still the same and LuaJIT, for some reason, doesn't change the patch with its semver scheme I guess.

**Comment by mrgreywater** [comment]
1>luajit.lib(lj_api.obj) : error LNK2005: _luaL_setmetatable already defined in main.obj <luajit\src\lj_api.c-L1048>
1>luajit.lib(lj_api.obj) : error LNK2005: _luaL_testudata already defined in main.obj <luajit\src\lj_api.c-L923>
1>luajit.lib(lj_api.obj) : error LNK2005: _lua_copy already defined in main.obj <luajit\src\lj_api.c-L191>
1>luajit.lib(lj_api.obj) : error LNK2005: _lua_tointegerx already defined in main.obj <luajit\src\lj_api.c-L408>
1>luajit.lib(lj_api.obj) : error LNK2005: _lua_tonumberx already defined in main.obj <luajit\src\lj_api.c-L345>
1>luajit.lib(lj_api.obj) : error LNK2005: _lua_version already defined in main.obj <luajit\src\lj_api.c-L115>
1>luajit.lib(lib_aux.obj) : error LNK2005: _luaL_setfuncs already defined in main.obj <luajit\src\lib_aux.c-L137>

these are also all already defined in LuaJIT-2.1.0-beta3 (compiled with windows+msvc14)
