### ISSUE TITLE
getting nested optional value causes crash

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#404]
Using optional from boost with `SOL_USE_BOOST` and trying to get nested value from the nonexistent table causes application to fail.
So the code
```cpp
sol::state lua;
sol::optional<int> will_not_error = lua["abc"]["DOESNOTEXIST"];
```
will error. In LuaJIT 2.0.4 it crashes with exception `Exception thrown at 0x0FA24F2F (lua51.dll) in Sol-LuaJIT.exe: 0xC0000005: Access violation writing location 0x00000007`.
In Lua 5.3 this:
![default](https://cloud.githubusercontent.com/assets/6823037/26035937/7b40ed02-38dd-11e7-922a-98ba66958f7e.png)

Tested with boost v.1.60.0 and v.1.64.0; x86 build.

**Comment by ThePhD** [comment]
For some unknown reason, this compile-time check evaluates to `std::false_type` when using `boost::optional` aliased to `sol::optional`:

`meta::is_specialization_of<sol::optional, meta::unqualified_t<T>>`

Where `T` is, indeed, a `boost::optional`. I don't now why it's failing so spectacularly.

**Comment by ThePhD** [comment]
This might be a VC++-exclusive bug, it seems. Something about the crappy way they handle qualified names.

**Comment by ThePhD** [comment]
Apparent fix is to create a struct which forces a template specialization, and I get to name it `is_optional`. Yay, more boilerplate for me...

**Comment by ThePhD** [comment]
Fixed, and other uses of the template alias should be purged, so you should theoretically be all set:

https://github.com/ThePhD/sol2/releases/tag/v2.17.3

**Comment by THE-FYP** [comment]
Yep, now it's fine. Thanks.
