### ISSUE TITLE
Nested movable usertype

### ISSUE THREAD

**Issue by nyorain** [ThePhD/sol2#406]
Hey, first of all thanks for the amazing piece of work, it was a pleasure to it so far!

Not entirely sure if this is really a bug (and even if it is, not sure it is a bug in sol2) but i was able to test it
with clang 4.0 and gcc 6.3 using c++14 as well as (the partial support for) c++17 on arch linux and the error was produced in all cases.
Consider the following codesnippet (the most minimal i could get it):

```cpp
#include <sol.hpp>
#include <iostream>

struct SomeNonCopyable {
	SomeNonCopyable() = default;

	// XXX: comment the following 2 lines out to make it work
	SomeNonCopyable(SomeNonCopyable&& other) noexcept = default;
	SomeNonCopyable& operator=(SomeNonCopyable&& other) noexcept = default;

	SomeNonCopyable(const SomeNonCopyable& other) = delete;
	SomeNonCopyable& operator=(const SomeNonCopyable& other) = delete;
};

struct B {
	SomeNonCopyable unused;
	int val {42};
};

struct A {
	B b;
};

int main()
{
	sol::state state;
	state.open_libraries(sol::lib::base);

	state.new_usertype<B>("B",
		sol::meta_function::construct, sol::no_constructor,
		"val", &B::val);

	state.new_usertype<A>("A",
		sol::meta_function::construct, sol::no_constructor,
		"b", &A::b); // XXX: could use dynamic property here

	A a {};
	state["a"] = &a;
	state.script("print(a.b.val)");
}
```

I would expect this to at least compile (i never actually copy anything) but it does not. A workaround 
I found is simply using a dynamic property for B::val when creating the usertype but i guess it should
work this way shouldn't it?
But it gets stranger: When commenting out the explicitly defaulted move operator/constructor in
SomeNonCopyable it works. Although explicitly defaulting those should not really change anything (afaik) since the copy operator/constructor is disabled anyways.
Actually caused me some headache to track this down and have still no clue what this could be.

Any ideas on this?

**Comment by ThePhD** [comment]
Fixed. Original code should work as advertised.

Backported into 2.17.3:
https://github.com/ThePhD/sol2/releases/tag/v2.17.3
