### ISSUE TITLE
get<T>()-chaining doesn't work

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#41]
In this example code
https://github.com/ThePhD/sol2/blob/develop/examples/tables.cpp
at the very bottom there is get<T>-chaining as an example.
```C++
lua.get<sol::table>("table2").get<sol::table>("nestedTable").get<std::string>("key2")
```
However if i try to copy that code snippet to my Visual Studio 2015 only the first ```get<sol::table>()``` gets accepted. The second ```get<sol::table>()``` and the  ```get<std::string>()``` get red marks, with the note "Error : type name not allowed"

If i type in the first
```C++
lua.get<sol::table>("table2")
```
and add a dot (".") after the ")" usually Visual studio then shows me possible member functions/variables that can follow, however nothing is displayed.
If chaining were allowed and working properly, then typing a dot would usually reveal a list, showing all the possible member functions and variables that could follow.

**Comment by ThePhD** [comment]
Intellisense is known to be dumb. In this case, it is being the dumb. There's nothing wrong with the API. The fix is for intellisense to stop being a piece of shit.
