### ISSUE TITLE
simple_usertype<t> with newindex / index

### ISSUE THREAD

**Issue by babyjeans** [ThePhD/sol2#410]
It's not in the documentation, but perhaps it was just an oversight - I can't seem to bind `new_index` or `index` when using a simple usertype. For my particular application, I can't create the entire usertype at once, so I was hopeful to see I can use the `set` function with simple usertypes... however, the getter / setter are never called using this test code:

```
class CTestType {
public:
	CTestType() { ; }
	static std::shared_ptr<CTestType> NewTest() {
		return std::make_shared<CTestType>();
	}

	sol::object getter(const std::string& _name, sol::this_state _s) {
		if (_name == "a") {
			return sol::make_object(_s, 2);
		} 

		sol::state_view L(_s);
		return sol::object(_s, sol::in_place, sol::nil);
	}

	void setter(const char* _name, sol::object _val, sol::this_state _s) {
	
	}
};

void print(const std::string& _msg) {
	std::string msg(_msg);
	msg = _msg;
}

void main() {
	sol::state lua;
	
	{
		lua["print"] = &print;
		lua.new_simple_usertype<CTestType>("test",
			sol::call_constructor, sol::factories(&CTestType::NewTest),
			sol::meta_function::index, &CTestType::getter,
			sol::meta_function::new_index, &CTestType::setter
		);
	}

	lua.script(R"(	
		local t = test()
		print(t.a)
	)");
}
```

but if I use a regular `usertype<T>` then it's fine.

Are the metamethods just not supported for the simple_usertype?

**Comment by babyjeans** [comment]
Since my main issue is that I wanted to dynamically add functions as well, I'm just returning functions in the index method for now. This works just dandy, but it still seemed a little weird they didn't work with a simple usertype.

**Comment by ThePhD** [comment]
Thanks for reporting. This was fixed with a major overhaul of the simple_usertype implementation underneath. Performance investigation is still pending, but correctness >>> performance, and it should not really degrade at all given we're still sticking to lifting as much computation to compile-time as possible.

Good luck with sol2

**Comment by ThePhD** [comment]
Pull from the latest or download from the latest single/sol/sol.hpp to get going.

**Comment by babyjeans** [comment]
Thanks a ton for the update!
