### ISSUE TITLE
Can't update simple_usertype at runtime when using index/newindex metamethods

### ISSUE THREAD

**Issue by babyjeans** [ThePhD/sol2#413]
Using this code:
```
auto registration(lua.create_simple_usertype<CTestType>());
registration.set(sol::call_constructor,       sol::constructors<CTestType()>());
registration.set(sol::meta_method::index,     &CTestType::getter);
registration.set(sol::meta_method::new_index, &CTestType::setter);
lua.set_usertype("test", registration);

lua["test"]["hi"] = [](CTestType& _self) { _self.hi(); };
```
This line:

`lua["test"]["hi"] = [](CTestType& _self) { _self.hi(); };`

Throws:

`lua: error: lua: error: lua: error: sol: received nil for 'self' argument (use ':' for accessing member functions, make sure member variables are preceeded by the actual object with '.' syntax)`

It **doesn't** hit the getter/setter, but without them it does work. I'm not sure if I'm just pushing the limits here, but figured I'd report it.

**Comment by ThePhD** [comment]
There's a long explanation about why this doesn't work and stuff (and why its also a bug), but let's just make it short. To start, pull from the latest. Then, observe the following:

2. You can set `index` and `new_index` freely on any usertype you like
3. `new_index` and `index` will not be called if you try to manipulate the __named usertype table directly__. This means modifying `test` (as in your code) will not call your `new_index` function, but sol2's instead to add that function to the usertype's table.
4) `new_index` and `index` will be called if you attempt to call a key _that does not exist on an actual userdata object_. That means `t = test()`, with `t.hi = 54` will call your function, but `test.hi = 54` will not.

**Comment by babyjeans** [comment]
The behavior that is has now, as of this pull, is actually what I **did** expect -  my goal _was_ to bind additional functions to the objects (a la classes) and _not_ go through my setter/getter - so thanks so much for another quick fix. This is 100% the behavior I was going for.

**Comment by ThePhD** [comment]
@babyjeans 👍

Go get 'em!

**Comment by ThePhD** [comment]
Added a note in the docs here to make sure I don't forget the behaviors: http://sol2.readthedocs.io/en/latest/usertypes.html
