### ISSUE TITLE
Question about usertype memory/Lua C API

### ISSUE THREAD

**Issue by squeek502** [ThePhD/sol2#416]
I was trying to use the Lua C API to retrieve a pointer to a usertype that was bound by Sol2 and got a bit confused. After some testing, it seems like what works (in the few cases I tried) is `T* val = *static_cast<T**>(lua_touserdata(L, -1))`, and I'm confused as to whether or not that conflicts with [the usertype memory docs](http://sol2.readthedocs.io/en/latest/api/usertype_memory.html).

I guess I don't have a specific question, just want to make sure this is intended.

Here's some test code that tests against the current functionality:
```c++
#define SOL_CHECK_ARGUMENTS
#include <catch.hpp>
#include <sol.hpp>

TEST_CASE("getting a usertype using the Lua C API")
{
	struct thing {
		int val;
	};

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<thing>("thing");

	thing a;
	a.val = 10;

	SECTION("pushing the value")
	{
		lua["a"] = a;
		lua_getglobal(lua, "a");
		REQUIRE(lua_isuserdata(lua, -1));
		void* raw = lua_touserdata(lua, -1);
		thing* actual = *static_cast<thing**>(raw);
		REQUIRE(actual->val == 10);
		lua_pop(lua, 1);
	}

	SECTION("pushing the pointer")
	{
		lua["a"] = &a;
		lua_getglobal(lua, "a");
		REQUIRE(lua_isuserdata(lua, -1));
		void* raw = lua_touserdata(lua, -1);
		thing* actual = *static_cast<thing**>(raw);
		REQUIRE(actual->val == 10);
		lua_pop(lua, 1);
	}
}
```

**Comment by ThePhD** [comment]
This is intended. It does not conflict with the usertype documentation.

`lua_touserdata` hands you a pointer to memory. We tell you what is in the memory. The first `sizeof(void*)` bytes is a `T*` pointer. If you are handed a `void*` pointer to a block of memory __inside which lies a pointer__ typed pointer, `static_cast<T**>` is how you would access it. Note that we place the __value__ of the pointer inside the first `sizeof(void*)` bytes, not the actual value of `T`.

**Comment by squeek502** [comment]
Appreciate the clarification. 👍

**Comment by ThePhD** [comment]
Added docs to make sure people in the future are guided: http://sol2.readthedocs.io/en/latest/api/usertype_memory.html#to-retrieve-a-t
