### ISSUE TITLE
Can't return a userdata from a bound usertype function:

### ISSUE THREAD

**Issue by Samulus** [ThePhD/sol2#418]
I'm trying to bind [this specific method in this library](https://github.com/ilmola/gml/blob/master/include/gml/vec.hpp#L141) (and more in the future from this lib after I get this one working) but sol2 generates a massive compilation error whenever I try to compile any variation of this code that would result in a gml::vec3 being returned:

```c++
void GMLWrapper::bind(sol::state& lua) {
   auto math = lua.create_named_table("gml");

   /// Vectors
   math.new_usertype<gml::vec3>("vec3",
         sol::constructors<gml::vec3(), gml::vec3(float, float, float)>(),
         // Fails to Compile
         sol::meta_function::multiplication, [] (gml::vec3 lhs, gml::vec3 rhs) -> gml::vec3 {
            return lhs * rhs;
         },
         // Fails to Compile
         sol::meta_function::multiplication, sol::resolve<gml::vec3 (const gml::vec3&) const>(&gml::vec3::operator*),
         // Compiles Correctly
         sol::meta_function::index, static_cast<float& (gml::vec3::*)(int)>(&gml::vec3::operator[])
   );
}
```

What i'm trying to accomplish is allowing the user in Lua to do:

```lua
local v1 = gml.vec3.new(1,2,3)
local v2 = gml.vec3.new(4,5,6)
local result = v1 * v2;
```

This happens using ``g++ (GCC) 7.1.1 20170516``, sol2 revision: ``7168c31``

I've attached the resulting error message. 
[error.txt](https://github.com/ThePhD/sol2/files/1051534/error.txt)

**Comment by ThePhD** [comment]
Tied to #414 possibly.

**Comment by ThePhD** [comment]
Also of note: `gml::vec` has `begin` and `end` types: it is likely tagging it as a `container_usertype` -- please make sure to follow the instructions for [too eager container detection](http://sol2.readthedocs.io/en/latest/api/containers.html#too-eager-container-detection) in the documentation.

**Comment by Samulus** [comment]
Yep that fixed it, I have no idea what kind of magic incantation that line does to get things working but I'll gladly use it! Here is the working snippet:

```c++
template <> struct sol::is_container<gml::vec3> : std::false_type {};

void GMLWrapper::bind(sol::state& lua) {
   auto math = lua.create_named_table("gml");

   /// Vectors
   math.new_usertype<gml::vec3>("vec3",
         sol::constructors<gml::vec3(), gml::vec3(float, float, float)>(),

         sol::meta_function::multiplication, [] (gml::vec3 lhs, gml::vec3 rhs) {
            return lhs * rhs;
         },

         sol::meta_function::index, [] (gml::vec3 self, int i) {
            return self[i-1];
         }
   );

}
```

Thanks for the quick update and awesome library!
