### ISSUE TITLE
Feature request : optional std::cout << error instead of throw(error)

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#42]
EDIT: Just found out that you commented on this in the readme -.- damn i'm dumb/blind... need moar sleep. XD I'm so sorry.

I've noticed with Sol2 when a Lua error is detected (syntax error, trying to index nil values, etc) the program throws an error and the program gets aborted/stopped.
In the state_view.hpp:
```C++ 
namespace sol {
namespace detail {
inline int atpanic(lua_State* L) {
#ifdef SOL_NO_EXCEPTIONS
	(void)L;
	return -1;
#else
	const char* message = lua_tostring(L, -1);
	std::string err = message ? message : "An unexpected error occurred and forced the lua state to call atpanic";
	throw error(err);
#endif
}
} // detail
```
Would it be possible to add an "error handling"-option for the ```sol::state``` where the user can choose to 
-```throw()``` the error message (abort/disrupt the C++ program), like it is now or
-```std::cout``` the error message to console (don't destroy lua-state and don't abort/disrupt the C++ progam, instead abort the currently active lua-activity, return to C++, let the C++ program continue and show Lua error message in console).

Many use Lua in combination with C++ so they have a part of the program (Lua) that does not neccessarily crash the entire program if an error occurs in that part. 
In many cases and for many users, the only reason where an error in the Lua part should crash/disrupt the entire program if C++ expects a return value from Lua but Lua has an error (resulting in C++ not getting any return or getting wrong returns), but in that case it's the C++s side to handle that situation.
That's why i think adding an option to ```std::cout``` the error to the console, return to C++ and let the C++ program continue would be a really nice feature (so people have the choice of either throwing each time an error occurs or letting the program continue with a displayed error message in the console).

Another good reason for an error console output would be because, at least in Visual Studio 2015, the compiler optimizes the throw()-error away when compiling the release version:
```
err	Error reading register value.	
L	Variable is optimized away and not available.	
message	Variable is optimized away and not available.	
```
So in the release version there is no indication what actually went wrong in the Lua files, which is bad when you want your users to be able to modify/add lua files to your program. If i try to catch the ``` std::runtime_error``` thrown by Sol2, like this
```C++
		try { 
			this->lua["updateGame"](dt); 
		}
		catch (const sol::error& e) { 
			std::cout << e.what() << std::endl; 
		}
```
in debug-mode it works, the error message gets displayed in the console and the program continues. In release mode however the error message from the Sol2-function ```atpanic``` gets optimized away, making the try-catch not working anymore. So again, a "print-to-console-and-continue-in-C++ instead of throw()"-option would be useful.

An console-printed error message would also allow users who later use the released software to edit/add lua files to the program and see error message without the program getting closed due to the throw().

**Comment by Nava2** [comment]
I don't like the idea of having a raw `cout` being used everything, that seems very specific.

What about taking the same approach as Lua and have a `sol::atpanic` style functor available? Set it if you want it, don't otherwise. It would add overhead, though. That being said, I don't think it'd be much.

**Comment by ThePhD** [comment]
This was anticipated and is part of the API. From the docs [here](http://sol2.readthedocs.org/en/latest/api/state.html#set-panic), you can specify your own `at_panic` function. The constructor for `sol::state` also takes an optional `at_panic` function.

E.g.:

````

int my_panic( lua_State* L ) {
    // Do whatever you like.
    std::cerr << lua_tostring(L, -1) << std::endl;
}

sol::state lua(my_panic);
lua.script("bad.code = toplel");
````

I really need to finish writing a tutorial. .-.
