### ISSUE TITLE
compiler is out of heap space

### ISSUE THREAD

**Issue by qfrtt** [ThePhD/sol2#420]
Hey im using sol2 for my application and to make an api im using the "simple_usertype<T>" but since my api is big im getting "compiler is out of heap space" errors. I tried to remove all the classes i made and i just realised that one "simple_usertype<T>" call adds 300kb to the compiled file , i thought that it was a problem with my application so i decided to try it in a new clean visual studio project and it's still the same it's eating too much ram for the compiler. I am using Luajit but i already tried it with a normal lua i still go the same issue. Any solution ? im using VS2017

**Comment by OrfeasZ** [comment]
Take a look [here](https://github.com/ThePhD/sol2/issues/329#issuecomment-276824983).

**Comment by qfrtt** [comment]
Thanks

**Comment by ThePhD** [comment]
I should add a note about this to the documentation at some point...

**Comment by ThePhD** [comment]
It's in there, now: http://sol2.readthedocs.io/en/latest/compilation.html#compiler-out-of-heap-space
