### ISSUE TITLE
Destroying a lua state

### ISSUE THREAD

**Issue by Aykelith** [ThePhD/sol2#421]
I have an engine, kind of, in which I use Sol2/Lua to create GUI. For every window I have an separate Sol2 state and some functions from the Lua script are bound to some buttons callbacks or specific events. When the button which send the user from one window to another is pressed the Lua function is called and in the Lua function a C++ function is called in which is created another Sol2 state with the new window and the actual window is closed. But I want to destroy/clean the old window, the old Lua state which is now useless but I can't delete the state in the bounded Lua function and so I tried in a thread and using a mutex but still no success. I'm getting, sometimes, only sometimes, crash referring to different things such as Sol2 trying to destroy some object. I wants some tips/help: how should I optimally handle the situation?

**Comment by ThePhD** [comment]
You can't destroy the Lua state you're working inside from a C++-bound function _in that state_.  I'm assuming this function gets called from a script.

Submit a command to a command queue. Check the command queue either before or after you start running your Lua VM. Submit a command to kill your state, pull it out in that command queue, and when your state is done running, kill your state, and then spin-up a fresh Lua VM after you're done.

**Make sure all references to things that come from old states are absolutely killed / removed from your code, in any way, shape, or form.** When you destruct the Lua state, every other `sol::reference` or similar type should also be dead / destructed. Not doing so will cause problems.

**Comment by ThePhD** [comment]
For example:

````
std::unique_ptr<sol::state> lua_window_state = std::make_unique<sol::state>();
while (1) {
     do_script(*lua_window_state, some_code);
     optional<command> maybe_cmd = cmd_queue.try_pop();
     if (maybe_cmd) {
          command& cmd = &maybe_cmd;
          if (is_quit_command(cmd)) {
               // kill Lua state
               lua_window_state.reset();
          }
     }
}
````

Adapt/change/revise/morph to your needs. Note that we don't use a "different thread" here, because putting the work on a different thread doesn't solve your problem (Order-Of-Operations, not Timing or anything else). You need to guarantee you're done with your Lua state: typically, that comes after you're done executing a script on it.
