### ISSUE TITLE
AppVeyor for VS 2017/2015 | Travis for g++ 7/6/5 , clang++ 3.7/3.8/3.9/4.0

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#425]
All of the old test harnesses should be placed into "Allowed Failures" buckets, including VS 2015. This will let us know what commit _exactly_ breaks a certain compiler level, albeit it would mean tests would take an additional hour to complete in the cloud (mostly because of additional XCode imaging setup).

- [x] Travis CI:
     + [x] g++ 5.3
     + [x] g++ 5.4
     + [x] g++ 6.3
     + [x] g++ 7.1
     + [x] clang++ 3.6
     + [x] clang++ 3.7
     + [x] clang++ 3.8
     + [x] clang++ 3.9
     + [x] clang++ 4.0

- [x] AppVeyor:
     + [x] Visual Studio 2015, Latest (allowed failure)
     + [x] Visual Studio 2017, Latest

All older tests should be bundled up as "allowed failures"

**Comment by ThePhD** [comment]
The current matrix for installing and setting up Lua and stuff is going to be hard to manage to extend to all these compilers and services...

I think I need to re-architect how I grab our Lua version and how I grab the compiler, especially for things working off Ubuntu Trusty. Either that, or perhaps it's time to work with Docker for the Linux-based stuff, so I can have cleaner images...? Our build times will increase by quite a bit, but it will allow me to have access to higher versions of G++ and clang++ without hitting ppa repo links.

**Comment by ThePhD** [comment]
So right now, I have my own VS 2017 projects locally that I use to run the test suite and all. But, I need to have something that generates a VS 2017/2015 project for AppVeyor.

It... looks like it's CMake time, at least for the tests.

**Comment by Nava2** [comment]
@ThePhD #23 sources may still be useful.

**Comment by ThePhD** [comment]
Note to self.

We should test Lua 5.1, 5.2, 5.3 and JIT on the latest compiler for each major platform (Windows, OSX, Linux).

Then, we should use the latest Lua (5.3) and test it across all of the compilers listed above. That way, we have less semi-duplicate entries and still cover a wide berth of compilers and architectures.

**Comment by ThePhD** [comment]
Latest release makes some very good headway into properly testing on all architectures and platforms, eliminating many of the issues with attempting to use `REQUIRE_THROWS` through the Lua API: https://github.com/ThePhD/sol2/releases/tag/v2.18.0

Next step is to actually overhaul the entire testing framework. The goal is to get acquainted with CMake, and use Docker to spin up the latest Ubuntu. The goal is to also download the lua version we want directly from the website, compile, and then build the Lua we need directly to build our tests against. @Nava2 's sources will help greatly with achieving this... but, for now.

I'm going to take a nap...

**Comment by Nava2** [comment]
This is super useful in CMake builds: 

https://github.com/LuaDist/lua

Use `ExternalProject_Add()` https://cmake.org/cmake/help/v3.2/module/ExternalProject.html

I could look at this if you'd like a hand.

**Comment by ThePhD** [comment]
#493 does all the heavy lifting.

When I merge that, I'll update the test harnesses all at once to use the new cmake stuff. If it works, then I can probably scrap all the ninja stuff I have, wee!

**Comment by ThePhD** [comment]
The PR for the CMakeLists has been committed.

Now it's just getting docker going to make it easy to pick a distro to use, in combination with getting appveyor up and running too...

**Comment by ThePhD** [comment]
This issue hasn't been forgotten, it's just tough to do properly.

I'm defining an external project using CMake to pull an exact version of Lua straight off their download FTP. This allows me to (flexibly) pull a target and then build it. It also enables Appveyor to be less strange, since the idea of a unified place to dump dynamic libraries, executables, headers and static/import libraries isn't exactly standardized on Windows and it would not be able to find a Lua install on Appveyor (probably).

It's been an... adventure. Hopefully I can commit something in the new few days...

**Comment by ThePhD** [comment]
````
test@testvb [09:10:51 PM] [~/build-sol2] 
-> % ctest
Test project /home/test/build-sol2
        Start   1: tests
  1/126 Test   #1: tests ....................................   Passed    0.99 sec
        Start   2: tests_single
  2/126 Test   #2: tests_single .............................   Passed    0.99 sec
        Start   3: any_return
  3/126 Test   #3: any_return ...............................   Passed    0.00 sec
        Start   4: any_return.single
  4/126 Test   #4: any_return.single ........................   Passed    0.00 sec
        Start   5: basic
  5/126 Test   #5: basic ....................................   Passed    0.00 sec
        Start   6: basic.single
  6/126 Test   #6: basic.single .............................   Passed    0.00 sec
        Start   7: calling_lua_functions
  7/126 Test   #7: calling_lua_functions ....................   Passed    0.00 sec
        Start   8: calling_lua_functions.single
  8/126 Test   #8: calling_lua_functions.single .............   Passed    0.00 sec
        Start   9: config
  9/126 Test   #9: config ...................................   Passed    0.01 sec
        Start  10: config.single
 10/126 Test  #10: config.single ............................   Passed    0.01 sec
        Start  11: container_usertype_as_container
 11/126 Test  #11: container_usertype_as_container ..........   Passed    0.01 sec
        Start  12: container_usertype_as_container.single
 12/126 Test  #12: container_usertype_as_container.single ...   Passed    0.01 sec
        Start  13: containers
 13/126 Test  #13: containers ...............................   Passed    0.00 sec
        Start  14: containers.single
 14/126 Test  #14: containers.single ........................   Passed    0.01 sec
        Start  15: containers_as_table
 15/126 Test  #15: containers_as_table ......................   Passed    0.00 sec
        Start  16: containers_as_table.single
 16/126 Test  #16: containers_as_table.single ...............   Passed    0.01 sec
        Start  17: coroutine
 17/126 Test  #17: coroutine ................................   Passed    0.00 sec
        Start  18: coroutine.single
 18/126 Test  #18: coroutine.single .........................   Passed    0.01 sec
        Start  19: coroutine_state
 19/126 Test  #19: coroutine_state ..........................   Passed    0.00 sec
        Start  20: coroutine_state.single
 20/126 Test  #20: coroutine_state.single ...................   Passed    0.01 sec
        Start  21: customization
 21/126 Test  #21: customization ............................   Passed    0.01 sec
        Start  22: customization.single
 22/126 Test  #22: customization.single .....................   Passed    0.01 sec
        Start  23: customization_convert_on_get
 23/126 Test  #23: customization_convert_on_get .............   Passed    0.00 sec
        Start  24: customization_convert_on_get.single
 24/126 Test  #24: customization_convert_on_get.single ......   Passed    0.00 sec
        Start  25: dynamic_object
 25/126 Test  #25: dynamic_object ...........................   Passed    0.01 sec
        Start  26: dynamic_object.single
 26/126 Test  #26: dynamic_object.single ....................   Passed    0.01 sec
        Start  27: environment_snooping
 27/126 Test  #27: environment_snooping .....................   Passed    0.01 sec
        Start  28: environment_snooping.single
 28/126 Test  #28: environment_snooping.single ..............   Passed    0.01 sec
        Start  29: environment_state
 29/126 Test  #29: environment_state ........................   Passed    0.00 sec
        Start  30: environment_state.single
 30/126 Test  #30: environment_state.single .................   Passed    0.01 sec
        Start  31: environment_state_2
 31/126 Test  #31: environment_state_2 ......................   Passed    0.01 sec
        Start  32: environment_state_2.single
 32/126 Test  #32: environment_state_2.single ...............   Passed    0.00 sec
        Start  33: environments
 33/126 Test  #33: environments .............................   Passed    0.00 sec
        Start  34: environments.single
 34/126 Test  #34: environments.single ......................   Passed    0.01 sec
        Start  35: environments_on_functions
 35/126 Test  #35: environments_on_functions ................   Passed    0.00 sec
        Start  36: environments_on_functions.single
 36/126 Test  #36: environments_on_functions.single .........   Passed    0.01 sec
        Start  37: functions
 37/126 Test  #37: functions ................................   Passed    0.01 sec
        Start  38: functions.single
 38/126 Test  #38: functions.single .........................   Passed    0.00 sec
        Start  39: indirect_function_calls
 39/126 Test  #39: indirect_function_calls ..................   Passed    0.01 sec
        Start  40: indirect_function_calls.single
 40/126 Test  #40: indirect_function_calls.single ...........   Passed    0.00 sec
        Start  41: multi_results
 41/126 Test  #41: multi_results ............................   Passed    0.01 sec
        Start  42: multi_results.single
 42/126 Test  #42: multi_results.single .....................   Passed    0.01 sec
        Start  43: optional_with_iteration
 43/126 Test  #43: optional_with_iteration ..................   Passed    0.01 sec
        Start  44: optional_with_iteration.single
 44/126 Test  #44: optional_with_iteration.single ...........   Passed    0.01 sec
        Start  45: overloading
 45/126 Test  #45: overloading ..............................   Passed    0.00 sec
        Start  46: overloading.single
 46/126 Test  #46: overloading.single .......................   Passed    0.01 sec
        Start  47: overloading_with_fallback
 47/126 Test  #47: overloading_with_fallback ................   Passed    0.00 sec
        Start  48: overloading_with_fallback.single
 48/126 Test  #48: overloading_with_fallback.single .........   Passed    0.00 sec
        Start  49: pairs
 49/126 Test  #49: pairs ....................................   Passed    0.01 sec
        Start  50: pairs.single
 50/126 Test  #50: pairs.single .............................   Passed    0.00 sec
        Start  51: pairs_with_raw_functions
 51/126 Test  #51: pairs_with_raw_functions .................   Passed    0.01 sec
        Start  52: pairs_with_raw_functions.single
 52/126 Test  #52: pairs_with_raw_functions.single ..........   Passed    0.01 sec
        Start  53: protected_functions
 53/126 Test  #53: protected_functions ......................   Passed    0.00 sec
        Start  54: protected_functions.single
 54/126 Test  #54: protected_functions.single ...............   Passed    0.01 sec
        Start  55: require
 55/126 Test  #55: require ..................................   Passed    0.00 sec
        Start  56: require.single
 56/126 Test  #56: require.single ...........................   Passed    0.00 sec
        Start  57: runtime_additions
 57/126 Test  #57: runtime_additions ........................   Passed    0.01 sec
        Start  58: runtime_additions.single
 58/126 Test  #58: runtime_additions.single .................   Passed    0.01 sec
        Start  59: script_error_handling
 59/126 Test  #59: script_error_handling ....................   Passed    0.01 sec
        Start  60: script_error_handling.single
 60/126 Test  #60: script_error_handling.single .............   Passed    0.00 sec
        Start  61: self_from_lua
 61/126 Test  #61: self_from_lua ............................   Passed    0.01 sec
        Start  62: self_from_lua.single
 62/126 Test  #62: self_from_lua.single .....................   Passed    0.01 sec
        Start  63: singleton
 63/126 Test  #63: singleton ................................   Passed    0.01 sec
        Start  64: singleton.single
 64/126 Test  #64: singleton.single .........................   Passed    0.00 sec
        Start  65: stack_aligned_function
 65/126 Test  #65: stack_aligned_function ...................   Passed    0.01 sec
        Start  66: stack_aligned_function.single
 66/126 Test  #66: stack_aligned_function.single ............   Passed    0.00 sec
        Start  67: static_variables
 67/126 Test  #67: static_variables .........................   Passed    0.01 sec
        Start  68: static_variables.single
 68/126 Test  #68: static_variables.single ..................   Passed    0.01 sec
        Start  69: tables
 69/126 Test  #69: tables ...................................   Passed    0.01 sec
        Start  70: tables.single
 70/126 Test  #70: tables.single ............................   Passed    0.00 sec
        Start  71: usertype
 71/126 Test  #71: usertype .................................   Passed    0.00 sec
        Start  72: usertype.single
 72/126 Test  #72: usertype.single ..........................   Passed    0.00 sec
        Start  73: usertype_advanced
 73/126 Test  #73: usertype_advanced ........................   Passed    0.01 sec
        Start  74: usertype_advanced.single
 74/126 Test  #74: usertype_advanced.single .................   Passed    0.01 sec
        Start  75: usertype_automatic_operators
 75/126 Test  #75: usertype_automatic_operators .............   Passed    0.00 sec
        Start  76: usertype_automatic_operators.single
 76/126 Test  #76: usertype_automatic_operators.single ......   Passed    0.00 sec
        Start  77: usertype_bitfields
 77/126 Test  #77: usertype_bitfields .......................   Passed    0.00 sec
        Start  78: usertype_bitfields.single
 78/126 Test  #78: usertype_bitfields.single ................   Passed    0.01 sec
        Start  79: usertype_call_from_c++
 79/126 Test  #79: usertype_call_from_c++ ...................   Passed    0.01 sec
        Start  80: usertype_call_from_c++.single
 80/126 Test  #80: usertype_call_from_c++.single ............   Passed    0.01 sec
        Start  81: usertype_dynamic_getter_setter
 81/126 Test  #81: usertype_dynamic_getter_setter ...........   Passed    0.01 sec
        Start  82: usertype_dynamic_getter_setter.single
 82/126 Test  #82: usertype_dynamic_getter_setter.single ....   Passed    0.01 sec
        Start  83: usertype_initializers
 83/126 Test  #83: usertype_initializers ....................   Passed    0.01 sec
        Start  84: usertype_initializers.single
 84/126 Test  #84: usertype_initializers.single .............   Passed    0.00 sec
        Start  85: usertype_simple
 85/126 Test  #85: usertype_simple ..........................   Passed    0.01 sec
        Start  86: usertype_simple.single
 86/126 Test  #86: usertype_simple.single ...................   Passed    0.00 sec
        Start  87: usertype_special_functions
 87/126 Test  #87: usertype_special_functions ...............   Passed    0.00 sec
        Start  88: usertype_special_functions.single
 88/126 Test  #88: usertype_special_functions.single ........   Passed    0.00 sec
        Start  89: usertype_var
 89/126 Test  #89: usertype_var .............................   Passed    0.00 sec
        Start  90: usertype_var.single
 90/126 Test  #90: usertype_var.single ......................   Passed    0.00 sec
        Start  91: variables
 91/126 Test  #91: variables ................................   Passed    0.00 sec
        Start  92: variables.single
 92/126 Test  #92: variables.single .........................   Passed    0.00 sec
        Start  93: variadic_args
 93/126 Test  #93: variadic_args ............................   Passed    0.00 sec
        Start  94: variadic_args.single
 94/126 Test  #94: variadic_args.single .....................   Passed    0.00 sec
        Start  95: functions_all
 95/126 Test  #95: functions_all ............................   Passed    0.00 sec
        Start  96: functions_all.single
 96/126 Test  #96: functions_all.single .....................   Passed    0.00 sec
        Start  97: functions_easy
 97/126 Test  #97: functions_easy ...........................   Passed    0.00 sec
        Start  98: functions_easy.single
 98/126 Test  #98: functions_easy.single ....................   Passed    0.00 sec
        Start  99: make_tables
 99/126 Test  #99: make_tables ..............................   Passed    0.00 sec
        Start 100: make_tables.single
100/126 Test #100: make_tables.single .......................   Passed    0.00 sec
        Start 101: multiple_returns_from_lua
101/126 Test #101: multiple_returns_from_lua ................   Passed    0.00 sec
        Start 102: multiple_returns_from_lua.single
102/126 Test #102: multiple_returns_from_lua.single .........   Passed    0.00 sec
        Start 103: multiple_returns_to_lua
103/126 Test #103: multiple_returns_to_lua ..................   Passed    0.00 sec
        Start 104: multiple_returns_to_lua.single
104/126 Test #104: multiple_returns_to_lua.single ...........   Passed    0.00 sec
        Start 105: namespacing
105/126 Test #105: namespacing ..............................   Passed    0.00 sec
        Start 106: namespacing.single
106/126 Test #106: namespacing.single .......................   Passed    0.00 sec
        Start 107: opening_a_state
107/126 Test #107: opening_a_state ..........................   Passed    0.00 sec
        Start 108: opening_a_state.single
108/126 Test #108: opening_a_state.single ...................   Passed    0.00 sec
        Start 109: opening_state_on_raw_lua
109/126 Test #109: opening_state_on_raw_lua .................   Passed    0.00 sec
        Start 110: opening_state_on_raw_lua.single
110/126 Test #110: opening_state_on_raw_lua.single ..........   Passed    0.00 sec
        Start 111: running_lua_code
111/126 Test #111: running_lua_code .........................   Passed    0.00 sec
        Start 112: running_lua_code.single
112/126 Test #112: running_lua_code.single ..................   Passed    0.00 sec
        Start 113: running_lua_code_low_level
113/126 Test #113: running_lua_code_low_level ...............   Passed    0.00 sec
        Start 114: running_lua_code_low_level.single
114/126 Test #114: running_lua_code_low_level.single ........   Passed    0.00 sec
        Start 115: self_call
115/126 Test #115: self_call ................................   Passed    0.00 sec
        Start 116: self_call.single
116/126 Test #116: self_call.single .........................   Passed    0.00 sec
        Start 117: set_and_get_variables
117/126 Test #117: set_and_get_variables ....................   Passed    0.00 sec
        Start 118: set_and_get_variables.single
118/126 Test #118: set_and_get_variables.single .............   Passed    0.00 sec
        Start 119: set_and_get_variables_exists
119/126 Test #119: set_and_get_variables_exists .............   Passed    0.00 sec
        Start 120: set_and_get_variables_exists.single
120/126 Test #120: set_and_get_variables_exists.single ......   Passed    0.00 sec
        Start 121: tables_and_nesting
121/126 Test #121: tables_and_nesting .......................   Passed    0.00 sec
        Start 122: tables_and_nesting.single
122/126 Test #122: tables_and_nesting.single ................   Passed    0.00 sec
        Start 123: userdata
123/126 Test #123: userdata .................................   Passed    0.00 sec
        Start 124: userdata.single
124/126 Test #124: userdata.single ..........................   Passed    0.00 sec
        Start 125: usertypes
125/126 Test #125: usertypes ................................   Passed    0.00 sec
        Start 126: usertypes.single
126/126 Test #126: usertypes.single .........................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 126

Total Test time (real) =   2.73 sec
````

It's beautiful.

**Comment by ThePhD** [comment]
At long laaast: https://ci.appveyor.com/project/ThePhD/sol2/build/2.19.0-49

**Comment by ThePhD** [comment]
TODO:

- [ ] LuaJIT in-house build using LuaJITBuild.cmake rather than trying to finagle with the sources themselves
- [ ] Use docker + travis-ci to get going rather than trying to muck around with travis's image restrictions and the like (just ensure build time is under 5 minutes)

**Comment by ThePhD** [comment]
docker makes me extremely sad.

**Comment by henriquegemignani** [comment]
What's broken? Usually docker makes things smoother, specially compared to travis default image

**Comment by ThePhD** [comment]
@henriquegemignani Environment variables and their transfer to the docker-compose and docker runners is extremely fragile and does not follow what it says in the documentation.

The docs state that if I have a `docker-compose` file, all I need to do is specify the environment variable without a name under the `environment:` block, and its value (if it exists) will be transferred over.

It is NOT doing that for me.

Not to mention that environment variables set in `docker-compose build` by my build script are not preserved in the image, and when I do `docker-compose run test` they just disappear, so I have to make sure that `docker-compose build` has the same environment variables, and then use `-e "VAR=VAL"` for each and every environment variable I want to pass through.

Suffice to say, I am not having a good time with this.

**Comment by henriquegemignani** [comment]
What are you using `docker-compose` for, in the context of a CI build?

I'll admit I haven't used docker-compose that well. I usually just build images and then either use something to push, or an ad-hoc script do run then.
Are these variables in the `environment:` block accessible during the `run` step, at least?

**Comment by ThePhD** [comment]
@henriquegemignani My problem was that I **was** using `docker-compose`.

Not anymore, though.

Most blogs and articles about `docker-compose` shipped it as the way to run your tests easily, wrapping up multiple setups in one easy call to `docker-compose up`, a script in the middle, and then `docker-composer down`.

The problem with this is that this was for -- as reading deeper provided me with -- dealing with when you needed to have multiple __services__ isolated and then taken care of. I had no such need, so my docker compose was just being spun up, only for me to take it down the next command. `docker-compose` and `docker` also are not very honest with how variables are propagated from the `.env` file, `--env-file`, `--env`/`-e` commands passed to the build and work stages.

`docker-compose up`'s environment variables are NOT made available during `docker build image ...`: this was truly bad because the environment variables did not show up unless I explicitly propagated them through. Similarly, `docker build image ...` did NOT take any of my environment variables into the build of the `Dockerfile`: rather, I had to pass them as `--build-arg "NAME=VALUE"`, name them in the Dockerfile with `ARG NAME`, and then also pass each named arg into `ENV NAME=${NAME}` for it to FINALLY show up in my `docker build image` and affect the scripts run in my `Dockerfile`.

But don't stop there, because this has NOTHING to do with `docker run {image name}`, whereupon you need to pass the exact same environment variables AGAIN. And the best part is, of course, `docker run ...` and `docker build image` -- contrary to the docs -- do NOT default environment variable values that you name without a value (e.g., `--env MY_VAR`) to the value in the shell. Indeed: I explicitly ran `export GCC_VERSION=7` in the shell, called `docker run sol2:ci --env GCC_VERSION`, and it did not propogate the value of GCC_VERSION. In fact, GCC_VERSION didn't exist at all, which was super, duper great to debug for a good day and a half of free time.

Oh. And don't forget: `VOLUME` doesn't work on VirtualBox shared folders. Why? Who knows: the virtual box bug for this has been open for some 3, 4 years now. And so instead of making a `sol2:ci` image that references a folder that already exists without copying, I had to debug by throwing in the entire sol2 repo -- and all my testing files that are ignored by .gitignore -- into Docker's image to get going. Thankfully, I later learned they have `.dockerignore`, which is pretty much exactly like `.gitignore`, so I could avoid some copy time. But even then, without `VOLUME`, every time I needed to test environment vars? Well, time to copy into Docker. Then build the docker image. Then wait for something to happen after `sudo apt-get install ...` runs for the 400th time with the 8 dependencies I have, plus any branches taken because of the decisions made by environment variables.

All in all, now that I've figured it out I'm just never going to touch it. At least CMake made sense when I figured it out: Docker just has esoteric behavior and straight up violates its own documentation at times, and the only way to get anything done with it is to specify every option, every command, every command line with rigor and intense study.

I would say I feel like a wizard, but all I feel like is a sap. I also dislike travis-ci for not just... you know. Making their Ubuntu LTS images standardize on the latest. But they're a business and I'm sure they have business reasons for dragging their feet and making it opt-in.

Either way, I never want to CI this repo again for all of 2018. Which is a shame, because I still need to write a CMake script to build LuaJIT, which uses its own complex series of specifically invoked command line arcanery per-platform...

Can't wait.

**Comment by henriquegemignani** [comment]
I don't think you were trying to use the environment variables for the usual docker flow. Checking the `Dockerfile` you commited along with the `.travis.yml` I don't think that's a good use for `docker build`. 

If you want, I can make some improvements to your docker images. What I recommend. for running via travis:

Create a docker image that contains all your environment dependencies: in your case I believe that's only the compilers? Publish this image to Docker Hub, preferably using theirs automated image build.
On the `travis.yml`, you would just pull that image and then `docker run`, possibly mapping the code with volumes or just cloning inside the container.

**Comment by ThePhD** [comment]
I would certainly appreciate any pointers on what to do. I have no idea what I'm doing and I'm just trying to make it so I can `docker build` the right thing based on the environment variables I pass in right now. If I should pre-process this step and turn it into something done outside build time, that'd be nice too.

**Comment by henriquegemignani** [comment]
You certainly want the `docker build` step to be done previously, and during the CI run you want to only `docker pull`. In order for this to work, you need to have these images hosted somewhere. [Docker hub](https://hub.docker.com/) is the standard place, and it's free for public repositories.

You could just run multiple `docker build -t sol-image-name xxx && docker push sol-image-name` on your local machine, pushing then to Docker Hub. This would also mean the least changes to what you already have. Just give a different label for each image variation you have, and you're set for this part.

Since the one responsible for installing the given LUA_VERSION, I recommend you drop all references to this from the Dockerfile. This value makes more sense being set directly on the `docker run` command.
Oh. Should also stop adding the sol2 repository in the image. This should come as a volume during `docker run`.

I did a small cleanup in the Dockerfile: https://gist.github.com/henriquegemignani/55b59411402f59408a63174d8510a459
The [Best practices guide](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) is also recommended.

Example commands:
On your computer:
1. `docker build -t ThePhD/sol2:gcc-6 --build-arg "GCC_VERSION=6" .`
2. `docker push ThePhD/sol2:gcc-6`

On `.travis.yml`
`docker run --rm --env "CI=${CI}" --env "LUA_VERSION=${LUA_VERSION}" ThePhD/sol2:$GCC_VERSION`

(I haven't tested if you can drop the `sudo` on `travis.yml`, but I expect you can. These commands also assume you created a Docker Hub account with your username, which should be default if you login with GitHub there I think)

**Comment by ThePhD** [comment]
Thanks for the pointers and the help. I'll be working on trying to get it to run.

At the moment, I can't use `Volume`s through the docker file or otherwise, mostly because Virtual Box Shared Folders aren't volume-able for reasons beyond my meager understanding. And since I do my testing through a shared Virtual Box folder, I have it as ADD at the moment. I originally did try to use VOLUME but did not go well with virtualbox, I will keep trying and hopefully get it so I can have a fast test/build cycle so I can finally push something up to the docker repos.

**Comment by henriquegemignani** [comment]
I guess you're using either a Windows or macOS machine, if you're running Virtual Box? I've had that issue previously, but I remember being able to use Virtual Box on mac succesfully.

In either case, try using the [Docker for Windows](https://www.docker.com/docker-windows) or [Docker for Mac](https://www.docker.com/docker-mac) releases. They handle the necessary docker machines and make things much smoother. Also, the Windows version uses Hyper-V instead of Virtual Box, but that may an issue if you're running Windows Home.

**Comment by ThePhD** [comment]
@henriquegemignani Thanks for your help. I think I figured out the flow of things and have pushed a number of docker images to my hub account. I'm running travis now... hopefully, each build won't be 20+ minutes like before with this methodology...!

**Comment by ThePhD** [comment]
It liiiives.

https://travis-ci.org/ThePhD/sol2/builds/327237500

https://ci.appveyor.com/project/ThePhD/sol2/build/2.19.0-78

I still have to do LuaJIT (and all the agony that implies), but this means we're FINALLY all tested out and done and can focus on other things that ACTUALLY MATTER. I also have a test case to investigate on clang but that comes later.

Thank you so much for your guidance, @henriquegemignani
