### ISSUE TITLE
Cannot bind bitfields to sol2?

### ISSUE THREAD

**Issue by Sixmorphugus** [ThePhD/sol2#427]
Hi,
I'm trying to generate bindings for the unreal engine but I've got a bit stuck with these:
![image](https://user-images.githubusercontent.com/7923357/27248861-59c9ae1e-5301-11e7-8514-d965bde68980.png)

To bind class properties, sol takes the memory address (&) of them, right? But the compiler doesn't let me take the address of one of these. Is there a way to bind public members like this as well as normal ones that works in every case?

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/blob/develop/examples/usertype_bitfields.cpp

**Comment by Sixmorphugus** [comment]
thank b0ss
