### ISSUE TITLE
containers overhaul

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#430]
@s13n has pointed out that having a user-specializable `sol::container_traits<T>` would ease people's use of containers and allow them to adapt special behaviors that go outside of sol2's default boundaries.

To solve this problem, we will need to first define the range of useful operations a container's metatable would have to provide. From a Lua standpoint, we have that documented there: 

http://sol2.readthedocs.io/en/latest/api/containers.html#additional-functions

From the C++ side, we'd need to have a few static trait functions on the `container_traits`:

- `clear(lua_State* L, self&, value_type&)`
- `push_back(lua_State* L, self&, value_type&)`
- `insert(lua_State* L, self&, iterator, value_type&)`
- `insert(lua_State* L, self&, iterator, key_type&, mapped_type&)`
- `find(lua_State* L, self&, key_type&)`
- `find(lua_State* L, self&, value_type&)`

The biggest problem here is how much should we auto-implement and how much should we detect if somebody does or does not have these static functions defined? Do we simply call a default that errors? Or is there a sensible default?

This is going to be a while, and will likely break current expectations about how things behave.

**Comment by s13n** [comment]
I come to think that the following would be a convenient strategy:
- Detect whether a type is a container using the (already existing) meta-function `is_container()`, and allow the users to add their own specializations. The default already implemented in Sol should ideally detect if the type meets the [Container concept](http://en.cppreference.com/w/cpp/concept/Container), but it may be sufficient to check for the presence of member types `value_type` and `iterator`. Allowing the user to provide specializations may be more convenient if `is_container()` is lifted from the `detail` namespace into the `sol` namespace.
- Do all container handling through user-overloadable free functions, i.e. `begin()`, `end()`, `clear()`, `find()`, `insert()`, `to_string()` etc., of which `begin()`, `end()` and `to_string()` are already available in the `std` namespace. Some others are already there in Sol, but could be moved from `sol::detail` to `sol`. The generic Sol code shouldn't call any container member functions directly. That should be done in the corresponding free function specialization only.
- If some of the functions aren't available in a suitable specialization, the corresponding Lua table operation should be unavailable automatically. That could be done through a catch-all default overload, or through other appropriate means. Functions that are always needed should lead to a compile-time error when a suitable overload isn't available.
- The set of standard overloads already built into Sol can then be extended as time goes by, without affecting the generic code. If an overload for a new type isn't there yet, the user can add it.

It seems to me that much of the infrastructure is already there, and just needs to be cleaned up and documented. If done right, it should be possible to adapt practically anything to serve as a Lua table, even types the user doesn't have control over, for example containers that come from a foreign library, or containers implemented in C.

**Comment by ThePhD** [comment]
Some other functions we'll need:

`begin()` and `end()`, which will return iterators that we will pack in to use. For random-access iterator types, it will be suggested to return a simple `std::size_t`. The others will use the actual iterator. There's a fair handful of glue code I'd need to still stick in without exposing the user to too many internal details...

**Comment by s13n** [comment]
`std::size_t` seems an unlikely iterator type to me, unless you want to use casts a lot. What's wrong with pointers? They're random access too.

**Comment by ThePhD** [comment]
Part of the reason is because of the interface for Lua's `pairs` functions, or its generalized iteration syntax. You're supposed to return 2 things: the key and the value. In the case of things designated as "associative", I'd expect the iterator to return the key and the value. But in the other case, I'd need some way of identifying what the key is. Likely, I'd have to generate it by keeping track of an iterator, and maybe require the user to define an `typedef std::true/false_type is_associative` on `container_traits`.

**Comment by ThePhD** [comment]
I'm not sure if I should pass the `lua_State*` to the user and let them use it to do things, or if I should keep that from the user and just demand certain function signatures...

**Comment by ThePhD** [comment]
This is finally almost done.

The only behavior I need to decide on is what happens if someone doesn't provide a function on the traits. Do we fail the lua code with a missing-funtion error? Or do we fall back do the default implementation? std behavior for things like minimal allocators suggests providing a default implementation if someone doesn't provide all of the functions is sufficient.

**Comment by OrfeasZ** [comment]
If providing a default implementation doesn't produce adverse side-effects then I think it's the best course of action.

**Comment by ThePhD** [comment]
The default implementation has a number of safety-guards built into it already (it's the default container implementation right now): we protect against writing into const iterators, check if an iterator is random access or worse, check if it has the desired member functions before trying to call them, has a backup implementation for calculation container size (`std::distance( begin(), end() )`), checks if the container has an erase function before using it...

And if it doesn't meet any possible workaround or criteria for a function, we simply throw do a `luaL_error( L, "ur container is whack, son" );`. I'm not sure what "adverse side-effects" could mean otherwise...?

**Comment by ThePhD** [comment]
Note to self:

`forward_list` is a nightmare of a container.

**Comment by ThePhD** [comment]
Eugh. Bikeshedding time:

`std::set<int>` gets set as container `c`. What do the following look like:

````

**Comment by ThePhD** [comment]
Above, the same for `std::multi_set`. This problem is not really present for `std::map` or `std::multi_map`, since we have an actual key-value association and doing `find` by key will always return the value.

`std::array` is thankfully handle-able, since that just makes any add-like operation tank miserably.

**Comment by s13n** [comment]
`c[20] = ???? -- wat`

My opinion: Evaluate ???? just like `if` would, i.e. as `true` or `false`, and then add if `true`, erase if `false`.

**Comment by s13n** [comment]
Regarding find and erase: That's not supported for native Lua tables, so if you want to support it, it can do what you like, provided there's some consistency between different container types. I would prefer to have `find` return something akin to what a C++ iterator is, probably that's closest to what Lua calls an index.

With multi-containers in particular, you'd want the result of `find` support iterating through the potentially multiple entries associated with a key.

**Comment by s13n** [comment]
BTW while we're bikeshedding: If the key is a somewhat more complex type, you'll likely have a custom ordering criterion, i.e. a suitably overloaded oprerator<() in C++. Are you going to support implementing this operator in Lua, i.e. via metamethods?

**Comment by ThePhD** [comment]
Comparators are automatically implemented for any usertype you push into Lua.

See: http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-regular-function-options

C++ containers do not expose their comparator member: they are set by the template value on the ordered container, and then optionally given as part of construction. When you set, add, erase, etc.: the `operator<` or `operator==` or `std::hash<Key>` are all tied to the container operation. Passing in a "different comparator" for a single operation is not allowed.

If you mean someone has an `operator<` they want to write in Lua, and then supply it to the container upon new/creation... no, that's not a scenario I'm going to create an "easy in" for. I don't even know how I would begin to allow that to even be a thing.

If you wanted something like that, you could write a `std::map<sol::object, sol::object, my_object_comparator>`, write the logic for how you'd like comparison to work (i.e., relying on an `operator<` methamethod or similar), and then public that to Lua using sol2. Then you can mess with it however you like.

**Comment by s13n** [comment]
No worries. I guess one could always go the extra mile and call a Lua function in a purpose-built operator<() to use with the container. No real need for you to create an easy-in, I'd say.

**Comment by ThePhD** [comment]
Final bikeshed: _safety_.

I think having a separate define from `SOL_CHECK_ARGUMENTS` that provides some additional safety for container arguments and the like would be helpful. Something like `SOL_SAFE_CONTAINERS`. Turning on `SOL_CHECK_ARGUMENTS` would turn this on automatically, just like it does for `SOL_SAFE_USERTYPE`.

**Comment by ThePhD** [comment]
Please review these container documents: http://sol2.readthedocs.io/en/latest/containers.html

TODO still: add safety defines and vet the whole implementation carefully.

**Comment by ThePhD** [comment]
Alright, the new container stuff is in now. I'm going to close this but if anyone has any feedback please feel free to post here or open an issue: https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp
