### ISSUE TITLE
checking of concrete unique_usertype depends on argument order

### ISSUE THREAD

**Issue by rohlem** [ThePhD/sol2#431]
I've found a strange bug with the new unique_usertype argument checking introduced by commit [0fb53335c4411178ce44980cd9f2c04317573743](https://github.com/ThePhD/sol2/commit/0fb53335c4411178ce44980cd9f2c04317573743) (I verified that its parent commit works correctly), triggered by supplying a `std::unique_ptr<foo>` object to a function parameter of type `std::unique_ptr<foo>&`.
Minimal test case:
```
	struct foo{};

	sol::state lua;
	lua.open_libraries();

	lua.set_function("unique_first", [](std::unique_ptr<foo>&, int) {std::cout << "works" << std::endl;});
	lua.set_function("unique_second", [](int, std::unique_ptr<foo>&) {std::cout << "breaks after 0fb5333" << std::endl;});

	lua["unique_foo"] = std::make_unique<foo>();

	lua.script("unique_first(unique_foo, 0)");
	lua.script("unique_second(0, unique_foo)");
```

When I first encountered it it incorrectly led to an `expected usertype, received usertype` error, the test program now crashes however, leading me to believe there might be an invalid pointer access somewhere (most likely stack_check.hpp).

To make sure I didn't miss anything I also wrote [a more expansive test program](https://gist.github.com/rohlem/69c4cdce82a7d1aee94a31cca6e6fd45) I thought I'd share in case you want to play around with it for testing, or even use it as base for a test case or something.

**Comment by ThePhD** [comment]
Thanks for the minimal repro. The problem was I hardcoded "1" as the index and wasn't using the... well, `index` parameter. It's fixed now.
