### ISSUE TITLE
need to detect missing keys in tables. could we have a "getOpt" function for sol tables or references?

### ISSUE THREAD

**Issue by thinlizzy** [ThePhD/sol2#44]
I've had a previous issue on the original sol library regarding detecting when a key was missing from a table.
With sol2 and sol::optional, I was able to work around this problem, but I had to write a convenient wrapper to make it being actually useful. This is named getOpt and it is shown below:
```
template<typename T, typename K>
T getOpt(sol::table tb, K && key, T def = T{})
{
	auto res = tb.get<sol::optional<T>>(std::forward<K>(key));
	return res.value_or(def);
}
```
usage example snippet:
```
auto animSpec = tbAnim.get<sol::table>(k); // k is an int index
MaskedImage img = images.loadMasked(
    animSpec["image"], 
    getOpt<bool>(animSpec,"flipX"),
    getOpt<bool>(animSpec,"flipY"));
```
example lua script:
```
  local basedir = "res/sprites/"
  local defDuration = 200
    animations = {
      left = {
        {image = basedir.."walkerLeft0.png", duration = defDuration},
        {image = basedir.."walkerLeft1.png", duration = defDuration},
      },
      right = {
        {image = basedir.."walkerLeft0.png", flipX = true, duration = defDuration},
        {image = basedir.."walkerLeft1.png", flipX = true, duration = defDuration},
      }
    }
```

do you think tables or references could benefit from having a getOpt() like function? (this will save client code from dealing directly with sol::optional objects)

thanks!

**Comment by Nava2** [comment]
Check the documentation for SOL-CHECK-ARGUMENTS!

It'll do what you want!

**Comment by ThePhD** [comment]
I do not think rolling this functionality into the library itself is a good idea. This is the job of optional, and not of `sol`: we provide support for optional and for references/proxies to check their validity to a degree, but adding functions to do things like "get_or_default"  means we have to consider other things: for example, if it's available on `lua[k].get_or_default<T>( ... );` doesn't that mean it needs to be available on `table` itself? `state_view`? Then, does it also belong on `object`, which has `is<T>` and `as<T>` functions?

Ultimately, I think it might be worth adding to `table` and then also adding this to everything else that works with tables (`state_view`, `proxy`, `object`). But I also  have to do things like wonder if people want conversions and stuff (e.g., the "default" value isn't the same as T?).

**Comment by thinlizzy** [comment]
Is there a way to at least provide a default constructor or a factory for sol::table that is equivalent to a lua empty table?  {}
My workaround works for every C++ type, but the default constructor of sol::table only creates a zombie object.
I had to do something like this, in order to get my getOpt() function working properly (animations is a sol:table object):
```
	auto emptyTable = lua.get<sol::table>("emptyTable");
...
	player.object.addAnimation(toAnimation(images,getOpt<sol::table>(animations,"up",emptyTable)));
```
in my lua script:
`emptyTable = {}
`

**Comment by ThePhD** [comment]
`lua.create_table( 0, 0 )`

**Comment by thinlizzy** [comment]
super sweet. thanks!
you may close this issue if you want to :)

**Comment by ThePhD** [comment]
Can also do `lua.create_table_with()`, IIRC

**Comment by ThePhD** [comment]
Ultimately decided not to implement this. I feel that its better to let the user handle defaults using `optional<T>:value_or`, and to save intermediates as necessary.
