### ISSUE TITLE
default traceback handler not applied

### ISSUE THREAD

**Issue by mrgreywater** [ThePhD/sol2#444]
The default traceback handler is only added when constructing sol::state with a custom allocator function [state.hpp#L75](https://github.com/ThePhD/sol2/blob/34b81bef6b2a0898a67be3e2f8d4e1846032e816/sol/state.hpp#L75), but not without [state.hpp#L68](https://github.com/ThePhD/sol2/blob/34b81bef6b2a0898a67be3e2f8d4e1846032e816/sol/state.hpp#L68).

This means you won't get a traceback in protected functions when constructing your sol state like so:
<code>
sol::state lua;
</code>

**Comment by ThePhD** [comment]
Thanks for reporting. Fixed: pull from latest.
