### ISSUE TITLE
Writing a searcher function

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#447]
I'm trying to write a package searcher using sol2. Checking other examples doing it directly through the C API, it seems like it should be sufficient to load a string and then pass on the return value of the load function. So this is how I'm going it with sol2:

```
sol::state lua;
sol::table searchers = lua["package"]["searchers"];
searchers.add(sol::as_function([this](const std::string &module)
{
	if(module == "foo")
	{
		return sol::make_object(lua, lua.load("local M = {} function M.bar() return \"bar\" end return M"));
	} else
	{
		return sol::make_object(lua, "\n\tno such module");
	}
}));
```
The searcher function is being called, and it will properly return its error string when searching for a module other than "foo". However, when searching for "foo", `require "foo"` will still fail.

(slightly unrelated, but would it be in the scope of sol2 to add some facility like `table.insert` to insert at any position of a table? Would be particularly helpful here to push my search function in front of the built-in ones. Of course I can just directly call the lua function, but having something right in the API would be more comfortable, I guess.)

**Comment by sagamusix** [comment]
Okay, that was a stupid mistake - need to actually do `lua.load(...).get<sol::object>()` to get the returned object!

(the question in parentheses still stands.)

**Comment by ThePhD** [comment]
@sagamusix I just want to make it clear: [`state::load(...)`](http://sol2.readthedocs.io/en/latest/api/state.html#state-load-code) loads a chunk of code but does not execute it: It will NOT create a module, but a function that will run the code provided.

"Module loading" as been mocked up by sol2 through the use of [`state::require`](http://sol2.readthedocs.io/en/latest/api/state.html#state-require-function). If you don't want to use that, you can use your code plus `state.script`, and convert the return value of that function to a `sol::object` to get out the module.

You can already "insert" at any position in the table using the typical indexing operator. If you mean "shove something at the beginning and push all other items back by 1 index", I unfortunately cannot because the idea of a sequence is not well-defined in Lua and I'm bound to screw something up for somebody if I even begin to try to accommodate that idea. If you need to establish some priority around a `sol::table`, write a class that maintains your invariants.

**Comment by sagamusix** [comment]
> "Module loading" as been mocked up by sol2 through the use of state::require.

The objective here was that I may want to lazily search for modules in a container (say, inside a zip file or so). As far as I understand, `state::require` needs to know the module numes, so I would have to list all files in that container.

> If you don't want to use that, you can use your code plus state.script, and convert the return value of that function to a sol::object to get out the module.

I tried using `sol::script` first, because it was also my understanding that this should work, but it doesn't find the module then:

```
searchers.add(sol::as_function([this](const std::string &module)
{
	if(module == "foo")
	{
		return lua.script("local M = {} function M.bar() return \"bar\" end return M").get<sol::object>();
	} else
	{
		return sol::make_object(lua, "\n\tno such module in script package");
	}
}));
```
> require("foo")
>>> [string "require("foo")"]:1: module 'foo' not found:
(...)
```
But my searcher is still being invoked, naturally. (Error checking is omitted until the code actually runs)

**Comment by ThePhD** [comment]
Ah. Well, in that case I know very little about the pathway that package searchers take. I wasn't able to help the last person who wanted to edit that stuff in their project and I'm not sure I'm equipped to help you figure out how to rig up the search pathways for yours. As I understand it, search conventions and pathways differ by the Lua version you use, among other settings and knobs I don't understand.

I would need to read more about the `require` function in the manual before helping you. However, I have a lot of things to do and I am not sure I would be faster in finding what you need before you would by reading about "require" and what's necessary (I'm working on the container overhaul right now).

**Comment by sagamusix** [comment]
Well, I was also looking around a bit before posting here, and I was able to find this Lua pseudo-implementation explaining the searcher stuff:
http://lua-users.org/lists/lua-l/2013-12/msg00172.html
`lua_searcher` in that implementation also just returns the result of loadfile; it does not explicitely execute it. So in theory my variant using `state::load` should be correct, but somehow it is not consistent with the regular search functions. Digging deeper...

**Comment by sagamusix** [comment]
In case someone stumbles upon this issue, here's how I ended up doing this. I just avoided wrapping the function entirely, to make it as similar to the internal loaders as possible.
```
static int CustomSearcher(lua_State *L)
{
	const char *name = luaL_checkstring(L, 1);
	if(!strcmp(name, "foo"))
	{
		const char *filename = "@Internal/foo.lua";	// Prefix with @ for proper stacktrace formatting
		std::string moduleContent = "local M = {} function M.bar() return \"bar\" end function return M";
		if(luaL_loadbuffer(L, moduleContent.c_str(), moduleContent.size(), filename) == LUA_OK)
		{
			lua_pushstring(L, filename);
			return 2; // Return open function and file name
		} else
		{
			return luaL_error(L, "error loading module '%s' from file '%s':\n\t%s",
				lua_tostring(L, 1), filename, lua_tostring(L, -1));
		}
	} else
	{
		// Not found
		return 1;
	}
}

...

sol::table searchers = lua["package"]["searchers"];
searchers.add(CustomSearcher);
```
This way it's possible to lazily require external scripts that may be packed e.g. in a zip file or similar, and they even will look pretty in the stacktrace (i.e. not starting with "[string foo...]") if you specify a filename that makes sense (e.g. "@foo.zip/bar/foo.lua").
