### ISSUE TITLE
Silencing more MSVC warnings

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#448]
Since sol2 already silences some MSVC warnings, these might also make sense to silence:
* C4702, unreachable code. Can be triggered by `sol::optional`.
* C4503, the decorated name was longer than the compiler limit (4096), and was truncated. You will get this pretty quickly already with a small API and the generated warnings are super long, so they just make the build noisy.

**Comment by ThePhD** [comment]
I already silence C4503, but it's based on where the user generates the templates (outside of my code). You'd need to silence that one.

C4702, I haven't gotten that warning. Can you give me an example?

**Comment by sagamusix** [comment]
> I already silence C4503, but it's based on where the user generates the templates (outside of my code). You'd need to silence that one.

I'm aware that silencing it in sol.hpp alone does not get rid of all generated warnings, but some. I cannot exactly tell when it helps and when it doesn't, it probably depends on functions are exactly being used. So I think it wouldn't hurt.

> C4702, I haven't gotten that warning. Can you give me an example?

There is one that's trivial to fix in `static int real_index_call_associative(std::false_type, lua_State* L)` because it has an if..then..else block that returns something in all cases, but then there's another return afterwards.

The other warnings I get from `OPTIONAL_MUTABLE_CONSTEXPR T& value() &` in sol::optional. I'm *not* using SOL_NO_EXCEPTIONS.

This is with Visual Studio 2015.

**Comment by ThePhD** [comment]
I'll add these around the library's code.
