### ISSUE TITLE
Modifying the global metatable

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#449]
Objective: Preventing people from shooting themselves in the foot by overwriting the global namespaces provided by my C++ <--> Lua API. So I want to prevent new_index being called on a few tables.

In general this should be possible (http://lua-users.org/lists/lua-l/2003-06/msg00364.html) but I have tried several ways of implementing this with sol2 which are probably all embarassingly wrong. Some help in how to accomplish this with sol2 would be greatly appreciated.

**Comment by ThePhD** [comment]
You can just call `lua.script()` to do what's shown there and it'd have the same effect. Doing everything "purely with the C API"  or "purely with sol2" isn't exactly necessary (and sometimes, not particularly possible...!).

You might be able to get far by doing `state::globals()` to get the global table, and then manipulate its metatable with `globaltable[sol::metatable_key]` and friends.

**Comment by ThePhD** [comment]
And here, for reference, though the examples don't mention this (I probably should add a 'readonly table' example with this in it): http://sol2.readthedocs.io/en/latest/api/metatable_key.html?highlight=metatable_key

**Comment by ThePhD** [comment]
I'm an idiot. This is a problem solved by using environments, which is far more efficient and completely supported by a sol2 API. You can restrict access, create fallback functions, and other things. Here's an example: https://github.com/ThePhD/sol2/blob/develop/examples/environments.cpp

**Comment by ThePhD** [comment]
You can combine this and getting the metatable of the environment, then set the `index` and `newindex` methods manually with a filtering function or something similar.

**Comment by sagamusix** [comment]
That looks promising, I'll give it a try later.

**Comment by galou** [comment]
After almost two days fighting and with the help of this issue, I managed to get something working. The issue that I had and which is related to the fact that I hardly knew lua before (I didn't know that you have to add the metatables manually). Here are my solution in pure C++ and C++/lua mix, only implementing the `__index` meta-function.
```C++
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <iostream>  // std::{cerr,endl}.

class LuaRunner
{
  public:

    LuaRunner() {
      // Add `print` to the global environment.
      lua_.open_libraries(sol::lib::base);

      sol::table global_table = lua_.globals();
      sol::table global_metatable = lua_.create_table_with();
      global_table[sol::metatable_key] = global_metatable;
      global_metatable[sol::meta_function::index] = [this] (sol::table table, sol::object key) {return index(table, key);};
    };

    bool runCode(const std::string & code)
    {
      const auto result = lua_.safe_script(code);
      return result.valid();
    }

  public:

    sol::state lua_;

    sol::object index(sol::table table, sol::object key)
    {
      return sol::make_object(lua_.lua_state(), 3.4444); // Implement your own index logic here.
    }
};

int main(int, char **)
{
  auto runner = LuaRunner{};

  auto code = R"(
   print("------")
   print("x: " .. (x or "nil"))
  )";

  if (not runner.runCode(code))
  {
    std::cerr << "Error running code" << std::endl;
    return 1;
  }

  return 0;
}
```

```C++
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <iostream>  // std::{cerr,endl}.

class LuaRunner
{
  public:

    LuaRunner() {
      // Add `setmetatable` and `print` to the global environment.
      lua_.open_libraries(sol::lib::base);

      lua_.set_function("from_storage", [this] (sol::object key) {return index(lua_.globals(), key);});
      runCode(R"(
        mt = {}
        mt["__index"] = function(table, key)
          return from_storage(key)
        end
        setmetatable(_G, mt)
      )");
    };

    bool runCode(const std::string & code)
    {
      const auto result = lua_.safe_script(code);
      return result.valid();
    }

  public:

    sol::state lua_;

    sol::object index(sol::table table, sol::object key)
    {
      return sol::make_object(lua_.lua_state(), 3.4444); // Implement your own index logic here.
    }
};

int main(int, char **)
{
  auto runner = LuaRunner{};

  auto code = R"(
   print("------")
   print("x: " .. (x or "nil"))
  )";

  if (not runner.runCode(code))
  {
    std::cerr << "Error running code" << std::endl;
    return 1;
  }

  return 0;
}
```
