### ISSUE TITLE
Question on numeric values

### ISSUE THREAD

**Issue by free-easy** [ThePhD/sol2#451]
What would happen if I bind to lua a function that returns, say a `uint64_t`. 
I know that for lua, before 5.3, all the numbers are doubles, which can represent at most a 52-bit integer.

Should I bind `uint64_t` as usertype and play with the metatable in order to have all the operators working in a expected way, or does sol2 make some magic in this regard?

**Comment by ThePhD** [comment]
Lua 5.3 has handling for integers (which I believe are 64-bit integers, the same type as `lua_Integer`). If you're using Lua 5.2 or 5.1, there's a bunch of solutions out there in the world that you can use. sol2 makes no special affordances: we put your `uint64_t` into a `lua_Integer` and then do `lua_pushinteger` to put it into the VM. Whether or not the bits are preserved is a matter of the Lua VM, and any guarantees sol2 would try to make are fragile at best (so we make none).

You can lift your `uint64_t` into a...

````
struct lua_has_interesting_design_choices {
     uint64_t value;

     operator uint64_t& () {
          return value;
     }

     operator uint64_t& () const {
          return value;
     }
};
````

And then override all of the methods on a usertype of that name. Overriding `uint64_t` (a fundamental integral type) to try and make it behave as a usertype is not supported, but tiny wrappers like the one above (albeit I'm sure you can pick a better name!) are fine. Just don't expect it to be neckbreak fast when dealing with a userdata.
