### ISSUE TITLE
Can sol::overload take lua_CFunctions?

### ISSUE THREAD

**Issue by Sixmorphugus** [ThePhD/sol2#452]
I'd like to know if it can, for optimisation reasons. If it can't that's fine - I can just pass them the normal way. I can't really find anything about this in the docs, but it could be that I'm not looking hard enough.

**Comment by ThePhD** [comment]
You can. But, how would you access the `lua_CFunction`, from Lua?

**Comment by ThePhD** [comment]
To be more clear:

````
void func_1 (int) {

}

void func_2( std::string ) {

}

int func_3 (lua_State* L) {

}

int main () {
     sol::state lua;
     lua.set_function( "f", sol::overload(
          func_1,
          func_2,
          func_3
     ));

     lua.script("f(1)"); // func_1
     lua.script("f('hi')"); // func_2
     lua.script("f(????)"); // ????
}
````

**Comment by Sixmorphugus** [comment]
That's the problem I've come to. I've considered making some sort of generator for a "combo function" which uses lazy evaluation to check the arguments and decide which C++ function to call, but haven't tried it yet. I assume this is what sol::overload is doing internally.

**Comment by ThePhD** [comment]
`sol::overload` checks the arguments when you call the function (so lazily, I guess??) and then matches to the first argument in the list that matches (first-come, fist-serve overload matching).

If you want to "hijack" into sol2's overloading mechanism and specify a "failure fallback" (?? I'm guessing, I still don't know what you want out of when someone calls 'f' with an unrecognized overload), that's not supported right now.

Right now, what happens is 1 and 2 would work, but anything asides from that that does NOT match will just error. Do you want a "call this if nothing matches" fallback? Or are you asking for something else? (The immediate answer to your question is no, no we do not have anything like that).

Note that you can simulate a "catch-all" function by changing `func_3` to be...

````
sol::variadic_results func_3 (sol::variadic_args args ) {
     sol::variadic_results r;
     // inspect "args" for things you want like any other sol2 object
     // add things to variadic_results as needed
     return r;
}
````

See:
http://sol2.readthedocs.io/en/latest/api/variadic_args.html
http://sol2.readthedocs.io/en/latest/api/variadic_results.html

Note that `variadic_results` is just a `std::vector<sol::object>`. If you know you're not returning anything more than 1 object, you can 'optimize' down to a `sol::object` return.

**Comment by ThePhD** [comment]
Finally, there's nothing stopping you from just making your own raw `lua_CFunction` that does your own kind of overloading.

**Comment by Sixmorphugus** [comment]
`sol::varadic_args` looks like what I want. Thanks.

And to clarify, I was asking about a "call this if nothing matches" fallback.

**Comment by ThePhD** [comment]
I should probably add that `variadic_results` + `variadic_args`  fallback to the examples. But I'm still working on other stuff right now. I'll put it in the back of my mind.

I need... a LOT of more "advanced" examples. People definitely want them, but I don't know what "advanced" usage looks like for people. These kind of issue requests help me add things that people can understand easier, so thank you for filing them.

**Comment by Sixmorphugus** [comment]
That's ok.

In terms of checking what's in the stack is compatible with a given overload, what I have at the moment is this; the culmination of a collection of static functions to construct a Vector:
```C++
if(sol::stack::check_get<FRotator>(lua_state, 1))
{
	return UKismetMathLibrary_Conv_RotatorToVector_Proxy(lua_state);
}

if(sol::stack::check_get<float>(lua_state, 1) && sol::stack::check_get<float>(lua_state, 2))
{
	return UKismetMathLibrary_MakeVector_Proxy(lua_state);
}

if(sol::stack::check_get<float>(lua_state, 1))
{
	return UKismetMathLibrary_Conv_FloatToVector_Proxy(lua_state);
}

if(sol::stack::check_get<FIntVector>(lua_state, 1))
{
	return UKismetMathLibrary_Conv_IntVectorToVector_Proxy(lua_state);
}

if(sol::stack::check_get<FVector2D>(lua_state, 1))
{
	return UKismetMathLibrary_Conv_Vector2DToVector_Proxy(lua_state);
}

if(sol::stack::check_get<FLinearColor>(lua_state, 1))
{
	return UKismetMathLibrary_Conv_LinearColorToVector_Proxy(lua_state);
}

return luaL_error(lua_state, "A matching overload could not be found for the given argument set.");
```

To do this the generator constructs a tree of the arguments needed by each version of the function, orders them most-to-least complex, and removes any that don't narrow anything down.

It doesn't work, though. Calling this generated "multi proxy" function (`lua_State* lua_state` is the only argument) will invariably cause a crash. I assume there's a much better way of figuring out what's stored in the stack that I'm just missing here.

**Comment by ThePhD** [comment]
Check is a function that returns just a boolean. It is documented: http://sol2.readthedocs.io/en/latest/api/stack.html#stack-check

If you do not give it a handler, it passes a `no_panic` handler.

Your overload resolution looks primitive, but more or less fine. If you can guarantee certain arities, you can eliminate large chunks of these checks by getting how many items are on the Lua stack (`int arg_count = lua_gettop(lua_state);`), and then eliminating all of the calls that do not have the necessary number of values.

If you use `sol::variaidic_args`, you get the argument count for the function call for free (`.leftover_count()`), you can retrieve a proxy element for a certain index `auto p = vargs[index]`, and then you can still use `sol::stack::check(lua_state, p.stack_index())` and then do `p.get<T>` when you need it.

**Comment by ThePhD** [comment]
This has been formalized for `sol::variadic_args` and there is an example for it in the repository now: https://github.com/ThePhD/sol2/blob/develop/examples/overloading_with_fallback.cpp

This is also part of the tests.
