### ISSUE TITLE
Another odd use case: sol::meta_function enumeration to name

### ISSUE THREAD

**Issue by Sixmorphugus** [ThePhD/sol2#454]
Hi,
I've generated this:
```C++
lua_state["Vector"][sol::metatable_key][sol::meta_function::subtraction] = UKismetMathLibrary_Subtract_VectorVector_Proxy;
lua_state["Vector"][sol::metatable_key][sol::meta_function::addition] = UKismetMathLibrary_Add_VectorVector_Proxy;
lua_state["Vector"][sol::metatable_key][sol::meta_function::division] = UKismetMathLibrary_Divide_VectorFloat_Proxy;
lua_state["Vector"][sol::metatable_key][sol::meta_function::multiplication] = UKismetMathLibrary_Multiply_VectorFloat_Proxy;
```

It is trying to bind functions found in external function libraries to core types as operators. However, this doesn't work because, I presume, `sol::meta_function::addition` != `"__add"`.

Is there any way to convert between the sol meta function enumerations and their actual internal lua names? It would also be fine if you could just give me a list of what the enumerations correspond to and I can make my own converter. Thanks for any help.

EDIT: Found the meanings here: http://lua-users.org/wiki/MetatableEvents

New generated bindings look like:
```C++
lua_state["Vector"][sol::metatable_key]["__sub"] = UKismetMathLibrary_Subtract_VectorVector_Proxy;
lua_state["Vector"][sol::metatable_key]["__add"] = UKismetMathLibrary_Add_VectorVector_Proxy;
lua_state["Vector"][sol::metatable_key]["__div"] = UKismetMathLibrary_Divide_VectorFloat_Proxy;
lua_state["Vector"][sol::metatable_key]["__mul"] = UKismetMathLibrary_Multiply_VectorFloat_Proxy;
```

Tested some other stuff, binding the `"__add"` string doesn't work either. Am I doing this right? Keep in mind that I can't use the normal usertype method here - these are added after the usertype has been read and are in fact from different classes that are read after it. Should I be indexing the `sol::metatable_key` here or is the global usertype table a metatable already?

Here's the error if it's useful:
![](http://i.imgur.com/cej0eyf.png)

**Comment by ThePhD** [comment]
I don't think we have support for adding meta_functions at runtime.

As a reference, we do convert `sol::meta_function::addition` to `__add`. I just don't think I have the code in to specifically let this work, I don't think. I haven't tried this so I'll have to make an example and then try to figure out why it's not working...

**Comment by ThePhD** [comment]
As a side note, here's the names: https://github.com/ThePhD/sol2/blob/develop/sol/types.hpp#L579

I do need a tutorial binding all the metamethods at some point, I guess.

**Comment by ThePhD** [comment]
I think I found the problem with your example. You should not be tapping directyl into `sol::metatable_key`: `vec2` already is the metatable:

````
struct vec2 {
	float x, y;

	vec2() = default;
	vec2(float x, float y) : x(x), y(y) {}

	vec2 operator+ (const vec2& r) {
		return { x + r.x, y + r.y };
	}
};

int main() {
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	
	lua.new_usertype<vec2>("vec2",
		sol::constructors<vec2(), vec2(float, float)>(),
		"x", &vec2::x,
		"y", &vec2::y
	);

	lua["vec2"][sol::meta_function::addition] = &vec2::operator+;

	lua.script(R"(
		l = vec2.new(1, 2)
		r = vec2.new(2, 3)
	)");

	lua.script(R"(
		v = l + r
	)");
	
	vec2& v = lua["v"];

	return 0;
}
````

I need to add this as an example (the run-time adding part). But, that should get you going!

**Comment by Sixmorphugus** [comment]
Alright, thanks!
