### ISSUE TITLE
sol::overload incompatible with sol::variadic_args

### ISSUE THREAD

**Issue by rohlem** [ThePhD/sol2#455]
A minor detail I've stumbled across that ends up complicating all kinds of constructs involving sol::variadic_args; I believe the root cause is in sol's overload resolution mechanism that can be triggered using sol::overload.
(very) minimal test case:
```
	sol::state s;
	s["f"] = sol::overload([](const sol::variadic_args& args){std::cout << '#' << args.leftover_count() << std::endl;});
	s.script("f(0) f() f(3, '4', 5)");
```
Having a sol::variadic_args parameter in a functor argument of sol::overload makes it rather non-trivial to satisfy (I guess it should work if you were construct a Lua-side sol::variadic_args object by hand, which is sort of contrary to their purpose/design; I didn't test that yet).
I think the expected / my suggested behaviour for this case is rather simple: variadic_args should disable any upper limit to the argument count but not take up any argument space themselves, as is their current behaviour in "simply" pushed/converted callable objects. While I'm sure it is possible to implement, I assume the required "hard-wiring" of this behaviour is simply absent as of yet. With "optimal" argument matching the details on which functor to prefer might be more involved (probably discouraging empty variadic_args), but with the current first-fit style matching I think there shouldn't be any ambiguities.

Another area this comes up in is when specifying usertypes using sol::constructors, sol::factories etc. ; it seems a safe assumption to me that they all share the same mechanism under the hood.

Lastly, it isn't really a pressing matter, as there's ways around this (writing your own checking overloader isn't too hard, esp. with C++17), but it does seem like inconsistent behaviour to me that should be documented somewhere (like here) and fixed _eventually_ (possibly by me the next time it crosses my mind, though I figure a solution you'd probably be faster and might come up with a solution that covers more ground than me).

**Comment by rohlem** [comment]
The issue was the const reference.
I don't remember why I'd put it there.
Let's all pretend this never happened.

**Comment by ThePhD** [comment]
They all do share the same overloading-matching mechanism under the hood, and a custom templated functor gets called for constructor cases, factory cases, and plain function overload cases.

This is actually a bug. `const` and `ref` and `volatile` should not affect that this works or not. I've put a fix in and I'll push it soon. Thanks for reporting it.
