### ISSUE TITLE
Calling __tostring for string conversion on a type that was just pulled from the stack

### ISSUE THREAD

**Issue by Sixmorphugus** [ThePhD/sol2#456]
So I'm writing a `print` function that expands on the behaviour of the normal lua one. Currently it can display booleans, nil, and tables.

It works as a `lua_CFunction` by simply checking how many values are on the stack and removing them one by one. However, after binding the metafunction `__tostring` on some of my types, the string conversion did not automatically work as expected - according to the Lua documentation, it's meant for use by Lua's `tostring` function which, for me, isn't present at all unless I load Lua libraries - something I'm trying to avoid doing in this case because I want to use Unreal's utility functions rather than Lua's whenever possible. I am not sure why this is or exactly which Lua library `tostring` is from.

Anyway, onto the question: I have a Lua stack index. I don't know what the value is because `print` is supposed to take anything. I can specifically check for all of the Lua base types as well as `usertype`, but that doesn't help me figure out if what I've pulled off the stack has a `__tostring` metafunction or not. Is there any way to know this once I've done the `usertype` conversion?

**Comment by Sixmorphugus** [comment]
After consulting various API I've come up with this code to do it, but this isn't using any of `sol`:
```C++
if (lua_isuserdata(L, i))
{
	if (luaL_getmetafield(L, i, "__tostring")) // puts a lua_CFunction on the stack
	{
		lua_CFunction ToString = lua_tocfunction(L, lua_gettop(L));
		lua_pop(L, 1);

		// Get lua to call the function
		lua_pushcfunction(L, ToString);
		lua_pushvalue(L, i);

		lua_pcall(L, 1, 1, 0); // pops the two values we just pushed, pushes a string

		// We now SHOULD have the string representation of i on the top of the stack.
		// It's not doing much good there so lets remove it
		const char* str = lua_tostring(L, lua_gettop(L));
		ResultString = FString::Printf(TEXT("%s"), UTF8_TO_TCHAR(str));

		// Again, we need to remove the extra stack value
		lua_pop(L, 1);
	}
}
```

**Comment by ThePhD** [comment]
You're assuming that `__tostring` would be a C function. It doesn't have to be. It can be multiple things, including a plain function from Lua. When you do `luaL_getmetatfield(L, i, "__tostring");`, that function is already on the stack, at the top. So, you can modify your code to do the following:

````
if (lua_isuserdata(L, i))
{
	if (luaL_getmetafield(L, i, "__tostring")) // puts a some function on the stack
	{
                lua_pushvalue(L, i);
                // call that function, with the value at 'i'
		lua_pcall(L, 1, 1, 0); // pops the two values we just pushed, pushes a string

		// We now SHOULD have the string representation of i on the top of the stack.
                // use -1 to reference the value at the top of the stack
                // negative indices are equivalent to start from 
                // the very top of the stack (-1) and traversing down it (-2, -3, ...)
		const char* str = lua_tostring(L, -1);
		ResultString = FString::Printf(TEXT("%s"), UTF8_TO_TCHAR(str));

		// Again, we need to remove the extra stack value
		lua_pop(L, 1);
	}
}
````

Now, with more sol2:

````
if (lua_isuserdata(L, i))
{
	if (luaL_getmetafield(L, i, "__tostring")) // puts a some function on the stack
	{
                lua_pushvalue(L, i);
                // call that function, with the value at 'i'
		lua_pcall(L, 1, 1, 0); // pops the two values we just pushed, pushes a string

		// We now SHOULD have the string representation of i on the top of the stack.
                // use -1 to reference the value at the top of the stack
                // negative indices are equivalent to start from 
                // the very top of the stack (-1) and traversing down it (-2, -3, ...)
		const char* str = lua_tostring(L, -1);
		ResultString = FString::Printf(TEXT("%s"), UTF8_TO_TCHAR(str));

		// Again, we need to remove the extra stack value
		lua_pop(L, 1);
	}
}
````

**Comment by ThePhD** [comment]
`stack_function` means "the thing at this index is a function on the stack. treat it like one". It is a bit faster than `function` because it does not save things in the Lua C Registry on construction and remove it on destruction.

We get out a `std::string` because `stack_function` removes its results off the stack when done.

We still have to pop because we left the `__tostring` value on the stack.

**Comment by Sixmorphugus** [comment]
Alrighty, thanks.

**Comment by ThePhD** [comment]
This isn't quite possible yet, but in the next commit I make for sol2, for **maximum** performance:

````
if (lua_isuserdata(L, i))
{
	if (luaL_getmetafield(L, i, "__tostring")) // puts a some function on the stack
	{
                sol::stack_aligned_function f_tostring(L, -1);
                sol::function_result result = f_tostring(sol::stack_reference(L, i));
                const char* str = result;
		ResultString = FString::Printf(TEXT("%s"), UTF8_TO_TCHAR(str));
                f_tostring.pop();
	}
}
````

This version:

Uses the new (and currently undocumented) `stack_aligned_` version of `function`: what it does is realizes that `luaL_getmetafield` already pushed a function onto the stack, and it knows that its at the of the stack already. So it doesn't push the function a second time before setting up the arguments (pushing a `sol::stack_reference` for `i`).

This saves 1 push operation.

The second boost is something that is possible: saving `const char*` from a `function_result`. `function_result` calls `lua_pop(L, result_count);` when it's done. Therefore, if you save it on the stack and don't do anything funny with said stack between getting it and using it, you can leave the string on the Lua stack and thus make it safe to get a `const char*` from Lua, without invalidating the string pointer on the Lua stack.

This saves a malloc/new

**Comment by ThePhD** [comment]
`stack_aligned_function` is now part of the latest, but I still need to make the tests pass, just as an FYI:

http://sol2.readthedocs.io/en/latest/api/stack_reference.html#stack-aligned-function

There might also be some typos here and there: it's fresh documentation.

**Comment by k3ll3x** [comment]
if your metatable has '__tostring' method, you can just call
```lua
luaL_tolstring(L, i, 0);
```
