### ISSUE TITLE
loadbuffer inside sol::environment

### ISSUE THREAD

**Issue by an0nym0us69** [ThePhD/sol2#457]
Hello, first of all thank you for all the work you put into the project 👍 
i saw that it's possible to load scripts (strings/file) inside sol::environment just by passing sol::environment as argument for sol::state::script/sol::state::script_file, it's actually a good option, but sadly it didn't support buffers, i have a function call which uses sol::this_environment and i wanted to load buffer inside it, hope that you can add that soon =)

**Comment by ThePhD** [comment]
What does "load buffer inside it" mean?

**Comment by an0nym0us69** [comment]
sorry if it was vague :x, here's an example : State.buffer(buff, size, name, sol::environment), would load the buffer then execute it inside a certain _ENV (sol::environment), the default buffer call executes it inside _G, was searching if i can call a function (the buffer) under certain sol::environment since where you load the buffer doesn't really matter, it's all about the execution of it i believe.

**Comment by ThePhD** [comment]
Let me be more specific.

What is the purpose of `State.buffer`? Do you mean take a `const char*`, and a `std::size_t size` parameters, alongside a `sol::environment env` to and read from that code? Do you mean a wrapper around `lua_loadbuffer` ? What is the `name` parameter for?

As a side note, if you do a loadbuffer call and then get out a `sol::function` from it, you can apply a `sol::environment` on that function (using the [functions documented here](http://sol2.readthedocs.io/en/latest/api/environment.html#free-functions)).

**Comment by an0nym0us69** [comment]
wow :o i didn't think about casting the loadbuffer to a sol::function, thank you very much for the advice, will give you feedback later =)

as for State.buffer, it's pretty much like executing a string (like in State.script), but in State.buffer, any error thrown (loading or executing) would have the name you supplied in the parameter instead of "string"
example : 
State.string => ["string"] : attempt to index "i" (a nil value)
State.buffer ("luascript") => "luascript" : attempt to index "i" (a nil value)

**Comment by an0nym0us69** [comment]
worked pretty fine when casting the loadbuffer call into sol::function, would be a good addition to add the function i mentionned though, i didn't know that i was able to do that until you gave me the advice, thank you for your time :)

**Comment by ThePhD** [comment]
You would do this by calling `luaL_loadbuffer` with your parameters, then doing `sol::function code(lua, -1);` to get a function from the code on the top of the stack.

Then, set up your environment before calling `sol::set_environment( env, code );`. Finally, to execute the code, do `code();`.

I will be writing an abstraction for `luaL_loadbuffer` and the generic `lua_load` in a bit. It will take me some time as I am still working on container abstractions.

**Comment by ThePhD** [comment]
Added raw load function that can be called with a `lua_Reader` and `void*` custom data: http://sol2.readthedocs.io/en/latest/api/state.html#state-load-code

All versions of sol2's `script` files now use `luaL_loadbufferx`, and take a form of `string_view` as the first argument. Construct a `std::string_view` if you're on C++17 and sol2's C++17 support is on, or just pass `sol::string_view(buf, size)` if you're not. Also has constructors for `basic_string` to work as well.
