### ISSUE TITLE
Can I new a sol::state with my own lua_State pointer?

### ISSUE THREAD

**Issue by djbhsys** [ThePhD/sol2#460]
My project use two language,and I have to create a lua_State in another project,so is there any way I can use the already exist lua_State to create a new sol::state.I'm already search out the doc but get no luck.so anyone can help?Thanks.

**Comment by Sixmorphugus** [comment]
You can use `sol::state_view`. It's documented here: http://sol2.readthedocs.io/en/latest/api/state.html?highlight=state_view

It's basically the same as `sol::state` but you get to manage the actual `lua_State` yourself. Which sounds like what you need.

**Comment by ThePhD** [comment]
@Sixmorphugus is exactly right. This is information is also present in the [Quick 'n' Dirty Tutorial](http://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#sol-state-on-lua-state) and in the [Integrating Existing Code](http://sol2.readthedocs.io/en/latest/tutorial/existing.html) tutorial.

Good luck.
