### ISSUE TITLE
Cannot run under Xcode 8 and C++14

### ISSUE THREAD

**Issue by gmisail64** [ThePhD/sol2#462]
After installing and initializing the library, this error is thrown:
```
"_luaopen_utf8", referenced from:
      void sol::state_view::open_libraries<sol::lib, sol::lib>(sol::lib&&, sol::lib&&) in PL.o
ld: symbol(s) not found for architecture x86_64
```
I am using the basic example found in the docs.

**Comment by ThePhD** [comment]
I don't have a Mac, so I can't really grok why this is happening. I am going to be setting up a test suite for XCode 7 and 8 soon, but that's going to be after I take care of some C++17 feature includes first. It may be a while before I can figure out how to help you.

As a side note, `luaopen_utf8` is a staple of Lua 5.3, I believe. Older versions of Lua would not have it. Make sure you're using the latest version of Lua with your project. Remember that the newest version of Lua is drop-dead easy to build in every platform: I would recommend you get the source and build it with XCode 8 on your machine.

**Comment by gmisail64** [comment]
I recompiled the latest version of Lua from the website (5.3.4) and I get the same error messages.

**Comment by ThePhD** [comment]
Make sure you're compiling your DLL for the 64-bit architecture (the error message seems to indicate the symbol is missing in that way).

Other than that, I don't have any other suggestions at the moment. I know @Nava2 works with Mac OSX and a few others, I'm not sure if they could chime in here. In the meantime, I'll be moving setting up an XCode 7 and 8 image to run on travis-CI with Lua 5.3 on my priority list.

**Comment by Nava2** [comment]
I don't know that I've used the full setup you've described here. I have been doing more TypeScript over Lua these days. 

That being said, @gmisail64 if you can give me a better minimum working example, I can possibly shed some light.

**Comment by ThePhD** [comment]
I'm going to close this, since the user who opened it seems to have gone MIA.

If you still need help, please reply here or open a new issue.
