### ISSUE TITLE
I' have an ideal to support custom data, hope you add this to example

### ISSUE THREAD

**Issue by horatii** [ThePhD/sol2#464]
```
namespace sol {
	namespace stack {
		template<>
		struct getter<HWND> {
			static HWND get(lua_State* L, int index, record& tracking) {
				tracking.use(1);
				return reinterpret_cast<HWND>(lua_tointeger(L, index));
			}
		};

		template<>
		struct pusher<HWND> {
			static int push(lua_State* L, const HWND value) {
				lua_pushinteger(L, static_cast<lua_Integer>(reinterpret_cast<int>(value)));
				return 1;
			}
		};
	}
}

HWND dummy_api(HWND hwnd)
{
      return nullptr;
}

int main()
{
    sol::state lua;
    lua.set_function("dummy_api", &dummy_api);
   
    lua.script("dummy_api(0)");

    return 0;
}
```

**Comment by ThePhD** [comment]
One comment, one question.

Question:
- Why use `dummy_api(0)` when you could use `dummy_api(nil)`? Then you don't need the custom code at all. `HWND` is supposed to be `void*`, and sol2 will convert `nil` to `nullptr` for you and vice versa.

Comment:
- `reinterpret_cast<int>` will work in a 32-bit build. Building a 64-bit dll will truncate your pointer and ruin you. Even if you cast to `std::size_t` or `std::uintptr_t` (as documented [here](http://en.cppreference.com/w/cpp/header/cstdint)), Lua 5.2 and below use `double` to represent their numbers and if you're not careful with the bits they may or may not get absolutely strangled in the conversion process during a 64-bit build.

**Comment by ThePhD** [comment]
I will unfortunately not be adding this to the examples as-is. My apologies.
