### ISSUE TITLE
Using Shared Library with Sol2

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#466]
From @alkino --

I can't find any tutorial about 'require' sol2 generated object in lua.
I naively do:
```cpp
static int init() {
  sol::state lua;
  lua.new_usertype<Foo>("Foo", ...);
  return 0;
}
static int initalized = init();
```
I produce a My_Object.so with that and in lua:
```lua
require ("My_Object")
```
But it doesn't work, so there should be another way.
Which one?

**Comment by ThePhD** [comment]
I do not have a proper handle on how to include shared libraries, but there's a few problems with your assumption.

- Creating a `sol::state lua` makes a completely new Lua State. It is then destroyed when the scope exits. It will never be found no matter how you set that function up.
- To require things from a shared object library, you need to obey Lua's rules. sol2 doesn't set up any special magic to make this happen. As I understand it, you need to write a routine in a shared object library that can be called and used in your main application. Taking information from [here](https://stackoverflow.com/a/26221022), this is how you would work your example:

**My_Object.hpp**
````cpp
struct test {
     int value;

     test() = default;
     test(int val) : value(val) {}
};
````

**My_Object.cpp** -> _My_Object.dll_
````cpp
#include <sol.hpp>

int lua_openMy_Object( lua_State* L ) {
     // get a state_view to work with an existing Lua state
     sol::state_view lua(L);
     // now you have all the beauty of sol2 with existing code
     
     // make empty table that will be our "module"
     sol::table my_object_table = lua.create_table();
     // populate table with your stuff

     my_object_table.new_usertype<test>("test",
          sol::constructors<test(), test(int)>(),
          "value", &test::value
     );

     // return the "module" back to the person that called this function
     // sol::stack::push is documented in the stack API,
     // and should always return 1 except for your custom types
     // 99% of lua custom modules return 1 object
     int number_of_things_pushed_to_stack = sol::stack::push(lua, my_object_table);
     return number_of_things_pushed_to_stack;
}
````

_script.lua_
````lua
mo = require("My_Object")

obj = mo.test.new(24)
print(obj.value)
````

**main.cpp** -> _main.exe_
````cpp
#include <sol.hpp>

int main () {
     sol::state lua;
     
     lua.script_file("script.lua");

     return 0;
}

````

As a side note, I might add an example showcasing the proper way to do this with vanilla Lua, so this question stops coming up. Either way, try and modify this until it behaves as you want. I again don't know if it's 100% accurate...

**Comment by alkino** [comment]
It works for me if we modify My_Object.cpp
```cpp
#include "sol.hpp"
#include "My_Object.hpp"

extern "C" __attribute__ ((__visibility__("default")))
int luaopen_My_Object( lua_State* L ) {
    // get a state_view to work with an existing Lua state
    sol::state_view lua(L);
    // now you have all the beauty of sol2 with existing code
    // make empty table that will be our "module"
    sol::table my_object_table = lua.create_table();
    // populate table with your stuff
    my_object_table.new_usertype<test>("test",
    sol::constructors<test(), test(int)>(),
    "value", &test::value
  );
  // return the "module" back to the person that called this function
  // sol::stack::push is documented in the stack API,
  // and should always return 1 except for your custom types
  // 99% of lua custom modules return 1 object
  int number_of_things_pushed_to_stack = sol::stack::push(lua, my_object_table);
  return number_of_things_pushed_to_stack;
}    
```
Differences: 
* `luaopen_*` and not `lua_open*`
* add the visibility and extern C

The way to make it visible is different for each target (windows, gcc, ...)
Maybe we can be inspired by https://github.com/boostorg/python/blob/develop/include/boost/python/module_init.hpp

Thanks

**Comment by ThePhD** [comment]
I am not going to get myself into the business of 
defining `extern "C"` plus visibility attributes. They are all compiler-specific and there is legitimately nothing I can do because at the end of the day _you_ have to write the code for the DLL and there's no code I can write that will allow me to swap in your "load function", like python's `module_init` does.

Functionality for loading arbitrary code from somewhere within the application is already provided by `sol::state_view::require(_file)`: http://sol2.readthedocs.io/en/latest/api/state.html#state-require-function

DLLs, unfortunately, cannot be our business.

**Comment by alkino** [comment]
And what about putting some words about it in the documentation? In the "C++ -> Lua" part for example. 

Moreover, I can't see the need of stack part in C API lua documentation. Do you have some link to it?

**Comment by ThePhD** [comment]
https://www.lua.org/pil/24.html
https://www.lua.org/pil/24.2.html

https://www.lua.org/pil/26.1.html

http://sol2.readthedocs.io/en/latest/api/stack.html

**Comment by alkino** [comment]
Thanks.

**Comment by ThePhD** [comment]
Added an example: https://github.com/ThePhD/sol2/tree/develop/examples/require_dll_example

**Comment by ThePhD** [comment]
Also added documentation for a trampoline: http://sol2.readthedocs.io/en/latest/api/stack.html#stack-call-lua
