### ISSUE TITLE
Bikeshed: top-level function wrap for outside code.

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#467]
Observe the following: https://github.com/ThePhD/sol2/issues/466#issuecomment-319497147

Specifically:
````cpp
int lua_openMy_Object( lua_State* L ) {
     sol::state_view lua(L);
     sol::table my_object_table = lua.create_table();
     my_object_table.new_usertype<test>("test",
          sol::constructors<test(), test(int)>(),
          "value", &test::value
     );
     int number_of_things_pushed_to_stack = sol::stack::push(lua, my_object_table);
     return number_of_things_pushed_to_stack;
}
````

This seems like a blahstorm waiting to happen for people who do not understand the Lua stack. We need a function that allows someone to lift the grubby details up. I propose something like `sol::wrap`. Example:

````cpp

sol::table My_Object_requires ( /* any stuff you want */, sol::this_state L ) {
     sol::state_view lua(L);
     sol::table module = lua.create_table();
     module.new_usertype<test>("test",
          sol::constructors<test(), test(int)>(),
          "value", &test::value
     );

     return module;
}

int lua_openMy_Object( lua_State* L ) {
     return sol::wrap( L, My_Object_requires );
}
````

Note the lack of knowing what a stack is and how it should work. Also note that we do this internally, we just never published that internal detail (it's currently called `sol::stack::call_into_lua` and `sol::stack::call`). Do we publish this so people have an "easy out" when working with raw Lua functions?

**Comment by ThePhD** [comment]
We'll just use `sol::stack::call_lua` and document it in an example.

**Comment by ThePhD** [comment]
Added docs: http://sol2.readthedocs.io/en/latest/api/stack.html#stack-call-lua

Used in DLL example: https://github.com/ThePhD/sol2/tree/develop/examples/require_dll_example

**Comment by ormshaw** [comment]
Would it be possible to provide a example of calling sol::stack::call_lua which passes additional arguments besides sol::this_state to the function sol calls.  something like

static
sol::table
initialiseModule(sol::this_state state, std::string string)
{
}

{
    std::string string{"Hello World!!!"};
    return sol::stack::call_lua(state, 0, initialiseModule, string);
}

as with gcc (10.1.1) I have been unable to get this working?

Thanks.
