### ISSUE TITLE
incorrect handling of large 32bit unsigned integers and 64bit signed integers

### ISSUE THREAD

**Issue by mrgreywater** [ThePhD/sol2#470]
Platform: MSVC x86 (luajit 2.1b3)
```
    lua.set_function("largeinteger", []()->std::uint32_t {
        return 0xFEFEFEFE;
    });
```
when calling this function from lua, you'll get a negative number, because 32bit unsigned integers and 64bit integers are pushed as lua_Integer (32bit signed)

See https://github.com/ThePhD/sol2/blob/e69e7c79faaa1f91b6cc736a4b08419a4da3219b/sol/stack_push.hpp#L194#L218

I haven't checked the other way around, passing large lua numbers to sol function, but it may show similar behaviour.

**Comment by ThePhD** [comment]
What exactly becomes the proper way, then, to handle these integers? I could try to push a `double` for 32-bit integers, but this would be unacceptable when we moved up to 64-bit integers since a double couldn't represent their largest values (signed or unsigned) anyhow.

**Comment by mrgreywater** [comment]
Well a double has 53 significant bite to represent the integer. I would expect the exact lua number representation for 32bit and the closest approximation for 64bit values. Not suddenly a forced 32bit signed integer. Casting to double first would work best.

**Comment by ThePhD** [comment]
As a side note, this would also mess with 5.3 code where there's a clear distinction between `int` and `double`, at least when you use API-checking functions to determine which is which.

**Comment by ThePhD** [comment]
As another additional sidenote, if you build Lua as a 64-bit library it defaults to using `long long`, which will alleviate this problem somewhat as well. Note to self: purposefully build in 32-bit to make sure that these classes of errors don't go over head...

**Comment by demianmnave** [comment]
At least 5.2 supports the notion of unsigned integers  (e.g. `lua_pushunsigned` and `lua_tounsigned{x}`).  Aren't these functions sufficient to address the problem regardless of word size?

**Comment by ThePhD** [comment]
I believe that was part of the reason why I had to change it: supporting 5.1 meant backtracking to using older functions. I could do some version-sniffing to protect against this, albeit 5.1 users will still flounder.

**Comment by demianmnave** [comment]
The version sniffing could be localized to  `sol_pushunsigned` and `sol_tounsigned{x}`, for example.  This would likely help avoid interfering with default Lua behavior, as well.

I'm probably preaching to the choir here, but having Sol2 deal with unsigned integers via double seems problematic for a variety of reasons, not the least of which is the potential to violate the principle of least surprise.

Also, I don't think this conversion behavior should default based on the Lua version.  If a user wants double<->unsigned conversions, it should be explicitly enabled at compile time.  This would help avoid interfering with the default behavior for all Lua versions.

**Comment by mrgreywater** [comment]
Sorry, but the current behaviour is simply unusable. Can we at least agree that when you pass an unsigned number to lua, you don't expect it to be negative? That's ridiculous. I agree that Lua 5.3 with integer support needs to be handled differently, but for all prior versions, you could check the size of lua_Integer and if it's too small, manually cast to a double before pushing it as such.
I know that making it work for each lua version is difficult, but casting every integral type to a signed 32bit integer can't be right.

**Comment by ThePhD** [comment]
We don't manually cast to a signed 32bit integer. We cast to what Lua recognizes as its _only_ integer type (`lua_Integer`). If you're trying to handle big numbers and build a 64-bit Lua Library, that's 64 bits, signed. If you're building 32-bit Lua Library, you get 32-bits, signed.

_And that's the only integer type it has an opening for._

Even the Lua code itself doesn't honestly care about the very-big-unsigned-numbers: `LUA_APIINTCASTS` implements `lua_pushunsigned` by casting to `lua_Integer` and dumping it with `lua_pushinteger` (same truncation/signedness problems):

````
...
#define lua_pushunsigned(L,n)	lua_pushinteger(L, (lua_Integer)(n))
...
````

"Wow, that's really wrong!" Yes, yes it is. But I don't have another choice. Lua internally discriminates between floats and integers, then lossy-overs that information by assigning everything one numeric type identifier: `number`. The most I can do is stuff it into a double, MAYBE, if I detect you're giving me a numeric value that is A) unsigned and B) exceeds the size of `lua_Integer`. But even then, Lua will get snippy with me: if I use `lua_checkinteger` or any of the checked API for safety (and sol2 does use this for argument safety), it may or may not absolutely barf. AND, if I just "gloss" it over and decide to play it off like doubles versus integers aren't a real thing, somebody [files an issue request on me](https://github.com/ThePhD/sol2/issues/247).

We can talk about how unusable it is, but at the end of the day _Lua doesn't have integer support_. Any behavior I pick is essentially whatever garbage I bikeshed and users pummel me for, or whatever compatibility smooth-overs I can think to do to help user concerns. One way or another someone's going to poke it, it's going to behave funny, and there's going to be an issue request about how awful it is.

And at this point, I can only tell you to know the limits of the system you're programming for while I try to jerry-rig a system held together by spit and imagination.

**Comment by ThePhD** [comment]
It's not just 5.1. 5.3 does not have `lua_pushunsigned` natively, probably because the people running Lua realized that having that as an API endpoint was a dumb idea when even in 5.3 the only existing integral type is a signed `lua_Integer` of 32 or 64 bits, depending on your build. So I'm once again left with the problem where I have to essentially "make up" behavior.

In 5.1, that probably means casting to `double` if the size is less than or equal to 53 bits (and just casting to `lua_Integer` otherwise and letting people build a proper 64-bit lua).

In 5.3, the only thing I can do is just do a direct push and hope the user gets it out on the other side properly.

In both cases, if your integer is too big to fit, it's going to show up as a mess in Lua (though if transported untouched through the API, it might still remain intact).

**Comment by mrgreywater** [comment]
Whats wrong with doing it like this:
if the number you want to push fits in a lua_Integer for sure (e.g typesize of pushed val < sizeof(lua_Integer) or same size if both are signed) -> lua_pushinteger
else cast to double and lua_pushnumber
This should work in all cases and version as you would expect it with the known few shortcomings.

**Comment by ThePhD** [comment]
The "few known shortcomings" are violating the expectations that users (rightfully) expected and complained about in issue #427 . It also changes the target behavior based on your build (64-bit versus 32-bit). Building with 32 bit means I have to push integers of unsigned 32-bit, signed 33+, and unsigned 33+ as doubles. Building as 64-bit means I have to push everything as integers, and then throw my hands up when someone writes 0xFEFEFEFEFEFEFEFE and expects it to come out in Lua just fine.

Finally, of what use is "as close as possible"? It's just as wrong as "this number seems to have the wrong sign"; it's wrong in every case, no matter what. There's no good automatic behavior for this.

My _ultimate_ preference is that someone casts their number to a double, explicitly. I also would not mind adding a page for conversion information, linking it from the safety page, and explaining that someone need be mindful of their build and the size of their integers. That is a better solution that allows the user to pick whatever behavior they want, and I don't have to make 1 to 4 different defaults clued in by `SOL_INTEGERS_HANDLED_LIKE_XXX` config macros.

**Comment by ThePhD** [comment]
Finally, what's a runtime warning? `throw sol::error("Your number will potentially be truncated or misinterpreted");`? sol2 builds with and without exceptions: what happens to the people with no exceptions?

**Comment by mrgreywater** [comment]
I'm working with alot of third party libraries, wrapping every function and manually casting values between double and int will completely destroy both binary size and the cleanness of the bindings. Having multiple define options seems like it would make most people happy. I'm at the point where I will just have to fork it and maintain those edits myself, but I would prefer if I didn't have to.
As for the exception, what about using lua_error if exceptions aren't enabled? (This may cause the stack not to be properly unwound, I dunno). Or bubble up the error somehow as return somehow? Or without exceptions you just can't have that error (In most cases, people disable exceptions bc of the speed penalty, and they likely don't want runtime checks aswell).

**Comment by ThePhD** [comment]
If it turns out you that your fork works well and it doesn't bite you later, I'd be happy to integrate it into sol2. I unfortunately, the best I'm going to do is probably what I mentioned earlier, _if_ I can prove that pushing an integer as a "double" and then checking `object::is<std::uint32_t>();` doesn't change from "true" to "false".
