### ISSUE TITLE
how to return self reference or dependency with usertype

### ISSUE THREAD

**Issue by mrgreywater** [ThePhD/sol2#472]
In luabind, you're able to return a reference to "self" from a usertype function. See http://www.rasterbar.com/products/luabind/docs.html#return-reference-to

In sol2, you seem to only be able to use sol::object as first argument in usertype methods, and manually parse the type, and finally return self as sol::object which is not really nice (if you return it as pointer, it won't be gc'd properly). It would be great if we could have sol::this_self, similar to sol::this_state, so you can simply return the reference of self.

In luabind you can also return a usertype member as reference with a dependency to the self instance:
http://www.rasterbar.com/products/luabind/docs.html#dependency
I would appreciate any help to get similar behaviour without wrapping all my members with std::shared_ptr.

These are just feature requests that would make the code cleaner to look at and you can workaround it, but it would be nice to have regardless :)

**Comment by ThePhD** [comment]
I'm going to be perfectly honest, I do not fully understand the motivation of this code, so I'm going to try to walk through what you're asking for.

You want to return `*this`, as a non-const reference into Lua. sol2 already supports that and returning it will return a reference, without making a copy. If you make it `const`, sol2 will make a copy and push it into Lua. What, exactly, is missing as far as "return reference to"?

Furthermore, I also don't understand the dependency issue here. Are you afraid that `this` is going to die because there are no references to it, because we keep pushing new userdata that holds pointers to some allocated data that might go out of scope?

In both of these cases, you can reference (and store) a copy of the userdata that's associated with a function call / constructor call by [pulling it off the stack](https://github.com/ThePhD/sol2/blob/develop/examples/self_from_lua.cpp). You are right that perhaps there should be some ability to control "self referencing" returns, where we get the reference for you and return it manually if it compares the same as the return value. I'll have to find out a wrapper for it...

**Comment by mrgreywater** [comment]
Here is an example usecase:
```
sol::state lua;
lua.open_libraries();
struct vec2 { float x, y; };
lua.new_usertype<vec2>("vec2",
    sol::call_constructor, sol::factories([](){
        return vec2{};
    }, [](vec2 const& v) {
        return vec2{v};
    }),
    sol::meta_function::garbage_collect, sol::destructor([](vec2& self){
        //write bogus data, to show self is now invalid and points to free'd memory 
        self.x = std::numeric_limits<float>::quiet_NaN();
        self.y = std::numeric_limits<float>::quiet_NaN();
    }),
    "x", &vec2::x,
    "y", &vec2::y,
    "rotate", [](vec2& self, double theta)->vec2& {
        double x = self.x;
        double y = self.y;
        auto cos_theta = std::cos(theta);
        auto sin_theta = std::sin(theta);
        self.x = (float)(x * cos_theta - y * sin_theta);
        self.y = (float)(x * sin_theta + y * cos_theta);
        return self; //returns c++ reference of self, what I want is that it returns the lua reference or has a dependency (as soon as the gc is executed, this returned reference points to invalid mem)
    },
    "scale", [](vec2& self, float scale)->vec2& {
        self.x *= scale;
        self.y *= scale;
        return self;
    }
);
sol::protected_function_result result = lua.do_string(
    "local v = vec2()"                                                              "\r\n"
    "v.x, v.y = 1, 0"                                                               "\r\n"
    "local t = v:rotate(math.pi / 2):scale(2)"                                      "\r\n"
    "print(tostring(v.x) .. ', ' .. tostring(v.y))"                                 "\r\n"
    //"assert(v == t)"                                                              "\r\n" //test lua reference is same. will fail
    "assert(math.abs(v.x) < 0.0001 and math.abs(v.y - 2) < 0.0001)"                 "\r\n" //test if chain execution worked. will be successful
    "assert(v.x == t.x and v.y == t.y)"                                             "\r\n" //test if t, the reference of v, has the same contents as v. will be successful
    "v = nil"                                                                       "\r\n"              
    "collectgarbage()"                                                              "\r\n"
    "assert(math.abs(t.x) < 0.0001 and math.abs(t.y - 2) < 0.0001)"                 "\r\n" //test if the reference t kept the created vector alive (and it also has the same content as old v). will fail
);
if (result.valid()) {
    std::cout << "Success" << std::endl;
} else {
    sol::error e = result;
    std::cout << "Fail: " << e.what() << std::endl;
}
```
Basically i would love to avoid passing references to lua that will not be kept alive. Having either a dependency, or being able to return the lua reference to a parameter would help tremendously.

**Comment by mrgreywater** [comment]
Another example where a dependency would be nice (without having to wrap unit::pos in a shared_ptr)
```
sol::state lua;
lua.open_libraries();
struct vec2 { float x, y; };
struct unit { vec2 pos; };
lua.new_usertype<vec2>("vec2",
    sol::call_constructor, sol::factories([]() {
        return vec2{};
    }),
    "x", &vec2::x,
    "y", &vec2::y
);
lua.new_usertype<unit>("unit",
    sol::call_constructor, sol::factories([](){
        return unit{};
    }),
    "pos", sol::property([](unit& self)->vec2& {
        return self.pos; //somehow return the pos as reference with dependency
    }),
    sol::meta_function::garbage_collect, sol::destructor([](unit& self){
        //write bogus data, to show self is now invalid and points to free'd memory 
        self.pos.x = std::numeric_limits<float>::quiet_NaN();
        self.pos.y = std::numeric_limits<float>::quiet_NaN();
    })
);
sol::protected_function_result result = lua.do_string(
    "local u = unit()"                                                              "\r\n"
    "local pos = u.pos"                                                             "\r\n"
    "u.pos.x, u.pos.y = 1, 0"                                                       "\r\n"
    "assert(u.pos.x == 1 and u.pos.y == 0)"                                         "\r\n"
    "assert(pos.x == 1 and pos.y == 0)"                                             "\r\n"
    "u = nil; collectgarbage()"                                                     "\r\n"
    "assert(pos.x == 1 and pos.y == 0)"                                             "\r\n" //test if reference still points to valid mem. will fail (may cause segfault/access violation like this)
);
if (result.valid()) {
    std::cout << "Success" << std::endl;
} else {
    sol::error e = result;
    std::cout << "Fail: " << e.what() << std::endl;
}
```

**Comment by ThePhD** [comment]
I could do `sol::this_self`, but the main problem would be lossless transference of where `this` is. For constructors, it's at the end of the stack. For regular member functions, it's at the beginning. For lambdas and properties, it may or may not exist at all (static function, write-only one-off properties, etc...). It will take a while to restructure things internally to make this work out just fine.

As for "linked dependencies", where something like a member variable depends on its originator, that's a tiny bit harder to do. I can make it so something like `pos.x` will go through a function and always reference `u` before hitting `pos`. But if you just pass around `pos` to, say, a print function or something, or you try to do `vec2& pos = lua["pos"];` (assuming you don't local it). sol2's code will break down a little. We'd have to detect you're using a special dependency-reference, and then find out where to find the original dependency. As of right now, `lua_newuserdata` allocates space for me to dump stuff, but doesn't really give me a way to stick things like a lua reference "with" that data (Lua 5.3 actually has something for it, but sol2 is supposed to work across all 3 major lua versions so I'd need to think of something).

Regarding the destructor, sol2 automatically generates a destructor for all your types. It's not missing, and we have tests that check this. In what case are destructors "not firing" for you?

**Comment by mrgreywater** [comment]
- sol::this_self would be nice, especially since self may be a different positions on the stack. I see it's not trivial.
- as for the dependencies, i guess you have to store the dependency somewhere along with lua's userdata object for the reference, luabind also works for old lua versions, so there must be some way. From the api perspective, it could maybe look like `return sol::dependency(sol::make_object(L, pos), self)` with self being that sol::this_self or some other sol::object.
- I had something like this and the destructor didn't fire
```
sol::state lua;
lua.open_libraries();
struct vec2 { float x, y; };
lua.new_usertype<vec2>("vec2",
    sol::call_constructor, sol::factories([](){
        return vec2{};
    }, [](vec2 const& v) {
        return vec2{v};
    }),
    sol::meta_function::garbage_collect, [](vec2& self){
        //write bogus data, to show self is now invalid and points to free'd memory 
        self.x = std::numeric_limits<float>::quiet_NaN();
        self.y = std::numeric_limits<float>::quiet_NaN();
    },
    "x", &vec2::x,
    "y", &vec2::y,
);
sol::protected_function_result result = lua.do_string(
    "local v = vec2()"      "\r\n"
    "v = nil"				"\r\n"
    "collectgarbage()"		"\r\n"
);
if (result.valid()) {
    std::cout << "Success" << std::endl;
} else {
    sol::error e = result;
    std::cout << "Fail: " << e.what() << std::endl;
}
```

**Comment by ThePhD** [comment]
Oh, right. You must wrap the `gc` method with `sol::destruct` or similar. It's written in the docs, here: http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-destructor-options

I guess a compile-time error would be nicer...?

**Comment by mrgreywater** [comment]
Well, it would be best if it would work even without wrapping it in sol::destructor, but a compile time error would be alright. So you see immediatly that it won't work.

**Comment by ThePhD** [comment]
I can't quite make this work without making `new_usertype` even more compile-time and runtime intensive. `sol::meta_function::garbage_collect` is -- ultimately -- a runtime label. I'd have to go through every key and see you specified it. `sol::destruct` was specifically make to avoid that problem and give me a way to simply sweep through all the stuff at compile-time and know you specified a destructor.

Plus, the check for seeing if I _should_ automatically generate a destructor is one I can only make at compile time [`std::is_destructible`](http://en.cppreference.com/w/cpp/types/is_destructible). If I check if the name exists using runtime checks, and then generate a destructor for you in the bracket of an `if` statement, I'd break everything (unless I write another level of indirection using `std::true_type` and `std::false_type` to switch on that).

And while the solution in the above paragraph sounds nice, you also need to find a way to do all of this in the syntax of a constructor...

... Yeah just specify `sol::destruct` around your destructors, please!

**Comment by ThePhD** [comment]
Added a few runtime checks (debug mode / throwing-enabled) only to explicitly annoy the user when they do not wrap the function in a `sol::destruct`.

**Comment by ThePhD** [comment]
I don't understand how dependencies work, in the case of making a variable depend on another. If I return the original userdata with some extra work into some variable `x` in Lua, I can't make, for example...

````
x = v.x
x = 25
print(x)
````

Because I can't override the setter or the getter for a plain variable. It has to be `obj.something` or `obj.something = something_else` for me to make it work. The self-dependency thing I can do fine but this isn't something I can rationalize properly, unless I'm thinking of the "variable" dependency wrong?

**Comment by ThePhD** [comment]
Well, I figured it out mostly.

BIKESHED: what is the name for this? `sol::policy( stuff )` seems pretty bland.

````
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

#include <limits>
#include <iostream>

int main(int argc, char* argv[]) {

	struct dep {
		int value = 20;
		~dep() {
			std::cout << "\t" << "[C++] ~dep" << std::endl;
		}
	};

	struct gc_test {

		dep d;

		~gc_test() {
			std::cout << "\t" << "[C++] ~gc_test" << std::endl;
			d.value = std::numeric_limits<int>::max();
		}
	};

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<dep>("dep",
		"value", &dep::value,
		sol::meta_function::to_string, [](dep& d) { 
			return std::to_string(d.value); 
		}
	);
	lua.new_usertype<gc_test>("gc_test",
		"d", sol::policy<sol::self_dependency_policy>(&gc_test::d),
		sol::meta_function::to_string, [](gc_test& g) { 
			return "{ d: " + std::to_string(g.d.value) + " }"; 
		}
	);

	lua.script(R"(
local g = gc_test.new()
local d = g.d
print("new gc_test, d = g.d")
print("", g)
print("g = nil, collectgarbage")
g = nil
collectgarbage()
print("", d)
print("d = nil, collectgarbage")
d = nil
collectgarbage()
)");
	
	return 0;
}
````

**Comment by ThePhD** [comment]
Output:

![It's alive](http://i.imgur.com/gTS6IER.png)

**Comment by mrgreywater** [comment]
Mmh, this looks really promising! as for the name, I have no idea, except that maybe the policies can have their own namespace like sol::policy<sol::policy::self_dependancy>(). If you only want to support self dependency, it could even be just sol::self_dependency()
As for returning sol::stack_object(L, 1); this doesn't work sadly, as I think the args of the function are popped from the stack by sol before the return values are pushed again, so (L, 1) is invalid. You can return sol::object(L, 1) fine, but only with the expected performance penalty due to the lua registry reference.

**Comment by ThePhD** [comment]
In my latest edits, I fixed returning a stack-based object (that is, anything that derives from `sol::stack_reference`). Now it will not "clean the stack" when it's done, but if a lot of functions that return a stack-based reference are called within one another over and over again, it can leave a lot of crap on the stack before it all gets cleaned up from the initial call.

Finally, a bikeshed happened and the names changed. Things look like this now:

````cpp
    struct holder;
    struct depends_on_reference;
    struct composition_related;
    static std::vector<composition_related*> composition_relateds_destroyed;
    static std::vector<holder*> holders_destroyed;
    static std::vector<depends_on_reference*> depends_on_references_destroyed;

    struct composition_related {
        std::string text = "bark";

        ~composition_related() {
            std::cout << "[C++] ~composition_related" << std::endl;
            text = "";
            composition_relateds_destroyed.push_back(this);
        }
    };

    struct holder {
        int value = 20;
        ~holder() {
            std::cout << "[C++] ~holder" << std::endl;
            value = std::numeric_limits<int>::max();
            holders_destroyed.push_back(this);
        }
    };

    struct depends_on_reference {

        std::reference_wrapper<holder> href;
        composition_related comp;

        depends_on_reference(holder& h) : href(h) {}

        ~depends_on_reference() {
            std::cout << "[C++] ~depends_on_reference" << std::endl;
            depends_on_references_destroyed.push_back(this);
        }
    };

    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.new_usertype<holder>("holder",
        "value", &holder::value
    );
    lua.new_usertype<depends_on_reference>("depends_on_reference",
        "new", sol::filters(sol::constructors<depends_on_reference(holder&)>(), sol::stack_dependencies(-1, 1)),
        "comp", &depends_on_reference::comp
    );

    lua.script(R"(
h = holder.new()
dor = depends_on_reference.new(h)
c = dor.comp
)");
    REQUIRE(composition_relateds_destroyed.empty());
    REQUIRE(holders_destroyed.empty());
    REQUIRE(depends_on_references_destroyed.empty());

    holder* h = lua["h"];
    composition_related* c = lua["c"];
    depends_on_reference* dor = lua["dor"];

    REQUIRE(h == &dor->href.get());
    REQUIRE(c == &dor->comp);

    lua.script(R"(
h = nil
collectgarbage()
)");
    REQUIRE(composition_relateds_destroyed.empty());
    REQUIRE(holders_destroyed.empty());
    REQUIRE(depends_on_references_destroyed.empty());

    lua.script(R"(
c = nil
collectgarbage()
)");

    REQUIRE(composition_relateds_destroyed.empty());
    REQUIRE(holders_destroyed.empty());
    REQUIRE(depends_on_references_destroyed.empty());

    lua.script(R"(
dor = nil
collectgarbage()
)");

    REQUIRE(composition_relateds_destroyed.size() == 1);
    REQUIRE(holders_destroyed.size() == 1);
    REQUIRE(depends_on_references_destroyed.size() == 1);
    REQUIRE(composition_relateds_destroyed[0] == c);
    REQUIRE(holders_destroyed[0] == h);
    REQUIRE(depends_on_references_destroyed[0] == dor);
````

So it's called `sol::filters` now, and things aren't passed as template arguments: they're passed as regular arguments. You can also pass a lambda:

 ````cpp
sol::filters( my_function, [](lua_State* L, int push_count) -> int { 
          /* do stuff, add or subtract from push count, generally beat up the stack... */ 
          return push_count; 
     }
);
````

**Comment by ThePhD** [comment]
Done. Docs are deployed: http://sol2.readthedocs.io/en/latest/api/filters.html

Thanks for the help.
