### ISSUE TITLE
code crashed,one thread one sol::state, with vs2015 update3

### ISSUE THREAD

**Issue by sniper00** [ThePhD/sol2#474]
```cpp
void test()
{
	sol::state lua;
	try
	{
		//may crash or exception
		lua.open_libraries();
	}
	catch (sol::error& e)
	{
		printf("error %s \r\n", e.what());
	}

	// Lua API is ok
	//auto L = luaL_newstate();
	//luaL_openlibs(L);
	std::this_thread::sleep_for(std::chrono::seconds(100000));
}

int main(int argc, char*argv[])
{
	std::thread th[10];
	for (int i = 0; i < 10; i++)
	{
		th[i] = std::thread(test);
	}

	for (int i = 0; i < 10; i++)
	{
		th[i].join();
	}

	return 0;
}
```

**Comment by sniper00** [comment]
I used sol2 in multithreaded, one thread one sol::state, but these code may crash or raise exception. use lua API is ok.

**Comment by ThePhD** [comment]
This may be releated to #458 . I will test this code on my working copy once I put the fix in for that issue.

**Comment by ThePhD** [comment]
As reported in #458, this is now fixed VIA: https://github.com/ThePhD/sol2/blob/104485bebd6908d3eeff2825d7f686e9632fb9e6/sol/protected_function.hpp#L60

Let me know if things keep breaking in other versions.

**Comment by mrgreywater** [comment]
Also look here: std::wstring_convert is not thread-safe
https://github.com/ThePhD/sol2/blob/develop/single/sol/sol.hpp#L7928

**Comment by ThePhD** [comment]
I can knock the static off, but for performance reasons I'd like to avoid that since someone actually complained about it not being static and dragging performance down considerably.

Maybe I can make it `thread_local` as a compromise?

**Comment by ThePhD** [comment]
Finally, `SOL_NO_EXCEPTIONS` triggers automatically when we detect someone has actually turned off exceptions VIA predefined compiler macros based on compilation switches. If someone leaves exceptions on in the compiler and then defines `SOL_NO_EXCEPTIONS`, whatever happens is entirely Their Fault™ and unless I decide to reimplement UTF8/16/32 handling (haaaaa hahaha no never it's a can of worms) there's no way for me to force the code to never throw an exception.

**Comment by mrgreywater** [comment]
If it's stored in the TLS it should be fine, but having it shared between threads is just asking for trouble. As for the exceptions, maybe catch them and convert to a luaL_error as you did in other places aswell. Even though just throwing is likely also fine for most use cases.

**Comment by mrgreywater** [comment]
There's also the non-throwing http://en.cppreference.com/w/cpp/string/multibyte/c32rtomb (see their example) and friends which might be more work, but then you could have better noexcept support in sol2 for wide strings.

**Comment by ThePhD** [comment]
Alright, but what happens when `c32rtomb` indicates an error? We'd be back to the same problem of "how do we tell the users this is not valid?". And once again, we'd just be doing `#ifdef SOL_NO_EXCEPTIONS` and throwing anyways, or asserting (and silently not caring). The standard library already has mechanisms to detect if it is compiling without exceptions and remove the exceptions from being tossed (but good luck knowing when things go wrong).

But then again, that's the point: people who turn off exceptions generally know what they're doing, so that's their problem.

**Comment by mrgreywater** [comment]
Well, I think the best thing would be if the conversion was done in stack::check, and if it's an invalid wstring, then report an error that no fitting overload was found (or use the string overload if there is any). In stack::check_get simply handle the error like any other type mismatch, in stack::push convert the c32rtomb error to a luaL_error.
But I also think all this work is likely not worth it, unless somebody requests it. Just using codecvt with a thread local variable should be fine.

**Comment by ThePhD** [comment]
That would entail essentially checking entire strings for safety. Compared to `llround` on every double that's being checked for integral compatibility, this is a performance nightmare just for correctness.

These conversions are literally only for convenience. If someone was serious about their conversions they can pull out a `const char*` or a `std::string`, and then perform the conversions themselves (or just cast directly: Lua states explicitly that its strings are simply a byte sequence with no special semantics attached, although the language _itself_ will always make its literals utf8 and the like). You'd only ever deal with unicode/wide strings if you started asking for them, and at that point you've already stepped into the rabbit hole: we provide Sensible Defaults™ with Reasonable Performance®, and if someone wants something crazier we don't exactly hide the internals: http://sol2.readthedocs.io/en/latest/api/stack.html

Either way, v2.18.0 was updated to use `thread_local`: https://github.com/ThePhD/sol2/releases/tag/v2.18.0
