### ISSUE TITLE
lua_class inherit cpp_class cannot register new function

### ISSUE THREAD

**Issue by longlt3** [ThePhD/sol2#475]
cpp:

`struct State {  };`

lua:
```
state_sleep = State.new()
function state_sleep:execute()
-- do smt
end
```

above code caused a crash.

does sol2 can do these stuff ?

**Comment by ThePhD** [comment]
No. sol2 cannot register a new function on an instance. It can only register on a new class. Use `State:execute` to add to the class.

You can also achieve this functionality by having a table that defers its unknown operations to `State`'s metatable. You can do this by creating a table and then setting its `__newindex` and `__index` functions appropriately.

**Comment by ThePhD** [comment]
Now with a clarification and a reader's note: http://sol2.readthedocs.io/en/latest/api/usertype.html?highlight=usertype#runtime-functions

There's also an example in the repository illustration this concept directly:
https://github.com/ThePhD/sol2/blob/develop/examples/runtime_additions.cpp

**Comment by longlt3** [comment]
I got it now
Thank you :)

**Comment by longlt3** [comment]
Could you please make more clear about 

> You can also achieve this functionality by having a table that defers its unknown operations to State's metatable. You can do this by creating a table and then setting its __newindex and __index functions appropriately.

I tried this way, but no luck
cpp:
```
struct Base 
{
    int m_hp;
    void base_func() { printf("base_func\n"); }
};
```
lua:
```
inherit = {}
inherit.__index = Base.__index
inherit.__newindex = Base.__newindex
function inherit:new (o)
    o = o or {}
    setmetatable(o, self)
    return o
end
function inherit:inherit_func()
    print(tostring(self).." inherit:inherit_func")
end

local l_ins = inherit:new()
l_ins:inherit_func()
print(l_ins.hp) // crashed
l_ins:base_func() // crashed
```

my purpose is: overload base_func and create new inherit_func also
