### ISSUE TITLE
Table and State can not have multiple things pulled out as pair

### ISSUE THREAD

**Issue by iaz3** [ThePhD/sol2#477]
I'm using Visual Studio 2017, compiling with  and following the [tutorial](http://sol2.readthedocs.io/en/latest/tutorial/variables.html)

In the Variables example, the line 
```
// table and state can have multiple things pulled out of it too
std::pair<int, int> xyresolution = resolution.get<int, int>( "x", "y" );
```

Fails to compile, citing a lack of conversion operators.

Specifically
```
error C2440: 'initializing': cannot convert from 'sol::stack::getter<std::tuple<Ret0,Ret1>,void>::R' to 'std::pair<int,int>'
        with
        [
            Ret0=int,
            Ret1=int
        ]
note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

I don't know if this is a documentation issue, sol2 bug, MSVC specific thing, or something else, so..

Oh, and i just noticed that this line `auto resolution = config.get<sol::table>("config");` is wrong. config there should be resolution

**Comment by ThePhD** [comment]
Most of the tutorials are serialized as a form of example, but what I should do is take all the code from tutorials and put them in actual cpp files as-they-are, and then use a build step to copy-pasta them into the docs so I know they work 100%...

That's going to take a while.

In the meantime, it seems like Visual Studio 2017's pair code added some new pair constructors that don't play ball. I don't quite know how to get around the issue right now, and some basic attempts at fixing it don't work. I'm just going to remove the line from the tutorial (and fix the typos).

Sorry about this; just don't try to pull out a `std::pair` in that way anymore, and use `std::tuple` instead.
