### ISSUE TITLE
Container Usertypes are not iterable

### ISSUE THREAD

**Issue by iaz3** [ThePhD/sol2#478]
Using the latest release of sol2, Visual Studio 2017 and compiled as C++17 through the appropriate compiler flags

I have a class, X, which satisfies the requirements of [Container](http://en.cppreference.com/w/cpp/concept/Container) and holds a different class, Y.

Class X has methods and functions that help manipulate Y's, and i want this class to be exposed to Lua.
As such, i've attempted to register it as a usertype, which works, but I can't for the life of me figure out how to get the actual Container part to work. No matter what i try i can't iterate over it from Lua.

I have tried specializing the is_container template to be true, but that does not visibly change anything.

Is this not possible in sol2? Am i missing something?

**Comment by Nava2** [comment]
Do you have a sample of the container? Does `sol::is_container<X>::value == true`?

**Comment by iaz3** [comment]
Yes, i've tried specializing the template for the container, still doesnt work.

**Comment by iaz3** [comment]
It may be worth noting that Class Y is itself a container for a further class, Z, which is also a container, and that all these classes share a common abstract base class.(Which itself is not a container.)

`sol::is_container<Y>`, and `sol::is_container<Z>` are both specialized to be false for reasons.

**Comment by Nava2** [comment]
Can you create a set of code that showcases the issue?

**Comment by iaz3** [comment]
The following code yields this output
```
1
Unhandled Error: lua: error: [string "..."]:4: bad argument #1 to 'for iterator' (table expected, got sol.X)
```
Alternatively, without pairs, `Unhandled Error: lua: error: [string "..."]:4: attempt to call a sol.X value`

deref_iter is a template class that satisfies Iterator to the extent that it's template argument does, and performs an extra dereference to hide the fact i use pointers.

```C++
class Y {
public:
	std::vector<int*> data;
	Y(int i) { data.push_back(new int(i)); }
public:
	int method_Y() const { return data.size(); }
public: // Container Requirements, operators, etc.
	using value_type = int;
	using reference = value_type&;
	using const_reference = const value_type&;
	using iterator = deref_iter<decltype(data)::iterator>;
	using const_iterator = const_deref_iter<decltype(data)::const_iterator>;
	using difference_type = decltype(data)::difference_type;
	using size_type = decltype(data)::size_type;
	Y(const Y &other);
	Y(Y &&other) noexcept = default;
	Y &operator=(Y &&other) noexcept = default;
	Y &operator=(const Y &other);
	iterator begin() { return iterator(data.begin()); }
	iterator end() { return iterator(data.end()); }
	const_iterator begin() const { return const_iterator(data.begin()); }
	const_iterator end() const { return const_iterator(data.end()); }
	const_iterator cbegin() const { return begin(); }
	const_iterator cend() const { return end(); }
	size_type size() const noexcept { return data.size(); }
	size_type max_size() const noexcept { return data.max_size(); }
	bool empty() const noexcept { return data.empty(); }
	friend bool operator==(const Y &lhs, const Y &rhs) noexcept { return lhs.data == rhs.data; }
	friend bool operator!=(const Y &lhs, const Y &rhs) noexcept { return !(lhs == rhs); }
};

class X {
public:
	std::vector<Y*> data{new Y(666)};
public:
	X() = default;
	int method_X() const { return data.size(); }
public: // Container Requirments, operators, etc.
	using value_type = Y;
	using reference = value_type&;
	using const_reference = const value_type&;
	using iterator = deref_iter<decltype(data)::iterator>;
	using const_iterator = const_deref_iter<decltype(data)::const_iterator>;
	using difference_type = decltype(data)::difference_type;
	using size_type = decltype(data)::size_type;
	X(const X &other);
	X(X &&other) noexcept = default;
	X &operator=(X &&other) noexcept = default;
	X &operator=(const X &other);
	iterator begin() { return iterator(data.begin()); }
	iterator end() { return iterator(data.end()); }
	const_iterator begin() const { return const_iterator(data.begin()); }
	const_iterator end() const { return const_iterator(data.end()); }
	const_iterator cbegin() const { return begin(); }
	const_iterator cend() const { return end(); }
	size_type size() const noexcept { return data.size(); }
	size_type max_size() const noexcept { return data.max_size(); }
	bool empty() const noexcept { return data.empty(); }
	friend bool operator==(const X &lhs, const X &rhs) noexcept { return lhs.data == rhs.data; }
	friend bool operator!=(const X &lhs, const X &rhs) noexcept { return !(lhs == rhs); }
};

namespace sol {
	template <>
	struct is_container<X> : std::true_type {};
}

void createState() {
	static_assert(sol::is_container<X>::value);
	sol::state lua;
	// open some common libraries
	lua.open_libraries(sol::lib::base, sol::lib::package, sol::lib::string, sol::lib::os, sol::lib::coroutine,
	                   sol::lib::math, sol::lib::table, sol::lib::io);
	// make usertype metatable
	lua.new_usertype<Y>("Y",
	                    sol::constructors<>(),
	                    "sizeY", sol::property(&Y::method_Y)
	                   );
	lua.new_usertype<X>("X",
	                    sol::constructors<X()>(),
	                    "sizeX", sol::property(&X::method_X)
	                   );

	lua.script(R"(
		local x = X.new()
		print(x.sizeX)
		for i, k in pairs(x) do
			print(i, k, k.sizeY)
		end
)");
}
```

**Comment by iaz3** [comment]
This code, though, works fine, and correctly iterators the vector, yielding 
```lua
1       555
2       666
3       777
```

```C++
lua["test"] = std::vector<int>{555, 666, 777};
lua.script(R"(
	for i, k in pairs(test) do
		print(i, k)
	end
)");
```

**Comment by ThePhD** [comment]
Sounds like you're using Lua 5.1 (that's where the `pairs` error comes from).

We warn you about this [under the example](http://sol2.readthedocs.io/en/latest/api/containers.html#a-complete-example).

I should make that warning bigger, with its own warning box and everything....

**Comment by ThePhD** [comment]
Oh. OH. I'm blind and dumb. This has nothing to do with Lua 5.1, sorry!

You're registering a `new_usertype` for `X`, and then trying to iterate over it. You can't do that and also have sol2 inject all of the functions and niceties to make it behave like a container, plus the extra functions: you have to implement `__pairs` and handle `__newindex` and `__index` yourself, since you're essentially taking control of the metatable when you register `__newindex` doing this.

This is my fault: I should explicitly specify that if you do `new_usertype`, you override the container-specific metatable. I'll add this note to the docs. 

One thing I can also do, though, is check if you've implemented `__pairs`. If you haven't I might be able to smear in a default implementation if I can detect that `is_container<T>` and other related type checks are true...

**Comment by iaz3** [comment]
A default implementation for container userdata that isnt doing it's own thing would be nice.
As it stands, this is a blocker for my usecase.

Kind of defeats the purposes otherwise imo.

**Comment by ThePhD** [comment]
Well, as a disclaimer the most I can do for you is handle `__pairs` automagically, which will allow you to call `pairs` on your type (in Lua 5.2 and 5.3). Otherwise, it'll be your job to handle things like manual iteration and manual get/set (`test:get(index)` isn't something I can define manually for you, for example, and neither can I define `test[index]` and similar since those are taken up by things you define on the usertype table).

**Comment by iaz3** [comment]
Actually now that i think about it, this wouldnt work because all sorts of other things, like the methods, would show up in iteration right?

What would be a better way to handle dual types like this would be some sort of wrapper on the sol side that forcefully treats a type as a container

Something like this

```C++
lua.new_usertype<X>("X",
	                    sol::constructors<X()>(),
	                    "Get", sol::container<X>()
	                   );
```

I tried to do something like that earlier, by it didn't work since sol wil just convert it into the userdata for lua.

Then in Lua you use it like `for i,k in pairs(X:Get()) do`

**Comment by ThePhD** [comment]
I would change the name `Get()` into `iterable`. Then, you would want to return a small shim that, at bare minimum, contains `begin()`, `end()`, and maybe a `size()` function. You would also want to have the typedefs `value_type` and `iterator` on it. By having those functions and those typedefs, it will be treated like a container, provided you don't also override that metatable.

Finally, no it wouldn't have methods or anything else show up in iteration (and it currently won't iterate methods and the like either).

**Comment by iaz3** [comment]
Well `Get()` in that example is just a function name, like any other on the usertype. User choice what its called.

As for the shim, thats what the made up sol::container<T>() would do. for a type T that would be treated as a container by sol if not for being a usertype, pretend it isnt a usertype and treat it like any other container.

**Comment by ThePhD** [comment]
That sounds like a slightly more elegant and controllable solution. I'd be willing to add both, but your second suggestion will take a lot more time.

**Comment by iaz3** [comment]
I don't need the first one and the shim i've already written up and got working

```C++
template <typename T>
class shimT {
public:
	T &s;
	shimT(T &s) : s(s) { }
public:
	using value_type = typename T::value_type;
	using reference = typename T::reference;
	using const_reference = typename T::const_reference;
	using iterator = typename T::iterator;
	using const_iterator = typename T::const_iterator;
	using difference_type = typename T::difference_type;
	using size_type = typename T::size_type;
	shimT(const shimT &other) = default;
	shimT(shimT &&other) = default;
	shimT &operator=(shimT &&other) = default;
	shimT &operator=(const shimT &other) = default;
	iterator begin() { return s.begin(); }
	iterator end() { return s.end(); }
	const_iterator begin() const { return s.begin(); }
	const_iterator end() const { return s.end(); }
	const_iterator cbegin() const { return begin(); }
	const_iterator cend() const { return end(); }
	size_type size() const noexcept { return s.size(); }
	size_type max_size() const noexcept { return s.max_size(); }
	bool empty() const noexcept { return s.empty(); }
	friend bool operator==(const shimT &lhs, const shimT &rhs) noexcept { return lhs.s == rhs.s; }
	friend bool operator!=(const shimT &lhs, const shimT &rhs) noexcept { return !(lhs == rhs); }
};

template <typename T>
shimT<T> shim(T &t) {
	return shimT<T>(t);
}
```

Usage

```lua
lua.new_usertype<T>("T",
	                            "Get", &shim<T>
	                           );
```

**Comment by ThePhD** [comment]
That will do the trick, yes! But it will only work for, say, `std::vector`. It also only allows you to iterate and get size (what about `insert`, `erase`, `find`, ... ).

Still, as long as it gets the job done! I'll leave this issue open to track progress on the other basic things I'm working on.

**Comment by iaz3** [comment]
It should work for *all* standard compliant Containers, since they all satisfy [these requirements](http://en.cppreference.com/w/cpp/concept/Container), and any user defined type that also satisfies those(which they should if theyre going around containing items)

Of course, it technically only needs to satisfy whatever sol2 needs/wants for container support. I just like my stuff to match standard things personally, so thats how i wrote it.

**Comment by ThePhD** [comment]
While we're on this bender...

`new_usertype` now generates its own `__tostring`, `__pairs`, `__len` and `__call` operators for the Lua code if it's supported. Still have to check `simple_usertype`s, though.

**Comment by iaz3** [comment]
?

**Comment by Nava2** [comment]
@iaz3, @ThePhD tends to post his streams of "thoughts" as reminders -- I wouldn't worry about it.

**Comment by ThePhD** [comment]
Shim, now part of sol2 in `as_container`:
https://github.com/ThePhD/sol2/blob/develop/examples/container_as_container.cpp
http://sol2.readthedocs.io/en/latest/api/as_container.html

Note that basic iteration on a user type is allowed as long as `value_type`, `iterator` `begin`, and `end` are present, without having to create a shim (5.2+ using pairs only). Also note that if member function `.size()` exists, we will use it for `#obj`:
https://github.com/ThePhD/sol2/blob/develop/examples/usertype_automatic_operators.cpp

Along with this are generic `__tostring` lookups and also automatic `__call` generation for Lua.

**Comment by ThePhD** [comment]
Incorporated formally into latest release: https://github.com/ThePhD/sol2/releases/tag/v2.18.0

**Comment by Leadwerks** [comment]
I am implementing a debugger and have exactly this problem. Is there something I can do to make this work with Lua 5.1 or do I have to change the Lua version?
