### ISSUE TITLE
luajit 2.0.4 have luaL_loadbufferx and luaL_loadfilex

### ISSUE THREAD

**Issue by Koncord** [ThePhD/sol2#479]
When invoking sol::state::script_file() code going to infinite loop.
There is no need re-implement these functions for 2.0.4.

**Comment by ThePhD** [comment]
Last I checked, 2.0.4 had _neither_ of these functions....

**Comment by ThePhD** [comment]
But, both of these functions are implemented in 2.0.5. Time to update the compatibility shim...

**Comment by Koncord** [comment]
Checked in 2.0.1
`koncord@Commodore64 ~/tes3mp-dev/LuaJIT-2.0.1 $ grep -rn ./src -e "luaL_loadfilex"
./src/lib_base.c:380:  status = luaL_loadfilex(L, fname ? strdata(fname) : NULL,
./src/lj_load.c:84:LUALIB_API int luaL_loadfilex(lua_State *L, const char *filename,
./src/lj_load.c:119:  return luaL_loadfilex(L, filename, NULL);
./src/lauxlib.h:81:LUALIB_API int (luaL_loadfilex) (lua_State *L, const char *filename,
`

**Comment by ThePhD** [comment]
Forcibly check for 2.0.1 and turn off compat functions for LuaJIT if that's the case: https://github.com/ThePhD/sol2/blob/develop/sol/compatibility/5.1.0.h#L160
