### ISSUE TITLE
Incomplete stack traceback with SOL_USING_CXX_LUA

### ISSUE THREAD

**Issue by jeychenne** [ThePhD/sol2#480]
This is a follow-up to issue #461, and I think I found why I was having an issue in the first place. I compile my own version of lua 5.3 as C++, and I use  SOL_USING_CXX_LUA. When this is turned on, the trace stack I get in case of missing arguments I get is incomplete:

```
runtime error caught (...) exception stack traceback: [C]: in field 'list_directory' /home/julien/Devel/dolmen/unit_test/lua/test.lua:3: in main chunk
``` 

When the define is off and I compile against my system's version of lua (which is compiled as C), I now get a proper error message indicating that an argument was missing:

```
sol: runtime error: /home/julien/Devel/dolmen/unit_test/lua/test.lua:3: stack index 2, expected boolean, received no value
stack traceback:
	[C]: in field 'list_directory'
	/home/julien/Devel/dolmen/unit_test/lua/test.lua:3: in main chunk
```

Is there any reason why lua-compiled-as-C++ doesn't behave as expected?

**Comment by ThePhD** [comment]
This is likely because we catch all exceptions using `...`. `luaL_error` communicates its errors by using a `throw` statement when you build with C++: likely, we're accidentally stuffing the error.

This is only a guess. I'll have to give it a spin and a try and see if I can't make something work out just a tiny bit better...

**Comment by ThePhD** [comment]
It looks like you'd need to have defined `SOL_EXCEPTIONS_SAFE_PROPAGATION` when using `SOL_USING_CXX_LUA`.

I define it for you now when you define `SOL_USING_CXX_LUA`, and it works out well enough:

![Wew lads](http://i.imgur.com/CfntzlP.png)

**Comment by ThePhD** [comment]
Noted here: http://sol2.readthedocs.io/en/latest/exceptions.html#lua-and-luajit-c-exception-full-interoperability
