### ISSUE TITLE
sol::state_view will crash if you close the state before the end of it's scope

### ISSUE THREAD

**Issue by iaz3** [ThePhD/sol2#482]
I was doing some refactoring and just got bit by this.

If you happen to close a lua_State in the same scope as a sol::state_view of that same lua_State, when the scope ends you'll get intermittent crashes depending on your luck when it's destruction tries to use the state.

Not a bug per se, but a note in the docs would be nice.

Luckily the fix is to just put braces around all code that uses the sol::state_view, thus creating a new scope, and close the state outside of them where it's safe.

**Comment by ThePhD** [comment]
Right, `sol::state_view` gets a reference to the global table and the registry upon creation. It has to remove those entries upon it going out of scope. I think I mention that it does this in the constructor docs, but not sure...

Either way, will make sure it's added to the docs.

**Comment by ThePhD** [comment]
Put a big ol' warning: http://sol2.readthedocs.io/en/latest/api/state.html#state
