### ISSUE TITLE
error binding sol::property with const and non-const getter

### ISSUE THREAD

**Issue by joe-92** [ThePhD/sol2#484]
I try to bind a getter to my usertype, which is overloaded as const and non-const version:
```c
struct S {
  void set(const int v) {
    value = v;
  }
  
  int &get() {
    return value;
  }
  
  const int &get() const {
    return value;
  }
  
  int value;
};

int main() {
  sol::state lua;
  lua.open_libraries();
  
  lua.new_usertype<S>("S",
    "value", sol::property(&S::get, &S::set)
  );
  
  return 0;
}
```

When I try to compile the code I get an error:
```
main.cpp:24:14: error: no matching function for call to 'property'
    "value", sol::property(&S::get, &S::set)
             ^~~~~~~~~~~~~
./sol.hpp:8428:24: note: candidate template ignored: couldn't infer template argument 'F'
        inline decltype(auto) property(F&& f, G&& g) {
                              ^
./sol.hpp:8435:24: note: candidate function template not viable: requires single argument 'f', but 2
      arguments were provided
        inline decltype(auto) property(F&& f) {
```

Is there a way to tell sol to bind the non-const getter and ignore the const one?

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/resolve.html

**Comment by joe-92** [comment]
Sorry, my fault... Thank you!

**Comment by ThePhD** [comment]
Oh, it's fine. I don't mean to be mean or anything: I just was tired and posted that before passing out for a nap, aha.

Best of luck to you! I hope your project goes well.

**Comment by joe-92** [comment]
No problem, I haven't understood it as mean :)
Thank you for your great library and the support. I have another problem (probably not a bug, but I don't get it working), should I open another issue or is there a better way to communicate?

**Comment by ThePhD** [comment]
File an issue or drop a message in the gitter and somebody will get back to you as soon as they feel like it.
