### ISSUE TITLE
Compilation errors with g++ 5.3.0

### ISSUE THREAD

**Issue by halcyonx** [ThePhD/sol2#485]
Hi, everyone! I've tried to compile simple program from "Sneak Peek" section and I got errors,
I've tried with -std=c++14 and -std=c++1z output is same:
https://pastebin.com/X5Ns8LU3
g++.exe (GCC) 5.3.0

In MSVC 2015 Community compilation has been successfully finished.

**Comment by ThePhD** [comment]
Not sure why this is happening. We include the necessary `<cctype>` header. Compilatino also succeeds on MinGW 6 and 7 and 5, so many this is a 5.3=specific bug...

**Comment by ThePhD** [comment]
Turns out MinGW doesn't like `strerror_s` since it's considered "optional" as part of the C11 standard. So they don't implement it sometimes.

It also doesn't have `strerror_r`. Which is really, really bad. Either way, I'm re-implementing it...

**Comment by ThePhD** [comment]
Should be fine now. Tagged up and ready to go: https://github.com/ThePhD/sol2/releases/tag/v2.18.0

**Comment by halcyonx** [comment]
Now error message is:
```
In file included from test_sol_binding.cpp:1:0:
sol.hpp: In function 'int strerror_r(int, char*, size_t)':
sol.hpp:2006:33: error: 'sys_nerr' was not declared in this scope
  if ((errnum < 0) || (errnum >= sys_nerr)) {
                                 ^
```

**Comment by halcyonx** [comment]
It seems strange, but I downloaded lua library version 5.2.4 and example was compiled successfully, previous version was 5.1.5

**Comment by ThePhD** [comment]
5.1.5 is where this error manifests because we have to write a compatibility shim for it. If you use 5.2.4 or 5.3.4 or even LuaJIT, this wouldn't be a problem per say.

`sys_nerr` is SUPPOSED to be defined by MinGW...

**Comment by ThePhD** [comment]
Give it another whirl: https://github.com/ThePhD/sol2/releases/tag/v2.18.0
