### ISSUE TITLE
Compilation issue for android

### ISSUE THREAD

**Issue by halcyonx** [ThePhD/sol2#488]
Hi, everyone! I've decided to use sol2 in my project and I tried to build my project based on cocos2dx for android platform. But there is compilation errors: https://pastebin.com/9pqRA26N
1. Android ndk version: android-ndk-r12b 
2. Android clang version 3.8.256229  (based on LLVM 3.8.256229)

In Application.mk I added APP_CPPFLAGS := -frtti -std=c++14 -fsigned-char
How can I solve this problem?

**Comment by ThePhD** [comment]
Thanks for reporting. Looks like Android's once again not a fan of putting its math and other c-like functions into the C++ `std` namespace when defined from C++. I'll have to just get rid of `std::` in front of math functions like `llround`, and then update it so everyone can use it.

Give me a moment...

**Comment by ThePhD** [comment]
Fixed. Look to 2.18.1 soon.
