### ISSUE TITLE
De-allocation crash after upgrading to 2.18.0

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#489]
Up until recently I was using sol 2.17.1 (with C++-compiled Lua 5.3), and today I decided to upgrade to 2.18.0.

Without any changes to my code, my application now crashes when sol2 tries to destroy a usertype. The code that crashes is the following:
```cpp
template <typename T>
inline int usertype_alloc_destroy(lua_State* L) {
	void* rawdata = lua_touserdata(L, 1);
	T** pdata = static_cast<T**>(rawdata);
	T* data = *pdata;
	std::allocator<T> alloc{};
	alloc.destroy(data); // <-- crashes here with read access violation
	return 0;
}
```

Maybe it's my debugger tripping, but it looks like the `data` pointer points to invalid data.

**Comment by ThePhD** [comment]
There's been a few cases of double-delete that popped up recently. I solved it on one instance but I still need to look more closely at what's going on.

**Comment by eliasdaler** [comment]
Possible repro;

```c++
#include <sol.hpp>

#include <iostream>

class Entity {
public:
    ~Entity() { std::cout << "WHAT" << std::endl; }
};

int main()
{
    sol::state lua;
    lua.open_libraries();
    lua.new_simple_usertype<Entity>("Entity");
    sol::function test = lua.do_string(R"(
return function(e)
end
)");

    {
        Entity e;
        test(e); // same with std::ref(e)!

        lua.collect_garbage(); // destroys e for some reason
    }

    system("pause");
}```

**Comment by ThePhD** [comment]
Reference tables were being given the regular metatable (that is, one without the `*` in its name) and then calling the destructor on honest, hardworking usertypes. It seemed to only affect things in the `simple_usertype` case, at least here.

It's fixed and I need to push a new release since this is a back-breaking bug.

**Comment by ThePhD** [comment]
Fixed.
