### ISSUE TITLE
A small warning with -Wall

### ISSUE THREAD

**Issue by victorlevasseur** [ThePhD/sol2#49]
Hi,

There's a small warning with sol 2.3 (not the case with 2.1) when building my project : 
```
protected_function.hpp:86:14: warning: unused variable ‘handlerpushed’ [-Wunused-variable]
         bool handlerpushed = error_handler.valid();
```

It seems that this boolean is never used again. Don't know if this line can be removed or not (that's why I did make a PR).

**Comment by ThePhD** [comment]
You're right: it can be removed. My mistake: I had chopped its use during a fixing / refactoring, and forgot to update!

Thanks for catching that out: surprised the tests didn't see this one...

**Comment by ThePhD** [comment]
Will push a fix in a li'l bit....

**Comment by victorlevasseur** [comment]
Nice. :+1: Meanwhile, I removed the line from the sol header in my project and everything is all right.

**Comment by ThePhD** [comment]
What's bizarre, though, is that `-Wall` `-pedantic` is used in tests. Are you sure the warning doesn't come from `-Wpedantic`?

**Comment by victorlevasseur** [comment]
I don't use -pedantic, just -Wall.

**Comment by ThePhD** [comment]
Strange. Well, either way, it works [now](https://travis-ci.org/ThePhD/sol2/builds/120276326). Feel free to pull from latest. I'll put up a 2.3.1 later on, after a few more fixes get pushed.
