### ISSUE TITLE
Segmentation fault when calling binary operator with incompatible right argument

### ISSUE THREAD

**Issue by TheLartians** [ThePhD/sol2#494]
When performing a binary operation such as addition or multiplication on a usertype I get a segmentation fault when the right argument has the wrong type.

For example, while `Test.new(1)+Test.new(2)` works, `Test.new(1)+x` will crash, when `x` is anything other than a `Test` object. I feel this should rather raise a Lua runtime error.

Full example:

```
#include <sol.hpp>
#include <iostream>

struct Test{
  int value;
  Test(int v):value(v){}
  Test operator+(const Test &rhs)const{ return Test(value + rhs.value); }
};

std::ostream &operator<<(std::ostream &stream,const Test &test){
  return stream << test.value;
}

int main(){
  sol::state lua;
  lua.open_libraries();
  
  lua.new_usertype<Test>("Test",
                         sol::constructors<Test(int)>(),
                         sol::meta_function::addition,&Test::operator+);
  try{
    lua.script("print(Test.new(1)+Test.new(2))", &sol::script_default_on_error); // works
    lua.script("print(Test.new(1)+2)", &sol::script_default_on_error); // boom
  }
  catch(sol::error error){
    std::cout << error.what() << std::endl;
  }

  return 0;
}
```

Crashes on the sol2 development branch as well as the latest release (v2.18.1). My Lua version is 5.3.4. Compiled with clang on MacOS 10.12.6.

**Comment by ThePhD** [comment]
Add `#define SOL_CHECK_ARGUMENTS 1` to the top of that.

**Comment by ThePhD** [comment]
Or, use `SOL_SAFE_USERTYPES`, if you want something less heavy. See: http://sol2.readthedocs.io/en/latest/safety.html

Best of luck!

**Comment by TheLartians** [comment]
Thanks, that fixed it! I see I should have read the special_functions example more carefully. Thanks for clarifying.

**Comment by ThePhD** [comment]
Oh, also, if you don't want the safety but still want to turn it on in select scenarios, please see: http://sol2.readthedocs.io/en/latest/api/protect.html
