### ISSUE TITLE
Usertype "manual" properties registering?

### ISSUE THREAD

**Issue by an0nym0us69** [ThePhD/sol2#496]
hello, 
i've been getting "compiler is out of heap space" error when using new_usertype (due to having so much properties inside 1 class), i tried new_simple_usertype too.. same thing, and no, splitting files doesn't really fix it cause it was caused by 1 usertype which had a big size..
what i decided to do is the following, but i had an issue with properties, it was returning functions instead of values : 

```cpp
State.new_usertype<Object>("Object");
State["Object"]["__tostring"] = &Object::ToString; //works fine
State["Object"]["health"] = sol::readonly_property(&Object::GetHealth); //it gives me a function when i try to do object.health instead of a lua number :/
```

is there a solution for avoiding the memory heap error/adding properties properly ? (i tried x64 tooltip thing, it didn't help cause the max i can have is 4gb ram anyways..)

**Comment by mrgreywater** [comment]
You need to use simple_usertype to add properties at runtime. https://github.com/ThePhD/sol2/blob/develop/examples/usertype_simple.cpp

**Comment by an0nym0us69** [comment]
okay thanks, create_simple_usertype is what i was looking for..
