### ISSUE TITLE
how to retrieve Lua bool from script?

### ISSUE THREAD

**Issue by Spacechild1** [ThePhD/sol2#499]
First I'd to thank you for this wonderful library!

I've run into problems when trying to work with Lua booleans.
let's say I have a lua table like 

`data = {state=false}`

now I'm trying to get this boolean value in C++ but none of the methods work. I might be wrong but it seems to me that the "bool" typecast only checks if the object is not nil.
so writing things like this doesn't work:

`bool state = mysolstate["data"]["state"]`

the outcome will always be true (because it's not nil)

then I thought this could work:

`int state = mysolstate["data"]["state"]`

but all lua booleans are apparently converted to int=0...
the only workaround I found so far is to use '1' and '0' instead of 'true' and 'false' in my Lua scripts, get them as ints in C++ and then cast to a bool.

is there any way to work with Lua booleans?

thanks a lot!

**Comment by squeek502** [comment]
Take a look a the [reading variables](sol2.readthedocs.io/en/latest/tutorial/variables.html#reading) docs, in particular the *safe lookup* and *optional lookup* sections. Simple examples of each:

```
auto state = mysolstate["data"]["state"];
bool stateExists = state.valid();
if (stateExists)
    bool stateValue = state.get<bool>();
```

```
sol::optional<bool> state = mysolstate["data"]["state"];
bool stateExists = (bool)state; // sol::optional cast to a boolean gives whether or not the variable exists
if (stateExists)
    bool stateValue = state.value();
```

**Comment by Spacechild1** [comment]
unfortunately this doesn't work either... "stateValue" will return true for both `true `and `false`.
looks like `get<bool>() ` and implicit typecasts to `bool` always return false for `nil `and true for non-`nil ` Lua values...

is there a way to explicitly get lua boolean values?

**Comment by squeek502** [comment]
These test cases work fine for me:

```c++
#define SOL_CHECK_ARGUMENTS
#include <catch.hpp>
#include <sol.hpp>

TEST_CASE("getting a bool value")
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	sol::optional<bool> before = lua["data"]["state"];
	bool beforeExits = (bool)before;
	REQUIRE(beforeExits == false);

	auto beforeAuto = lua["data"]["state"];
	bool beforeAutoExists = beforeAuto.valid();
	REQUIRE(beforeAutoExists == false);

	lua.do_string("data = {state=false}");

	sol::optional<bool> after = lua["data"]["state"];
	bool afterExists = (bool)after;
	REQUIRE(afterExists == true);
	REQUIRE(after.value() == false);

	auto afterAuto = lua["data"]["state"];
	bool afterAutoExists = afterAuto.valid();
	REQUIRE(afterAutoExists == true);
	REQUIRE(afterAuto.get<bool>() == false);

	bool directAfter = lua["data"]["state"];
	REQUIRE(directAfter == false);
}
```

**Comment by Spacechild1** [comment]
man, I'm so sorry... it was a stupid error in my Lua script... thanks a lot, though! you're examples work perfectly!
