### ISSUE TITLE
Android NDK does not know about std::to_string

### ISSUE THREAD

**Issue by halcyonx** [ThePhD/sol2#500]
Dont know how to write personal message here. Notice in sol 2.18.1 in template function: 
`template <typename T>
		inline int adl_default_to_string(std::true_type, lua_State* L) {
			using std::to_string;`
Android NDK throw an error, it does not know about std::to_string. I've fixed it manually in sol.hpp. 
Can be closed.

**Comment by ThePhD** [comment]
Fixed in latest.
