### ISSUE TITLE
How to get name of lua object

### ISSUE THREAD

**Issue by igorkrpanic** [ThePhD/sol2#504]
Is there a simpler way of getting name of sol::object created in lua script?
For now I am using function below but I would expect to have something like get_name member in sol::object
```cpp
std::string get_name( const sol::object& t )
{
    const sol::table& globals = sol::state_view( t.lua_state() )["_G"];
    for (auto& i : globals)
    {
        if (i.second == t)
            return i.first.as<std::string>();
    }
    return "";
} 
```

**Comment by ThePhD** [comment]
There is not. That object can also have multiple names:

````
a = some_type.new()
b = a
c = a
pick_one = c
````

Finding "the name" is borderline impossible. If you need the name of all objects in a particularly environment, you've probably got some strange design somewhere. If you know the name ahead of time, you should save the name and then use that to reference/query into the environment.

Finally, you can get the global table with `sol::global_table g = sol::state_view( t.lua_state() ).globals();`, I believe.

**Comment by mrgreywater** [comment]
@ThePhD I think this is more of a question to get some kind of general type information, not necessarily the lua 'path' to the type. Similar to my __type request in the chat.
