### ISSUE TITLE
__type table

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#506]
Users in the past have requested that they be able to check if one type is the same as another: #356 

Lately, users have also been requesting the ability to get the name of a type, such as @mrgreywater in the Gitter. It's a request that's popped up here and there, so I'm going to commit to adding such a thing. I want to make it a table, with the following entries:

````
__type.is ( obj ) -- function that tells you whether an object is of a certain type
__type.name -- string that has the C++ type name, or what we can get to the best of our ability
````

Anything else that should be included? I think that's just about all that's relevant, really. `__type` should be available on the metatable you register only, but not the object itself as far as I understand.

Thoughts?

**Comment by squeek502** [comment]
Seems good to me. Just to clarify, would this only be available on the usertype table, not on instances of the usertype? For example, if `Thing` is a bound usertype:

```lua
local inst = Thing.new()

print(Thing.__type.name) -- prints `Thing`
print(inst.__type.name) -- error, attempting to index nil?
```

If so, then I think naming the function `is` might not be ideal (it doesn't make as much intuitive sense to me asking `Class is instance?` rather than `instance is Class?`), but that's a pretty minor thing.

**Comment by mrgreywater** [comment]
To stay compatible with other lua extensions, __type should be a metamethod that returns the type string. One could make it optional if it either returns the name with which the type was registered, or the demangled c++ type name.
Another nice thing to have would be having a way to get the function signature(s) for usertype methods, so you can figure out how to call a certain function just from the lua side.
Having __type.is is not really necessary I think, but having a function from c++ to get the type name, which can be bound to lua if a user wants to would be nice.

**Comment by mrgreywater** [comment]
I think there are three use cases for type info:
1) People who want to do type checks in lua
2) People who want runtime information for debug and documentation reasons
3) Informational error messages.
If you don't add usertype_name in c++, then people will add their own implementations, which might be worse than what you can come up with (see the recent issue with the globals table iteration approach)
As for not conforming to other extensions, then at least don't use __type and completely break them by using the same key, but supplying an incompatible table. even though I don't understand why you need to do it differently when this approach (__type string metafield) has been around since lua 5.0 with luaSub and works fine.

**Comment by ThePhD** [comment]
The recent issue was about finding the name of some object that exists in a table (particularly, the global environment), not getting its bound usertype name.

I'll keep `__type` for a string name, and `__typeinfo` for sol2's purposes. This should keep back compatibiltiy maximal but also give me the flexibility to implement the things I need.

Current implementation does not allow me to fulfill all the current requests, and it's likely something I won't be able to overcome unless I don't mind having `obj.__type` be a valid accessor (`obj` being an instance of some type `T`):

````
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<my_thing>("my_thing");
	lua.safe_script("obj = my_thing.new()");

	// works
	lua.safe_script("assert(my_thing.__type.is(obj))");
	lua.safe_script("assert(not my_thing.__type.is(1))");
	lua.safe_script("assert(not my_thing.__type.is(\"not a thing\"))");
	lua.safe_script("print(my_thing.__type.name)");

	// works
	lua.safe_script("assert(getmetatable(my_thing).__type.is(obj))");
	lua.safe_script("assert(not getmetatable(my_thing).__type.is(1))");
	lua.safe_script("assert(not getmetatable(my_thing).__type.is(\"not a thing\"))");
	lua.safe_script("print(getmetatable(my_thing).__type.name)");

	// crash, attempt to index nil
	lua.safe_script("assert(getmetatable(obj).__type.is(obj))");
	lua.safe_script("assert(not getmetatable(obj).__type.is(1))");
	lua.safe_script("assert(not getmetatable(obj).__type.is(\"not a thing\"))");
	lua.safe_script("print(getmetatable(obj).__type.name)");
````

**Comment by ThePhD** [comment]
`sol::lib::extensions` might make for a good top-level library name to put things like `sol.is` and `sol.type_name` into.

**Comment by ThePhD** [comment]
Fun stuff: a survey of libraries using the following displayed that these were already in use.

- `__NAME`
- `usertype(obj)`
- `type(obj).name`
- `__type` (as a function or string)
- `__typeinfo`

It also gets better because almost none of them agree where the type name should actually go. Some have it on the metatable, but others have these as fields directly on the class (and inaccessible from the metatable). One person mentioned getting the metatable and then sweeping the Lua registery for a match, so they could check the name value in the registry (offensively slow, but they cached lookups).

I'm not sure where to put any of this type information for it to play nice. I also don't know which libraries do what: kaguya doesn't seem to make this information available immdeiately, neither does luwra. luabind apparently has `__type`, but a lot of that is hidden in its private details? I haven't been able to check OOLua or others yet.

There's also still my worry that people will start using `__type.name` or `__type` or whatever to do class checks in Lua, and that just smacks of bad design...

**Comment by daurnimator** [comment]
/me comes in without reading whole issue:

How are you currently using `__name`? It's the official lua field for naming a type. It gets used in various places by lua (e.g. argument checking error messages)

**Comment by ThePhD** [comment]
I don't, at all (none of sol2's code is Lua code: I don't have to read `__name` or `__type` or anything: I just serve up the C++ name directly to the user when I need to present an error).

**Comment by daurnimator** [comment]
> I don't, at all (none of sol2's code is Lua code: I don't have to read __name or __type or anything: I just serve up the C++ name directly to the user when I need to present an error).

You don't control all error messages. e.g. see how `__name` is used internally by lua to present this error message:

```
$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> some_foo = setmetatable({}, {__name="foo"})
> io.open(some_foo)
stdin:1: bad argument #1 to 'open' (string expected, got foo)
stack traceback:
	[C]: in function 'io.open'
	stdin:1: in main chunk
	[C]: in ?
```

**Comment by ThePhD** [comment]
That's good to know, but I was under the impression that `luaL_newmetatable` already supplied this (the metatable name, which has some sol-specific prefix + the class name, has shown up in people's error messages before). The manual says it does, but even then the `__name` of the metatable is not identical to the class name (which is what people are asking for) and a bunch of other information people want to shove into this type identification table.

**Comment by daurnimator** [comment]
> That's good to know, but I was under the impression that luaL_newmetatable already supplied this (the metatable name, which has some sol-specific prefix + the class name, has shown up in people's error messages before)

Yes it does.

> even then the __name of the metatable is not identical to the class name (which is what people are asking for)

In that case you need some sol-specific location.

> and a bunch of other information people want to shove into this type identification table.

Can they put the existing `__name` field in such a thing?

However, reading your issue first post, if you're trying to identify types, then you need to do it based on the metatable itself, not by the contents of them.
Simplest way to do this is a (weak) table in the registry that maps from metatable to your chosen name/id/unique something.

**Comment by ThePhD** [comment]
From the gitter:

* type name
* type id
* base classes
* property/method names
* property types, method signatures with return type (including overloads), constructor signatures

It was also stated they want this on all functions bound from sol, and all enumerations created. I was thinking I might not just have the `__type` field, but also have something special for tables (enums) and functions. I think for tables we can just go the metatable route with `__type`, but for functions bound from C++ I think it would be best to store the data in some predefined upvalue.

Problem: the way functions are bound in C++ are heavily complicated. We already reserve the 1st upvalue for `set_environment`, since this function gets and sets the first upvalue of userdata, functions, etc. to match the environment specification (Lua 5.1, we just use `set_fenv` and friends).

We could reserve the 2nd upvalue for a table that describes type information for the function, and then store other information the typical reference storage and function pointers in the other upvalues like before. But this makes things difficult when someone wants to do something like `f = my_user_type.some_function`, where the upvalue on `f` would contain the information. When variables are bound to a usertype, we have to use `__index` to retrieve the name `some_function`, which means we'd have to create and push a type table every single time someone queries the function (a real hassle and performance hit).

All in all, I think I might actually put this feature request on ice until later. So far the only scenario for all this information presented to me has been automatic documentation generation or error reporting for bad function calls, but I've already added error reporters for bad function calls that report the desired function signatures to users and the `__name` bit is already taken care of.

I'm not sure automatic documentation is something I want to commit to supporting, especially if it comes in the form of a complete reflection engine.... for now, I'm going to leave the `__type` table as it is now, and put this feature request on ice.
