### ISSUE TITLE
Compile-Time Overloaded Functions

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#51]
`sol::c_call<typename F, F fx>`
Overloaded version?
`sol::c_overload<typename... F>::call<F... fxs>`

Eww.

**Comment by ThePhD** [comment]
Might want to wait for James Touton's `template <auto F>` before we commit to this travesty.

**Comment by nabijaczleweli** [comment]
>pretty much feature complete

**Comment by ThePhD** [comment]
Notice the Bike.Shed tag.
