### ISSUE TITLE
Compilation error with XCode 9.0

### ISSUE THREAD

**Issue by jeychenne** [ThePhD/sol2#510]
I'm trying to compile an app that uses sol on macOS Sierra with XCode 9.0, but I get the following error:

```
../dolmen/extra/sol.hpp:7197:58: error: expected unqualified-id
                        if (t == type::table || t == type::none || t == type::nil) {
                                                                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
      #define nil nullptr
                  ^
```

**Comment by milleniumbug** [comment]
Wow, that's some non-hygenic macro defined by Apple. Shame! Generally once a macro collision occurs, everyone loses. 

In case you don't actually use `nil` in the meaning defined by Objective-C, you can work around it by doing `#undef nil` before including any of the Sol2 headers.

**Comment by ThePhD** [comment]
No longer a problem: https://github.com/ThePhD/sol2/releases/tag/v2.18.3

**Comment by jeychenne** [comment]
Thanks to both of you. I tried downloading the latest version but the problem is still there. Applying the fix suggested by @milleniumbug does work though.

**Comment by Rapptz** [comment]
Are you aware that changing it from `nil` to `lua_nil` is effectively a breaking change? lol

**Comment by ThePhD** [comment]
@jeychenne What's the errors you're getting (perhaps you have a full build log you can paste directly here, in a pastebin, or a gist)?

@Rapptz: There's still an alias to `nil = lua_nil` in the enum definition, if we detect we're not on Objective-C/C++ (where `nil` is a keyword). I'll also add the macro guards to be extra safe.

**Comment by Rapptz** [comment]
Ah alright. I missed the alias.

**Comment by jeychenne** [comment]
@ThePhD Here is the error:

```
../dolmen/extra/sol.hpp:4521:14: error: expected unqualified-id
        const nil_t nil{};
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
      #define nil nullptr
                  ^
In file included from ../dolmen/main.cpp:11:
In file included from ../dolmen/DolmenApp.h:43:
In file included from ../dolmen/lib/Project.h:46:
In file included from ../dolmen/runtime/scripting.h:8:
../dolmen/extra/sol.hpp:4925:3: error: expected identifier
                nil = lua_nil,
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
      #define nil nullptr
                  ^
```

**Comment by ThePhD** [comment]
This might be fixed now, but I don't have a Mac with an OSX SDK on it to test for sure. Still, I vetted the entire framework for uses of `nil` and it should be all cleared now.

Try latest or get it from here again: https://github.com/ThePhD/sol2/releases/tag/v2.18.3

**Comment by jeychenne** [comment]
Thanks again. I don't have my mac handy but I'll try on Monday and will let you know...

**Comment by jeychenne** [comment]
I was able to take a look at it and I can confirm that the latest version works without any problem. Thanks again for the quick fix!

**Comment by ThePhD** [comment]
Great! Good luck out there.
