### ISSUE TITLE
Help to understand: Singleton to usertype?

### ISSUE THREAD

**Issue by terminar** [ThePhD/sol2#519]
Hi, 
I'm trying to understand how I can map a singleton class with private constructor and public ::getInstance() to a sol2 usertype, but I haven't found a similar example or something in the documentation yet.

Example
=======

c++-side:
----------
[...]
```
std::shared_ptr<SomeLib> SomeLib::getInstance() {
  static std::weak_ptr<SomeLib> instance;
  static std::mutex m;

  m.lock();
  auto ret = instance.lock();
  if (!ret) {
    ret.reset(new SomeLib());
    instance = ret;
  }
  m.unlock();

  return ret;
}
```
----
Hoping to get something like this on the Lua side:
```
local sli = SomeLib.getInstance()
sli:doSomething()
```
----
Also, the returned initialised class shouldn't be destroyed by Lua (talking about garbage collection/ownership).
Is there some magic stuff I can use with Sol2?

Thanks (and Kudos for the great work on Sol2!)
Björn

**Comment by ThePhD** [comment]
The closest example there is is: https://github.com/ThePhD/sol2/blob/develop/examples/usertype_initializers.cpp

But it still ends up destructing/constructing the memory, just with hidden constructors. A more accurate "singleton" example:

````
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

#include <iostream>

#include <memory>
#include <mutex>

struct SomeLib {
private:
	SomeLib() {}
public:
	static std::shared_ptr<SomeLib> getInstance();

	int doSomething() const {
		return 20;
	}

	// destructor must be public to work with 
	// std::shared_ptr and friends
	// if you need it to be private, you must implement
	// a custom deleter with access to the private members
	// (e.g., a deleter struct defined in this class)
	~SomeLib() {}
};

std::shared_ptr<SomeLib> SomeLib::getInstance() {
	static std::weak_ptr<SomeLib> instance;
	static std::mutex m;

	m.lock();
	auto ret = instance.lock();
	if (!ret) {
		ret.reset(new SomeLib());
		instance = ret;
	}
	m.unlock();

	return ret;
}

int main(int, char*[]) {
	std::cout << "=== singleton example ===" << std::endl;

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<SomeLib>("SomeLib",
		"new", sol::no_constructor,
		"getInstance", &SomeLib::getInstance,
		"doSomething", &SomeLib::doSomething
		);

	lua.script(R"(
-- note we use the `.` here, not `:` (there's no self to access)
local sli = SomeLib.getInstance()
local value = sli:doSomething()
print('sli:doSomething() returned:', value)
assert(value == 20)
)");

	std::cout << std::endl;
	return 0;
}
````

As a side note, if you don't want Lua to destroy your memory when GC is called (even when the public constructor is publicly available), you can simply pass in a `std::ref( obj );` or a `&obj` pointer (more formally a `std::addressof(obj);`, since some types can override the `&` operator).

I'll likely add this as an example to make things easier for people.

**Comment by ThePhD** [comment]
Note that it's imperative for sol2 not to generate a constructor for you the tag "no_constructor" must be used. This is described in the usertype constructor documentation: http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-constructor-options

Finally, the example is live: https://github.com/ThePhD/sol2/blob/develop/examples/singleton.cpp"

Best of luck. Let me know if you make anything cool or have any suggestions for the examples.
