### ISSUE TITLE
Help getting C++ exceptions out of Lua functions defined in C++

### ISSUE THREAD

**Issue by G1itcher** [ThePhD/sol2#522]
In this example:

```
#include <sol/sol.hpp>

class MyException : public std::runtime_error
{
public:
	explicit MyException(std::string someInfo) :
	runtime_error{"MySpecialExceptionHappened"},
	m_someInfo { someInfo }
	{
	}
	
	std::string m_someInfo;
};

int main()
{
	sol::state luaState;
	luaState.set_function("someFunction", []{
		//Do a bunch of stuff
		throw MyException{ "It's All gone wrong, do something in C++ to remedy this!" };
	});

	sol::function luaFunc = luaState["someFunction"];

	try
	{
		luaFunc();
	}
	catch(const MyException& e)
	{
		//Can't get here
	}
}
```

How do I catch C++ exceptions thrown from within a Lua function? It seems that sol grabs them all and I lose important info as a result. I did take a look at #define SOL_EXCEPTIONS_SAFE_PROPAGATION but I'm not sure that's what I'm after.

**Comment by G1itcher** [comment]
Side stepped issue by not extending from std::exception.

**Comment by ThePhD** [comment]
I suppose with safe exception propogation, I don't have to catch errors.

If you're doing this on the wrong platforms, however, you're essentially destroying your stack and probably introduced a dozen bugs on the process. ... Not to mention that having an exception that isn't derived from `std::exception` is probably also a bad idea.

**Comment by ThePhD** [comment]
I made a push to the repository that might help you. Here's the things you'll need to do / verify to make your codebase to behave properly without bugs:

1. Compile Lua as C++. This will enable you to safely throw exceptions through Lua functions without absolutely destroying the VM or violating the C++ boundaries
2. Define `SOL_USING_CXX_LUA`
3. This will automatically turn on `SOL_EXCEPTIONS_SAFE_PROPOGATION`

You should be able to get your behavior then, with or without protected functions, not have the bad code smell of not deriving from `std::exception`, and be good to go.

Best of luck.

**Comment by G1itcher** [comment]
That is excellent, thank you very much!

**Comment by G1itcher** [comment]
To confirm, to use this, I need to implement luaJIT right?

**Comment by ThePhD** [comment]
No. You can compile Lua 5.3.4 as C++, but you need to compile Lua yourself manually.

LuaJIT is still compiled as C code, but depending on which platform you build it for comes with full exception interop: http://luajit.org/extensions.html#exceptions

**Comment by G1itcher** [comment]
Ah I see. Many thanks for getting back to me!

**Comment by ThePhD** [comment]
Part of the latest release: https://github.com/ThePhD/sol2/releases/tag/v2.18.5
