### ISSUE TITLE
lua_newthread can't work 

### ISSUE THREAD

**Issue by tmothupr** [ThePhD/sol2#524]
I want to run script in independent stack but have some shared global things, so use lua_newthread to create one, but sol::state_view seems only throw things on main lua state. Isn't it the right way to do it?
My sol version only use c++14.

#include <cassert>
#include<iostream>
#include "sol.hpp"

int main(int, char*[]) {
	 
	sol::state lua;
	lua.open_libraries();
	auto L = lua_newthread(lua.lua_state());
	 sol::state_view runner_thread_state = L; // runner_thread.state();
	runner_thread_state.do_string("function fun() print('fuck') end");
	runner_thread_state["fun"]();
	try
	{
		lua["fun"]();
	}
	catch (std::exception const& e)
	{
		std::cerr << e.what() << std::endl;
	}
	return 0;
}

**Comment by ThePhD** [comment]
`lua_newthread` pushes a new thread onto the stack. If you want something that is managed, you should be using `sol::thread`, and its creation utility `sol::thread::create`. Then, you can get the state for that thread with `runner_thread.state();`

Finally, Lua threads do not guarantee atomicity. Nor does it guarantee that the operations won't hit a common place in Lua -- e.g., the global table. You can of course get away with maybe having a separate stack, but unless you understand the stack and how to use it you'll likely do something wrong. I wouldn't recommend it, to be perfectly honest. What Lua considers a "thread" and what C++ considers a "thread", and what the two consider "thread local", don't seem to be the same thing.

**Comment by tmothupr** [comment]
Hi !!!
I'm using an older version of sol2, which only use C++14. The lua5.1.lib
and lua5.1.dll which are download from somewhere can be successfully
integrated into my project.
But when I compiled lua5.3.lib and lua5.3.dll. by myself, and replaced the
5.1, linking error appeared !!!
[>lua53.lib(lapi.obj) : error LNK2005: _lua_absindex  has been ......]



2017-10-25 20:54 GMT+08:00 The Phantom Derpstorm <notifications@github.com>:

**Comment by ThePhD** [comment]
@tmothupr When you bring in a new lua DLL and Library you MUST also change the headers you build against. Please use the Lua 5.3 header files and properly add them as your include flags to the Visual Studio project.

Also, it would be best to open new issues, rather than commented on unrelated old ones.
