### ISSUE TITLE
Help on  <unresolved overloaded function type>

### ISSUE THREAD

**Issue by terminar** [ThePhD/sol2#526]
Hi,

still trying to get into sol2 (and sailing around some template problems), but the existing examples are very helpful!

Today another request for a tipp, I was diving into <unresolved overloaded function type> problems at several tests with our code when C++ can't resolve methods.

A noncomplete example class which should explain the problem:

```
class User : public BaseEntity {
 public:
  static std::shared_ptr<User> CreateUser();
  static std::shared_ptr<User> CreateUser(const std::list<std::string>& attrNameList);
  static std::shared_ptr<User> CreateUserAsCopy(const BaseEntity& srcUser);
}
```
When I try to 
```
  lua.new_usertype<User>("User",
                                 "new",sol::no_constructor,
                                 "CreateUser", &User::CreateUser
);
```
to wrap only one (!) of the methods, I get horrible template errors. I tried to help the compiler with something like
```
( std::shared_ptr<User>(User::*)()) &User::CreateUser
```
but that only got me to new problems and error messages. 

Is there a "correct" or easy way to resolve such problems when the compiler can't resolve the overloaded methods?

Bye
Björn

PS: Yes, I'll give you feedback when creating something interesting, currently, I am trying to get around some problems with templates, threads, listener callback methods, ...

**Comment by ThePhD** [comment]
sol2 includes a utility to help:

http://sol2.readthedocs.io/en/latest/api/resolve.html

When working with threads, please be sure to know that Lua is a single-threaded, zero-atomicity, no-concurrency runtime. You must high-level lock **every single operation** performed against the state (everything you do with Lua must be locked).

You can get around this problem by not sharing states between threads. If you need information to flow between the two, serialize a value and transport that value to the new thread, then push it into the new Lua state to avoid problems. And no, you can't share Lua values/references between 2 different states.

**Comment by terminar** [comment]
resolve<> seems to work, thank you for the info.

Regarding threads: yes, I know the plain C Lua API and the main "problem" with threads on Lua, but I haven't found the "perfect" solution with Sol2 for our code yet, but that's just more homework ;).
