### ISSUE TITLE
Is it possible to compile latest version with c++11?

### ISSUE THREAD

**Issue by guijun** [ThePhD/sol2#534]
Is it possible to compile latest version with c++11?
If not, please let me know which version should I use.
thanks alot.

**Comment by ThePhD** [comment]
No, sol2 is a C++14 and above library. The compiler flag required is `std=c++1y`, `std=c++14`, or some equivalent or better standard provided by your compiler.

I did not keep track of the last C++11 release. It was... a **long** time ago. However, compilers all the way back to GCC 4.9.x (GCC 4.8.x might have some bad enough compiler bugs to choke in places) will give you what you need, if you have control over the compiler flag.

I would recommend moving to C++14. It was considered a "bugfix" release of C++11... and indeed, it fixed a lot of missing things that we had to write polyfill/patches for in sol2. Your best bet would be looking to nearly the start of this repo, over... 2 years ago? You'll be missing a lot of features.

**Comment by guijun** [comment]
I'm wondering if C++14 is fully available on ios and android ......

**Comment by ThePhD** [comment]
Yes and yes. People have built using XCode for iOS using sol2. They have also built for Android using various toolchains, but they are all backed by releatively recent versions of GCC, provided you didn't not pick up a distribution for 4 years ago.
