### ISSUE TITLE
Strange: Undefined symbols for architecture x86_64:   "luaL_error(lua_State*, char const*, ...)", referenced from:

### ISSUE THREAD

**Issue by guijun** [ThePhD/sol2#535]
Xcode 8.3.2
a Project with tolua++ libLua linked.
I tried to add sol.hpp and add some lines:
            sol::state lua;
                // open some common libraries
            lua.open_libraries(sol::lib::base, sol::lib::package);
                // go!
            lua.script( "print('bark bark bark!')" );

then build it and errors appears:

Undefined symbols for architecture x86_64:
  "luaL_error(lua_State*, char const*, ...)", referenced from:
      compat53L_checkstack_53(lua_State*, int, char const*) in libItems.a(MCLua.o)
  "luaL_unref(lua_State*, int, int)", referenced from:
      sol::basic_reference<false>::deref() const in libItems.a(MCLua.o)
  "lua_concat(lua_State*, int)", referenced from:
      compat53L_traceback(lua_State*, lua_State*, char const*, int) in libItems.a(MCLua.o)
      compat53_findfield(lua_State*, int, int) in libItems.a(MCLua.o)
  "lua_gettop(lua_State*)", referenced from:
      compat53L_traceback(lua_State*, lua_State*, char const*, int) in libItems.a(MCLua.o)
      compat53_pushglobalfuncname(lua_State*, lua_Debug*) in libItems.a(MCLua.o)
      compat53_absindex(lua_State*, int) in libItems.a(MCLua.o)
      sol::state_view::unsafe_script(sol::basic_string_view<char, std::__1::char_traits<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, sol::load_mode) in libItems.a(MCLua.o)

=============================

I double checked that my tolua++ bindings works with libLua.a linked correctly.

**Comment by ThePhD** [comment]
I was able to build and run a project using `toLua` on both Ubuntu and Windows, but I do not own a Mac. Therefore, I can only do my best guesses.

I would image something is going wrong with the linker, it's just a question of what, really. It sounds like you've already checked that `-llua` and all of that is set, I don't really have many other suggestions for you. I can only ask that your libLua for the right architecture (64-bit), so it syncs up properly. Also make sure that your build of Lua is done with a C compiler (and not C++), and builds as C (and not C++: if it's built as C++ the function names will be mangled differently, and for that sol2 requires `#define SOL_USING_CXX_LUA`).

**Comment by guijun** [comment]
Hi, thanks for feedback.
I added #ifdef __cplusplus extern "C" { for lua headers and it works.

**Comment by ThePhD** [comment]
The header `lua.hpp` is supposed to do that automatically for you: https://github.com/ThePhD/sol2/blob/develop/sol/compatibility/version.hpp#L27

It's the default include sol2 uses when pulling Lua code. You may want to make sure your lua.hpp looks like this: http://download.redis.io/redis-stable/deps/lua/etc/lua.hpp

**Comment by ThePhD** [comment]
But, patching it over works just as well.
