### ISSUE TITLE
new_experimental_usertype: combating compile time woes

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#538]
This is an issue for bikeshedding ideas about how to handle a new usertype that will likely be standardized in sol v3.

The biggest problem so far is that people bind 200+ member functions and variables to a class, all with different signatures, and then the compilation times go through the roof.

We need to isolate the compilation times into something much more manageable. This means getting rid of variadic templates in favor of something like `initializer_list`, even if it costs us a lot of performance.

Oh boy...

**Comment by mrgreywater** [comment]
Before starting with this, I think it would make sense to benchmark the compilation times. Even when creating a table and using lua.set_function with 200+ functions, it's taking quite a while to compile. Using initializer_list instead of variadic templates might decrease memory consumption while compiling, but I think it might make sense to do some profiling first.

**Comment by ThePhD** [comment]
There are no gains to be had with `set_function`. It takes one of the most direct paths to hitting the internal getters and setters it possibly can.: there's is little we can do to optimize its compilation pathway. `set` and `get` might be better because we can optimize single-key paths to not make tuples, but even that gain might not be all that worth it.

`new_usertype`, on the other hand, presents a myriad of problems. From having to spam out the function 2-5 times depending on whether or not the user specifies default constructibles, to performing many (one-time, linear, forward-only) traversals over the entire type list, to generating dozens of functions for just 1 very specific type, `new_usertype` has lots of intermediary garbage. Not to mention that most tuples are implemented recursively, and `new_usertype` makes a tuple the size * 2 the number of declarations.

Benchmarking will of course be fine, I'm sure, but I think I already know where to start.

**Comment by guijun** [comment]
I had spent a whole day for moving my binding from tolua++ to sol2, I found my xcode became very very lag and compile time is about 10 minutes with about 8G heap,so I have to abandon xcode for coding.
I had spent another whole day for moving my binding from sol2 to kaguya, compile time is about 2-3 seconds.

**Comment by ThePhD** [comment]
cf. #612
