### ISSUE TITLE
SOL_CHECK_ARGUMENTS - everywhere

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#54]
Currently, when someone gets a `sol::table` and such from the stack, we don't assert that it's actually a table on construction, even when `SOL_CHECK_ARGUMENTS` is specified. That should be fixed for all the `sol::reference` types, such as:

- [ ] `sol::table`
- [ ] `sol::userdata`
- [ ] `sol::light_userdata`
- [ ] `sol::function`
- [ ] `sol::protected_function`
- [ ] `sol::thread`
- [ ] `sol::coroutine` (is just a function)

**Comment by nabijaczleweli** [comment]
@ThePhD Put a space between `[]` to make a checkbox
