### ISSUE TITLE
sol::thread::status() returns incorrect value

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#541]
Function `thread::status` always returning `thread_status::dead` if thread was runned.
```cpp
sol::state lua;
lua.open_libraries(sol::lib::coroutine);
lua.script("function main() coroutine.yield() end");
sol::thread t = sol::thread::create(lua);
sol::coroutine cor = t.state()["main"];
cor();
assert(cor.status() == sol::call_status::yielded); // ok
assert(t.status() == sol::thread_status::yielded); // error
```
Without [this condition](https://github.com/ThePhD/sol2/blob/e17455f5b67a96f35920772f21773d43f3f7aa66/sol/thread.hpp#L175) the returning thread status is correct.

Lua 5.3, LuaJIT 2.0.5, VS2017, latest sol2.

**Comment by ThePhD** [comment]
Sounds about right. I'll take a look at the logic again. I'll probably just toss the condition out entirely or something.

**Comment by ThePhD** [comment]
It's fixed in the latest.
