### ISSUE TITLE
documentation: threading

### ISSUE THREAD

**Issue by maysl** [ThePhD/sol2#542]
The documentation states that 
> any access or any call on Lua affects the whole global state

But it also suggests to

> spawn mutliple Lua states for each thread

This is not entirely clear to me.
Is a `sol::state` as thread-safe as an `int` (meaning concurrent access to different `sol::state` objects is well-behaved)?
Or is a `sol::state` as thread-safe as an `int&` (meaning no guarantees whatsoever)?

Maybe you could update the docs accordingly. Thank you for this great library!

**Comment by ThePhD** [comment]
It should read "spawn a single Lua state and tie it to a single thread, and do not attempt to perform cross-access".

I'll update the docs.

**Comment by ThePhD** [comment]
Updated.

**Comment by maysl** [comment]
Thank you! Understood.

It may also be worth replacing the phrase
> affects the whole global state

with 
> affects the whole `sol::state`
