### ISSUE TITLE
SOL_CHECK_ARGUMENTS into smaller pieces

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#543]
It would be nice if `SOL_CHECK_ARGUMENTS` was chopped into smaller pieces that controlled different parts of the framework, so that safety for only some pieces could be turned on while others are left off to make it more suitable for release builds. Current ideas:

````
// Checks low-level getter function
// (and thusly, affects nearly entire framework)
#if !defined(SOL_SAFE_GETTER)
#define SOL_SAFE_GETTER 1
#endif

// Checks access on usertype functions 
// local my_obj = my_type.new()
// my_obj.my_member_function()
// -- bad syntax and crash
#if !defined(SOL_SAFE_USERTYPE)
#define SOL_SAFE_USERTYPE 1
#endif

// Checks sol::reference derived boundaries
// sol::function ref(L, 1);
// sol::userdata sref(L, 2);
#if !defined(SOL_SAFE_REFERENCES)
#define SOL_SAFE_REFERENCES 1
#endif

// Checks function parameters and 
// returns upon call into/from Lua
// local a = 1
// local b = "woof"
// my_c_function(a, b)
#if !defined(SOL_SAFE_FUNCTION_CALLS)
#define SOL_SAFE_FUNCTION_CALLS
#endif

// Checks conversions
// int v = lua["bark"];
// int v2 = my_sol_function();
#if !defined(SOL_SAFE_PROXIES)
#define SOL_SAFE_PROXIES 1
#endif
````

**Comment by OrfeasZ** [comment]
I support this!

**Comment by ThePhD** [comment]
Is there a set of these that should be automatically turned on for Release builds?

Or, should I just leave it so we default to having only certain ones on in Debug builds (`SOL_SAFE_USERTYPE` and `SOL_SAFE_REFERENCES` are the 2 I'm thinking about right now: the others have been known to stopgap people who already have large code bases and do some amount of type punning them tossing around usertypes).

**Comment by OrfeasZ** [comment]
Personally, I think by default the current behavior should be maintained, for backwards compatibility purposes, along with having `SOL_CHECK_ARGUMENTS` set all these to `1`. If some of them do not really change any behavior or performance characteristics while offering additional safety, it would be nice to have them on by default.

**Comment by ThePhD** [comment]
Alright. I will leave Release builds as naked as they have always been, then.

As a side note, Debug builds always turned on at least `SOL_SAFE_USERTYPE`, even in older version (`SOL_SAFE_USERTYPE` was actually the first 'small piece'). I think an additional safety feature that would cost a small amount of performance but really warn people when they pull out nonexistent garbage is `SOL_SAFE_REFERENCES` as well. This will, of course, be what I will be turning on automatically in the `DEBUG` mode.

**Comment by ThePhD** [comment]
Checklists are nice:

- [ ] `SOL_SAFE_REFERENCES` on all reference types
    + [ ] `reference`
    + [ ] `stack_reference`
    + [ ] `object`
    + [ ] `coroutine`
    + [ ] `unsafe_function`
    + [ ] `protected_function`
    + [ ] `userdata`
    + [ ] `lightuserdata`
- [ ] `SOL_SAFE_FUNCTION_CALLS` on the `lua_call` and similar `function_types.hpp` types
    + [ ] `call.hpp`
    + [ ] `function_types.hpp` (and sub headers)
    + [ ] 
- [ ] `SOL_SAFE_PROXIES` on all proxy types
    + [ ] `unsafe_function_result`
    + [ ] `protected_function_result`
- [ ] `SOL_SAFE_GETTER` affects everything, but only changes how the getter works at the moment

**Comment by ThePhD** [comment]
Annnd we're done.

Now I have to write docs for these 5 new defines, buh.

**Comment by ThePhD** [comment]
It's in the latest: http://sol2.readthedocs.io/en/latest/safety.html
