### ISSUE TITLE
Compile error C2480 and Visual Studio 2017

### ISSUE THREAD

**Issue by flyengineonline** [ThePhD/sol2#545]
Hi.
I use visual studio 2017 and get compilation error C2480. 
![image](https://user-images.githubusercontent.com/32847562/33802007-9a11c47e-dd9f-11e7-849c-85caf2667d11.png)

```
#include "stdafx.h"

#include "sol.hpp"
#include <cassert>

int main(int argc, char* argv[]) 
{
	sol::state lua;
	int x = 0;
	lua.set_function("beep", [&x] { ++x; });
	lua.script("beep()");
	assert(x == 1);
}
```

**Comment by ThePhD** [comment]
That's bizarre, I don't receive this error. `thread_local` automatically implies `static`. What is the text of the error you are receiving?

**Comment by flyengineonline** [comment]
E1378  local storage of variables in the stream can be used only for static and external variables
E0020 identifier not defined
C2480 thread allowed only for static data items
![image](https://user-images.githubusercontent.com/32847562/33802167-53a615e0-dda3-11e7-82f7-ffb9e8dd54eb.png)

**Comment by ThePhD** [comment]
I cannot reproduce your error. Pasting that code into Visual Studio 2017 Community Edition, I receive no errors and it builds.

Note that red underlines do not stop a build: sometimes, the Intellisense compiler is not caught up to the regular C++ compiler that actually compiles your code.

````
1>------ Build started: Project: scratch, Configuration: Debug x64 ------
1>main.cpp
1>scratch.vcxproj -> sol\x64\Debug\scratch.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
````
![It works](https://i.imgur.com/CXt02G7.png)

Please make sure you're using the latest sol2 (grab the single header out of `single/sol` folder in repository).

**Comment by effolkronium** [comment]
@ThePhD, cute color highlighter! Can you export it for me?)

**Comment by ThePhD** [comment]
@effolkronium The color scheme comes from Visual Assist X: https://www.wholetomato.com/
