### ISSUE TITLE
C++17 depreciated functions in VS2017 v15.5.x

### ISSUE THREAD

**Issue by reworks** [ThePhD/sol2#549]
Getting a number of errors trying to compile sol2 on the latest visual studio. Seems Microsoft have depreciated a large number of functions in C++17?

Error Log:
https://pastebin.com/RkQA68u0

Specific Error(s):
C4996
STL4017

Workaround:
#define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/codecvt.html

The note there explains the rationale. In other words, you need to define it. They deprecated codecvt, but they failed to provide any kind of meaningful alternative that was not hand-tied to their platform.

If I could find a Public Domain or MIT licensed (or similar) unicode library that handled utf32/16 -> utf8 and utf8 -> utf16/32, I could also replace it with that, but I'm trying to keep my dependency count to a minimum here.
