### ISSUE TITLE
Stack Guard

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#55]
Much like `lock_guard`, `stack_guard` should  get the number of elements on the stack on construction and then get the number on exist and throw / error if the number is wrong if there's a violation in the destructor. It can be used as a check invariants and expectations.

There could be two types: one used internally in the framework that only errors / throws on if `SOL_CHECK_ARGUMENTS` is specified (but these invariants aren't something the framework is ever supposed to break, so... redundant / overkill in addition to unit tests?). The other should error all the time (this one will be `stack_guard`).

**Comment by Nava2** [comment]
> but these invariants aren't something the framework is ever supposed to break, so... redundant / overkill in addition to unit tests?

If they're removed during optimization, what's the harm in a debug build? What was the justification for the idea in the first place?

**Comment by ThePhD** [comment]
Safety was the justification.

**Comment by ThePhD** [comment]
But there's only been once time I forgot to clean the stack nicely. :B

**Comment by ThePhD** [comment]
Added,though not yet fully integrated or used in `Sol` yet. Deciding where this is an important or critical invariant and making it part of the build is going to require more than a cursory look.
