### ISSUE TITLE
sol::as_table and vector of tuple

### ISSUE THREAD

**Issue by a1ien** [ThePhD/sol2#552]
For example we want pass `std::vector<std::tuple<int,int,int>>`

``` cpp
std::vector<std::tuple<int,int,int>> a = {{3, 4 ,5}, {6, 8,5}, {10,12,5} };
lua["arr"] = sol::as_table(a);
```
We get error on compilation. 
Error happen when we try push tuple. Call proplem seqence
https://github.com/ThePhD/sol2/blob/develop/sol/stack_push.hpp#L261 her we push as table.
On line 266 we get `const std::tuple<int,int,int>&`
pass it to stack::push and on this line [pusher<std::tuple<Args...>>](https://github.com/ThePhD/sol2/blob/develop/sol/stack_push.hpp#L903)
Here `T t` have the type const std::tuple<int,int,int>& and we call [forward_get](https://github.com/ThePhD/sol2/blob/develop/sol/traits.hpp#L614) with T  const std::tuple<int,int,int>&
in gcc 7.2 error note
`cannot convert ‘std::get<0, int, int, int>((* & tuple))’ (type ‘std::__tuple_element_t<0, std::tuple<int, int, int> > {aka const int}’) to type ‘std::remove_reference<int>::type& {aka int&}’
    return std::forward<meta::tuple_element_t<I, Tuple>>(std::get<I>(tuple));`

If we remove const and reference on https://github.com/ThePhD/sol2/blob/develop/sol/stack_push.hpp#L266
All ok. But maybe it's not best solution

**Comment by ThePhD** [comment]
We use `const auto& i` here because when you do `as_table` we have to copy it into Lua anyways, so there's no real benefit to doing anything else. I can make overloads for move operators, but that's a separate issue to `forward_get` behaving poorly...

I'll try to make `forward_get` do The Right Thing™ first.

**Comment by a1ien** [comment]
Yes, I also thought that here const auto & i is more correct. I try use unqualified_tuple_element_t in forward_get but without success.

P.S. 
And small oddities
```
std::array<std::pair<const char *, int>, 5 > a{{{"a", 1}, {"b", 2}, {"c", 3}, {"d", 4}, {"e", 5}}};
lua["arr"] = a;
//and 
lua["arr"] = sol::as_table(a);
```
in first we get
container has:
1: a
2: b
3: c
4: d
5: e
in second we get
container has:
b: 2
c: 3
d: 4
e: 5
a: 1

**Comment by ThePhD** [comment]
Lua tables are unordered data structures. There is no guarantee to iteration order. When you push a regular `std::vector`, we push a `userdata` type that we then deck out with lots of functionality to make it appear as close to a table as possible.

See: sol2.readthedocs.io/en/latest/containers.html

**Comment by ThePhD** [comment]
Also, a slight quirk of behavior: when you push a `some_list_type<T>` and perform `as_table` on it, we check to see if `T` `==` `pair<...>`. If it is, we assume you want an associative list created of the elements, not a `{1, 2, 3, 4, 5, ... }` list where each index maps to a string-number pair (plus, it's fairly hard for us to model that without creating nested tables).

This is mostly a holdover of behavior from sol1 -- I have considered changing it a few times, but it just doesn't seem worth the breaking change.

**Comment by ThePhD** [comment]
I got this fixed in my dev branch now, just need to add some more tests and make sure it doesn't happen again.

Thanks for reporting.
