### ISSUE TITLE
no suitable constructor exists to convert from "void" to "sol::protected_function_result"

### ISSUE THREAD

**Issue by phlogios** [ThePhD/sol2#556]
I'm trying to validate a script before executing it, and managed to write code that compiles and runs with Clang, but fails on Windows.

```
sol::load_result script = lua.load(source);
if (!script.valid()) {
  sol::error err = script;
  sol::load_status status = script.status();
  LOG(LogLevel::ERROR, "Something went wrong loading the code: %s error \n\t%s", sol::to_string(status).c_str(), err.what());
}
else
{
  sol::protected_function_result scriptResult = script(); //Does not compile with Visual Studio 2017
  ...
}
```
The error is:
`no suitable constructor exists to convert from "void" to "sol::protected_function_result"`
on the scriptResult assignment.

Is there a better way of doing it?

**Comment by ThePhD** [comment]
```
auto handler = [] (sol::protected_function_result pfr) {
     sol::error err = script;
     sol::load_status status = script.status();
     LOG(LogLevel::ERROR, "Something went wrong loading the code: %s error \n\t%s", sol::to_string(status).c_str(), err.what());
     return pfr;
};
lua.script(source,  handler);
```

Try this.

**Comment by ThePhD** [comment]
Yeah I edited the code, I typed it from my head and there were a few things missing. It should work now.

**Comment by ThePhD** [comment]
As a side note, your original code works just fine (I just compiled and ran it). It's just Intellisense barfing because it can't handle the templates (go figure).

If you just compile it, it works.
