### ISSUE TITLE
Old-style-cast warning.

### ISSUE THREAD

**Issue by a1ien** [ThePhD/sol2#562]
```
sol2/sol/simple_usertype_metatable.hpp:330:62: warning: use of old-style cast [-Wold-style-cast]
    baseclasscast = (void*)&detail::inheritance<T, Bases...>::type_cast;

sol2/sol/stack_get.hpp:665:79: warning: use of old-style cast [-Wold-style-cast]
     detail::inheritance_cast_function ic = (detail::inheritance_cast_function)basecastdata;

sol2/sol/usertype_metatable.hpp:454:62: warning: use of old-style cast [-Wold-style-cast]
    baseclasscast = (void*)&detail::inheritance<T, Bases...>::type_cast;

sol2/sol/optional_implementation.hpp:669:16: warning: use of old-style cast [-Wold-style-cast]
         : *(T*)nullptr;

sol2/sol/stack_check.hpp:458:82: warning: use of old-style cast [-Wold-style-cast]
      detail::inheritance_check_function ic = (detail::inheritance_check_function)basecastdata;

```

**Comment by ThePhD** [comment]
Some of these are fixable. Others are not allowed. I'll modify as needed, but honestly you should ignore the warning here: it's not buying you anything useful.

**Comment by a1ien** [comment]
> it's not buying you anything useful.
Yes but if project include this warning it's also enable in sol.
> Others are not allowed.
You are talking about `(detail::inheritance_cast_function)basecastdata`?

**Comment by ThePhD** [comment]
This should be taken care of.

I changed how some of the casting is done and so this shouldn't be an issue any longer. Most of it was just transitioning to static cast, some required a reinterpret_cast. In both cases it seems GCC/Clang are not going to yell at me for casting function pointers and similar using `reinterpret_cast` , so I'll take it.
