### ISSUE TITLE
C2675: usertype can't register class members of type std::set<std::string>

### ISSUE THREAD

**Issue by razaron** [ThePhD/sol2#564]
Hi,
I'm having a problem (fails to compile) where I can't registers variables of type `std::set<std::string>` to a usertype.
Variables of type `std::set<const char*>` register and works just fine. 

The compilation error:
`unary '--': 'std::string' does not define this operator or a conversion to a type acceptable to the predefined operator`	in file `c:\libraries\sol2\sol\container_traits.hpp` @ `line 890`
This is in VS2017 using  /std:c++17.

Minimum example:
```C++
struct Foo
{
	std::set<std::string> set{};
	Foo() {}
};

struct Bar
{
	std::set<const char*> set{};
	Bar() {}
};

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	
	// Fails to compile
	lua.new_usertype<Foo>("Foo",
		sol::constructors<Foo()>(),
		"set", &Foo::set
		);
	
	// Compiles and works
	lua.new_usertype<Bar>("Bar",
		sol::constructors<Bar()>(),
		"set", &Bar::set
		);
}
```

**Comment by ThePhD** [comment]
I'll look into this soon.
