### ISSUE TITLE
Restart lua and clenup sol::protected_function

### ISSUE THREAD

**Issue by a1ien** [ThePhD/sol2#567]
I try restart lua and clean up saved reference.
``` cpp
	sol::protected_function callback{};
	sol::state lua;

	lua.script("function func() end");
	callback = static_cast<sol::protected_function>(lua["func"]);
	callback();
	callback = {};
	lua = {};

	lua.script("function func() end");
	callback = static_cast<sol::protected_function>(lua["func"]);
	callback();
```
`callback = {}` not proper clean up. After this assign we have point to lua_state it's ok if we not close state.
But after when callback assign new value we call `move_assign` and inside `move_assign` call `detail::xmovabl` with old lua_state. And one of this state was closed.
If we just call `callback = static_cast<sol::protected_function>(lua["func"]);` without `callback = {};`
closed lua_stete be in xmovabl call

**Comment by a1ien** [comment]
It seems that [here](https://github.com/ThePhD/sol2/blob/develop/sol/reference.hpp#L202) we forgot to reset the pointer

**Comment by a1ien** [comment]
Oh link above to `copy_assign` correct [this](https://github.com/ThePhD/sol2/blob/develop/sol/reference.hpp#L225) `move_assign`.
But maybe we need set luastate to nullptr everywhere.
Since we do not get consistency with the constructor.

**Comment by ThePhD** [comment]
This should now work as advertised. Best of luck!
