### ISSUE TITLE
Avoid allocation at runtime with user_type

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#569]
Hi,

There is some string allocation at runtime when using user datatype.
In order to avoid this you can define mapping_t like that

```
struct mapping_key_t
    {
      size_t keyHash;

      mapping_key_t(const std::string& key)
        : keyHash(std::hash<string_view>()(string_view(key)))
      {
      }

      mapping_key_t(const char *key)
        : keyHash(std::hash<string_view>()(string_view(key)))
      {
      }
    };

    struct mapping_key_hasher_t
    {
      std::size_t operator()(const mapping_key_t& k) const
      {
        return k.keyHash;
      }
    };

    struct mapping_key_eq_t
    {
      bool operator()(const mapping_key_t& left, const mapping_key_t& right) const
      {
        return left.keyHash == right.keyHash;
      }
    };

    typedef std::unordered_map<mapping_key_t, call_information, mapping_key_hasher_t, mapping_key_eq_t> mapping_t;
```
and
```
				auto name = stack::get<const char*>(L, keyidx);
				auto memberit = f.mapping.find(name);
```
instead of using a string

Thanks !

**Comment by ThePhD** [comment]
And what happens when 2 keys produce the same hash?

**Comment by otristan** [comment]
silly me.
I would like to do something along this then
```
    struct mapping_key_hasher_t
    {
      std::hash<string_view> hash;

      std::size_t operator()(const std::string_view& k) const
      {
        return hash(k);
      }
    };

    struct mapping_key_eq_t
    {
      bool operator()(const string_view& left, const string_view& right) const
      {
        return left == right;
      }
    };

    typedef std::unordered_map<std::string, call_information, mapping_key_hasher_t, mapping_key_eq_t> mapping_t;
```

but This is not currently possible with unordered_map
https://stackoverflow.com/questions/34596768/stdunordered-mapfind-using-a-type-different-than-the-key-type/34598083

:(

**Comment by ThePhD** [comment]
Yeah. I've already went through this pain, figuring this out.

For what it's worth, the allocation cost for this is almost entirely negligible on any recent implementation of the standard library and any OS published after 1990 because allocators these days never just do single allocations, they always allocate blocks and increase the total block size when necessary: sol2 almost never triggers this by allocating a few **bytes** just to dump some string data for a field name,

**Comment by otristan** [comment]
My issue here is that we run the lua interpreter in a time critical priority audio thread where you are forbidden to allocate because of allocation lock.

**Comment by otristan** [comment]
a simple fix using 
typedef std::map<std::string, call_information, std::less<>> mapping_t;

but I suppose you have chosen unordered_map for speed reasons

**Comment by ThePhD** [comment]
For speed reasons, yes. Benchmarks checking string lookup for everything from 10 to 10,000 elements in a map indicated that even an unordered_map at 10 random strings beat out std::map and sorted std::vector.

However, now that you've explained to me your actual use case I can start building out a `SOL_NO_CRITICAL_ALLOCATIONS` code path that can help you. Defining `mapping_t` to what you wrote would be a start, and I can look into other pain points for you as well.

Are there any other areas where you need to avoid allocations, as dictated by company rules?

**Comment by otristan** [comment]
For everything that runs in a highly concurrent thread environment, allocation is usually a big no no because of this global lock especially in case of different thread priority.
You don't want your time critical thread to wait for a low priority thread to finish his allocation.
Usually people use per thread allocator like Intel Thread building blocks, but no allocation is even better :)

**Comment by ThePhD** [comment]
My question is what parts of sol2 are you running in a highly concurrent thread environment? As far as I know, usertype variables/functions are the only thing that do run-time allocation of data (string data, in that one place you saw where we look up fields).

I'm wondering if there are any other places that you ran in the environment that triggered the allocation thread lock, just to check to make sure I'm not missing anything.

Note that any changes I make for this will likely be guarded behind `SOL_NO_CRITICAL_ALLOCATIONS`. I know for a fact that registering a usertype with `new_usertype` makes several allocations (for `simple`) and 1/2 allocations (for normal `new_usertype`), but you shouldn't be registering classes post-initialization or modifying them post-initialization in this kind of contentious environment. There are just about no other string allocations asides from that that I know of.

Also, what compiler are you using this for? Diamond comparators `std::less<>` and friends weren't widely adopted for the older ones, so you must be using something fairly new?

**Comment by otristan** [comment]
So far this is the only place that was triggered in my use case.
Don't care indeed about register allocation as this is not done in the time critical thread.

using VS2017 (15.5) for my test but hopefully it should work in Xcode 9.2 which is my other target platform

**Comment by otristan** [comment]
FWIW boost::unordered_map allows a find with CompatibleKey
http://www.boost.org/doc/libs/1_64_0/doc/html/boost/unordered_map.html

**Comment by ThePhD** [comment]
Do you use `boost`? I can't turn it on by default but I do have `SOL_USE_BOOST` as a define, so I can add `boost::unordered_map<>` as part of what happens with that.

**Comment by otristan** [comment]
edited my post in the meantime.
So yes :)

**Comment by otristan** [comment]
Found another allocation.
`call_syntax syntax = argcount > 0 ? stack::get_call_syntax(L, &usertype_traits<T>::user_metatable()[0], 1) : call_syntax::dot;`
but I'm wondering what the code is actually doing.
Is there a reason to use `&usertype_traits<T>::user_metatable()[0]` which is then constructed into a string instead of `usertype_traits<T>::user_metatable()` which directly returns a const string &?

This  `&usertype_traits<T>::user_metatable()[0]` is use at multiple location.

Thanks !

**Comment by ThePhD** [comment]
Old code where it took `const char*`, but was changed I think.

**Comment by otristan** [comment]
In that case my fix will do the trick.
You can update the three
`stack::get_call_syntax(L, &usertype_traits<T>::user_metatable()[0], 1)`
to
`stack::get_call_syntax(L, usertype_traits<T>::user_metatable(), 1)`

Thanks !

**Comment by ThePhD** [comment]
Implemented and hand-tested (I don't have a test harness for boost builds, though I'm sure one day I should make one).

Grab the latest and give it a whirl, tell me if any other allocations send your company into a tizzy.

**Comment by otristan** [comment]
All good on my end now. Will let you know if I find other unwanted allocation.
Hopefully your benchmark are now a lot better ;)

Thanks a lot !
Much appreciated.

**Comment by otristan** [comment]
Following test on my own regarding similar usage of boost unordered_map with string and sol::string_view, looks like the assumption that boost::hash<string> return's values(how the map_t is declared) and boost::hash_range return's values are similar is not always right.
Might be safer to use a custom hasher in both case implemented in both case using boost::hash_range

SOL_USE_BOOST and !SOL_CXX17_FEATURES case

**Comment by ThePhD** [comment]
https://www.boost.org/doc/libs/1_67_0/doc/html/hash/reference.html#boost.hash_va_1_3_11_11_2_2_27_1

![Nice](https://i.imgur.com/kh12MpU.png)

Always nice when docs lies to me...
