### ISSUE TITLE
new_enum<enum_type> creates an extra table

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#573]
Let's say we create an enum like this:
```
sol::state lua;
sol::table t = lua.create_table("foo");
enum class values
{
	x=40,y=41,z=42
};
t.new_enum<values>("values1", { { "x", values::x }, { "y", values::y },{ "z", values::z } });
t.new_enum("values2", "x", values::x, "y", values::y, "z", values::z);
```
And then dump the content of the "foo" table, e.g. using this: https://stackoverflow.com/a/42062321/1530347

Output:
```
{
	['values2'] = {

	},
	['values1'] = {

	},
	[3] = {
		['z'] = 42,
		['y'] = 41,
		['x'] = 40
	}
}
```
If you only run the second enum registration, you only get the empty "values2" table (I guess whether the contents of these tables cannot be enumerated from Lua or not is a separate issue).
However, the registration of "values1" also inserts a second table, whose index is equal to the number of objects in the enum. That looks like it shouldn't be happening.

**Comment by ThePhD** [comment]
I fixed the `[{Number here}]` array problem in latest, but the rest of those arrays are actually totally 100% legit.

What the `print_table` algorithm doesn't consider is the case where `_index` metatable field of the `values1` and `values2` table points to another table, which in turn controls lookup. Note that we do this to ensure the read-only-ness of the table, as it required of most enums (if you change the template parameter to `false`, the values will show in the table). You can modify the `print_table` implementation to chase metatable's `__index` and print its values if it too is a table.

**Comment by sagamusix** [comment]
Thanks for the fix! Yeah I noticed that many of these printers don't seem to be able to get into some data structures, so I already considered rolling my own...
