### ISSUE TITLE
passing argument as reference doesn't compile

### ISSUE THREAD

**Issue by emikita** [ThePhD/sol2#576]
void ArgByRef(int& r) // ok when ref is removed
{
	r++;
}

lua["ArgByRef"] = &ArgByRef;
lua.script("a = 0;	ArgByRef(a);		assert(a == 1)");

with error (VS2015):
1>d:\projects\mainrepository\sier\sources\external\include\sol\sol.hpp(11335): error C2664: 'void (int &)': cannot convert argument 1 from 'std::ios_base::iostate' to 'int &'
1>  d:\projects\mainrepository\sier\sources\external\include\sol\sol.hpp(11341): note: see reference to function template instantiation 'decltype(auto) sol::wrapper<void (__cdecl *)(int &),void>::call<_Ty>(F &,_Ty &&)' being compiled
1>          with
1>          [
1>              _Ty=std::ios_base::iostate,
1>              F=void (__cdecl *)(int &)
1>          ]
...

**Comment by ThePhD** [comment]
You can't pass things by reference that are primitives. Lua does not support this.

**Comment by emikita** [comment]
Thanx
