### ISSUE TITLE
Issue with inheritance

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#580]
Hi,

I'm trying to do some lua binding for the Juce Library
https://juce.com/

and I'm having some trouble making it work

My basic wrapping is done as is

```
    lua.new_usertype<juce::Colour>("Colour"
                                   , sol::constructors<juce::Colour(uint32)>()
                                   , sol::call_constructor, sol::constructors<juce::Colour(uint32)>()
                                   );

    lua.new_usertype<juce::Component>("Component"
                                      );

    lua.new_usertype<juce::DocumentWindow>("DocumentWindow"
                                           , sol::constructors<juce::DocumentWindow(const juce::String&, juce::Colour, int)>()
                                           , sol::call_constructor, sol::constructors<juce::DocumentWindow(const juce::String&, juce::Colour, int)>()
                                           , "centreWithSize", &DocumentWindow::centreWithSize
                                           , "setVisible", &DocumentWindow::setVisible
                                           , "addAndMakeVisible", sol::resolve<void(Component*, int)>(&Component::addAndMakeVisible)
                                           );

    lua.new_usertype<juce::Slider>("Slider"
                                   , sol::constructors<juce::Slider()>()
                                   , sol::call_constructor, sol::constructors<juce::Slider()>()
                                   , sol::base_classes, sol::bases<juce::Component>()
                                   , "setBounds", sol::resolve<void(int, int, int, int)>(&juce::Slider::setBounds)
                                   );
```

where Slider is a Component and setBounds is a method with multiple signature hence the usage of resolve

The lua code is the following:
```
window = DocumentWindow("Main", Colour(0xffFF0000), 0)
window:centreWithSize(800, 600)
window:setVisible(true)

mySlider = Slider()
Slider.setBounds(mySlider, 50, 50, 100, 30)
--mySlider:setBounds(50, 50, 100, 30)
window:addAndMakeVisible(mySlider, 0)
```

the first version works while the commented version with : doesn't.

Am I missing something ?

Thanks !

**Comment by otristan** [comment]
humm if I don't define SOL_USE_BOOST, it works fine

**Comment by otristan** [comment]
more precisely with SOL_UNORDERED_MAP_COMPATIBLE_HASH

**Comment by ThePhD** [comment]
What does "doesn't work" mean here? Compile-time error? Runtime error? Returns the wrong method?

I need a few more details so I can help narrow this down, as I do not have JUCE.

**Comment by otristan** [comment]
It says that I try to call a null function aka don’t find the function definition. I will be able to give you the exact error message tomorrow at the office. Looks like the boost unordered_map with string_view mess up the lookup when there is some inheritance as it works fine for DocumentWindow right now and fails as soon as declare Component as a base of DocumentWindow

**Comment by ThePhD** [comment]
Can you also tell me the platform you're on? We use varying hash functions based on what platform is available, or default to the boost one if it's available, so I'd need to check to make sure there's equivalency between the hashes...

**Comment by otristan** [comment]
That did the trick.
This was indeed a hash mismatch.

Thanks !
