### ISSUE TITLE
[HELP] All examples in docs should not be in-line, but should point to an actual source file

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#581]
All of the longer examples in the docs should point to a source file. We did this for the tutorial, but we should do it for all of the other source files and have a link to the file so people know that this stuff is compilable, real stuff that works.

**Comment by a1ien** [comment]
[Here ](https://github.com/ThePhD/sol2/blob/develop/docs/source/tutorial/customization.rst) is not a correct example(abs index and subtraction).
But in [source ](https://github.com/ThePhD/sol2/blob/develop/examples/customization.cpp) correct

**Comment by ThePhD** [comment]
Hence why we need more of these places to point to source, and why I need to update the documentation. Pointing to real source files compiled by the tests make our documentation more honest and less likely to fall out of proper usage.

**Comment by ThePhD** [comment]
As a side note, this is the kind of changes I would need help doing:

https://github.com/ThePhD/sol2/commit/22c41d94826df7326f3e13f463ba14a4dffea3db

Plus, if anyone has any additional examples they want to add to the repository to help those that come after them, please do!

**Comment by ThePhD** [comment]
As of

https://github.com/ThePhD/sol2/commit/947945d098ad28a930f0fc7d028abc880c24836e

Documentation has been fully vetted and cleaned, and now all examples are based in a file that is run as part of the examples / tests suite.
