### ISSUE TITLE
Crashed in math.pow function

### ISSUE THREAD

**Issue by 21JiCao** [ThePhD/sol2#582]
```
#include <sol.hpp>
#include <cassert>

int main() {
    sol::state lua;
	lua.open_libraries(sol::lib::base);
	lua.open_libraries(sol::lib::math);

	lua.script("function g (a, b) return math.pow(a,b) end");
	double r = lua["g"](2.5, 2.0);
}
```

Above code crashed in Windows 10, 64 bit, VS community 2017, debug mode. Please help.

**Comment by ThePhD** [comment]
math.pow and other math functions were deprecated in Lua 5.3.

https://www.lua.org/manual/5.3/manual.html#8.2

Sorry. You need to use the exponentiation operator instead of math.pow.
