### ISSUE TITLE
override function metatable with lua code

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#583]
Hi,

I was wondering if it is possible to override a usertype function metatable at runtime using Lua code?

I'm trying to bind a GUI library (Juce) with a base type of Component which features a paint function that takes a Graphic context
```

lua.new_usertype<Graphics>("Graphics"
                               , "fillAll", sol::overload(sol::resolve<void(void) const>(&Graphics::fillAll), sol::resolve<void(Colour) const>(&Graphics::fillAll))
                               );

lua.new_usertype<Component>("Component"
                                , sol::constructors<Component()>()
                                , sol::call_constructor, sol::constructors<Component()>()
                                , "paint", &Component::paint
                                );
```
and in lua do something like that

```
local comp = Component()
comp.paint = function(self, g)
	g:fillAll(Colour(0xffFF0000))
end
```

Right now I have the following error
attempt to index a sol.juce::Component value (local 'comp')

Should it work ? if not, is there a proper way to support this ?

Thanks !

**Comment by ThePhD** [comment]
You cannot override on a per-object basis. At least, you can't do that by default. sol2 allows you to mess with the overall metatable for the ENTIRE class (using `function Component:paint ( ... ) .... end`).

If you want table-like semantics, you'll need to do some hooking-up of the index function. There are examples of how to do this: https://github.com/ThePhD/sol2/blob/develop/examples/usertype_dynamic_getter_setter.cpp#L16

The logic only shows how it works for `local v = obj.member` and `obj.member = blah`, but you can extend the syntax to support also retrieving functions. Note that `obj:function()` is simple `obj.function(obj)`, so it will call your getter with the function's name and you will be expected to return the function so that the Lua VM can call it for you with all the arguments (you do not call it directly yourself).

I need to write some more examples for this...

**Comment by otristan** [comment]
Will check this.

```
 sol::object ComponentGetter(juce::Component *pThis, sol::stack_object key, sol::this_state L) 
  {
    return sol::object(L, sol::in_place, sol::lua_nil);
  }

  void ComponentSetter(juce::Component *pThis, sol::stack_object key, sol::stack_object value, sol::this_state L) 
  {
  }
```

```
, sol::meta_function::index, &ComponentGetter
 , sol::meta_function::new_index, &ComponentSetter
```

Is this supposed to work as well with non member function ?
because right now this do not compile (cannot convert from 'sol::stack::check_getter<Tu,void>...)
as my goal is to add this support to juce::Component in a non intrusive way.

**Comment by otristan** [comment]
In any way I need to do some c++ wrapper as the c++ will need to find the new virtual function one way or another ;)

**Comment by ThePhD** [comment]
I don't quite know what that does from looking at the LuaBind examples. Do you have a better description of what it's supposed to do?

**Comment by otristan** [comment]
The paint member function of a Component is a c++ virtual member function that draws the widget.
My goal is to be able to override this drawing method in Lua like that
```
local comp = Component()
comp.paint = function(self, g)
	g:fillAll(Colour(0xffFF0000))
end
```
so I need a C++ class that wrap the original c++ Component instantiated from Lua where I can again call Lua code if it has been overridden.
wrap_base allows to have access to lua context inside the wrapped Component object.

Let me know if this is still unclear.

**Comment by OrfeasZ** [comment]
@otristan when you set the `paint` function like that from lua, does it get overwritten for all `Component` objects or just that one instance (`comp`)?

**Comment by OrfeasZ** [comment]
I mean ideally, in your scenario, not currently.

**Comment by otristan** [comment]
just that one instance

**Comment by otristan** [comment]
in LuaBind, this looks like that
```
struct ComponentWrapper : public Component, public wrap_base
{
  ComponentWrapper(): Component() {}
  ComponentWrapper(const juce::String &name): Component(name) {}
  
  
  virtual void resized() 
  {
    call<void>("resized");
  }
  
  static void default_resized(Component *p)
  {
    p->Component::resized();
  }  

  virtual void paint(Graphics &g) 
  {
    call<void>("paint", boost::ref(g));
  }
  
  static void default_paint(Component *p, Graphics &g)
  {
    p->Component::paint(g);
  }  
};
```

```
 module(L)[
 class_<Component, ComponentWrapper>("Component")
 .def("paint", &Component::paint, &ComponentWrapper::default_paint)
];
```

**Comment by OrfeasZ** [comment]
In that case, if I'm understanding correctly, you want sol to individually manage vtables for bound usertype objects?

In implementation terms, if you want to do it transparently from both C++ and Lua, I guess this would mean:

1. Having a way of marking usertypes and bound functions as "overridable", which would require said functions to be virtual.
2. For said "overridable" usertypes, creating a copy of the original vtable and pointing the vtable pointer of the bound object to it, per object (is there even a way to reliably determine the size of a vtable?).
3. Introduce a storage mechanism for lua functions when assigned on a usertype object (lifetime management?).
4. For each overridable virtual function assigned from lua, overwrite the corresponding entry in the vtable to point to a proxy function that calls the stored lua function (can the index of the function pointer in the vtable be reliably determined?) and returns the results (exception handling?).

Just some thoughts, there might be a better way to do this.

**Comment by otristan** [comment]
Not asking for something magic, but at least for something similar to what LuaBind offers would be good enough.

**Comment by OrfeasZ** [comment]
I believe you can already achieve what you're trying to do with the current version of sol2. You can try something like this:

Your class:
```cpp
class Component
{
public:
    void Paint()
    {
        if (!customPaint)
            return PaintInternal();

        paint();
    }

    void PaintInternal() { ... }

    void Setter(sol::stack_object key, sol::stack_object value, sol::this_state)
    {
        // Add more checks here.
        if (key.as<std::string>() == "paint")
        {
            customPaint = true;
            paint = value.as<sol::protected_function>();
        }
    }
private:
    bool customPaint;
    sol::protected_function paint;
};
```

And then bind it as:

```cpp
lua.new_usertype<Component>("Component"
    "paint", &Component::Paint,
    sol::meta_function::new_index, &Component::Setter
);
```

**Comment by ThePhD** [comment]
````cpp
#define SOL_CHECK_ARGUMENTS 1
#define SOL_USE_BOOST 1
#include <sol.hpp>
#include <string>

#include <iostream>

int main() {
	
	struct thingy {
		sol::function paint;

		thingy(sol::this_state L) : paint(sol::make_reference<sol::function>(L.lua_state(), &thingy::default_paint)) {
		}

		void default_paint() {
			std::cout << "p" << std::endl;
		}

	};
	
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<thingy>("thingy",
		sol::constructors<thingy(sol::this_state)>(),
		"paint", &thingy::paint);

	sol::string_view code = R"(
obj = thingy.new()
obj:paint()
obj.paint = function (self) print("g") end
obj:paint()
function obj:paint () print("s") end
obj:paint()
)";

	lua.safe_script(code);

	return 0;
}
````

This is one way that "just works". Note that you're spending storage every time you create a new function to hold the `lua_State*` and the `int index` (along with an inner `sol::reference` for the error handler, if `SOL_SAFE_FUNCTION` is defined).

Also note that both syntaxes to define a function work using the object itself.

If you want something more complicated, again, you can simply go the route of writing your own indexing table and calling functions as you see fit, as @OrfeasZ is showing off.

**Comment by otristan** [comment]
This looks good.
Will check this.

Thanks a lot !
