### ISSUE TITLE
C2665: 'sol::usertype_detail::is_indexer': none of the 4 overloads could convert all the argument types

### ISSUE THREAD

**Issue by NullCascade** [ThePhD/sol2#584]
Duplicate of closed issue #330 

Environment is Visual Studio 2017 (15.5.5), developing an x86 DLL using C++. Host operating system is Windows 10 (up to date). Entire project can be found at https://github.com/NullCascade/MWSE/tree/lua-binding

I am implementing Sol2 as a simple header as part of the source files. I am linking to the latest stable version of LuaJIT (included in the repo above, but msvcbuild has to be run manually).

The code in question is not in the above repo, but is simple and pasted below. It is the start of binding [this struct](https://github.com/NullCascade/MWSE/blob/lua-binding/MWSE/TES3Script.h), and the code is inserted before `#if ENABLE_LUA_OVERRIDE` in [LuaInterface.cpp](https://github.com/NullCascade/MWSE/blob/lua-binding/MWSE/LuaInterface.cpp#L193).

```cpp
state->new_usertype<TES3::Script>("mwScript"
    "longVariableCount", sol::readonly(&TES3::Script::longCount)
    );
```
The same error happens when not specifying `sol::readonly` or when using `sol::property`/`sol::readonly_property` instead.

I've tried cleaning the project and building again. I've tried building in debug and release, and don't get further details. 

Please let me know if there's anything else I can do to help narrow down the issue.

**Comment by NullCascade** [comment]
Noticed I was on v2.18.7 instead of v2.19. I updated to the latest single header version without any change in the issue.

**Comment by ThePhD** [comment]
I'm having a hard time reproducing this. Might take me a while.

**Comment by NullCascade** [comment]
Something between [this commit](https://github.com/NullCascade/MWSE/commit/024ef09a8a215f3e317689a3e153fdf02343831e) and [this commit](https://github.com/NullCascade/MWSE/commit/51f097b362b8b525f66e689243350e3e4a230e93) seems to have gotten rid of the issue for me. Hopefully this will help you narrow it down.

The project linked is mostly self-contained (exception being the need to build LuaJIT separately, but it's in the repo too) and should be easy to jump into if you think it's related to something specific there.

**Comment by NullCascade** [comment]
As usual, this is user error.

The issue is that there is no comma after the name of the usertype. In my code above:
```cpp
state->new_usertype<TES3::Script>("mwScript"
    "longVariableCount", sol::readonly(&TES3::Script::longCount)
    );
```

When it should be:
```cpp
state->new_usertype<TES3::Script>("mwScript",
    "longVariableCount", sol::readonly(&TES3::Script::longCount)
    );
```

**Comment by ThePhD** [comment]
That is really unfortunate. I'm glad you could solve it, though!
