### ISSUE TITLE
Coroutine stack traceback

### ISSUE THREAD

**Issue by THE-FYP** [ThePhD/sol2#588]
Sol kindly provides a stack traceback message with all the errors that could be caught, but except for errors from coroutines. I suggest adding a stack traceback for coroutines too.
I made it for myself by small change in `coroutine.hpp`, but I think it would be nice if Sol had this feature natively.
```diff
diff --git a/sol/coroutine.hpp b/sol/coroutine.hpp
--- a/sol/coroutine.hpp
+++ b/sol/coroutine.hpp
@@ -59,11 +59,13 @@ namespace sol {
                protected_function_result invoke(types<>, std::index_sequence<>, std::ptrdiff_t n) {
                        int firstreturn = 1;
                        luacall(n, LUA_MULTRET);
-                       int poststacksize = lua_gettop(lua_state());
-                       int returncount = poststacksize - (firstreturn - 1);
                        if (error()) {
+                               optional<const char*> errormsg = stack::get<const char*>(lua_state());
+                               luaL_traceback(lua_state(), lua_state(), errormsg.value_or(nullptr), 0);
+                               int returncount = lua_gettop(lua_state()) - (firstreturn - 1);
                                return protected_function_result(lua_state(), lua_absindex(lua_state(), -1), 1, returncount, status());
                        }
+                       int returncount = lua_gettop(lua_state()) - (firstreturn - 1);
                        return protected_function_result(lua_state(), firstreturn, returncount, returncount, status());
                }
```

However, despite it's working fine (just doesn't print the coroutine's function name), I'm not doing PR because I can't be sure if this is a proper solution, so it's up to you.

Thanks.

**Comment by ThePhD** [comment]
This is probably because `coroutine` doesn't include the basic error handling function that calls `luaL_traceback` by default. I think the better top-level idea is to make it so `coroutine` by default uses the same mechanisms as `protected_function`.

**Comment by ThePhD** [comment]
This has been built into the latest and will be pushed soon.

**Comment by ThePhD** [comment]
Implemented.
