### ISSUE TITLE
issue with uint64 c++ -> lua 

### ISSUE THREAD

**Issue by didierjeanphi** [ThePhD/sol2#590]
Good evening,

I have the methods with the following signature

```c++
uint64_t fnv1_a ( std::string const & str)... 
bool isRegistered ( uint64_t  value)
```
I use the following lua script

```lua
local dpxvar = dpxmakeId("depixus.device.rawhid.DPXHIDevice")
-- HERE print displays 1.7437945503387e+19
if dpxqueryclsId( dpxvar  )  then ---issue here for the number 
-- in this function, the value is 9223372036854775808
end
```
Does the library of Lua support uint64_t ?

**Comment by ThePhD** [comment]
Lua does not support Unsigned 64-bit integers. The highest Lua 5.3 can handle is a lua_Integer, which is a **signed** 64-bit number.

sol2 does not check potential misrepresentation and overflow by default. You can turn it on using: `SOL_SAFE_NUMERICS` definition, as described in http://sol2.readthedocs.io/en/latest/safety.html#safety-config

Please note that proper handling should be done VIA some other mechanism, such as making a custom `unsigned` wrapper that holds the uint64_t in a struct, then register that struct as a usertype.
