### ISSUE TITLE
Destructors of objects created within bindings not called when function raises error

### ISSUE THREAD

**Issue by hzwar** [ThePhD/sol2#592]
Hi,
thanks for this outstanding library!
I'm not sure if it's by design (can't be solved) or a bug. It's about stack unwinding and releasing of resources allocated within a bound function which eventually triggers a luaL_error (explicitly or by Sol itself). In the test below I'd expect that the shared_ptr is destructed automatically because doc says 
> When a Lua VM error occurs and lua_error is triggered, it raises it as an exception which will provoke proper unwinding semantics.

Commenting out the luaL_error makes the test pass.

Reproduced on OSX10.13.3, develop, v2.19.0 and some older past 2.18.x tags
```
TEST(Sol, LeakTest)
{
    static size_t fooCount{};

    struct Foo
    {
        Foo()
        {
            ++fooCount;
        }
        ~Foo()
        {
            --fooCount;
        }
    };

    {
        sol::state lua;
        lua.open_libraries(sol::lib::base);

        lua["fn"] = [&]() {
            auto foo = std::make_shared<Foo>();
            luaL_error(lua, "unwind me");
        };

        auto result =
            lua.script("fn()", [](lua_State*, sol::protected_function_result pfr) {
                return pfr;
            });
    }

    EXPECT_EQ(fooCount, 0);
}
```

**Comment by ThePhD** [comment]
Destructors are never run because Lua is a C API. Invoking `luaL_error` calls `longjmp`, a C-API assembly-level JUMP instruction.

There is nothing I can do to help you here, except that you should not be calling that to error. Note that sol2 attempts to catch thrown errors and serialize them into Lua errors, which allows for unwinding, but calling it directly.

Where in the docs is what quote? I thought it was predicated by "if you build Lua as C++..."

**Comment by ThePhD** [comment]
Yes, I do preface it with "Build Lua as C++": http://sol2.readthedocs.io/en/latest/errors.html?highlight=When%20a%20Lua%20VM%20error%20occurs%20#destructors-and-safety

**Comment by hzwar** [comment]
Yes, stupid me. Doc said it clearly and I quoted out of context.
Lua wasn't build as C++. So far I never forced a C lib to compile as C++. Cmake change ```set_source_files_properties(${SOURCES} PROPERTIES LANGUAGE "CXX")``` fixes my issue.
Maybe something for the doc... (or maybe I just haven't seen it).
Still get some ```clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated```when building Lua but they can be turned off. Do you know a better way to correctly force clang or better Cmake to build as C++?
Thanks!

**Comment by ThePhD** [comment]
Pass the flag `-x c++` to Clang for the build of the source files.
