### ISSUE TITLE
Missing Paragraph in exceptions.rst ?

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#594]
The third paragraph ends "Here's an example my_panic_function you can have that prints out its errors:"

But there is no example.

**Comment by ThePhD** [comment]
Probably because I moved it to `error.rst` and forgot to delete that line.

Woops.

**Comment by RussellHaley** [comment]
Also: "chances are you might have screwed the pooch."

That made me laugh out loud (literally in our quite office) but may not be entirely appropriate for documentation?

**Comment by ThePhD** [comment]
... Wait, no, it's there. I moved it _from_ `errors.rst` to `exceptions.rst`.

![Looks okay to me](https://i.imgur.com/D4v3Bg5.png)

Your, uh. Web browser might be weird?

**Comment by RussellHaley** [comment]
Google Chrome on Windows 10 - Version 63.0.3239.132 (Official Build) (64-bit)

![sol2-doc](https://user-images.githubusercontent.com/2166039/36456274-f12ed160-1658-11e8-954f-6a4e336cb2d7.PNG)

**Comment by RussellHaley** [comment]
Okay, my bad. It's correct on the docs site: http://sol2.readthedocs.io/en/latest/exceptions.html (including bestiality reference!)
The link provided on the lua-l mailing list in a conversation points to the github version and I didn't notice that. 
Anyway, I'll be sticking to exceptions so the neighbors dog is safe.  Cheers! Russ
