### ISSUE TITLE
Wrap Eigen Matrix Fails

### ISSUE THREAD

**Issue by rhythmchicago** [ThePhD/sol2#595]
Hello, everyone.

Very much enjoying sol2. I'm trying to wrap and expose an Eigen::MatrixXf to a lua script. It took me awhile to figure out a way that would compile, but I'm not sure if I'm doing this the best way. I was hoping I could get feedback.

```
class MatrixXf : Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> 
{
public:
	MatrixXf(int row, int col) :
		Eigen::MatrixXf(row, col)
	{
	}

	void resize(int row, int col)
	{
		Eigen::MatrixXf::resize(row, col);
	}
};

...

void LuaLab::registerLuaExtensions(sol::state& lua)
{
        ....
	lua.new_usertype<MatrixXf>(
		"matrix",
		sol::constructors<MatrixXf(int,int)>(),
		"resize", &MatrixXf::resize
	);
}

```

From a lua script:

```
m = matrix.new(5,5)
m:resize(2,2)
```

It works, but I'm wondering if I'm making things overly-complicated. Unfortunately, I've not found a way to 'typedef' or more directly wrap the Eigen template. For example, both of these fail to compile:

1. Replace the class with a typedef.
typedef Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> MatrixXf;
2. Publicly sub-class the Eigen::Matrix
class MatrixXf : **public** Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> 

The error is the same for both modifications:
error C2440: 'initializing': cannot convert from 'initializer list' to 'luaL_Reg'

Is there a better way to register the usertype where I wouldn't have to replicate the entire API of the template?

Thanks!

Language: C++
MSVC 2017

**Comment by OrfeasZ** [comment]
You should be able to do something like this:

```cpp
lua.new_usertype<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic>>("matrix",
	sol::constructors<sol::types<Eigen::Index, Eigen::Index>>(),
	"resize", &Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic>::resize
);
```

**Comment by rhythmchicago** [comment]
lua.new_usertype<Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic>> (
		"eigen",
		sol::constructors<sol::types<Eigen::DenseIndex, Eigen::DenseIndex>>()
	);

Same error, but now it looks like it's the optional arguments in the constructor:

1>        with
1>        [
1>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
1>        ]

Is there a way to account for that?

**Comment by OrfeasZ** [comment]
What's the full error you're getting?

**Comment by rhythmchicago** [comment]
2>../sol.hpp(17142): error C2440: 'initializing': cannot convert from 'initializer list' to 'luaL_Reg'
2>../sol.hpp(17142): note: Invalid aggregate initialization
2>../sol.hpp(17191): note: see reference to function template instantiation 'void sol::usertype_detail::make_length_op<T,Regs,sol::meta::enable_t::_>(Regs &,int &)' being compiled
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>,
2>            Regs=std::array<luaL_Reg,34>
2>        ]
2>../sol.hpp(17657): note: see reference to function template instantiation 'void sol::usertype_detail::insert_default_registrations<T,std::array<luaL_Reg,34>,sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs::<lambda_053eaa5eefc7f2766fcb414163b46f45>&>(Regs &,int &,Fx)' being compiled
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>,
2>            Regs=std::array<luaL_Reg,34>,
2>            Fx=sol::usertype_metatable<Eigen::Matrix<float,-1,-1,0,-1,-1>,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs::<lambda_053eaa5eefc7f2766fcb414163b46f45> &
2>        ]
2>../sol.hpp(17655): note: while compiling class template member function 'int sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs(std::array<luaL_Reg,34> &,int &)'
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(17915): note: see reference to function template instantiation 'int sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &>::finish_regs(std::array<luaL_Reg,34> &,int &)' being compiled
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\type_traits(477): note: see reference to class template instantiation 'sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &>' being compiled
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\memory(2150): note: see reference to class template instantiation 'std::is_convertible<sol::usertype_metatable<T,std::integer_sequence<::size_t,0,1>,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &> *,sol::usertype_detail::registrar *>' being compiled
2>        with
2>        [
2>            T=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18679): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&,const char(&)[5],const sol::destructor_wrapper<void>&>(sol::detail::verified_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18679): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&,const char(&)[5],const sol::destructor_wrapper<void>&>(sol::detail::verified_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &,const char (&)[5],const sol::destructor_wrapper<void> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18684): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&>(sol::detail::add_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18684): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&>(sol::detail::add_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18695): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&>(sol::detail::check_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(18695): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<const char(&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>&>(sol::detail::check_destructor_tag,const char (&)[4],sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>> &)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(19205): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<,sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>(sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(19205): note: see reference to function template instantiation 'sol::usertype<Class>::usertype<,sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>(sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(20365): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::new_usertype<Class,sol::types<Eigen::DenseIndex,Eigen::DenseIndex>,>(const std::string &,sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>../sol.hpp(20365): note: see reference to function template instantiation 'sol::basic_table_core<true,sol::reference> &sol::basic_table_core<true,sol::reference>::new_usertype<Class,sol::types<Eigen::DenseIndex,Eigen::DenseIndex>,>(const std::string &,sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>)' being compiled
2>        with
2>        [
2>            Class=Eigen::Matrix<float,-1,-1,0,-1,-1>
2>        ]
2>..(503): note: see reference to function template instantiation 'sol::state_view &sol::state_view::new_usertype<Eigen::Matrix<float,-1,-1,0,-1,-1>,sol::types<Eigen::DenseIndex,Eigen::DenseIndex>,>(const std::string &,sol::constructor_list<sol::types<Eigen::DenseIndex,Eigen::DenseIndex>>)' being compiled

**Comment by OrfeasZ** [comment]
Oof this was tricky. So upon further inspection it looks like sol tries to automatically bind some stuff on the class based on some assumptions it makes, but not everything is type compatible so the compiler whines. On top of that, since `resize` is generic it has to be specialized too. After some trial and error I got it to work with the latest version of sol2:

```cpp
typedef Eigen::Matrix<float, Eigen::Dynamic, Eigen::Dynamic> EigenMatrix;

namespace sol
{
	namespace meta
	{
		namespace meta_detail
		{
			template <>
			struct has_size_test<EigenMatrix>
			{
			public:
				static const bool value = false;
			};
		}
	}
}

void main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::package);

	lua.new_usertype<EigenMatrix>("matrix",
		sol::constructors<EigenMatrix(EigenMatrix::Index, EigenMatrix::Index)>(),
		"resize", (void(EigenMatrix::*)(EigenMatrix::Index, EigenMatrix::Index)) &EigenMatrix::resize
	);
	
	lua.script("m = matrix.new(5, 6)");

	EigenMatrix& m = lua["m"];

	std::cout << "Cols: " << m.cols() << " - Rows: " << m.rows() << std::endl;

	lua.script("m:resize(2, 3)");
	
	std::cout << "Cols: " << m.cols() << " - Rows: " << m.rows() << std::endl;
}
```

Try it out and let me know if it works. Keep in mind that you might encounter other issues when binding other functions / variables.

@ThePhD do you think it would be possible to introduce some sort of trait that prevents sol from binding anything that's not explicitly specified in usertype definitions?

**Comment by rhythmchicago** [comment]
Works. Thank you very much!

I suppose my next challenge is to return a reference to a value in the underlying matrix that the lua script can manipulate. The operator() overload returns a float reference that I can see in the lua script, but it doesn't change the value in the matrix if the value is changed in the lua script. I'm still working through the documentation, though.

Such a big help. Thank you very much.

**Comment by OrfeasZ** [comment]
No problem. I would leave the issue open until @ThePhD has a chance to respond.

**Comment by ThePhD** [comment]
Return types of primitive types as references cannot be changed in Lua. Lua does not know how to handle references/pointers to primitives and treat them regularly. I've thought about trying to create some kind of abstraction for them but it never pans out or holds up to scrutiny (e.g., `float*` would have to be pushed as a userdata. Any function that expects a number and does `lua_tonumber` on that argument (from the C API) or does `lua_isnumber` will invariably fail).

As for the issue here, I honestly did not expect Eigen to have such a problematic interface. Unfortunately, there's no magic I can implement that says "work with size except for Eigen".

I can maybe look at Eigen to see if I can produce a better `has_size` test...

**Comment by OrfeasZ** [comment]
Eigen's `size()` is just: `inline Index size() const { return rows() * cols(); }`, where `Index` is most likely `std::ptrdiff_t`.

**Comment by rhythmchicago** [comment]
Thanks for the heads up on return types. 

So far the @OrfeasZ solution is working, although I'm not doing anything particularly complicated yet. If the problem is unique to Eigen, perhaps documenting the proper approach is the best solution. I'll be working on this the next few days and will happily turn in whatever working code I hammer out.

Again, thank you for all the help. If you need anything tested, let me know.

**Comment by ThePhD** [comment]
`lua_CFunction test = sol::c_call<decltype(&EigenMatrix::size), &EigenMatrix::size>;`

This line doesn't compile. For some reason. It seems like I can't use Eigen's `size` in a compile-time context.

**Comment by OrfeasZ** [comment]
Yeah, it's pretty odd. I tried making a reproduction case by re-implementing size one-to-one but that didn't trigger the issue. I wonder if this also happens with other compilers.

**Comment by rhythmchicago** [comment]
Does it help if I post what I have working so far?

**Comment by ThePhD** [comment]
I should have already fixed it and Eigen should work properly now.

@OrfeasZ There's also a note in the documentation for an escape hatch, when you don't want default functions automatically registered: http://sol2.readthedocs.io/en/latest/api/usertype.html#automagical-usertypes
