### ISSUE TITLE
Tables and Iterators?

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#596]
Hi, 
Sorry, my C++ skills are non-existent and I couldn't seem to find an example of using an iterator over a basic table:

conf={
project_name="tenW1",
project_version=1.9,
base_dir="C:\\Users\\MyUser\\testing"
}

Perhaps you could also show safe type testing and access, or point to that in the examples/documentation?

**Comment by ThePhD** [comment]
There is no example of table iterators. Mostly, because they're kind of bad and useless anyhow (they're the weakest class of iterator, `InputInterator`).

All you need, however, is to invoke `begin()` and `end()` on the table like any other, or call `table::for_each`.

**Comment by RussellHaley** [comment]
My use case so far is to read in a lua conf file to an MDI gui in qt[1]. One possibility of displaying the conf file is to create a component per table entry. It would be nice to iterate over the table, create the components and create getters and setters back to the table (probably need a mutex?). Otherwise I need to know about the file structure ahead of time. 

Just for clarification: do you mean the implementation is "kind of bad and useless" or using iterators against sol2? Can you suggest a second pattern?
--------

[1] The use case for the MDI Gui is vague at best, but there is an example markdown editor in qt I'm going to turn into a project based application. As I mentioned, my C++ is shite so an example would greatly clear my path. 
The example project is here: https://github.com/RussellHaley/WinLua-Editor but the code is not up to date of of this writing.

**Comment by ThePhD** [comment]
Lua's iteration mechanism in the C API is based on your stack. So a lot of C++'s iterator guarantees cannot hold, making the iterators retrieved from `sol::table` (and other derived types) with `begin()` and `end()` more or less not-usable with many of the more sophisticated C++ stdlib algorithms.

BUT!

For iteration it works just fine:

````cpp
sol::state lua;
lua.safe_script("conf.lua");
sol::table conf_table = lua["conf"];

for (const auto& key_value_pair : conf_table ) {
     sol::object key = key_value_pair.first;
     sol::object value = key_value_pair.second;

     // inspect key/value, manipulate as you please
}
````

**Comment by RussellHaley** [comment]
Most appreciated. 👍  
> "...more or less not-usable with many of the more sophisticated C++ stdlib algorithms..."

Can you provide some examples of where I should not step?

**Comment by RussellHaley** [comment]
Okay, I see it now here:

https://github.com/ThePhD/sol2/blob/develop/examples/optional_with_iteration.cpp

I'll try adapting this...

**Comment by RussellHaley** [comment]
Example member function in qt. Assumes a string key and only numbers and strings for values.

void MdiForm::OpenLuaFile(const QString &path)
{
    std::cout << "=== opening a state ===" << std::endl;
    std::cout << path.toStdString();
    sol::state lua;
    // open some common libraries
    lua.open_libraries( sol::lib::base );
    try{
        lua.script_file(path.toStdString(), sol::script_default_on_error);

        sol::optional<sol::table> conf = lua["conf"];
        if(conf){
            for (const auto& key_value_pair : conf.value() )
            {
                sol::object key = key_value_pair.first;
                sol::object value = key_value_pair.second;
                std::string k = key.as<std::string>();
                sol::type t = value.get_type();
                switch (t) {
                case sol::type::string: {
                    std::cout << k << ": " << value.as<std::string>() << std::endl;
                }
                    break;
                case sol::type::number: {
                    auto v = value.as<double>();
                    std::cout << k << ": " << v << std::endl;
                }
                    break;
                default:{
                    std::cout << "hit the default case!" << std::endl;
                }
                }
            }
        }
    }
    catch(sol::error& err){
        std::cout << "oops: " << err.what() << std::endl;
    }
}
