### ISSUE TITLE
Distributing with Binary Lua

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#598]
Hello,

I have a Windows binary Lua distribution called [WinLua](http://github.com/winlua). Your library is sublime and I'd really like to add it to my installers. Is it enough to include the single/sol.hpp file (and license) or do you have a recommended distribution strategy?

I'm also the [Lua 5.3 maintainer on FreeBSD](https://www.freshports.org/lang/lua53) and don't see sol2 in our ports tree. I shall look to correct that in the future.
 
Cheers,
Russ

**Comment by ThePhD** [comment]
sol2 is a header only library, so just dropping the single in there is probably good enough.

There's a whole CMake distribution thing but I haven't battle-tested its install capabilities thoroughly, so I'd really just recommend putting the single inclusion header somewhere people can reach.

All of the licenses related to sol2 can be found at: http://sol2.readthedocs.io/en/latest/licenses.html

Just be wary: sol2 can have some edgecase bugs. I fix them pretty fast, but if something does break and they report it to you, do forward it to me so I can get on it right quick.

**Comment by RussellHaley** [comment]
Ha! I'll take that as a challenge to go find edge cases. 

For my edification: is it crazy talk to think about linking a static lib of lua with the sol2 header and create a dll?

**Comment by ThePhD** [comment]
That simply wouldn't work. The majority of sol2's API is built through what's known as Templates in C++. Templates must have their routine's source exposed to the user so that it can generate the code for any specific type. Therefore, the header is the only way to access and use sol2's API. There's nothing to export into a DLL: the header file must be shipped, and at that point whether someone is using a static lua library or a dynamic lua library doesn't matter.

**Comment by RussellHaley** [comment]
Lua 5.3 works great and only 1 include statement is needed to support lua in an application. I noticed however Lua 5.1.5 doesn't have a lua.hpp file. I'll build a test for 5.1 at some point but I need to update my installer for 5.1 first. Is there something I need to do to handle the missing file or does the sol2 library compensate? I only begrudgingly support 5.1.

**Comment by ThePhD** [comment]
I don't compensate: I expect someone to dump out a quick lua.hpp to fulfill the hole. (It's just `extern "C" { .. }` and then including all the headers.)

When `__has__include` becomes a reality of the C++ standard and is implemented across compilers I'll be able to do that without some magic.

**Comment by RussellHaley** [comment]
Er, I suppose I could have looked at the contents of the 1k file. tee hee. Thanks.

**Comment by RussellHaley** [comment]
https://github.com/WinLua/bin/wiki/Release-1#2018-03-01---1803a

Feel free to test. 👍
