### ISSUE TITLE
Scite 4.03

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#601]
Hi, 

I've been using the Scite text editor for a number of years now. It uses Lua as an automation tool, but I've often lamented it's stuck at 5.1. I did some research some time back and read that there is only one file that uses Lua but never followed it up because I didn't know the C api. 

With my shiny new light saber in hand (sol2), I started digging into the sources and found the aforementioned tale to be true. The sources build easily under VS2017 via nmake but I haven't created a project yet (I'm trying to learn qt creator). 

I'm going to take a crack at converting it to sol2. I've created an initial issue [here](https://github.com/RussellHaley/scite/issues/1) and will fill in the details later. The issue links to the header file. Is there any chance you are willing to help in the effort? I thought I'd ask because it's a reasonably high profile project and would provide good exposure to sol2.

As you are familiar with the C api, I would be looking to you to perhaps review the existing code and suggest how I would approach some of the larger items? Of course if you wanted to drop some code I wouldn't complain either. 

Cheers,
Russ

**Comment by RussellHaley** [comment]
It's already been converted. As per the scite website:

Version 4.0.0 is an unstable major release due to including unstable Scintilla 4.0.0.
Lua was upgraded to 5.3.

Russ

**Comment by ThePhD** [comment]
Hoorah for upgrades!

**Comment by RussellHaley** [comment]
I'm devastated. Fixing that has been on my bucket list for *years*. I can finally approach it and it got patched.   ;)

No worries, I'll find more. 👍
