### ISSUE TITLE
C2903 and C2760 when calling load_result

### ISSUE THREAD

**Issue by CaptainKrisu** [ThePhD/sol2#604]
1 Load a lua script with load_file as load_result variable
2 Use either () or call function on load_result variable
3 Errors!

Attempting to call a load_result variable returns C2903 and C2760 errors:
C2903 'call': symbol is neither a class template nor a function template [sol.hpp, line:19871]
C2760 syntax error: unexpected token '...', expected ';' [sol.hpp, line:19871]

Using Microsoft Visual Studio Community, version 15.6.0. 
C++ 17
Sol 2 v2.19.5

**Comment by ThePhD** [comment]
This is a compiler bug with VC++, a regression. I'll check in a quick fix to unblock you.

Sorry about this.

**Comment by ThePhD** [comment]
Fixed in latest.
