### ISSUE TITLE
Return type in try/catch for C++ function returning sol::object

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#605]
Hi, 
Given a C++ function that returns sol::object, what would I return from a catch statement? Put another way, can you help me solve for "MagicUnicorn" below?
 
sol::object BGState::runScript(QString script)
{
    try
    {
        return m_lua.script(script.toStdString(),
                                          sol::script_default_on_error);
    }
    catch (sol::error& err)
    {
        std::cout << "Oops: " << err.what() << std::endl;
        return new sol::MagicUnicorn();
    }
}

**Comment by ThePhD** [comment]
You shouldn't. Catch and crash: http://sol2.readthedocs.io/en/latest/errors.html#catch-and-crash

Or, handle errors properly with `sol::protected_function_result pfr = lua.script( ..., sol::script_pass_on_error );`, and then return `sol::object( lua, sol::lua_nil )` if it doesn't come out to what you expected. See https://github.com/ThePhD/sol2/blob/develop/examples/script_error_handling.cpp#L43 or https://github.com/ThePhD/sol2/blob/develop/examples/tutorials/quick_n_dirty/running_lua_code.cpp#L28 and

**Comment by RussellHaley** [comment]
Thank you, it's a little more clear now. 

From http://sol2.readthedocs.io/en/latest/errors.html#catch-and-crash
> Building Lua as C++ gets around this issue, and allows lua-thrown errors to properly stack unwind.

I'm having trouble finding reference on how to build Lua as C++? I assume it's very simple and I'm just not seeing it. I'll have to examine what the ramifications are on a purely windows environment; I had been wanting to try and preserve Lua as pure C but I am starting to question why.

**Comment by ThePhD** [comment]
Preserving Lua as C is purely an ABI / compatibility question, for the most part.

To build Lua as C++, you simply make sure each source file is processed as C++ instead of C when you build Lua. You don't have to do this with LuaJIT 2.1.0-beta3 or similar because it can build stack unwinding into itself.

**Comment by RussellHaley** [comment]
In NLua they seem to have renamed everything to cpp. Is that my only option to build lua as C++ in VS?
https://github.com/NLua/lua/tree/master/src

**Comment by ThePhD** [comment]
No, you just need to pass the correct compiler flag to make it build as C++. I believe that's `-x c++` for clang and gcc, and `/TC` for Visual Studio.
