### ISSUE TITLE
Compiling using c++17 flag

### ISSUE THREAD

**Issue by gomezkeane** [ThePhD/sol2#607]
When trying to compile my project using the std=c++17 flag on linux using g++ version 7.3.0 I get the following warning

In static member function ‘static sol::optional<std::variant<_Types ...> > sol::stack::check_getter<std::variant<_Types ...> >::get_empty(std::false_type, lua_State*, int, Handler&&, sol::stack::record&)’:
/home/jims/code/prototype/prototype/sol.hpp:9695:45: warning: typedef ‘T’ locally defined but not used [-Wunused-local-typedefs]
    typedef std::variant_alternative_t<0, V> T;

**Comment by ThePhD** [comment]
Sorry, just an oversight on my part.

**Comment by ThePhD** [comment]
Fixed in latest.
