### ISSUE TITLE
Wrong function gets called when registering table with lambdas

### ISSUE THREAD

**Issue by knorrest** [ThePhD/sol2#608]
The code below when compiled with gcc 7.3.0 produces the problem (MSVC works as it should)
The resulting output is then really strange:

_log_fatal: Some log entry...
log_fatal: Some log entry...
log_fatal: Some log entry...
log_fatal: Some log entry...
log_fatal: Some log entry...
log_fatal: Some log entry..._

so apparently the registration of methods fails somehow (or am I doing something really stupid..)

`TEST(LibraryTests, CallLogMethods)
{
	auto L = luaL_newstate();
	sol::state_view state(L);	

	sol::table table(state, sol::create);
    table.set(
		"log_fatal", [](const std::string& s) {std::cout << "log_fatal: " << s << std::endl; },
		"log_error", [](const std::string& s) {std::cout << "log_error: " << s << std::endl; },
		"log_warn", [](const std::string& s) {std::cout << "log_warn: " << s << std::endl; },
		"log_info", [](const std::string& s) {std::cout << "log_info: " << s << std::endl; },
		"log_debug", [](const std::string& s) {std::cout << "log_debug: " << s << std::endl; },
		"log_trace", [](const std::string& s) {std::cout << "log_trace: " << s << std::endl; }
	);
    state["rt"] = table;

    state.safe_script(R"(
		rt.log_fatal("Some log entry...")
		rt.log_error("Some log entry...")
		rt.log_warn("Some log entry...")
		rt.log_info("Some log entry...")
		rt.log_debug("Some log entry...")
		rt.log_trace("Some log entry...")
	)");
}`

**Comment by ThePhD** [comment]
This is the second 7.3.0 bug report I've had where things work bizarre. Was gcc 7.3.0 recently released or something...?

Either way, my GCC harness is absolutely busted right now so I can't repro anything specifically gcc related. I would try to see if you can use individual `.table.set` calls, or just do `table["log_X"] = { lambda here... };`. Maybe gcc will behave better than.

**Comment by ThePhD** [comment]
Finally got to investigate. Looks like a compiler bug...?

**Comment by ThePhD** [comment]
```
	auto L = luaL_newstate();
	sol::state_view state(L);

	sol::table table(state, sol::create);
	table.set(
		"log_fatal", [](const std::string& s) {std::cout << "log_fatal: " << s << std::endl; },
		"log_error", [](std::string s) {std::cout << "log_error: " << s << std::endl; },
		"log_warn", [](const std::string& s) {std::cout << "log_warn: " << s << std::endl; },
		"log_info", [](const std::string& s) {std::cout << "log_info: " << s << std::endl; },
		"log_debug", [](const std::string& s) {std::cout << "log_debug: " << s << std::endl; },
		"log_trace", [](const char* s) {std::cout << "log_trace: " << s << std::endl; }
	);
	state["rt"] = table;

	state.safe_script(R"(
	rt.log_fatal("Some log entry...")
	rt.log_error("Some log entry...")
	rt.log_warn("Some log entry...")
	rt.log_info("Some log entry...")
	rt.log_debug("Some log entry...")
	rt.log_trace("Some log entry...")
)");
```

With different signatures, the functions start to differentiate properly. It's time to investigate GCC and the standard...

My solution for you is to avoid the lambdas if possible.

**Comment by knorrest** [comment]
I noticed that too, and it really feels like a compiler bug. And sure, I can avoid lambdas, but I have loads of them in some places... Still, I really appreciate your quick replies!
I had an even stranger behaviour when I had a counter

auto dbg_counter = 0;
...
"log_debug", [](const std::string& s) {std::cout << "log_debug: " << s << std::endl; ++dbg_counter},
...
state.safe_script(R"(
	rt.log_debug("Some log entry...")
)");
ASSERT_EQ(dbg_counter, 1) 

The assert passed, but _log_fatal_ was printed...

**Comment by ThePhD** [comment]
I called the lambdas directly and they all print out the correct string and perform the correct action. This... bothers me, greatly.

**Comment by ThePhD** [comment]
What version of Lua are you using, perchance?

**Comment by knorrest** [comment]
I use the latest release - 5.3.4.

**Comment by ThePhD** [comment]
Long search later, found the issue.

You can fix this by doing `.set_function`, which will handle this case properly. If you use `set`, we have to assume it's a class, and thusly this problem can pop up. I'll add a note to the docs about registering things with `set` using multiple lambdas.

**Comment by knorrest** [comment]
Ok, I've fixed it by using set_function. I don't fully understand the problem though - was this purely a sol thing and not GCC related?

**Comment by ThePhD** [comment]
I added a note to the docs that not only points to this issue but also explains that using `set_function` gets around this limitation. Buyer Beware, I guess.

Sorry for the trouble, there's not much else I can do to make this work out without forcing RTTI on everyone.

**Comment by knorrest** [comment]
No problem, thanks for the explanation!
