### ISSUE TITLE
LuaJIT intergration with Sol2

### ISSUE THREAD

**Issue by felaugmar** [ThePhD/sol2#61]
Hi, i'm trying to use LuaJit intead of the standard lua,
I did compile the LuaJit and I used the lua51.lib generated from it on sol2.

But when I try to get: "jit.version" inside a script, doesn't work.
can anyone help-me?
I need a way to check if LuaJit is being used.

OBS: I did with the dll instead of static lib, but the same occurs.

**Comment by ThePhD** [comment]
That module is built into LuaJIT. If it's not showing up, you're not linking the right library / including the right headers. It's supposed to be immediately available whenever you open a luaL_newstate with luajit, or so the [documentation](http://luajit.org/ext_jit.html) says:

"The functions in this *built-in* module..."

**Comment by ThePhD** [comment]
Aww, crap.

So I went through the JIT sources just to make sure, and as it turns out you need to specificall `luaopen_jit` in order for this to be made available to you. I'm going to push this to the main branch to allow for it: it's a special function that comes with luajit and I didn't know it was even a thing.

**Comment by felaugmar** [comment]
Yes, it was that, after your first replay, i checked again and found this function.
Now it's working, thanks.

**Comment by ThePhD** [comment]
Good, good. I'll push my changes to the repo and allow you to open it using the lua_openlibraries function, like so:

![http://i.imgur.com/Smuum0d.png]

**Comment by felaugmar** [comment]
Nice, thanks and good job <3

**Comment by ThePhD** [comment]
It's [here now](https://github.com/ThePhD/sol2/releases). Happy coding.
