### ISSUE TITLE
unregister user types in sol2

### ISSUE THREAD

**Issue by zack-snyder** [ThePhD/sol2#610]
When you can register new types in sol2, how can I unregister them?
I searched the docs, but didn't found anything. Is it possible? When yes, how?

**Comment by ThePhD** [comment]
I do not have an "unregister" function. I probably should, maybe. I dunno.

**Comment by zack-snyder** [comment]
To give you a motivation for this:

I load a plugin; register the new type to sol2.
When I now want to unload the plugin, I need to remove it from sol2 too.
And only this type, not all of it.

**Comment by ThePhD** [comment]
Functionally, you can do this by setting the table-entry you created to `nil`. That effectively erases the usertype from existence, albeit the storage allocated for it might not die until a later GC cycle.

**Comment by ThePhD** [comment]
cf. #612
