### ISSUE TITLE
C2903, C2760 errors on MVSC

### ISSUE THREAD

**Issue by heliasi4** [ThePhD/sol2#611]
I wanted to continue working on a project of mine and updated my Visual Studio (since I need C++17 features) and suddenly got struck with the following errors: C2903, C2760.

sol\sol.hpp(14793): error C2903: 'call': symbol is neither a class template nor a function template
sol\sol.hpp(14793): error C2760: syntax error: unexpected token '...', expected ';
each referencing 4 times this very line.

and this huge thing:
```
\sol\sol.hpp(14798): note: see reference to function template instantiation 'decltype(auto) sol::proxy<sol::global_table &,const char (&)[9]>::call<,const std::string&>(const std::string &)' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\type_traits(16707566): note: see reference to function template instantiation 'decltype(auto) sol::proxy<sol::global_table &,const char (&)[9]>::operator ()<const std::string&>(const std::string &)' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\type_traits(1345): note: see reference to class template instantiation 'std::_Is_invocable_r<_Ret,_Fx,const std::string &>' being compiled
1>        with
1>        [
1>            _Ret=std::vector<std::string,std::allocator<std::string>>,
1>            _Fx=sol::proxy<sol::global_table &,const char (&)[9]> &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\type_traits(1357): note: see reference to class template instantiation 'std::_Conjunction<true,_First,std::_Is_invocable_r<_Ret,_Fx,const std::string &>>' being compiled
1>        with
1>        [
1>            _First=std::negation<std::is_same<sol::proxy<sol::global_table &,const char (&)[9]>,std::function<std::vector<std::string,std::allocator<std::string>> (const std::string &)>>>,
1>            _Ret=std::vector<std::string,std::allocator<std::string>>,
1>            _Fx=sol::proxy<sol::global_table &,const char (&)[9]> &
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\type_traits(1363): note: see reference to class template instantiation 'std::conjunction<std::negation<std::is_same<sol::proxy<sol::global_table &,const char (&)[9]>,_Function>>,std::_Is_invocable_r<_Ret,_Fx,const std::string &>>' being compiled
1>        with
1>        [
1>            _Function=std::function<std::vector<std::string,std::allocator<std::string>> (const std::string &)>,
1>            _Ret=std::vector<std::string,std::allocator<std::string>>,
1>            _Fx=sol::proxy<sol::global_table &,const char (&)[9]> &
1>        ]
```

This occurs when I try to build my project, I read #604, I used the _v2.19.5_ release of sol2, the latest commit 3f65ad43d8df47926f2c204ab8ee8aaf341763c7 and it always fails when I try to build my project.

_Microsoft Visual Studio Community 2017 
Version 15.6.2
VisualStudio.15.Release/15.6.2+27428.2005

Visual C++ 2017   00369-60000-00001-AA163
Microsoft Visual C++ 2017

Debugging Tools for Windows   10.0.16292.1001

Windows Driver Kit   10.0.16292.1001_

I hope this is sufficient, thanks for your time!

**Comment by ThePhD** [comment]
Chances are they just fixed the bug mentioned in #604 and now the patch I issued for before is now defunct. Lovely...

**Comment by ThePhD** [comment]
This is fixed now.

**Comment by heliasi4** [comment]
Sadly not on my end, lines changed, built with `single.py`:

sol.hpp(14925): error C2903: 'call': symbol is neither a class template nor a function template
sol.hpp(14930): note: see reference to function template instantiation 'decltype(auto) sol::proxy<sol::global_table &,const char (&)[9]>::call<,const std::string&>(const std::string &)' being compiled

**Comment by ThePhD** [comment]
Try the latest again, let me know how it goes.

**Comment by heliasi4** [comment]
Works splendid now! Thanks for your time.
