### ISSUE TITLE
Support for C++11 shared pointers?

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#613]
Hi, I am looking for a new Lua binding library that supports C++11 shared pointers for use in Leadwerks Game Engine 5:
https://leadwerks.com/5

Previously, we used tolua++. Does sol2 support shared pointers?

**Comment by ThePhD** [comment]
Yes. And it's infinitely extensible to other pointer types, from boost or your own custom library:

http://sol2.readthedocs.io/en/latest/api/unique_usertype_traits.html

**Comment by ThePhD** [comment]
To be specific: out of the box support includes `std::shared_ptr<T>` and `std::unique_ptr<T, Deleter>`.

**Comment by JoshKlint** [comment]
Thanks, shared_ptr is the only one I need.

I have a question about how shared_ptr objects are stored and collected. Let's say I have a function that returns an entity object. I assign an additional attribute to that object and then lose track of it on the Lua side, although it is retained in the engine. When I retrieve the same object again, will my values still be set? Should they? I am still trying to wrap my head around converting our engine to shared pointers.
```
local model = LoadModel("car.mdl")
local wheel = model:FindChild("wheel01")
wheel.friction = 20
wheel = nil
collectgarbage(collect)
wheel = model:FindChild("wheel01")
print(wheel.friction)--What gets printed here?
```

**Comment by ThePhD** [comment]
Assuming you have outfitted `Model` with the ability to absorb additional properties (no, this does not come for free with usertypes, it does not behave like a runtime-expandable dynamic object, but like the actual C++ class), then it will work.

If you do not bind something to handle `friction` before hand, that assignment will raise an error. If you want objects which can be dynamically added to, consider adding a storage table for dynamic properties: https://github.com/ThePhD/sol2/blob/develop/examples/dynamic_object.cpp#L10

**Comment by ThePhD** [comment]
Shared/unique mentions are now part of docs, to help people with this question in the future:

https://github.com/ThePhD/sol2/blob/develop/examples/unique_ptr.cpp
https://github.com/ThePhD/sol2/blob/develop/examples/shared_ptr.cpp

Best of luck on your project! Let me know how it goes.
