### ISSUE TITLE
Getting started exposing our API...

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#614]
I am starting to expose our API to Lua with sol2. I am using LutJIT 2.05 and Visual Studio 2017.

Here I set the first function:
```
lua = new sol::state();
lua->open_libraries();
lua->set_function("CreateWindow", static_cast<shared_ptr<Window>(*)(const std::string&, const int, const int, const int, const int, const int, shared_ptr<Window>)>(&CreateWindow));// differentiates between the Unicode and ANSI versions of the command
```

This is the function declaration in C++:
`extern shared_ptr<Window> CreateWindow(const std::string& title, const int x = 0, const int y = 0, const int width = 1024, const int height = 768, const int style = WINDOW_TITLEBAR, shared_ptr<Window> parent = NULL);`

Then I load and execute this script:
```
print("Starting...")
local window = CreateWindow("My Game",0,0,1024,768)
print("OK!")
```

When I run this I get a crash "Exception Unhandled", probably occurring inside the LuaJIT DLL:
> Unhandled exception at 0x00007FF8AD8D4008 (KernelBase.dll) in Leadwerks.exe: 0xE24C4A02.

The script works fine if I remove the call to CreateWindow(). I am guessing there is something else I have to do to make sol recognize those classes as arguments and as the return value?

**Comment by ThePhD** [comment]
Have you stepped into `CreateWindow` to see what is going wrong there?

**Comment by squeek502** [comment]
Not sure if this is the cause, but note that sol2 doesn't handle default parameters on its own (you need to bind overloads for each variation), so `shared_ptr<Window> parent` might be getting an unexpected value, since you don't provide that via the Lua call.

**Comment by ThePhD** [comment]
What @squeek502 said is true, too. That'll probably fix it for you!

**Comment by JoshKlint** [comment]
This is the way you can get errors:
`		try
		{
			lua->safe_script(source);
		}		
		catch (const std::exception& e)
		{
			Print(e.what());
		}`
