### ISSUE TITLE
Downcasting impossible?

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#615]
> Down-casting from a base class to a more derived type is, unfortunately, impossible to do.

https://github.com/ThePhD/sol2/blob/947945d098ad28a930f0fc7d028abc880c24836e/docs/source/api/stack.rst

Is this correct? If I have a class Entity and another class that extends it called Terrain, can I not get the Terrain object from the Entity object?
```
class Entity {};
class Terrain : Public Entity {}
```
```
local entity = world:GetEntity(0)
if entity:GetClassName() == "Terrain" then
      local terrain = Terrain(entity)
end
```

**Comment by OrfeasZ** [comment]
The excerpt from the documentation you quoted is talking about casting an object of type `Entity` to an object of type `Terrain`, which is not supported. If you want to support something like that you will have to provide your own mechanisms for it (ie. binding a C++ function that accepts `Entity` objects and casts and returns them as `Terrain` objects). 

On the opposite direction, granted your `sol::base_classes` are set correctly, you should be able to pass more specific types to methods or properties that accept a base type (ie. you should be able to pass an object of type `Terrain` to a function that accepts `Entity`).

**Comment by OrfeasZ** [comment]
For the specific example you provided, a solution would be to bind the constructor of your `Terrain` usertype as a factory function (see `sol::factories(...)`), and having one of your factories accept an `Entity` type. However keep in mind that you will have to do manual checks to validate whether the passed in object is indeed of type `Terrain`.

**Comment by JoshKlint** [comment]
No problem, as long as it is possible. I plan ti auto-generate my binding code once I figure out how it works manually. Thanks!

**Comment by OrfeasZ** [comment]
Yep, definitely possible. It's pretty much the same thing I've been doing for a while ;)

**Comment by JoshKlint** [comment]
> On the opposite direction, granted your `sol::base_classes` are set correctly, you should be able to pass more specific types to methods or properties that accept a base type (ie. you should be able to pass an object of type `Terrain` to a function that accepts `Entity`).

Without going into too much detail, this does not appear to be the case. Are you sure this is still valid? I am using the SOL_BASE_CLASSES and SOL_DERIVED_CLASSES macros.

**Comment by ThePhD** [comment]
`local terrain = Terrain(entity);` calls a function, which might be a constructor. It isn't necessarily a cast in Lua.

You can take "more derived" types by doing `Terrain*` and `Entity*` or `Terrain&` and `Entity&` as arguments, since that lets sol2 know you're asking for a reference, which means no slicing will happen.
