### ISSUE TITLE
Binding a function as a class method

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#618]
I plan to write a header parser that automatically generates all my Lua binding code for sol2. Part of this will involve creating extra functions for any method that accepts a shared_ptr as an argument, as well as new functions to mimic default arguments. For example, this class method:
```
void Entity::SetParent( shared_ptr<Entity> parent, const bool global = true)
```
Would result in the following two auto-generated functions:
```
void ENTITY_SETPARENT(Entity& self, Entity& arg1)
void ENTITY_SETPARENT(Entity& self, Entity& arg1, const bool arg2);
```
Is there a way to trick sol into treating ENTITY_SETPARENT like it is a class method that can be called like this in Lua?:
```
entity:SetParent(parent,true)
```

**Comment by JoshKlint** [comment]
I tried this and it actually works. Here's my original C++ method:
``class World
{
    void Render(shared_ptr<buffer> buffer);
}```
And here is my wrapper function:
```void SOL_WORLD_RENDER(World& world, Buffer& buffer)
{
	world.Render(dynamic_pointer_cast<Buffer>(buffer.Self()));
}```
Sol binding code:
```lua.new_usertype<World>("World", "Render", SOL_WORLD_RENDER);```

**Comment by ThePhD** [comment]
The lua code `obj:func( arg1, arg2, ... )` is actually identical to `obj.func( obj, arg1, arg2, ...)`. A free function which takes `self&` as its first member function is identical -- in Lua terms -- to a member function in C++.

So we don't force you to worry about it / care when bound.
