### ISSUE TITLE
Comparing shared_ptr values

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#619]
Consider the script below:
```
local a = CreateBox(world,1,1,1)
local b = CreateBox(world,1,1,1)

a:SetParent(b,true)
local c = b:GetChild(1) --returns a

print(a)
print(b)
print(c)
print(a==c)
```
This prints out the following:
> userdata: 0x1a9942c8
> userdata: 0x1a994308
> userdata: 0x1a9944e0
> false

But this is what I expect:
> userdata: 0x1a9942c8
> userdata: 0x1a994308
> userdata: 0x1a9942c8
> true

Here is a script that produces the desired output:
```
local a = CreateBox(world,1,1,1)
local b = CreateBox(world,1,1,1)
local c = a

print(a)
print(b)
print(c)

print(a==c)
```
So obviously it is comparing the shared pointers, and not the pointer stored inside. How can I change this behavior to the desired one?

**Comment by OrfeasZ** [comment]
You can define a custom equality check metamethod for your usertype:

```cpp
lua.new_usertype<Box>("Box",
    ...,
    sol::meta_function::equal_to, &Box::Equals
);
```
```cpp
bool Box::Equals(const Box& other) const
{
    return ...;
}
```

**Comment by JoshKlint** [comment]
Here is what I am trying:
```
	bool SharedObject::SOL_EQUALS(const SharedObject& o) const
	{
		return true;
	}
```
```
lua.new_usertype<SharedObject>("SharedObject", sol::meta_function::equal_to, &SharedObject::SOL_EQUALS);
```
But the function is never called by the derived classes.

**Comment by OrfeasZ** [comment]
Are you specifying all your base classes for derived types?

For example, say you have the following hierarchy:
```cpp
class A {};
class B : public A {};
class C : public B {};
```

When defining the `C` usertype you need to specify all base classes:
```cpp
lua.new_usertype<C>("C",
    sol::base_classes, sol::bases<A, B>()
);
```

**Comment by JoshKlint** [comment]
Yes, these are the relevant declarations:
```
lua->new_usertype<SharedObject>("SharedObject", sol::meta_function::equal_to, &SharedObject::SOL_EQUALS);
lua->new_usertype<Entity>("Entity_", "Destroy", &Entity::Destroy, "SetPosition", sol::resolve<void(const Vec3&, const bool)>(&Entity::SetPosition), "SetPosition", sol::resolve<void(const float, const float, const float, const bool)>(&Entity::SetPosition), "GetChild", &Entity::GetChild, "SetParent", SOL_ENTITY_SETPARENT, "GetParent", &Entity::GetParent, sol::base_classes, sol::bases<SharedObject>());
lua->new_usertype<Model>("Model_", sol::base_classes, sol::bases<Entity, SharedObject>());
```

**Comment by JoshKlint** [comment]
However, if I cast the entity to a model so A and C are both models, it works. The Model() function is a function that receives a shared_ptr<SharedObject> and returns a shared_ptr<Model>:
```
local a = CreateBox(world,1,1,1)
local b = CreateBox(world,1,1,1)

a:SetParent(b,true)
local c = b:GetChild(1) --returns a
c = Model(c)

print(a)
print(b)
print(c)
print(a==c)
```

**Comment by OrfeasZ** [comment]
Hm, maybe metatable functions such as these are not transferred down to base classes. @ThePhD

**Comment by JoshKlint** [comment]
I tried inserting the function at every level, and it still never gets called. Also tried making different versions for each class.

**Comment by JoshKlint** [comment]
It seems like it only works if the two objects being compared are of the same type.
- Model is derived from Entity
- CreateBox() returns a Model.
- GetChild() returns an entity.
- Model() is a function that casts a shared_ptr<Entity> to a shared_ptr<Model>
This works
```
local a = CreateBox(world,1,1,1)
local b = CreateBox(world,1,1,1)
a:SetParent(b,true)
local c = b:GetChild(1)
c = Model(c)
print(a==c)
```
This does not work:
```
local a = CreateBox(world,1,1,1)
local b = CreateBox(world,1,1,1)
a:SetParent(b,true)
local c = b:GetChild(1)
print(a==c)
```

**Comment by ThePhD** [comment]
From the docs, about [meta functions](http://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-automatic-meta-functions)

> heterogenous operators cannot be supported for equality, as Lua specifically checks if they use the same function to do the comparison: if they do not, then the equality method is not invoked; one way around this would be to write one int super_equality_function(lua_State* L) { ... }, pull out arguments 1 and 2 from the stack for your type, and check all the types and then invoke operator== yourself after getting the types out of Lua (possibly using sol::stack::get and sol::stack::check_get)

**Comment by ThePhD** [comment]
If `GetChild(1)` does not return a `std::shared_ptr<T>` that is identical to the `std::shared_ptr<T>` of `a`, then there is quite literally nothing I can do to invoke any function call on `==`. That's not my rules. I suspect that you're not using Lua 5.3, as the rules were changed to be more lenient and useful in 5.3.

Lua 5.1 `==` rules for override `sol::meta_function::equal_to` (`"__eq"`): 

> "eq": the == operation. The function getcomphandler defines how Lua chooses a metamethod for comparison operators. A metamethod only is selected when both objects being compared have the same type and the same metamethod for the selected operation.
>     function getcomphandler (op1, op2, event)
>       if type(op1) ~= type(op2) then return nil end
>       local mm1 = metatable(op1)[event]
>       local mm2 = metatable(op2)[event]
>       if mm1 == mm2 then return mm1 else return nil end
>     end

Lua 5.3 rules are simpler:
> __eq: the equal (==) operation. Behavior similar to the addition operation, except that Lua will try a metamethod only when the values being compared are either both tables or both full userdata and they are not primitively equal. The result of the call is always converted to a boolean.

5.3 doesn't compare the metatables. Which means in 5.3, you can return things that have different metatables and compare equals.

I should probably note this in my documentation to avoid user confusion...

**Comment by JoshKlint** [comment]
I am using LuaJIT for speed. Is there any realistic way to override the equals operator? A search for "super_equality_function" only shows your page linked above. Is that just a theoretical idea?

**Comment by ThePhD** [comment]
Really, none that I know of. The "super equality function" idea is purely a theoretical idea. I don't think you can patch the way __eq is handled through Lua code either: you'd need to modify LuaJIT or similar. There is a LuaJIT mailing list, I could ask there but I fear that the answer will be the same as the one here.

As a side note, you should probably define an `equals(a, b)` method and use that everywhere it matters. I know it's not intuitive and it certainly doesn't help your designers, but my hands are about as tied as yours here. `sol::meta_method::equal_to` is just never called, and only the most performance-costly, zany workarounds will make it happen.

... That workaround being, store a metatable inside your metatable, and then have lookup for function names done through an indirection table that switches on some unique identifier for the class. This will, of course, slow everything down UNIVERSALLY, for only the marginal benefit of having `__eq` work.

**Comment by JoshKlint** [comment]
So three options:
- LuaJIT and Equals()
- Lua 5.3 and ==
- LuaJIT and == hack
- Preprocessor that changes all occurances of T==Y to Equals(T,Y)
