### ISSUE TITLE
Get/Set functions as variable access

### ISSUE THREAD

**Issue by felaugmar** [ThePhD/sol2#62]
Hi again,
it's not really an issue,
but would be nice when creating a new usertype, can pass something like that:

`lua.new_usertype<Player>("Player", "hp", (&Player::GetHp, &Player::SetHp), "maxHp", (&Player::GetMaxHp, &Player::SetMaxHp));`

and when using it on lua, use like a normal variable
`hp = player.hp`
`player.hp = 5`

instead of this (or something like)
`hp = player.getHp()`
`player.setHp(5)`

--
This could be made without impacting the performance?
what you think about this?

**Comment by ThePhD** [comment]
It's already something I did in anticipation of this very request. Make sure you pull the latest or download the current 2.4.0 release, then do:
````
lua.new_usertype<Player>( "Player",
"hp", sol::property(&Player::GetHp, &Player::SetHp),
"maxHp", sol::property(&Player::GetMaxHp, &Player::SetMaxHp)
);
````

This should do what you desire. Let me know if anything funky happens: while we have tests for this, it was notoriously hard to implement.

**Comment by felaugmar** [comment]
oh, i didn't saw this, sorry.
well, worked like a charm, good job <3
