### ISSUE TITLE
meta_function::to_string and string ownership

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#620]
I've searched through the repository and documentation but I am having trouble finding a clear example of usage of the sol::meta_function::to_string meta function.

I am using the following function:
```
std::string SOL_VEC3_TOSTRING(const Vec3& v)
{
    std::string s = std::string(v.x) + ", " + std::string(v.y) + ", " + std::string(v.z);
    return s;
}
```
It appears from the behavior that the string is sometimes going out of scope before the print() command. My guess is the std::string is converted into a c_str() somewhere along the way. What is the correct way to return a string for this function?

**Comment by ThePhD** [comment]
That code is just kind of wrong. `std::string(number)` just creates a string of size `(int)v.x`, filled with '\0'.

Use `std::to_string` to convert your numbers, or any of the other stringifying-providers for your class.

**Comment by JoshKlint** [comment]
Yeah, that was just made up psuedo-code actually. I have my own string conversion functions.

But the point is, is it correct for this function to return an std::string?

The example here uses a totally different syntax:
https://github.com/ThePhD/sol2/blob/develop/examples/usertype_automatic_operators.cpp

**Comment by ThePhD** [comment]
As a side note, if you define a `to_string` free function, `to_string` member function, or `operator<<( std::ostream& os, const Vec3& v )` function, sol2 will pick that up and bind it automatically. Returning a `std::string` is just fine.

The internal conversion routine takes the `.data()` of the `std::string` and its `.size()`, and then pushes a `lua_pushstring(L, pointer, size)`. This copies the string data, byte by byte.

**Comment by JoshKlint** [comment]
Yeah, it works about half the time and the other half of the time I get these kinds of messages:
```
Lua Error: sol: runtime error: An unknown error has triggered the default error handler
stack traceback:
        [C]: in ?
        [C]: in function 'print'
        [string "C:/Users/Josh/Documents/Leadwerks/Projects/Le..."]:45: in main chunk
```
This looks like some random memory overwrite to me, which might be something on my end.

**Comment by JoshKlint** [comment]
I can confirm the error had to do with my pointer to string conversion. Our 64-bit build is new and untested and the pointer conversion works differently.
