### ISSUE TITLE
Copying Objects

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#621]
I think this is my last issue to investigate.

Here is my Vec3 class:
```
lua->new_usertype<Vec3>("Vec3_", "x", &Vec3::x, "y", &Vec3::y, "z", sol::meta_function::to_string, &Vec3::ToString);
lua->set_function("Vec3", CreateVec3);
```
I fake a C++ style constructor with this function:
```
Vec3 CreateVec3(const float x, const float y, const float z)
{
    return Vec3(x,y,z);
}
```
When I run this script:
```
v1 = Vec3(1,2,3)
v2 = Vec3(1,2,3)
v3 = v2

v3.x = 69 --modifies v3 AND v2
print(v1)
print(v2)
print(v3)
```
The output is this:

> 1.000000, 2.000000, 3.000000
> 69.000000, 2.000000, 3.000000
> 69.000000, 2.000000, 3.000000

I would expect the output to be this:
> 1.000000, 2.000000, 3.000000
> 1.000000, 2.000000, 3.000000
> 69.000000, 2.000000, 3.000000

Is there any way I can make the = operator make a copy of simple objects like this?

**Comment by ThePhD** [comment]
Unfortunately, no. Your copies MUST be explicit. You can bind a copy constructor so you can do Vec3(v1): otherwise, it will not copy. Lua uses reference semantics throughout. You need to explicitly return a new object through a Lua-bound C++ function.

**Comment by JoshKlint** [comment]
It looks like we actually get the exact same behavior in our current engine so that’s fine.

**Comment by JoshKlint** [comment]
I actually kind of like how Lua just puts its foot down and says “No, it always works the same one way”.  It makes it so you don’t have to remember much to use the language.
