### ISSUE TITLE
std::remove doesn't modify exposed std::vector

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#622]
I'm not sure if this is meant to be supported or not, but I found that when using std::remove() to remove a vector element, the changes weren't visible on the Lua side:
```
std::remove(oldparent->kids.begin(), oldparent->kids.end(), Self() ); // does not work with sol
```
I had to change it to this:
```
for (auto it = oldparent->kids.begin(); it != oldparent->kids.end(); it++)
{
	if ((*it) == Self())
	{
		oldparent->kids.erase(it);
		break;
	}
}
```

**Comment by ThePhD** [comment]
Vectors are serialized as userdata. They are copied unless you explicitly return or set them into Lua as a reference.

**Comment by JoshKlint** [comment]
So is something like this inefficient? "kids" is a C++ class member that is an std::vector:
```
for n = 1, #entity.kids do
    local child = entity.kids[n]
end
```

**Comment by JoshKlint** [comment]
Okay, this is actually the correct code and it works fine with sol:
```
oldparent->kids.erase(std::remove(oldparent->kids.begin(), oldparent->kids.end(), dynamic_pointer_cast<Entity>(Self())));
```
The design of the remove function seems bizarre to me, but I never use it.
