### ISSUE TITLE
C2903, C2760 errors on MVSC v15.6.6

### ISSUE THREAD

**Issue by Joxno** [ThePhD/sol2#626]
I seem to be having similar issues as mentioned in #611 

```
sol.hpp(14950): error C2903: 'call': symbol is neither a class template nor a function template
sol.hpp(14950): error C2760: syntax error: unexpected token '...', expected ';'
```
After rewriting line 14946, 20158 to simply check if _MSC_FULL_VER is defined instead of also checking the value.
`#if defined(_MSC_FULL_VER)`
I was able to get the project compiling and functioning.

Microsoft Visual Studio Community 2017
Version 15.6.6
/std:c++17

Sol2 Single Header 
Revision 612c123

Cheers!

**Comment by ThePhD** [comment]
I guess I'll just keep bumping the version until it gets fixed in MSVC. The worst part was, it was fixed before the versions listed.... sigh.
