### ISSUE TITLE
Python ctor syntax support

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#634]
Hi,

I would like to support the python syntax for ctor for readability purpose.

Here is an example
`local knob = Knob{"knob", 0.8, 0, 1, bounds={20, 20, 48, 48}, stripImage = "knob_48x48x101.png"}`

where the default ctor for Knob takes one string and 3 floating values
and I have two member property bounds and stripImage.

Right now I declare Knob with this
`, sol::call_constructor, sol::factories(&Knob::from_args, &Knob::from_lua_table)`

```
  static Knob* from_lua_table(sol::this_state ts, sol::table args)
  {
    auto *pKnob = new Knob(args.get<juce::String>(1), args.get<float>(2), args.get<float>(3), args.get<float>(4));

    sol::state_view lua = ts;
    args.for_each([&](sol::object const& key, sol::object const& value)
    {
      if (key.get_type() == sol::type::string)
      {
        sol::function func = lua[key];
        func(pKnob, value);
      }
    });
    return pKnob;
  }

  static Knob* from_args(const String &name, float defaultValue, float min, float max)
  {
    return new Knob(name, defaultValue, min, max);
  }
```
Currently, from_lua_table implementation do not work and I was wondering what would be the right way to call function using the lua state view using an sol::object.
Or another way to make this syntax works.
In our previous LuaBind implementation, this feature was implemented in Lua but I was wondering is this possible to do without headache in c++ as well.

Thanks !

**Comment by ThePhD** [comment]
Your implementation seems fine, except for the center bit:

````
    sol::state_view lua = ts;
    args.for_each([&](sol::object const& key, sol::object const& value)
    {
      if (key.get_type() == sol::type::string)
      {
        sol::function func = lua[key];
        func(pKnob, value);
      }
    });
````

This part seems wrong. You're asking for a `sol::function` from the `key` in the table.... none of the named arguments you pass in are a function: they're all tables. So this code would crash with a helpful message (if you enabled `SOL_CHECK_ARGUMENTS`, which you should in any debug build).

You know your named arguments, in advance. No reason to make this hard on yourself with a generic for loop:

````
sol::optional<sol::table> maybe_bounds = args["bounds"];
if (maybe_bounds) {
     sol::table& bounds = *maybe_bounds;
     // do whatever to access 1, 2, 3, 4
}

sol::optional<std::string> maybe_stripImage = args["stripImage"];
if (maybe_stripImage) {
     std::string& stripImage = *maybe_stripImage;
     // do whatever with it
}
````

And so-on, so-forth.

**Comment by otristan** [comment]
Well, I want to support all possible arguments that bind to any functions so the explicit check of all properties is not really an option :)
stripImage and bounds are actually defined function

`, "stripImage", sol::property(&Knob::setStripKnobImage)`
` , "bounds", sol::property([](Component &comp, sol::table bounds) { comp.setBounds(bounds.get<float>(1), bounds.get<float>(2), bounds.get<float>(3), bounds.get<float>(4)); })`

but maybe I should somehow prefix those with the class name.
I know I am asking something quite exotic

**Comment by ThePhD** [comment]
Oh, my. I just realized you are using the factory methods, not `initializer`s.

There are also other problems with your approach.

By returning a raw pointer, sol2 will not properly delete things for you. Raw pointers do not indicate the ownership pattern you want. You should be returning a `std::unique_ptr`, or if `juce` has its own version then you can return that provided you [hook up a unique_usertype specialized to it](http://sol2.readthedocs.io/en/latest/api/unique_usertype_traits.html). Ownership is talked about in the [tutorials](http://sol2.readthedocs.io/en/latest/tutorial/ownership.html).

For the rest of the things...

You cannot activate properties or bindings without going through the proper syntax _in Lua_. If you need to access them through your constructor/initializer/etc. you need to parse out what you need manually from your tables and hand it to the right C++ functions, _or_ you need to create a bunch of (C++-accessible) functions to do that work for you.

**Comment by otristan** [comment]
In that case I will go on using the default call_constructor so I don't bother with unique_ptr if not required
`, sol::call_constructor, sol::constructors<Knob(const String&, float, float, float)>()`

For the rest of things, this seems to be a real pain in that case so I'm going to skip trying to do this in c++ :)

Thanks for your input !
