### ISSUE TITLE
sol::optional<sol::function> aborts when constructed from non-function

### ISSUE THREAD

**Issue by ahoischen** [ThePhD/sol2#638]
I am trying to safely call a function in a table. From the [reading variables tutorial](http://sol2.readthedocs.io/en/latest/tutorial/variables.html#id3) I expected sol::optional to be nullopt when the given value cannot be converted to the contained type. However, the following program causes an abort when assigning func.

```C++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "sol.hpp"

TEST_CASE("optional<function> is created from integer") {
    sol::state state{};
    sol::table table = state.create_table_with("func", 42);
    sol::optional<sol::function> func = table["func"]; // SIGABRT
    REQUIRE(func == sol::nullopt);
}
```

```
An error occurred and panic has been invoked: stack index -1, expected function, received number: must be a function or table or a userdata (type check failed in constructor)
```

Storing lookup results in `sol::optional<sol::function>` works fine in cases where the value is either `nil` or a function, however, it breaks for values of other types. A possible workaround would be to do the lookup and invocation through a safe_script call, however I would like to avoid invoking the parser in this code. This abort should at least be documented in the linked tutorial section, since it is not intuitive from the given examples.

I am using Lua 5.3.4 (compiled as C), Sol 2.20.0, Catch 2.1.0 and C++17. My compiler is g++ 7.3.0 and I'm on Linux. Code is compiled using CMake with `CMAKE_BUILD_TYPE=Debug`. Compiling in release mode doesn't print the error message but Catch reports that the `REQUIRE` fails.

**Comment by ThePhD** [comment]
Yeah, there seems to be some problems around `sol::optional` that I need to look into. I'm at a conference right now, so this will be solved a little bit later.

Sorry about this! As a work around, you can pull out `sol::object` and then use `obj.as<>` to convert after doing an `is<>` check. It's ugly, but it's just a workaround for the next few days if you really need to get going. I would suggest putting it inside of a function so you can tear it out in a few days.
