### ISSUE TITLE
Crash in usertype_metatable::core_indexing_call caused by misaligned access to usertype_metatable

### ISSUE THREAD

**Issue by xobkcalb** [ThePhD/sol2#641]
Sample code:
```c++
struct Base {};
struct Derived : Base {};

template <typename SelfType>
struct LambdaWrapper {
   void operator()(SelfType& self, sol::object param) const {}
   std::function<void(SelfType&, float)> lambda;
};

void crash(sol::state lua) {
    lua.new_usertype<Base>("Base",
       "x", sol::writeonly_property(LambdaWrapper<Base>{})
   );
   lua.new_usertype<Derived>("Derived",
       sol::base_classes, sol::bases<Base>()
   );

   Derived d;
   lua["d"] = d;

   lua.safe_script("d.x = 5"); // crash
}
```

It seems that sol2 uses a `usertype_metatable<T, ...>` userdata, stored under `usertype_traits<T>::gc_table()` key *(a rather misleading one, I should say)* in the global table, as a fallback for finding members that an object gets from its base classes. On my system, the default memory allocator allocates 8-byte aligned blocks. Most of the time, class `usertype_metatable<T, ...>` is, too, 8-byte aligned, and everything works perfectly.

But in some use-cases compiler decides to make this class (which, for the example above, is `sol::usertype_metatable<Base, std::__1::integer_sequence<unsigned long, 0, 1, 2>, char const (&)[2], sol::property_wrapper<void, LambdaWrapper<Base> >, char const (&)[4], sol::constructor_list<sol::types<> > &, char const (&)[5], const sol::destructor_wrapper<void> &>`) aligned to 16 bytes, and then everythng goes to hell.
1. When the time comes, `pusher<usertype_metatable<...>>::make_cleanup(...)` creates the `usertype_metatable` on Lua's userdata: `stack::push<user<umt_t>>(L, metatable_key, uniquegcmetakey, std::move(umx));`
2. Userdata is created aligned to 8 bytes, but not 16 bytes, and, somewhere deep inside, `user_allocate()` pads the userdata and adjusts the actual beginning of the created object by 8 bytes.
3. Despite the userdata pointer being misaligned, `umt_t& target_umt = stack::pop<user<umt_t>>(L);` still works and gives the correct (adjusted by 8 bytes from the userdata beginning) object. Everything works, for now.
4. `"d.x = 5"` looks for member `"x"` inside `d`'s metatable of `"Derived"` via `usertype_metatable<...>::core_indexing_call()`, doesn't find it, and tries to look via `f.newindexbaseclasspropogation(L, found, ret, accessor);`, which in turn calls `walk_single_base()`. And finaly, `walk_single_base()` gets our misaligned userdata `stack::get_field<true>(L, gcmetakey);` and calls `int value = basewalkfunc(L);` which is actually another `usertype_metatable<...>::core_indexing_call()`, but this time with template parameter `toplevel = false`.
5. Inside we call `usertype_metatable& f = toplevel ? ... : stack::pop<light<usertype_metatable>>(L);`, and get misaligned result (starting from the userdata beginning instead of beginning + 8 bytes), and after that usually `auto memberit = f.mapping.find(name);` crashes the application.
6. Wow that was a lot of text.

My system is an iMac Pro 2017 with MacOS High Sierra:
```
$ uname -a
Darwin DS.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

My compiler is:
```
$ /Library/Developer/CommandLineTools/usr/bin/c++ --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
*(wow, it's so very useful not to know which actual LLVM version I am using, ~~fuck you~~thank you, Apple!)*

Versions affected: I've found this bug on v2.19.0, v2.20.0 seems to be affected too.

And by the way, thank you for your library of pure awesomeness!

**Comment by xobkcalb** [comment]
It further seems that the start of Lua's userdata (pointer returned from `lua_newuserdata()` call) is `0x28` bytes from the beginning of the corresponding allocated memory block, so "more aligned" memory allocation won't help with it...

**Comment by xobkcalb** [comment]
I've tried to add `memory = detail::align_user<T>(memory);` to the `getter<light<T>>` specialization, and it helped:
```
template <typename T>
struct getter<light<T>> {
    static light<T> get(lua_State* L, int index, record& tracking) {
        tracking.use(1);
        void* memory = lua_touserdata(L, index);
        memory = detail::align_user<T>(memory); // TODO: fixed?
        return light<T>(static_cast<T*>(memory));
    }
};
```

No idea what this might cause though...

**Comment by ThePhD** [comment]
This is going to take me a while to debug.

Not sure if using the alignment there is the right call. I'll look into the code.

**Comment by ThePhD** [comment]
Alright, it works on my machine, so it's going to be infinitely harder to debug, lovely.

Nevertheless, the values of the addresses do look wrong. I was almost certain this was taken care of because we ran ASAN over everything when first implementing alignment.

**Comment by ThePhD** [comment]
This is now fixed. Grab the updated 2.20.0
