### ISSUE TITLE
Adding state to vector.

### ISSUE THREAD

**Issue by Oen44** [ThePhD/sol2#642]
I was looking for a way to create add-on system for my future projects and wanted to try with Lua and Sol2. Unfortunately I have ended up with error when adding lua states to vector.
Error:

	'sol::state::state(const sol::state &)': attempting to reference a deleted function
	c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0

I'm using Visual Studio 2015.

	#define SOL_CHECK_ARGUMENTS 1
	#include "sol\sol.hpp"

	#include <vector>
	#include <string>
	#include <iostream>
	#include <filesystem>

	namespace fs = std::experimental::filesystem;

	std::vector <sol::state> luaStates;

	int main()
	{
		std::string scriptsPath = "Lua Scripts";
		for (auto & p : fs::directory_iterator(scriptsPath)) {
			std::ostringstream oss;
			oss << p;
			std::string path = oss.str();

			sol::state lua;
			lua.open_libraries(sol::lib::base);
			lua.script_file(path);

			luaStates.push_back(lua); // Error
		}

		return 0;
	}

**Comment by ThePhD** [comment]
`sol::state` is move-only. You need to `std::move` it. You cannot copy a state because there is no well-defined copy operation for one state to another.
