### ISSUE TITLE
Custom exception Handling

### ISSUE THREAD

**Issue by dudztroyer** [ThePhD/sol2#643]
Hey, 

Again, after more than extensive 4 hours reading and filtering through the docs and other issues, I've got a issue I cant figure out how to do it.

I have some functions that after executed I would like to stop running any script. After researching some things and trying others, the one which actually got solving my problem was throwing an exception to kick off the try and catch of my state::script(string).

````
	sol::table Walker = lua.create_named_table("Walker");

	Walker.set_function("GoLabel", sol::overload(
		[](std::string Label) {
		pugi::xml_node point = CGUI::m_stGUI->p->cWalker->GetNodeFromLabel(Label);
		if (!point.empty()) {
			CGUI::m_stGUI->p->cWalker->m_CurrentPoint = point;
			throw ScriptException::SE_Stop;
		}
		else {
			throw ScriptException::SE_WalkerNoLabel;
		}
	},
		[](std::string Label, bool stopOnNoPoint) {
		pugi::xml_node point = CGUI::m_stGUI->p->cWalker->GetNodeFromLabel(Label);
		if (!point.empty()) {
			CGUI::m_stGUI->p->cWalker->m_CurrentPoint = point;
			throw ScriptException::SE_Stop;
		}
		else if (stopOnNoPoint) {
			throw ScriptException::SE_WalkerNoLabel;
		}
	}
	));
````

This is the function I'm calling. I've even tryied execute a state::script(string) inside the lambda but the refference would not be there, since this lambdas is inside a Setup function on a ScriptManager class.

This is how I call the scripts:

````
ScriptException CScriptManager::Do(CScriptBase* script, lua_State * st) {
	script->m_Started = true;
	script->m_Ended = false;
		try {
			auto rn = ((st == nullptr) ? lua : (script->thisThread.state())).script(script->m_Script);
			script->m_Ended = true;
		}
		catch (const sol::error& e) {
			script->m_Ended = true;
			std::string error = e.what();
			p->cLog->Log("Script error: " + error, "SCRIPT");
			script->returnValue = -1;
			return ScriptException::SE_Error;
		}
		catch (ScriptException exc) {
			script->m_Ended = true;
			script->returnValue = -1;
			switch (exc) {
			case ScriptException::SE_Stop:
				break;
			case ScriptException::SE_WalkerNoLabel:
				p->cLog->Log("Script used GoLabel to unknown point, stopping walker", "SCRIPT");
			case ScriptException::SE_WalkerOFF:
				p->cSettings->m_Settings.child("Settings").child("Walker").child("Status").attribute("value") = false;
				p->cGUI->UpdateSettingsTree();
				break;
			}
			return exc;
		}
		return ScriptException::SE_Ok;
}
````

Ok. The thing is, whenever I throw my ScriptException, it gets translated as a sol::error, with an unknown error and traceback information(SOL_CHECK_ARGUMENTS). Is there a way to bypass this and add a custom exception handling?

Out of this errors, I've tryied SOL_EXCEPTIONS_SAFE_PROPAGATION,  and a few other solutions, but no success.

Is there a way to inside the lambda stop the execution of the script? I would try sol.script("do return end"), but since I do not get the sol reference I cant do it. I've tryied passing "[this]","[sol]", "[&]", "[=]", "[&sol = sol]" and a few others, but seems like I really cant reference a member from that function. I know this is C++ related, but could potentially solve my issue.

Thanks again.

**Comment by ThePhD** [comment]
So there's a number of places where you can entirely override the default exception handlers and behavior of throws for sol2.

sol2's throwing mechanisms being overridden are covered here: 
sol2.readthedocs.io/en/latest/exceptions.html#exception-handling

You can also override the `at_panic` functions as well, and handle throwing and panicking on your own.

**Comment by dudztroyer** [comment]
I've taken a look on that, but seems like Lua only throws string related exceptions, but I'm looking into a better way to separate the default lua exception without any kind of string comparision. 

Probably if I would do any string comparision I could just build a sol::error

**Comment by ThePhD** [comment]
If you want to early-exit a script that is running, use coroutines and yield.

Lua throws string errors when you use `error()`. When you `throw`, sol2 catches these errors in the trampoline and calls the default exception handler. You can register your own exception handler and serialize the errors however you like: you can `sol::stack::push` your own exception object, or a string, or some arbitrary 3rd thing: as long as you respect that after your handler gets called that I will call `lua_error(L);` and send your error on up the Lua stack.

Of course, you don't have to do this. You can simple call `throw` in your handler to re-throw through the Lua C API. Of course, if you throw through the C API you will probably absolutely destroy your stack, and otherwise obliterate your ability to run the program correctly beyond that point (and likely crash without a perceivable error).

**Comment by ThePhD** [comment]
For what it's worth, you should probably not be checking errors using exceptions in this case. Many scripts fail for many reasons and it's very unlikely you need that information in-full: you would be infinitely better off using `.safe_script(...);` to run your script safely. When an error gets reported through the `sol::protected_function_result` return value, you can inspect that and also any information on the type when converted to `sol::error` (or perhaps your own serialized exception type).

**Comment by dudztroyer** [comment]
I was travelling and could not get into it until now. Sorry for the delay on feedback.

I've actually just cornered out the need of the script exit, making it on a single function throwing an standard string. Just in case the user really wants to abort, not forcing it abort on a custom function. Also this is good to avoid messing with the standard sol::error parser.

````
lua.set_function("StopScript",[&]() { throw "StopScript executed"; });
````

This solved the problems and I actually dont needed anything other than this. 

But i've looked into coroutines and yield but could not get the difference between sol::threads... I'll write a new issue because it is out of this scope of question.

**Comment by ThePhD** [comment]
Throwing strings themselves is a bad, bad idea....

... But! You're free to do as you wish.

**Comment by dudztroyer** [comment]
Well, other than throwing and creating some "complex"(to me is complex lol) coroutines, what would be another option to just abort the execution? 

The reason I would like this behavior is because I cant be sure that the regular user will use a working logic.

I'll take a deeper look on the safe_script and try to adjust on that. But i'm open to suggestions hehe

**Comment by dudztroyer** [comment]
By the way @ThePhD, I've been looking into this and I've noticed there are several other ways to finish the script execution prematurely from inside the Lua script.

Now I've been looking into adding some kind of force-kill to any script running for more than X seconds.  I've already built the framework to handle it but I could not get any success stopping from a running script executed from a ``sol::thread``. I've tryied again throwing any error from simple ``luaL_error`` or ``lua_error`` but it actually crash the program. Is there anything I can do to accomplish this? 

Since while the script is being run the calling thread is blocked, I spawn another worker to deal with this, but looks like doing this async is causing the crashes...

````
luaL_error(script->thisThread.thread_state(), "Forcing finish of script.");
````

**Comment by ThePhD** [comment]
Lua is not asynchronous in the slightest. a `sol::thread` is not a C++ thread or a POSIX Thread or a Windows Thread:  it is a chunk of stack space, because that is what Lua defines as a Thread. Lua (and sol2) are not thread safe: you must synchronize and properly cancel, or risk absolutely destroying the VM in which you do Asynchronous calls.

**Comment by dudztroyer** [comment]
That is what I've read about on other issues... But the ``sol::thread`` is just for defining new environment for sub-scripts. 

The async I said is because I execute several of those sub-scripts within a loop every X ms, one of them might get stuck(user making mistakes on a infinite while loop or something). Since this would be a problem for the subsequent scripts, I call std::async and run the script from there, noting the start time, setting a flag before the script start and after the script ends, so I can keep track and not repeatdly start a script before it ends. 

So, when forcing that script execution, I get the sol::thread state and call an error, from another c++ thread.  Actually there is no race conditions since it would act as just a timer to force stop... Which I'm not able to do.

The ultimate reason of this is not actually killing one long-running script, but killing all the scripts with their sol::threads bound to the same sol::state member from the Script Manager parent class, whenever the user resets the global program settings. I could wait until each one of them stops executing, but that would cost some time in case one script is really bad in its own logic. Instead, forcing it to stop looks like a way around it.

https://github.com/ThePhD/sol2/issues/69 -> Looks like i'm getting into this situation, but it is actualy slightly different, since I am using state_view, not just a state.

What i'm looking like is what this user accomplished in lua and asking the same to do in jerryscript -> https://github.com/jerryscript-project/jerryscript/issues/1356

**Comment by ThePhD** [comment]
`std::async` is not required to run on a separate C++ thread. It can run in the same thread. Its choice for doing this is arbitrary and out of your control.

> So, when forcing that script execution, I get the sol::thread state and call an error, from another c++ thread. 

That's exactly illegal, and I'm surprised your code has not crashed sooner and harder.

You cannot safely take down a user script that has been running for too long without endangering the entire lua state. You need to create a separate `lua_State` (`sol::state`) for C++ thread. Sharing states between C++ threads is a recipe for disaster. Calling `luaL_error` or `lua_error` on a _currently running state_ that did not agree to call either of those is exactly the bad thing to do.

Either force your user to check in with a function on each iteration / step of their work, or take your hands out of it. If you want to bring down the whole state asynchronously, Lua does not have primitives for that. This honestly sounds like something you should ask on Lua's mailing list.

**Comment by dudztroyer** [comment]
It's not in production yet, just messing around and trying to get into it... See the boundaries and find a way that "works", even if it is sort of pasta code lol After that i'll optimize and make it safe.

> So, when forcing that script execution, I get the sol::thread state and call an error, from another c++ thread.
I meant that this is what i'm trying to do, but when doing this it crashes. Now I understand why...

By "force" you would mean a hook? Or just telling users to call a "timeout" function every here and there? 

Just to sum up: so there is no way to "clear" nor "reset" a lua::state while a script is running? Either I wait for it to terminate or I'm likely going to crash?

**Comment by ThePhD** [comment]
sol2 doesn't have an abstraction for this: you can write something that uses `luaL_hook` and then kills the script when the hook gets called and the "kill me" flag it set: 

https://www.lua.org/pil/23.2.html

https://stackoverflow.com/questions/4721548/how-do-i-use-lua-hooks-to-find-out-the-name-of-the-currently-running-function

I haven't used them much but other people use them extensively. Hooks add overhead, but maybe that overhead won't matter for you.
