### ISSUE TITLE
Issue with returning shared_ptr<const T> in call constructor

### ISSUE THREAD

**Issue by hzwar** [ThePhD/sol2#644]
Hi,
the test below fails with
```
[string "..."]:3: attempt to index a sol.sol::detail::unique_usertype<const Foo> value (global 'foo')
stack traceback:
	[string "..."]:3: in main chunk
```
The reason is that I'm returning a shared_ptr<*const* T> in the call constructor. Removing the const makes the test pass but obviously creates an object of a different qualified type. To workaround that I used nasty std::const_pointer_cast's in other parts of the bindings in order to "talk non-const" i.e. not being const-correct.
Thanks for looking into it!

Sol v2.20.0 and latest develop, Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0. macOS 10.13.4.
```
TEST(Sol, ConstUsertype)
{
    struct Foo
    {
    };

    sol::state lua;
    lua.open_libraries(sol::lib::base);
    lua.new_usertype<Foo>("Foo",
                          sol::call_constructor,
                          sol::factories([&]() {
                              return std::make_shared<const Foo>();
                          }), // removing const above passes test
                          "bar",
                          [] { return 42; });

    auto script = R"(
foo = Foo()
return foo:bar()
                  )";
    auto result = lua.script(
        script, [](lua_State*, sol::protected_function_result pfr) { return pfr; });
    EXPECT_TRUE(result.valid());

    if (result.valid())
    {
        int bar = result;
        EXPECT_EQ(bar, 42);
    }
    else
    {
        sol::error error = result;
        std::cerr << error.what() << "\n";
    }
}
```

**Comment by ThePhD** [comment]
Looks like I'm not applying `std::remove_cv` on the internal `unique_usertype` value. Thanks for catching this.

As a side note: I have not thoroughly vet sol2 for const-correctness. In fact, usertypes -- when you push a `const` version of something -- do not keep the internal version const-qualified, nor do we generate a const version of the metatable.

This is something I'm targeting to fix with v3.

**Comment by hzwar** [comment]
Big thank you!! No more const casts here ;-)
btw: just read your slides from C++ Now, very nice. Reg. the compile time/bloat I can only encourage users to have small units plus ccache/ninja or similar. No problems at all.
Cheers

**Comment by Ryu204** [comment]
Hello. Does sol3 guarantee mutating a const reference returned from a bound C++ function in lua code to be a hard runtime/compile error? I was not able to find related information on the topic on sol3 docs.
