### ISSUE TITLE
get<sol::optional<sol::table>> fails when there's no table (nil value)

### ISSUE THREAD

**Issue by noGithub-oO** [ThePhD/sol2#646]
When calling `get<sol::optional<sol::table>>` on a `sol::table`, I get runtime errors regarding type check failures when there's no value assigned to given key (index). Everything works OK unless it enters table constructor and passes `nil` inside of it. Looks very similar to #638. You can use the same code, just replace `sol::function` with `sol::table` and use some non-existent key with `get<>` lookup.

Latest sol (2.20) and latest msvs (15.7.1) as of the time of writing, with lua 5.3.

**Comment by ThePhD** [comment]
Sorry about that. There's multiple places where I have to optimize optional's getter, so I missed a few.

I think this should cover them all. Grab the latest: https://github.com/ThePhD/sol2/releases/tag/v2.20.1

Thanks for using sol2!
