### ISSUE TITLE
Another conditional_t implementation to reduce template instantiations

### ISSUE THREAD

**Issue by Morwenn** [ThePhD/sol2#647]
I know that you like details, compile-time improvements and such, so here is a simple reimplementation of `std::conditional_t` taken from [this article][1] which generates fewer template instantiations than the standard implementation (by virtue of only being instantiated for `conditional<true>` and `conditional<false>`):

```cpp
template<bool>
struct conditional
{
    template<typename T, typename U>
    using type = T;
};

template<>
struct conditional<false>
{
    template<typename T, typename U>
    using type = U;
};

template<bool B, typename T, typename U>
using conditional_t = typename conditional<B>::template type<T, U>;
```

It's not a huge improvement, but in my experience it still reduces the size of the generated binary without having any noticebale effect on compile times. Considering it's an almost free optimization, I thought that you might want to give it a try :)

  [1]: https://odinthenerd.blogspot.fr/2017/03/start-simple-with-conditional-why.html

**Comment by ThePhD** [comment]
Thanks, fam. I'll put this to good use in the sol3 branch.

**Comment by ThePhD** [comment]
Integrated.
