### ISSUE TITLE
how to work with protocal buffer 3.5?

### ISSUE THREAD

**Issue by imilli** [ThePhD/sol2#648]
1、Can you give an example? 
2、Use only .proto files?

**Comment by ThePhD** [comment]
1. I don't know what you mean.
2. I have never worked with Protobuff / Protocol Buffers in my life.

Please give me more information. This repository is about working with Lua files from C++.

**Comment by imilli** [comment]
Can provide support for google protocal buffer? similar to LuaPbIntf support .proto files, link here: https://github.com/jinq0123/LuaPbIntf, google protocal buffer is very popular used in rpc  or microservices.

**Comment by ThePhD** [comment]
No, that is unfortunately outside of my scope. If someone wants to use sol to add protobuff support, they can, but it's not something I can build in directly.

Maybe -- if time permits -- someone could create an example of doing this and store it in the `/examples` directory for others to use? Still, it's not something I myself would work on personally.

**Comment by imilli** [comment]
Ok,thank you for your answer.
