### ISSUE TITLE
Using environments 

### ISSUE THREAD

**Issue by dudztroyer** [ThePhD/sol2#650]
While trying to make a multi-threaded(or just async calls) scripting system, I've got into this program design, which all of these scripts to be run are unsafe(aka from the user):

- 1: One SETUP script, to define common variables/functions/tables which should be readonly from other scripts;
- 2: Few one-time executed scripts running in the mian thread. This needs to have the SETUP environment so it can access the main variables/tables;
- 3: Few looping scripts that needs also to have access to the SETUP envorionment. They are running concurrently and can be enabled or disabled on demand.

The framework to have it all working is already built up, with custom stopping/relaunching settings/looping and such. The only thing I cant get it to work is to feed the looping(3) scripts with the SETUP informaiton.

But, since Main Thread has an sol::state and each looping scripts have each one their own state (the docs and here i've been told that for concurrent the proper way is to go with multiple states), I would need to feed the looping ones with the run-time changes of the SETUP. 

The current running setup I have is:
- For 1: Run the script directly on the state;
````
lua.script(script->m_Script);
````

- For 2: Run the script on a brand new environment, but on the main thread state each time a new script is run:
````
script->thisEnvironment = sol::environment(lua, sol::create, lua.globals());
lua.script(script->m_Script, script->thisEnvironment);
````

-For 3: Run the script on a brand new environment, on the early created state, each time a script loops:
````
script->thisEnvironment = sol::environment(script->thisState, sol::create, lua.globals());
script->thisState.script(script->m_Script, script->thisEnvironment);
````

This last one is where I'm having trouble. Is there a way to use the environment fallback on the globals of another state? If yes, how? If no, how can I accomplish the same thing I'm wanting?

I've tryied to use the same state for all three, but since it is async sometimes it bugs out. I need it to be also reliable.

Thanks again

**Comment by ThePhD** [comment]
You can't use the globals of another state as the fallback for an environment table. Lua does not have any way of transferring state or objects or values between States. You must explicitly serialize between them. You must either directly serialize and synchronize states, or you must have one and only one state.

**Comment by dudztroyer** [comment]
What kind of serialization/synchronization between those states you would recommend me to take a look?
I've seen that there is not standard way to do it, but perhaps you may have stumbled upon on a similar use scenario...

With only one state It would be possible with some kind of thread lock to prevent double access to the same state, i think...

Also, another problem just appeared: when trying to defiine each new state, I have a "Setup" function which receives an sol::state as argument and then sets up the argument with new usertypes/tables/functions. The main state works just fine, but when I make a new state using that function, those custom usertypes seem to not be accessed.

I've tryied this:
````
void Setup(sol::state * arg_stateToSetUP) {
	arg_stateToSetUP->open_libraries(sol::lib::base, sol::lib::math, sol::lib::string, sol::lib::table, sol::lib::bit32, sol::lib::os);
	arg_stateToSetUP->set_function("Wait", &Sleep);
	arg_stateToSetUP->set_function("Time", [&]() { return time(NULL); });
}
Setup(&thisState);
````
And this:
````
void Setup(lua_State * arg_stateToSetUP) {
	sol::state_view tempSt(arg_stateToSetUP);
	tempSt.open_libraries(sol::lib::base, sol::lib::math, sol::lib::string, sol::lib::table, sol::lib::bit32, sol::lib::os);
	tempSt.set_function("Wait", &Sleep);
	tempSt.set_function("Time", [&]() { return time(NULL); });
}
Setup(&thisState.lua_state());
````
But no success... Is there something wrong? It works on defining the main state, but not on the child others... Cant understand why.

**Comment by ThePhD** [comment]
If by "child states" you mean `sol::thread` alikes, that does not work. Lua Threads only have different stack space, and all point to the main thread, and ultimately share that top-level environment.

You can only be calling `open_libraries` on the Main Thread of any given `lua_State*`.

**Comment by dudztroyer** [comment]
Child states I meant a sol::state, which would fit on the number 3 on the main topic. Thats why "child". It is just a bare sol::state, that I call the Setup function when a wrapper that contains external infromation is being constructed.
````
	thisState = sol::state();
	p->cScripts->Setup(&thisState);
````
Or
````
	thisState = sol::state();
	p->cScripts->Setup(thisState.lua_state());
````

So basically it is on the main thread of that state, but still it doesnt set up.

**Comment by dudztroyer** [comment]
I've already got some xml implementation as well some json... Worked with protobuf on this project also. But I was thinking on something lua to lua, because there is no way to hardcode every possible variable an user puts in the setup that he would want to use on those looping scripts.

For now I'll stick to this setup, but later on will consider using only one state to hold all the user info.

Thanks for your help, and if anything else pops up i'll jump back here

Oh, and keep up the good work on this lib, it was really few hours of a learning curve to get from zero knowledge of c++ lua to making a complete script with custom usertypes/overloads work (of course without this crazy framework i've trying to accomplish). So yeah, it is really straightforward :P

**Comment by RussellHaley** [comment]
Not related to sol2, but an even loop like cqueues, luasys and others can be used to flip your threading model on its head (one lua state and a C library that polls underneath your lua code). Cqueues is quite good and very complete. It uses coroutine so you don't have to write ugly callbacks like node.js. Windows libraries to do the same are hard to come by though.
