### ISSUE TITLE
Bug report :SOL_PRINT_ERRORS  default print any exceptions / errors that occur in Release mode

### ISSUE THREAD

**Issue by sniper00** [ThePhD/sol2#652]
In the newest sol2 sol.hpp release (2.20.0) there is a small bug in these code ,SOL_PRINT_ERRORS always defined,  neither 1 or 0.
```cpp
#ifdef SOL_PRINT_ERRORS
			std::cerr << "[sol2] An exception occurred: ";
			std::cerr.write(what.data(), what.size());
			std::cerr << std::endl;
#endif
```

**Comment by ThePhD** [comment]
Where do you see that code?

**Comment by ThePhD** [comment]
Fooound it. It was in `trampoline`. For future bug reports, please include the line or some surrounding code: makes it easier to ID what's going on without doing a big ol' search. (Though, maybe I should embrace my *nix-en brethren and just get on with VIM and grep already...)
