### ISSUE TITLE
Avoid pulling in C++ library bloat for little gain (i.e. streams, facets, localization)

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#657]
Sol uses std::to_string, which uses streams internally, which use the whole heavyweight internationalization framework from the standard library. This can inflate the executable considerably, which can be painful on embedded systems.

I think this pulls in way too much code for what it actually does in sol. There should at least be a simple way to avoid it. Perhaps std::to_chars from C++17 can help.

**Comment by ThePhD** [comment]
I could probably drop this, but `from_chars` and `to_chars` is still lacking good implementation in some places. If I can find a replacement, I'll totally go for this.

**Comment by Rapptz** [comment]
Just so we're clear here, `std::to_string` does not use streams (i.e. `std::stringstream` and friends). [`libstdc++v3`](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/basic_string.h#L6413) uses `std::sprintf` and friends, as does [`libc++`](https://github.com/llvm-mirror/libcxx/blob/5f3d5935a377ad4d4be4ab1ef93e8e9294814a53/src/string.cpp#L436).

**Comment by s13n** [comment]
You're right, I put the blame on the wrong thing. Still, sol pulls in the stream stuff somehow. I need to work harder to track down how exactly that happens.

**Comment by OvermindDL1** [comment]
Maybe this could help:  https://github.com/include-what-you-use/include-what-you-use

**Comment by s13n** [comment]
News: I tracked down a bug that causes most of this bloat:

There's a wrong preprocessor condition around the `#include <iostream>`. The same mistake happens a few lines down around the 3 lines where `std::cerr` is used. It causes `<iostream>` to be always included, even when it isn't used. Just including it, even when not using its content, increases the size of the `.text` segment by 184664 bytes in my case.

This is apparently because it instantiates `std::cout`, `std::cin` and friends, and with it the whole internationalization ulcer gets pulled in.

In the single header sol.hpp v2.20.2 the fix affects two lines: 5790 and 5808, which need to be made the same as everywhere else where `SOL_PRINT_ERRORS` is used. Quite obvious when you look at it, no need for a patch.

**Comment by ThePhD** [comment]
This is already fixed, I just haven't pushed yet because other fixes.

**Comment by s13n** [comment]
Good. Thanks!
