### ISSUE TITLE
Lazy `require()`able libraries

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#659]
Hi,

I call a `require()`able libraries trough a C function with create_global to true
but even if my lua code don't call the require explicitly, my module will be in the global namespace.
Shouldn't the register be done lazily only when the lua script actually call require ?

Thanks !

**Comment by ThePhD** [comment]
Please provide some example code and commentary, I cannot visualize what you are trying to do.

**Comment by otristan** [comment]
```
static sol::table registerJuceInternal(sol::this_state s)
{
  sol::state_view lua = s.lua_state();

  sol::table module = lua.create_table();

  // Colour
  module.new_usertype<Colour>("Colour"
                              , sol::constructors<Colour(uint32)>()
                              , sol::call_constructor, sol::constructors<Colour(uint32)>()
                              , "withHue", &Colour::withHue
                              );
  return module;
}

static void registerJuce(sol::state& lua)
{
  lua.require("juce", sol::c_call<decltype(&registerJuceInternal), &registerJuceInternal>, true);
}

int main(void)
{
	sol::state lua;
	  lua.open_libraries(sol::lib::base,
                            sol::lib::package,
                            sol::lib::table,
                            sol::lib::math,
                            sol::lib::string,
                            sol::lib::coroutine);
      registerJuce(lua);

      lua.script_file("test.lua");
	return 0;
}
```

test.lua

```
--require "juce"
local c = juce.Colour(0xff000000)
```

Even if I don't say require "juce", it will work.

I can put false in last arg of require
and do this in the lua file
local juce = require "juce"
but I would prefer avoid doing this.

**Comment by ThePhD** [comment]
This is exactly the specified behavior of `require`. Require does not create a function that you have to call to get the functionality: `sol::`state(_view)::requires()` **IS the requires call**.

In order to have the functionality you desire, you need to hook into package searchers and similar which is a lower-level, deeper abstraction that I have not wrapped (and don't really have any plans to).

**Comment by otristan** [comment]
Fair enough.
Thanks for the clarification.

**Comment by ThePhD** [comment]
I'll put it on my TODO list but to be honest I wouldn't even know how to start, and as I understand it there's differences in how platforms handle this...

**Comment by otristan** [comment]
Related to https://github.com/ThePhD/sol2/issues/447

**Comment by otristan** [comment]
FYI
```
static sol::table registerJuceInternal_(sol::this_state s)
{
  sol::state_view lua = s.lua_state();
  return lua.require("juce", sol::c_call<decltype(&registerJuceInternal), &registerJuceInternal>, true);
}

static void registerJuce(sol::state& lua)
{
  sol::table searchers = lua["package"]["searchers"];
  searchers.add([](sol::this_state s, const std::string &module) {
    if (module == "juce")
    {
      return sol::c_call<decltype(&registerJuceInternal_), &registerJuceInternal_>;
    }
  });
}
```

it's "searchers" since lua 5.2 and used to be "loaders" in 5.1

something like that works but is probably sub optimal
