### ISSUE TITLE
Setting function or protected_function to nullptr cause crash

### ISSUE THREAD

**Issue by Rasa0** [ThePhD/sol2#669]
On the c++ side, if i try to set a function or protected_function variable to null, it crashes. From the implementation i figure it's expected behavior (reading meta code is kinda hard), so as a follow up question. How do i "clear" a function variable? Or is that not something that should ever be done?

**Comment by ThePhD** [comment]
Short answer: yeah probably shouldn't clear it.

Long answer:
Strongly-typed reference types (such as `sol::function`, `sol::table`, etc.) expect their types to be non-nil upon construction in safety modes. The reason for this is that it helps you get into a mindset that if you construct a strongly-typed version of something, you shouldn't have to keep checking if it's valid.

If you have the expectation that something needs to be cleared, use a `sol::object` and explicitly use `sol::object.is<T>` to check for the type, and then `sol::object.as<T>` to cast to what you need. This will make your intent more clear and save you from having to always check if a function is what you want: `sol::function` will always be valid, and `sol::object`/`sol::reference` will always be in a state of flux.

**Comment by Rasa0** [comment]
Ahh. That makes sense.

The original cause of the problem was that i kept a sol::function in a member variable (same as sol::state), because i want the function to be available in c++ (Lua user code could set is to nil). When the class was destroyed i got a crash because the sol::state was destroyed before the sol::function. Reordering of members solved that. Keeping a sol::function around like that might not be a sound idea in that case. I will most likely implement a sandbox later to prevent users from messing with my Lua interface. Wanted to keep the sol::function around for now to prevent that problem. But the destruction order will still be a problem if i use sol::object so i guess i just need to be careful about what i'm doing.

I consider this issue solved, but any further comments about my reasoning? Still trying to learn how to use sol properly!

Also, thanks for the quick answer, and for making sol. Working with the C interface have caused a lot of pains in the past, and sol have made working with Lua pleasant again =)
