### ISSUE TITLE
Cannot add new entries to usertype if new_index is overloaded

### ISSUE THREAD

**Issue by TurboLed** [ThePhD/sol2#670]
The following code crashes:

			class object {};
			sol::state lua;
			lua.open_libraries(sol::lib::base);
			lua.new_usertype<object>("object", 
				sol::meta_function::new_index, [](object& o, const sol::object& key, const sol::object& value) { return; }
				);

			// CRASH because of sol::meta_function::new_index above
			lua["object"]["test"] = [](object& o) { return; };

**Comment by ThePhD** [comment]
This is more or less expected behavior, I think. Maybe. Albeit the crashing is probably wrong...

**Comment by TurboLed** [comment]
The "new_index" overloading should affect only the instances of the "object" class, aka userdata. Not the table defining the class itself.
I expect the behavior to be the same as declaring the "test" function in the declaration of the new_usertype.
I'm looking for this as a solution to add nested classes and enums. Without having the new_index override, adding this code below works:
sol::table t = lua["object"];
t.new_enum("TestEnum", ...); // object.TestEnum works in Lua
// or
t.new_userdata<subObject>(...) // object.subObject works too

**Comment by ThePhD** [comment]
Fixed on latest.
