### ISSUE TITLE
Testing for a table returns true for usertypes

### ISSUE THREAD

**Issue by pvandommelen** [ThePhD/sol2#672]
If you could use a full testcase let me know.

When supplying a cpp function with a usertype the following function returns true where I would expect it to return false for usertypes:
```
lua.set_function("is_table", [](sol::object value) {
	return value.is<sol::table>();
});
```

This does work correctly, and gives me a workaround for now:
```
lua.set_function("is_table", [](sol::object value) {
	return value.get_type() == (sol::type)LUA_TTABLE;
});
```

Similarly, supplying a usertype to a function only accepting a table works, but then crashes on iterating (or requesting the size of) the table:
```
lua.set_function("table_size", [](sol::table value) {
	return value.size(); //crash!
});
```

Is this behaviour known? Can it be improved?

**Comment by ThePhD** [comment]
Usertypes are not metadata on tables: they are metadata and metatables on userdata.

Still, this is exactly expected behavior. Userdata can behave as table-alikes, and therefore can be used with the table abstraction. There is a `sol::userdata` abstraction.

If you want precise type checking, you need to do `value.get_type() == sol::type::table`.

As far as the crashes go, I don't know if it's worth the man-hours to try and pin down a fix for that, because there are some usertypes that are iterable and size-gettable (see: container usertypes and their metatable abstractions).

**Comment by pvandommelen** [comment]
Is it possible to have sol check for this when accessing size() or iteration and throw a nicer exception? Having that exception thrown would have saved me a couple of hours earlier while trying to figure out what was going wrong.

**Comment by ThePhD** [comment]
To be fair, I'd rather pin this down more precisely by adding a new type: `sol::definitely_table` (name needs work, obviously).

**Comment by ThePhD** [comment]
Going to settle on the name `sol::lua_table`. Any type prefixed by `lua_` will be extremely specific to what it's asking for. Some of these types will just be typedefs, since they already cover these things exactly (e.g., `sol::light_userdata` is already extremely picky).

Objections?

**Comment by pvandommelen** [comment]
Works for me

**Comment by ThePhD** [comment]
As a side note, why are you using `table.size();` and not `#table` in Lua?

**Comment by ThePhD** [comment]
After attempting an implementation of this, this further chops the sol2 implementation types into more pieces that I have to program for. I unfortunately do not think this is worth the implementation effort or the additional types.

If you need to hammer the type down, the type checks illuminated above should be more sufficient. I apologize if this isn't what you wanted to hear, but I'm trying very hard to reduce type spam and generated .obj size: this makes it slightly worse.

**Comment by pvandommelen** [comment]
https://github.com/ThePhD/sol2/blob/develop/examples/customization_convert_on_get.cpp

My functions both accept a wrapped and raw table, and 'Count' in that case would return a wrapped number for both. This wrapping deals with handling changes in its dependencies. So I want a single function to handle both cases.

Too bad that you can't find an acceptable way to implement the extra type. But I'm good, using the type checks suggested above works fine for me.

To get back to a previous point, I'm not convinced that casting a usertype to a table is acceptable. While a usertype may gain table-like features (count and iteration), directly casting a usertype to a table should almost always be a bug.

An alternative approach is to add the types sol::iterable and sol::countable, which sol::table would both inherit. This however introduces the same issues you just shut down lua_table for, and also causes BC breaks, and requires a time spent on refactoring that you probably have little interest in. I think it would make the library more fool proof though.

**Comment by ThePhD** [comment]
Thanks to the new customization point support for sol3, separating this out became easy enough.

It's called `lua_table`/`stack_lua_table` in sol3. Shit name, but meh!
