### ISSUE TITLE
Compile error: cannot convert from 'char *' to 'Tu (&)'

### ISSUE THREAD

**Issue by NullCascade** [ThePhD/sol2#674]
Getting a compile error with the new version. 
```
Severity    Code    Description    Project    File    Line    Suppression State
Error    C2440    'return': cannot convert from 'char *' to 'Tu (&)'    MWSE    c:\games\morrowind\mwse\mwse\sol.hpp    4022    
```
Happens when doing:
```cpp
usertypeDefinition.set("areaSoundEffect", sol::readonly_property([](TES3::MagicEffect& self) { return &self.areaSoundEffect; }));
```
Where TES3::MagicEffect looks like:
```cpp
struct MagicEffect {
    ...
    char areaSoundEffect[32];
    ...
};
```

**Comment by ThePhD** [comment]
I understand what you're trying to do here but I'm almost positive this isn't what you want to happen? Right now we're returning a container-userdata for this, not a string, for the property...

**Comment by NullCascade** [comment]
This was user error, I wasn't intending to do that and must have copy/pasted something. Not sure why updating sol2 flagged an issue, but in this case it's sol2 pointing out that I'm being dumb. Thanks for taking the time to look at it.
