### ISSUE TITLE
Iterating table and printing key value pairs

### ISSUE THREAD

**Issue by Rasa0** [ThePhD/sol2#676]
Using the C-API of Lua I'm able to print out key value pairs of tables like this:

```c++
void StackDump(lua_State* L) {
	int top = lua_gettop(L);
	for(int i = 1; i <= top; i++)
	{
		int t = lua_type(L,i);
		switch(t)
		{
		case LUA_TSTRING:
			printf("[string]: '%s'", lua_tostring(L,i));
			break;
		case LUA_TBOOLEAN:
			printf(lua_toboolean(L,i) ? "[bool]: true" : "[bool]: false");
			break;
		case LUA_TNUMBER:
			printf("[number]: %g", lua_tonumber(L,i));
			break;
		case LUA_TTABLE:
		case LUA_TLIGHTUSERDATA:
		case LUA_TFUNCTION:
		case LUA_TUSERDATA:
		case LUA_TTHREAD:
			printf("[%s]: %p", lua_typename(L,t), lua_topointer(L,i));
			break;
		default:
			printf("[%s]", lua_typename(L,t));
			break;
		}

		printf("  ");
	}
	printf("\n");
}
```

But when iterating a sol::table i can't seem to get the address of: tables, userdata, functions and threads; as seen above. Have been reading the documentation and code to see if I'm missing something. Or is that information simply hidden under the abstraction? I could just use the C-API and do it as i have always done, but I'm just asking so I'm not missing anything.

Edit. Code block

**Comment by ThePhD** [comment]
I do not expose to_pointer. You can use

int si = key.push();
lua_topointer(lua, -si);
key.pop();

And similar for the value during iteration. I could also add a .pointer()
method on reference/object/etc., But it would do exactly what I have just
typed out (with some optimizations for sol::stack_reference).

**Comment by Rasa0** [comment]
Tested, and works as expected! Thanks!

**Comment by ThePhD** [comment]
`pointer` now exists as a method in latest bugfix release v2.20.4
