### ISSUE TITLE
Customizable (u)int64_t handling

### ISSUE THREAD

**Issue by Rochet2** [ThePhD/sol2#677]
DESCRIPTION
Lua cannot handle 64 bit integers and sol2 seems to simply cast the value to a double thus losing percision or possibly even converting to 0.
Currently trying to use extension points for uint64_t or int64_t will cause a compile error since sol2 already implements a specialization for push, check and get for all integral types (the casting).
As such there is no way I can see currently to fix (u)int64_t compatibility properly without editing sol2's internal code.

EXAMPLE
using lua 5.2
cmake flags for clang:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror -Wextra -Wno-long-long -pedantic -std=c++14")`
sol2 version:
https://raw.githubusercontent.com/ThePhD/sol2/4480b7ef89305240d4a231bc1ebd86932d51585a/single/sol/sol.hpp
```cpp
#include "sol.hpp"
#include <iostream>
#include <cstdint>

// a part of code needed for using extension points to make
// custom check, get, push functionality in sol2
// uncommenting this causes clang to error on compile, compiles fine on VS
// namespace sol {
//    template <> struct lua_size<int64_t> : std::integral_constant<int, 1> {};
// }

int main()
{
    sol::state lua;
    lua.open_libraries();

    lua.script("print(_VERSION)");
    lua.script("function f(x) return x end");

    uint64_t y = 0xFFFFFFFFFFFFFFFFULL;
    uint64_t x = y;
    for (; true; --x)
    {
        y = lua["f"](x); // push and get uint64_t value to and from lua
        if (y != x) // if the value we got and pushed are not same, print diagnostic message
        {
            // this stuff is printed a lot when lua does not support 64 bit values properly
            // for some reason y is always 0.. hm
            std::cout << "x:" << x << std::endl;
            std::cout << "y:" << y << std::endl;
            std::cout << "diff:" << (0xFFFFFFFFFFFFFFFFULL - x) << std::endl;
        }
    }
    return 0;
}
```

PROPOSEDCHANGE
Current implementation uses something like this on the check,get,push of integral values:
`std::enable_if_t<std::is_integral<T>::value>`

A fix could look something like this:
`std::enable_if_t<std::is_integral<T>::value && !std::is_same<T, int64_t>::value && !std::is_same<T, uint64_t>::value>`

Excluding uint64_t and int64_t will still allow the values to be passed through and printed in lua as userdata, but math will be disabled by default. Extension points can then be used to define further behavior (like casting to double instead of userdata for speed and math capabilities at the cost of percision).
Lua 5.3 would be able to support int64_t by default I believe and would require a special case, however I dont think it can handle uint64_t still.

**Comment by ThePhD** [comment]
I am not interested in pursuing this direction.

It is vastly preferable that you either upgrade to Lua 5.3 so you can use the 64-bit integers present (well, 63 + 1 sign bit), OR

Wrap your 64+bit numbers in a custom type to transfer them through Lua.

**Comment by Rochet2** [comment]
The first option is not possible since the full range and distinction between the two would be needed.
The second option requires that (u)int64_t is not used anywhere, for example functions would require using the custom wrapped type instead of (u)int64_t as parameter type which is also not possible.
For now I will just probably use the proposed change myself.

**Comment by ThePhD** [comment]
There is no need to produce a distinction for option 1: it's a bag of bits and you can simply view the memory in whatever way you see necessary.

As a side note, this might be fixable when sol3 introduces new customization points. But as it currently stands, the proposal here is a serious compatibility break that I cannot consider for sol2.
