### ISSUE TITLE
Is it possible to directly pass the result of a sol::state::script_file call to a function expecting its converted result?

### ISSUE THREAD

**Issue by arnavb** [ThePhD/sol2#680]
Say I had a class `GameMap` with a constructor that took a `sol::table` as an argument. For example, said constructor may look like the following:

```C++
GameMap::GameMap(const sol::table& locationsTable) :
    locationsTable_ { locationsTable }
{
}
```
The class above is used for storing a list of game locations in a text adventure game.

The format of the lua file is:

```Lua
local locations = {
    location_1 = {
        -- ...
    },
    -- ...
}

return locations
```

Now, when initializing this class directly from a file, I might do:

```C++
GameMap gameMap{ luaState.script_file("resources/locations.lua") };
```

However, this does not work; Running this results in the following error:

```
main.cpp: In function ‘int main()’:
main.cpp:13:70: error: call of overloaded ‘GameMap(<brace-enclosed initializer list>)’ is ambiguous
     GameMap gameMap{ luaState.script_file("resources/locations.lua") };
                                                                      ^
In file included from main.cpp:1:0:
game_map.hpp:12:5: note: candidate: GameMap::GameMap(const table&)
     GameMap(const sol::table& locationsTable);
     ^
game_map.hpp:9:7: note: candidate: GameMap::GameMap(const GameMap&)
 class GameMap
       ^
```

(The relevant compiler is `g++-5 (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904`, with the `-std=c++14` flag enabled)

In order to fix this problem, I have broken down the constructor initialization to two steps:

```C++
sol::table test = luaState.script_file("resources/locations.lua");
GameMap gameMap{ test };
```

While this works, it is somewhat inconvenient as it requires two lines of code and an extra variable, when one should be just fine. Is there any way to go around this? I tried doing a `static_cast`, but to no avail.

**Comment by ThePhD** [comment]
Except it's not.

`sol::script` returns a `thing-that-is-convertible-to`, not a `thing`. That makes all the difference for overload resolution. `static_cast` might work but there is literally no difference between writing it out and not-writing-it-out: the performance metrics are identical.

**Comment by arnavb** [comment]
Ah, thanks for the clarification. I should have done my research...
