### ISSUE TITLE
Stack not unwinding on error [LuaJIT]

### ISSUE THREAD

**Issue by Rasa0** [ThePhD/sol2#681]
In my project I call an update function in protected mode, which in turn calls a C function, which then call a Lua function that then call error.

Callstack:
lua (protected)
C
lua (unprotected)
error

In the C function i have a std::string, who's destruction is never called, causing memory leaks.

After some digging around and testing I found that the problem occurs with LuaJIT but not Lua5.1 (built as c++).

I have modified the example code from https://github.com/ThePhD/sol2/issues/592 to demonstrate the problem:

```C++
#define SOL_EXCEPTIONS_SAFE_PROPAGATION 1
#include <sol.hpp>

int main(int, char**)
{
	static size_t fooCount{};

	struct Foo {
		Foo()
		{
			++fooCount;
		}
		~Foo()
		{
			--fooCount;
		}
	};

	{
		sol::state lua;
		lua.open_libraries(sol::lib::base);

		lua.script(R"(
			function crash() 
				error() 
			end 
		)");

		lua["fn"] = [&]()
		{
			auto foo = std::make_shared<Foo>();
			lua["crash"]();
		};

		auto result = lua.safe_script("fn()", [](lua_State*, sol::protected_function_result pfr)
		{
			return pfr;
		});
	}

	assert(fooCount == 0);

	return 0;
}
```

I'm working on a Lua IDE integrated into my engine that allows live development. I need the error to unwind the call stack when an error is encountered, so I can't fix it by doing a protected call in the C function.

Is this expected behavior of LuaJIT and/or is there a way to circumvent it? Would be sad if i had to switch to Lua5.1 to avoid this problem.

**Comment by ThePhD** [comment]
Lua's error function `longjmp`s when not built as C++.

... And that's it.

You don't get safety. You don't get unwinding. LuaJIT does not give any of this to you, unless you build x64 and do everything the documentation tells you to with the latest LuaJIT. This is spoken about extensively in so2's documentation. This isn't a sol2 problem. It's a Lua(JIT) problem.

Compile Lua as C++ or update your LuaJIT to behave. If neither work, consider re-structing your code and not calling `crash()` without using the designated `protected_function` mechanisms. (You can unwind the function manually by calling the function, handling the error, and then just `return`-ing gracefully.)

**Comment by Rasa0** [comment]
Everything is built as c++ and x64.

Doesn't the initial protected_function call handle subsequent calls to C function?

**Comment by ThePhD** [comment]
No. You need to protect everything. And handle everything. At all levels.

Consider replacing the default error handling function with [`set_default_handler`](sol2.readthedocs.io/en/latest/api/protected_function.html#id3) to make your life easier.

**Comment by Rasa0** [comment]
Ok! Already using a custom handler =).

Will have to do some more tinkering then. Thanks!
