### ISSUE TITLE
Compatibility with Xcode 9.4.1 (GNU C++17)

### ISSUE THREAD

**Issue by execomrt** [ThePhD/sol2#688]
There are a couple of error when compiling on Mac with Xcode 9.4.1

sol.hpp:1553:53: error: implicit instantiation of undefined template 'std::__1::array<char, 1>'
                             static const bool value = sizeof(test<T>(0)) == sizeof(sfinae_yes_t);
sol.hpp:1565:53: error: implicit instantiation of undefined template 'std::__1::array<char, 1>'
                                static const bool value = sizeof(test<T>(0)) == sizeof(sfinae_yes_t);
sol.hpp:1577:53: error: implicit instantiation of undefined template 'std::__1::array<char, 1>'
                                static const bool value = sizeof(test<T>(0)) == sizeof(sfinae_yes_t);
sol.hpp:1592:53: error: implicit instantiation of undefined template 'std::__1::array<char, 1>'
sol.hpp:1607:53: error: implicit instantiation of undefined template 'std::__1::array<char, 1>'
                                static const bool value = sizeof(test<T>(0)) == sizeof(sfinae_yes_t);
                                                                                ^
Thanks for having a look at it !

**Comment by ThePhD** [comment]
Known error. Quick fix: add `#include <array>` before you include sol2.

**Comment by execomrt** [comment]
OK thanks, it worked. Please check my project : https://github.com/execomrt/tosolpp
This uses tolu++ package file and generate Sol 2 code. I'm looking for tester and comments.
Cheers;
