### ISSUE TITLE
Question: Overriding require behavior

### ISSUE THREAD

**Issue by darkgnostic** [ThePhD/sol2#692]
I have one virtual file system, where I store all my files. LUA files also.
When I load LUA file from container, I extract it in memory, then run it with sol.

    sol::state lua;
    lua.script(vfs.get_content("package.lua"));

in case my package.lua has for example at the top of the file 

    local inspect = require('engine.inspect')

which with I include other packages. Now, my problem is that require will try to load file from disk, instead from my virtual file system (which is absolutely normal).

My question is fairly simple (I couldn't find answer for it). Is there any function in sol where I can override require function behavior? Like forwarding LUA call to some c++ function with path, where I can load file, and pass it back to LUA?

Thanks in advance

**Comment by ThePhD** [comment]
That looks like it answers the question. Thanks for the help @OrfeasZ 👌

**Comment by ThePhD** [comment]
Note to self: add this to the examples.

**Comment by darkgnostic** [comment]
Fantastic @OrfeasZ ! Thank you!

**Comment by darkgnostic** [comment]
@OrfeasZ I have copy/pasted your example, but it doesn't work. It never hits LoadFileRequire

```
[sol2] An error occurred and panic has been invoked: [string "..."]:2: module 'a' not found:
        no field package.preload['a']
        no file '.\a.lua'
        no file 'G:\Tests\LUA\LuaTest\Debug\lua\a.lua'
        no file 'G:\Tests\LUA\LuaTest\Debug\lua\a\init.lua'
        no file '.\a.dll'
        no file 'G:\Tests\LUA\LuaTest\Debug\a.dll'
        no file 'G:\Tests\LUA\LuaTest\Debug\loadall.dll'
```

I am using sol v2.20.3 (revision daa9993) (latest)

**Comment by darkgnostic** [comment]
Changing searchers to loaders will fix the issue. 

```
lua["package"]["loaders"] = lua.create_table_with(
		1, LoadFileRequire
	);
```

One question though, `create_table_with ` will overwrite existing loaders or it will append new loader?

**Comment by ThePhD** [comment]
It will overwrite.

**Comment by OrfeasZ** [comment]
A note for whoever stumbles upon this in the future: Lua 5.1 and earlier use `package.loaders` while Lua 5.2 and newer use `package.searchers`.

@darkgnostic if you want to append to the loaders/searchers table you can probably do something like this (untested):
```cpp
sol::table loaders = lua["package"]["loaders"];
loaders.add(LoadFileRequire);
```

**Comment by ThePhD** [comment]
There will be a simple function in sol3 called `add_requires_searcher` that will do this for you, and `clear_requires_searchers` that will clear it for you.
