### ISSUE TITLE
Question about userdata depth 

### ISSUE THREAD

**Issue by darkgnostic** [ThePhD/sol2#693]
I have browsed through all stuff with userdatas, and everything works well until i add _substruct_.

    sol::usertype<player_class_2> player_class_type_2(
    		"name", &player_class_2::name_
    	);
    lua.set_usertype("player2", player_class_type_2);
    
    lua.script("pl2 = player2.new()\n"
    "pl2.v.name=\"George2\"");
    
I have tried: 

    "v.name", &player_class_2::name_

and

    lua.set_usertype("player2.v", player_class_type_2);

but neither work.

What is the correct way of doing it, or am I doing something prohibited?

Here is complete example:

```
struct player_class_2 {
	player_class_2()
	{}
	std::string name_;
};
 int main() {
    sol::state lua;
    lua.open_libraries();

sol::usertype<player_class_2> player_class_type_2(
		"v.name", &player_class_2::name_
	);
	lua.set_usertype("player2", player_class_type_2);

	lua.script("pl2 = player2.new()\n"
		"pl2.v.name=\"George2\"");

	player_class_2& pl2 = lua["pl2"];

	std::cout << "Sol says that player2 is: " << pl2.name_ << std::endl;

return 1;
}
```

**Comment by ThePhD** [comment]
You create a `new_usertype` of the substruct. It is not registered "underneath" that type: it goes in the namespace you want it to. Then, accessing `pl2.v.name` works as expected, **provided you bind `v` to a struct of some type.

Yout example doesn't really clearly illustrate to me what you want. In none of your examples do you show what `v` is supposed to be, so I can only guess.

**Comment by darkgnostic** [comment]
Actually I tried to bind substruct to another usertype, which also didn't worked. Give me a minuet I will assemble one example.

**Comment by ThePhD** [comment]
Let me be a bit more clear:

`v.name` is not a valid name _by itself_. Lua will happily create a key of that type, but it will be nearly impossible for you to access it using `pl2.v.name`: this is because Lua, as a language, parses every `.` as meaning a new variable inside of the thing that comes before the `.` -- so, `v` needs to be a valid entry, by itself.

You can circumvent this with `pl2["v.name"]`, but that is not the syntax you want, nor it is worth it. If you want `obj.v` to bind to something, you need to make `v` return something that Lua can use/understand (usertype, table, etc.).

**Comment by darkgnostic** [comment]
Here it is base example of what I want to achieve. You got it right, I wanted to have LUA substruct bound to C++ struct. here is slightly changed definition when all structs and substructs are properly bind. But that doesn't work neither.

```
struct base_data {
	std::string name_;
};
struct player {
	base_data base_data_;
};

int main() {
	sol::state lua;

	lua.open_libraries();

	// bind base data substruct
	sol::usertype<base_data> base_data_(
		"name_", &base_data::name_
	);
	lua.set_usertype("base_data", base_data_);

	// bind player struct
	sol::usertype<player> player_(
		"base_data", &player::base_data_
	);
	lua.set_usertype("player", player_);

	// create new player
	lua.script("pl = player.new()\n"
		"pl.base_data.name=\"George2\"");

	// retrieve it
	player& pl = lua["pl"];
	std::cout << "Sol function says that player is: " << pl.base_data_.name_ << std::endl;

	return 1;
}
```

**Comment by ThePhD** [comment]
Your code fails because you bind the variable name in Lua as `"name_"`, and not `"name"`. (Note well the underscore you left in the quotes.)

**Comment by ThePhD** [comment]
(After that is fixed, the code runs perfectly fine. If there's another problem here, you should elaborate so I can re-open the issue.)

**Comment by darkgnostic** [comment]
_Facepalm_ 

Thanks! 👍
