### ISSUE TITLE
Create char*[] from table?

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#694]
Hi, 
Sorry for the crap question. My C is weak and I've been away for a while. I can't seem to figure out a good way to re-create argv from my table? I've realized as I write this I'll need to dynamically allocate the array perhaps, but how do I get a char* from sol2? More details below.

I'm writing a C++ application for calling different versions of Lua (a wrapper lua.exe) and I want to parse out some of the main() parameters my application receives and pass a subset to a modified lua main(). I renamed to LUA_API mainL(int argc, char* argv[]). I'm trying to parse argv in Lua (called through sol2) and pass back a subset of the values. 
 
``` C++
int main(int argc, char* argv[]) {
	sol::state lua;
	// open some common libraries
	lua.open_libraries(sol::lib::base, sol::lib::string);
	lua.script("args={}");
	for(int i = 0; i < argc; i++){
		lua["args"][i] = argv[i];
	}
        //Creates a opts table that contains parameters and an opts.other table for 
       // the parameters destined to mainL() 
        lua.script(get_opts);
        int argc2 = lua["argc"];

//? How do I re-create argv from my table?
}
```
Any help would be grand.
Russ

**Comment by ThePhD** [comment]
```
std::vector<std::string> argv2_storage;
sol::table argv2_table = lua["args"];
for (const auto& kvp : argv2_table) {
     argv2.push_back(kvp.second.as<std::string>());
}
std::vector<const char*> argv2;
for (const std::string& str : argv2_storage) {
    argv2.push_back(str.c_str());
}
const char* argv2_pointers[] =argv2.data();
````

We extract into a vector of `std::string`. There is some dumb C++ rules at play here that don't let us write `std::vector<std::string> blah = lua["args"];`. I can assure you those rules are dumb, which is why I'm writing a paper to fix them. We do this in 2 steps because a `.push_back()`, if we do not know the size of the table before hand, can invalidate the array if we do not `.reserve()` enough space before-hand and gaurantee that `.capacity()` >= `desired_size` meaning that the pointers we get can potentially be moved.

Once that is done, we store it in an `argv2` vector. We fill it with a for loop because I'm too lazy to use a `std::accumulate`/`std::transform` from `<algorithm>`, and it's readable.

Then, we finally get ourselves the array we want. Note that this is not an owning array: it only references the memory stored in the vector and is not a fresh copy.

**Comment by ThePhD** [comment]
Also, lua tables preserving ordering by counting from 1. So...

```
	for(int i = 0; i < argc; i++){
		lua["args"][i + 1] = argv[i];
	}
```

Minor fix.

**Comment by RussellHaley** [comment]
Thanks so much. The following works for me. I tried to remove one of the loops by just using the std::vector<char*> but it didn't work (see the commented code).
```c++
int main(int argc, char* argv[]) {
	sol::state lua;
	// open some common libraries
	lua.open_libraries(sol::lib::base, sol::lib::string);
	lua.script("args={}");
	for(int i = 0; i < argc; i++){
		lua["args"][i] = argv[i];
	}
	//will need to run protected and get an error return value?
	lua.script(get_opts);
	
	int lua_argc = lua["argc"];
	//~ char * test = lua.script("return 'test'");
	std::cout << lua_argc << std::endl;
	sol::table lua_argv_table = lua["other"];
	std::vector<std::string> v_lua_argv_string;
	for (int i = 0; i < lua_argc; i++) 
	{
		auto proxy = lua_argv_table[i];
		//~ Implicit conversion saves us here
		v_lua_argv_string.push_back(proxy);
		std::cout << proxy.get<std::string>() << std::endl;
	}
	std::vector<const char*> v_lua_argv_char;
	for (const std::string& str : v_lua_argv_string) 
	{
		v_lua_argv_char.push_back(str.c_str());
	}
	
	//~ std::vector<const char*> v_lua_argv_char;
	//~ for (int i = 0; i < lua_argc; i++) 
	//~ {
		
		//~ auto proxy = lua_argv_table[i];
		//~ v_lua_argv_char.push_back(proxy.get<std::string>().c_str());
		//~ std::cout <<"from proxy "<< proxy.get<std::string>().c_str() << std::endl;
	//~ }
	const char** lua_argv =v_lua_argv_char.data();
	
	for(int i=0; i < lua_argc; i++)
	{
		std::cout << "test: " << lua_argv[i] << std::endl;
	}
	std::string sho = lua["opts"]["version_string"];
	std::cout << "Where are we going? " << sho << std::endl;
	std::cout << "This concludes tonights script." << std::endl;
	system("pause");
	return 0;
};

```

Working output:
```
C:\Users\russh\projects\AllLuaJam> .\bin\dtlua.exe -53 -e -other --file c:\temp -o
4
C:\Users\russh\projects\AllLuaJam\bin\dtlua.exe
-e
-other
-o
test: C:\Users\russh\projects\AllLuaJam\bin\dtlua.exe
test: -e
test: -other
test: -o
Where are we going? 5.3\lua53.dll
This concludes tonights script.
Press any key to continue . . .
```

Output from code that doesn't work:

```
C:\Users\russh\projects\AllLuaJam> .\bin\dtlua.exe -53 -e -other --file c:\temp -o
Hello world
4
from proxy C:\Users\russh\projects\AllLuaJam\bin\dtlua.exe
from proxy -e
from proxy -other
from proxy -o
test: C:\Users\russh\projects\AllLuaJam\bin\dtlua.exe
test:
test:
test:
Where are we going? 5.3\lua53.dll
This concludes tonights script.
Press any key to continue . . .
```

Last but not least, the getopt-lua.hpp with the lua script:
``` C++
char * get_opts =  R"V0G0N(
--START LUA
local sep = '\\'
local so_ext = '.dll'
opts = {}

opts.bits = 32
other = {}
argc = 0

local function check_version(version)
	--strip the dash and see if we can make a number
	-- if the number is between 51 and 54 (inclusive) then return it
	-- if the version is alread set, return an error
	local ver = tonumber(version:sub(2))
	local msg = nil
	if ver then
		if ver < 51 or ver > 54 then
			msg = ver.." is not a valid version"
			ver = nil
		end
	end 
	if opts.version then
		msg = "Cannot set "..ver.." Already set to"..opts.version
		ver = nil
	end
	return ver, msg
end

local param = -1

for i,v in pairs(args) do
	local item = v:lower()
	local ver = v:match("-5%d")
	local err = nil
	if i == 0 then
		other[0] = v
	elseif ver then
		ver, err = check_version(ver)
		if ver then 
			opts.version = ver
			opts.version_string = string.format("%.1f%slua%d%s",opts.version/10, sep, opts.version, so_ext)
		else
			opts.err = err
		end
	elseif item == "-x64" then
		opts.bits = 64
	elseif v == "-f" or v == "--file" then
		opts.config_file = args[i+1]
		param = i
	elseif param > -1 then
		param = -1
	else
		other[#other + 1] = item
	end
end

for i,v in pairs(other) do
	argc = argc+1
end

-- END LUA
)V0G0N";
```

**Comment by ThePhD** [comment]
Lua does not allow you to take `const char*` pointers out of it. Lua only has valid c strings when they're on the stack: when they leave Lua's stack, they are no longer valid pointers and can be moved / garbage collected / shifted around, invalidating the memory pointer.

This is why you cannot get a `std::vector<char*>`, and why it would fail for you.

Finally, getting a `std::string` in-place and then getting a `c_str()` to that makes no sense. You're creating a temporary thing that owns the data -- `.get<std::string>()` -- getting a pointer to its internal data as a null-terminated `const char*` -- `.c_str()` -- and the only save the pointer, not the actual value that holds, owns, and ultimately deletes the data when it does. And it _does die_; the moment that expression is over in your commented-out code, you just have a dangling pointer in your vector. I'm honestly surprised it didn't explode much, much quicker or just outright segfault.

Note there is a less-beautiful but simpler way to write this:

```
sol::as_table_t<std::vector<std::string>> serialized_argv2 = lua["argv"];
std::vector<const char*> argv2;
// notice .source on next line
for (const std::string& str : serialized_argv2.source) {
	argv2.push_back(str.c_str());
}
```

You can run scripts safely to get errors out of it using `auto result = lua.safe_script(get_opts, sol::script_pass_on_error);`. The `sol::script_pass_on_error` explicitly says to not throw, just pass the error through. You can inspect the return by looking at `result.valid()` and other things (it's just a `protected_function_result` usable in the same way as protected function returns -- http://sol2.readthedocs.io/en/latest/api/protected_function.html).

**Comment by ThePhD** [comment]
I apologize as my use of `const` and `not-const` is merely a typo: all of those things were supposed to be `const` and it does not change what I was trying to say.

My only contention is that your code would not work because it made references to temporary `std::string`s.

As for the rest of the code, I have no idea. I don't work with the Windows API closely. If you need to `non`-const your data, remove const everywhere and replace `.c_str()` with `.data()`, which in later versions of C++ allows you to get it non-const. If you're not working with a recent version of C++, you can use `&str[0]` to get a non-const  `char*`:

````
	sol::as_table_t<std::vector<std::string>> serialized_argv2 = lua["other"];
	std::vector<char*> argv2;
	for (std::string& str : serialized_argv2.source) {
		argv2.push_back(&str[0]);
	}
````

**Comment by ThePhD** [comment]
I will note that if you don't plan to modify the string's contents, then `const` is what you want since it will compile-time enforce that you're not making modifications. Just make sure you have `const` in all the right places to ensure that changes are never done to the underlying data (I think with a pointer to a pointer, there's room for 2 or 3 `const`s in there.
