### ISSUE TITLE
external/sol/sol.hpp:8244:21: warning: unused variable 'v'

### ISSUE THREAD

**Issue by akovachev** [ThePhD/sol2#698]
Greetings!

Kudos to ThePhD for giving us this amazing library!

First time opening an issue here, so hopefully within the guidelines.

Well... not really an issue, but just a nitpick, since this is the only warning we get in our build right now.

Bazel under Mac OS X.

```
external/sol/sol.hpp:8244:21: warning: unused variable 'v' [-Wunused-variable]
                        const lua_Number v = lua_tonumberx(L, index, &isnum);
```

We would like to have a build clean of both warnings and errors and prefer not to use -Wunused-variable for the time being.

Cheers!

**Comment by akovachev** [comment]
There is a funky #if defined statement causing this. We enabled SOL_CHECK_ARGUMENTS, which removes the warning, but still...

I would change the following code

```
			const lua_Number v = lua_tonumberx(L, index, &isnum);
			const bool success = isnum != 0
#if (defined(SOL_SAFE_NUMERICS) && SOL_SAFE_NUMERICS) && !(defined(SOL_NO_CHECK_NUMBER_PRECISION) && SOL_NO_CHECK_NUMBER_PRECISION)
				&& static_cast<lua_Number>(llround(v)) == v
#endif // Safe numerics and number precision checking
```

to something like that:

```
			const bool success_temp = isnum != 0;
#if (defined(SOL_SAFE_NUMERICS) && SOL_SAFE_NUMERICS) && !(defined(SOL_NO_CHECK_NUMBER_PRECISION) && SOL_NO_CHECK_NUMBER_PRECISION)
			const lua_Number v = lua_tonumberx(L, index, &isnum);
			const bool success = success_temp && static_cast<lua_Number>(llround(v)) == v
#endif // Safe numerics and number precision checking
```

So that the #if defined is not in the middle of the sentence.

**Comment by ThePhD** [comment]
This is fixed.
