### ISSUE TITLE
conflict with a symbol in file container_traits.hpp 

### ISSUE THREAD

**Issue by didierjeanphi** [ThePhD/sol2#699]
Good morning,
In the file mentioned in the subject, an error is thrown due to a conflict with the fmt library.
Nowhere in the code, I issue a 
```c++
using namespace fmt;
```
and yet the struct below 

```c++
		struct error_result {
			int results;
			const char* fmt;
			std::array<const char*, 4> args;

			error_result() : results(0), fmt(nullptr) {
			}

			error_result(int results) : results(results), fmt(nullptr) { //error here
			}

			error_result(const char* fmt, const char* msg) : results(0), fmt(fmt) { //error here
				args[0] = msg;
			}
		};

```

produces the following error

```
sol/container_traits.hpp:462:33: error: expected identifier before ‘[’ token
    error_result() : results(0), fmt(nullptr) {
```

Thank you for your assistance.

D

**Comment by dedmen** [comment]
It's probably confused to hell because you are trying to use a namespace name as a variable name.

**Comment by isvogor-foi** [comment]
I have a similar problem, and it seems that there is a conflict with spdlog library... Both use fmt.

**Comment by ThePhD** [comment]
This was brought up before. I'm fixing it in my currently bundle of fixes, but if somebody wants they can make a quick patch to change the variable name to save themselves and others the agony.

**Comment by isvogor-foi** [comment]
I fixed my issue... just renamed the fmt to fmt_ because fmt is also a library (fmt/format.h). So I've tried to fix my project to use another instance of the fmt library but didn't manage.
Simple change of the variable name from fmt to fmt_ in sol2 fixed my issue. I made a pull request.

**Comment by ThePhD** [comment]
👍
