### ISSUE TITLE
Different loading style crash the game

### ISSUE THREAD

**Issue by gamepois0n** [ThePhD/sol2#703]
any idea why `lua.script_file(path1);` will crash my game while `sol::load_result script = lua.load_file(path); + script();` will not? I am using `sol::state_view lua(L);`

path.lua contains only variables while path1.lua contains variables and functions + register function

edit: even if I create a brand new state with `sol::state nlua;`, using script_file will still crash the game

**Comment by ThePhD** [comment]
Please use the safety versions of `script_file` such as `safe_script_file` to obtain error information that you can print out and inspect to help solve your errors.

**Comment by gamepois0n** [comment]
`		fLog("1");
		sol::protected_function_result scriptresult1 = nlua.safe_script_file(path1);
		fLog("loading into result");
		fLog("string: %s, int: %d", scriptresult1, scriptresult1.valid());`
my log prints out "1", but it never got to "print loading into result"
