### ISSUE TITLE
how do you deduce lambda argument types?

### ISSUE THREAD

**Issue by Spacechild1** [ThePhD/sol2#706]
Hi, this is probably not the right place but I couldn't find another way to get in touch with you.

First I want to say THANK YOU for sol2, working with it is a real pleasure. I especially appreciate the wonderful documentation!

I have a question about the implementation:

when I do something like this:
~~~
table["sum"] = [](int x, int y) -> int {
    return x + y;
};
~~~
how on earth do you manage to deduce the number and types of the lambda function arguments? for static/free functions and member functions it's trivial, but I've read on several places that it's not possible for lambdas - which obviously isn't true :-) I've skimmed through the code but couldn't spot it... it would be awesome if could give me a hint where to look.

**Comment by ThePhD** [comment]
`bind_traits`. All lambdas are structs with `operator()(Arg1, Arg2, ..., ArgN)` implemented. Which means it's just a member function. Apply same rules as for member functions apply.*

* - note, lambdas also decay into a function pointer of `R(*)(Arg1, Arg2, ..., ArgN)` if they have "no state". In this case you see if you can deduce the signature, then check if its convertible to the function pointer, then convert straight away to only store a function pointer, which is a 10/10 optimization.

**Comment by Spacechild1** [comment]
oh my, I didn't think about operator()... thanks a lot!
