### ISSUE TITLE
How to bind `sol::meta_function::index` to a static class function?

### ISSUE THREAD

**Issue by WolfgangSteiner** [ThePhD/sol2#707]
I have a class `TColorHSLA` that represents a color value and is exposed to sol as a `usertype`:

```
s.new_usertype<TColorHSLA>("Color",
    sol::constructors<TColorHSLA(), TColorHSLA(float,float,float,float)>(),

    sol::meta_function::index, [](const char* key, sol::this_state s) -> sol::object
    {
      sol::state_view lua(s);
      if (TColorHSLA::SHasNamedColorValue(key))
      {
        return sol::make_object(lua, TColorHSLA::SRetrieveNamedColorValue(key));
      }
      else
      {
        return sol::make_object(lua, sol::nil);
      }
    },
    "multiply_alpha", &TColorHSLA::MultAlpha,
    "multiply_lightness", &TColorHSLA::MultLightness,
    "with_alpha", &TColorHSLA::WithAlpha,
    "black", sol::overload(
        [](){ return TColorHSLA::SColorBlack(); },
        [](float alpha) { return TColorHSLA::SColorBlack(alpha); }),
    "white", sol::overload(
        [](){ return TColorHSLA::SColorWhite(); },
        [](float alpha) { return TColorHSLA::SColorWhite(alpha); }),
    "gray", sol::overload(
        [](float value){ return TColorHSLA::SColorGray(value); },
        [](float value, float alpha) { return TColorHSLA::SColorGray(value, alpha); }),
    sol::meta_function::equal_to, &TColorHSLA::operator==);
```

So in my lua code I can do stuff like: 
```
c1 = Color.black(0.5)
c2 = c1:mulitply_alpha(0.25)
```

But when I try to do:
```
c3 = Color.ViewBackgroundColor
```

My `index` function never gets called and the returned color in lua is always `nil`.

I could get it to work when binding a member function to the `sol::meta_function::index` but that does not really make sense here, as I am trying to bind a factory function. Is there any way that I can get this to work? Do I need a function/lambda with a special set of arguments?

Thanks!

**Comment by WolfgangSteiner** [comment]
Thanks for the quick response! I ended up implementing it in a similar way that you suggested and moved the preset colors to a `config` table. I did not know that you are already working on sol3! Keep up the great work!

**Comment by ThePhD** [comment]
I'm considering adding a `sol::static_index` and `sol::static_newindex` to give people access to this. I need better names, but it's on the dockets.
