### ISSUE TITLE
Is it possible to stop and resume a lua state that is running ?

### ISSUE THREAD

**Issue by grandemk** [ThePhD/sol2#708]
For example: The lua script calls a sleep(5) function implemented in c++.
This function stops the interpreter and sets a time at which we will want to resume the script.
We busy wait (while doing other things) and check if the time has come to resume the lua script.
When the time has come, we resume the lua script and it continues after the sleep function.

Is this possible ?
Thanks,
Kevin

**Comment by ThePhD** [comment]
Also note that Lua is single-threaded, so putting C++ to sleep inside or with your Lua state is essentially freezing everything's execution.

You're definitely looking for coroutines.

**Comment by grandemk** [comment]
> Note that "sleep" in C++ freezes the C++ thread. A C++ thread is not equal to a Lua thread.
Yes, I meant a 'sleep' function that doesn't really sleep but sets a timer and then stops the lua script call.

Alright, so with coroutines, with only one thread (I'm monothreaded for now) it would go like this:

lua script calls sleep function in c++
the sleep function uses coroutines to yield to the main loop
the mainloop yields back to the sleep function when the timer is finished and the script continues.
Is that right ?
thanks for the answer :)

**Comment by grandemk** [comment]
This is what I want to do:
https://github.com/ThePhD/sol2/issues/589

Thanks for the support :)
