### ISSUE TITLE
Getters/setters with multiple arguments

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#709]
We have a command call Entity::SetPosition in our API:
```
virtual void SetPosition(const Vec3& position, const bool global=false);
virtual void SetPosition(const float x, const float y, const float z, const bool global=false);
```
It would be nice if getters and setters worked with multiple arguments, so we could do something like this:
```
local box = CreateBox(world)
box.position = 1, 2, 3, true
```

**Comment by OrfeasZ** [comment]
This assignment syntax is actually not supported in lua. Every value on the right needs to have a corresponding variable on the left.

**Comment by JoshKlint** [comment]
Ah okay. Thanks!
