### ISSUE TITLE
Dynamic properties?

### ISSUE THREAD

**Issue by billw2012** [ThePhD/sol2#71]
I like the addition of properties for classes (and, more generally, this library). Is there any way to dynamically add them to my userdata? 

I thought perhaps having a table as an exposed member (don't know if that is possible) that I can dynamically add properties to would be a way to do it, but it appears properties only work with usertype. Some sort of example of what I want to do:
```C++
struct DynamicObject
{
    void update_dynamic_props()
    {
        for(auto& prop : props)
        {
            dynamic_props[prop] = sol::property([&]() { return prop.second; }, [&](const std::string& new_val) { prop.second = new_val; });
        }
    }

    sol::table dynamic_props;
    std::unordered_map<std::string, std::string> props;
};


void property_test()
{
    state lua;
    lua.new_usertype<DynamicObject>("DynamicObject",
      							     "dynamic_props", &DynamicObject::dynamic_props
							     );
```

**Comment by ThePhD** [comment]
Properties aren't supported as something that can be generally set on anything just yet. Having the ability for tables would probably be good.

I'll put this on the TODO list. But I'm also in the last 2 weeks of school.

**Comment by ThePhD** [comment]
Just a note: I haven't forgot about this feature, but I'm trying to figure out what else to do besides "properties work with not-userdata now". What is the observable effect for the code you wrote?

**Comment by ronald-reagan** [comment]
While we're talking about additions to sol::property, will sol::this_state be acceptable to be present in the arguments of methods passed to sol::property? As in,
```
class Test {
public:
  int a;

  int getA(sol::this_state L) { return a; }

  void setA(sol::this_state L, int n) { a = n; }
};

// ..
L.new_usertype<Test>("Test",
                       "a", sol::property(&Test::getA, &Test::setA));
```

**Comment by ThePhD** [comment]
I have no idea if that would work. I'm almost gonna say "No", since we specifically provide either 1 argument or 0 to the function. I'll be sure to tag that on as something to do after this week (PAAAPEEERS AND GRAAADES Ihateschool).

**Comment by ronald-reagan** [comment]
Yup, it doesn't work right now. With some slightly sneaky use of meta methods it should be usable but it's a bit ugly ;)

**Comment by billw2012** [comment]
What I really wanted is to bind dynamic properties directly to instances of userdata that are owned by the C++ side. However I figured that being able to add them to a table that is a member would be a useful compromise, assuming dynamic properties directly on the instance might not be doable.

**Comment by ThePhD** [comment]
What is a dynamic property? Something where you can rig up a userdata to have aribitrary keys that you don't set with a metatable / `new_usertype`? You do that by using the `__index` metamethod and the `__newindex` metamethod (__index = getter, __newindex = setter). E.g.:

````
struct dynamic {
     sol::object lookup_get ( const char* accessor ) {
            // look up data based on c-string accessor, get out the parameter
            // e.g.: thing[accessor]
     }

     sol::object lookup_set ( const char* accessor, sol::stack_object value ) {
            // set something based on accessor, using the value if you like
            // e.g.: thing[accessor] = value
     }
};

lua.new_usertype<dynamic>( "dynamic",
     sol::meta_function::index, &dynamic::lookup_get,
     sol::meta_function::new_index, &dynamic::lookup_set,
);
````

Try that. If that answers what you want, I think I'll close this issue then, because these methamethods are essentially what this functionality is for.

**Comment by ThePhD** [comment]
If you want it on a table, create a new metatable on that table and also set the index / __newindex values on it as well. You can access the metatable (and set it if you see its `nil`) from `sol` by doing `auto x = mytable[sol::metatable_key];` `if (!x) { /* no metatable: set it */ x = lua.create_table_with(); }`

**Comment by ThePhD** [comment]
I'm gonna assume that overriding `__index` and `__newindex` gives you the power you want. Good luck!

**Comment by Nava2** [comment]
I know this is old, but I think having a tutorial section with these examples would be useful.

**Comment by billw2012** [comment]
Sorry this isn't working for me:

```C++

struct PropertySet
{
	sol::object get_property_lua(const char* name, sol::this_state s)
	{
		MY_INFO("PropertySet::get_property %s", name);
		auto& var = props[name];
		return sol::make_object(s, var);
	}

	void set_property_lua(const char* name, sol::stack_object object)
	{
		MY_INFO("PropertySet::set_property %s", name);
		props[name] = object.as<std::string>();
	}

	std::unordered_map<std::string, std::string> props;
};

struct DynamicObject
{
	PropertySet& get_dynamic_props()
	{
		return dynamic_props;
	}

	PropertySet dynamic_props;
};


void property_test()
{
	using namespace sol;

	state lua;
	lua.new_usertype<PropertySet>("PropertySet"
								  , meta_function::new_index, &PropertySet::set_property_lua
								  , meta_function::index, &PropertySet::get_property_lua
								  );
	lua.new_usertype<DynamicObject>("DynamicObject"
									,"props", sol::property(&DynamicObject::get_dynamic_props)
									);
	lua.set_function("print", [](std::string str) {
		MY_INFO("lua print: %s", str.c_str());
	});

	lua.script(R"__(
obj = DynamicObject:new()
obj.props.name = 'test name'
print('name = ' .. obj.props.name)
)__");
}
```

I get exception "[string "..."]:3: sol: attempt to index (set) nil value "test name" on userdata (bad (misspelled?) key name or does not exist)".

It *was* working (when I was taking and returning std::strings instead of sol::objects) before I updated to latest (so I could have the make_object function to take and return arbitrary types), but now this.

**Comment by ThePhD** [comment]
My bad there. I pushed the fix. Code should work as advertised.

**Comment by billw2012** [comment]
Actually it's my fault, I don't know why I'm trying to work against your latest changes instead of last release. I rolled back to last release and it works fine now!

**Comment by ThePhD** [comment]
@Nava2 Examples are in the docs now and referenced in there as well. Thanks for the suggestion and thanks for this issue! I appreciate you guys reporting and working with me here.
