### ISSUE TITLE
How can I get the error text in when I use sol::coroutine ?

### ISSUE THREAD

**Issue by grandemk** [ThePhD/sol2#710]
Hi,

Using the script_file function, I get exception when something wrong happens in the lua script, but when I use the coroutine interface, I only have an enum showing that an error occured.
I would like to be able to show the same kind of errors as the script_file interface.

Here is what I'm trying to do:
https://gist.github.com/grandemk/3efd707fb77a1332f45e9839b650f0a1

Thanks

**Comment by Rochet2** [comment]
Calling the coroutine seems to return a sol::protected_function_result: `auto result = co();`
Check out the documentation for how to get the error message from it: https://sol2.readthedocs.io/en/latest/api/protected_function.html

**Comment by grandemk** [comment]
Thanks a lot for the pointers, I've updated the gist to show the answer to my question in case anyone as the same problem.
Thanks for such a great library :)
