### ISSUE TITLE
Problem with operator< when binding std::map using VS 2017

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#711]
The following code fails to compile with Visual Studio 2017 and sol 2.20.4 for reasons I don't understand. It complains about not being able to find a suitable `operator<`, which IMHO it should only need for the key type, which is `std::string` and therefore should have an appropriate `operator<`.

```C++
#include "sol.hpp"
#include <map>
#include <any>
#include <string>

int main() {
    typedef std::map<std::string, std::any> Map;

    sol::state lua;

    lua.new_usertype<Map>("Map",
        sol::constructors<Map()>(),
        "putString", [](Map &m, std::string const &k, std::string const &v){
            m.insert_or_assign(k, v);
        }
    );
}
```

BTW, I'm trying to come up with a smart way of handling `std::any`. I believe that `std::any` ought to have a special place in a binding of C++ to a dynamically typed language like Lua. Yet I'm finding it particularly hard to cope with. Any tip is welcome!

**Comment by ThePhD** [comment]
The way to handle std::any is to not touch std::any. It can be anything. The only way to know what it is is to poke at it, repeatedly, until you find out what type it is.

How many type checks am I supposed to do against it before I stop and just pass it through sol2 untouched? Do I check for int? What about short? long? long double? const char*? string_view? std::string? std::vector, and for what type-

You can see this rabbit hole doesn't have a bottom.

std::any is an extremely poor type, useful only for transporting through things like ABI or API boundaries.

**Comment by s13n** [comment]
> How many type checks am I supposed to do against it before I stop and just pass it through sol2 untouched?

I think it would be best to only support an essential set, i.e. the types that Lua supports natively. You then offer the possibility for a user to plug in code that handles the other cases.

For example, I wouldn't recommend to support anything in a `std::any` that doesn't own what it refers to, so `const char*` would be down to the user to cope with, as well as `std::string_view`. This leaves `std::string` to translate to/from a Lua string as the only sensible default.

The myriad of integer types is probably the major headache, when it comes to unpacking a `std::any`, but at least the set is bounded.

But I admit I haven't thoroughly thought this through.

**Comment by s13n** [comment]
Ah, and one more thing:

> The only way to know what it is is to poke at it, repeatedly, until you find out what type it is.

That's not strictly true. There's `type()`, which can be used to obtain type information for the value held inside. Maybe there's a way to use this in a smart way, instead of going through a long list of `any_cast<whatever>()` calls.

**Comment by ThePhD** [comment]
That returns `std::type_info`. sol does not use RTTI, so that throws out that approach already.

**Comment by ThePhD** [comment]
(Also, the last time I had a `static {blah}` like I would have a `static std::unordered_map`. somebody opened an issue against it saying it was non-reentrant as far as threading went, so that also throws that approach out too...)

**Comment by s13n** [comment]
FYI, gcc has similar complaints. It seems that `operator==` and/or `operator<` are being requested for the key/value pair, instead of the key alone. I haven't deciphered the error novel yet, to find where exactly it goes wrong.

**Comment by s13n** [comment]
A tidbit of potentially interesting information regarding this `std::any` binding business:

[https://www.boost.org/doc/libs/1_68_0/libs/hana/doc/html/index.html#tutorial-quickstart-any](url)

**Comment by ThePhD** [comment]
This code is compiling again on the latest sol2 (not sol3).

I can't seem to reproduce the problem anymore.

**Comment by ThePhD** [comment]
Tried on a few more platforms, could not reproduce.

**Comment by s13n** [comment]
Interesting. I have updated my Visual Studio Community 2017 to the current version 15.8.9, and the sol header to 2.20.5, and the problem persists. Which compilers have you tested with?
