### ISSUE TITLE
Runtime Error every time there's a Lua error

### ISSUE THREAD

**Issue by DCubix** [ThePhD/sol2#713]
Hi,
I'm using this library for my project but I did not want the program do die every time there's a Lua error. I need it to be printed to the console. How do I work around that? I've already set a panic and an exception handling function...
![](https://i.postimg.cc/qqXJdRdw/download_1.png)

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/blob/develop/examples/script_error_handling.cpp

**Comment by DCubix** [comment]
Oh alright. Thanks!
