### ISSUE TITLE
Any way to get the current line of code or an object?

### ISSUE THREAD

**Issue by isvogor-foi** [ThePhD/sol2#715]
I'm pushing objects created in c++ to Sol2 tables, and it works nicely. I own the objects in C++, while I use them in Lua. However I have a "monitoring" issue. 
Once I run a Lua script in C++, is there any way to know (from c++) which line of code I'm running? Or better yet, which object I'm using? 
Background:
In Lua, I'm using an objects function which has some duration (e.g. 10 sec or so), and therefore I also have a code which checks whether it is over, something like:
```
move.move_to(position1)
while not move.is_done() do end
```
Something tells me that there should be a smarter way to do this, or at least that this while should have a some amount of sleeping inside. I was thinking of:
1) either develop a C++ sleep function and push it to Lua
2) waiting from C++ until Lua is done, however, I don't know when it is done since my function calls are async. Therefore I would need to know which one of my C++ objects is used, or the line of code or something....

**Comment by OrfeasZ** [comment]
I'm not sure I understand what you're trying to achieve. You want to make your `move_to(x)` function (which I assume is bound to a C++ function) execute in the background and return immediately, and then use `is_done()` to check if it's done? There is a way to get the current line of execution, by using `lua_getstack()` and grabbing line information from the `lua_Debug` info, but that's fairly expensive and can mess with your order of execution.

**Comment by isvogor-foi** [comment]
You assume correctly. ```move_to(x)``` is an async function which runs in background and returns immediately. Then I use ```is_done``` from Lua to "delay" returning to C++.

**Comment by OrfeasZ** [comment]
I think I understand what you mean a bit better now, but correct me if I'm wrong: You call your lua script from C++, but you want to continue execution immediately (in C++), without having to wait for the script to finish? If that's the case then I guess you can either do this on a separate thread from C++ side (though you have to be careful not to mess with lua at the same time as other threads, so you'll need to implement appropriate locking), or use something like [coroutines](https://www.lua.org/pil/9.1.html) (sol2 has native support for them too).

**Comment by isvogor-foi** [comment]
Hmm... Well not quite like this. Actually I don't want C++ to continue. 
I'm calling Lua from C++, but Lua performs a async function which returns. Since it returns, lua continues and gets back to C++. Currently I'm pausing in lua until the function is done, however, this doesn't seem quite right.

**Comment by OrfeasZ** [comment]
Coroutines might still be the answer then, as you can query their execution status from C++ and act accordingly. See [here](https://sol2.readthedocs.io/en/latest/api/coroutine.html).

**Comment by isvogor-foi** [comment]
On the face of things this seems like something I need... Thanks!

**Comment by ThePhD** [comment]
I'm going to close this as solved. If you need more help, feel free to re-open.

**Comment by isvogor-foi** [comment]
Hi, again... I'm having trouble following the execution progress. 
So I'm pushing some C++ functions to lua, and then execute lua using sol2. And once I start executing lua code I have no idea what's happening inside. Is there any way to track it from C++?
It would be ideal if I could get the current line of code, as it is executed. 
I looked at the example `examples/environment_snooping.cpp` but it's not quite what I need. Although it seems it should do what I want.

**Comment by ThePhD** [comment]
You need to build out this functionality using Lua's debug hooks and similar. Sol2 does not come with this functionality out of the box.

**Comment by isvogor-foi** [comment]
I've followed the example of environment_snooping.cpp, and pushed the mentioned "complicated" function from the example to lua stack, having an idea that it will report the line number. And indeed it does, however it reports the number in which it is. So, I need to call it after each lua statement. Like so:
`do_something()
complicated() <--- to report status
do_something()
complicated() <--- to report status
do_something()
complicated() <--- to report status
`
Which results in outputs 2, 3, and 6. While this works and I could live with it, I need to artificially add those statements to my code. Do you have any suggestions as in to do it in a... let's say, more engineered way? - e.g. in parallel... so that my code executes normally, and I just get a pointer? similarly as one would when reading a file with raw pointers?
Thanks!

**Comment by Rochet2** [comment]
You can use a lua debugger like https://github.com/ToddWegner/clidebugger
Or attach a lua debugger like the one with zerobrane studio which requires luasocket
Or you could do something with the debug library http://www.lua.org/manual/5.3/manual.html#pdf-debug.sethook
Here is a small example, but I recommendreading the documentation of debug.sethook for more info.
```
debug.sethook(function(_, line)
print(line)
end, "l")
```
This code would print the line of any code that is executed after it. https://i.imgur.com/45ahOP2.png
