### ISSUE TITLE
sol::basic_reference::pointer leaves stack imbalanced

### ISSUE THREAD

**Issue by jquesnelle** [ThePhD/sol2#717]
`sol::basic_reference::pointer` leaves the stack with one more element than was on it when called. `lua_topointer` does not pop from the stack, it merely returns the pointer to the top. So, after `sol::basic_reference::pointer` is called, there is reference to the object `pointer` was called on the stack. Simple test case:

```c++
#include <sol.hpp>
#include <cassert>
#include <stdio.h>

struct vars {
    int boop = 0;
};

int main() {
    sol::state lua;
    lua.new_usertype<vars>("vars", "boop", &vars::boop);
    lua["obj"] = boop();
    auto ref = lua["obj"];
    int stackSize = lua.stack_top();
    const void* ptr = ref.pointer();
    printf("obj: %p\n", ptr);
    assert(lua.stack_top() == stackSize);
}
```

**Comment by ThePhD** [comment]
Woops.

I'll fix this soon!

**Comment by ThePhD** [comment]
Or you can fix it, thanks!
