### ISSUE TITLE
Attempt to index a nil value when calling a function.

### ISSUE THREAD

**Issue by hdt80** [ThePhD/sol2#72]
Before I try to call a function in Lua, I load the file using 

`state.open_file(path)`

Where path is a std::string of the relative path to the script. I know the loading works, because if I pick a file name that doesn't exist, an error is thrown. 

To call a function, I use

```
template<typename... Args>
void callFunc(const char* name, Args&&... args) {
    try {
        state.get<sol::function>(name).template call<void>(args...);
    } catch (sol::error e) {
        printf("Lua error: %s", e.what());
    }
}
```

This bit of code worked previously, but then I updated and the docs are outdated and doesn't work either. 

I'm actually calling it with 
```
callFunction("onUpdate", diff) // diff being an int here
```

The function inside the .lua file is
```
function onUpdate(diff)
    print("test");
end
```

If I'm doing something wrong, which I probably am, let me know and I'll be super grateful.

**Comment by ThePhD** [comment]
I cannot reproduce. This works fine (Lua 5.3.2, VC++):

````
#define SOL_CHECK_ARGUMENTS

#include "sol.hpp"

template<typename... Args>
void callFunc(sol::state& lua, const char* name, Args&&... args) {
	try {
		lua.get<sol::function>(name).template call<void>(args...);
	}
	catch (sol::error e) {
		printf("Lua error: %s", e.what());
	}
}

int main(int argc, char* const argv[]) {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.script(R"(
function onUpdate(diff)
	print("test");
end
)"
	);
	
	int diff = 20;
	callFunc(lua, "onUpdate", diff);

	return 0;
}
````

**Comment by ThePhD** [comment]
`open_file` is from the old `sol` repository. Are you sure you're using the correct code? The new function is called `script_file`, and the other one has been deprecated and removed in `sol 2.x.x`.

**Comment by hdt80** [comment]
I was using 'load_file`, sorry for the confusion. 

Using `script_file` works just fine, I thought from reading the docs that calling `script_file` would run the script in the file. 

Thanks for the help! Fixed it. I appreciate how quickly you helped me.
