### ISSUE TITLE
Assigning usertype instance in the table and accessing that, but can't.

### ISSUE THREAD

**Issue by liliilli** [ThePhD/sol2#720]
Hello, I'm making a game framework with your lua wrapping library. 
I always thanks yours but I stuck some point that binds my C++ structure to lua's table. 

Here is my base table script code of lua. 
All script component that has its own lua script must be derived from this. 
(My game framework is consist of actor (game object in unity, AActor in UE4) and components that bind to valid actor instance in C++ memory.)
``` lua
LDyScript = {
    mActor = nil
  , new = function(self, v)
      o = v or {}
      setmetatable(o, self)
      self.__index = self
      return o
    end

  , __pDyInitializeWith = function(self, actorInstance)
      self.mActor = actorInstance
    end

  , Initiate = function(self) end
  , Start = function(self) end
  , Update = function(self) end
  , Destroy = function(self) end
  , OnEnabled = function(self) end
  , OnDisabled = function(self) end
}
```
like this,
``` lua
-- Derived script table. 
-- self.mActor duplication is passed now to concentrate to resolving problem.
TestScript1 = LDyScript:new()

function TestScript1:Initiate()
    -- here are some code.
    local logInstance = MDyLog:GetInstance()
    logInstance:PushLog(EDyLogLevel.Critical, "TestScript 1 Initiate")
    logInstance:PushLog(EDyLogLevel.Debug, "TestScript 1 Initiate : " .. self.mActor:GetActorName())
end
-- ...
```
So I also set usertype of `FDyActor` for lua scripting into `sol::state` before calling aboves.
``` c++
///
/// @brief
/// @param  lua
///
void DyInitilaizeFDyActor(sol::state& lua)
{
  /// Binding lua
  lua.new_usertype<dy::FDyActor>("FDyActor",
      /// Base
      sol::base_classes, sol::bases<FDyObject>(),
      /// Cosntructors
      "new", sol::constructors<FDyActor(void)>(),
      ///
      "Activate",     &FDyActor::Activate,
      "Deactivate",   &FDyActor::Deactivate,
      "IsActivated",  &FDyActor::IsActivated,
      "GetActorName", &FDyActor::GetActorName // This function just return const std::string&
  );
}
```
Finally, below is problem invocation point that I road a script file from outside, bind to `sol::state`, extract derived script `sol::table` from this, and bind `FDyActor` instance reference to `self.mActor` by calling `LDyScript.__pDyInitializeWith` as argument 1.
``` c++
// ... some codes ...
MDY_NOTUSED auto _    = luaInstance.safe_script_file(validScriptMetaInfo.mScriptPath);
this->mScriptInstance = luaInstance[this->mScriptName];
this->mScriptInstance["__pDyInitializeWith"](*this->GetBindedActor()); // <- Problem!
this->mIsScriptInstanceBinded = true;
// ... some codes ...
```
But what I get is exception error, from `sol.hpp line 20837`, and message was
`lua: error: [string "..."]:12: sol: attempt to index (set) nil value "mActor" on userdata (bad (misspelled?) key name or does not exist)`.

I stuck that point, so studied about metatable, and table on lua official homepage shortly. After this, I simulated my problem in [lua demo](https://www.lua.org/cgi-bin/demo) just using lua's type instead of C++ binded customized usertype... and It works in demo page.

So I think that it's not lua's syntax problem but library problem. I used sol2 library improperly as I thought. How I can set or assign my usertype instance to the arbitary table in lua script?

Ps: I'm not a english native, so may have some difficulties to understand my issue. 😫 I'll do my best to explain what happned in detail as time goes on. Thanks!

**Comment by squeek502** [comment]
You are calling `__pDyInitializeWith` with `*this->GetBindedActor()` as the `self` parameter, not the `actorInstance` parameter.

You need to pass `self` explicitly, like so:
```
this->mScriptInstance["__pDyInitializeWith"](this->mScriptInstance, *this->GetBindedActor());
```

You could see the problem by adding a print:
```
  , __pDyInitializeWith = function(self, actorInstance)
      print(tostring(self), tostring(actorInstance))
      self.mActor = actorInstance
    end
```

**Comment by liliilli** [comment]
Thanks! I changed my code to call function explicitly, and everything starts going well. 😃

**Comment by liliilli** [comment]
Thanks! I changed my code to call function explicitly, and everything starts going well. 😃
