### ISSUE TITLE
unable to convert table to std::pair<int, int> with .get<int, int>

### ISSUE THREAD

**Issue by poww10s** [ThePhD/sol2#726]
Using the example in the documentation: 
`#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

#include <tuple>
#include <utility> // for std::pair

int main () {

        sol::state lua;
        lua.script_file( variables.lua );

        // the type "state" behaves exactly like a table!
        bool isfullscreen = lua["config"]["fullscreen"]; // can get nested variables
        sol::table config = lua["config"];

        // can also get it using the "get" member function
        // auto replaces the unqualified type name
        auto resolution = config.get<sol::table>( "resolution" );

        // table and state can have multiple things pulled out of it too
        std::pair<int, int> xyresolution = resolution.get<int, int>( "x", "y" );
        // As an example, you can also pull out a tuple as well
        std::tuple<int, int> xyresolutiontuple = resolution.get<int, int>( "x", "y" );

        return 0;
}`

![image](https://user-images.githubusercontent.com/6687517/47949493-5a2f6780-df1a-11e8-8957-1d06a3c61d65.png)

unable to compile due to this error:

`src/main.cpp:31:68: error: conversion from 'sol::stack::getter<std::tuple<int, int>, void>::R' {aka 'std::tuple<int, int>'} to non-scalar type 'std::pair<int, int>' requested
         std::pair<int, int> xyresolution = resolution.get<int, int>( "x", "y" );`

Same warnings appear if I comment out the std::pair line, but it compiles.

IDE: VS Code. Compiler, Mingw64

**Comment by poww10s** [comment]
Okay so just replacing `auto` with `sol::table` in the line `auto resolution = config.get<sol::table>( "resolution" );` fixes all these issues. But why is this the case? shouldn't auto work here? isn't that the point of auto? looking closer, using auto sets resolution to the type `<error-type>`.

**Comment by poww10s** [comment]
Nevermind, it fixes the issue assigning it to a tuple, but std::pair still does not work

**Comment by ThePhD** [comment]
std::pair's constructors were borked recently by some changes to the library's conversion from tuple -> pair. Can't help anyone: this was reported before in the Discord, I just need to fix the sample to use tuple or change how the constructed line works.

**Comment by ThePhD** [comment]
This is outside of my control.

I can't affect pair/tuple construction, but I did fix the examples and tutorials. Thanks for sharing with me.

Let me know if anything else goes wrong.
