### ISSUE TITLE
Retrieve C++ object?

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#727]
This is presently how I retrieve objects off the stack:
```
Object* VirtualMachine::ToObject(const int index)
{
	void* v = lua_touserdata(L, index);
	return (Object*)v;
}

o = vm->ToObject(-1);
if dynamic_cast<Vec2*>(o)...
```
I was wondering if there was a better way to check the object type with sol? Is there something like sol::getuserdataclass()?

**Comment by ThePhD** [comment]
Use `sol::stack::get<Object*>`. It does proper base lookup if you've set base classes.

The stack API is documented here: https://sol2.readthedocs.io/en/latest/api/stack.html
