### ISSUE TITLE
Possible problem with runtime functions.

### ISSUE THREAD

**Issue by realj3** [ThePhD/sol2#729]
If I add to derived class runtime function with the name that is already defined (runtime) in base class, and base class has at least one member variable bound, I get debug assertion.

1. Create two simple classes hierarchy and register them the with new_usertype.
2. Base class should contain variable or sol::property binding.
3. Add functions at runtime to the both classes - the thirst to the base class, the second to the derived. Both function should have the same name.
4. The program will crash on second add as vector "runtime" in line 18574 has zero size.

I use sol 2.20.4 and Visual Studio 2017 (15.8.9)

```
#include <sol.hpp>

class A
{
public:
	int x;
};

class B : public A
{
};


int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<A>("A",
			"x", &A::x                   //no crash without this
		);

	lua.new_usertype<B>("B",
		sol::base_classes, sol::bases<A>()
		);

	lua.script("function A:c() print('A') end");
	lua.script("function B:c() print('B') end");  //there is crash here.
}
```

**Comment by ThePhD** [comment]
This is fixed in the latest.
