### ISSUE TITLE
Exception message is lost when thrown from stateful lambda and C++ compiled LUA

### ISSUE THREAD

**Issue by mgibula** [ThePhD/sol2#731]
Hi,
when testing Sol 2.20.5 I've found inconsistency that I believe is a bug. For starters I'll note that I'm using Lua 5.1, compiled with C++ compiler, so my understanding is that lua_error() will propagate error using exception rather than longjmp().

The following program (compiled with -DSOL_USE_BOOST -DSOL_USING_CXX_LUA -DSOL_EXCEPTIONS_ALWAYS_UNSAFE -DSOL_CHECK_ARGUMENTS) reproduces the problem:
```
#include "sol.hpp"

#include <iostream>

void will_throw() {
        throw std::runtime_error("oh no not an exception!!!");
}

int main() {
        sol::state lua;
        lua.open_libraries(sol::lib::base);

        int a = 1;

        // This one works
        // lua.set_function("will_throw", &will_throw);

        // This one works as well
        // lua.set_function("will_throw", []() {
        //    will_throw();
        // });

        // capture 'a' to force a stateful lambda
        lua.set_function("will_throw", [&a]() {
            a = 66;
            will_throw();
        });

        sol::protected_function_result pfr2 = lua.safe_script(R"_(will_throw())_", &sol::script_pass_on_error);

        sol::error err2 = pfr2;

        std::cout << std::endl;
        std::cout << "result from will_throw from constructor: " << err2.what() << std::endl << std::endl;

        return a;
}
```
When "will_throw" is defined from function pointer or a stateless lambda, the output is "result from will_throw from constructor: oh no not an exception!!!", but when using stateful lambda, the output is "result from will_throw from constructor: caught (...) exception". 

From what I'm able to tell from backtrace, in stateful lambda case, there are two trampolines, nested in each other. So the first one catches std::exception, puts error message on stack and calls lua_error() - which - because Lua is compiled as C++ - will throw exception of some unspecified type, that gets catch in outer trampoline in catch (...) block, which puts generic error message and calls lua_error() again.

I've tried using SOL_EXCEPTIONS_SAFE_PROPAGATION define, but results are even worse, with a panic "An error occurred and panic has been invoked: stack index 1, expected string, received function" for all cases. 

I have to admit, I don't really know what is the use case for this define - if LUA is compiled as C++ it will swallow all exceptions (as it cares only for exception it throws, not any others) and leave no message on stack, so trampolines seem to be always needed.

**Comment by ThePhD** [comment]
This is fixed.
