### ISSUE TITLE
std::optional<T> does not behave like a nil-able field in a usertype

### ISSUE THREAD

**Issue by porpoises** [ThePhD/sol2#733]
Test case:
```cpp
struct Foo {
  std::optional<int> v;
};

sol::state lua;
lua.new_usertype<Foo>("Foo", "v", &Foo::v);
lua.script(R"(
  foo = Foo.new()
  foo.v = 1
)");
```

This causes the following error:

```
[sol2] An error occurred and panic has been invoked: [string "..."]:3: stack index 3, expected userdata, received number: value is not a valid userdata (bad argument into 'void(std::optional<int>)')
```

Is there a way to make Sol handle `std::optional<T>` as if it was not wrapped, except allowing fields to be set to nil?

**Comment by porpoises** [comment]
With some coaxing, I managed to write a wrapper to convert between `sol::optional` and `std::optional` on read/write:

```cpp
template <typename R, typename T>
auto nullable_member(std::optional<R> T::*m) {
    return sol::property([m](T const& self) {
        return self.*m ? sol::optional<R>((self.*m).value()) : sol::nullopt;
    }, [m](T& self, sol::optional<R> v) {
        self.*m = v ? std::optional<R>(std::move(v.value())) : std::nullopt;
    });
}
```

... but it's not the prettiest thing to have to apply it everywhere a `std::optional` field is :( Unfortunately, I can't figure out where the correct extension point for that would be to make a pull request for.

**Comment by ThePhD** [comment]
I'm so glad I'm clairvoyant, I just added a getter/pusher for regular `std::optional` to latest.

Extension points are added with customization points. As described in the tutorial and examples: https://sol2.readthedocs.io/en/latest/tutorial/customization.html

This fix is already on latest but not in the single include.

**Comment by ThePhD** [comment]
Pull latest, now included in the single include and part of tests.

**Comment by porpoises** [comment]
Hm, I'm not sure if I'm missing something here, but I still get the same error. I'm at commit `55e92056c1d31300b82e52ac863ab8f7a9c8a541` with `SOL_CXX17_FEATURES` defined.

This works fine though:

```cpp
lua["test"] = std::optional<int>(1);
lua.script("test = test + 1")
```

... but when an `std::optional` is embedded within a struct, it seems to not like it.

I'm using the accursed MSVC2017, if that makes any difference here.

**Comment by ThePhD** [comment]
Now it's REALLY fixed. Pull 2.20.6.

**Comment by porpoises** [comment]
Awesome, it works now. Thanks!
