### ISSUE TITLE
trouble with sol::optional with userdata

### ISSUE THREAD

**Issue by thinlizzy** [ThePhD/sol2#74]
I just updated to the latest sol2 code and I started to get errors in a previous code that was relying on sol::optional

Here is the stack trace:

In file included from D:\diego\progs\c++\lib\sol2/sol/table.hpp:25:0,
                 from D:\diego\progs\c++\lib\sol2/sol/state_view.hpp:26,
                 from D:\diego\progs\c++\lib\sol2/sol/state.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol.hpp:25,
                 from ..\src\lua\LuaLoader.h:7,
                 from ..\src\lua\LuaLoader.cpp:4:
D:\diego\progs\c++\lib\sol2/sol/table_core.hpp: In instantiation of 'decltype(auto) sol::basic_table_core<<anonymous>, T>::traverse_get_deep_optional(int&, Key&&) const [with bool global = false; T = sol::optional<tk::basic_point<int> >; long long unsigned int I = 0ull; Key = const char (&)[9]; bool top_level = false; base_t = sol::reference]':
D:\diego\progs\c++\lib\sol2/sol/table_core.hpp:136:59:   required from 'decltype(auto) sol::basic_table_core<<anonymous>, T>::traverse_get_optional(std::true_type, Keys&& ...) const [with bool global = false; T = sol::optional<tk::basic_point<int> >; Keys = {const char (&)[9]}; bool top_level = false; base_t = sol::reference; std::true_type = std::integral_constant<bool, true>]'
D:\diego\progs\c++\lib\sol2/sol/table_core.hpp:84:53:   required from 'decltype(auto) sol::basic_table_core<<anonymous>, T>::tuple_get(sol::types<U>, std::index_sequence<I>, Keys&&) const [with Ret = sol::optional<tk::basic_point<int> >; long long unsigned int I = 0ull; Keys = std::tuple<const char (&)[9]>; bool top_level = false; base_t = sol::reference; std::index_sequence<I> = std::integer_sequence<long long unsigned int, 0ull>]'
D:\diego\progs\c++\lib\sol2/sol/table_core.hpp:186:25:   required from 'decltype(auto) sol::basic_table_core<<anonymous>, T>::get(Keys&& ...) const [with Ret = {sol::optional<tk::basic_point<int> >}; Keys = {const char (&)[9]}; bool top_level = false; base_t = sol::reference]'
..\src\lua\LuaLoader.cpp:68:58:   required from 'T LuaLoader::getOpt(sol::table, K&&) [with T = tk::basic_point<int>; K = const char (&)[9]; sol::table = sol::basic_table_core<false, sol::reference>]'
..\src\lua\LuaLoader.cpp:211:59:   required from here

**D:\diego\progs\c++\lib\sol2/sol/table_core.hpp:114:52: error: inconsistent deduction for 'decltype(auto)': 'sol::optional<tk::basic_point<int> >' and then 'sol::optional<tk::basic_point<int>&>'
         return stack::get<T>( base_t::lua_state( ) );**
                                                    ^
In file included from D:\diego\progs\c++\lib\sol2/sol/optional.hpp:28:0,
                 from D:\diego\progs\c++\lib\sol2/sol/types.hpp:27,
                 from D:\diego\progs\c++\lib\sol2/sol/reference.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol/object.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol/proxy.hpp:26,
                 from D:\diego\progs\c++\lib\sol2/sol/table_core.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol/table.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol/state_view.hpp:26,
                 from D:\diego\progs\c++\lib\sol2/sol/state.hpp:25,
                 from D:\diego\progs\c++\lib\sol2/sol.hpp:25,
                 from ..\src\lua\LuaLoader.h:7,
                 from ..\src\lua\LuaLoader.cpp:4:
D:/diego/progs/c++/lib/sol2/Optional/optional.hpp: In instantiation of 'constexpr const T& sol::optional<T>::operator*() const [with T = tk::basic_point<int>]':
D:/diego/progs/c++/lib/sol2/Optional/optional.hpp:567:20:   required from 'constexpr T sol::optional<T>::value_or(V&&) const & [with V = tk::basic_point<int>; T = tk::basic_point<int>]'
..\src\lua\LuaLoader.cpp:69:53:   required from 'T LuaLoader::getOpt(sol::table, K&&) [with T = tk::basic_point<int>; K = const char (&)[9]; sol::table = sol::basic_table_core<false, sol::reference>]'
..\src\lua\LuaLoader.cpp:211:59:   required from here
D:/diego/progs/c++/lib/sol2/Optional/optional.hpp:200:97: error: use of 'sol::optional<T>::operator*() const::<lambda()> [with T = tk::basic_point<int>]' before deduction of 'auto'
 # define TR2_OPTIONAL_ASSERTED_EXPRESSION(CHECK, EXPR) ((CHECK) ? (EXPR) : ([]{assert(!#CHECK);}(), (EXPR)))
                                                                                                 ^
D:/diego/progs/c++/lib/sol2/Optional/optional.hpp:544:12: note: in expansion of macro 'TR2_OPTIONAL_ASSERTED_EXPRESSION'
     return TR2_OPTIONAL_ASSERTED_EXPRESSION(initialized(), contained_val());
            ^

`Position` is the same as `tk::basic_point<int>`, which has only `int x; int y;` as data members
`lua.new_usertype<Position,int,int>("Position");`

then I am reading a position object from a sol::table instance like this

`position = getOpt<Position>(luaTable,"position");`

getOpt relies on sol::optional to return a default value if a value is not found in the table, but it is no longer working due to errors on getting the sol::optional instance

```
template<typename T, typename K>
T LuaLoader::getOpt(sol::table tb, K && key)
{
	auto res = tb.get<sol::optional<T>>(std::forward<K>(key));
	return res.value_or(opt_traits<T>(lua).getDefault());
}

template<typename T>
struct opt_traits {
	explicit opt_traits(sol::state & lua) {}
	T getDefault() { return T{}; }
};
```

**Comment by thinlizzy** [comment]
to add more information, that same getOpt function works properly when T is int 

(it was working properly when T was an object too before I git pulled from both sol2 and Optional repos)

**Comment by thinlizzy** [comment]
FYI, this is the workaround I adopted to replace my sol::optional usage

```
template<typename T, typename K>
T LuaLoader::getOpt(sol::table tb, K && key)
{
	sol::object result = tb.get<sol::object>(std::forward<K>(key));
	if( result.get_type() == sol::type::nil ) return opt_traits<T>(lua).getDefault();
	return result.as<T>();
}

```

**Comment by ThePhD** [comment]
Well, this brought me on quite the adventure with optional. I managed to fix this plus some unrelated bugs. Will push soon.

**Comment by ThePhD** [comment]
Release here: https://github.com/ThePhD/sol2/releases/tag/v2.5.2
