### ISSUE TITLE
WRITE-MODIFY variables to the Lua file

### ISSUE THREAD

**Issue by mumin16** [ThePhD/sol2#740]
I want to WRITE-MODIFY variables to the Lua file.  doesn't sol2 include any way to do this?
or should I use the classic c++ i/o?

**Comment by ThePhD** [comment]
sol2 is not an IO library. It allows you to manipulate the Lua VM, as it exists and is embedded in your applications and libraries.

If you need to modify variables to a Lua file, an IO layer that will serialize your Lua stuff to a file, or just do it by hand. Serializing to a Lua file from sol2 by handling tables and using a recursive table.for_each is most certainly possible.
