### ISSUE TITLE
Add safe_script to quick and dirty

### ISSUE THREAD

**Issue by hsdk123** [ThePhD/sol2#743]
Hi, I've been using sol2 in development / production for a while, and it seems that what new developers, including myself, seem to slip up on most is working our heads around the initial unexpected exceptions, aborts, etc. that can arise due to invalid lua scripts.

Scripts can very easily become full of bugs or syntax errors especially when going through continuous iterations for ex. game mechanics.

I thus would like to propose at the very least that 'safe_script' be added into the quick and dirty tutorial, s.t. developers can see a reference to the more safer, and thus contained version of the commands that might be more preferable for use during script development. 

A larger section on the difference between safe / protected vs normal concepts in the quick and dirty tutorial would also make things much more understandable and allow the developer to know of edge cases that should be kept in mind when making decisions on implementation.

**Comment by ThePhD** [comment]
`sol::function`, `.script`, and all the other boring-named functions default to the safe versions with the define `SOL_CHECK_ARGUMENTS` on (you can specifically trigger it with `SOL_SAFE_FUNCTION`). All examples include `SOL_CHECK_ARGUMENTS` and I have gotten most examples and tutorial documentation to include that at the very top of each snippet.

As far as writing more documentation, pull requests welcome? I can't read anyone's mind for what they want to see in the tutorials, or how they want it to be written. I explain very thoroughly about exceptions, errors, invalid aborts, etc. in the exceptions and errors documentation:

https://sol2.readthedocs.io/en/latest/errors.html#running-scripts
https://sol2.readthedocs.io/en/latest/exceptions.html

Anything more, I'd love some examples or more pointed suggestions.
