### ISSUE TITLE
Sharing variables/functions/etc between Sol states running in different threads

### ISSUE THREAD

**Issue by benoves** [ThePhD/sol2#750]
I've used two applications that work like this:

1. It has a Setup, where you set up variables and their values.

2. You can create multiple scripts that run simultaneously, e.g. script1, script2, script3. The scripts can access the Setup variables, but the variables set in a given script can only be accessed by the script in question. You also cannot create a function in these scripts: you can only use library functions (see below) and C++ functions registered for Sol usage.

3. You can add a library to the library folder, all .lua libraries are loaded on program startup and their methods (variables, functions, etc) can be used in the scripts.

I'm pretty sure the developer doesn't use coroutines because it's not efficient in this scenario where speed is a must and running multiple simultaneous scripts is common. It can only be achieved by OS multithreading (std::thread), where each thread has its own sol state.

How does the developer achieve this? The Setup variables are not hardcoded, and neither are the methods (variables, functions, etc) in the library. Anyone can write a library and make it available to the scripts by placing it in the library folder. If you modify a library, you must close and open the program again. They are loaded on program startup.

I've gone through the documentation but didn't find an answer, and this question is so common. You would help the Sol community greatly if you added relevant info in the docs. Indeed, many people interested in Lua could switch to Sol if they find a resolution to this common question.

**Comment by ThePhD** [comment]
This isn't a Sol problem or a Lua problem: you could insert any programming language and you'd still have issues.

You need to serialize between states, which would imply locking or similar. You serialize to some common in-between format, and then serialize into the other state, which in a multi-threading scenario would imply locking. None of this is Lua or sol-specific.

**Comment by ThePhD** [comment]
To help in knowing what things users stick in your state, you can sandbox everything that do by having a `sol::environment`, which already has several examples and docs describing its functionality. This would allow you to specifically control and introduce what is inside the state for a given user, and as such serialize between states as needed.

For functions bound through sol2's API (they will all be cfunction's, which are identifiable with type checks), those are opaque blobs that we perform a myriad of optimizations on. For userdata, you need to add a specific point of serialization to transfer from 1 state to another. Again, locking is also your problem: sol2 cannot assume any architecture on your part and do this for you.

**Comment by ThePhD** [comment]
For sol2-added functions, asking the user to add the same functions is solvable: call the same Setup and give them the state as a parameter.

For Lua-made functions, I don't know what it means to serialize between them. Ask on the Lua mailing list: it'll probably end up being platform and Lua-flavor specific (LuaJIT versus Lua). (Or just do the same thing and have a Setup Lua function called on the right state).
