### ISSUE TITLE
Catch submodule problem

### ISSUE THREAD

**Issue by fwjavox** [ThePhD/sol2#753]
There is a problem with the `Catch` git submodule.
It is listed in `.gitmodules` but the `Catch` directory is not part of the repository.
Reproducing the problem is easy with a clean git clone:
```
git clone https://github.com/ThePhD/sol2.git
git submodule
```
The last command should list `Catch` as a submodule but it does not because the `Catch` directory is missing. Also `git submodule init` and `git submodule update` don't work due to this.
To fix the problem simply call
```
git submodule add https://github.com/philsquared/Catch.git
```
again.

@ThePhD Would you mind to commit this to the repository?

**Comment by ThePhD** [comment]
I mean I kind of wanted to throw out the Catch dep, honestly. It's just used for building tests.

**Comment by fwjavox** [comment]
The Yocto build system reads the submodules from the `.gitmodules` file and calls git to get the commit hash of each of them. This fails for the Catch submodule so the whole build fails.

**Comment by ThePhD** [comment]
I'll destroy the submodule proper.

**Comment by ThePhD** [comment]
Fixed.

**Comment by fwjavox** [comment]
Thank you!
