### ISSUE TITLE
Copying data to tables

### ISSUE THREAD

**Issue by kotbegemot** [ThePhD/sol2#756]
Here is an example of what I want to make work.
```C++ 14
#include <iostream>
#include <deque>
#include <sol.hpp>

int main() {
    sol::state lua;
    lua.open_libraries(sol::lib::base);

    lua.set_function(
            "test",
            [](sol::table jobs) {
                std::deque<int> d ={1,2,3,4,5,6,7};
                std::copy(std::begin(d),std::end(d),std::begin(jobs));

            }
    );

    lua.script(R"(d={}
    test(d)
    for key in pairs(d) do
       print(d[key])
    end

	)");
    return 0;
}
```

**Comment by kotbegemot** [comment]
@ThePhD

**Comment by kotbegemot** [comment]
An example of the use that you want to redo. https://github.com/smart-cloud/RocketJoe/blob/9fc5cde14bf2ed7fb614495700c0d13379054c05/services/lua_engine/lua_sandbox.cpp#L103

**Comment by ThePhD** [comment]
sol2 table iterators are forward-only input iterators, one of the weakest category of iterators. There are no output iterators for sol2's tables; sorry.

You can emulate this by using a ranged-for loop and serializing the elements into the table. `table.add` might do what you want best, but Lua table counts are O(log N) not O(1), and each .add() will call it. It might be best to write it like this:

```
    lua.set_function(
            "test",
            [](sol::table jobs) {
                std::deque<int> d ={1,2,3,4,5,6,7};
                std::copy(std::begin(d),std::end(d),std::begin(jobs));
                int sz = jobs.size();
                for ( auto&& v : d ) {
                    jobs[sz] = std::move(v);
                    ++sz;
                }
            }
    );
```

**Comment by kotbegemot** [comment]
@ThePhD Thank.
