### ISSUE TITLE
Set an environment for a load_result object?

### ISSUE THREAD

**Issue by sagunkho** [ThePhD/sol2#761]
Hello,

Great work on the project! I'm new to Lua and its C API. What I'm doing is to set an environment for a load_result, and it isn't compiling. What am I doing wrong? and What is the best way to save the script and run in later in within different environments. Also, what exactly is the target type expected in `set_on(const T& target)` or `set_environment(const basic_environment<E>& env, const T& target)` ?

My code is as follows - 
```
	sol::load_result script = lua.load(R"(
			   print(str_arr[3])
			   str_arr[3] = str_arr[3] .. ': modified'
			   print(str_arr[3])
				print(TEST_VAR)
			   )");

	sol::environment env(lua, sol::create, lua.globals());
	env["TEST_VAR"] = 24;

	env.set_on(script);
	script();
```

Thanks in advance.

**Comment by ThePhD** [comment]
`load_result` is not an actual function, it just converts to one. Properly convert to `sol::function` and set the environment on that. Or, just use `lua.script` with the proper environment overload and use that.

**Comment by sagunkho** [comment]
@ThePhD Thanks a lot, it worked!

```
	sol::environment env(lua, sol::create, lua.globals());
	env["TEST_VAR"] = 24;

	sol::function f = script;
	env.set_on(f);
	f();
```
