### ISSUE TITLE
Bind member function to existing (non-copyable) object

### ISSUE THREAD

**Issue by badeiomme** [ThePhD/sol2#767]
It is not possible to call set_function when the provided object is not copyable.

```c++
class c
{
public:
	c() = default;
	c(const c &) = delete;
	c(c &&) = delete;

	int myfunc() { return 1; }
};

int main(int argc, char **argv)
{
	sol::state lua;
	c c_instance;

	lua.set_function("myfunc", &c::myfunc, c_instance);
}
```

**Comment by ThePhD** [comment]
I mean... no. What magic am I supposed to do that makes this work, you've cut off every avenue that I can use to make this happen?

If you can promise to keep `c_instance` alive, you can use `std::ref` or `&c_instance` to refer directly to that variable's memory address. If it goes out of scope, calling the function you set it with is UB. If the memory that is being pointed to dies (e.g, you `std::unique_ptr<c> ptr_c_instance = std::make_unique<c>();` then pass `ptr_c_instance.get()`),  and then that memory location dies, it's UB.

**Comment by badeiomme** [comment]
I'm well aware that I have to keep the object alive, i left this out to keep the example simple.
Using std::ref works well - I didn't come up with the idea. Thanks for pointing it out!
