### ISSUE TITLE
sol2 custom return type? 

### ISSUE THREAD

**Issue by gryphun** [ThePhD/sol2#77]
Is there some kind of wrapper return type I can use to go from C++ to LUA?  I have a class like below.  I feel like I'm missing some sol specific return type that would solve my problems.

```

class Param {
	int i;
	float f;
	string s;
	
	type	_type
	
	void getValue( const std::string &key, int &value ) {
		value = i
	}
	
	
	void getValue( const std::string &key, float &value ) {
		value = f
	}
		
	void getValue( const std::string &key, std::string &value ) {
		value = s;
	}
	
	sol:special_ret_type getValue(  const std::string &key ) {
		sol:special_ret_type ret;
		if( _type == FLOAT )
			ret.set( f )
		else if( _type == INT )
			ret.set( i )
		else if( _type == STRING )
			ret.set( s )
			
		return ret;
	}
}
```

I want to bind this function to LUA. and return a value of the appropriate type.  Right now I've set something like this up always return a string, but that obviously requires coverting any numeric type which is not optimal.
    sol:special_ret_type getValue(  const std::string &key ) {

**Comment by Nava2** [comment]
[`sol::object`](http://sol2.readthedocs.io/en/latest/api/object.html) perhaps?

**Comment by ThePhD** [comment]
We don't have a type for this, but we should.

Anyone got any ideas for a good name?

**Comment by ThePhD** [comment]
As a temporary workaround,

````
sol::object getValue(  sol::this_state l, const std::string &key ) {
        lua_State* L = l;
        if( _type == FLOAT )
            stack::push( L, f );
        else if( _type == INT )
            stack::push( L, i );
        else if( _type == STRING )
            stack::push( L, s );

        return sol::object(L, -1); // pull object off of top of the stack
    }
````

Stack manipulation is, however, not fun, so we definitely need a good name...

**Comment by ThePhD** [comment]
Some names:

`sol::return_object`
`sol::value`
`sol::something`

... I like `sol::return_object`, for now. Maybe `sol::return_value`?

**Comment by gryphun** [comment]
Thanks for the prompt response. 

I like sol::return_object

**Comment by OrfeasZ** [comment]
Shouldn't `sol::object` be also used for such use cases, since (from my understanding at least, correct me if I'm wrong) it already encapsulates an underlying type? I think being able to use it as both a generic parameter and return type makes the whole implementation process a bit more streamlined.

**Comment by ThePhD** [comment]
It doesn't push or pop something from the stack. It just references something that already exists. Which is a bit unfortunately, but that's the way the cookie's crumbled, I suppose?

**Comment by OrfeasZ** [comment]
I understand that it doesn't do that right now, but what I'm suggesting is adding support for that functionality to it instead of introducing a completely new type, in order to streamline development. 

For example, think of a case where you have a function that accepts a `sol::object` as a parameter and you want to return that same object at the end of the function without having to re-encapsulate it.

**Comment by ThePhD** [comment]
You can do that already.

````
sol::object pass_through ( sol::object a ) {

}

lua.set_function( "pass", pass_through );
lua.script( "print(pass(1)) print(pass("WOOF")) print(pass(22.1))" );
````

**Comment by ThePhD** [comment]
Though... you may be onto something. Rather that a new type, we can make it a new _function_.

````
template <typename T>
sol::object return_object( lua_State* L, T&& value ) {
    sol::stack::push(L, std::forward<T>(value));
    sol::object r = stack::pop<sol::object>(L);
    return r;
}
````

**Comment by ThePhD** [comment]
Think I'm going to take the function approach and make it `make_object`.

**Comment by ThePhD** [comment]
Get it here: https://github.com/ThePhD/sol2/releases/tag/v2.5.3
