### ISSUE TITLE
Suggestion/possible solution for Unreal 4 check macro BS

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#771]
Sorry for not making it a pull request itself, i don't have Git installed on this pc. This pull request
https://github.com/ThePhD/sol2/pull/770
mentions that the check macro from Unreal 4 has changed and you seem to be a bit displeased that you have to change your files because of them too.

I did a bit of research : Unreal 4 uses MSVC as its default compiler.
MSVC supports the `#pragma push_macro` and `#pragma pop_macro` preprocessor actions, which saves and restores the previous definitons of the check() macro (i think GCC and clang support it too).

I just tested this and it seems that it works perfectly fine:
At the top of the sol.hpp (i'm using single header)
```C++
#if defined(UE_BUILD_DEBUG) || defined(UE_BUILD_DEVELOPMENT) || defined(UE_BUILD_TEST) || defined(UE_BUILD_SHIPPING) || defined(UE_SERVER)
#define SOL_INSIDE_UNREAL 1
#endif // Unreal Engine 4 bullshit
#if defined(SOL_INSIDE_UNREAL) && SOL_INSIDE_UNREAL
#ifdef check
#define SOL_INSIDE_UNREAL_REMOVED_CHECK 1
#pragma push_macro("check")
#undef check
#endif 
#endif // Unreal Engine 4 Bullshit
```
and at the very bottom:
```C++
#if defined(SOL_INSIDE_UNREAL) && SOL_INSIDE_UNREAL
#if defined(SOL_INSIDE_UNREAL_REMOVED_CHECK) && SOL_INSIDE_UNREAL_REMOVED_CHECK
#undef check
#pragma pop_macro("check")
#endif 
#endif // Unreal Engine 4 Bullshit
```

Actually, you can shorten all the macros for UE4 a bit by removing a few unneccessary `#define`s:
```C++
#if defined(UE_BUILD_DEBUG) || defined(UE_BUILD_DEVELOPMENT) || defined(UE_BUILD_TEST) || defined(UE_BUILD_SHIPPING) || defined(UE_SERVER)
#define SOL_INSIDE_UNREAL
#ifdef check
#pragma push_macro("check")
#undef check
#endif 
#endif // Unreal Engine 4 Bullshit

...
[sol.hpp content]
...

#if defined(SOL_INSIDE_UNREAL)
#undef check
#pragma pop_macro("check")
#endif // Unreal Engine 4 Bullshit
```

Now you won't have to make any changes anymore, no matter what Epic does to the `check` macro.

**Comment by ThePhD** [comment]
SHIP IT.

Does GCC have something similar?

**Comment by ThePhD** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Push_002fPop-Macro-Pragmas.html

NICE.

The future is NOW.

**Comment by ThePhD** [comment]
Fixed in sol3.

**Comment by shohnwal** [comment]
Sorry for reopening this, i just thought about something : 
You don't have to check if it's in Unreal or not, just do this:
```C++
#ifdef check //if there was another check macro defined...
#pragma push_macro("check") //save it
#undef check //undef the old check macro
#define checkmacro_stored //remember that we saved another check macro
#endif

...
[sol.hpp content]
...

#undef check //undef sol2s check macro
#ifdef checkmacro_stored //if there was a previous save of a check macro
#pragma pop_macro("check") //restore it
#undef checkmacro_stored
#endif
```
That way you are not only guarded against Unreals macros but also against any other library/file that  wants to ```C++ #define check```. This might save you and sols users some trouble in the future.
