### ISSUE TITLE
can I create std::vector in lua?

### ISSUE THREAD

**Issue by qtcdxxyuc** [ThePhD/sol2#773]
when vector create in cpp, it is ok.
but i want to create vector in lua, how can i do ?

**Comment by ThePhD** [comment]
```
std::vector<int> create_int_vector() {
  return {};
}

lua.set_function("create_int_vector", &create_int_vector);

lua.script(R"(

vec = create_int_vector();
vec:add(1)
vec:add(2)
-- etc. etc...

)");
```

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/blob/develop/examples/containers.cpp

**Comment by qtcdxxyuc** [comment]
Is it necessary for me to use a wrapper function to generate a vector from cpp?

**Comment by ThePhD** [comment]
Yes. Templates don't exist in Lua.
