### ISSUE TITLE
need some help on class dependences

### ISSUE THREAD

**Issue by RPG3D** [ThePhD/sol2#774]
original c++:
A.h
```
class B;
class A : public Object
{
B* GetData();
}
```

B.h
```
class B: public A
{
void SomeFunc();
}
```

lua wrapper

```

LuaObject.h
class LuaObject
{
Object* RawObject = nullptr;
}

```

LuaA.h
```
class LuaA : LuaObject
{
//I think I can not use LuaB here, but it shuold be LuaB
LuaObject GetData(){  LuaObject Ret; Ret.RawObject =  (A*)RawObject->GetData(); }
}

```

LuaB.h
```
class LuaB : public LuaA
{
void SomeFunc():
}
```

**Comment by ThePhD** [comment]
Your code neither compiles or makes sense. Use `assert`s or similar to show me the behavior you're trying to achieve. This does not look like a sol2 problem, and this is not a general helpdesk.

**Comment by RPG3D** [comment]
the original C++ class inside UE4,
I add some wrapper class for them, but some of the original class have complex denpendences, I don't how to deal with them.

**Comment by ThePhD** [comment]
To solve any inter-class dependency issues:

1. Forward-declare all classes (`class B; class A; class LuaObject; class LuaB; class LuaA;`)
2. Forward-declare all necessary functions, even when defining the class.
3. Define the functions after the needed classes have been defined.

For example,

`forward.h`
```
class B; class A;
```

`forward_lua.h`
```
class LuaObject; class LuaB; class LuaA;
```

`LuaObject.h`
```
class LuaObject
{
     Object* RawObject = nullptr;
}
```

`LuaA.h`
```
#include <my_lib/LuaObject.h>

class LuaA : LuaObject
{
     // forward declaration
     LuaObject GetData();
}
```

`LuaB.h`
```
#include <my_lib/LuaObject.h>

class LuaB : LuaObject
{
     void SomeData();
}
```

`LuaAB.impl.h`
```
#include <my_lib/LuaA.h>
#include <my_lib/LuaB.h>

LuaObject LuaA::GetData(){  /* whatever you want, all data is available here */ }
```

`lua_wrapper.h`
```
#include <my_lib/forward_lua.h>
#include <my_lib/LuaA.h>
#include <my_lib/LuaB.h>
#include <my_lib/LuaAB.impl.h>
```

**Comment by RPG3D** [comment]
in this line
 // forward declaration
     LuaObject GetData();

I want to use the paired LuaB(for class B) not a generic class

**Comment by ThePhD** [comment]
Then you need to restructure your class. You can't have 2 fully complete class definitions using values of one another.
