### ISSUE TITLE
Pass arguments to script file?

### ISSUE THREAD

**Issue by sagunkho** [ThePhD/sol2#775]
Related to #125 , how does one pass arguments to a script_file?

**Comment by ThePhD** [comment]
I don't think there's a well-defined way to do it.

**Comment by Rochet2** [comment]
Copying the example from the related issue, I would assume its by doing this
```cpp
sol::load_result fx = lua.load_file("script.lua");
sol::tie( a, b ) = fx("your", "arguments", "here");
```

```lua
-- script.lua
local a,b,c = ...
print(a,b,c)
```

Tested and seems to work fine.

**Comment by ThePhD** [comment]
Well, today I learned something new. Neato.

I'll tag this as documentation, since it should probably be put in the docs.

**Comment by eliasdaler** [comment]
Yup, every script/chunk you execute can be viewed as a function, it's pretty neat. :)
