### ISSUE TITLE
tonumber has a maximum of 4294967295 (UINT32_MAX) when base is not 10

### ISSUE THREAD

**Issue by pdgendt** [ThePhD/sol2#777]
Hi, 

I didn't have time yet to verify this on a desktop environment, but I can confirm the issue on ARM (cross compiled).
I used version 2.20.6 as a single header file in a C++/GCC project on a ubuntu 18.04 build system.

My defines:
`-DSOL_USING_CXX_LUAJIT -DSOL_CHECK_ARGUMENTS -DSOL_USE_BOOST -DSOL_SAFE_FUNCTION`

```c++
int main() {
    sol::state lua;
    // should print something like 9,223372037e18 (INT64_MAX)
    // but will get the maximum of 4294967295
    lua.script("print(tonumber('7fffffffffffffff', 16))");

    return 0;
}
```

The example above is with base 16, a common case, but all values other than 10 will produce the same issue.

Thanks in advance

**Comment by Rochet2** [comment]
The code there is basically the same as opening a lua interpreted and typing `print(tonumber('7fffffffffffffff', 16))` to it. No sol required anywhere, so probably not related to sol.

Luajit is very strict about the manual from what I have read.
From lua51 manual https://www.lua.org/manual/5.1/manual.html#pdf-tonumber
> In base 10 (the default), the number can have a decimal part, as well as an optional exponent part (see §2.1). **In other bases, only unsigned integers are accepted**.

Emphasis mine.

So basically only base 10 works with numbers higher than unsigned int max.

**Comment by ThePhD** [comment]
Yeah, what @Rochet2 said.

You should also consider that the most Lua 5.1 and LuaJIT do not have dedicated integers at all.

Lua 5.2 and Lua 5.3 do have integers, but are still subject to Lua's rules.

I can't help you here, I don't think...!

**Comment by pdgendt** [comment]
Ok, thanks for the explanation.

I tried online using [repl](https://repl.it/repls/LargeKhakiGraph) where lua version 5.1 is used and the output is correct.
I can't tell if it's luajit so probably that's the difference?

**Comment by Rochet2** [comment]
repl.it implements its own lua. I think its made in javascript or something. In any case before some updates it couldnt even correctly parse hex numbers.
In real lua the behavior is the same.
![image](https://user-images.githubusercontent.com/468816/53128342-54af6900-356d-11e9-8ce3-fb8188e8cf0b.png)
