### ISSUE TITLE
Cannot get item at index on Container (Which inherits of std::vector)

### ISSUE THREAD

**Issue by Stalker2106x** [ThePhD/sol2#779]
Hey!
I am struggling with usertypes exposition...
I have two simple classes like this:

    template <typename T>
    class Collection<T> : public std::vector<T> {}

as a container, and

    struct Entity {
        std::string example;
     }

esposed like this:

	lua.new_usertype<Entity>("Entity",
		sol::constructors<Entity()>(),
		"example", &Entity::example,
	);
        Collection<Entity> collection; //It is actually filled, but i skipped it for the minimalist example
        lua["Collection"] = collection;

I'm struggling on accessing the "example" field with lua.
sol::is_container<Collection<Car>>::value returns true for container class.
i am able to call :size() method, or :clear() method, but nothing works with T &operator[] or T &at(const int &index)
My lua script is:

    alert(Collection[0].example); //alert is a custom methods which takes a string and prints it.

What did I do wrong ? I guess this is a simple mistake... But i'm so into it i don't see it...
Thanks for any help, I appreciate.

**Comment by ThePhD** [comment]
When you make a Usertype explicit with `new_usertype`, you override all of the custom container methods. So there is no interactivity for indexing or the like.

You need to write it in yourself now.

**Comment by Stalker2106x** [comment]
Thank you for your answers! hm..
That would mean for each T in Collection<T>, to explicitely declare a new_usertype that would map T &operator[](cont int index) to "get" lua name?
Why are size and clear methods available? My class is basically a std::vector, and therefore should behave like
    lua["any"] = std::vector<Entity>()
right ? I will do some tests right there anyway, thank you for your answers.

**Comment by ThePhD** [comment]
Because that would require me to hook up the _entire_ container `usertype` machinery under your usertype (and possibly clobber your calls). This is easier in sol3, but borderline impossible for sol2: I'll consider adding this feature for sol3.

**Comment by Stalker2106x** [comment]
This definitely works when re-exposing my usertypes with new_usertype.
I had to wrap std::vector, I could not expose it when inheriting from std::vector, so I moved the inheritance to a vector member and redefined basic functionnality mapped to it.

There is still something wrong: I have no idea about how to override operator[] in lua (i did find an example with sol::meta_function but couldnt get it to work). I browsed the docs, and i guess it is documented there, but could not find it.
I kinda feel like the quick'n'dirty tutorial is missing the operator overload example.

Anyway, my container does work in lua now, which is a big step forward, thank you !

**Comment by ThePhD** [comment]
There are operator overload examples and examples for overriding `__index` and `__newindex` (`sol::meta_function::index`, `sol::meta_function::new_index`), which correspond to _both_ `obj["a"]`/`obj["a"] = 20` and `obj.a` / `obj.a = 20`. You need to override indexing, make sure you have added your function calls, and then implement your lookup logic for any elements for `__index` and `__newindex`.

Lua's iteration for loops is inclusive. Lua (by itself) also has a convention of iterating from 1 as a start, which is why its numeric for loop is inclusive. Adjust your code.
