### ISSUE TITLE
Prevent instantiation of a usertype from lua

### ISSUE THREAD

**Issue by OrfeasZ** [ThePhD/sol2#78]
A very common use case for me is that I define a usertype (without any `sol::constructor<>`s) and then either set a global instance of it from C++, or just pass instances of it to various  functions, without ever wanting the user to be able to instantiate said usertype.

As discussed in #75, sol will attempt to use the default parameterless constructor if one is not specified.

As a current workaround I can see specifying an actual class constructor with a dummy parameter in order for sol to not pick it up, but would it be possible to introduce something like `sol::constructorless` or even `sol::abstract` in order to achieve the same result?

**Comment by ThePhD** [comment]
`sol::constructor<>` will do it. Albeit, it will generate a "I don't know what function you're trying to call" error, rather than a "attempted to index a nil value"-style of error.

**Comment by ThePhD** [comment]
Here: https://github.com/ThePhD/sol2/releases/tag/v2.5.3
