### ISSUE TITLE
Is there a way to bind Lua member variable as a call to C/C++ function with the name of that variable ?

### ISSUE THREAD

**Issue by xirius** [ThePhD/sol2#780]
I'm totally new to Lua/sol2. I understand it is possible to bind Lua variables and methods to ones on the C/C++ side quite easily with sol2.

But is it possible to bind a user type variable to the call of the C/C++ function which may look like properties on the Lua side ?

Example:
```c++
// C++
struct player {
  int get_value(const std::string& property) const {
    auto it = values.find(name);

    if (it != values.end()) {
      return it->second;
    }

    return -1;
  }

  std::map<std::string, int> values; // Ideally map would be map<std::string, sol::any> or map<std::string, sol::variant<int, double, ...>>
};
```
And on the Lua side:
```lua
-- Lua
p = player.new()
print(p.score)
```
So when I call `p.score` in Lua, it gets translated to the call to the `player::get_value` function on C++ side with the value of property "score" ?

**Comment by ThePhD** [comment]
http://sol2.readthedocs.io/en/latest/api/property.html

**Comment by xirius** [comment]
`sol::property` It is not exactly the same thing, at least if I understood it correctly :)

`sol::property` maps at the compile time but I want to make the resolution at the run time

The `player` class has a bag of properties that can be populated at the run time.
Then in Lua when I call `print(p.score)` I want to check if `score` exists as a key inside the `std::map` and if it exists I want to retrieve it (if not it should return `nil`).

Is it possible ?

**Comment by ThePhD** [comment]
Then you need to bind to `sol::meta_function::index`, to capture both `p.score` and `p["score"]` calls. Whenever a getter is applied that does not already have a name, sol2 passes it to the underlying index function. If you don't define one, we do it for you. If you do provide one, it gets passed `self`, `key` and `value`. So just write a function:

```
struct player {
  int get_value(const std::string& property) const {
    auto it = values.find(name);

    if (it != values.end()) {
      return it->second;
    }

    return -1;
  }

  static sol::object my_index_func( player& p, sol::stack_object key, sol::stack_object vale ) {
     // stuff here
  }

  std::map<std::string, int> values; // Ideally map would be map<std::string, sol::any> or map<std::string, sol::variant<int, double, ...>>
};

lua.new_usertype<player>( "player",
     sol::meta_function::index, my_index_func
);
```

**Comment by ThePhD** [comment]
Example doing exactly what you're asking: https://github.com/ThePhD/sol2/blob/develop/examples/dynamic_object.cpp

Example for a very specific case of making a vector type: https://github.com/ThePhD/sol2/blob/develop/examples/usertype_dynamic_getter_setter.cpp#L24

**Comment by xirius** [comment]
Amazing, thank you very much!

**Comment by treemap24** [comment]
I explored for a long time and finally found the solution I needed



https://stackdev.space/questions/passing-a-callback-from-c-to-lua
