### ISSUE TITLE
Usertype method bind fail, if it takes reference to primitive type as argument.

### ISSUE THREAD

**Issue by pirogronian** [ThePhD/sol2#781]
It seems that Sol2 don't like primitive type' references as usertype method arguments. Following sample of code:
`#define SOL_SAFE_USERTYPE 1`
`#define SOL_SAFE_REFERENCES 1`
`#define SOL_CHECK_ARGUMENTS 1`
`#define SOL_PRINT_ERRORS 1`
`#define SOL_SAFE_FUNCTION 1`
`#define SOL_SAFE_FUNCTION_CALL 1`
`#define SOL_SAFE_GETTER 1 `
`#define SOL_EXCEPTIONS_SAFE_PROPAGATION 1`

`#include "sol.hpp" `

`int f1(int a) {`
`    return a + 1;`
`}`

`void f2(int &a) {`
`    a ++;`
`}`

`struct Type {`
`    int f1(int a) {`
`        return a + 1;`
`    }`

`    void f2(int &a) {`
`        a ++;`
`    }`
`};`

`int main() {`
`    sol::state lua;`
    
`    lua.set(f1);`
`    lua.set(f2);`
    
`    lua.new_usertype<Type>("Type", "f1", &Type::f1, "f2", &Type::f2);`

`    return 0;`
`}`
generates (via `g++ -llua ref.cpp`) following error:
> (...) ref.cpp:37:68:   required from here
sol.hpp:12721:20: error: cannot bind non-const lvalue reference of type ‘int&’ to an rvalue of type ‘int’
    return (mem.*fx)(std::forward<Args>(args)...);
           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sol.hpp:12721:48: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
    return (mem.*fx)(std::forward<Args>(args)...);

I'm making binding for external library, so I can't just rewrite a method to be bound. I'm not very familiar with modern templating. Maybe there's a reason for such a behaviour. Please, give me any advise, if possible.

**Comment by ThePhD** [comment]
Non-const references of primitives types cannot be bound, because there is no way to properly feed that information back out of Lua. Lua has no references for primitive types: create a wrapper around the function to have the desired effect of changing the variable, and then returning it + any results you need.
