### ISSUE TITLE
Customization point fails

### ISSUE THREAD

**Issue by Rochet2** [ThePhD/sol2#782]
I tried sol3 with the new extension points.
Wrapping uint64 and int64 worked fine locally on windows and linux systems, but for some reason travis fails.

Error message:
```
[sol2] An error occurred and has been passed to an error handler:
  sol:
    runtime error: [string "f_maxint64_t(maxint64_t)"]:1:
      stack index 1, expected number, received int64: not an integer
stack traceback:
	[C]: in function 'f_maxint64_t'
	[string "f_maxint64_t(maxint64_t)"]:1: in main chunk
```

Failing line: `REQUIRE_NOTHROW(lua.script("f_maxint64_t(maxint64_t)"));`
In this `f_maxint64_t` is a function that takes `int64_t` as a parameter and `maxint64_t` is the maximum `int64_t` value that has been pushed to lua.
It seems that pushing the `int64_t` worked as expected ( it is userdata ), but checking is not working.

Failing build: https://travis-ci.com/Rochet2/sol3test/builds/102792864
code: https://github.com/Rochet2/sol3test
test.cpp contains the test code that fails
stackinterface.h contains the extension point code
wrap64.h contains the object that is used to represent (u)int64

Im probably not using the extension API entirely correctly, I am guessing.

**Comment by ThePhD** [comment]
You've opened Pandora's box.

I'm gonna have to write a blog post to answer this one, so it'll be a bit. This one might not be _properly_ solvable until the full release of sol3, which... is not gonna be fun.

For now, you'll have to qualify when you want special handling with `wrap<>` versions explicitly in the function's APIs. Sorry...!

**Comment by jameyboor** [comment]
I think this issue needs more labels.

**Comment by ThePhD** [comment]
Excellent point!

**Comment by ThePhD** [comment]
@Rochet2 

There's nothing I can do without doing crazy gymnastics to help this specific case.

The fix for you is defining them by doing the following:

```
#include <sol/forward.hpp>

/* Forward-declare all customization points that use primitives */

#include <sol/sol.hpp>

// The rest of your code
```

This will allow sol2 to pick up your extension points. Note you only have to forward-declare for the primitive types like ùint64_t` or `string_view` and shit.

**Comment by Rochet2** [comment]
Alright.
I updated the code with that suggestion and now linux and windows pass.
https://travis-ci.com/Rochet2/sol3test/builds/103806192

An unrelated issue:
I also updated to latest sol3, but then windows fails, so keeping on the older version. https://travis-ci.com/Rochet2/sol3test/builds/103805661
Seems the latest update broke VS build.

**Comment by ThePhD** [comment]
@Rochet2 Don't know what's wrong: it looks like a really bad compiler bug, and I don't know how to fix it honestly.

**Comment by ThePhD** [comment]
@Rochet2 Should be fixed now but I probably borked clang, kek.

Oh well!
