### ISSUE TITLE
'fake' argument errors when compiled in debug mode

### ISSUE THREAD

**Issue by qfrtt** [ThePhD/sol2#783]
When i am compiling in debug mode or have the SOL_CHECK_ARGUMENTS defined I always get errors that aren't actually errors for example here :

```
stack index 4, expected number, received no value: not a numeric type (bad argument into 'FontHandle<std::basic_string<char,std::char_traits<char>,std::allocator<char> >, long, unsigned char)')
```
but here's my code
```
local p_font = DrawHandler:CreateFont("Calibri", 8)
```
and here's the definition inside the C++ app
```
FontHandle LuaCreateFont(std::string family, long size, std::uint8_t flags = 0);
```
I have also tried removing the part where I set default values like  std::uint8_t flags = 0 but the error is still there

**Comment by ThePhD** [comment]
Default arguments cannot be bound in any C++ project, therefor it expects 4 arguments (`self`, which is `DrawHandler`, plus the 3 arguments).

It sucks, but there's nothing I can do about this!

**Comment by ThePhD** [comment]
If you need it, you can write a `sol::overload` for this and use a lambda for passing the 2-argument version. But that's the best I can think of?

**Comment by qfrtt** [comment]
This error still persists here in an other situation
```
stack index 5, expected number, received string: not a numeric type (bad argument into 'void(FontHandle, D3DXVECTOR2, std::basic_string<char,std::char_traits<char>,std::allocator<char> >, unsigned long)')
```
```
DrawHandler:Text(p_font or DrawHandler.defaultFont, D3DXVECTOR2(permaOffset.x + 5, permaOffset.y - 12 + start * 14), entry.name .. ": ", rgba2hex(colors.permaText))
```
 void Text(FontHandle font, D3DXVECTOR2 position, std::string text, D3DCOLOR color);
```

```

**Comment by ThePhD** [comment]
`DrawHandler:Text( { everything else you wrote... } )` gets transformed to `DrawHandler.Text( DrawHandler, { everything else you wrote... } )`. Using the colon `:` syntax means that whatever is to the left of the colon gets passed as the first argument. Use the right one of either `.` or `:` depending on whether you want to pass the object as the first argument (typically `self`)!

**Comment by qfrtt** [comment]
What i meant is why without debug mode the script works and executes as needed

**Comment by ThePhD** [comment]
They are errors, safety is turned off by default in release modes unless you specifically ask for it. See: https://sol2.readthedocs.io/en/latest/safety.html

If you run the code, you will get unexpected / bad values, or crashes. Unless you have thoroughly vetted the code, it is strongly recommended to turn on (and keep on) the safeties.
