### ISSUE TITLE
Issue migrating function from sol::state A to B

### ISSUE THREAD

**Issue by sagunkho** [ThePhD/sol2#786]
I have issues migrating a function between 2 states, that is defining it in the first and executing it in the second. Here is the code below - 

```
	sol::state lua;
	sol::state lua2;

	lua2.open_libraries(sol::lib::base);

	lua.script(R"(
				a = function() print('hello') end
			   )");
	lua2.set_function("a", lua.get<sol::function>("a"));
	lua2.script("print(a)");
	lua2.script("a()");
```

The output of the above should be the function address and 'hello' but the latter fails to print. Actual output - 

```
Running 1 test case...
function: 0x0514caa8
unknown location:0: [4;31;49mfatal error: in "Sol2Test": unknown type[0;39;49m
/Users/sagunkho/CLionProjects/Horizon/repo/src/Tests/Sol2Test.cpp:39: [1;36;49mlast checkpoint: "Sol2Test" test entry[0;39;49m

[1;31;49m*** 1 failure is detected in the test module "Sol2Test"
[0;39;49mProgram ended with exit code: 201
```
The issue is that print is nil when running in lua2.
The program was compiled in a boost test case on macOS 10.14 x64. Compiler - clang++ -arch x86_64

**Comment by ThePhD** [comment]
This is not at all possible.

You need to define the function in the second state, VIA actual bytecode or lua code that you specifically load with `.script` or similar calls. It is also fundamentally impossible to work with any function, table, etc. defined in one state and passed to the next.

**Comment by ThePhD** [comment]
To be clear, you would need to use the Lua C API at this point, because sol2 does not provide an API for dumping an old function. See:

http://www.lua.org/manual/5.3/manual.html#lua_dump

I could provide a function to do this, but it would only be available in the sol3 branch. You would use it, hypothetically, by doing:

```
sol::state lua;
sol::state lua2;

lua2.open_libraries(sol::lib::base);

sol::load_result lr = lua.load(R"(a = function() print('hello') end)");
std::vector<char> bytecode_dump = lr.dump();
lua2.script( sol::string_view( bytecode_dump.data(), bytecode_dump.size() ) );
lua2.script("print(a)");
lua2.script("a()");
```

This function does not yet exist, so you'd have to write something yourself to do the `.dump();` part, using `lua_unload`.

**Comment by ThePhD** [comment]
This is now apart of sol3, and looks as follows:

```
#define SOL_CHECK_ARGUMENTS 1
#include <sol/sol.hpp>

#include <cassert>

int main () {

	sol::state lua;
	sol::state lua2;
	lua2.open_libraries(sol::lib::base);

	sol::load_result lr = lua.load("a = function (v) print(v) return v end");
	assert(lr.valid());
	sol::protected_function target = lr;
	sol::bytecode target_bc = target.dump();

	auto result2 = lua2.safe_script(target_bc.as_string_view(), sol::script_pass_on_error);
	assert(result2.valid());
	sol::protected_function pf = lua2["a"];
	int v = pf(25557);
	assert(v == 25557);

	return 0;
}
```

**Comment by sagunkho** [comment]
@ThePhD Great work! When can we expect a sol3 release? Thanks for working on this super awesome library.

**Comment by ThePhD** [comment]
sol3 is feature complete and on its on branch. It will become the default when the docs are finished (i.e., a long while from now).
