### ISSUE TITLE
sol2 how to get variadic args from lua ?

### ISSUE THREAD

**Issue by chengmiao** [ThePhD/sol2#787]
Latestly, i use sol2 to bind lua in C++, but i have a problem to use it like this . Can someone help me, sorry for my pool english.
I have a variadic template function :

template <typename ... Args>
DBQuery & insert_into(const std::string & tbName ,const Args & ... args)
{
      // do some thing with args...
}

how can i use it in lua?

**Comment by ThePhD** [comment]
You need to bind the function with the arguments hammered out. Variadic temples in C++ are a compile-time construct: Lua is a runtime virtual machine. As such, you need to explicitly instantiate each template, and then bind them explicitly:

```
lua.set_function( "insert_into_number", &DBQuery::insert_into<double> );
lua.set_function( "insert_into_number_number", &DBQuery::insert_into<double, double> );
lua.set_function( "insert_into_string", &DBQuery::insert_into<string> );
```

"Wow, that's really terrible!", I hear you say. To which I say: Yes, yes it is terrible! But there's no other choice, unless you have a runtime processor you can hook this up to.

sol's natural Overloading Support makes this somewhat better:

```
lua.set_function( "insert_into", sol::overload( 
&DBQuery::insert_into<double>,
&DBQuery::insert_into<double, double>,
&DBQuery::insert_into<std::string>,
&DBQuery::insert_into<double, std::string>
/* etc... */
) );
```

With the second, you can write `insert_into( db, 1 )` or `insert_into( db, "wee" )` and it'll automatically pick the right function. But you HAVE to specify all the ones you want in advance. That, or use `sol::variadic_args` and do your processing at _runtime_, switching on types and creating a thing you can insert into the DB.

But that's left as an exercise for the reader.

**Comment by chengmiao** [comment]
thanks for reply me ! Thats sovle my problem.  But use sol::variadic_args, you must also define different type of functions to use when switch on types. Am i  right?

**Comment by chengmiao** [comment]
@ThePhD

**Comment by ThePhD** [comment]
You switch on the `.get_type();` or use `.is<T>();` for the objects.

**Comment by chengmiao** [comment]
did you mean that : 
`lua["f"] = [](sol::variadic_args args) {
            for ( auto v : args)
            {
                auto type = v.get_type();
                switch (type) {
			    case sol::type::lightuserdata:
			    case sol::type::lua_nil:
				    break;
			    case sol::type::number:
				    // but how i know what the number is int32 or float in C++, so i can convert it to int32 or float
				    break;
			    default:
			    }
            }
		});`

**Comment by chengmiao** [comment]
Did you mean that:
  
![image](https://user-images.githubusercontent.com/5022412/54257316-e40ed180-4599-11e9-8dd8-963404e6e0cb.png)

**Comment by ThePhD** [comment]
Yes.

`v.is<int32_t>();` and `v.is<double>();` can differentiate when you have the `number` classification.

**Comment by chengmiao** [comment]
OK  thanks！
