### ISSUE TITLE
Another C1202: recursive problem in VS2017

### ISSUE THREAD

**Issue by k12Sergey** [ThePhD/sol2#788]
Hi,
I'm trying to use lua sol for not so long and i like it. But i get few problem and didnt find solution for almost few days. So i'm here.

I got two strange problem, so i split them in separate issues.
I use qt creator + mingw and it is compile correctly, but when i go to 
qt creator + VS2017 compiler i've got the following problem.

**C1202: recursive type or function dependency context too complex**
in the following place of my code
`        lua_.new_simple_usertype<Flags::flag2>
                (
                    "flag",
                    sol::meta_function::multiplication, sol::resolve<Flags::flag2(const Flags::flag2&, const Flags::flag2&)>(&Flags::operator*)
                );`
with error in this place in sol.hpp
`template <typename F, typename U = meta::unqualified_t<F>>
                inline constexpr auto resolve_f(std::true_type, F&& f)
                        -> decltype(resolve_i(types<meta::function_signature_t<decltype(&U::operator())>>(), std::forward<F>(f))) {
                        return resolve_i(types<meta::function_signature_t<decltype(&U::operator())>>(), std::forward<F>(f));
                }`
As you can see, there is only one operator overload, and it fail. I'm trying to reproduce this error with almost the same class in test project but it's compile. 

I know its impossible to propose solution by this, but maby i miss somthing and there was an issue like this or documentation says what to do. I will keep trying to localize the core of the problem.

Thanks for any advice, and sorry for my english.

**Comment by ThePhD** [comment]
Remove the `resolve`, or use an explicit static cast to a member function (this is a member function, right?).

**Comment by k12Sergey** [comment]
Hi! Your so fast to responde. I shoul say i'm fun of sol once again! 
Nope, operators were overloaded out of class
`flag2 operator!(const flag2 &f);
flag2 operator*(const flag2 &f1, const flag2 &f2);
flag2 operator+(const flag2 &f1, const flag2 &f2);
flag2 operator-(const flag2 &f1, const flag2 &f2);`
Sorry, i dont get about static cast. There is no member overload of operators.

**Comment by ThePhD** [comment]
Try:
```
lua_.new_simple_usertype<Flags::flag2> ( "flag", 
     sol::meta_function::multiplication, static_cast<Flags::flag2(*)(const Flags::flag2&, const Flags::flag2&)>(&Flags::operator*)
);
```

Or something like that.

**Comment by k12Sergey** [comment]
Wow, its compile! 
But what this code actually do? And why resolve didnt help?

**Comment by ThePhD** [comment]
Who knows; MSVC is weird, but `resolve` is even more weird and is only meant to be one tool used. I should add some docs about using `static_cast` when `resolve` fails.

Either way, it takes the name `&Flags2::operator*` and explicitly requests that it be turned into a known function pointer. sol2 knows what to do with a function pointer, so it works.

**Comment by k12Sergey** [comment]
Amazing! 
I test another places with the same error and they too worked! 
Thank a lot!
