### ISSUE TITLE
operator overloading problem 

### ISSUE THREAD

**Issue by k12Sergey** [ThePhD/sol2#789]
Hi! As i say i got two unsolveble problems (by my knowledge).
And this time it even weirder.

The problem is that one operator worked in lua script and another isnt and lua just stop execution of the script.  But both worked in c++ code.

I got two overload of operator
```
using wrap_double   = Wrapper3::Wrapper3<double>;
lua_.new_usertype<wrap_double>               (
   "wrap_double",
   sol::meta_function::addition, sol::overload(
      sol::resolve<arrow   (const arrow&, const wrap_double&) > (&Wrapper3::operator+),
      sol::resolve<arrow   (const wrap_double& , const arrow&)> (&Wrapper3::operator+))
);
```
They definition as follows
```
template<typename T1, typename T2>
auto operator+(const Wrapper3<T1>&w1, const T2&w2)
{
    return w2;
}
template<typename T1, typename T2>
auto operator+( const T1&w1, const Wrapper3<T2>&w2)
{
    return w1;
}
```
This problem exist only for the any operator  with arrow and wrap_double
Even more, i have  another class similar to arrow and no problem in there! 

I almost try to define this overload directly (without templates) and specify templates parameters in operator, but nothing worked.
Unfortunatly it too difficult to test this problem outside the project (arrow is template class).
And all other operators overloaded for wrap_double worked fine!

Thanks for any advise!

**Comment by k12Sergey** [comment]
Test for operators in c++
```
arrow  a(1.0, 0.0, 0.0);
auto w = Wrapper3::get_wrap(1);
auto ww = a+w;
```

**Comment by ThePhD** [comment]
Use static cast while specifying the template arguments to  `&Wrapper3::operator+<arrow, wrap_double>`. You must have a fully defined function, which means:

- all template arguments must be picked
- it is unambiguous which overload it picks

**Comment by k12Sergey** [comment]
I almost try it. And it has no effect.
So i tried to do the following (eleminate all nessesary part)
```
inline auto operator+(const Wrapper3<double>&w1, const arrow&w2)
{
    return w2;
}
inline auto operator+( const arrow&w1, const Wrapper3<double>&w2)
{
    return w1;
}
```
And this is an overload
```
sol::resolve<arrow   (const arrow&, const wrap_double&) > (&Wrapper3::operator+),
sol::resolve<arrow   (const wrap_double& , const arrow&) > (&Wrapper3::operator+))
```
Antd here is the lua script
```
a  = get(1,2,3) 		-- arrow
wd = get_wrap(1.5)		-- wrap_double
print 'start'
w1 = wd + a
print 'right side'
w  = a+wd
print 'left side'
```

And output to the console is:
***************** test wrappers *****************
start
right side

As we can see the second operation stop the execution. Unfortunately i dont know how to debug this.
But i newer come in second operator overloading. It fail before c++.

**Comment by k12Sergey** [comment]
If it be usefull, c++ object recieved in lua as follows
```
Defines::value<double> get(double x)
{
    Defines::value<double> tmp(x);
    return std::ref(tmp);
}

root::math::arrow_type<double> get(double x, double y, double z)
{
    root::math::arrow tmp(x,y,z);
    return std::ref(tmp);
}
```

**Comment by ThePhD** [comment]
Why are you returning a `std::ref` to a value type you created inside the function? That's asking for a segfault, because `tmp` is dead by the time this function returns.

Have you tried printing out the error you get from Lua following the script handling examples? https://github.com/ThePhD/sol2/blob/develop/examples/script_error_handling.cpp

**Comment by k12Sergey** [comment]
Amazing! I didnt get any problem with lua and lua sol till now and didnt even watch error handling.
I added it now and i got this
```
Something went horribly wrong running the code: runtime error
        ...\DEVELOPING\git\transistor\transistor_lua\test\read2.lua:9: sol: no matching function call takes this number of arguments and the specified types
stack traceback:
        [C]: in metamethod '__add'
        ...\DEVELOPING\git\transistor\transistor_lua\test\read2.lua:9: in main chunk
```

**Comment by k12Sergey** [comment]
I trying to compile this usertype witout overload, only with one operator+ and this problem still here

**Comment by k12Sergey** [comment]
Additional info.
If i use VS2017 compiler + templated operators the error message sligthly different
```
runtime error
        ...PING\SOLVER\git\transistor\transistor_lua\test\read2.lua:42: stack in
dex 2, expected userdata, received sol.Wrapper3::Wrapper3<double>: value at this
 index does not properly reflect the desired type (bad argument into 'root::math
::arrow_type<double>(const classroot::math::arrow_type<double>&, const classroot
::math::arrow_type<double>&)')
stack traceback:
        [C]: in metamethod '__add'
        ...PING\SOLVER\git\transistor\transistor_lua\test\read2.lua:42: in main
chunk
```

**Comment by k12Sergey** [comment]
Thanks to error message, i funally found the trace of the problem.
The arrow class were defined as follows
```
        lua_.new_usertype<arrow>
                (
                    "arrow",
                    sol::meta_function::index,      [](arrow& t, int i){return t.R[i];},
                    sol::meta_function::new_index,  [](arrow& t, int i, double x){return t.R[i] = x;},
                    sol::meta_function::addition        , sol::resolve<arrow(const arrow&, const arrow&)>(&root::math::operator+),                    
                );
```
and if i delete operator+ difinition everything worked (except of arrow addition of cource). Seems like lua wrongly decide wich operator should be used.

**Comment by k12Sergey** [comment]
Sorry for so much messages with the history of my problem investigation.
I come to a simple example which isnt working the same way. I possibly wrong in some part of setting usertype or somthing
[main.zip](https://github.com/ThePhD/sol2/files/2966810/main.zip)
