### ISSUE TITLE
luacppinterface - C++ Member Function call Black Magic

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#79]
[luacppinterface](https://github.com/davidsiaw/luacppinterface) is currently very fast in how it is able to call C++ member functions. It would be wise to investigate what exactly is making it so fast compared to the other frameworks, and if so, devour their ideas and make them better.

**Comment by ThePhD** [comment]
luacppinterface uses a self-looking table for metatable lookup, which is what speeds up member function finding. We do this in the case of only having member functions bound, except in a slightly different manner.

We need to make it a self-pointing metatable so we don't pay the missed lookup cost.

**Comment by ThePhD** [comment]
OOLua might do something similar? Except from its begin / end syntax it might perform something much more crazy and optimize under the hood. Need to give it a look.

**Comment by ThePhD** [comment]
So we just need to use the power of TEMPLATES and TUPLES to eliminate Yet Another Virtual Function Call.
S i g h.

**Comment by ThePhD** [comment]
This is finally done. Need to OFFICIALLY TEST, but the speed should be a lot better if only registering member functions, and we should have gotten rid of all of the virtuals involved with usertypes as well.

**Comment by thinlizzy** [comment]
will there be an official version/announcement for this change?
is this a breaking change? can I safely pull from develop branch now? :dancers:

**Comment by ThePhD** [comment]
@thinlizzy Yes: https://github.com/ThePhD/sol2/releases

The latest release is there, breaking changes shouldn't exist (except for how we handle base classes now, which requires you to be [explicit about it](http://sol2.readthedocs.io/en/latest/api/usertype.html#inheritance). Most people were being explicit anyhow, thankfully.

**Comment by thinlizzy** [comment]
on that particular example, what bad things happen if I don't specify the base class A?

will this still work?
```
b = B.new()
-- returns 20
b:call()
```

and this?
`B b = lua["b"];`

perhaps the problem is here?
```
A & a = lua["b"];
// returns 20?
a.call();
```

**Comment by ThePhD** [comment]
Let's find out:

![Lel](http://i.imgur.com/3hVw4rB.png)

Well, golly good gumdrops, it works. But, notice here that we are using the Silver Bullet That Allows This To Happen: single-inheritance. Even if it's virtual, the data pointer and the vtable will be at the same offset for each of the classes, so MOST compilers (VC++, g++, clang++) will "let you get away with it".

This is why the documentation says "check your compiler documentation", because at this point you're toying with Implementation-Defined / Undefined Behavior.

"But it's faster!" Probably. But speed only matters so much when you have a bug with a multiply-derived class and you're desperately trying to figure out what went wrong in your system...

**Comment by thinlizzy** [comment]
thank you very much for your explanation. I will add the bases for sure
