### ISSUE TITLE
performance with toluapp

### ISSUE THREAD

**Issue by 715703148** [ThePhD/sol2#790]
Read these guidelines. They are relatively simple and will allow me to help you better:

1. Produce a simple, short, compilable test case that reproduces your problem.
2. Make a descriptive title that summarises the bug as a whole.
3. Explain the bug in as much detail as you can in the body of the issue. 
4. Include Compiler/IDE (Visual Studio, XCode...), Build and Deployment System, Language (C++, Objective-C++), and any special defines you have set.

If you want to request a feature:

1. Produce any relevant imaginary code that illustrates what you would like or desired behavior.
2. Include a description and title of what you would like.
3. Annotate and describe the behavior through comments, asserts or just a small write up.

Thanks for helping sol grow!

**Comment by ThePhD** [comment]
... ? Can I delete this?
