### ISSUE TITLE
runtime lua error: value at this index does not properly reflect

### ISSUE THREAD

**Issue by k12Sergey** [ThePhD/sol2#791]
Hi, i've got an example with the following error during lua execution

` stack index 2, expected userdata, received sol.wrap_double: value at this index does not properly reflect the desired type (bad argument into 'arrow(const classarrow&, const classarrow&)`

The problem occure when we have two usertypes with the same overloaded operator and one of usertype classes used in the overload operator of second usertype.

Unfortunately i didnt find any information about using several usertype with overload operators between them.

**And here is the example code:** 
```
#define SOL_CHECK_ARGUMENTS 1

#include <sol.hpp>
#include <iostream>
#include <cassert>
#include <string>


using namespace std;

class arrow
{
public:
    double R[3];
    arrow(double x, double y, double z){ R[0] = x; R[1] = y; R[2] = z;}
};
arrow operator+(const arrow& a1, const arrow& a2)
{return arrow(a1.R[0]+a2.R[0],a1.R[1]+a2.R[1],a1.R[2]+a2.R[2]);}

class wrap_double
{
public:
    double R;
    wrap_double(double x): R(x) {}
};
arrow operator+(const arrow& a, const wrap_double& x)
{ return arrow(a.R[0]+x.R,a.R[1]+x.R,a.R[2]+x.R);}
arrow operator+(const wrap_double& x, const arrow& a)
{ return arrow(a.R[0]+x.R,a.R[1]+x.R,a.R[2]+x.R);}


wrap_double get_double(double x) {return wrap_double(x);}
arrow get_arrow(double x, double y, double z) {return arrow(x,y,z);}

int main()
{
    std::cout << "*** lua to c++ ***" << std::endl;

    sol::state lua;
    lua.open_libraries(sol::lib::base);
    lua["get_double"] = get_double;
    lua["get_arrow"]  = get_arrow;
    lua.new_usertype<arrow>
            (
                "arrow",
                sol::meta_function::addition, static_cast<arrow(*)(const arrow&,const arrow&)>(&operator+)
            );
    lua.new_usertype<wrap_double>
            (
                "wrap_double",
                sol::meta_function::addition, sol::overload(static_cast<arrow(*)(const arrow&,const wrap_double&)>(&operator+),
                                                            static_cast<arrow(*)(const wrap_double&,const arrow&)>(&operator+))
            );
    std::string code = "d  = get_double(5)\
                        a  = get_arrow(1,0,0)\
                        c1 = d+a\
                        print 'passed'\
                        c2 = a+d\
                        print 'passed'";

    sol::protected_function_result result = lua.script(code, sol::script_pass_on_error);
    if (!result.valid()) {
        sol::error err = result;
        sol::call_status status = result.status();
        std::cout << "Something went horribly wrong: " << sol::to_string(status) << " error" << "\n\t" << err.what() << std::endl;
    }

    return 0;
}
```

**Comment by ThePhD** [comment]
From the Lua 5.3 manual:

> __add: the addition (+) operation. If any operand for an addition is not a number (nor a string coercible to a number), Lua will try to call a metamethod. First, Lua will check the first operand (even if it is valid). **If that operand does not define a metamethod for __add**, then Lua will check the second operand. If Lua can find a metamethod, it calls the metamethod with the two operands as arguments, and the result of the call (adjusted to one value) is the result of the operation. Otherwise, it raises an error.  -- [Lua 5.3 Manual, Metamethods](https://www.lua.org/manual/5.3/manual.html#2.4)

Emphasis is mine. "Arrow" has an `__add` operator on it. Therefore, it will attempt to use that one, and not check the second. This is a Lua problem, not a sol problem.

If you want to fix it, then put all the mixed operations on the type you expect to be first. Otherwise, you have some architecting to do.

**Comment by k12Sergey** [comment]
Thanks! I should read more about lua. Hope this could help to someone like me.
