### ISSUE TITLE
avoid allocation at runtime when printing

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#795]
Hi,
Would it make sense to use something like fmt::memory_buffer here
with ostream.h support
to avoid ostringstream memory allocation

```
		template <typename T>
		inline int oss_default_to_string(std::true_type, lua_State* L) {
			std::ostringstream oss;
			oss << stack::get<T>(L, 1);
			return stack::push(L, oss.str());
		}
```

Thanks !

**Comment by ThePhD** [comment]
Write a `to_string` method on your class and this will never be called.

**Comment by otristan** [comment]
You are right, plus, my technique would have issue for the scope of memory validity

**Comment by otristan** [comment]
For future reference, the right way to avoid allocation is a special handling for printing by redefining
the lua print function and we don't call the tostring lua function for that type
