### ISSUE TITLE
sol::optional warning with VS2017

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#798]
Hi! I just started trying the new sol3 beta.

Consider the following usage of `sol::optional`:
```c++
sol::optional<std::string> str;
auto x = str.value_or("!");
```
This produces the following warning on VS2017: `sol.hpp(4950): warning C4239: nonstandard extension used: 'return': conversion from 'T' to 'T &'`

The following won't even compile:
```c++
sol::optional<unsigned int> un;
auto y = un.value_or(0);
```

The same code used to work with sol2.20 on VS2015. In the latter case, using `0u` as the default value solves the issue.

**Comment by ThePhD** [comment]
Looks like a hard regression. Not sure how it escaped me.

I'll fix it.

**Comment by ThePhD** [comment]
Should be fixed in latest.

**Comment by sagamusix** [comment]
Thanks, that did the trick! Excited to dive into sol 3.0 after I could ditch VS2015. :)
