### ISSUE TITLE
Custom containers: Warnings generated if iterator does not return a reference

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#799]
Okay, here's another one that generates a warning in sol 3.0 on VS2017 and worked fine in sol 2.20 on VS2015.

The `value_type` of my custom containers is a `sol::object` (it's a wrapper object exposing the public API of my internal classes) which is synthesized on the fly in `operator[]` via `sol::make_object`. The iterator class overloads `operator()` and `operator*` to return those freshly generated objects, and as such they cannot return a real reference, i.e. `reference_type` is `sol::object` and not `sol::object&`.

This worked without warnings in sol 2.20. Now I get `sol.hpp(19131): warning C4239: nonstandard extension used: 'initializing': conversion from 'Scripting::ProxyContainer::iterator::reference' to 'Scripting::ProxyContainer::iterator::reference &'`.

**Comment by ThePhD** [comment]
My impression was this was always a bad thing, MSVC just decided they were going to be noisy this time around. I'll look into seeing if I can clean up my assumption of returning a reference type.

**Comment by ThePhD** [comment]
... Which clashes with other people who declare that I don't have a right to use `::reference` because it breaks their not-really-containers. Sigh...

Let's just hack up a solution then... is there anywhere else it complains?

**Comment by ThePhD** [comment]
Should be fixed, as far as containers are concerned. Let me know if there are other warnings.

**Comment by sagamusix** [comment]
That did the trick! Warnings are gone, except for one, not sure if it's worth opening another issue at this point because this is all I get:
```
1>sol.hpp(1550): warning C5046: 'sol::meta::meta_detail::is_callable<T,void>::F::operator ()': Symbol involving type with internal linkage not defined
1>        with
1>        [
1>            T=Tu
1>        ]
```
No history of template instantiations that lead to this...
