### ISSUE TITLE
Cant require a library, have tried .require_script and , .require_file, and tried hard coding.

### ISSUE THREAD

**Issue by CosDevelopment** [ThePhD/sol2#800]
Here is my provided code 
C++
```CPP
#include <sol/sol.hpp>
#include <iostream>
#include <string>

int main()
{
        sol::state lua;
        lua.open_libraries(sol::lib::base, sol::lib::package);
        std::string x = lua["package"]["path"];
        lua["package"]["path"] = x + ";/usr/local/share/lua/5.1/LuaMidi.lua";
        lua.script_file("test.lua");
}
```
Lua
```Lua
local lm = require('LuaMidi')
local T = lm.Track
local ne = lm.NoteEvent
local w = lm.Writer

local track = T.new()
local notes = {'C3','D3','E3','F3','G3','A3','B3','C4'}

track:add_events(ne.new({pitch =notes,sequential=true}))
local wr = w.new(track)
wr:save_MIDI('C Major Scale')
```

the above c++ code is my most recent attempt at running this file. both lua and luajit compile it just fine.

I have tried
```
lua.require_script("lm","require(\"LuaMidi\")",true);
lua.require_file("lm","/path/to/lib/file",true)

lua.script(R"(
local lm = require('LuaMidi')
local T = lm.Track
local ne = lm.NoteEvent
local w = lm.Writer

local track = T.new()
local notes = {'C3','D3','E3','F3','G3','A3','B3','C4'}

track:add_events(ne.new({pitch =notes,sequential=true}))
local wr = w.new(track)
wr:save_MIDI('C Major Scale')

)")
```

the error I get is 
```
[sol2] An exception occurred: caught (...) exception
[sol2] An exception occurred: caught (...) exception
[sol2] An exception occurred: caught (...) exception
[sol2] An exception occurred: caught (...) exception
[sol2] An error occurred and panic has been invoked: caught (...) exception
terminate called after throwing an instance of 'sol::error'
  what():  lua: error: caught (...) exception
Aborted (core dumped)
```

I dont really know what else to do.

**Comment by Rochet2** [comment]
`package.path` should probably have `;/usr/local/share/lua/5.1/?.lua` appended to it.
and then you would use `require('LuaMidi')` where `LuaMidi` is the file name that replaces the `?` in the `package.path`.

The luajit errors are weird. I get those too. For some reason the real error is lost and we only see caught(...) which is probably not what should be happening.

**Comment by CosDevelopment** [comment]
Am I not appending that? In my c++ code I have the append to the package

```CPP
std::string x = lua["package"]["path"];
        lua["package"]["path"] = x + ";/usr/local/share/lua/5.1/LuaMidi.lua";
```

**Comment by Rochet2** [comment]
You are appending
`;/usr/local/share/lua/5.1/LuaMidi.lua`
when I think you should be appending
`;/usr/local/share/lua/5.1/?.lua`

**Comment by CosDevelopment** [comment]
Tried that ,still throwing the same error.

**Comment by CosDevelopment** [comment]
I guess I should also.emphasize.

The lua compilers run the lua file just fine, without having to add it to the package.path. I dont know if thats relevant or not, but it does compile through Lua and Luajit

**Comment by ThePhD** [comment]
`require_script` and `require_file` shouldn't have more "requires" in them: it should have the actual script you're attempting to run and place in the "library" global named `"lm"`, in your case.

I am no expert in handling these kinds of errors. It will be a while as I set up a decent test case and try to get this to work. As a side note: where are you storing `LuaMidi.lua`?

**Comment by ThePhD** [comment]
As in: is this in the Working Directory of the application? Is it actually at `/usr/local/share/...` ?

**Comment by CosDevelopment** [comment]
Yes its actually in that location. Its LuaMidi downloaded through luarocks. 

And the scripts provided is the actual scripts

**Comment by CosDevelopment** [comment]
Wait. That is the working directory of the midi library installed through luarocks, not the working directory of the application I am developing.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/blob/72181513d5459c4209f567fa4b36228e51709216/examples/source/require_override_behavior.cpp

**Comment by ThePhD** [comment]
Side note: this requires sol3. However, you can mock up the behavior yourself, with examples as seen in #692!
