### ISSUE TITLE
[Help] C++-owned Lua datatype

### ISSUE THREAD

**Issue by zovt** [ThePhD/sol2#801]
Apologies if this exists already, I've been reading through the docs / examples and haven't found anything related to the use-case I have in mind, and I've been struggling with my own attempts.

My basic problem is this: I am working on an engine in which I am leveraging sol2 to allow scripting game behavior. I have a scene structure in which you can attach scripts to objects, and each script runs in it's own sol::state. So, to communicate between scripts, I'd like to define a structure owned by the C++ core that allows the scripts to define arbitrary properties on the C++ game objects. Essentially, a `std::unordered_map<std::string, CPPLuaType>` where CPPLuaType is a type that is owned and managed by the C++ code, but is easily writable and readable from the Lua scripts.

My attempts so far have involved `map<std::string, std::any>` (segfault when assigning a value from lua), `map<std::string, void*>` (value is always treated as nil even after assigning), and `map<std::string, sol::object>` (segfault when the game is closed due to what I would guess is an issue with the sol::state being deconstructed before the sol::object).

Am I going about this the wrong way? Does what I'm trying to accomplish make sense? I think another option for me would be to run all of the scripts in a global Lua environment, but I would like to explore this option before going to global variables in a Lua environment.

Thanks, and let me know if you need any more information on my end.

**Comment by zovt** [comment]
I've just tried `map<std::string, LuaType>` where LuaType = `std::variant<std::string, int, float, bool>` which seems to be working as intended. Going to leave this issue open for consideration, though feel free to close it. Apologies for the spam!

**Comment by ThePhD** [comment]
`variant` works as you expect it would, but it is not suitable for raw references. If you have special classes which come from Lua, you can add it to the variant with `std::reference_wrapper<my_class>`,

Other than that, you're on the right track. If you'd like something more Lua-oriented, you can also check out the dynamic object example, which showcases piling stuff in.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/blob/sol3/examples/source/dynamic_object.cpp
