### ISSUE TITLE
build issue with SOL_USE_BOOST

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#806]
When using 
#define SOL_USE_BOOST
I get the following error with the latest trunk code

sol.hpp(21024): error C2039: 'has_value': is not a member of 'boost::optional<sol::u_detail::usertype_storage<Base> &>'

Works fine if not defined

Don't hesitate if you need further info.

Thanks !

**Comment by ThePhD** [comment]
Not sure why boost doesn't have `has_value()` here. Wonder what I am supposed to use...

**Comment by otristan** [comment]
There is `is_initialized `but it's deprecated.
Still you can use this and use std:optional even if boost is there when cpp17 is enabled ?

**Comment by ThePhD** [comment]
std::optional does not handle references well, and that is integral to sol2 having a not-garbage API.

**Comment by otristan** [comment]
Actually it depends on the boost version. Looks like > 1.68 got the has_value
but is_initialized is always there.

**Comment by ThePhD** [comment]
Fixed.
