### ISSUE TITLE
Compilation error in sol::optional::value_or

### ISSUE THREAD

**Issue by Tobger** [ThePhD/sol2#808]
The code
```cpp
#include "sol.hpp"

int main() {
	sol::optional<int> n;
	return n.value_or(42);
}
```
compiled with MinGW-g++7.3.0 produces
> ..\Test\sol.hpp: In instantiation of 'constexpr T& sol::optional<T>::value_or(U&&) const & [with U = int; T = int]':
..\Test\main.cpp:5:22:   required from here
..\Test\sol.hpp:4950:23: error: cannot bind non-const lvalue reference of type 'int&' to an rvalue of type 'int'
    return has_value() ? **this : static_cast<T>(std::forward<U>(u));
           ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

because [`sol::optional::value_or`](https://github.com/ThePhD/sol2/blob/c1a8cb1dc5212b6c69deedf456fb81ba7609f8a2/include/sol/optional_implementation.hpp#L1396-L1402?ts=4) would return a reference to a temporary in case `has_value()` is `false`. Same for the overload below. The return type should be `T` instead of `T&`.

**Comment by ThePhD** [comment]
This was fixed a while ago.

Please use the latest before you file bugs.

![A long while ago.](https://i.imgur.com/kFz1uvn.png)

**Comment by Tobger** [comment]
Oh. It's [the current state of the `sol3` branch](https://github.com/ThePhD/sol2/blob/sol3/include/sol/optional_implementation.hpp#L1399). I guess people are not supposed to use that. I assumed sol3 was the experimental new version while `develop` was sol2. Might be worth making that more clear.

**Comment by ThePhD** [comment]
I thought I pulled the nuke on that branch, but I guess not. I'll try to nuke it better: but, sol3 was merged into mainline sol2.

**Comment by ThePhD** [comment]
Okay, I nuked the sol3 branch on Github and only develop exists. I'm sure this'll be a system shock to some people but it'll prevent stuff like this.

Happy programming!
