### ISSUE TITLE
is_x?

### ISSUE THREAD

**Issue by EToreo** [ThePhD/sol2#81]
I would like to check if a table key is of certain types.  I found `sol::optoinal` and am willing to use it, but it seems cumbersome and not full-featured (how am I supposed to check if its an array or another table?).

Would you be interested in adding?
- `is_null()`
- `is_number()` (maybe break this out into int, and double?)
- `is_string()`
- `is_table()`
- `is_array()`

I'm using this JSON library that does the same thing: https://github.com/nlohmann/json#stl-like-access

**Comment by EToreo** [comment]
I think I found what I am looking for: https://github.com/ThePhD/sol2/blob/27a8dde1e6532d58e7ca3008ac9c110e1c8b5c7a/test_tables.cpp#L53

**Comment by ThePhD** [comment]
See: http://sol2.readthedocs.io/en/latest/api/object.html#function-type-check

Example:

````
sol::object x = lua["something"];
x.is<sol::nil_t>(); // is nil
x.is<int>(); // is number
x.is<std::string>();
x.is<sol::nil_t>();
x.is<sol::table>();
````

There is no `array` in lua. It's just a table with all integer keys. The proper way is to just use `optional` and see if it works.

**Comment by EToreo** [comment]
Thanks!

**Comment by crastinus** [comment]
In my old code i figure out what table is an array or not in this way

>   (luaL_getn(L, -1) == 0 ? get_table(inst) : get_array(inst))

**Comment by ThePhD** [comment]
@crastinus That code might fail if you have an integer key of `1`, and then a bunch of other keys that are strings and the thing is a table.

No, I don't have a better solution, except to maybe use the `container` adaptions built into sol2: http://sol2.readthedocs.io/en/latest/containers.html
