### ISSUE TITLE
about stack_aligned_stack_handler_function

### ISSUE THREAD

**Issue by firedtoad** [ThePhD/sol2#811]
how to get trace back info with stack_aligned_stack_handler_function 
there is only error info like this 
main.lua:5: stack index 2, expected number, received nil: not a numeric (integral) type (bad argument into 'void(unsigned char, const std::__cxx11::basic_string<char> &)')
but no stack traceback info

**Comment by ThePhD** [comment]
As the name implies, you need to have a perfectly aligned stack. Your stack handler must be sitting below your function on the stack, then your function needs to be on the stack, and then all arguments will be pushed on top of that. You should have the traceback stack handler in place. Did you put it in place?

Why are you using stack_aligned_stack_handler_function?

**Comment by firedtoad** [comment]
some legacy code  need to be fitted i don't want to modify dead code 
i 'll try later with your advice 
thanks a lot

**Comment by firedtoad** [comment]
thanks

**Comment by ThePhD** [comment]
@firedtoad That's fine, I just wanted to understand your use case better!

What you'll want to do to make sure this works properly is pull the latest code from here, then try the following example to get an idea of how it should work:

https://github.com/ThePhD/sol2/blob/develop/examples/source/stack_aligned_stack_handler_function.cpp

Let me know how it goes!
