### ISSUE TITLE
[help] Sol2 and C++ 14 final version ?

### ISSUE THREAD

**Issue by kotbegemot** [ThePhD/sol2#812]
Sol 2 which version will be the last to support C++ 14 ?

**Comment by kotbegemot** [comment]
@ThePhD

**Comment by ThePhD** [comment]
You don't have to @ me, as the owner of this repository I get pinged for every issue and every comment on every issue.

Go back to the releases and you will see the latest version supporting C++14. It's also mentioned very explicitly in the documentation what compilers are supported, etc. etc.
