### ISSUE TITLE
Internal Error when including sol 

### ISSUE THREAD

**Issue by DragosPopse** [ThePhD/sol2#813]
I used sol on a previous project with visual studio 2015 and it worked just fine. I upgraded vs to 2017 and it got me C1001 internal error, updated again to 2019 and it disapeared for a project but it reapeared in another. I narrowed the problem down and it appears that when I am including sol in any project it gives me this error that points to metatable.hpp.

1>D:\C++ Projects\Shipcraft\Shipcraft\include\sol\metatable.hpp(164,1): error C1001:  An internal error has occurred in the compiler.
1>D:\C++ Projects\Shipcraft\Shipcraft\include\sol\metatable.hpp(164,1): error C1001: (compiler file 'd:\agent\_work\3\s\src\vctools\Compiler\CxxFE\sl\p1\c\convert.cpp', line 674)
1>D:\C++ Projects\Shipcraft\Shipcraft\include\sol\metatable.hpp(164,1): error C1001:  To work around this problem, try simplifying or changing the program near the locations listed above.
1>D:\C++ Projects\Shipcraft\Shipcraft\include\sol\metatable.hpp(164,1): error C1001: Please choose the Technical Support command on the Visual C++
1>D:\C++ Projects\Shipcraft\Shipcraft\include\sol\metatable.hpp(164,1): error C1001:  Help menu, or open the Technical Support help file for more information

Thank you very much for your time. I don't know what other informations to give about this problem

**Comment by OrfeasZ** [comment]
Make sure you're **not** using the `-fpermissive` flag (turned on by default in newer versions of MSVC). Also make sure that your VS is fully up-to-date.

**Comment by ThePhD** [comment]
Yeah, turn off /permissive like @OrfeasZ said!

**Comment by DragosPopse** [comment]
Wow. Thank you so much guys. It worked. I want to say that this project is a great inspiration for me and allows me to learn a lot.

**Comment by ThePhD** [comment]
https://developercommunity.visualstudio.com/content/problem/588576/internal-compiler-error-c1001-when-using-sol3-with.html

Upvote this issue if you want to help get it on Microsoft's radar.
