### ISSUE TITLE
Compile issue 

### ISSUE THREAD

**Issue by Simoncl** [ThePhD/sol2#815]
struct floatVector
{
	floatVector(){}
	std::vector<float> container;
};
luaRef.new_usertype<floatVector>("floatVector",
		"floatContainer", &floatVector::container);

Am I doing something stupid? This does not compile.

INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe'

Cheers

Simon

**Comment by ThePhD** [comment]
`luaRef.new_usertype<floatVector>("floatVector", "floatContainer", &floatVector::container);`

Try that. (Missing the template argument.)
