### ISSUE TITLE
Newbie help, get type name.  

### ISSUE THREAD

**Issue by acronamy** [ThePhD/sol2#817]
So... I want to give some context, because I think you might be interested in this application of  Sol. This is my first C++ project so talk to me like Im 5 about c++, I am porting the Lua Vm to Web Assembly, unlike most projects, mine is designed to run in Node.js. and so far I can get strings and numbers back to JavaScript from my Sol. Sol's attraction has been very helpful so far.

I have to convert a lua table to a JavaScript Object, The interop will be fairly simple.
Lua Table >> std::map >> JavaScript Map >> JavaScript Object.

In order to do this, I am currently iterating over my table, during this loop I am going to need to figure out what is a key and what is a value and also what type.

```lua
module.exports = {
    foo = 1,
    bar = "string",
    1
}
```

```cpp
// Where kv is key value ?
for (auto& kv : (sol::table)lua_file_exports) {
	cout << typeid(kv).name() << endl; // PROBLEM - outputs: NSt3__24pairIN3sol12basic_objectINS1_15basic_referenceILb0EEEEES5_EE
        // key value pair item
	if (typeid(kv).name() == "string") {
        ... do a thing ...				
	}
	// array like table item
	if (typeid(kv).name() == "number") {
        ... do a thing ...
	}
}
```

PS.
I am delighted to confirm the emscripten compiler, compiles with a few edits to the includes form <> to "" path based includes.

**Comment by OrfeasZ** [comment]
C++ is not a dynamic language, as opposed to JavaScript, and `typeid` is a compile-time directive. As such, you will always get the same type back.

What you probably want to do is something like this (untested because I don't have a compiler in front of me right now):
```cpp
for (auto& kv : (sol::table) lua_file_exports) 
{
    if (kv.first().get_type() == sol::type::string)
    {
        // Get table key as string.
        std::string key = kv.first().as<std::string>();
        // Do something with `key` here.
    }

    if (kv.first().get_type() == sol::type::number)
    {
        // Get table key as number.
        lua_Number key = kv.first().as<lua_Number>();
        // Do something with `key` here.
    }

    // You can access the value of this pair using `kv.second()`.
}
```

Keep in mind that even free-standing items (like the number `1` in your example) will still be assigned a key by lua (in this case it will probably have the key `1`, as lua starts indexing from `1` and not `0`).

**Comment by ThePhD** [comment]
Yep, @OrfeasZ got it right here.

Good luck with your code!

**Comment by acronamy** [comment]
I know this is closed but I wanted to amend something  @OrfeasZ's code, in my case `kv.first().as<std::string>()` did not provide a callable, I am unsure why, but I know enough to understand what the error is talking about and fix it. In my case at-least it should be `kv.first.as<std::string>()`.

Kudos for the answer, bonus for getting the value! It's nice being able to do a comparison on a types rather than a string, that's something I have never seen before.
