### ISSUE TITLE
can Sol2 bind functions as ffi functions? 

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#818]
Does sol2 by default use ffi functions if combined with luajit?
If not can it be done?
Do I need to set any preprocessor defines?
and are there any other optimizations that sol2 can use with luajit?

**Comment by ThePhD** [comment]
No, because ffi functions have limited understanding and sol2 accepts all of C++, not just a (subset of) C as what can be understood and made to FFI. If you need FFI functions, you need to invoke luajit's FFI directly.
