### ISSUE TITLE
what are the C++ types I can use in function arguments for sol::state::set_function() ?

### ISSUE THREAD

**Issue by thinlizzy** [ThePhD/sol2#82]
I've got weird runtime errors when I tried things like this, for example:
`lua.set_function("loadImage",[](char ch, std::string const &imageFile) { ... });`

I had to change to this, to make it work:
`lua.set_function("loadImage",[](std::string ch, std::string imageFile) { /* use ch[0] here */ });`

lua code: `loadImage("A","a.png")`

also is there any way to bind user data in function arguments? It did not work for me as well.

**Comment by ThePhD** [comment]
There's no `char` type in lua. "A" is a string. Even if it's just one `char` long (it's one byte long), it's a string. We can add an overload and converter for this, just to make it easier to deal, but... it's kind've hazardous. For example, if someone has a UTF8 encoded string, and they ask for the `char` back... do we just yank the first byte, or do we try to decode the string to get the first "character"? What about `wchar_t`? `char32_t`? `char16_t` ? `sol` would need to include an encoder and a decoder with it, and then we'd also have to specify what we push these characters as (utf8? utf16? utf32?, etc. etc...).

Binding userdata in function arguments should just work™, if it's a class type. If you want an actual userdata from lua and not the class type, try using `sol::userdata` to get the raw `void*` pointer.

**Comment by ThePhD** [comment]
````
#define SOL_CHECK_ARGUMENTS

#include "sol.hpp"
#include <iostream>

int main(int argc, char* const argv[]) {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	struct bark {
		int x = 500;

		bark() {}
		bark(int x) : x(x) {}
	};

	lua.set("b", bark{ 200 });

	lua.set_function("fx", [](bark& b) { std::cout << b.x << std::endl; });
	lua.script("fx(b)");
	return 0;
}
````

Works for me. Note that you don't have to set a usertype / metatable to at the very least pass it around like an opaque handle: it just works. Please tell me if something specifically goes wrong.
