### ISSUE TITLE
usertype constructor simplicity

### ISSUE THREAD

**Issue by fhoenig** [ThePhD/sol2#822]
What would it take to change MyUserType:new() / MyUserType.new() to MyUserType() for constructors?

**Comment by OrfeasZ** [comment]
You can use `sol::call_constructor`:

```cpp
lua.new_usertype<MyUserType>(
    sol::call_constructor, sol::constructors<MyUserType()>()
);
```

**Comment by fhoenig** [comment]
woops. RTFM fail.
Thank you for the quick answer! :-)

**Comment by ThePhD** [comment]
👍
