### ISSUE TITLE
Usertype equality of pointers return false

### ISSUE THREAD

**Issue by ibachar** [ThePhD/sol2#823]
Hi,

I've recently updated to use sol3 3.0.2 with Lua 5.2 from sol2 and have encountered an issue regarding comparison of pointer usertypes which used to work in sol2. I won't post the exact code (searching for a Node * inside a vector of Node *) but instead post this snippet:
```c++
class Test {
};

void main() {
    auto &lua = <obtain sol::state>
    lua.new_usertype<Test>("Test");

    Test test;

    lua["t1"] = &test;
    lua["t2"] = &test;

   lua.script("print(t1 == t2)");
}
```

The above code prints false. Was there any change to the behaviour regarding default eq operators?

Thanks

**Comment by ThePhD** [comment]
Looks like a regression, that should work. I have tests for this so it shouldn't have ever escaped the test realm... I'll look into it.

**Comment by ThePhD** [comment]
This is fixed.
