### ISSUE TITLE
Accepting a Lua function as an argument and calling it

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#825]
I am trying to make a function in C++ that can be called in Lua to provide C++ with a Lua function. Not just the name of the function, but the function value itself:

    	void AddModelLoader(sol::stack_object function);

However, when I try to use this value in C++ it says the type is nil / none. How can I do this?

**Comment by JoshKlint** [comment]
It should be sol::object, not sol::stack_object.

**Comment by OrfeasZ** [comment]
If you want to limit what people can pass in you can also use `sol::function` or `sol::protected_function` (right now using object they can pass in anything and you'd manually have to check if it's a function). For `sol::stack_` versions of things you pretty much have to use them straight away, before any other changes to the stack are made (you can't for example store them and use them later, which is what I assume you're doing).

**Comment by ThePhD** [comment]
@OrfeasZ has it exactly right!
