### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by HyEvil** [ThePhD/sol2#826]
Hi,I found a compile error that seems caused by the stack::push missing lua_state parameter,and the sol version is v3.0.2.
![image](https://user-images.githubusercontent.com/6279864/58900690-36dbcd80-8732-11e9-90a0-8414fd183079.png)

**Comment by ThePhD** [comment]
Oh. Thanks for that.

**Comment by ThePhD** [comment]
All fixed, thanks for reporting!
