### ISSUE TITLE
Wrap C++ Library with Sol2 for usage from a Lua script. 

### ISSUE THREAD

**Issue by SerebryanskiySergei** [ThePhD/sol2#827]
Hi All!

Can you do me a favor please and explain a bit, how can I resolve a following situation:

I have a C++ library (can be built as static or dynamic). I need to have a possibility to call functions from the library inside the Lua script, for example in file "main.lua".

How to do that? What I need to read, which example can I get as a basis?

Thank you,
Sergey

**Comment by OrfeasZ** [comment]
Start with the [Getting Started](https://sol2.readthedocs.io/en/latest/tutorial/getting-started.html) guide, and work your way through it. It covers everything from setting up a lua vm to binding functions and creating custom usertypes.

**Comment by SerebryanskiySergei** [comment]
The reason why I've created the topic is that I've not found the corresponding things in the examples.
Everywhere in examples you're creating lua scripts from the c++ files.

**Comment by OrfeasZ** [comment]
You can find how to run lua from a file instead of writing it as a string of code in C++ in one of the first examples in the [quick n' dirty tutorial](https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#running-lua-code) (`lua.script_file("a_lua_script.lua");`).

**Comment by SerebryanskiySergei** [comment]
Yes, and in this example I need to compile and run a C++ executable in order to do that.
But as far as I understood there is no way to run lua script using lua executor?

**Comment by OrfeasZ** [comment]
That's right. Standard Lua has no built-in FFI support. If you want something that does you might want to look into LuaJIT.

**Comment by ThePhD** [comment]
As @OrfeasZ said, this is a C++ library. sol (and Lua) have nothing to do with going the other way; you'll need another library for that.

Vanilla Lua has long has extension for writing functions and functionality through C++ DLLs or static libraries that you can then "open", but that still has nothing to do with sol2. You'd have to hook the `require()`s behavior and the `package` module behavior, as specified in the Lua Manual (for the version of Lua you're using: 5.1, 5.2 or 5.3).

Good luck!
