### ISSUE TITLE
sol_lua_get compiling issues with MSVC /permissive- enabled (two-phase name lookup)

### ISSUE THREAD

**Issue by PeteHuf** [ThePhD/sol2#828]
I get a compile error including the single-header version when `/permissive-` is enabled for MSVC:
`sol.hpp(9897): error C3861:  'sol_lua_get': identifier not found`

Can work around the issue by disabling two-phase name lookup: `/Zc:twoPhase-`

I suspect this issue might also cause a problem in non-MSVC compilers which have historically done better with two-phase name lookup. Either that or there is a bug in MSVC, as they are actively improving this area of the compiler.

**Comment by ThePhD** [comment]
Out of my hands: https://developercommunity.visualstudio.com/content/problem/588576/internal-compiler-error-c1001-when-using-sol3-with.html

Fix has been checked in for 16.3. Won't get that for maybe a few more weeks or months, who knows.

**Comment by PeteHuf** [comment]
Thanks for the quick response. The workaround is fine for now. This library looks great, keep up the good work.
