### ISSUE TITLE
Use of std::is_floating_point causing issues with custom LUA_NUMBER

### ISSUE THREAD

**Issue by PeteHuf** [ThePhD/sol2#829]
I've customized Lua to use my own floating-point class in place of `float`. I run into an issue when trying to push it to the stack via Sol3 because my type isn't recognized by `std::is_floating_point` as being the 'number' type. A `if constexpr` check in `sol::stack::unqualified_pusher`

I considered customizing is_floating_point in the way you would for hashing, but based on what I heard here: [customizing is_floating_point](http://www.howtobuildsoftware.com/index.php/how-do/6Xn/c-11-floating-point-standards-are-all-types-extending-stdis-floating-point-required-to-implement-fenv-in-c-11-standard), I don't want to do that. (It isn't standards compliant.)

It looks like I'll be able to work around the issue by changing the conditions to something like this:

```c++
if constexpr (std::is_floating_point_v<T> || std::is_same_v<T, LUA_NUMBER>)
```

**Comment by ThePhD** [comment]
Have you considered just writing a `LUA_NUMBER` sol3 customization point instead? That can work as an immediate fix while I think about adding this and `std::is_same_v<T, lua_Integer>` as well.

**Comment by PeteHuf** [comment]
I looked at the `sol_lua_get` set of customization functions, but it looked like they were expecting the values to be in userdata, is there another place for me to look for an example?

**Comment by ThePhD** [comment]
They don't have to be userdata. Just slap the new floating type in all the places where the type is expected and you should be good to go.

**Comment by PeteHuf** [comment]
Thanks, I'm still a bit confused though. From reading `tutorial/customization.rst`, all the examples I've seen represent these custom types as tables on the Lua side. The C++ decomposes the class/struct to go into a Lua table, then recomposes on the way back. In my case I am just pushing a number, not inside a table. I think that's why I can't get it to work properly.

**Comment by PeteHuf** [comment]
FYI, I also added
```C++
		template <>
		struct lua_type_of<LUA_NUMBER> : std::integral_constant<type, type::number> {};
```
as part of my quick fix

**Comment by ThePhD** [comment]
Just do `lua_pushnumber(L, LUA_NUMBER);` inside the customization point. You can do literally anything in that function, so long as you serialize, check, and de-serialize in equivalent fashion.

**Comment by ThePhD** [comment]
Formal fix in latest.

**Comment by PeteHuf** [comment]
Thanks! I pulled the change, and it seems to work great! I have one question:
```
else if constexpr (std::is_floating_point_v<Tu> || std::is_same_v<T, lua_Number>) {
```
In the spots where `is_floating_point_v` is checking `Tu`, the `is_same_v` is checking `T` in your change. Is this by-design? If so, I'm curious to know why.

**Comment by ThePhD** [comment]
Nah, that's a big ol' derp on my part.
