### ISSUE TITLE
Trivial compile fails with VS2017

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#830]
Tried this with sol3.02 (revision dafb184), using VS2017 15.9.13:

```
#include "sol.hpp"
int main() {}
```

It fails to compile with this error:

`sol.hpp(11964): error C3779: 'sol::stack::stack_detail::unchecked_unqualified_get': a function that returns 'decltype(auto)' cannot be used before it is defined`

Shouldn't this just compile?

**Comment by ThePhD** [comment]
Turn off /permissive until Visual Studio 16.3 becomes the official compiler.

See #821 for details.

**Comment by s13n** [comment]
Seems to be a duplicate of #778, sorry for the noise!

**Comment by what951006** [comment]
![te22222](https://user-images.githubusercontent.com/19505641/72586924-6260a080-392e-11ea-8f10-ddef0a763253.JPG)
A picture show u how to fix it!
