### ISSUE TITLE
MSVC Compilation error (deleted function?)

### ISSUE THREAD

**Issue by tkozybski** [ThePhD/sol2#832]
MSVC Version 15.9.13
Conformance disabled.
I've used the latest release single file.

Failing code
```
 struct TestStruct {

    int get_hp() const
    {
        return 0;
    }
};

sol::state lua;
    lua.new_usertype<TestStruct>("TestStruct",
        "hp", sol::readonly_property(&TestStruct::get_hp));


```
Error

> C2280	'std::unique_ptr<char [],std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function	Test c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory0	881	

Output log

> 4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory0(881): error C2280: 'std::unique_ptr<char [],std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function
4>        with
4>        [
4>            _Ty=char []
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\memory(2519): note: see declaration of 'std::unique_ptr<char [],std::default_delete<_Ty>>::unique_ptr'
4>        with
4>        [
4>            _Ty=char []
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory(163): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,_Ty&>(_Alloc &,_Objty *const ,_Ty &)' being compiled
4>        with
4>        [
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>,
4>            _Ty=std::unique_ptr<char [],std::default_delete<char []>>,
4>            _Objty=std::unique_ptr<char [],std::default_delete<char []>>
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory(164): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,_Ty&>(_Alloc &,_Objty *const ,_Ty &)' being compiled
4>        with
4>        [
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>,
4>            _Ty=std::unique_ptr<char [],std::default_delete<char []>>,
4>            _Objty=std::unique_ptr<char [],std::default_delete<char []>>
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory(190): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_FwdIt,_Alloc>::_Emplace_back<_Ty&>(_Ty &)' being compiled
4>        with
4>        [
4>            _FwdIt=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>,
4>            _Ty=std::unique_ptr<char [],std::default_delete<char []>>
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory(190): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_FwdIt,_Alloc>::_Emplace_back<_Ty&>(_Ty &)' being compiled
4>        with
4>        [
4>            _FwdIt=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>,
4>            _Ty=std::unique_ptr<char [],std::default_delete<char []>>
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xmemory(217): note: see reference to function template instantiation '_FwdIt std::_Uninitialized_copy_al_unchecked<_Ty*,_Ty*,_Alloc>(_InIt,const _InIt,const _FwdIt,_Alloc &,std::_General_ptr_iterator_tag,std::_Any_tag)' being compiled
4>        with
4>        [
4>            _FwdIt=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Ty=std::unique_ptr<char [],std::default_delete<char []>>,
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>,
4>            _InIt=std::unique_ptr<char [],std::default_delete<char []>> *
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\vector(1823): note: see reference to function template instantiation '_FwdIt *std::_Uninitialized_copy<_Iter,std::unique_ptr<char [],std::default_delete<_Ty>>*,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>(const _InIt,const _InIt,_FwdIt,_Alloc &)' being compiled
4>        with
4>        [
4>            _FwdIt=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Iter=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Ty=char [],
4>            _InIt=std::unique_ptr<char [],std::default_delete<char []>> *,
4>            _Alloc=std::allocator<std::unique_ptr<char [],std::default_delete<char []>>>
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\vector(738): note: see reference to function template instantiation 'std::unique_ptr<char [],std::default_delete<_Ty>> *std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Ucopy<std::unique_ptr<_Ty,std::default_delete<_Ty>>*>(_Iter,_Iter,std::unique_ptr<_Ty,std::default_delete<_Ty>> *)' being compiled
4>        with
4>        [
4>            _Ty=char [],
4>            _Iter=std::unique_ptr<char [],std::default_delete<char []>> *
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\vector(738): note: see reference to function template instantiation 'std::unique_ptr<char [],std::default_delete<_Ty>> *std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Ucopy<std::unique_ptr<_Ty,std::default_delete<_Ty>>*>(_Iter,_Iter,std::unique_ptr<_Ty,std::default_delete<_Ty>> *)' being compiled
4>        with
4>        [
4>            _Ty=char [],
4>            _Iter=std::unique_ptr<char [],std::default_delete<char []>> *
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\vector(732): note: while compiling class template member function 'std::vector<std::unique_ptr<char [],std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::vector(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)'
4>        with
4>        [
4>            _Ty=char []
4>        ] (compiling source file src\dllmain.cpp)
4>c:\praca\c++\potest\Test\src\dllmain.cpp(276): note: see reference to function template instantiation 'std::vector<std::unique_ptr<char [],std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::vector(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)' being compiled
4>        with
4>        [
4>            _Ty=char []
4>        ]
4>c:\praca\c++\potest\Test\include\sol\sol.hpp(21008): note: see reference to class template instantiation 'std::vector<std::unique_ptr<char [],std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>' being compiled
4>        with
4>        [
4>            _Ty=char []
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\type_traits(616): note: see reference to class template instantiation 'std::basic_string_view<char,std::char_traits<char>>' being compiled (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(2124): note: see reference to class template instantiation 'std::is_convertible<const _StringViewIsh (&),std::basic_string_view<char,std::char_traits<char>>>' being compiled
4>        with
4>        [
4>            _StringViewIsh=char [2]
4>        ] (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(2122): note: see reference to variable template 'const bool conjunction_v<std::is_convertible<char const (&)[2],std::basic_string_view<char,std::char_traits<char> > >,std::negation<std::is_convertible<char const (&)[2],char const *> > >' being compiled (compiling source file src\dllmain.cpp)
4>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(3774): note: see reference to alias template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Is_string_view_ish<_StringViewIsh>' being compiled
4>        with
4>        [
4>            _StringViewIsh=char [2]
4>        ] (compiling source file src\dllmain.cpp)
4>Done building project "Test.vcxproj" -- FAILED.

**Comment by tkozybski** [comment]
I've downloaded the current commit and used the whole include folder (not the single file version) and it compiled.

**Comment by ThePhD** [comment]
I cannot reproduce this error with the single include or the whole folder. I regenerated the single include just to be sure, and still was not able to get the error.

I don't know what to say, but I'm glad it's working!
