### ISSUE TITLE
Question: documentation of new user_type registration

### ISSUE THREAD

**Issue by Spacechild1** [ThePhD/sol2#835]
Hi, first thanks a lot for sol3! 

I'm currently updating my code from sol2 to sol3 and I'm especially making use of the new `user_type` implementation being just a regular metatable, as mentioned here: https://thephd.github.io/sol3-feature-complete, so you don't have register everyhing inside the `new_usertype<Foo>` call.

The code examples in the `examples/` folder already make use of this (showing both the old and new way) but it doesn't really show up in the official docs, see for example: https://sol2.readthedocs.io/en/latest/tutorial/cxx-in-lua.html

From what I understand, one should generally prefer the new way (unless the class is very small) to reduce compile times and there is no difference in runtime speed, but this doesn't seem to be mentioned anywhere in the docs.

Also, I've stumbled across the following warning in https://sol2.readthedocs.io/en/latest/usertypes.html:

> Note that to use many of sol3’s features, such as automatic constructor creation, sol::property, and similar, one must pass these things to the usertype as part of its initial creation and grouping of arguments. Attempting to do so afterwards will result in unexpected and wrong behavior, as the system will be missing information it needs. This is because many of these features rely on __index and __newindex Lua metamethods being overridden and handled in a special way!

Is this still true?

Best, Christof

**Comment by ThePhD** [comment]
Oh, that's no longer true. Gotta blow up that warning.

.... But it's writing docs aaaaaahhh....... I can feel it. The laziness, sinking into my bones, even as I open up the editor... !

**Comment by Spacechild1** [comment]
thanks!

> .... But it's writing docs aaaaaahhh.......

I feel you :-)

**Comment by ThePhD** [comment]
Fixed. https://github.com/ThePhD/sol2/releases/tag/v3.0.3
