### ISSUE TITLE
Passing coroutine to C++ function

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#836]
I am trying to create a system whereby Lua scripts can create a sequence of coroutines stored and managed in C++.

```
	void Entity::AddCoroutine(sol::function func, sol::variadic_args args)
	{
		//Create coroutine
		sol::thread thread = sol::thread::create(VirtualMachine::L);
		sol::coroutine co(thread.state(), sol::ref_index(func.registry_index()));

		//Call with initial arguments
		co(args);

		//Add to stack
		coroutines.push_back(co);

		//Add entity to active set
		auto world = this->world.lock();
		if (world == nullptr) return;
		world->coroutineentities.insert(dynamic_pointer_cast<Entity>(Self()));
	}

	void Entity::UpdateCoroutines()
	{
		if (coroutines.empty()) return;

		auto status = coroutines[0].status();
		if (status != sol::call_status::yielded and status != sol::call_status::ok)
		{
			return;
		}
		if (coroutines[0].runnable() == false)
		{
			return;
		}

		//Call function
		auto result = coroutines[0]();

		if (!result.valid())
		{
			DebugError("Lua error in coroutine.");
		}
	}
```

Here is the Lua script:

```
function Script:MoveToPoint(targetpos, speed)
	while true do
		coroutine.yield()
		
		local currentpos = self:GetPosition()
		local change = targetpos - currentpos
		local dist = change:Length()
		
		if dist <= speed then
			
			--We have reached our target
			self:SetPosition(targetpos)
			return
			
		end
		
		--Keep moving towards the target
		change = change / dist
		currentpos = currentpos + change * speed
		self:SetPosition(currentpos)
	end
end

function Script:Start()
	local movespeed = 0.01
	local p0 = self:GetPosition() - Vec3(10,0,0)
	self:AddCoroutine( self.MoveToPoint, self, p0, movespeed )
end
```

My code actually works, and I can see the object moving, but after a few seconds it crashes in stack_core.hpp here:
```
auto attempt_alloc = [](lua_State* L, std::size_t allocated_size, void*& pointer_adjusted, void*& data_adjusted) -> bool {
				void* adjusted = lua_newuserdata(L, allocated_size);
				pointer_adjusted = align(std::alignment_of<T*>::value, sizeof(T*), adjusted, allocated_size);
				if (pointer_adjusted == nullptr) {
					lua_pop(L, 1);
					return false;
				}`
```

**Comment by JoshKlint** [comment]
Looks like this is a similar issue:
https://github.com/ThePhD/sol2/issues/723

Note that my build is pretty old so if this has been fixed recently please let me know.

**Comment by JoshKlint** [comment]
Note that I do not care about trying to run Lua on multiple threads, at all. I have no idea why threads are even used in coroutines.

**Comment by JoshKlint** [comment]
After updating to the latest code in the repo I get a crash on line 616 of reference.hpp, after a couple of seconds of the coroutine running.

**Comment by ThePhD** [comment]
I'm gonna have to take some time on this: anything coroutine related makes my head spin.

**Comment by ThePhD** [comment]
The problem is `sol::thread` dies: you need to package it up with the coroutine so it can keep the stack space available after the `AddCoroutine` function ends. Note that a `sol::thread` is NOT an execution thread, it's just stack space. But, the people in Lua named it a `thread`, so that's what you get. I really should alias it with `sol::stack_space` at some point, but I can never find the time or motivation to do it...

Maybe when I write some better coroutine examples and docs.

**Comment by ThePhD** [comment]
(Or, that's my current theory for the sudden crash.)

**Comment by ThePhD** [comment]
I can't find any other reason for this other than the `sol::thread` dying. Try to keep it alive, and re-open if the problem persists.
