### ISSUE TITLE
Passing floating-point number to function that expects int leads to ambiguous error message

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#837]
Using latest master, with `SOL_ALL_SAFETIES_ON`, I get the following funny error message when trying to pass a floating-point number (which happens to be a perfect integer) to a C++ function that expects an int:

> stack index 2, expected number, received number: not a numeric type or numeric string (bad argument into 'bool(int, const char*)')

I'm not sure if this is supposed to work automagically, but either way the error message seems a bit misleading.

**Comment by ThePhD** [comment]
It's supposed to be okay with a perfect integer passed to it, since it would check lua_isinteger and stuff...

**Comment by sagamusix** [comment]
Apologies, there were several usages of the function and one of them 
didn't pass a perfect integer... so that was the one that was triggering 
the error. Still, the original issue stands, I wonder if the error 
message could be a bit more descriptive rather than telling the user 
that a number cannot be converted into a number.

**Comment by ThePhD** [comment]
Okay, I think I put in a better error message.

Give it and spin and let me know if it's nice!

**Comment by ThePhD** [comment]
Specifically:
![waow](https://i.imgur.com/zY0hzoX.png)

**Comment by sagamusix** [comment]
Is there anything specific I'd have to enable to get this error message? Because I'm still getting:

> stack index 2, expected number, received number: not a numeric type or numeric string (bad argument into 'void(int)')

**Comment by ThePhD** [comment]
Just the safety defines, probably _without_ `SOL_STRINGS_ARE_NUMBERS`

**Comment by sagamusix** [comment]
Indeed, omitting `SOL_STRINGS_ARE_NUMBERS` makes it show the intended message (just noticed that there's a double-space somewhere in that error message by the way!)

**Comment by ThePhD** [comment]
Should I add the message for SOL_SAFE_STRINGS?

**Comment by sagamusix** [comment]
Well, my first question would be.. why is this influenced by string-specific options? To be honest I'm not entirely sure yet if I (or my users) will need `SOL_STRINGS_ARE_NUMBERS` in the end. I just figured out that I can enable `SOL_NO_CHECK_NUMBER_PRECISION` to circumvent the entire problem - although I'm not sure if this encourages sloppy coding and if this should be excused when users write code for my API, or if it will just result in bad surprises.

**Comment by ThePhD** [comment]
Because the options weaken what is considered a valid floating point (and a valid integral) when going between Lua and C++. If you want to be strict in all your interfaces and not accidentally chop off numbers, then defining all safeties and allowing precision checks is good, then you'll probably want to leave it alone. If you want `foo_takes_number("32.3")` to be valid, then you want `SOL_STRINGS_ARE_NUMBERS`. If you want to not allow strings to be passed to numeric calls and not to pay the conversion cost inside of Lua, then you don't define that. Some people tend to care about the precision `e.g., `std::variant<int, float>`: others just don't care.

**Comment by sagamusix** [comment]
I think I will just go without it. I originally added `SOL_STRINGS_ARE_NUMBERS` as a response to the last comment in #442 but I feel it's not actually necessary for anything I use. I guess removing it solves more problems than having it...
