### ISSUE TITLE
VS2017 warning regarding symbol with internal linkage

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#838]
This is less of a bug report than maybe a call for help...? I wish I could provide a simple repro case but adding or removing any of my own code makes the problem randomly appear or disappear without any specific call to sol stuff in my own code being the definite culprit... This is what I get with VS2017:
```
1>...\single\include\sol\sol.hpp(1656): warning C5046: 'sol::meta::meta_detail::is_callable<T,void>::F::operator ()': Symbol involving type with internal linkage not defined
1>        with
1>        [
1>            T=Tu
1>        ]
```
None of the functions that I register with sol should have internal linkage (it's mostly member functions, nothing in anonymous namespaces or defined as inline, etc.). So... has anyone encountered this before? Could it be an issue in sol, in my own code, or just a bogus warning (given that the code runs just fine)?

If you wish to try it yourself, the code is at https://github.com/sagamusix/openmpt
The warning typically pops up when compiling ScriptIntegration.cpp.

**Comment by ThePhD** [comment]
It's a bogus error but it's likely an issue with sol2. I'll take a look.

**Comment by ThePhD** [comment]
I am actually having a hard time producing a repro for this, with VS 2017 x86 or x64. Have a particular line I can look at?

**Comment by sagamusix** [comment]
Do you mean that you cannot get it to emit the warning at all, or you cannot find a way to make the warning appear and disappear? When compiling in Debug mode (x64 tested for now), I get the warning in `ScriptIntegration.cpp` and it sometimes disappears if I remove random sol class and function registrations.

**Comment by ThePhD** [comment]
This is all fixed now! Pull latest.

**Comment by sagamusix** [comment]
Warnings are gone. Thanks for the fix!
