### ISSUE TITLE
Pateron account needs more money

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#840]
I just found your Patreon page and I am happy to support this excellent project. :)

**Comment by ThePhD** [comment]
Awww, thank you!

And now, for the programmed shilling:

<shill>
Did you know GitHub opened up the Sponsor program, and that they will not only NOT take any fees out of the money you give me for the first year, but will also MATCH your entire donation to me?!
</shill>

**Comment by JoshKlint** [comment]
Cool, I will do that instead. Patreon is a useless middleman.

**Comment by playmer** [comment]
I didn't know that either! I'll switch over my patreon pledge to this!

**Comment by ThePhD** [comment]
👍 Thanks, and have fun!

**Comment by JoshKlint** [comment]
I just got around to this.

Thanks for making this. I am using this in my new game engine, and your work will be used in some NASA projects. Good stuff!
