### ISSUE TITLE
cannot compile example on visual studio 2017

### ISSUE THREAD

**Issue by noeat** [ThePhD/sol2#843]
env: visual studio 2017 (15.8.2)
sol2 version: develop
step:
1、use cmake generating visual studo project
2、compile example basic

complier output:
e:\f\library\sol2\include\sol\stack_core.hpp(1005): fatal error C1001: an internal error occurred in the compiler
2>(compiler file“f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp”，line 3674)

stack_core.hpp(1005):
```c++
	template <typename T, typename Handler>
		bool check(lua_State* L, int index, Handler&& handler, record& tracking) {
			if constexpr (meta::meta_detail::is_adl_sol_lua_check_v<T>) {
				return sol_lua_check(types<T>(), L, index, std::forward<Handler>(handler), tracking);
			}
			else {
			
				using Tu = meta::unqualified_t<T>;
				qualified_checker<T, lua_type_of_v<Tu>> c;
				// VC++ has a bad warning here: shut it up
				(void)c;				
				return c.check(L, index, std::forward<Handler>(handler), tracking);
			}
		}
```

**Comment by ThePhD** [comment]
Nothing I can do. You need to turn off the `/permissive-` flag that is turned on by default but is still buggy.

The issue that causes this problem is fixed, but only for a release that's probably months from releasing right now, see: https://github.com/ThePhD/sol2/issues/821#issuecomment-497185928
