### ISSUE TITLE
VS2019 internal compiler error

### ISSUE THREAD

**Issue by slauko** [ThePhD/sol2#846]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1001	 An internal error has occurred in the compiler.
(compiler file 'd:\agent\_work\4\s\src\vctools\Compiler\CxxFE\sl\p1\c\convert.cpp', line 674)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information	G2Lua	D:\Lua Projects\Gothic2\G2Lua\packages\sol.hpp	23388	

getting this error when trying to compile my project with sol included and c++ language standard set to c++17.
![Screenshot_14](https://user-images.githubusercontent.com/28165655/61487242-af76b080-a9a5-11e9-8e02-d0707919f7e2.png)

how to fix this ? thanks in advance

**Comment by playmer** [comment]
I think you'll probably need to provide a specific repro, right now there's little actionable here? Ideally you report this to MSVC, as they never want the compiler to ICE:
https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019

The same information (compiler version, repro file) can also be used to potentially find a work around for you.

**Comment by slauko** [comment]
`#pragma once
#include <Windows.h>
#include <iostream>

extern "C" {
	#include "lauxlib.h"
	#include "lua.h"
	#include "luaconf.h"
	#include "lualib.h"
}
#ifdef _WIN32
	#pragma comment (lib, "lua51.lib")
#endif // _WIN32
#ifndef LUA_OK
#define LUA_OK 0
#endif

#include <sol/sol.hpp>
#include <cassert>

bool CheckLua(lua_State* Lua, int result) {
	if (result != LUA_OK)
	{
		//lua_Debug ar;
		//lua_getstack(L, 1, &ar);
		//lua_getinfo(L, "nSl", &ar);
		//int line = ar.currentline;
		std::string error = lua_tostring(Lua, -1);
		std::cout << "[LUA]ERROR: " << error << std::endl;
		return false;
	}
	return true;
}

void TestFunction(std::string name) {
	std::cout << "[C++]HostFunction called" << std::endl;
	std::cout << "Hello "<< name << std::endl;
}

int main() {
	sol::state Lua;
	Lua.open_libraries(sol::lib::base, sol::lib::package, sol::lib::string);
	Lua["Hostfunction"] = &TestFunction;
	while (true)
	{
		if (CheckLua(Lua, Lua.do_file("scripts\\Gothic2.lua")))
		{
			//all went well
		}
	}
	return 0;
}`


i just tried it with this simple test , i dont know if included everything right at all (im new to lua, but i worked with standalone lua)

**Comment by ThePhD** [comment]
This is because you are using `/permissive-`, the compiler flag that is broken but on-by-default for MSVC.

Turn it off: https://github.com/ThePhD/sol2/issues/821
