### ISSUE TITLE
Documentation of container classifications seems confusing.

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#847]
This is about the [documentation page](https://sol2.readthedocs.io/en/latest/containers.html) with the chapter "container classifications", and the table therein.

I find the following things confusing:

1. The text talks about serializing containers into sol3. Surely this isn't meant to imply that the container contents are being copied into a Lua table? One would expect the table to be used in-place, right? Perhaps it should be made clear what serializing a container into sol3 actually means, or the place where it is decribed in detail should be referred to.

2. Fixed containers have a note/caveat saying that "C++ implementation inserts using operator[]", but I thought that a fixed container can't be inserted into. Am I missing something?

3. I have a fixed associative container that has a find function, and the find function is actually used by sol3 (to check, I have removed the implementation and the linker complains). However, it doesn't appear to be called. If I type `container["key"]` in Lua, I would have expected my find() function to be used, but instead an iteration using begin() and end() is happening. So my question is, of the functions that are listed in the table as being relevant for container classification, in which situations are they actually being called? In my case, find() must be used for something, otherwise it wouldn't get linked, but what is it?

**Comment by ThePhD** [comment]
1. serialization occurs by moving or copying the container into sol3, albeit it should be clear whether we are just moving it into a userdata or placing it into a table. serialization generally refers to making things into something they are not, so that is probably a worse description: "move into table" seems like a better way to go.
2. "inserts" is probably the wrong word: we write into slots using operator[]. That's about it.
3. I'd have to peer into the implementation again. `find()` is used for... well, the `find()` call, but some associative containers have subtly different semantics for `operator[]` calls.

I'll try to get a better answer for 3. For 1 and 2: pull requests welcome.

**Comment by s13n** [comment]
1. Well, the most important bit of information for me would be whether the container, i.e. its elements, are copied or not. In other words, is serialization going to create a deep copy of the container? Or is it merely creating a reference for the existing container? This matters from a  memory consumption viewpoint, and from a usage viewpoint, i.e. whether modifying the container after serialization affects the original container or not. I know the term "serialization" from marshalling data for persistence or communication, which always involves making a copy, hence my confusion. I'd provide a verbiage if it was completely clear to me, but it isn't yet.

2. Ah, so a "fixed" container is only fixed in terms of which elements it holds, the elements themselves can be overwritten? IOW you can overwrite an existing element, but not add new ones or delete existing ones? In this case the note in the table should probably read: "C++ implementation uses operator[] to read/write existing elements." This leaves the question: What about constant containers, which can only be read? Are they supported? How are they detected?

3. Well, for starters, operator[] usually adds a new element to an associative container if it doesn't find the key. The behavior of find() is to not change the container. If the container doesn't have an operator[], you would use find(), possibly along with insert(), to emulate it, right?

**Comment by ThePhD** [comment]
Do you have an example container for the associative container you speak of? I'd like to try and step through some of the logistics for when it is called in that case.

**Comment by ThePhD** [comment]
I don't know of any container that is "constant", other than `std::array`. If you create a `std::array<const T, N>` or something, I'm sure the implementation will explode, and I do not have the time to try or even attempt to fix anything related to someone trying to `const`-qualify container elements. At that point, you're in "sufficiently special" territory and the default implementation likely won't be enough: use the customization points.

**Comment by ThePhD** [comment]
Fixed the docs to look better, the `find` stuff is probably better off not being tracked in a docs issue. Post the example code here and then I'll open a new issue (or if you've got the energy, you open the new issue).

**Comment by s13n** [comment]
Well, any container is constant if you only have a const& to it. Take vector as an example, where all nonmodifying function members exist in a const variant. So I would have expected constant containers to be much less of a special case. They're just ordinary containers where modifying operations like insert or erase are unavailable. When binding them using Sol, I would expect all operations to work that don't modify the container, and those that do would produce an error.

BTW, a container with constant elements isn't the same as a constant container, strictly speaking. The former could theoretically allow addition of new elements, only existing ones can't be changed. The latter would forbid insertion and deletion of elements, and so is even more restricted. IOW it is "fixed", AND has constant elements. That's what I am interested in.

My container is a bit too complicated to serve as a simple example, but I'll come up with something simpler to illustrate the point. Give me a bit of time, I'll open a separate ticket for that.
