### ISSUE TITLE
Help, Need an older compiler!!

### ISSUE THREAD

**Issue by AngeliaQing** [ThePhD/sol2#848]
We use version sol2-2.20.6. It works fine on windows, but encounter much errors on linux.
![image](https://user-images.githubusercontent.com/35912697/61680665-1517c380-ad3d-11e9-9249-0de96570ecf3.png)

Our Complier is much older, with tlinux2.2, complier4.8.5

Thanks for helping!

**Comment by ThePhD** [comment]
I don't know what "compiler 4.8.5" is, unless you mean gcc 4.8.5. At which point, your chances of this working are -- at best -- slim. All gcc 4.8.X are the buggiest and most horrible versions of "modern" C++ compilers there is: you'd likely save yourself a lot of pain just by upgrading.

If you are missing `make_index_sequence`, you must have not turned on `-std=c++1y` or `-std=c++14`. sol2 is not a C++11 library at any version anymore.

**Comment by AngeliaQing** [comment]
yes, gcc 4.8.5. we cannot use c++14, what a pity...

**Comment by ThePhD** [comment]
Sorry! You'll have to use an INCREDIBLY old version of sol2 with a bunch of fixes/features missing. That's really unfortunate, but maybe The Powers That Be will give you a chance to upgrade your compiler.
