### ISSUE TITLE
Calling Unknown function on global variable crashes on cleanup

### ISSUE THREAD

**Issue by schnitzelK1ng** [ThePhD/sol2#85]
Hey there,

I just grabbed latest to benefit from the "attempt to index a nil value" fix, but ran into an issue on app exit.
When having called an unknown function on a global lua var it will crash on exit with iterator debug level 2, orphaned pointer, read access violation.

Example:
```
class A
{
public:
    A() : a(0){}
};

solState.new_usertype<A>("A", "a", &A::a);
```

runs and exits fine:
```
local test = A.new()
test:Unknown()
```

runs fine but will cause app crash on exit:
```
test = A.new() -- notice global variable
test:Unknown() -- having called it will cause app to crash on exit
```

Looking into it more the crash happens during GC for the fail_on_error functor.

**Comment by ThePhD** [comment]
It's probably getting GCed more than once for some reason. Thanks for the small repro: will look into shortly.

**Comment by ThePhD** [comment]
I added the destructor and did the trace. Looks like I needed to explicitly add an initializer to the static variable inside the function that created this. Now, instead of seeing 0x0000000 for `this`, I see an actual pointer value inside `fail_on_error`'s destructor. I'm going to assume it's good to go: give it a jiggle after the push is done, tell me if it's still broken.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/commit/a4e3caee15374818566dd1c842e063e5a956e345 Fixed, as far as I can tell. Might need to add iterator debug levels to g++'s build, though.

**Comment by schnitzelK1ng** [comment]
thanks for the quick update, it's interesting, I put a breakpoint in the destructor.
For the working test (local variable) it gets hit correctly, but for a global variable the orphaned pointer detection and read access error happens before the destructor is called.

Also note that this is with exceptions and rtti off.
Looking into it more.

**Comment by ThePhD** [comment]
I'm beginning to suspect you have the `sol::state` allocated as part of a global / static variable somewhere...

**Comment by ThePhD** [comment]
Give me an SSCCEE. Here's the one I'm using to test this:

````
#define SOL_CHECK_ARGUMENTS

#include "sol.hpp"
#include <iostream>

int main(int argc, char* const argv[]) {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	struct wuff {
		int value = 500;
		wuff() {}
		wuff(int x) : value(x) {}
	};

	lua.set("w", wuff{ 200 });
	lua.set("w2", wuff{ 200 });

	lua.new_usertype<wuff>("wuff",
		"Value", &wuff::value
	);

	lua.script("w3 = wuff.new()");
	try {
		lua.script("wuff:derp()");
	}
	catch (const std::exception& ex) {
		std::cout << ex.what() << std::endl;
	}
	for (auto kvp : lua) {
		
	}
	return 0;
}
````

**Comment by ThePhD** [comment]
How does your code ever make it past calling the bad code if you have RTTI and Exceptions disabled? By default, lua calls `abort` when you fuck up and don't jump out of the `at_panic` function.

**Comment by schnitzelK1ng** [comment]
i wrap lua.script in a runscript method which pushes/pops an error handler function.
Tyring to repro it in an isolated example like you suggested, could indeed be a lifetime issue, although sol::state is just a class member and should get shutdown properly.. investigating.

**Comment by ThePhD** [comment]
Is the class that wraps up `sol::state` allocated before `main()` ?

**Comment by schnitzelK1ng** [comment]
its a sharedPtr manager created and shutdown before main finishes

**Comment by schnitzelK1ng** [comment]
can't repro in isolated application so far, it must be something silly on my end, don't worry about it for now. I'll report back. thanks!

**Comment by ThePhD** [comment]
A few thoughts:
- shared_ptr might be being kept alive beyond end of `main()` somehow, like if you pass the manager by-value through a `lua.set("manager", mananger);` or a `lua["mananger"] = manager;` or something, which makes a copy. Use `std::ref` or pass the pointer to make it not copy.
- You can use `load` method in place of `lua.script`, and then set the `load_result` to a `sol::protected_function` and set the `error_handler` on that which might make the push/pop error handler easier to use.

Good luck.

**Comment by schnitzelK1ng** [comment]
minor update: i can reproduce it in a small sample app the the exceptions compiler flag disabled (Visual Studio 2015 /EHsc), SOL_NO_EXCEPTIONS define can be on or off, does not matter, the compiler flag being off will lead to the crash on exit (still with iterator debug level 2).

Any spot you can think of that would rely on it?

**Comment by ThePhD** [comment]
Do you have an example of the way you push/pop your panic/error-handling function? I have ITERATOR_DEBUG_LEVEL=2 set, /EHsc turned off, and I still just get the usual crash 'n' burn or the everything-is-fine.

**Comment by schnitzelK1ng** [comment]
Alright I've now got it in a state where it'll crash on exit regardless of whether /EHsc is on or off, so that's good. I do have a feeling that it's related to the lifetime of the errorHandler..

Here's the test app:

```
#define _ITERATOR_DEBUG_LEVEL 2
#define _HAS_EXCEPTIONS 0

#include <stdio.h>

#pragma warning(push)
#pragma warning(disable: 4189 4577 4127)
#define SOL_NO_EXCEPTIONS
#define SOL_NO_RTTI
#define SOL_CHECK_ARGUMENTS
#include "sol.hpp"
#pragma warning(pop)

#pragma comment(lib, "lua_x64_Debug.lib")

int luaPanic(lua_State* L)
{		
	printf("Lua Error: %s", lua_tostring(L, -1));
	lua_pop(L, 1);
	return 0;
}	

int luaPrint(lua_State* L)
{		
	const char* msg = lua_tostring(L, -1);
	printf("%s", msg);
	lua_pop(L, 1);
	return 0;
}

int runScript(sol::state& lua, const std::string& script)
{
	sol::load_result scriptResult = lua.load(script.c_str());
	if (scriptResult.valid())
	{
		sol::protected_function protectedFunctionCall = scriptResult;
		protectedFunctionCall.error_handler = lua.get<sol::function>("errorHandler");		
		sol::protected_function_result callResult = protectedFunctionCall();
		if (callResult.valid())
		{
			return 0;
		}
		else
		{
			// err.what() contains invalid string

			//sol::error err = callResult;
			//printf("lua call error: %s", err.what());			
			return 1;
		}
	}
	else
	{
		return 1;
	}

	return 0;
}

int main()
{
	std::unique_ptr<sol::state> lua = std::make_unique<sol::state>();
	lua->set_panic(luaPanic);
	
	lua->open_libraries(sol::lib::base, sol::lib::debug);
		
	lua->set("print", luaPrint);
	lua->script("function errorHandler(err)\nprint(err)\n return err\n end");

	class A
	{
	public:
		A() : a(0) {}
		int a;
	};

	lua->new_usertype<A>("A",
		sol::constructors<sol::types<>>(),
		"a",
		&A::a);

	// /EHsc compiler flag off will lead to a read access violation on exit 
	// when clearing the 'functions map' of function_detail::usertype_indexing_function
	runScript(*lua, "test = A.new()\ntest:Unknown()");

	// just calling this script and not the above works fine. possible issue with error handling..
	//runScript(*lua, "test = A.new()\ntest.a = 2\nprint(test.a)");
	
	return 0;
}
```

**Comment by ThePhD** [comment]
I've run it several times, in debug and release, with exceptions on and off, and it doesn't error / crash abort. The destructor shows a proper value. It's destructed after lua_State begins to die. What lua version are you using? luajit? lua 5.3.2 ? lua 5.2.4 ? lua 5.1.5 ?

**Comment by ThePhD** [comment]
It could also honestly be crap codegen on VS 2015's part: I'm running VS 2015 Update 2.

**Comment by schnitzelK1ng** [comment]
using lua 5.3.2 on VS 2015 (no update 2) - updating.. 
will also double check my settings for compiling the lua lib

**Comment by schnitzelK1ng** [comment]
Do you get a valid .what() string in runScript? for test:Unknown()?

**Comment by schnitzelK1ng** [comment]
rebuilt lualibs, works like a charm. Sorry to waste your time.

**Comment by schnitzelK1ng** [comment]
rebuilt lua-libs, fixes the sample, adjusting sample slightly recreates the issue.. trying to circle it in more.

**Comment by ThePhD** [comment]
It's fine: I got to find an interesting bug in VC++'s `stdlib`. I guess I have to file a report now.

Basically, if _HAS_EXCEPTIONS = 0, exceptions don't properly copy / propogate their internal string pointer like the other version of the class. Instead, they just dumb-copy the pointer value, which results in it pointing to sometimes-erased memory, because `exception` takes ` const std::string& Message`, and then just sets the internal pointer with `Message.c_str()`, without copying or doing any kind of safety.

I guess people use exceptions so little this isn't a problem for them. But now that I've seen it I have to create a separate `sol::error` class when I detect `VC++` and just store the string myself, since I don't have time for VC++'s shenanigans.

Eitherwho, thanks for trucking through this one with me.

**Comment by schnitzelK1ng** [comment]
I have one more round for you, if you don't mind running it.
Slightly modified, after a while it'll get stuck in an infinite loop trying to free the same function map usertype_indexing_function. somehow that table gets messed up...

```

#define _ITERATOR_DEBUG_LEVEL 2
#define _HAS_EXCEPTIONS 0

#include <stdio.h>

#pragma warning(push)
#pragma warning(disable: 4189 4577 4127)
#define SOL_NO_EXCEPTIONS
#define SOL_NO_RTTI
#define SOL_CHECK_ARGUMENTS
#include "sol.hpp"
#pragma warning(pop)

#pragma comment(lib, "lua-5.3.2.lib")

int luaPanic(lua_State* L)
{		
	printf("Lua Error: %s", lua_tostring(L, -1));
	lua_pop(L, 1);
	return 0;
}	

int luaPrint(lua_State* L)
{		
	const char* msg = lua_tostring(L, -1);
	printf("%s\n", msg);
	lua_pop(L, 1);
	return 0;
}

class ScriptManager
{
public:
	ScriptManager();
	int runScript(const std::string& script);

	void test();

	std::unique_ptr<sol::state> m_lua;
};

ScriptManager::ScriptManager()
{
	m_lua = std::make_unique<sol::state>();
	m_lua->set_panic(luaPanic);

	m_lua->open_libraries(sol::lib::base, sol::lib::debug);

	m_lua->set("print", luaPrint);
	m_lua->script("function errorHandler(err)\nprint(err)\n return err\n end");

	class A
	{
	public:
		A() : a(0) {}
		int a;
	};

	m_lua->new_usertype<A>("A",
		sol::constructors<sol::types<>>(),
		"a",
		&A::a);
}


int ScriptManager::runScript(const std::string& script)
{
	sol::load_result scriptResult = m_lua->load(script.c_str());
	if (scriptResult.valid())
	{
		sol::protected_function protectedFunctionCall = scriptResult;
		protectedFunctionCall.error_handler = m_lua->get<sol::function>("errorHandler");		
		sol::protected_function_result callResult = protectedFunctionCall();
		if (callResult.valid())
		{
			return 0;
		}
		else
		{
			// err.what() contains invalid string
			sol::error err = callResult;
			//printf("lua call error: %s", err.what());			
			return 1;
		}
	}
	else
	{
		return 1;
	}

	return 0;
}

void ScriptManager::test()
{
	// /EHsc compiler flag off will lead to a read access violation on exit 
	// when clearing the 'functions map' of function_detail::usertype_indexing_function
	runScript("test = A.new()\ntest.a = 2");
	runScript("test = A.new()\ntest:Unknown()");

	// just calling this script and not the above works fine. possible issue with error handling..
	//runScript(*lua, "test = A.new()\ntest.a = 2\nprint(test.a)");
}

int main()
{
	ScriptManager s;

	for (int i = 0; i < 100; i++)
	{
		s.test();
	}

	return 0;
}
```

**Comment by ThePhD** [comment]
Ran just fine and excited for me. Not sure what's going on: the loop properly terminates, everything cleans up... I'm just not sure what's going on for you.

**Comment by schnitzelK1ng** [comment]
No worries, thanks for helping with it. I'll report back in case I'll eventually find out whats up.
Nice job on sol2 btw!

**Comment by ThePhD** [comment]
Was able to repro. It's either in the `std::map` destructor or the `std::string` destructor. I'm getting the feeling that the `_HAS_NO_EXCEPTIONS` part of the VC++ library isn't very well maintained...

**Comment by ThePhD** [comment]
From the bug report I filed:

> I've filed this as VSO#221619 but we won't be able to get to it soon. Note that _HAS_EXCEPTIONS=0 is currently undocumented, untested, and unsupported.

You're treading deadly, dangerous waters. Good luck.

**Comment by schnitzelK1ng** [comment]
Thanks for looking into it. I'll try some more memory watching, worst case step down a notch on the iterator debug level.
