### ISSUE TITLE
Runtime type checking???

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#850]
I looked at #506, and the issue is 2 years old? so I was wondering, is there any way I can get the type name (c++) type_index or typeid of a sol object/referece? (I really need it)

**Comment by ThePhD** [comment]
What is wrong with the `.is<T>()` function in C++?

**Comment by ThePhD** [comment]
Also, in Lua, the table bound to the `usertype` contains a `__type` field:

```
sol::state lua;

lua.new_usertype<my_class>("MyClass");

lua.script("print(MyClass.__type.name)");
lua.script("print(MyClass.__type.is(MyClass.new()))");
lua.script("print(MyClass.__type.is("not a MyClass"))");
lua.script("print(MyClass.__type.is(24))");
```

Best of luck.

**Comment by xzores** [comment]
I have my own typesystem (i need to pass types from 1 lua script to another and store it offline), so i need my own type system.
I only have the sol object (the way it is setup now)

I only need to know the name and size of the type.

`static std::shared_ptr<Variable> covertFromSol(sol::object& o) {
	//what to do here???
        Variable::create("name", size);

}`

**Comment by xzores** [comment]
ok, so just for anyone else that was looking for something like this:

check for every type and if it is a table check if it is a usertype by getting __type:

simple example:
```

static std::shared_ptr<Variable> covertFromSol(sol::object& o) {
		
		if (o.get_type() == sol::type::nil) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::boolean) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::number) {
			Debugger::Critical("afsasf");
		} 
		else if (o.get_type() == sol::type::string) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::table) {

			sol::object intObj = o.as<sol::table>()["__type"]["name"];
			if (intObj.get_type() == sol::type::nil || intObj.get_type() == sol::type::none) {
				throw;
			}
			else if (intObj.get_type() == sol::type::string) {
				Debugger::Debug(intObj.as<std::string>());
			}
		}
		else if (o.get_type() == sol::type::thread) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::userdata) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::lightuserdata) {
			Debugger::Critical("afsasf");
		}
		else if (o.get_type() == sol::type::function) {
			Debugger::Critical("afsasf");
		}

		return createVariable<int>(5);
	}



```

**Comment by OndrejPopp** [comment]
Concerning this clause,
`else if (o.get_type() == sol::type::table) {

			sol::object intObj = o.as<sol::table>()["__type"]["name"];
			if (intObj.get_type() == sol::type::nil || intObj.get_type() == sol::type::none) {
				throw;
			}
			else if (intObj.get_type() == sol::type::string) {
				Debugger::Debug(intObj.as<std::string>());
			}
		}
`
It is still possible I think to have a sol::type::table that is not a usertype, so throwing there doesn't have to be exactly right.

Anyway, tx @ThePhD for the __type thing. I was having problems, in lua, dumping the whole table tree. It gave me an exception every time I tried to traverse a user type. So now I break it off on the __type thing. Actually, in lua 5.4 it also works by using the pcall for the recursive call to catch the exception. However in Lua jit 5.1 it still prints an extra [sol] line telling me that an exception has occured.... So, to supress that I used the __type thing now.

It would be great if the user types would be traverable so you could dump the type info like with Python. For example, if there would also would be a __function and a __field thing.

Have a nice day!
