### ISSUE TITLE
Compile Error when using set_function with lambda on table operator

### ISSUE THREAD

**Issue by kelvinhammond** [ThePhD/sol2#851]
Read these guidelines. They are relatively simple and will allow me to help you better:

1. **Produce a simple, short, compilable test case that reproduces your problem.**
The issue is that it does not compile, cannot comply, extrapolated to closest option.
```C++
#include <iostream>
#include <string>

#include "sol/sol.hpp"

class Test {
 public:
  Test() : lua_{} {}
  
  void setup() {
    auto log_table = lua_.create_table();
    lua_["log"] = log_table;
    // log_table.set_function("f", [](std::string s) { std::cout << s <<
    // std::endl; });
    lua_["log"].set_function(
        "f", [](std::string s) { std::cout << s << std::endl; });
    lua_["log"] = log_table;
    
    lua_.script(R"(
    log.f('hello')
    log.f('hi')
  )");
  }
  
 private:
  sol::state lua_;
};

int main(int argc, char *argv[]) {
  Test t{};
  t.setup();
  return 0;
} 
```

Compiled with: `clang++ -I ./third_party/include/ -std=c++17 $(pkg-config --cflags --libs luajit) main.cc -o main && ./main`

2. **Make a descriptive title that summarises the bug as a whole.**
Yay, I did this.

3. **Explain the bug in as much detail as you can in the body of the issue.**
The above does not compile, uncomment the commented out code and comment out the `lua_["log"].set_function`, compile(s).

4. **Include Compiler/IDE (Visual Studio, XCode...), Build and Deployment System, Language (C++, Objective-C++), and any special defines you have set.**
clang++ or g++, both give the same error
```
> clang++ --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix

> g++ --version
g++ (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ThePhD** [comment]
You cannot pass a key with the `set_function` call. When you work with proxies (the intermediates returned by `operator[]`), all keys go in the `[]`, and not in `set_function`.

The line should look like this:
```cpp
lua_["log"]["f"].set_function([](std::string s) { std::cout << s << std::endl; });
```
