### ISSUE TITLE
object.is<T>() bug?

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#852]
```
solstate["asf"] = sol::usertype<testType>();
sol::object o = solstate["asf"];
bool b = o.is<testType>(); //is false
```

why would this ever fail??? (b is false)

**Comment by Rochet2** [comment]
What exactly do you expect `sol::usertype<testType>();` to be? I think here lies your issue.
If you wanted to set "asf" to be a new instance of testType, then you would do `solstate["asf"] = testType();`
