### ISSUE TITLE
Lua version not supported?

### ISSUE THREAD

**Issue by gamepois0n** [ThePhD/sol2#855]
I am using the newest version of visual studio and downloaded the sol.hpp from the newest release, when I tried to compile it's telling me lua version not supported. 

I am currently using lua 5.1.5, it  used to work fine with an older version of sol2, came back to check and see that it is now 3.0 so I wanted to try it out.

**Comment by ThePhD** [comment]
That doesn't sound right. Can you point me at the Lua 5.1 repo you're using with sol3?

**Comment by gamepois0n** [comment]
https://sourceforge.net/projects/luabinaries/files/5.1.5/Windows%20Libraries/Static/lua-5.1.5_Win64_vc15_lib.zip/download

**Comment by gamepois0n** [comment]
it's telling me lua version not declared or not version 5.1+

**Comment by sebaiova** [comment]
That warning is for header files not found as well. check them out.

**Comment by gamepois0n** [comment]
#pragma comment(lib, "Library/lua5.1.lib")
#include "Library/sol.hpp"

the error i get is
error C1189:  #error:  "unsupported Lua version (i.e. not Lua 5.1, 5.2, or 5.3)"

**Comment by ThePhD** [comment]
No repro.

I was able to download the static Lua library and code, use that include directory, and have it work with Visual Studio 2017, 2019, x64, x86. I also did it with just manually configuring some CMake.

Unless you can provide more information, I can't help you here. This sounds like you did not set up Lua properly.

**Comment by chao-mu** [comment]
For what it's worth, I was able to reproduce this issue with sol 3.0.3 + travis.

Github: https://github.com/chao-mu/sol-experiment
Travis build (Ubuntu Bionic, with packages liblua5.3, liblua5.3-dev, and lua5.3): https://travis-ci.org/chao-mu/sol-experiment

I think this is because lua is failing to be included at all. If I remember correctly, while developing with Lua on ubuntu I noticed I had to include lua5.3/lua.hpp and not just "lua.hpp" (or .h, I forget what I was using).

From within the travis build:
```
$ sudo locate lua.h
/usr/include/lua5.3/lua.h
/usr/include/lua5.3/lua.hpp
```

**Comment by ThePhD** [comment]
The fix for that is passing `-I /usr/include/lua5.3` as part of the command line for the application. In Visual Studio terms, that's going to Project Properties -> C/C++ -> General and adding entries to "Additional Include Directories", or something like that.

**Comment by chao-mu** [comment]
Thank you for the quick response. It helped me realize I was misspelling the variables supplied by find_package in my cmake file. 

I had 
```
find_package(Lua REQUIRED)
include_directories(${LUA_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${LUA_LIBRARIES})
```

Should have been

```
find_package(Lua REQUIRED)
include_directories(${LUA_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} ${LUA_LIBRARY})
```
(notice plural vs singular).

Fixing that was enough to get the build working.
