### ISSUE TITLE
Internal Error Compiler VS2017

### ISSUE THREAD

**Issue by Mjdgithuber** [ThePhD/sol2#857]
I am getting an internal error in Visual Studio's compiler. I am using the 2017 64-bit compiler without the permissive flag. It is the most up to date compiler for the 2017 version.

It seems to have a problem with:
`return c.check(L, index, std::forward<Handler>(handler), tracking);`
On line 10372 (in the single file) of the current release.

I have disabled the permissive flag for the Visual Studio project, which fixes a different problem. I have no idea why this is happening, but if I just have it return false it works fine. Also right above that you have:
`// VC++ has a bad warning here: shut it up`
`(void)c;`
so I'm not sure if that has something to do with it. If this can't be easily fixed then is there something you recommend? How often does this function actually get used, would it be a train wreck if I just returned true/false?

This is without any code other than a main and 
`#include "libs/sol/sol.hpp"`

**Comment by Mjdgithuber** [comment]
Ok, now I am more confused. I was playing around a bit with your code and the problem actually seems to be with: 
`using Tu = meta::unqualified_t<T>;`

Instead using that line of code I manually substituted in-place of Tu, so 'c' is now defined as 
`qualified_checker<T, lua_type_of_v<meta::unqualified_t<T>>> c;` 
instead of 
`qualified_checker<T, lua_type_of_v<Tu>> c;`

I really don't see how this could possibly make any difference, but for compatibility sake I think it would be best to get rid of the using statement.

**Comment by ThePhD** [comment]
I went through and replaced many of these in an effort to fix non-`/permissive-` bugs and `/permissive-` bugs in the MSVC compiler. Long story short, the compiler is super wrong here and workarounds either break upstream (VS2019) or tie my hands with bad code that doesn't compile on GCC or Clang. :/

I can spend some more time fixing this for the sake of just trying to get VS 2017 to stop being garbage.

Also: no, please don't just return `true` or `false`: this is the thing that changes how `sol::overload` works and also puts sane type safety into the system. Returning just `true`/`false` will likely break the entire system in hilarious spectacular (but probably very frustrating) ways.

**Comment by ThePhD** [comment]
As a side note, I only have VS 2019 right now (because I was trying to fix another VS 2019/2017 bug and I had to delete everything, only for the problem to still be there, HAH) so it'll be a bit while I reinstall 2017. For the 3rd time. e.e

**Comment by ThePhD** [comment]
I can't reproduce this error on VS 2017, VS 2019, or VS2019 Preview: sorry. Please include the full error code and the full code sample you run through Visual Studio, maybe with your compiler settings too.
