### ISSUE TITLE
Small coroutine documentation issues

### ISSUE THREAD

**Issue by firas-assaad** [ThePhD/sol2#859]
I was looking at the coroutine API documentation here https://sol2.readthedocs.io/en/latest/api/coroutine.html and I noticed a couple of small issues..

One is in the members section of the documentation, where the C++ code isn't rendered. The code snippits seem completely missing form the HTML even though I can see them in the source file https://raw.githubusercontent.com/ThePhD/sol2/develop/docs/source/api/coroutine.rst 

The other is a correction to the co.lua script, which is missing a declaration of the counter variable. It doesn't run in its current form unless I set the variable or pass it to the function.

Thanks for making this wonderful library!

**Comment by ThePhD** [comment]
Fixed and now that code builds as part of CI, to make sure I don't do another stupid:

https://sol2.readthedocs.io/en/latest/api/coroutine.html
