### ISSUE TITLE
Casting to sol::make_object from various types

### ISSUE THREAD

**Issue by EToreo** [ThePhD/sol2#86]
I'm trying to serialize json into a `sol::object`.  I'm running into 3 issues with the code I have included.

1. Casting `sol::nil` to `sol::object`
2. Casting `std::string` to `sol::object`
3. Casting `sol::table` to `sol::object`

Any help is appreciated.

```c++
sol::object jsonToLuaObject(const json & j, const sol::state & lua) {
  if (j.is_null()) {
    return sol::nil;
  } else if (j.is_boolean()) {
    return sol::make_object<bool>(lua, j.get<bool>());
  } else if (j.is_number()) {
    return sol::make_object<double>(lua, j.get<double>());
  } else if (j.is_string()) {
    return sol::make_object<char *>(lua, j.get<std::string>().c_str());
  } else if (j.is_object()) {
    sol::table obj;
    for (json::const_iterator it = j.begin(); it != j.end(); ++it) {
      obj[it.key().c_str()] = jsonToLuaObject(*it, lua);
    }
    return obj.as<sol::object>();
  } else if (j.is_array()) {
    sol::table obj;
    unsigned long i = 0;
    for (json::const_iterator it = j.begin(); it != j.end(); ++it) {
      obj[i++] = jsonToLuaObject(*it, lua);
    }
    return obj;
  }
  return sol::nil;
}
```

**Comment by ThePhD** [comment]
I've updated the code and added tests to make sure this can be done (that is, `return my_table;` works as expected). You'll need to change `return sol::nil` to `return sol::make_object( lua, nil);`. Furthermore, you don't need to specify the templates in `< ... >` for each of these: `return sol::make_object( lua, j.get<std::string>() );` should be plenty of enough.

**Comment by EToreo** [comment]
Works like a charm.  Thanks!
