### ISSUE TITLE
No way to detect an empty std::function?

### ISSUE THREAD

**Issue by RealmRPGer** [ThePhD/sol2#862]
The following code throws an error of "bad function call" because an empty std::function does not resolve to nil.

	sol::state lua;
	std::function<void()> foo = nullptr;
	sol::function bar;

	lua["Foo"] = foo;
	lua["Bar"] = bar;

	auto result = lua.script(R"SCR(
		if Bar ~= nil
		then
			Bar()
		end

		if Foo ~= nil or type(Foo) ~= 'function'
		then
			Foo()
		end
		)SCR");

Is there any way within Lua to check if an std::function is empty? I haven't figured one out as of yet. For now I've converted all std::function<> objects to sol::function objects, but I don't consider this a valid solution for all cases moving forward.

**Comment by ThePhD** [comment]
No, there's not. `nullptr` std::function's feel like a code smell but as long as I can do `if (foo)` to check if it's valid I'll just serialize `nil` instead of a dead function object, I guess.

Man, C++ makes me sad sometimes...
