### ISSUE TITLE
`stack_table::size()` works incorrectly

### ISSUE THREAD

**Issue by erysaj** [ThePhD/sol2#864]
`stack_table` does not push itself onto stack hence `size()` computes the length for top-most object.

```
TEST_CASE("stack_table/size", "make sure size() works correctly on stack tables") {
    sol::state lua;
    sol::stack_table t(lua, sol::create);
    t[1] = 42;
    auto sz1 = t.size();
    REQUIRE(sz1 == 1);
    sol::stack::push(lua, "some string");
    auto sz2 = t.size();
    REQUIRE(sz2 == 1);
}
```

Originally discovered in v2.20.6, but reproduces on master as well

**Comment by ThePhD** [comment]
Fixed in latest: pull and have fun!

We also fixed it in other places it might derp in table_core. There might be other places in the whole framework but I didn't notice any so 🤷‍♀
