### ISSUE TITLE
Lua function call performance issue

### ISSUE THREAD

**Issue by ottoGithub** [ThePhD/sol2#865]
When I call a function in lua script, I found that the main cost is luaL_ref() and LuaL_unref()。Is this necessary?SolCall will be much more slower than luaCall() because of the extra function call overhead.
Here is the case:
```
script.lua:
function test_call(s, n)
end
-------------------
void SolCall() {
	sol::state lua;
	lua.open_libraries();
	lua.script_file("script.lua");
	auto f = lua["test_call"];
	f("hello world.", 123); // will call luaL_ref and luaL_unref
}
void LuaCall() {
	lua_State* L = luaL_newstate();
	luaL_openlibs(L);
	luaL_dofile(L, "script.lua");
	lua_getglobal(L, "test_call");
	lua_pushstring(L, "hello world.");
	lua_pushinteger(L, 123);
	if(lua_pcall(L, 2, 0, 0) != LUA_OK) {...}
}
```

**Comment by ThePhD** [comment]
Yes, for safety and exception handling reasons.

But nothing stops you from doing the down low and dirty you really want to using the stack API:
https://sol2.readthedocs.io/en/latest/api/stack.html

Examples:
https://github.com/ThePhD/sol2/blob/develop/examples/source/stack_aligned_function.cpp#L21
https://github.com/ThePhD/sol2/blob/develop/examples/source/stack_aligned_stack_handler_function.cpp#L23

Good luck.

**Comment by ThePhD** [comment]
Fun news: I managed to switch the internal implementation to not call `luaL_ref` anymore for proxies.

I have no idea if it's more efficient or not. But at least it's correct!
