### ISSUE TITLE
ASan exception (memory leak) on userdata type error

### ISSUE THREAD

**Issue by dpacbach** [ThePhD/sol2#867]
Hi there,
ASan (LeakChecker) is telling me that there is a memory leak happening after encountering a type error on a userdata.  I think I traced it to:

```cpp
template <typename R, typename... Args>
struct argument_handler<types<R, Args...>> {
    int operator()(lua_State* L, int index, type expected, type actual, const std::string& message) const noexcept(false) {
        std::string addendum = "(bad argument into '";
        ...
        return type_panic_string(L, index, expected, actual, message.empty() ? addendum : message + " " + addendum);
    }
};
```

in the call to `type_panic_string` it appears to call `luaL_error` which apparently never returns according to the docs, and so I'm guessing it is preventing various destructors from running and causing leaks.

This leak only happens when I cause a type error, but nevertheless I would like to try to avoid this since it makes my ASan output really noisy (and lua type errors from user input will be a normal part of my app so I would like to avoid memory leaks even in those cases).  Is there anything I can do to prevent this?  Thanks

Environment: Sol2 3.0.3, Linux, Clang trunk.

**Comment by ThePhD** [comment]
Building Lua as C++ will enable throws to be used to communicate errors, which will respect destructors.

I agree I should figure out some sort of fix to this. I have a few ideas...

**Comment by dpacbach** [comment]
Ok I built a custom Lua as C++ and using that, the issue goes away.  Thanks

**Comment by ThePhD** [comment]
I'm going to reopen this because I need to make this work as C too, so pardon the extra notifications! I'll be using this issue to track my work.

**Comment by dpacbach** [comment]
Sounds good, thanks.

**Comment by ThePhD** [comment]
Turns out this is harder than expected because C++ makes so many temporaries. I'm gonna have to vet the ENTIRE STACK OF FUNCTION CALLS - G-G-G-GAASP.

**Comment by dpacbach** [comment]
Thanks for the effort on this.  Do you currently have an ASan build in your CI pre-commit checks?  If not, then (assuming you find a fix for this) perhaps you will want to add such a build along with a unit test that triggers a `usertype` error in order to catch any (otherwise silent) regressions of this in the future.

**Comment by ThePhD** [comment]
Fixed (mostly?) in latest. Ish.

**Comment by dpacbach** [comment]
Thank you; it may take me a few days to test the fix, but will let you know if I see the issue anymore.
