### ISSUE TITLE
Panic when throwing from within C++ function.

### ISSUE THREAD

**Issue by dpacbach** [ThePhD/sol2#869]
Hi,
I am getting a panic from sol when I try to read the `sol::error` from a `protected_function_result` that holds an error originating from having thrown an exception inside C++ code.  Here is a standalone reproducer (I have all safeties on):

```cpp
namespace rn::lua {

test_panic() {
  sol::state st;
  st["thrower"] = [] { throw std::logic_error( "hello" ); };

  auto pfr =
      st.safe_script( "thrower()", sol::script_pass_on_error );

  if( !pfr.valid() ) {
    sol::error err = pfr; // !! panics
    ... // does not get here.
  }
}

} // namespace rn::lua
```

which panics on the line indicated (inside `protected_function_result::tagged_get` when it tries to get the string off of the stack at the default index).  I have exceptions enabled in Sol2, though I may be doing something else wrong.  Specifically, it gives me this:

`[sol3] An error occurred and panic has been invoked: stack index 1, expected string, received function`

Could you help to enlighten me as to what I am doing wrong?  Thanks

**Comment by ThePhD** [comment]
Cannot repro, need more information.

Compiler, Platform (Win/Mac/Linux), toolchain, etc.

What do you mean by "with exceptions on"? Did you compile Lua as C++, or just you typical off-the-shelf C Lua?

**Comment by dpacbach** [comment]
Hi,
Here is information about my setup, let me know if you need anything more.  I can reproduce it on all the OS's and compilers listed below consistently:

**Lua**: Version 5.3.5, built from source, compiled along with my application as part of the build process using same compiler flags, and then statically linked into my binary (i.e., no shared libs).

**OS**:
1. Linux (various Ubuntu flavors)
1. macOS (10.12.6)

**Compilers**:
1. `clang version 9.0.0 (trunk 363582)`
1. `g++-9-2-0 (GCC) 9.2.0`

**Compiler flags**: 
```
-Wall      # sol, lua, and my app build with no warnings.
-Wextra
-pthread
-std=c++2a
```

**Relevant Compiler Definitions**:
```
-DLUA_COMPAT_5_2
-DLUA_USE_LINUX         # or *_MACOSX on macOS
-DSOL_USING_CXX_LUA=1   # I added this because without it I get linker errors
```

**Build System**: CMake

Anything wrong with my compiler definitions?  The whole setup works really well otherwise, this is the only issue I am encountering at the moment.

**Comment by dpacbach** [comment]
I should also mention that I verified that Lua is getting built as C++ by manually inserting `#error` preprocessor statements into Lua's `ldo.c` to ensure that `__cplusplus` is defined and that it does not choose anything other than this:
```
#define LUAI_THROW(L,c)  throw(c)
```
which I assume is what we want and indicates that Lua is getting built as C++.

**Comment by dpacbach** [comment]
Also, I include `sol.hpp` like this:
```cpp
#define SOL_CXX17_FEATURES 1
#define SOL_ALL_SAFETIES_ON 1
#include "sol/sol.hpp"
```

**Comment by ThePhD** [comment]
Short answer: turn on `SOL_EXCEPTIONS_ALWAYS_UNSAFE`.


Long answers:
Ah. Sorry, I need to add a note to the docs that `SOL_USING_CXX_LUA` automatically turns off all the exception trampolining we do. This is necessary to allow people to throw through the Lua API, but Lua's API might have a general catch mechanism that does not know how to handle errors.

The right answer here is "you cannot throw through Lua, since Lua is a C API". Even if you build it as C++, Lua does not know how to handle exceptions that propogate out of the bound function and spill into sol2's guts.

**Comment by ThePhD** [comment]
(Some people do weird things with their Lua builds, or work with LuaJIT, and want the dangerous behavior by default. Sometimes it ends up costing new users: sorry about that.)

**Comment by dpacbach** [comment]
Thanks a lot, that fixed it!

**Comment by dpacbach** [comment]
Just to make sure that I understand, are you saying that what I am doing is not safe even now that the panic is gone (i.e., throwing from C++ bound functions)?  Or is it safe now that I have `SOL_EXCEPTIONS_ALWAYS_UNSAFE=1`?
