### ISSUE TITLE
A problem with luacppinterface mentioned in the docs

### ISSUE THREAD

**Issue by davidsiaw** [ThePhD/sol2#87]
Thanks for checking out my library and picking at problems with using it, its always great because it shows me where I should improve. However I am concerned by a little thing in your features page:

![screenshot 2016-05-13 13 27 25](https://cloud.githubusercontent.com/assets/874280/15238023/acaf3f96-190e-11e6-914e-fc23ede3dc30.png)

I'm not quite sure what you meant by that. I assumed it was that it would segfault when you tried to get an already set function that was made using CreateFunction, so I wrote a test for that

https://github.com/davidsiaw/luacppinterface/commit/9ff04a1ee2c2dd8399d3728316d03ed3b63a8fef

Fortunately this test passes, so I didn't understand that statement correctly. If you have more details about this problem could you please open an issue for it?

Thanks a lot.

**Comment by ThePhD** [comment]
The wording on that is poor, it should say "get a function written out normally by Lua, and then get it out again". I had written it after going into the luacppinterface source and changing the LuaFunction type-checker to accept userdata... only for it to fail the other way around. I'll switch the wording.

[Here is what I am talking about](https://github.com/ThePhD/lua-bench/blob/master/lua%20bench/src/luacppinterface.cpp#L93). The way your type checkers work, you only check if it's a function -- or if it's a userdata -- and only then do you allow someone to call it. You can't have both of those commented-out samples work at the same time.

Tables can be functions. Userdata can be functions. Functions can be functions. That should be allowed by your library, but it's not. I don't see a type to be specific about what I would want to get out either (LuaFunction vs LuaCFunction vs LuaUserdataFunction, for example), and even if you did make 3 separate types for it I would probably vomit (the code inside of them would look entirely identical). Your library uses this fact to create C Functions, but your `LuaFunction` abstraction doesn't understand the regular hand-written function anymore.

I will change it if the library changes.

**Comment by davidsiaw** [comment]
I am not sure if I understand you correctly, but I am assuming that "get a function written out normally by Lua" means "to get a function defined in a Lua script", and "get it out again into a LuaFunction" to mean "to get a function from Lua as a LuaFunction".

I am still struggling to understand what "broken" in your code comment specifically means, so I attempted to run the code mentioned, and there is no problem. Both methods yield the expected results (renamed the vars and removed the chrono):

```c++
#include <iostream>
#include <memory>
#include <luacppinterface.h>

inline int basic_call(int x) {
	return x;
}

int main()
{
	
	Lua lua;
	auto global = lua.GetGlobalEnvironment();
	global.Set("f", lua.CreateFunction<int(int)>(basic_call));
	
	auto f = global.Get<LuaFunction<int(int)>>("f");

	auto result = f.Invoke(5);

	std::cout << result << std::endl;


	Lua lua2;
	auto global2 = lua2.GetGlobalEnvironment();
	lua2.RunScript(R"(function f (i)
		return i;
	end)");
	
	auto f2 = global2.Get<LuaFunction<int(int)>>("f");
	auto result2 = f2.Invoke(6);

	std::cout << result2 << std::endl;

	
	return result != 5 || result2 != 6;
}

```

**Comment by ThePhD** [comment]
This same code crashes on your `ziab-fixes` branch, which is the branch I used and did a PR against earlier when running my tests. It introduces "strict type checks" commit [here](https://github.com/davidsiaw/luacppinterface/commit/d7eba394d36c769e94397fb5cc71251f5605f9aa), and this branch will crash tests with an abort.

Nevertheless, it's probably fair that I judge luacppinterface based on the state of your `v1`/`master` branches, not the latest volatile branch instead. I will change the docs accordingly.

**Comment by davidsiaw** [comment]
Alright. Great. Thanks for making me aware of this problem in the [davidsiaw/luacppinterface@ziab-fixes](https://github.com/davidsiaw/luacppinterface/tree/ziab-fixes) branch.
