### ISSUE TITLE
.unregister() on only one state

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#870]
I want to unregister an usertype for a sol::state, but as far as I know it would also unregister all for all the other sol::states, can I do this on only 1 sol::state.

(I want to do it for safety, in some instances using some data structures is UB)

**Comment by ThePhD** [comment]
Sounds like a buuuug.

**Comment by xzores** [comment]
How? I am asking how to unregister a usertype for a single sol::state? sol::usertype<T>.unregister, does not take in an sol::state, so how would it know? and I find no documentation how to access a states version of some usertype?

**Comment by xzores** [comment]
when I say "I want to do it for safety, in some instances using some data structures is UB", I mean I have multiple threads running some lua code. The lua code sometimes needs a shared_ptr that might be shared with other threads, therefor it is UB if 2 threads access the shared_ptr at the same time. I want to control when a lua state can access the members.

**Comment by ThePhD** [comment]
I mean there's a bug in sol3, not in your code, and I need to look into this and fix it.

**Comment by xzores** [comment]
How is it a bug? is there suppose to be an sol::state::remove_usertype?

**Comment by ThePhD** [comment]
`usertype is derived from `sol::reference`. `usertype` has a reference to the current state.

unregister deleting it from all states is a bug. It is a sol3 bug.

**Comment by xzores** [comment]
Ohh ok, never tried :). But how would you do it without a instace of a the usertype? (or am i missing something?)

**Comment by ThePhD** [comment]
So you can call the `.unregister()` function on any type and it should just do it for a single state only. If you want to do it for all states you need to loop through each and every state and call `.unregister` on that `sol::usertype<Class>` or the un-typed `sol::metatable`.

I should've just answered this a long time ago...!
