### ISSUE TITLE
Passing "unnamed" sol::table between Lua and C

### ISSUE THREAD

**Issue by solchanel** [ThePhD/sol2#871]
I am having trouble with passing "unnamed" table from Lua to C function with `sol::table`.
I was looking into docs how to pass Lua table trough but I couldn't find any example or issue without passing table without keys, the closest related issue I came up with  [#374](https://github.com/ThePhD/sol2/issues/374).
The code:
```
struct SimpleClass
{
	void SimpleClass::DrawPosition(sol::table pos)
	{
		cout << "Pos: {" << pos.get<float>(0) << ":" << pos.get<float>(1) << endl;
	}
};

int main()
{
	sol::state State;

	auto name_space = State["name_space"].get_or_create<sol::table>();
	name_space.set_function("DrawPosition", &SimpleClass::DrawPosition);

	State.open_libraries();
	State.script(R"(
		print("Hello world")
		name_space.DrawPosition({ 100.0, 50.0 })
	)");

	return 0;
}
```
output:
`Hello world`
~~From the debugger point of view, its crashing at `name_space.DrawPosition` (script->luaL_loadbufferx)
I'v got a question, is it even possible to push such table without keys or am I doing something wrong with sol::table?~~

edit:
I see the problem now, I did a mistake with registering member functions of my static object with lambda in this chapter: [namespacing](https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#namespacing). my guess is that works only with created objects, my question is Can I bind static member function like that?

**Comment by ThePhD** [comment]
Yes.

Make it `static`.
