### ISSUE TITLE
SOL_ALL_SAFETIES_ON in sol³ doesn't handle nil arguments or mismatched types

### ISSUE THREAD

**Issue by Samulus** [ThePhD/sol2#873]
System: `Linux desktop 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux`
Compiler: `g++ (GCC) 9.1.0`
Sol version: `b2c22ea`

I'm running into two issues related to the `SOL_ALL_SAFETIES_ON` flag seeming to fail on me:

1) Providing a `nil` argument to a bound usertype triggers a SEGV
2) Providing the wrong type of argument (A `Vec3` instead of a `Material`) silently fails, causing undefined behavior later in my program.

Reproducible gist here: https://gist.github.com/Samulus/27d6db0aebe0f3c51e4c8dc52fec306a

**Comment by ThePhD** [comment]
No repro on silent failure: handler gets called.

**Comment by ThePhD** [comment]
Repro on SEGV on all platforms.

**Comment by xzores** [comment]
Hmm, I have a problem with SOL_ALL_SAFETIES_ON, where it throws on mismatched types (expected = boolean) and (actual = sol::nil). It throws in error_handler.hpp somewhere on line 96.

**Comment by ThePhD** [comment]
@xzores That sounds exactly expected.

**Comment by xzores** [comment]
but can't I say something like never throw?

**Comment by xzores** [comment]
I call safe_script in a try catch

**Comment by ThePhD** [comment]
`safe_script(the_script, ..., sol::script_pass_on_error);`, or pass in your own handler. See the tutorials and examples for more information: https://github.com/ThePhD/sol2/blob/develop/examples/source/tutorials/quick_n_dirty/running_lua_code_safely.cpp#L28

**Comment by ThePhD** [comment]
This is fixed now, pull from latest.

**Comment by Samulus** [comment]
:+1: Thanks for fixing this. The silent failure you couldn't reproduce now fails as expected on my machine. SEGV is gone too.
