### ISSUE TITLE
use other hashtables than std::unordered_map for user types et al?

### ISSUE THREAD

**Issue by Spacechild1** [ThePhD/sol2#874]
Hi, this is just a question: since `std::unordered_map` is not exactly the best hash table in the world (the C++ standard forces library authors to implement it with buckets), are there any plans to support other types of hash tables (besides `boost::unordered_map`) or even add your own optimized hash table for things like user type method lookup? I'm specifically thinking about hash tables with open addressing to improve cache performance. I haven't done any measurements myself, I'm just curious if that is something you have thought about. Anyway, thanks for the great work! sol3 is of course my favourite lua binding library :-)

**Comment by ThePhD** [comment]
Nope, because that's another dependency I have to maintain, and another dependency people will complain about (e.g., if I used Abseil's hash maps).

**Comment by Spacechild1** [comment]
I see, I was just wondering about the possible performance improvements (after all, `std::unordered_map` is terrible). I might run some tests with other hash table implementations and report back if I find significant improvements. Thanks for your attention!

**Comment by ThePhD** [comment]
That's be fantastic.
