### ISSUE TITLE
Passing C++ unsigned char* array to Lua crashes it, maybe I'm doing something wrong?

### ISSUE THREAD

**Issue by benoves** [ThePhD/sol2#876]
Well, I tried the example from readthedocs:
lua["my_arr"] = &cppArray;
That's how you pass C++ functions to Lua too (without &), which works fine. But for arrays, it crashes when you use the array, e.g. print(my_arr[1]), I think it's because the array is C++ and not C.

I found a workaround, but it's extremely slow:

    lua.script("my_array={}");
    for (int i = 0; i < 5000000; i++) {
        lua["my_array"][i] = cppArray[i];
    }

Copying value by value from C++ to Lua is such a huge overhead... not efficient at all! And why isn't it as simple as passing a non-array variable? Unless I'm missing something, I think you should add such feature and make it simple. The reason I want to copy the array to Lua is to decrease the overhead of calling the C++ function which handles this array from Lua _millions of times_.

**Comment by ThePhD** [comment]
A pointer is not an array.

If `cppArray` is a pointer type, then it is expected that this code fails. Use a `span` implementation (https://github.com/martinmoene/span-lite) or whatever to change it from being a pointer to an array.

If `cppArray` is a real array (not a pointer, but a `unsigned char[500000]` or similar) then this is a bug and I would like to see a bit more of the code so I can reproduce and fix it.

**Comment by benoves** [comment]
Yes, cppArray is a pointer. I resolved the problem by copying the pointer to an array with memcpy, though not before I figured out that local arrays have a stack limit of 1mb on Windows, and my array is larger than that, which was leading to unexplained crash. I figured out that declaring much smaller arrays worked, so the problem was the array size. The solution I found on Google, and which worked, was to have it declared globally.

This is working fine:
    lua["my_arr"] = &cppArray;
However, my_arr starts at index 1, whereas on cppArray it's 0. Sol3 ignores this fact, even though you can have index 0 on Lua if you declare explicitly (I know that "by default" it starts at 1). It's just an observation, I had to change my function a little bit because of the initial index position, all is fine now. I think you could change sol3 to respect the index, but if it's to introduce overhead, leave as is.

Now I have to figure out why my program crashes with LuaJIT, considering that you wrote and I read in the release notes of LuaJIT-2.1.0-beta3 that it has x86 C++ Exception Interoperability.

My program shows exceptions in a separate window, and since each Lua VM runs in its own thread, you'll see the exception printed to this window referring the script that threw it, but the program continues running. Not if you replaced Lua with LuaJIT: it crashes the entire program on exception!

This code:
    a = "hello" .. world
Will throw an error with Lua: world, which is not defined anywhere, is a nil value.
So far so good: the program was able to report the exception that Lua threw, and the other threads continue running unaffected.
But on LuaJIT, the same code will lead to a total crash of the program. What are your tips, why is it that vanilla Lua works but LuaJIT-2.1.0-beta3 crashes on exception?

**Comment by ThePhD** [comment]
Lua indexes things from 1, not 0. That's not a sol3 bug or anything else, that's just how Lua behaves.

LuaJIT and Lua have different ways of handling exceptions. Also, exceptions should not be used to handle errors from Lua, because they are unsafe. Please execute code using `safe_script` rather than `script`, etc. etc. This is all talked about in the tutorial: https://sol2.readthedocs.io/en/latest/tutorial/all-the-things.html#running-lua-code

**Comment by benoves** [comment]
Not the complete code, but changing:

```
try {
    ...
} catch (const sol::error& e) {
    ...
}
```

To:
            
```
auto bad_code_result = lua.script(codeStr, [this](lua_State*, sol::protected_function_result pfr) {
    ...
    return pfr;
});
```

Did it for LuaJIT, now the exception behavior is the same as with vanilla Lua: the exception appears in the dialog window where you can see what was wrong with script, and the other threads, running separate VMs, continue working normally. Hopefully this information will help others.

What are the differences between try { ... } catch { ... } and sol::protected_function_result?

In the context between these two exception handling, how is x86 C++ Exception Interoperability affected, if at all?

**Comment by ThePhD** [comment]
Please read the documentation: https://sol2.readthedocs.io/en/latest/exceptions.html
