### ISSUE TITLE
sol::overload + bind values

### ISSUE THREAD

**Issue by DaedricSpartan99** [ThePhD/sol2#878]
In the example below I'm using the function sol::overload and I would like to bind 
the value of _eman_ to the two connect calls, but it doesn't compile. 
What should I use as syntax in order to make it work?
`
enum key_t = {...};
enum mouse_t = {...};

class Event_manager {
public:
    void connect_key(key_t);
    void connect_mouse(mouse_t);
private:
    // stuff used in connect_key and connect_mouse
};

Event_manager eman; // singleton

int main() {
      sol::state state;  
      state.set_function("connect", sol::overload(
                         &Event_manager::connect_key,
                         &Event_manager::connect_mouse), &eman); // here is the issue
}
`

**Comment by ThePhD** [comment]
You will have to use a lambda or std::bind instead, attaching the `eman` argument to each individual lambda.

Not quite as efficient, but that's the price, unfortunately!

**Comment by DaedricSpartan99** [comment]
Got it. Thank's!
