### ISSUE TITLE
Thread safety for set / set_function

### ISSUE THREAD

**Issue by benoves** [ThePhD/sol2#881]
I have this simple yet powerful working code:

std::map<std::string, std::variant<bool, double, std::string>> m;

l.set("g", &m);

Now I can exchange stuff between VMs.

But I've found out that writing and reading to &m simultaneously may result in reading corrupt data (in my case, it seems an empty string is returned).

VM 1: while (true) do **g.foo = "bar"** end
VM 2: while (true) do **print(g.foo)** end

Occasionally prints ""

I propose either the optional sol::threadsafe, as in:
l.set("g", &m, sol::threadsafe);
l.set_function("g", &m, sol::threadsafe);

Or the creation of set functions with it enabled:
l.set_threadsafe("g", &m);
l.set_function_threadsafe("g", &m);

So that a RAII mutex is held from the sol side of things for the duration of the call.

In my example l.set("g", &m) where m is a std::map, is mutex protection even possible if implemented from the sol side? What I know is that it's not possible to bind a mutex to an object.

**Comment by ThePhD** [comment]
`sol::state`s do not communicate. You would need to set that architecture up yourself. Lua does not concern itself with thread safety, and neither can I: you will need to make a container shim and lock on usage. You can override container behavior by reading the docs and using the extension points described therein: https://sol2.readthedocs.io/en/latest/containers.html#container-overriding

**Comment by benoves** [comment]
I'm aware that states cannot communicate, but you can bind Lua to C++ and therefore share data, as I did by binding to a std::map where you can easily share numbers, bool and strings between states.

std::map<std::string, std::variant<bool, double, std::string>> m;
l.set("g", &m);

VM 1: g.foo = "bar"
VM 2: print(g.foo) // prints bar

By thread safety, I'm not asking a revolutionary change to the sol::state itself, but merely an introduction of a std::lock_guard mutex on the set / set_function sol side (as an optional!) so when calling g from a thread, the other threads are held by the mutex until the call ends.

Is it possible to implement this feature? Maybe it's unfeasible, I think of sol as a single, separate logic even when you run multiple states, in which case I guess it's possible to implement set / set_function with the optional of a mutex.

**Comment by ThePhD** [comment]
I think you underestimate the amount of work that would go into adding thread guards to specific variables for the binding layer, and protecting every operation in the interpreter.

Making an invisible-to-the-user requires a metric hellton of work to do for any variable. The API you write looks simple but it would not only be incredibly inefficient (as I can only provide the most coarse guarantees), it would also be an excessively enormous amount of work.

There are concurrent maps and concurrent queue implementations: I suggest you pick up those and use them, and maybe they define a standards-like enough API that it gives you what you need with little to not effort on your part.

The extension points I pointed you to are your way of protecting the operations at a fine-grained level. If you want coarse-grained, interpreter-level locks on a single Lua state, recompile Lua with `lua_lock(lua_State*)` and `lua_unlock(lua_State*)` functions defined. (But that would entirely freeze one interpreter while something was running, defeating the point of the threading to being with).

**Comment by benoves** [comment]
I liked your suggestion of using a concurrent map library, so I searched for one and found this: https://github.com/kshk123/hashMap

"A concurrent thread-safe hash map implemented in C++."

CTSL::HashMap<std::string, int> m(1000);
l.set("g", &m)

g.test = 1
print(g.test) // attempt to index global 'g' (a userdata value)

While sol works with std::map out of the box, it's unable to interface with this library. Am I missing something obvious?

If not, then I guess it'll be a hassle to make custom implementations of concurrent map work with sol, as it doesn't seem to understand the data type.

**Comment by benoves** [comment]
The bad and the good news.

I found another concurrent map library: https://github.com/greg7mdp/parallel-hashmap/

This one works with sol, but when two threads are loop-writing to the variable (tens of thousands of times a second) and a third thread reads it, often it gets garbage value so the concurrency is not really there, I'm at a loss as to why, perhaps you could test.

Why am I insisting on using a table-like variable (e.g. std::map) instead of a function? Because Lua's syntactic sugar is awesome!

g["foo"] = "bar" can be replaced by g.foo = "bar" which is pretty much like you declare any variable in Lua, so people are more accustomed to it and it looks cleaner.

Sadly, that's not possible with functions as far as I'm aware.

For the sake of functionality, I'm sticking to an overloaded function:

```
        lua.set_function("g", sol::overload(
                               [this](std::string str) {
                                   return global(str);
                               },
                               [this](std::string str, std::variant<bool, double , std::string> var) {
                                   global(str, var);
        }));
```

The C++ has two overloaded functions named _global_, one to set and one to get, and for concurrency both have to lock the same global mutex: if a thread is reading, it blocks both reading and writing by other threads, and if a thread is writing, it also blocks both reading and writing by other threads. I didn't know that by locking a global mutex, all places with this mutex is locked! In other words, you can lock sections where your thread has not even touched. Am I correct? I sure as hell didn't get more garbage value after doing this.

My request for you, who's doing a good job with sol3, is to go beyond making sol3 a pure wrapper and add thread-safety for set / set_function and later data sharing between states via a table-like global C++ variable, this topic is among the most searched for Lua newbies.
