### ISSUE TITLE
equal_to metafunction not called

### ISSUE THREAD

**Issue by TravellingSalesPerson** [ThePhD/sol2#882]
I have created a c++ numeric type `foo` I would like to use from lua. Eventually I ran into a problem, where it seems `foo`'s equality comparison is not called when I compare an object of type `foo` with an element of a `std::vector<foo>`.

Consider the following example:

```
#include <iostream>

#include "sol.hpp"

struct foo {
	explicit foo(int d) : data(d) { }	
	int data;
};

int main() {
	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<foo>("foo",
		"new", sol::constructors<foo(int)>(),
		sol::meta_function::addition, [] (foo d0, foo d1) -> foo {
			return foo(d0.data + d1.data);
		},
		sol::meta_function::equal_to, [] (foo d0, foo d1) -> bool {
			std::cout << "equality\n";
			return d0.data == d1.data;
		}
	);

	lua["getdata"] = [] () -> std::vector<foo> {
		return { foo(4) };
	};

	lua.script(R"(
		local a = foo.new(4)	
		local fromvec = getdata()[1]
		print(a == fromvec)
		print(a == fromvec + foo.new(0))
	)");
}
```

Which prints:
```
false
equality
true
```

The variables `a` and `fromvec` both refer to an object of type `foo` containing the value `4`.
However, the first equality check between the two returns false.

In the second equality check, I add `0` and this makes the equality check suddenly work. Also note that the string "equality" is printed which means that my custom equality operator actually was called.

I am on Ubuntu 18.04 and both luajit and lua5.2 produced the same unexpected output on the development branch, 88355fcdf85dfcf52c76e41f75b36cd6ba0b7954 for the record.
I compiled with g++ 7.4

I would have expected the following output

```
equality
true
equality
true
```

I have digged a little bit furthur and tried:
```
lua.script(R"(
	local a = foo.new(4)	
	local fromvec = getdata()[1]
	print(getmetatable(a))
	print(getmetatable(fromvec))
	print(getmetatable(fromvec + foo.new(0)))
)");
```

which prints
```
table: 0x56506b6a0e70
table: 0x56506b6a1130
table: 0x56506b6a0e70
```

From this output it appears that the following happens:
1. An object `foo` has a different metatable than an element of a `vector<foo>`. Lua's equality operator sees this and falls back to address comparison. Since `0x56506b6a0e70 != 0x56506b6a1130`, it prints `false`.
2. Adding the two objects seems to work even with different metatables. Furthermore, the metatable of the result is the same as the original `foo`'s. This explains why adding `foo.new(0)` makes the example work.

I am not sure what I am doing wrong. It would probably work if I simply return the elements as a sol:table instead of a std::vector<foo>. But I figured there is something that I am doing wrong conceptually and I was hoping for some insight on how I should do this in the correct way.

Thank you very much for your help. sol is really helping me a ton!

**Comment by ThePhD** [comment]
### Short answer
Upgrade to Lua 5.3.

### Long Answer:

Nope. You've run afoul of Lua 5.1 and Lua 5.2's "shortcut", built into the spec itself for 5.2 and below:

> "eq": the == operation. The function getequalhandler defines how Lua chooses a metamethod for equality. A metamethod is selected only when both values being compared have the same type and the same metamethod for the selected operation, and the values are either tables or full userdata.

Lua 5.3 takes those ruless of the table:

> __eq: the equal (==) operation. Behavior similar to the addition operation, except that Lua will try a metamethod only when the values being compared are either both tables or both full userdata and they are not primitively equal. The result of the call is always converted to a boolean.

**Comment by TravellingSalesPerson** [comment]
Thank you very much for your very prompt help.

Unfortunately, switching away from luajit is not possible for me.

I fail to understand why `a` and `fromvec` have different metatables in the first place.

For example, when I use std::pair<foo, foo> as a container instead of std::vector or when I use as_table on the vector, it suddenly works:
```
lua["getdata2"] = [] () -> std::pair<foo, foo> {
	return { foo(4), foo(4) };
};

lua["getdata3"] = [] () {
	std::vector<foo> result { foo(4), foo(4) };
	return sol::as_table(result);
};

lua.script(R"(
	local a = foo.new(4)	
	local x1, _ = getdata2()
	local x2 = getdata3()[1]
	print(a == x1)
	print(a == x2)
)");
```
The output is:
```
equality
true
equality
true
```

Is there an explanation on why `a` and `fromvec` have different metatables whereas `a`, `x1` and `x2` have the same when passed as `std::pair` or `as_table(std::vector...))`

If lua 5.3 is not an option, is there a solution that avoids such pitfalls or at least a guideline you can recommend following when implementing such a lua usertype?

**Comment by ThePhD** [comment]
Because they get serialized as values into Lua, whereas taking a value straight from a `std::vector<T>` returns references into Lua to mirror the semantics someone would want out of C++.

Because we are required to keep object lifetimes valid and destroy objects appropriately, things serialized into Lua (as regular values) must have their destructors called. Things serialized from references (`return my_cpp_vec[3]` in Lua) need to not have their destructors called, because they are references and do not own the lifetime.

You can read on the choices between returning value vs. references here:
https://sol2.readthedocs.io/en/latest/functions.html#functions-and-argument-passing

You can see the memory layout for things serialized into C++ here:
https://sol2.readthedocs.io/en/latest/api/usertype_memory.html#for-t

**Comment by ThePhD** [comment]
(To be clear: references and values have different metatables, because they need to have different `__gc` methods. No, having or not having `__gc` on reference vs. value is not something made available for customization through sol3's `usertype`.)

**Comment by mrmiller** [comment]
I'm in a similar situation and was working on a patch for moonjit to get this working. That said, I'm a little curious why it can't work as is. I understand that the metatables are different and why they need to be different. But according to my reading of the spec (and after looking at the Lua and luajit source), `__eq` doesn't compare the metatables—it compares the actual functions on both metatables bound to `__eq`. If both `__eq` functions are equal, then it will get invoked.

I'm most definitely a Lua novice, so I may be way off base... but why can't the metatables all share the same function?

**Comment by mrmiller** [comment]
> If I manually bind a function to `__eq` rather than using the automagical bindings, I can achieve my expected behavior and everything works.

Just to clarify what I mean here, this gives me the correct behavior for `__eq` in Lua 5.1 & 5.2:
```
template<typename T>
static sol::usertype<T> registerType(sol::state s, char const * name)
{
  return sol.new_usertype<T>(name,
    sol::no_constructor,
    /* other members */
    sol::meta_function::equal_to, sol::object(runtime.getState(), sol::in_place, &T::operator==)
  );
```

Leaving out the explicit binding to `equal_to` and relying on the automagical binding or simply binding `&T::operator==` doesn't work, because each metatable has a different function from Lua's perspective.
