### ISSUE TITLE
sol::coroutine not staying dead after being called again

### ISSUE THREAD

**Issue by shohnwal** [ThePhD/sol2#883]
I'm a bit confused about Luas behavior when a coroutine exits vs what sol2 does when a coroutine exits. I'm using the latest release of sol2 (v3.03) and LuaJit.

Using Lua only i used this to examine coroutine status behavior and call behavior
```lua
function func()
  coroutine.yield(1)
  coroutine.yield(2)
  return 3
end

local co = coroutine.create(func)
print(coroutine.status(co))
print(coroutine.resume(co))
print(coroutine.status(co))
print(coroutine.resume(co))
print(coroutine.status(co))
print(coroutine.resume(co))
print(coroutine.status(co))
print(coroutine.resume(co))
print(coroutine.status(co))
print(coroutine.resume(co))
print(coroutine.status(co))
```
Output : 
```
suspended
true	1
suspended
true	2
suspended
true	3
dead
false	cannot resume dead coroutine
dead
false	cannot resume dead coroutine
dead
```
As expected, i can call the coroutine 3 times, after that every call to it will result in the coroutine complaining that it's already dead.

However, when i use sol2 in C++ to create coroutines, they seemingly dont stay dead

```C++
int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::table, sol::lib::string, sol::lib::io, sol::lib::math, sol::lib::debug, sol::lib::count, sol::lib::os, sol::lib::package, sol::lib::ffi, sol::lib::jit);
	lua.script(R"(
		function ErrorHandler(error_msg)
			print("Lua Error :" .. error_msg)
		end
	)");
	sol::protected_function::set_default_handler(lua["ErrorHandler"]);
	lua.script(R"(
		function CoTest()
			coroutine.yield(1)
			coroutine.yield(2)
			return 3
		end
	)");
	sol::thread LuaThread = sol::thread::create(lua);
	std::cout << "Thread status before coroutine assignment : " << (int)LuaThread.status() << std::endl << std::endl;
	sol::coroutine derpyCoroutine = sol::coroutine(LuaThread.state(), lua["CoTest"].get<sol::function>());
	std::cout << "Before first call, costatus : " << (int)derpyCoroutine.status() << " , Thread status : " << (int)LuaThread.status() << '\n';
	for (int i = 0; i < 10; i++) 
	{
		int result = derpyCoroutine(); //coroutine should complain about being dead after 3rd iteration
		std::cout << "result : " << result << " , costatus : " << (int)derpyCoroutine.status() << " , Thread status : " << (int)LuaThread.status() << '\n';
	}
	system("pause");
	return 0;
}
```

Output : 
```
Thread status before coroutine assignment : -1

Before first call, costatus : 1 , Thread status : -1
result : 1 , costatus : 1 , Thread status : 1
result : 2 , costatus : 1 , Thread status : 1
result : 3 , costatus : 0 , Thread status : -1
result : 1 , costatus : 1 , Thread status : 1
result : 2 , costatus : 1 , Thread status : 1
result : 3 , costatus : 0 , Thread status : -1
result : 1 , costatus : 1 , Thread status : 1
result : 2 , costatus : 1 , Thread status : 1
result : 3 , costatus : 0 , Thread status : -1
result : 1 , costatus : 1 , Thread status : 1
Press any key to continue . . .
```

As you can see, in the beginning, before the first call, the coroutine has a `call_status` 1 ("yielded") and the thread has `thread_status` -1 ("dead").

After doing a `coroutine.yield()`  , the `sol::coroutine`, has a `call_status` 1 ("yielded") and the thread has the `thread_status` 1 ("yielded), as expected.

When the `sol::coroutine` returns, the coroutines status goes to `call_status` 0 ("ok") and the thread goes to `thread_status` -1 ("dead").

Unlike pure Lua however (see first example), calling the `sol::coroutine` again, instead of complaining that the coroutine is dead, seemingly restarts it (and its thread?). 

According to the documentation it seems like only yielded coroutines are supposed to be callable, while call_status::ok shouldn't be callable again
https://sol2.readthedocs.io/en/latest/api/coroutine.html
```
The coroutine object is entirely similar to the protected_function object, 
with additional member functions to check if a coroutine has yielded (call_status::yielded) 
and is thus runnable again, whether it has completed (call_status::ok) and thus 
cannot yield anymore values,
```

Personally, i don't mind it, since i can always  check the coroutines `call_status` after each call and check when it's 0 ("ok"), aka when the coroutine is finished and i should abort calling it again. 
Heck, i even like it, i can see some situations where restarting it by just calling it again is more convenient (and perhaps more performant?) than recreating/reassigning/reinitializing via assignment 

I was just wondering if this is intended behavior or subject to change.

**Comment by ThePhD** [comment]
Gonna be extra honest here: not a clue what's going on, I almost never use coroutines. It'll be a while before I debug this.

**Comment by ThePhD** [comment]
I think this behavior was actually the result of an old complaint, where someone wanted the reset behavior from the C API. So I think it'll stay for now, even if it's not how Lua proper behaves. I'm not sure how I feel about it still though....
