### ISSUE TITLE
protected_function_result to bool crash? a bug? 

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#884]
Soo am I doing something wrong? a sol::protected_function_result should be able to implicit cast to boolean right?

Why would this crash my program??
```				
try{
	sol::protected_function_result a = runCodeI(code);
	bool t = a;        **<------- we crash here**
	prom.set_value(t);
}
catch (...) {
	prom.set_value(T());
}
```

and here we have the function:
```
sol::protected_function_result LuaObject::runCodeI(const std::string& s) throw (std::exception, sol::error) {
	
	sol::environment environment = sol::environment(mystate, mystate.globals());

	auto ret = mystate.safe_script(s, environment,
		[&s](lua_State* state, sol::protected_function_result pfr) -> sol::protected_function_result {
		
			sol::error err = pfr;

			Debugger::Error("failed to execute code : " + s + ", error : " + err.what());

			throw err;
			return pfr; // should i delete?
	});

	return ret;
}
```

**Comment by xzores** [comment]
btw is a really great library and you allways seem to close the issues. Very nice work :=)

**Comment by ThePhD** [comment]
Converting to bool is assuming your call succeeded. If your call did not succeed then this is a bad thing.

Finally, exceptions thrown by your handler may be caught by an intermediate layer, especially if you have built Lua as C++. If you have, then throwing an exception and letting it explode out of C++ and into Lua past sol2's exception trampoline results in a hard error. (Do `#define SOL_EXCEPTIONS_ALWAYS_UNSAFE 1` or `-DSOL_EXCEPTIONS_ALWAYS_UNSAFE=1` or whatever the equivalent is one the command line for your build.)
