### ISSUE TITLE
Make sol::property more restrictive to accommodate common setter/getter overload.

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#886]
A common way in C++ to provide getter and setter functions for a property is through a pair of overloaded member functions, one for setting that takes a single argument and returning void, and one for getting that takes no argument and returns a value.

It would be convenient if they could be used directly with `sol::property`, instead of having to resort to lambdas to disentangle the two overloads.

I guess this is because currently the function signatures accepted by `sol::property` are too general, hence sol can't figure out which overload to use. By restricting the signature, it might be possible to allow passing the getter/setter directly.

Example:
```
class my_class {
    int some_property_;
public:
    void some_property(int p);
    int some_property();
};

// usertype registration
lua.new_usertype<my_class >("my_class ",
    "some_property", sol::property(&my_class::some_property, &my_class::some_property)
);
```

Of course, if there's a better way to do this, I'm all ears. I have experimented with `static_cast` to select the proper overload, but how do you even write that down when the overloads are member functions? The recommendation to give the setters and getters distinct names to avoid the overload problem unfortunately isn't helping when the class is from a foreign library one can't change. This pattern is common enough to perhaps warrant a more direct solution than going through lambdas.

**Comment by ThePhD** [comment]
[`sol::resolve`](https://sol2.readthedocs.io/en/latest/api/resolve.html)

**Comment by s13n** [comment]
That is still a bit verbose, but much better, thanks!

I wasn't aware of `sol::resolve` at all,  perhaps it would help to briefly mention it in the bullet point list for functions here:
https://sol2.readthedocs.io/en/latest/functions.html
