### ISSUE TITLE
Can't print usertype.

### ISSUE THREAD

**Issue by s13n** [ThePhD/sol2#887]
I've got the following usertype binding:
```
#include <boost/asio.hpp>
#include "sol.hpp"

// ...

typedef boost::asio::ip::address Address;

lua.new_usertype<Address>("Address",
    "new", sol::factories([]() {
        return Address();
    }, [](std::string_view addr) {
        return boost::asio::ip::make_address(addr);
    }),
    "is_loopback", &Address::is_loopback,
    "is_multicast", &Address::is_multicast,
    "is_unspecified", &Address::is_unspecified
);
```
Now, when I do the following from Lua 5.3.4, it prints an error:
```
> Address
error calling 'print' (stack index 1, expected userdata, received table: value is not a valid userdata)
```
Somehow, sol seems to get confused whether it is a table or a usertype.

**Comment by ThePhD** [comment]
It might have begin/end and you might need to mark it as not being a contianer.

**Comment by s13n** [comment]
It doesn't have begin/end AFAIK. But it has to_string() and operator<<.

Anyway, if it were recognized as a container, wouldn't print() show something like this?
```
table: 0x.....
```

**Comment by ThePhD** [comment]
Maybe. If you bound a `to_string` or similar function and you, somehow, are passing a table to that function rather than an actual userdata, it's going to give that error. I don't know if you've overridden your print function but I can't tell what's going wrong here.

**Comment by ThePhD** [comment]
I can't reproduce this here nor can I get it to catch properly. I default-construct an Address with `Address.new` in Lua and it prints fine:

> 0.0.0.0

This is the code:

```
#define SOL_PRINT_ERRORS 1
#include <boost/asio.hpp>
#include <sol/sol.hpp>

typedef boost::asio::ip::address Address;

int main () {

	sol::state lua;
	lua.open_libraries(sol::lib::base);

	lua.new_usertype<Address>("Address",
		"new", sol::factories([]() {
			return Address();
		}, [](std::string_view addr) {
			return boost::asio::ip::make_address(addr);
		}),
		"is_loopback", &Address::is_loopback,
		"is_multicast", &Address::is_multicast,
		"is_unspecified", &Address::is_unspecified
	);

	lua.script("local addr = Address.new() print(addr)");

	return 0;
}
```

I'm going to close. If you can provide more information that makes it fail, do let me know.

**Comment by anrp-tri** [comment]
Drive-by comment: I think I ran in to this (and I got out of it by `is_automagical<T> : std::false_type`) but the question was about stringifying the type itself, not an object of the type.
