### ISSUE TITLE
lua_longjmp Microsoft C++ exception messages in VS debug output

### ISSUE THREAD

**Issue by firas-assaad** [ThePhD/sol2#889]
I have `#define SOL_USING_CXX_LUA 1` and Lua compiled as C++ using Visual Studio. Everything works fine but I see many `Microsoft C++ exception: lua_longjmp at memory location xxxx` messages in the debug log when running my application inside Visual Studio. The messages seem to originate in `lua_yieldk` which calls `luaD_throw`.

I use sol::yielding and get the expected behavior in terms of yielding between Lua and C++, so I wonder if it's safe to ignore these messages.

Simple program to illustrate it:

    #define SOL_USING_CXX_LUA 1
    #include <sol.hpp>
    #include <iostream>

    int main() {
        try {
            sol::state lua;
            lua.open_libraries(sol::lib::base, sol::lib::coroutine);
            lua["f"] = sol::yielding(
                [](int x) {
                    std::cout << "C++ - Inside f(" << x << ")\n";
                    return x;
                }
            );

            sol::string_view code = R"(
                print('Lua - Before coroutine')
                f(5)
                print('Lua - After coroutine')
            )";

            sol::coroutine co = lua.load(code);
            while (co) {
                std::cout << "C++ - Resuming coroutine\n";
                co();
                std::cout << "C++ - Coroutine status: " << sol::to_string(co.status()) << "\n";
            }
            std::cout << "C++ - Everything went fine!";
        } catch (std::exception & e) {
            std::cout << e.what() << "\n";
        }
    }

Visual Studio debug output:
`Exception thrown at 0x76431932 in SolSchedulerTest.exe: Microsoft C++ exception: lua_longjmp at memory location 0x00AFE354.`

Program output:

    C++ - Resuming coroutine
    Lua - Before coroutine
    C++ - Inside f(5)
    C++ - Coroutine status : yielded
    C++ - Resuming coroutine
    Lua - After coroutine
    C++ - Coroutine status : ok
    C++ - Everything went fine!

**Comment by ThePhD** [comment]
When built as C++, Lua throws exceptions rather than performing an actual `longjmp` to get out of places. Your yield is probably Lua tossing that exception to escape.

Everything seems fine.

**Comment by levilindsey** [comment]
Is there any way to silence these exceptions?
