### ISSUE TITLE
Add "user data" pointer to exception callback

### ISSUE THREAD

**Issue by rmorales87atx** [ThePhD/sol2#891]
Hello,

I had a need for the default exception handler to be a class member, but the design of the exception callback requires it to be a straight C function pointer.

I believe I have sufficiently modified the exception handler to permit the passing of a userdata pointer to enable my usage scenario.

I've included a patch with my changes. I am currently a user of the "single" `sol.hpp` file, so my patch is a diff against that.

[sol_exception_userdata.txt](https://github.com/ThePhD/sol2/files/3800743/sol_exception_userdata.txt)

**Comment by ThePhD** [comment]
The single is regenerated: I don't do patches against the single. Please put a patch against the actual source.
