### ISSUE TITLE
Function that returns vector of shared pointers gets converted into table of raw pointers?

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#894]
This function lists all the available monitors:
`extern std::vector<shared_ptr<Display> > ListDisplays();`

In Lua:
```
local displays = ListDisplays()
local window = CreateWindow(displays[1],0,0,800,600)
```
CreateWindow() expects a `shared_ptr<Display>` but instead it is getting a Display*. What is the best way to deal with this?

**Comment by ThePhD** [comment]
This is a bug that is a residual from fixing returns of `std::vector<unique_ptr<T>>`. This'll be fixed soon.

**Comment by ThePhD** [comment]
Fixed in latest.
