### ISSUE TITLE
Problem registering ordered/sequence container

### ISSUE THREAD

**Issue by valkarion** [ThePhD/sol2#895]
Hi. 

I have a container that's basically a few abstractions over a std::vector to insert and remove elements in order. When I register it to Sol the automagic can pickup on insertion (by giving it a push_back, not insert), length, and iteration but when calling erase I get the following message: sol: cannot call erase on 'sorted_vector<int,std::less<int> >'

Here's a complete example: 

	#include <iostream>
	#include <vector>
	#include <algorithm>
	#include "sol.hpp"

	template <typename T, class Compare = std::less<T>>
	class sorted_vector {
		Compare cmp;
	public:
		typedef typename std::vector<T>::iterator iterator;
		typedef typename T value_type;
		std::vector<T> v;

		T& operator[]( const size_t index ) { return v[index]; }

		iterator find( const T& what ) {
			iterator it = std::lower_bound( v.begin(), v.end(), what );
			return it == end() || cmp( what, *it ) ? end() : it;
		}

		bool exists( const T& what ) { return find( what ) != v.end(); }

		void insert( const T& what ) {
			iterator it = std::lower_bound( v.begin(), v.end(), what );
			if ( it == v.end() || what < ( *it ) ) {
				v.insert( it, what );
			}
		}
	
		iterator erase( const T& what ) {
			return v.erase( std::remove( v.begin(), v.end(), what ), v.end() );
		}

		void push_back( const T& what ) { insert( what ); }

		void clear() { v.clear(); }
		bool empty() const { return v.empty(); }
		size_t size() const { return v.size(); }
		iterator begin() { return v.begin(); }
		iterator end() { return v.end(); }
	};

	namespace sol {
		template <typename T>
		struct is_container<sorted_vector<T>> : std::true_type {};
	}

	int main() {
		sol::state L;
		L.open_libraries( sol::lib::base, sol::lib::table );

		sorted_vector<int> vec;
		vec.insert( 1 ); vec.insert( 2 ); vec.insert( 4 );

		L["vec"] = &vec;

		auto res = L.script( R"(
			print(#vec)
			for _, v in pairs(vec) do 
				print(v)
			end

			vec:add(3)
			for _, v in pairs(vec) do 
				print(v)
			end

			vec:erase(2)
	)" );
	   
		std::cin.get();
	}

Accoring to the docs, ordered and sequence containers look for different kind of erase functions, so I am not sure if that's the problem, or how to ask the lib nicely to use the one I want (erase by element type value). I am using the latest version of Sol on VS2019.

**Comment by ThePhD** [comment]
You need `typedef T key_type;` to have it look like a lookup container like `set`.
