### ISSUE TITLE
Unable to pass objects from C++ to lua member functions

### ISSUE THREAD

**Issue by Bennett-ewan** [ThePhD/sol2#899]
Read these guidelines. They are relatively simple and will allow me to help you better:

I am able to pass an object to a global function from C++, with the following function:
```
function Collision(Object)
  --Handle object
end
```
The object is a class that I have defined as a usertype, and I can correctly handle it with this function. However, I have created collision functions for individual behaviors that are derived from a parent behavior. The function looks like:
```
function Behavior:On_Collision(Object)
  --Handle object
end
```
I call the function from C++ with the following code:
```
onCollision(obj)
```
onCollision is a sol::protected_function and obj is a user defined type. This exact same syntax works the global collision function, but not the member function. It does correctly call the On_Collision member function, however the object passed in is nil. 

Any guidance would be appreciated. Let me know if you need any more information
Thanks so much!

**Comment by ThePhD** [comment]
Remove the `Object` parameter in the `Behavior:On_Collision` call. Then, use `self`: Lua implicitly injects `self` as a variable referring to the object in functions defined with a colon `:` character.

I know, wonky, but that's how it works. Good luck!

**Comment by Bennett-ewan** [comment]
> Remove the `Object` parameter in the `Behavior:On_Collision` call. Then, use `self`: Lua implicitly injects `self` as a variable referring to the object in functions defined with a colon `:` character.
> 
> I know, wonky, but that's how it works. Good luck!

I understand that, however this function is to handle the collision between two objects. The parameter object is the the other object that is is colliding with, so it is different than self

**Comment by ThePhD** [comment]
There is no implicit `this` or `self` in Lua, when you're inside another function object call. Do:

```
self:onCollision(obj)
```
or
```
obj1:onCollision(obj2)
```
or
```
obj1.onCollision(obj1, obj2)
```
or
```
obj1.onCollision(obj2, obj1) -- reverse params, maybe it matters
```
or
```
self.onCollision(self, obj2)
```
or
```
obj2.onCollision(self, obj2)
```

To fix the problem. Whatever fits your fancy. Note the places where `:` matters or does not matter.
