### ISSUE TITLE
Compilation fails with -fno-exceptions

### ISSUE THREAD

**Issue by 3damned** [ThePhD/sol2#901]
// SOL_SINGLE_INCLUDE_HPP
// This file was generated with a script.
// Generated 2019-10-02 08:43:38.869924 UTC
// This header was generated with sol v3.0.3 (revision 908074e)
// https://github.com/ThePhD/sol2

Compiling with Apple clang version 11.0.0 (clang-1100.0.33.8) 
clang++ -std=c++17 -O2 -fno-exceptions

SOL_NO_EXCEPTIONS 1 got defined but..

sol.hpp:3538:3: error: cannot use 'try' with exceptions disabled
                try {
                ^
sol.hpp:5000:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:5007:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:5013:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:5021:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:5855:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:5862:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:18340:3: error: cannot use 'throw' with exceptions disabled
                throw dump_error(result_code);
                ^
sol.hpp:5000:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:23931:15: note: in instantiation of member function 'sol::optional<sol::basic_environment<sol::basic_reference<false> > >::value' requested here
                        return env.value();
                                   ^
sol.hpp:5007:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:23935:15: note: in instantiation of member function 'sol::optional<sol::basic_environment<sol::basic_reference<false> > >::value' requested here
                        return env.value();
                                   ^
sol.hpp:5000:4: error: cannot use 'throw' with exceptions disabled
                        throw bad_optional_access();
                        ^
sol.hpp:24280:44: note: in instantiation of member function 'sol::optional<std::__1::basic_string_view<char, std::__1::char_traits<char> > >::value' requested here
                        const string_view& topmsg = maybetopmsg.value();
                                                                ^
sol.hpp:3538:3: error: cannot use 'try' with exceptions disabled
                try {
                ^
sol.hpp:3549:48: note: in instantiation of function template specialization 'sol::basic_insert_dump_writer<sol::basic_bytecode<std::__1::allocator<std::byte> > >' requested here
        constexpr inline auto bytecode_dump_writer = &basic_insert_dump_writer<bytecode>;
One wonders if SOL_NO_EXCEPTIONS 1 implies the case when c++ exceptions were turned off with -fno-exceptions.

**Comment by ThePhD** [comment]
It should work; surprised there's a naked `try` literally anywhere in the code that isn't protected; I haven't touched that code recently.

**Comment by ThePhD** [comment]
Hey, this should be fixed now.

**Comment by 3damned** [comment]
Thank you! It compiles and works fine now.
P.S.> Actually I had to do one more little thing to get it compiled: moved `dump_panic_on_error ()` definition right before its caller -`dump_throw_on_error ()` definition.
