### ISSUE TITLE
Line numbers for wrong arguments errors only shown with overloaded function

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#902]
When I make a mistake in the parameters I give a C++ function or method, if the function is overloaded I get a nice message like this:
`Error: [string "C:/------/scripts/objects/player/fpsplayer.lua"]:150: sol: no matching function call takes this number of arguments and the specified types`

If the function is _not_ overloaded, then I get an error like this:
`Error: stack index 2, expected string, received boolean:`

This makes it very difficult to tell where my mistake is. What do I need to do differently to make line numbers appear for these errors? (Possibly related to https://github.com/ThePhD/sol2/issues/666)

I am always using protected_function.

Sol is included like this:
```
#define SOL_NO_CHECK_NUMBER_PRECISION 1
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>
```
I have an exception handler set:
```
int exception_handler_function(lua_State* L, sol::optional<const std::exception&> maybe_exception, sol::string_view description)
{
	std::string err = std::string(description);
	DebugError(err);
	return 0;
}
lua->set_exception_handler(&exception_handler_function);
```
C++ calling code looks like this:
```
bool Entity::CallFunction(const std::string& name)
{
	if (VirtualMachine::L == nullptr) VirtualMachine::Reset();

	auto L = VirtualMachine::L;
	bool success = false;
	auto self = dynamic_pointer_cast<Entity>(Self());
		
	sol::function errorfunc = {};
	lua_getglobal(L, "LuaErrorHandler");
	if (lua_isfunction(L, -1)) errorfunc = sol::function(L);

	int stacksize = lua_gettop(L);
	sol::stack::push(L, self);
	sol::stack::get_field(L, name);
	if (lua_isfunction(L, -1))
	{
		auto f = sol::protected_function(L);	
		if (f.valid())
		{
			if (errorfunc.valid()) f.set_default_handler(errorfunc);
			sol::protected_function_result result;
			try
			{
				result = f(self);
			}
			catch (const sol::error & e)
			{
				DebugError(e.what());
			}
			if (result.status() == sol::call_status::ok) success = true;
		}
	}

	lua_settop(L, stacksize);
	return success;
}
```
Here is the Lua error function:
```
function LuaErrorHandler(message)
    if type(message) == "string" then
	   	DebugError(message)
	else
		DebugError("Unknown Lua error.")
    end
end
```
And this is what DebugError() does:
```
void DebugError(const std::wstring& s)
{
	Print("Error: " + s);
	exit(1);
}
```

**Comment by ThePhD** [comment]
`set_default_handler` sets the handler for every single `protected_function` instance. Are you sure that's what you want?

If you want to set the error handler for a single one, just use the variable `error_handler` and set it to a `(protected_)function` of some sort. Calling `set_default_handler` does not affect currently-alive functions, only new ones created after.

Line numbers and general traceback information is a result of `default_traceback_handler`, which is the default attached to `sol::` functions. It seems like you're replacing that with something else, which might explain why the line numbers and other interesting information is disappearing. If you need this information, you should figure out how to work with and call `luaL_traceback`, or just look at the implementation inside `sol::default_traceback_handler` and duplicate what's necessary.

**Comment by JoshKlint** [comment]
Okay, so it looks like the default error handler will push an error message onto the stack you can retrieve after detecting that the function call failed. I did not realize that. So this is the correct way to call functions:
```
bool Widget::CallFunction(const std::string& name)
{
	if (VirtualMachine::L == nullptr) VirtualMachine::Reset();

	auto L = VirtualMachine::L;
	bool success = false;
	auto self = dynamic_pointer_cast<Widget>(Self());

	int stacksize = lua_gettop(L);
	sol::stack::push(L, self);
	sol::stack::get_field(L, name);
	if (lua_isfunction(L, -1))
	{
		auto f = sol::protected_function(L);
		if (f.valid())
		{
			sol::protected_function_result result;
			try
			{
				result = f(self);
			}
			catch (const sol::error & e)
			{
				DebugError(e.what());
			}
			if (result.status() == sol::call_status::ok)
			{
				success = true;
			}
			else
			{
				if (lua_isstring(L, -1))
				{
					std::string msg = lua_tostring(L, -1);
					DebugError(msg);
				}
				else
				{
					DebugError("Unknown Lua error.");
				}
			}
		}
	}

	lua_settop(L, stacksize);
	return success;
}
```

**Comment by 3damned** [comment]
Thank you! It compiles and works just fine now. 
P.S.> Actually I had to do one more little thing to get it compile: moved `dump_panic_on_error()` definition to the lines right before `dump_throw_on_error()` definition, which uses `dump_panic_on_error()
