### ISSUE TITLE
sol::variadic_args use in usertype constructor

### ISSUE THREAD

**Issue by 11nk** [ThePhD/sol2#903]
```cpp
struct foo 
{
	foo(sol::variadic_args args)
	{
		std::cout << args.size() << std::endl;
	}
};


int main(int argc, char ** argv)
{
	sol::state lua;

	lua.open_libraries();
	lua.new_usertype<foo>("foo", sol::constructors<foo(sol::variadic_args)>());

	lua.script(R"(
	foo.new()
	foo.new(0, 1)
	foo.new(0, 1, 2)
	foo.new(0, 1, 2, 3)
	)");
}
```
This will be print
```
1
3
4
5
```
why? my compiler is vc2019.

**Comment by otristan** [comment]
last arg is a sol::this_state

See https://github.com/ThePhD/sol2/issues/471

**Comment by 11nk** [comment]
@otristan thanks!

**Comment by ThePhD** [comment]
🤔 Wait, that doesn't seem right...

**Comment by ThePhD** [comment]
This issue seems slightly unsolvable because I sort of have given people the grand expectation that in constructors the last element on the stack will always be the "self" argument.

Alternatively, I could make all constructor calls slightly slower by pushing a Lua value onto the stack at position 1 instead, and then letting the `variadic_args` construct from there...

Ooph. Breaking API assumptions or doing the right thing........

Hard choice.

**Comment by ThePhD** [comment]
This is now fixed properly and your expectations work.

Good luck!

**Comment by joyoussidd** [comment]
> ```c++
> struct foo 
> {
> 	foo(sol::variadic_args args)
> 	{
> 		std::cout << args.size() << std::endl;
> 	}
> };
> 
> 
> int main(int argc, char ** argv)
> {
> 	sol::state lua;
> 
> 	lua.open_libraries();
> 	lua.new_usertype<foo>("foo", sol::constructors<foo(sol::variadic_args)>());
> 
> 	lua.script(R"(
> 	foo.new()
> 	foo.new(0, 1)
> 	foo.new(0, 1, 2)
> 	foo.new(0, 1, 2, 3)
> 	)");
> }
> ```
> 
> This will be print
> 
> ```
> 1
> 3
> 4
> 5
> ```
> 
> why? my compiler is vc2019.

@ThePhD  How can we print the arguments using std::cout ?? Or if not directly how can we convert it and then print using std::cout ??

**Comment by otristan** [comment]
something like that ?
```
auto lua = args[args.size() - 1]
 for (size_t i = 0; i < args.size() - 1; i++)
          {
            auto v = args[i];

              std::cout << lua["tostring"](v.get<sol::object>()).get<const char*>();
            }
            if (i != va.size() - 1)
            {
             std::cout << " ";
            }
          }
std::cout << std::endl;
```

**Comment by joyoussidd** [comment]
@otristan Need to check this. 

My intension is to accept any data type in argument

It can be any of these
1) Single string element
2) Multiple string elements
3) Single Numeric element
4) Multiple numeric elements
5) Mix of various data types together

So that, I can iterate all the elements and store it in QVariantList (An QT API) by doing the required conversion 

Can you please guide me through this??

**Comment by otristan** [comment]
You can use
```
sol::type type = v.get_type();
switch (type)
            {
              case sol::type::string:
              {
                const char* str = v.get<const char*>();
                break;
              }
              case sol::type::number:
              {
                if (v.is<int>())
                {
                  lua_Integer value = arg.get<lua_Integer>();
                }
                else
                {
                  double value = v.get<double>();
                }
                break;
              }
              case sol::type::boolean:
              {
                bool value = v.get<bool>();
                break;
              }
```

and so on.

**Comment by joyoussidd** [comment]
@otristan Thanks alot friend. I will be trying it today.

**Comment by joyoussidd** [comment]
@otristan 

I tried basic functionality here, but not getting expected size in output.

Lua Snippet

> function init()
> 	ui.TestFunction({2.3, 4.1, 99.12, 77.09})
> end

C++ Snippet

> ui.set_function("TestFunction", [this](const sol::variadic_args& args){
>                 std::cout << "\n### TestFunction ### :- " << args.size() << "\n";
>               });

I am getting size as 1 when it should be 4.

Do you understand why ? Or Am I doing it in a wrong way ?

**Comment by otristan** [comment]
because it's one variable but of type array.
ui.TestFunction(2.3, 4.1, 99.12, 77.09)
will return 4

**Comment by joyoussidd** [comment]
@otristan But I have to include 2 more parameters in the TestFunction()

ui.TestFunction(const std::string &fileObjectName, const std::string &functionName, {........... array data here .....})

How will it work ?

**Comment by otristan** [comment]
3 parameters, 2 string and one array, then you can introspect the array.

Try a bit on your own :)

**Comment by joyoussidd** [comment]
@otristan I need to pass multiple elements together as a part of this 3rd Argument. 

So If I do something like this,

> ui.TestFunction(para1, para2, 3.4, 5,6, 11.99, 33.2);

So will it not consider total parameters as 6 ?

**Comment by otristan** [comment]
yep it will. 
I thought you meant ui.TestFunction(para1, para2, {3.4, 5,6, 11.99, 33.2});

Please try :)

**Comment by joyoussidd** [comment]
@otristan It did not work sir,

```
function init()
	 ui.TestFunction("TestData", "InvokeFunction", {3.4, 5,6, 11.99, 33.2})
end
```

     

```
 ui.set_function("TestFunction", [this](const std::string& qmlFileObjectName, const std::string& functionName,const sol::variadic_args& args){
                std::cout << "\n qmlFileObjectName :- " << qmlFileObjectName << "\n";
                std::cout << "\n functionName      :- " << functionName << "\n";
                std::cout << "\n Total Args        :- " << args.size() << "\n";
                //auto vargs = std::vector<sol::object>(args.begin(), args.end());
              });
```

Size comes out to be 1 here again

**Comment by otristan** [comment]
1 in array plus your two string
```
function init()
	 ui.TestFunction("TestData", "InvokeFunction", 3.4, 5,6, 11.99, 33.2)
end
```
 ui.set_function("TestFunction", [this](const std::string& qmlFileObjectName, const std::string& functionName,const ```
sol::variadic_args& args){
                std::cout << "\n qmlFileObjectName :- " << qmlFileObjectName << "\n";
                std::cout << "\n functionName      :- " << functionName << "\n";
                std::cout << "\n Total Args        :- " << args.size() << "\n";
                //auto vargs = std::vector<sol::object>(args.begin(), args.end());
              });
```

**Comment by joyoussidd** [comment]
Great, It works now. Thanks alot. I tried passing numeric + string elements and got proper count

**Comment by joyoussidd** [comment]
@otristan 

I am not aware of anyway to initialize the sol::variadic_args in my Unit Test Case.

I need to create sol::variadic_args variable and pass to this Function in my Test Case and then verify the conversions to c++ data types.

`void ClassLua::Convert(const sol::variadic_args& args)`

I tried, 

`sol::variadic_args va = "StringData";`

Error : conversion from 'const char [11]' to non-scalar type 'sol::variadic_args' requested

How can I create variadic_args variable with single, multiple and mix data types ??

**Comment by otristan** [comment]
don't think you can in c++ as you are not supposed to.
Do it in lua

**Comment by joyoussidd** [comment]
@otristan Ok Thanks

**Comment by joyoussidd** [comment]
@otristan 

In Lua, How can I create this Multi data type Variable and pass as an argument ?

**Comment by joyoussidd** [comment]
@otristan Can you please guide

**Comment by otristan** [comment]
https://stackoverflow.com/questions/70284743/lua-how-to-create-a-variable-that-can-have-mix-data-types-and-pass-it-as-an-a

**Comment by joyoussidd** [comment]
@otristan 

I have posted that question today..

If I create a variable as

var = {"String", 12, true, 30.11}

I am getting count as 1 when I use sol::variadic_args.

I have to explicity pass var[1], var[2], var[3], var[4] so that sol::variadic_args get the proper count.

**Comment by otristan** [comment]
don't pass the array, call the function with the arg directly OR treat this only arg as a sol::type::table and unroll the resulting parameters.

**Comment by joyoussidd** [comment]
@otristan Do you mean

sol::type::table var = {"String", true, 12, 30.23} 

ui.InvokeFunction(var) ??

**Comment by otristan** [comment]
At some point, you need to do your homework. I have given all the information required to make it work.

**Comment by joyoussidd** [comment]
@otristan Brother

There are other people who work on Lua Side and my part is writing API's in C++ to work on data recieved from Lua

So exploring lua will take alot of time.

**Comment by joyoussidd** [comment]
@otristan 

Thanks alot for all the guidance 😊

**Comment by otristan** [comment]
sol::type type = v.get_type();
switch (type)
            {
case sol::type::table: {
				sol::table inner = value.as<sol::table>();
for (const auto& key_value_pair : inner )
            {
                sol::object key = key_value_pair.first;
                sol::object value = key_value_pair.second;
                std::string k = key.as<std::string>();
                sol::type t = value.get_type();
                switch (t) {
                case sol::type::string: {
                    std::cout << k << ": " << value.as<std::string>() << std::endl;
                }
                    break;
                case sol::type::number: {
                    auto v = value.as<double>();
                    std::cout << k << ": " << v << std::endl;
                }
                    break;
                default:{
                    std::cout << "hit the default case!" << std::endl;
                }
                }
            }
        }
break;
}

**Comment by joyoussidd** [comment]
@otristan Thanks
