### ISSUE TITLE
"undefined reference to `httpserver::operator<<(std::ostream&, httpserver::http_request&) " need non-const operator << 

### ISSUE THREAD

**Issue by fatihwk** [ThePhD/sol2#904]
I'am using libhttpserver lib, just want export the http_request  class to lua . 
  L.new_usertype<http_request>("HttpRequest",
                    "get_path",
                    &http_request::get_path,
                    "get_pass",
                    &http_request::get_pass,
                    "get_user",
                    &http_request::get_user
                    );

will cause the link error 

CMakeFiles/glua.dir/src/main.cpp.o: In function `int sol::detail::oss_default_to_string<httpserver::http_request>(std::integral_constant<bool, true>, lua_State*)':
/home/arthur/work/glua/lib/sol2/include/sol/stack_core.hpp:1357: undefined reference to `httpserver::operator<<(std::ostream&, httpserver::http_request&)'
collect2: error: ld returned 1 exit status

so I must define the non-const operator <<   function for http_request : 
//  std::ostream & operator << (std::ostream & os , http_request  & req)  { //req without non-const 
//    ... 
//      return os; 
//  }; 

i think it's unnecessary to do this . I just wonder .

**Comment by ThePhD** [comment]
That's odd. It shouldn't force trying to get a call to a non-const one...

let me try to mock up a sample that errors reliably for me.

**Comment by ThePhD** [comment]
Can't really repro by deployed some minor fixes in the meantime. Maybe they will fix it for you; reopen if latest doesn't work.
