### ISSUE TITLE
Callback with vector of variants with type not comparable

### ISSUE THREAD

**Issue by damienrg** [ThePhD/sol2#905]
Hi,

The following code does not compile:

```c++
#include <functional>
#include <variant>
#include <vector>

#include <sol/sol.hpp>

struct Foo
{
  int value;
};

using Data = std::vector<std::variant<Foo>>;

using Callback = std::function<void(const Data &)>;

void foo(Callback) {}

int main()
{
  sol::state lua;
  lua.set_function("foo", &foo); // compilation error
  return 0;
}
```
To make the code compile, I have to define a `operator==` for `Foo` or wrap `Data` in struct:
```c++
#include <functional>
#include <variant>
#include <vector>

#include <sol/sol.hpp>

struct Foo
{
  int value;
};

using Data = std::vector<std::variant<Foo>>;

struct Bar
{
  Data data;
};

using Callback = std::function<void(const Bar &)>;

void bar(Callback) {}

int main()
{
  sol::state lua;
  lua.set_function("bar", &bar);
  return 0;
}

**Comment by ThePhD** [comment]
Variant's comparison operators do not SFINAE away, unfortunately, so using non-regular types with no comparisons does not remove the comparison operators.

The quick fix is to un-automagic the type explicitly, but I'll probably do this on purpose in the nearish future: https://sol2.readthedocs.io/en/latest/api/usertype.html#automagical-usertypes

**Comment by ThePhD** [comment]
Should be fine now. Maybe. Ish.

**Comment by damienrg** [comment]
I am not sure I understand the second part of your answer. You mean that doing the following specialization should fix the compilation error:
```c++
namespace sol {
template <>
struct is_automagical<std::variant<Foo>> : std::false_type {};
}
```
I tested it but I still have the compilation error.

**Comment by ThePhD** [comment]
Well, that should have fixed it, but there were other places where variant was getting tackled. Try to pull the latest and do it now: it should work out okay, I think.

**Comment by damienrg** [comment]
Thank you, it now compiles even without doing:
```c++
namespace sol {
template <>
struct is_automagical<std::variant<Foo>> : std::false_type {};
}
```

**Comment by ThePhD** [comment]
S p i c y 👍
