### ISSUE TITLE
"caught (...) exception" error in yielding function

### ISSUE THREAD

**Issue by firas-assaad** [ThePhD/sol2#906]
I was compiling with `SOL_USING_CXX_LUA` but I noticed that exceptions in C++ called by Lua are reinterpreted by sol. Following the answer in the following issue https://github.com/ThePhD/sol2/issues/869 I turned on `SOL_EXCEPTIONS_ALWAYS_UNSAFE`. It seems to work as expected for most cases, but in the case of a yielding function that calls a lambda I get a "caught (...) exception" whenever the function is called.

Here is the code I'm using (with latest sol, using PUC Lua 5.2):

    #define SOL_EXCEPTIONS_ALWAYS_UNSAFE 1
    #define SOL_USING_CXX_LUA 1
    #define SOL_ALL_SAFETIES_ON 1
    #include <sol.hpp>
    #include <iostream>
    #include <exception>

    int main() {
        try {
            sol::state lua;
            lua.open_libraries(sol::lib::base, sol::lib::coroutine);
            std::cout << "\nSimple test\n";
            auto func = [](int x) {
                std::cout << "C++ - Inside f(" << x << ")\n";
                return x;
            };
            lua["f"] = sol::yielding(
                [&func](int x) { return func(x); }
            );

            sol::string_view code = R"(
                print('Lua - Before coroutine')
                f(5)
                print('Lua - After coroutine')
            )";

            sol::coroutine co = lua.load(code);
            while (co) {
                std::cout << "C++ - Resuming coroutine\n";
                auto result = co();
                if (!result.valid()) {
                    sol::error err = result;
                    throw std::runtime_error(err.what());
                }
                std::cout << "C++ - Coroutine status: " << sol::to_string(co.status()) << "\n";
            }
            std::cout << "C++ - Everything went fine!";
        } catch (std::exception & e) {
            std::cout << e.what() << "\n";
        }
        catch (...) {
            std::cout << "something happened\n";
        }
    }

I get the following output:

    Simple test
    C++ - Resuming coroutine
    Lua - Before coroutine
    C++ - Inside f(5)
    [sol3] An exception occurred: caught (...) exception
    caught (...) exception
    stack traceback:
            [C]: in function 'f'
            [string "..."]:3: in main chunk

If I change the sol::yielding definition to not call another lambda like so:

        lua["f"] = sol::yielding(
            [](int x) {
                std::cout << "C++ - Inside f(" << x << ")\n";
                return x;
            }
        );

Then everything works as expected:

    Simple test
    C++ - Resuming coroutine
    Lua - Before coroutine
    C++ - Inside f(5)
    C++ - Coroutine status: yielded
    C++ - Resuming coroutine
    Lua - After coroutine
    C++ - Coroutine status: ok
    C++ - Everything went fine!

Alternatively, if I don't define `SOL_EXCEPTIONS_ALWAYS_UNSAFE` before including sol then everything works fine, but then I can't catch my original C++ exceptions.

**Comment by ThePhD** [comment]
`lua_yield` is probably throwing it's signal as an exception.

This is probably doing wonders on the functionality here. I have no idea how I'm going to fix this.

**Comment by firas-assaad** [comment]
Any idea why it works for the simpler case (not calling another lambda)? I was able to trace it to the difference between how [stateless](https://github.com/ThePhD/sol2/blob/72181513d5459c4209f567fa4b36228e51709216/include/sol/function_types_stateless.hpp#L44) and [stateful](https://github.com/ThePhD/sol2/blob/72181513d5459c4209f567fa4b36228e51709216/include/sol/function_types_stateful.hpp#L43) functions are called (the `typed_static_trampoline` on the stateless call)

**Comment by ThePhD** [comment]
`lua_yield` jumps by throwing.

BECAUSE OF COURSE IT WOULD <_>

**Comment by ThePhD** [comment]
Well I think I fixed everything. I think.

Try latest, see what explodes.

**Comment by firas-assaad** [comment]
Thanks for looking into it! The non-exceptional sample code above is fixed now.

However, with your newest change it doesn't seem like SOL_EXCEPTIONS_ALWAYS_UNSAFE does what it used to do before. When an exception is thrown from the C++ side Sol rethrows a panic error. Before your latest change, defining SOL_EXCEPTIONS_ALWAYS_UNSAFE allowed me to check if the result is valid and to get the text of my original C++ exception, but now it works the same regardless of the #define

Code:

    #define SOL_EXCEPTIONS_ALWAYS_UNSAFE 1
    #define SOL_USING_CXX_LUA 1
    #define SOL_ALL_SAFETIES_ON 1
    #include <sol.hpp>
    #include <iostream>
    #include <exception>

    int main() {
        try {
            sol::state lua;
            lua.open_libraries(sol::lib::base, sol::lib::coroutine);
            auto func = [](int x) { throw std::runtime_error("runtime error from C++"); return x; };
            lua["f"] = sol::yielding(
                [&func](int x) { return func(x); }
            );

            sol::string_view code = R"(f(5))";

            sol::coroutine co = lua.load(code);
            while (co) {
                auto result = co();
                if (!result.valid()) {
                    sol::error err = result;
                    throw std::runtime_error(err.what());
                }
            }
        } catch (std::exception & e) {
            std::cout << "Exception: " << e.what() << "\n";
        }
        catch (...) {
            std::cout << "Exception: ... happened\n";
        }
    }

Result before your latest commit:

    [sol3] An exception occurred: runtime error from C++
    Exception: runtime error from C++
    stack traceback:
            [C]: in function 'f'
            [string "f(5)"]:1: in main chunk

Result with latest sol.hpp:

    [sol3] An error occurred and panic has been invoked: stack index 1, expected string, received number
    Exception: lua: error: stack index 1, expected string, received number

**Comment by firas-assaad** [comment]
I found another situation where "caught (...) exception" happens (only when SOL_EXCEPTIONS_ALWAYS_UNSAFE  is set):

    #define SOL_EXCEPTIONS_ALWAYS_UNSAFE 1
    #define SOL_USING_CXX_LUA 1
    #define SOL_ALL_SAFETIES_ON 1
    #include <sol.hpp>
    #include <iostream>
    #include <exception>

    class A {};

    int main() {
        try {
            sol::state lua;
            lua.open_libraries(sol::lib::base, sol::lib::coroutine);

            auto type = lua.new_usertype<A>("A");
            type["f"] = sol::yielding(
                [](A& cmd) {
                    std::cout << "in A::f()\n";
                }
            );

            sol::string_view code = R"(
                a = A.new()
                a:f()
            )";

            sol::coroutine co = lua.load(code);
            while (co) {
                auto result = co();
                if (!result.valid()) {
                    sol::error err = result;
                    throw std::runtime_error(err.what());
                }
            }
            std::cout << "C++ - Everything went fine!";
        } catch (std::exception & e) {
            std::cout << "Exception: " << e.what() << "\n";
        }
        catch (...) {
            std::cout << "Exception: ... happened\n";
        }
    }

Output with SOL_EXCEPTIONS_ALWAYS_UNSAFE set:

    in A::f()
    [sol3] An exception occurred: caught (...) exception
    Exception: caught (...) exception
    stack traceback:
            [C]: in function 'f'
            [string "..."]:3: in main chunk

Output without SOL_EXCEPTIONS_ALWAYS_UNSAFE:

    in A::f()
    C++ - Everything went fine!

**Comment by firas-assaad** [comment]
Could this be reopened, or should I create a new issue for the other cases I found?

**Comment by ThePhD** [comment]
I still remember this, don't worry. I'm just busy. But sure, I'll reopen.

**Comment by ThePhD** [comment]
Alright, attempt #2. Give it a go if you get the time.

**Comment by firas-assaad** [comment]
It works perfectly! Thanks a lot :D

I will let you know if I find anything else.
