### ISSUE TITLE
wstring / unicode support?

### ISSUE THREAD

**Issue by JoshKlint** [ThePhD/sol2#907]
This isn't really the responsibility of sol2 to handle, but I was wondering if you had any thoughts on handling unicode / wstring (long explanation why UTF-8 is the future even though only 95% of programmers don't understand it but are too embarrassed to admit it) in Lua?

We have some GUI widget scripts that do a lot of text handling and I am wondering what to do here. Maybe we should just bind a wstring as a class in Lua and skip Lua strings entirely?

**Comment by ThePhD** [comment]
Every `std::wstring` is assumed UTF16 or UTF32 and serialized into Lua as UTF8 when pushed through sol2. `std::string` is assumed UTF8, and pushed in directly. (This is obviously wrong, if the `std::string` came from the platform or system, where it very well may not be that.)

Beyond that, you're welcome to write some converters to handle it. Someone did this before using the old way (https://github.com/ThePhD/sol2/issues/140#issuecomment-237934947), but you can rewrite it in the new way: https://sol2.readthedocs.io/en/latest/tutorial/customization.html
