### ISSUE TITLE
Lua libraries when compiling as C++

### ISSUE THREAD

**Issue by epsilon-phase** [ThePhD/sol2#911]
Hi, this is admittedly a bit tangential to your project but for the life of me, I can't find anything else about this. 

I would like to use lpeg, but compiling lua as c causes uh, interesting memory handling issues due to improper destructor handling. If I compile lua as c++, then it is no longer possible to load lpeg.

**Comment by ThePhD** [comment]
Chances are, LPEG is loaded as a C library. That means it reaches out looking for a DLL that can load LPEG.

I've never used LPEG despite hearing a ton about it: do you know how they hook into Lua? It's just a `require` statement and a DLL in your application with a C function like `load_lpeg` or something?

**Comment by epsilon-phase** [comment]
Yeah, I was trying to use load_library to load it, but it fails even when compiled as c++
Even trying to load pointing it at the mangled symbols fails

**Comment by ThePhD** [comment]
I can't figure out how to make anything change here, for my tests.

If you need additional help, reopen this with maybe a bit of a small repo to illustrate the problem, because I can't construct an example I can fix...!
