### ISSUE TITLE
setting a table in global

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#912]
Help desk!

how do I do something like this:

		sol::table mytable = ThisFunctionRetunsASolTable();		
		state.globals().set("Some_table_name", mytable );

I want to set a sol table on a sol table.

I also tried: 
                `state["Some_table_name] = mytable;`

Btw the table "Some_table_name" is allready a part of globals, but I want to replace it, does that make any difference?

**Comment by ThePhD** [comment]
Have you tried just.... running exactly `state["Some_table_name"] = mytable;`, in a program?

**Comment by xzores** [comment]
yep, this does not work.
```
sol::table o2 = TypeRegister::covertToSol(state, TT);
state["_ENV"] = o2;
```

but weirdly this work (but it is not what i want to do):
```
sol::table o2 = TypeRegister::covertToSol(state, TT);
state["_ENV"]["Some_table"]  = o2;
```

this also works
```
sol::table o2 = TypeRegister::covertToSol(state, TT);
state["Some_table_that_does_not_exists"]  = o2;
```

**Comment by xzores** [comment]
After some testing it seems to not work, when the table is called "_ENV" correct?

**Comment by xzores** [comment]
nope renaming _ENV does not help, I think the problem is that I created a sol::environment

```
safeEnviroment = sol::environment(state, sol::create, state.globals());
state.globals()["_ENV"] = safeEnviroment;
safeEnviroment.set("_G", safeEnviroment);
safeEnviroment.set("_ENV", safeEnviroment);
```

Is there a difference between a normal table and an environment?
and is it even possible to replace the environment table with a normal table? or is a deep copy the way forward?

**Comment by ThePhD** [comment]
Writing into the `_ENV` variable and the `_G` variable is not a workable solution. These are shortcut variables defined when you open `sol::lib::base` / the [Basic Library (§6.1)](https://www.lua.org/manual/5.3/manual.html#6.1). Specifically, "changing its value does **not affect any environment, nor vice versa**" (emphasis mine).

If you want to change the environment for a script, literally use the new environment created with the script calls. Then, when you need variables, do `my_environment["foo"];` to get and similar syntax to set.
