### ISSUE TITLE
vs2019 and SOL_NO_EXCEPTIONS build failure

### ISSUE THREAD

**Issue by yamashi** [ThePhD/sol2#913]
Hello,

When building sol with SOL_NO_EXCEPTIONS set on visual studio 2019, line 13314 of sol.hpp 
`lua_pushnumber(L, static_cast<lua_Number>(std::forward<Args>(args)...));`
generates an error, commenting it out fixes the problem, I am not sure if this line is important that's why this isn't a PR.

Best,
Max

**Comment by ThePhD** [comment]
Fixed now.
