### ISSUE TITLE
VS2019 warning spam when binding a lambda in a file while using namespace std

### ISSUE THREAD

**Issue by npiegdon** [ThePhD/sol2#914]
sol: **3.0.3** and/or **3.2.0**
Visual Studio 2019: latest (**16.4.2**) building with either /std:c++17 or /std:c++latest, with or without /permissive-

Minimal repro:
```c++
#include "sol.hpp"

int main()
{
  sol::state lua;
  lua["f"] = []{};
}

#include <string>
using namespace std;
```

This generates [245 lines of warnings](https://github.com/ThePhD/sol2/files/4001745/solWarnings.txt).  (Line numbers there are for sol 3.2.0).  Despite the warnings, it compiles and runs just fine (even with more interesting captures, etc.)

The critical lines are the last two.  Without `using namespace std` there are no warnings.  Regardless of their position in the file (after all uses of sol, etc.) the warnings are still generated.

It does seem to depend on `<string>` being included.  Changing the include to `<vector>` will also eliminate the warnings.  The using statement must be at the global scope.  Placing it inside a function or namespace scope also eliminates the warnings.

Other function bindings like the following work without any warnings (even with `using namespace std`):
```c++
  lua["f2"] = &SomeStaticFunction;
  lua["f3"] = &MyClass::SomeMemberFunction;
```

... I suppose the advice is probably "don't write `using namespace std`". :wink:

**Comment by ThePhD** [comment]
Yeah I don't really know what to do about this. MSVC has a number of other really crazy bugs related to name lookup that other people have already filed with the compiler team related to lookup of function calls and conversions. This is likely related to it. I'm not really interested in making a minimal repro and sending it to MSVC, though; it's a lot of effort to get a minimal repro and fix something like this.

In either way, there's nothing I can do to help you here. Sorry!
