### ISSUE TITLE
FYI: Keil Armcc v5 compiler doesn't support C++17

### ISSUE THREAD

**Issue by RussellHaley** [ThePhD/sol2#915]
Hi, 

Just an FYI: I was looking into building sol2 into a project that uses an older keil toolchain. I have discovered that the Arm armcc compiler (v5) only supports C++ 11. The newer armclang compiler only supports C++17 through community extensions.

Armcc compiler options: http://www.keil.com/support/man/docs/armcc/armcc_chr1406800556948.htm

There is claim of C++17 "Community" support for the newer armclang compilers but I have no way of testing that:
https://developer.arm.com/docs/100748/latest/using-common-compiler-options/selecting-source-language-options

Keil support level definitions indicate that "community" features are non-optimized features included in the base LLVM packages. https://developer.arm.com/docs/100748/latest/supporting-reference-information/support-level-definitions#pge1444224923692

Cheers,
Russ

**Comment by ThePhD** [comment]
You'll either have to use an older version of sol2 or ask them to speed up their efforts; sorry, I can't spend too much time backporting everything with the amount of things I have on my plate to do!

**Comment by RussellHaley** [comment]
Hi, this wasn't a request. I was just letting you know in case someone else bumps into it. Cheers.
