### ISSUE TITLE
Error message shown in debug mode but crashes in release mode

### ISSUE THREAD

**Issue by mahnamizjaf** [ThePhD/sol2#916]
In a previous post i've asked about catching syntax errors in a previous post :
[https://github.com/ThePhD/sol2/issues/910#issuecomment-567110399](url)

the project I'm working on is running on VS2019 and has  SOL_ALL_SAFETIES_ON defined and in which I've used it in such a manner:

C++ side
 ```
struct myClass 
{
  int haha;
    myClass()
      :haha{0}{};
}
void Raycast(/*some vars*/)
{  /* some code*/   }
int main()
{
    sol::state mLua;
    mLua.open_libraries(sol::lib::base, sol::lib::package, 
					 sol::lib::string, sol::lib::os, 
					 sol::lib::math, sol::lib::table, 
					 sol::lib::io);

    sol::environment& env =sol::environment{ mLua, sol::create, mLua.globals() };
    mLua.script_file("someLua.lua",env);
     mLua["Physics"]= mLua.create_table_with("Raycast", &Raycast);
try{
    sol::protected_function_result res  = env["update"]();
    if (!res.valid() )
    {
		sol::error err = res;
		std::cout << err.what() << std::endl;
    }
}
catch(sol::error& err)
   { std::cout << err.what() << std::endl;}
}
```
lua side:
```
function update()
    Physics.Raycast()
end
```

now the issue is that at the moment I'm getting the error messages in debug mode saying somewhat like this:
"failed to run:assets/scripts/test.lua:11: stack index 1, expected userdata, received no value: value is not a valid userdata (bad argument into 'SHE::LuaBinding::RayCastHit(const structSHE::Math::Vector3&, const structSHE::Math::Vector3&, const float&, const structSHE::LuaBinding::collisionMask&)')
stack traceback:
        [C]: in field 'Raycast'
        assets/scripts/test.lua:11: in function <assets/scripts/test.lua:10>"

which is what i wanted.

However when i build it in release mode this exception was thrown:
![Capture](https://user-images.githubusercontent.com/48344251/71959564-fdba8d00-322d-11ea-9408-5da6bd83c7f3.PNG)

which is really weird and has been bugging me for a while.

**Comment by ThePhD** [comment]
This was a misconfiguration on my part that applied exclusively to using the function call operator on the proxy returned from `lua["whatever"]`, as you did here.

Pull from latest, it's fixed.

**Comment by mahnamizjaf** [comment]
hey dev, I'm still getting the same issues with the current pull, i'm using sol v3.2.0 (revision 43f215c)
