### ISSUE TITLE
environment and readonly properties

### ISSUE THREAD

**Issue by yamashi** [ThePhD/sol2#918]
Hello,

I want to associate constant data to each sol::environment I create. I initially tried to use 
`env["database"] = somedatabase;` 
but as it turns out the Lua script can change 'database' to something else, what would be the proper way to associate immutable data to an environment ? 
Also when a function is called from Lua, in C++ using sol::this_environment is there a way to add data to the environment so that I don't have to use a dirty map<sol::environment, data> or set a context before calling a function ?

Best,
Max

**Comment by OrfeasZ** [comment]
`sol::environment` is just a good-old table, so you can just modify its metatable and make the `__index` / `__newindex` metamethods filter accesses to it. Keep in mind, that depending on how you do this, you might break the normal accessors. See [here](https://sol2.readthedocs.io/en/latest/api/readonly.html#id1) for an example.

As for your second question, I'm not sure I understand what you're trying to do. Are you trying to bind user data to your environment so you can arbitrarily access it at any point?

**Comment by yamashi** [comment]
So I decided to not use the environments in the end this way I can use the lua registry instead and store context variables there and retrieve them from functions, this way scripts can only edit the values using the debug functions that I disabled to prevent that from ever happening.
