### ISSUE TITLE
Question: How to interact with the io library?

### ISSUE THREAD

**Issue by hmenke** [ThePhD/sol2#921]
I would like to open a file in Lua using `io.open` and then pass the file handle to C++ so that I can write to the already opened file from there.

As a simple example I just pass `io.stdout` as a field in a table to a C function and compare whether the enclosed `FILE *` is the same as `stdout`.

With the Lua C API I would write the following code (lots of error checking omitted):
```cpp
#include <lua.hpp>
#include <cstdio>

int test(lua_State *L) {
    lua_getfield(L, 1, "file");
    luaL_Stream *p = (luaL_Stream *) luaL_checkudata(L, -1, LUA_FILEHANDLE);
    lua_pushboolean(L, p->f == stdout);
    return 1;
}

int main() {
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    lua_pushcfunction(L, &test);
    lua_setglobal(L, "test");
    luaL_dostring(L, "print(test{ file = io.stdout })");
    lua_close(L);
}
```
With sol2 I naively assumed that I could to sort of the same thing but that does not work and throws an error at runtime.
```cpp
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>
#include <cstdio>

bool test(sol::table t) {
    luaL_Stream *p = t["file"];
    return p->f == stdout;
}

int main() {
    sol::state L;
    L.open_libraries();
    L["test"] = &test;
    L.script("print(test{ file = io.stdout })");
}
```
What is the correct way to interface with file handle from the `io` library?

(Unfortunately I can't use sol2 v3 because of C++17).

**Comment by ThePhD** [comment]
Unfortunate that you can't use v3.

You'll have to patch support in for luaL_Stream* yourself by writing a checker, getter, and pusher. The online docs are for sol3: use the docs and examples at the sol2 v2.20.x branch you are on to see an example of writing a pusher and checker.

Good luck!

**Comment by hmenke** [comment]
Thank you for your guidance!  Here is what I have come up with so far.  Comments are more than welcome!
```cpp
#include <cstdio> // stdout
#define SOL_CHECK_ARGUMENTS 1
#include <sol.hpp>

namespace sol {

template <>
struct lua_size<luaL_Stream *> : std::integral_constant<int, 1> {};

template <>
struct lua_type_of<luaL_Stream *>
    : std::integral_constant<sol::type, sol::type::poly> {};

namespace stack {

template <>
struct checker<luaL_Stream *> {
    template <typename Handler>
    static bool check(lua_State *L, int index, Handler &&handler,
                      record &tracking) {
        int absolute_index = lua_absindex(L, index);
        void *p = luaL_testudata(L, absolute_index, LUA_FILEHANDLE);
        bool success = (p != nullptr);
        tracking.use(1);
        return success;
    }
};

template <>
struct getter<luaL_Stream *> {
    static luaL_Stream *get(lua_State *L, int index, record &tracking) {
        int absolute_index = lua_absindex(L, index);
        void *p = lua_touserdata(L, absolute_index);
        tracking.use(1);
        return static_cast<luaL_Stream *>(p);
    }
};

template <>
struct pusher<luaL_Stream *> {
    static int push(lua_State *L, luaL_Stream *file) {
        luaL_Stream *p = (luaL_Stream *)lua_newuserdata(L, sizeof(*p));
        p->f = file->f;
        p->closef = file->closef;
        luaL_setmetatable(L, LUA_FILEHANDLE);
        return 1;
    }
};

} // namespace stack

} // namespace sol

bool test(sol::table t) {
    luaL_Stream *p = t["file"];
    return p->f == stdout;
}

int main() {
    sol::state L;
    L.open_libraries();
    L["test"] = &test;
    L.script("print(test{ file = io.stdout });");
}
```

**Comment by ThePhD** [comment]
`sol::type::poly` is probably not right: it should be `sol::type::userdata` (because it is a userdata).

Other than that, spot-on!

**Comment by hmenke** [comment]
Thanks, I corrected my previous comment in case someone else comes across this and just wants to copy-paste the code.  I probably should wrap the `luaL_Stream` into something derived from `std::streambuf` so that it can interoperate with C++ streams, but for now it's sufficient. Thanks again for your help and for your work on sol2!
