### ISSUE TITLE
Docs repeated example

### ISSUE THREAD

**Issue by alexdevteam** [ThePhD/sol2#922]
At https://sol2.readthedocs.io/en/latest/tutorial/ownership.html#pointer-lifetime-smart-ptr:
![image](https://user-images.githubusercontent.com/16354904/73134301-59aa5180-4035-11ea-808b-920c19d963c3.png)
The first example is meant to represent bad usage of raw pointers.

![image](https://user-images.githubusercontent.com/16354904/73134317-7181d580-4035-11ea-8e62-1fc15b2975f1.png)
The second example is meant to represent usage of unique_ptr or shared_ptrs, but is just the same code example.

**Comment by ThePhD** [comment]
Yep, that's a derp. I'll fix it eventually.

**Comment by ThePhD** [comment]
Should be better now.
