### ISSUE TITLE
Multiple coroutines problem

### ISSUE THREAD

**Issue by alexdevteam** [ThePhD/sol2#927]
```cpp
#include <sol/sol.hpp>

int main() {
    sol::state s{};
    s.open_libraries(sol::lib::base);
    s.open_libraries(sol::lib::coroutine);
    sol::table table = s.script_file("../script.lua");
    std::array<sol::coroutine, 2> stuff{ table["some_func"], table["some_func2"] };
    for (auto& each : stuff) {
        each();
        assert(each.status() == sol::call_status::yielded);
    }
    return 0;
}
```
```lua
local something = {}

function something.some_func(self)
    print("some_func")
    coroutine.yield()
end

function something.some_func2(self)
    print("some_func2")
    coroutine.yield()
end

return something
```
Creating multiple coroutines in a state causes a lot of problems. In this particular example, this is returned:
```cpp
some_func
Tests: /home/alex/Desktop/Projects/Tests/main.cpp:13: int main(): Assertion `each.status() == sol::call_status::yielded' failed.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
And without the assert, you can see that some_func2 isn't even called:
```cpp
some_func

Process finished with exit code 0
```

**Comment by ThePhD** [comment]
You are executing the coroutine on the same stack as the other coroutine. Coroutines require a separate execution space (provided by `sol::thread`) to get work done without clobbering other coroutines or functions and any leftover state on the execution space (e.g., the Lua stack).

Create a `sol::thread` and run the coroutine from that thread, as shown in this example: https://sol2.readthedocs.io/en/latest/api/coroutine.html#yield-main-thread
