### ISSUE TITLE
using LuaJIT will not compile without error

### ISSUE THREAD

**Issue by JorySchossau** [ThePhD/sol2#928]
MRE: The first 'sneak peek' demo snippet on the github landing page:
```cpp
#include <sol/sol.hpp>
#include <cassert>

int main() {
    sol::state lua;
    int x = 0;
    lua.set_function("beep", [&x]{ ++x; });
    lua.script("beep()");
    assert(x == 1);
}
```

Using latest Sol2 and LuaJIT:
```sh
$ clang++ -std=c++17 -I./LuaJIT-2.0.5/src -I./single/include -L./LuaJIT-2.0.5/src -o sample sample.cpp -lluajit
./single/include/sol/sol.hpp:13432:13: error: no member named 'closef' in 'luaL_Stream'
```
The Sol source has a comment on this:
```cpp
/* In PUC-Rio 5.1, userdata is a simple FILE*
* In LuaJIT, it's a struct where the first member is a FILE*
* We can't support the `closef` member
*/
```

Environment:
os: solus linux
compiler: clang 9.0.0

@OrfeasZ on discord observed some of the CI builds failing for the same reason, and suggests the following commit as the culprit: https://github.com/ThePhD/sol2/commit/0c38fd1a579175d74992ce753b0e29a715d21eb6

**Comment by ThePhD** [comment]
Fixed, just like #931.
