### ISSUE TITLE
Lua call c++ functions with arguments as table

### ISSUE THREAD

**Issue by clclon** [ThePhD/sol2#929]
If it does not bother you, please show an example of how to call c ++ functions with arguments in the form of a table from Lua. Table example:

```
t = {
    ws = 25,
    hs = 45,
    arr = { 11,12,13,14,15,16,17 }
}
call_c_function(t)
```
C++ structure:

```
struct t
{
   int32_t ws, hs;
   std::vector<uint8_t> arr;
};

void call_c_function(sol::???<t> a) {}

```
I'm look `containers_as_table.cpp`, `sol::as_table_t` not working for me..

**Comment by OrfeasZ** [comment]
You can accept `sol::table` as an argument. See https://sol2.readthedocs.io/en/latest/api/table.html.

**Comment by ThePhD** [comment]
What @OrfeasZ said. Also, you are trying to map a structure to a table, and vice-versa: that requires a customization point. Which has an example. Specifically, this work: https://github.com/ThePhD/sol2/blob/develop/examples/customization/source/lua_zm_interop.cpp

As part of this example: https://github.com/ThePhD/sol2/tree/develop/examples/customization
