### ISSUE TITLE
Adding script defined variables and binding them to C++ objects

### ISSUE THREAD

**Issue by penumbra23** [ThePhD/sol2#932]
Hello everyone!
First things first, love this repo ❤️ 

I'm trying to make a general purpose game engine with Lua scripting using Sol2. The engine uses 
a component system and scripts are attached onto objects. Most engines have the concept of script data, without hard-coding object properties in the engine, but defining it through the scripts.

Example:

script.lua
```
hp = 100

function attack()
  hp = hp - 5;
end

function update()
   ....
   ....
end
```

In my C++ code:
```
for(auto obj = objects.begin(); obj < object.end(); ++obj)
{
    obj->getScript().execute("update");
    if (obj->getType() == "Monster")
        obj->getScript().execute("attack");
}
```

Every object that has this script attached, should have it's separate memory space with it's own `hp` variable. When executing methods (i.e. `attack()`) it should bind to only that object and execute "his" attack method.

I've tried to add a global variable `this` to reference the object in C++ code and on every iteration set `lua["this"] = obj;` but adding variables like `this.hp = 100` throws the `unimplemented new_index` error. 

Is there some way to implement this behavior without hard-coding variables inside C++ classes?

**Comment by ThePhD** [comment]
Each script can be sandboxed using a `sol::environment`, while still maintaining a single `sol::state`. What you need to do is change how your "execute" is handled.

```
class Script {
private:
     sol::environment code_env;

public:
     Script(sol::state& lua, std::string script_code) : env(lua) {
          lua.script(script_code, code_env);
     }

     void execute(std::string_view target_name) {
          sol::protected_function target_execution = code_env
     }

     sol::environment& environment () {
          return code_env;
     }

     const sol::environment& environment () const {
          return code_env;
     }
};
```

Now, when you need access to variables set on the script, you do `int hp = obj->getScript().environment()["hp"];`. This is a very, VERY long spelling so you could probably introduce some shortcut functions or operators or w/e you want.

Good luck.
