### ISSUE TITLE
Docs for automatic metafunction pairs does not mention value_type

### ISSUE THREAD

**Issue by cschreib** [ThePhD/sol2#934]
The documentation for usertype automatic metafunction ``pairs`` ([here](https://sol2.readthedocs.io/en/latest/api/usertype.html#usertype-automatic-automagic-meta-functions)) mentions the need for ``begin()`` and ``end()`` functions on the type, but not the ``value_type`` trait. Without it, the ``pairs`` function does not work (is nil) and no useful error message is given as to why (beside "is not recognized as a container"). 

However the need for ``value_type`` is clearly stated in the code, and it is also mentioned elsewhere in the documentation, on the ``containers`` page ([here](https://sol2.readthedocs.io/en/latest/containers.html#container-overriding)).

**Comment by ThePhD** [comment]
Added.

**Comment by cschreib** [comment]
Thank you for your responsiveness!
