### ISSUE TITLE
error C2039: 'function_pointer_type': is not a member of 'sol::lua_bind_traits<sol::basic_reference<false>>' on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [ThePhD/sol2#935]
Hi,

Recently, we added the sol2 project to the RWC test suit to detect the MSVC compiler regression and found the following errors. could you help look at this? Thank you. Note, the next release MSVC will trigger this error.

**Repro steps:**

1. git clone https://github.com/ThePhD/sol2.git f:\sol2\src
2. mkdir f:\sol2\build_x86 && pushd f:\sol2\build_x86
3. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DSOL2_LUA_VERSION=5.1.5 -DSOL2_PLATFORM=x86 -DSOL2_CI=ON -DSOL2_BUILD_LUA=ON -DBUILD_LUA_AS_DLL=ON -DSOL2_TESTS=ON -DSOL2_EXAMPLES=ON -DSOL2_TESTS_EXAMPLES=ON f:\sol2\src
4. cmake --build . --config Release  --verbose -- /maxcpucount

Build.log:[build_x86.log](https://github.com/ThePhD/sol2/files/4218581/build_x86.log)

**Error:**
coroutine.i
F:\sol2\src\include\sol\call.hpp(350): error C2039: 'function_pointer_type': is not a member of 'sol::lua_bind_traits<sol::basic_reference<false>>'
F:\sol2\src\include\sol\wrapper.hpp(38): note: see declaration of 'sol::lua_bind_traits<sol::basic_reference<false>>'
F:\sol2\src\include\sol\call.hpp(459): note: see reference to function template instantiation 'int sol::call_detail::agnostic_lua_call_wrapper<F,true,true,true,0,true,void>::call<sol::reference&,>(lua_State *,Fx)' being compiled
        with
        [
            F=uFx,
            Fx=sol::reference &
        ]

**Comment by ThePhD** [comment]
Re-run the file compiling just the `as_returns.cpp` file: there's at least 5 different error streams interspersed here and it's making it a lot harder to get to the source of the problem.

**Comment by mrdooz** [comment]
It looks like that with the latest MSVC2019 preview, there is some case of `fx_traits` that isn't being caught by the template specialization, so the `struct fx_traits : basic_traits<false, false, void, void>` struct is being used (which is causing the compile error, as this case has no `function_pointer_type`).

**Comment by ThePhD** [comment]
Looks like this should be fixed up now.

**Comment by ThePhD** [comment]
Fixed.

**Comment by helmesjo** [comment]
Which release will this be part of? @ThePhD

**Comment by ThePhD** [comment]
The next one, which isn't out yet. So jsut grab from the latest instead.

**Comment by helmesjo** [comment]
Haha well true... What my question implied was more: Any planned release date? :) 
We're using the conan package, so depend on official releases.

**Comment by ThePhD** [comment]
Hopefully sometime before mid June. There's a lot of features I want to add before the next date, and some binary size / runtime memory optimizations, too.

**Comment by ThePhD** [comment]
To be clear: waiting that long is pretty bunk, but sol2 is a header-only library. You can grab the single-file headers from this location and just copy-paste them over and that's it, that's the magic: https://github.com/ThePhD/sol2/tree/develop/single

**Comment by helmesjo** [comment]
Yes of course, but unfortunately it doesn't work if it's a conan package (besides locally when testing). The CI builds will still fail.
