### ISSUE TITLE
meta_function enum not doing what it's supposed to do?

### ISSUE THREAD

**Issue by imi-tat0r** [ThePhD/sol2#936]
First of all, eventhough I've spent hours on your documentation already (great job on that btw), I am quite new to Lua in general and I don't know if what I did is anything useful, but I tried.
In case it has something to do with all this, I am using Sol with LuaJIT.

So in the docs you have the `meta_function` enum which, from my understanding, is used as an easier way of doing stuff like `metatable["__index"]`.
However I found that at least one of them, `sol::meta_function::metatable` to be specific, either doesn't work as it's supposed to or I misunderstood the documentation quite a bit.

What I tried to do was, hiding/protecting my metatable from unwanted changes:

```
// index will be called for every access as the rest of the metatable is empty
env_metatable[sol::meta_function::index] = [env_origtable](sol::table _tbl, std::string key)
{
	return env_origtable[key];
};

// block write access
env_metatable[sol::meta_function::new_index] = &access_violation; // this is just a one line wrapper of luaL_error()

// block getmetatable()
env_metatable[sol::meta_function::metatable] = false;

// apply metatable
env_protected[sol::metatable_key] = env_metatable;
```

At this point I have a table called "input_handler" with a function called "is_key_pressed" and now run the following script:
```
print(input_handler.is_key_pressed(0x12)) -- VK_MENU (ALT key)
print(getmetatable(input_handler))
```

The output I expected (while pressing the ALT key) was
```
true
false
```
because according to the Lua Docs (http://lua-users.org/wiki/MetatableEvents)
`__metatable - Hide the metatable. When "getmetatable( myTable )" is called, if the metatable for myTable has a __metatable key, the value of that key is returned instead of the actual metatable. `

however the output I got was this:
```
true
table: 0x00f550d0
```

After god knows how many hours, for some reason I tried it like this:
```
// index will be called for every access as the rest of the metatable is empty
env_metatable["__index"] = [env_origtable](sol::table _tbl, std::string key)
{
	return env_origtable[key];
};

// block write access
env_metatable["__newindex"] = &access_violation; // this is just a one line wrapper of luaL_error()

// block getmetatable()
env_metatable["__metatable"] = false;

// apply metatable
env_protected[sol::metatable_key] = env_metatable;
```
and got the wanted output
```
true
false
```
Is this intended behavior and I completely misunderstood something or is this acutally a bug that almost cost me sanity.

**Comment by ThePhD** [comment]
Huh. I'm not sure why I defined the name of `sol::meta_function::metatable` to be `__mt` instead of `__metatable`.

Lemme go do some digging.

**Comment by ThePhD** [comment]
Alright, so there's some old crufty garbage that relies on `__mt` rather than `__metatable`, and I think it changes between versions. I need to do some more double-checking, but since I might not care about that old, crufty garbage I'll probably swap to always using `__metatable`.

**Comment by ThePhD** [comment]
Fixed.
