### ISSUE TITLE
object as std::string for to_string-able usertypes

### ISSUE THREAD

**Issue by valkarion** [ThePhD/sol2#937]
Hi. 

I have some classes that use the automagic to_string construction. Everything works perfectly on the Lua side but when I want to have the same behaviour on the C++ side in a generic version via sol::object the obj.as\<std::string\>() outputs nothing, here's a small example: 

	#include "sol.hpp"
	#include <iostream>

	class Alma {
	public:
	};

	std::ostream& operator<<( std::ostream& os, const Alma& thing ) {
		std::string res = "Alma";
		os << res;
		return os;
	}

	void CPrint( sol::object obj ) {
		std::cout << obj.as<std::string>();	
	}

	int main() {
		sol::state L;
		L.open_libraries( sol::lib::base );

		L.new_usertype<Alma>( "Alma" );
		L["CPrint"] = CPrint;

		L.script( R"(
			local a = Alma:new()
			print(a)	-- prints "Alma"
			CPrint(a)	-- prints nothing
		)" );

		std::cin.get();
		return 0;
	}

So my question is: is it possible to access the conversions via the object itself in some manner, or I'll have to convert the sol::object into the class?

**Comment by ThePhD** [comment]
You need to do `lua["to_string"](the_object);`. There is magic that `to_string` does in the Lua standard library to the conversions. Calling `as` for a `sol::object` does not do that magic: it does a strict conversion, subject to a few caveats listed in the documentation:

https://sol2.readthedocs.io/en/latest/safety.html
Search for `SOL_STRINGS_ARE_NUMBERS`.
