### ISSUE TITLE
Partitioning a container of a user defined type based on different properties of the type, using Lua

### ISSUE THREAD

**Issue by amirmasoudabdol** [ThePhD/sol2#938]
This is more of a followup to a question that I've asked on [Cpplang Slack](https://cpplang.slack.com/archives/C21PKDHSL/p1582199565241000) and [Stackoverflow](https://stackoverflow.com/questions/60512792/comparing-different-properties-of-a-class-in-a-stdvector-of-a-class). I think I've a good idea and prototype for what I want to achieve but I thought maybe I ask it here too before I start the implementation, in case that I'm missing something.

Basically, imagine I've a class like 

```cpp
class data_ {

public:
    int n {0};
    double a {0};
    double b {0};
    double c {0};

    bool is_blue {false};
    
    data() = default;
};
```

and I would like to let the user write some queries on the properties of the class, then, I transfer those logics to my code and check all the items in a container like `std::vector<data_>` and report the indices of the matching items. For instance, user might provide a string like `a > 5.0`, `c < 3`, `min(b)`, `is_blue == true`. 

I know now that I can do all of this with `std::partition` and basically different way of sorting my container. However, since I don't know what my input would be, I need to generate those comparison functions on the fly. For this, I thought, ok, I'm going to have a few string template, and use `sol`, and Lua to generate those on the runtime based on users input. So, for instance,

```cpp
std::string tmp_min_script = R"(
    function min_f (l, r)
        return l.{} < r.{}
    end
)";

std::string tmp_comp_script = R"(
    function comp_f (d)
        return d.{}
    end
)";

std::string min_f_string = fmt::format(tmp_min_script, "a", "a");
std::string comp_f_string = fmt::format(tmp_comp_script, "c < .5");

lua.script(min_f_string);
lua.script(comp_f_string);

lua.new_usertype<data_>( "data_",
                          "n", &data_::n,
                          "a", &data_::a,
                          "b", &data_::b,
                          "c", &data_::c
);

auto min_it = std::min_element(vdata.begin(), vdata.end(),
                                 [&lua](const data_& l, const data_& r) { return lua["min_f"](l, r); });

auto pivot = std::partition(vdata.begin(), vdata.end(),
                           [&lua](const data_& d) { return lua["comp_f"](d); });
```

I know this works, and it's quite scalable for my use case where I'd not have a lot of those logics. But, I was wondering if I'm missing something about sol and Lua interaction that might break this or inefficient or even wrong. I don't even know if this is a valid use case of Lua or sol, so, I'd really appreciate it if you can take a quick look and let me know if I'm heading into a dark abyss with this or not :D

Thanks in advance,
A.

**Comment by ThePhD** [comment]
When you do `lua["comp_f"]`, you perform a lookup to retrieve that function. You can save on speed by doing `sol::function f = lua["comp_f"];` if you know it's there and don't need all the song and dance of a look up PER call.

This also reminds me I need to implement `function_of` at some point... but that's not related tot his.

Good luck!
