### ISSUE TITLE
A way to distinguish & iterate over an array-table?

### ISSUE THREAD

**Issue by Velocity-** [ThePhD/sol2#939]
So, first of all: Sol is awesome. Amazing job.

I'm trying to write a little JSON serializer and have to distinguish between a 'dictionary-like' table and an array. I looked [at this reference](https://github.com/rxi/json.lua/blob/master/json.lua) but I'd like to do it using native Sol APIs. The `obj.is<vector<sol::object>>`-esque stuff does not seem to work for this case. What approach should I use?

```cpp
json encodeValue(const sol::object& val) {
    if (val.is<sol::string_view>()) {
        return val.as<sol::string_view>();
    } else if (val.is<int>()) {
        return val.as<int>();
    } else if (/* magical way to decide it's an array */) {
        auto arr = json::array();
        // fill arr with elements...
        return arr;
    } else if (val.is<sol::table>()) {
        return encodeTable(val.as<sol::table>());
    }

    return nullptr;
}

json encodeTable(const sol::table& table) {
    json out;

    for (auto& e : table) {
        auto key = e.first;
        auto encoded = encodeValue(e.second);

        if (key.is<sol::string_view>()) {
            out[key.as<sol::string_view>().data()] = encoded;
        } else if (key.is<int>()) {
            out[key.as<int>()] = encoded;
        }
    }

    return out;
}
```

**Comment by OrfeasZ** [comment]
Lua itself does not distinguish between "arrays" and "dictionaries". They are all tables. As such, there is no easy way to distinguish between them. Most approaches I've seen simply check if the keys start with "1" and are sequential with no gaps and if so they assume it's an array and otherwise they treat it as a dictionary.

**Comment by ThePhD** [comment]
It's as @OrfeasZ says: Lua has no way to accurately determine whether something is an array vs. a table without a potentially expensive check.

Them's just the breaks; sorry. A lot of requests for array functionality have been lobbied at Lua developers but they feel it is not worth the add. Not much I can do without actually forking the Lua language itself.
