### ISSUE TITLE
Safety: Different Levels, Different Defaults

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/sol2#94]
It's become clear from a number of bug reports like #92 and other previous ones that users desire the need to have safety in place by default. However, Sol takes an all-or-nothing approach to safety: you get it all with `#define SOL_CHECK_ARGUMENTS` or none at all, since `SOL_CHECK_ARGUMENTS` hard-cleanses the bottom-most level of the API.

There should be some extra defines:

- [x] `#define SOL_SAFE_USERTYPE` check if the first argument to a usertype function is a nullptr. Put this one on by default when we detect the compiler has its debug flags set `_DEBUG` for VC++, and lack of `NDEBUG` for g++/clang++

... Actually, that's the only other necessary safety bit I can think of. SOL_CHECK_ARGUMENTS affects all function calls by affecting all getters...

**Comment by nabijaczleweli** [comment]
Use `- [ ]` instead of `[ ] -` for fancy checkboxes

**Comment by Nava2** [comment]
Since the issue keeps coming up, what about turning on/checks by default using NDEBUG (what assert.h uses).

Since a lot of the issues are asked regarding new developers, it'd be convenient to have it on in debug builds by default and optimized away by default in Release. Obviously, if the lower level macros are manually defined, this should override the default behaviour. 

Just my $0.02. :+1:

**Comment by Nava2** [comment]
Oh, meant to post this too: http://stackoverflow.com/a/5474282.

**Comment by ThePhD** [comment]
The problem is, because SOL is header only, it's not as if someone can build the debug version and then use the debug version deliberately, or not use the debug version deliberately: someone could "test" our framework for general speed and then balk at its slowness since we have such a humongous amount of testing at the lowest level of the API. That's why I think `SOL_SAFE_USERTYPE` should be defined by default, and `SOL_CHECK_ARGUMENTS` be "the next level"

**Comment by ThePhD** [comment]
Also, we already know how to detect "debug" for the two compilers, we just haven't flicked on the right switch yet: https://github.com/ThePhD/sol2/blob/develop/sol/compatibility/version.hpp#L45

**Comment by Nava2** [comment]
I feel like the "slowness" aspect for benchmarking shouldn't be a problem. If someone is benchmarking with debug builds, they're more or less doing it wrong. 

With respect to the right variable, I'm really not sure about that. [`NDEBUG`](http://en.cppreference.com/w/c/error/assert) seems to be the common one to use.

**Comment by ThePhD** [comment]
@ronald-reagan This should help you when you call things with `.`, unless you disable it by default.
