### ISSUE TITLE
how to iterator table with meta table's __pairs in C++

### ISSUE THREAD

**Issue by jdx2013519** [ThePhD/sol2#941]
`
sol::table a = lua["a"];
for (auto & it : a)
{
}
`
but table a's metatable __paris did not work. how to iterator it in C++？
thx。

**Comment by ThePhD** [comment]
We call `lua_next` and all that jazz from the Lua C API. Using `pairs` would likely require a different feature, or a new algorithm entirely.

I'll think about adding this as a feature, but right now it's not in sol.

**Comment by ThePhD** [comment]
Woops, did a derp and closed this when I shouldn't have. Thanks @nabijaczleweli !

**Comment by ThePhD** [comment]
There is a `.pairs()` method on tables now.

**Comment by ThePhD** [comment]
(Grab the latest from the develop branch.)
