### ISSUE TITLE
Hashing in require function

### ISSUE THREAD

**Issue by Mikhail2017** [ThePhD/sol2#942]
Hello. I've declared two functions in c++ code with different names and same signature
```
sol::state_view view(app.scriptEngine<lua_State>());

view["package"]["preload"]["sys.f1"] = [] {
        return []() mutable {
           std::cout << "f1\n";
}

view["package"]["preload"]["sys.f2"] = [] {
        return []() mutable {
           std::cout << "f2\n";
}
```

Trying to call them in lua code

```
local func1 = require("sys.f1")
local func2 = require("sys.f2")

func1()
func2()
```

will print
f1
f1

Changing signature of second function in c++ code and lua call to
```
view["package"]["preload"]["sys.f2"] = [] {
        return [](double) mutable {
           std::cout << "f2\n";
}

func2(0.)
```

is printing
f1
f2

Looks like function signature is hashed inside sol and used instead of functions name.

Ubuntu 18.02

**Comment by ThePhD** [comment]
No, it's not a hash.

The Itanium ABI (Linux) mangles lambdas differently than the SysV ABI (MSVC). MSVC provides a globally unique name, and gives that name to use in `__FUNC_DSIG__`. Linux does not require any such unique naming for the returned mangling of a lambda and implementations, in fact, do not bother in GCC or Clang with Itanium. They therefore melt together the names provided through macros and others into identical things, making them impossible to distinguish.

To fix this, wrap the return in `sol::as_function` (https://sol2.readthedocs.io/en/latest/api/as_function.html), or explicitly decay it to a function pointer.
