### ISSUE TITLE
[question] sol::table and declaration order

### ISSUE THREAD

**Issue by yamashi** [ThePhD/sol2#946]
Hello,

I am wondering if it is possible to have a stable ordering that follows the declaration in Lua.
For example I have the following table in Lua
```lua
OBJECT.Properties = { 
    TableTest = {},
    NumberTest = 42,
    StringTest = "str",
    BoolTest = true,
    ReplicatedStr = { Replicates = true, Default = "toto" },
    ReplicatedBool = { Replicates = true, Default = true },
    ReplicatedInt = { Replicates = true, Default = 45 },
    ReplicatedFloat = { Replicates = true, Default = 12.345 }
}
```

But when accessing the lua["OBJECT"]["Properties"] that I cast to a sol::table, the field order is different and even changes between runs, which makes it impossible for the UI to display the fields in the order the user intended. So far the only solution I can think of would be to have the user manually input the index for each element but I would like to avoid that.

Best,
Max

**Comment by ThePhD** [comment]
No. Lua Table do not have stable ordering. You need to gather all elements into something like a vector and provide a canonical ordering that way.

Or patch your Lua distribution. Either way, not something sol2 can do for you.

**Comment by Rochet2** [comment]
```lua
OBJECT.Properties = { 
    { "TableTest", {} },
    { "NumberTest", 42 },
    { "StringTest", "str" },
    { "BoolTest", true },
    { "ReplicatedStr", { Replicates = true, Default = "toto" } },
    { "ReplicatedBool", { Replicates = true, Default = true } },
    { "ReplicatedInt", { Replicates = true, Default = 45 } },
    { "ReplicatedFloat", { Replicates = true, Default = 12.345 } },
}
```

Here is a possible example of using lua table like a vector.
Basically it just stores pairs in a list and thus the order is saved.
However you lose the association table feature as you need to access them by index and loop all to find a specific one.
