### ISSUE TITLE
Seg fault when iterating over sol::table that's actually a usertype

### ISSUE THREAD

**Issue by jzrake** [ThePhD/sol2#948]
It seems that when a function whose argument is `sol::table` is invoked with a `sol::usertype`, calling the `begin()` member function of the table triggers a seg fault. This behavior is inconsistent with the `size()` member function, which correctly throws an error. For example:

```
module["zip"] = [] (sol::table args) // invoked with a usertype
{
    args.size();  // throws an error
    args.begin(); // seg fault
};
```

I get this behavior even when the library is configured with `SOL_ALL_SAFETIES_ON`.

**Comment by ThePhD** [comment]
I guess I'll need to add a guarding check to make sure this doesn't explode here.

**Comment by ThePhD** [comment]
This is tied to #941, but for now it will just iterate over nothing for usertypes.
