### ISSUE TITLE
Instantiate usertype via C++

### ISSUE THREAD

**Issue by Peka3** [ThePhD/sol2#950]
This is not a bug, rather a understanding problem. I'm creating a usertype by:
```
lua.new_usertype<Entity>("Player",
	"getId", &Entity::getId
);
```

After that I'm extending this usertype in LUA:
```
Player.counter = 0

function Player:increment()
	self.counter = self.counter + 1
	Log("Incremented player with id " .. self:getId() .. ": " .. self.counter)
end
```

If I call the Player:increment function via C++ and pass the pointer of 2 different entities, then they both share the same context.
```
Entity* entityA = new Entity(1); // (uint32_t id)
Entity* entityB = new Entity(2);

// passing reference of entity (to make 'self' working)
lua["Player"]["increment"](entityA);
// expected output: "Incremented player with id 1: 1"
lua["Player"]["increment"](entityB);
// expected output: "Incremented player with id 2: 1"
```

Both increment the same "counter"-variable, so the output is:
Incremented player with id 1: 1
Incremented player with id 2: **2**

Just they should both use their own context, how is this possible? I would be really glad if someone could explain what I do wrong, because I'm stucking here and even with the docs I still didn't found a solution how to make this scenario working.

**Comment by Rochet2** [comment]
A user data does not have a table of its own. By default you cannot store any data for an individual user data.

All Player type user data use the same metatable. You defined
Player.counter = 0
In your metatable. All player entities share this counter since they use the same Player table as a metatable and access the same counter.

Cant think from the top of my head how to make such a variable work from lua.

**Comment by ThePhD** [comment]
Usertypes are just that: **types**. Doing `Player.counter` -- as @Rochet2 said -- is the same as having a static variable in C++ that you set to a value.

"So then, how do I extend it with more variables and functions?"

That requires a little more hard work. The good news: there's examples of that hard work, to make it easy on you!
- https://github.com/ThePhD/sol2/blob/develop/examples/source/dynamic_object.cpp
- https://github.com/ThePhD/sol2/blob/develop/examples/source/usertype_dynamic_get_set.cpp


Good luck!
