### ISSUE TITLE
Can sol return af std vector of std vector of std vector of usertype?

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#951]
Hello I tried to 

```
sol::function genFunc = state["generateChunk"];
sol::object temp = genFunc(x,y,z);
if (temp.is<std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>>()) {			
    std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>& voxData = temp.as<std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>>();
}
```

Well it fails. the if statment is true, but it thorws when calling as
The user type is created like this:
`state.new_usertype<VoxelData>("VoxelData", sol::call_constructor, sol::factories(VoxelData::Create);`

and I used sol::factories (so it should create a std::shared_ptr when calling "VoxelData(1)" in the lua script)

I also tried just with integers and this worked fine:
```
if (temp.is<std::vector<std::vector<std::vector<int>>>>()) {			
    std::vector<std::vector<std::vector<int>>>& voxData = temp.as<std::vector<std::vector<std::vector<int>>>>();
}
```

The lua script:
```
    voxels = {}

    for x=1,chunkWidth do
        voxels[x] = {}
        
        for y=1,chunkWidth do
            voxels[x][y] = {}
    
            for z=1,chunkWidth do
                voxels[x][y][z] = VoxelData(1);

            end
        end
    end

    return voxels
```

and for the integer test:
```
    voxels = {}

    for x=1,chunkWidth do
        voxels[x] = {}
        
        for y=1,chunkWidth do
            voxels[x][y] = {}
    
            for z=1,chunkWidth do
                voxels[x][y][z] = 1;

            end
        end
    end

    return voxels
```
Am I completely of the tracks, is this even a sol feature or is this a bug

Edit:
I have also tried with sol:.table and that works fine too

**Comment by ThePhD** [comment]
`std::vector<std::vector<std::vector<int>>>&` asks for a REFERENCE to the data. This will not work; it is not a `std::vector` in memory (how can I reference memory that is not in the exact bit-shape necessary?): it is a `sol::table`. What you're asking for shouldn't work under any circumstances (I'm guessing an MSVC extension is kicking in that allows you to have a temporary stored in a reference, or that your code is just broken without safeties on).

What you should do is either used a `sol::nested` function argument/explicit `.get<...>()` call (documented here: https://sol2.readthedocs.io/en/latest/api/nested.html), or try to access the nested in a simpler manner. Note that doing a table conversion will explicitly convert all the elements immediate;y, and that will cost you in terms of memory.

**Comment by xzores** [comment]
Soo just understand you. Right now I am doing this:

```
std::vector<std::vector<std::vector<sol::table>>>& voxData = temp.as<std::vector<std::vector<std::vector<sol::table>>>>();

							//TODO rework this (optimize) 

							for (int x = 0; x < voxData.size(); x++)
								for (int y = 0; y < voxData[x].size(); y++)
									for (int z = 0; z < voxData[x][y].size(); z++) {
										int i = voxData[x][y][z]["type"];
										s->set(x, y, z, VoxelData(i));
									}
```

And it seems to work perfect.
Are you saying that it should not work or are you saying the one with int should not work or both?

**Comment by ThePhD** [comment]
That that builds and works is a miracle, and I am not going to ask too many hard questions about it. :D

(No, what you just wrote should not even compile or run. At some point when I'm less tired I'm going to write up your code as an example and see why it's not horrifically exploding on you. But we'll just count it as a blessing that it's working, so ship it!)

**Comment by xzores** [comment]
lols seems to be working perfect XD, tha fak. But I mean that's fine by me, ill ship it

**Comment by xzores** [comment]
Hmm ok, I will do the right thing and use sol::nested, but hmmm how??

From the example, I would think that I should do like this:
```
sol::nested<std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>> nestData = temp.as<sol::nested<std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>>>();
							
const std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>& voxData = nestData.value();
```

But this will call the panic function and abort the app

**Comment by xzores** [comment]
I ended up doing this:

```
if (temp.valid() && temp.is<std::vector<std::vector<std::vector<std::shared_ptr<VoxelData>>>>>()) {

							const auto& voxData = temp.as<sol::nested<std::vector<sol::nested<std::vector<sol::nested<std::vector<sol::object>>>>>>>();

							//TODO rework this (optimize) 

							for (int x = 0; x < voxData.size(); x++){
								const auto& voxDatax = voxData[x].value();
								for (int y = 0; y < voxDatax.size(); y++){
									const auto& voxDataxy = voxDatax[y].value();
									for (int z = 0; z < voxDataxy.size(); z++) {
										const sol::object& o = voxDataxy[z];

										if(o.is<std::shared_ptr<VoxelData>>()){
											std::shared_ptr<VoxelData>& voxelData = o.as<std::shared_ptr<VoxelData>>();
											s->set(x,y,z, *voxelData);
										}

									}
								}
							}
						}
```

is this what you meant?

**Comment by ThePhD** [comment]
You're not supposed to do a bunch of `sol::nested`... so, well. Let me try my hand at writing this, and see if I can't get something to work that's a bit better! It will take a while, though: I'm doing ISO C Standardization Meeting stuff right now.

**Comment by xzores** [comment]
Thanks, an example would be great ;)
