### ISSUE TITLE
Unhandled exception when assigning nil to a nonexistent element in a vector of variants

### ISSUE THREAD

**Issue by McKillroy** [ThePhD/sol2#953]
This example demonstrates the problem:
Assigning nil to a nonexistent element in vector of int c5 throws and gets caught as expected.
The same thing with vector of variants c4 blows up.
Code:

`
     #include <sol/sol.hpp>
     #include <exception>
    #include <iostream>
    #include <variant>
    #include <vector>
    
    int main( ) {
        sol::state lua {};    
        std::vector<std::variant<int, double, std::string>> c4;
        std::vector<int> c5;
    
    lua.open_libraries( sol::lib::base,
          sol::lib::bit32,
          sol::lib::coroutine,
          sol::lib::count,
          sol::lib::debug,
          sol::lib::io,
          sol::lib::math,
          sol::lib::os,
          sol::lib::package,
          sol::lib::string,
          sol::lib::table,
          sol::lib::utf8 );
    
      lua[ "c4" ] = sol::var( &c4 );
          
      lua.safe_script( "print(\"Hello world! Lets test some explosives!\")" );
  
      try {
          lua.safe_script( R"V0G0N(
          print("\n\nAssigning a regular value to the first new slot in the c4 vector: [1]")
          c4[1] = 1
          print("c4[1]: ", c4[1])
          )V0G0N" );
      }
      catch ( std::exception& e ) {
          std::cout << "Explodes to: " << e.what( ) << std::endl;
      }
  
      try {
          lua.safe_script( R"V0G0N(
          print("\n\nAssigning nil to an existing slot in the c4 vector: [1]")
          c4[1] = nil
          print("c4[1]: ", c4[1])
          )V0G0N" );
      }
      catch ( std::exception& e ) {
          std::cout << "Explodes to: " << e.what( ) << std::endl;
      }
  
      try {
          lua.safe_script( R"V0G0N(
          print("\n\nAssigning nil to a new slot in the c5 vector: [1] (exception gets caught)")
          c5[1] = nil
          print("c5[1]: ", c5[1] )
          )V0G0N" );
      }
      catch ( std::exception& e ) {
          std::cout << "Explodes to: " << e.what( ) << std::endl;
      }
  
      try {
          lua.safe_script( R"V0G0N(
          print("\n\nAssigning nil to a new slot in the c4 vector: [2] (exception gets NOT caught)")
          c4[2] = nil
          print("c4[2]: ", c4[2])
          )V0G0N" );
      }
      catch ( std::exception& e ) {
          std::cout << "Explodes to: " << e.what( ) << std::endl;
      }
   }
`

**Comment by McKillroy** [comment]
Same problem recently (unpropagated exeption) when assigning a wrong type to a variant in a vector.
Not making an extra issue here - I think it's related.

**Comment by ThePhD** [comment]
This should be improved in latest. Pull and let me know.

**Comment by ThePhD** [comment]
This was fixed.
