### ISSUE TITLE
Is this correct usage (returning a table from C++ function)

### ISSUE THREAD

**Issue by Leadwerks** [ThePhD/sol2#956]
I'm working on integrating a debugger, and wanted to ask if this is proper usage?:
```
	sol::table Vec3::debug()
	{
		sol::table t;
		t["x"] = x; t["y"] = y; t["z"] = z;
		return t;
	}
```
The function is called directly from Lua code:
```
local t = v:debug()
```

**Comment by ThePhD** [comment]
`sol::table` does not attach it to the working Lua state. Do:

```cpp
	sol::table Vec3::debug(sol::this_state ts)
	{
		sol::table t(ts, sol::create);
		t["x"] = x; t["y"] = y; t["z"] = z;
		return t;
	}
```

The way you call it doesn't change, as `this_state` is a "transparent argument" (https://sol2.readthedocs.io/en/latest/api/this_state.html):

```cpp
local t = v:debug()
```

**Comment by Leadwerks** [comment]
Oh man, this is so cool. This works really really well with Lua Debugger:
https://marketplace.visualstudio.com/items?itemName=devCAT.lua-debug
