### ISSUE TITLE
usertype container example

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#959]
Hi,

Sorry about the help desk but I am having hard time figuring how to make an usertype as a container.
My constraint is that I cannot modify the usertype though, otherwise you have indeed already put nice helpers to do that... It would have been to easy :)

I have a usertype like the following
```
struct Point
{
Point() {}
Point(int x_, int y_) : x(x_), y(y_) { }
int x = 0;
int y = 0;
};
```

and would like to be able to access as an array in lua
as well as through x and y properties
So far I have that
```
auto generator = module.new_usertype<Point>("Point",
                                                             sol::constructors<Point(), Point(int, int)>());
      generator.set("x", sol::property(&Point:x));
      generator.set("y", sol::property(&Point:y));
```

I tried to declare

```
namespace sol {
template <>
struct is_container<juce::Point<int>> : std::true_type {};
}
```

and then It seems to be related to sol::meta_function::pairs
or something like
```
template <>
struct usertype_container<Point> {

  using value_type = int;
  using size_type = size_t;

  size_type max_size() const noexcept { return 2; }
};
```
I have seen the examples pairs.cpp but it seems quite complicated especially for a fixed size container

Any pointers ?

Thanks !

**Comment by ThePhD** [comment]
The pairs example is what you'll have to do, and that IS the _easy_ version.

The next level up is implementing whatever subset of relevant functions you need to inside the `usertype_container` specialization, in this list: https://sol2.readthedocs.io/en/latest/containers.html#container-operations

Good luck.

**Comment by otristan** [comment]
oh boy.

Thanks !
