### ISSUE TITLE
Multiple independent bindings to c variables

### ISSUE THREAD

**Issue by fahrnic** [ThePhD/sol2#962]
My application updates periodically several variables that are bound to the lua context.
The script will be called after some values have been updated.
```
static int a = 5;

auto utA = m_lua.new_usertype<void>("a");
utA["aref"] = sol::var(std::ref(a));

m_lua.script("print(a.aref)");	// 5

auto utB = m_lua.new_usertype<void>("b");
utA["bref"] = sol::var(std::ref(a));

a = 6;

m_lua.script("print(a.aref)");	// nil (!)
m_lua.script("print(b.bref)");	// 6
```
I expect to receive the value 6 instead of nil at the 2nd output.
Remarks:
- I don't use the the user_type to bind to a concrete type --> _void_. My application binds in the initialization phase many variables to the script dynamically. I will have several independent namespaces (e.g. usertypes a, b)
- I did also try with tables (create_named_table) - but ref variables were handled as addresses. 
- it is important to have the binding forward/backward between c++/lua

What is the best way to generate bound types like this:
```
a.aref1
a.aref2
a.aref3
...
b.bref1
b.bref2
b.bref3
...
```

**Comment by fahrnic** [comment]
Because my application generates the usertypes dynamically (from json like source) I do not have an individual type for each item. Is there an other way that allows to bind vars w/o type?

**Comment by fahrnic** [comment]
For binding a Scalar value I made the class `ScalarContainer`. Now binding forwards and backwards works.
**But** arithmetic operations (e. g. Modulo `%`) are not allowed (_Error sol: runtime error: [string "`print(myTupel.xyz%17)`"]:1: attempt to perform arithmetic on a sol.ScalarContainer<long unsigned int> value (field 'xyz')_)

I use `ScalarContainer` as follows:
```
auto table = lua.create_named_table(tableName);
table.set(entryName, ScalarContainer<T>(*(T *)entryRef));
```
The class `ScalarContainer`:
```

template <typename T>
class ScalarContainer
{
public:
	ScalarContainer(T &value) : m_value(value)
	{
	}

	T &value()
	{
		return m_value;
	}

	operator T &()
	{
		return value();
	}

private:
	std::reference_wrapper<T> m_value;
};
```
I know this problem is related to `reference_wrapper`. What is the right solution for this? Workaround? Alternate solution to bind single values to a ref?

**Comment by ThePhD** [comment]
So, to solve your original problem:

bind a single usertype (using the type `void` or similar) and re-use the same thing to keep binding different variables. Note that under this scheme you can't use the same name for 2 different things, so be careful to avoid that. You can get a usertype in sol3 doing `sol::usertype<void> my_usertype_box = lua["a"];`. You can check if it exists by doing `sol::optional<sol::usertype<void>> my_usertype_box = lua["a"];`

For your second question, you need to override all of the operations on the ScalarContainer type. That is, you need to explicitly bind `sol::meta_function::modulus` and all of those when binding your `ScalarContainer` usertype.

Good luck!
