### ISSUE TITLE
What about add natvie_ptr for new_usertype object?

### ISSUE THREAD

**Issue by halx99** [ThePhD/sol2#966]
Read these guidelines. They are relatively simple and will allow me to help you better:

1. Produce a simple, short, compilable test case that reproduces your problem.
2. Make a descriptive title that summarises the bug as a whole.
3. Explain the bug in as much detail as you can in the body of the issue. 
4. Include Compiler/IDE (Visual Studio, XCode...), Build and Deployment System, Language (C++, Objective-C++), and any special defines you have set.

If you want to request a feature:

1. Produce any relevant imaginary code that illustrates what you would like or desired behavior.
2. Include a description and title of what you would like.
3. Annotate and describe the behavior through comments, asserts or just a small write up.

Thanks for helping sol grow!

**Comment by ThePhD** [comment]
Please be more specific. What is `native_ptr`.

**Comment by halx99** [comment]
Umm, I think this is a specific feature, so just ignore this issue.
The use case is when I export our socket lib's io_service to lua, I wan't redirect network log to unity3d editor's console, for more detail, you can see:
https://github.com/yasio/DemoU3D/blob/master/Assets/StreamingAssets/YAsioTest.lua

**Comment by halx99** [comment]
the native_ptr is the real address of c++ object.
