### ISSUE TITLE
Compatible Layer Compiler Errors While Using MoonJIT

### ISSUE THREAD

**Issue by atom0s** [ThePhD/sol2#967]
Didn't want to make a pull request to fix this without first seeing if there is something I am missing config wise that would avoid this. I am new to sol3, and still getting used to how it is setup.

Environment setup:
 - VS2019
 - sol3 latest (as of May 13, 2020)
 - MoonJIT latest (as of May 13, 2020) - https://github.com/moonjit/moonjit

The Lua 5.3 compat header has two errors in it while making use of MoonJIT which can be easily fixed. However, I am not sure if this is the appropriate fix for this, or if I am just overlooking a define.

The errors are:

```
compat-5.3.h(102,16): error C2371: 'lua_Unsigned': redefinition; different basic types

compat-5.3.h(157,1): warning C4005: 'lua_pushglobaltable': macro redefinition
```

_Second is only a warning by default, but I generally compile with warnings as errors._

The first can be fixed by assuming LuaJIT is the only time this issue will be seen, as I did not have it while compiling with stock Lua. So I fixed that via:

```cpp
#if !defined(LUAJIT_VERSION)
typedef size_t lua_Unsigned;
#endif
```

The second is fixed by just checking for existing definitions like the other functions near it:

```cpp
#ifndef lua_pushglobaltable
#define lua_pushglobaltable(L) \
  lua_pushvalue((L), LUA_GLOBALSINDEX)
#endif
```

Edit; sorry forgot to include a small snippet:

```cpp
// MoonJIT lib
#pragma comment(lib, "lua51.lib")

// General includes..
#include <sol/sol.hpp>
#include <Windows.h>
#include <string>
#include <vector>

int32_t __cdecl main(int32_t argc, char* argv[])
{
    sol::state lua;
    lua.open_libraries();
}
```

This is enough to produce these errors. Include paths point to sol and moonjit accordingly.

**Comment by ThePhD** [comment]
Is there a MoonJIT-specific macro I can use for the first case? The second I can happily fix up.

**Comment by atom0s** [comment]
I don't believe so, they just forked LuaJIT with a new name and continued some development. The actual Lua header and usage remains the same/unchanged, and the Lua versioning variables/macros are left as LUAJIT_ prefixed.

```cpp
#define LUAJIT_VERSION		"moonjit 2.2.0"
#define LUAJIT_VERSION_NUM	20200  /* Version 2.2.0 = 02.02.00. */
#define LUAJIT_VERSION_SYM	moonjit_version_2_2_0
#define LUAJIT_COPYRIGHT	"Copyright (C) 2019-2020 moonjit developers"
#define LUAJIT_URL		"https://github.com/moonjit/moonjit"
```

You could base it on the values, but that may be a bit more annoying to maintain.

**Comment by ThePhD** [comment]
I've left an issue in the MoonJIT repository. If I don't get a simple answer then the hackery begins.

**Comment by ThePhD** [comment]
Spicy: https://github.com/moonjit/moonjit/commit/d7784a30acb78f3b378462892ab9abf2ecb28eaa

We can now just check for `MOONJIT_VERSION`. If you're okay with that, I'll use that to check for MOONJIT.

**Comment by atom0s** [comment]
Ultimately up to you, but LuaJIT stock will probably have the same issues. 

I am looking into other libraries than sol at this point though as sol does not seem to deal with coroutines well from the C side.

**Comment by ThePhD** [comment]
Fair enough! Good luck.

**Comment by ThePhD** [comment]
This is taken care of.
