### ISSUE TITLE
Errors with const std::optional& in parameters (VS 16.6.0)

### ISSUE THREAD

**Issue by SirLynix** [ThePhD/sol2#969]
I updated Visual Studio to the last version and got the function_pointer_type error (#935). I read it was fixed by sol last version so I updated to master (d9c034d67263671bc35d3e3a3acc29682ebab88d).

This indeed fixed the error but a new one appeared, which seems related to const std::optional<T>&:

```cpp
#include <sol3/sol.hpp>

int main()
{
	sol::state state;
	state["dummy"] = [](const std::optional<int>& path)
	{
	};
}
```

Here's the log: https://hastebin.com/quvowoqohi.shell

**Comment by ThePhD** [comment]
That is not the log, I don't think.

**Comment by SirLynix** [comment]
Oh crap. Fixed!

**Comment by ThePhD** [comment]
This is now fine.

**Comment by SirLynix** [comment]
Thanks!
