### ISSUE TITLE
can I have aliases/typedefs with userdata but with different names?

### ISSUE THREAD

**Issue by thinlizzy** [ThePhD/sol2#97]
if I set another usertype with the same type (an alias), but with a different name on Lua, it overwrites the previous usertype definition

example code:
```
#include <cmath>
#include <sol.hpp>

class point {
public:
	int x,y;

	constexpr point():
		x(),y()
	{}
	constexpr point(int x, int y):
		x(x), y(y)
	{}
	
	int distance() { return std::sqrt(x*x + y*y); }
};

using Vect = point;

int main()
{
	sol::state lua;
	lua.open_libraries(sol::lib::base);
	lua.new_usertype<point,int,int>("point",
		"x",&point::x,
		"y",&point::y);
	lua.script("p = point.new(10,20)");
	lua.script("print(p.x,p.y)");
		
	lua.new_usertype<Vect,int,int>("Vect",
		"distance",&Vect::distance);
	lua.script("v = Vect.new(10,20)");
	lua.script("print(v:distance())");

	lua.script("p2 = point.new(10,20)");
	lua.script("print(p.x,p.y)");
}
```

output:
```
10      20
22
nil     nil
```

so once I register "Vect", point loses x and y definitions :(

**Comment by ThePhD** [comment]
Aside from the logical nightmare implementing this would be...

... _why_?

**Comment by thinlizzy** [comment]
the weird part is I get the "expected behavior" if I publish all functions in both user types
(so lua can have both point and Vect doing what I need, if I don't mind the 'extra' functions)

**Comment by thinlizzy** [comment]
my real question is why the latter definition overwrites the functions of the former one, but the former name still stays available on Lua?

**Comment by ThePhD** [comment]
The actual metatable in the registry is based of off the `usertype_traits<T>` specialization. `typedefs` are not a new type: they're the same time, so they both have the same `usertype_traits<T>`. The new one overrides the old created metatable entirely. The old name points to that same metatable, but the metatable is being changed by `sol`.

I would need to finish a huge refactor to `usertype` in order to make something like this behave proper... and it would ruin things like variables, so I'm not sure if it can actually be done..!

**Comment by ThePhD** [comment]
Quick fix is to introduce a "strong typedef"
````
struct vect : point {
using point::point;
};
````

Now it'll be a different type, and get its own metatable from the `usertype_traits<T>`.

**Comment by thinlizzy** [comment]
as a workaround, I can do like this:
```
lua.new_usertype<point,int,int>("point");
lua.new_usertype<Vect,int,int>("Vect"
        "x",&point::x,
        "y",&point::y,
        "distance",&Vect::distance);
```
and have all functions in both "point" and "Vect" names in Lua

can I do this safely or will this introduce bad behavior in Lua?

**Comment by ThePhD** [comment]
Should be just fine.

**Comment by ThePhD** [comment]
Official advice to have 2 different ones is to either define them in the proper order (make sure 2 typedefs don't collide) or introduce a [strong typedef](http://www.boost.org/doc/libs/1_60_0/libs/serialization/doc/strong_typedef.html) (using boost or otherwise).
