### ISSUE TITLE
Possibility to catch C++ exceptions within lua script with pcall, xpcall

### ISSUE THREAD

**Issue by deadlocklogic** [ThePhD/sol2#970]
Hi!
First of all, I would like to thank you for such a great library.
I want to ask about the possibility of catching C++ exceptions from within lua script with pcall, xpcall.
Is this possible with minimal changes to the code structure (I am trying to bind a relatively big library).

So basically a simple example describing what I need (just to show the idea) :
```C++
#define SOL_USING_CXX_LUA 1
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

#include <assert.hpp>
#include <iostream>

int main(int argc, char** argv)
{
	sol::state lua;
	lua.open_libraries();

	lua.set_function("divide", [](float a, float b) -> float { 
		if (b == 0)
		{
			throw std::exception("This is an error");
		}
		return a / b;
	});
}
```

In the lua script I want to be able to call the code below without exiting directly after the thrown exception:
```Lua
if pcall(print(divide(3, 0))) then
    print("Division is valid")
else
    print("Division is invalid")
end
```

In reality when trying this simple example I am getting an unhandled exception (in single header sol.hpp line 24181 method ```inline int default_at_panic(lua_State* L)```):
```[sol3] An error occurred and panic has been invoked: stack index 1, expected string, received function```.

The technique I am talking about works automatically with SWIG according to its docs.
I know a lot of C++ developers will prefer changing the semantics of exceptions to return codes/signals/return args etc.., and use exceptions for fatal errors etc ... and of course as developing my C++ project I am trying to abide by such concepts as much as possible.

Another side question, I am trying to run the exact snippet found in the docs:
https://sol2.readthedocs.io/en/latest/exceptions.html#exception-handling still I am being hit with the same unhandled exception.

I am using:
Microsoft Visual Studio Community 2019 : Version 16.6.0
lua 5.1.5

Any suggestions?
Thanks again!

**Comment by atom0s** [comment]
Use `xpcall` with an error handler instead. Here's a simple try/catch lib for Lua that makes use of this and works with your given code to catch the exception from within Lua.

https://github.com/djfdyuruiry/lua-try-catch-finally/blob/master/try-catch-finally.lua

**Comment by deadlocklogic** [comment]
Thanks, well this example is of course very simple, it tries to show how lua can imitate java or C++ with a try/catch/finally as syntactic sugar. It is not related to sol maybe.
Just a question is sol3 compatible with Visual Studio 2019 because many snippets in the sol docs are crashing with a same unhandled exception: '''[sol3] An error occurred and panic has been invoked: stack index 1, expected string, received function'''

**Comment by deadlocklogic** [comment]
My bad lua exception handling is working out of the box indeed with sol, my lua code should've been:
```
status, retval = pcall(divide,3, 0)
if status then
    print("Value was : ", retval)
    print("Division is valid")
else
    print("Division is invalid")
end
```
In my case I was calling the throwing function before even giving pcall the opportunity to call it safely and catch the exception.
