### ISSUE TITLE
usertype_container::size example seems to be incorrect

### ISSUE THREAD

**Issue by sagamusix** [ThePhD/sol2#973]
Example in question: https://github.com/ThePhD/sol2/commit/5022c4d8f62bcf27888041947daf8f28fa83c21c#diff-b931f6c71498bb0a100fb9b02f7f35d6R153

I was adding `usertype_container<my_type>::size` to my code similarly to how it's done by that example, but that seems to be wrong, as the function is directly called by lua and sol doesn't really seem to do any sort of translation of the stack.

So after a little debugging session, my understanding is that the `size` function of a `usertype_container` specialization should look like this instead:

```cpp
static int size(lua_State *L)
{
	auto &self = sol::stack::get<my_type &>(L, 1);
	sol::stack::push(L, self.size());
	return 1;
}
```

Can you confirm this?

Related: Would it be possible to add a `size` specialization in the same way as `begin`/`end`/etc., i.e. something like `static int size(lua_State *L, my_type &self)`, or is there a technical reason why it doesn't work the same way and the user has to access the stack themselves?

**Comment by ThePhD** [comment]
Oops, that code is definitely wrong in the example / tests.

`offset`, `begin`, and `end` are supposed to be different: they are called by the default implementation where possible.

`size` is supposed to be more like the other extension points found in the [container extension points docs](https://sol2.readthedocs.io/en/latest/containers.html#container-operations). So your implementation is correct. Let me get on fixing things and making sure it's fine...

**Comment by ThePhD** [comment]
There, it should be fixed on master now.
