### ISSUE TITLE
Can't compile after updating vs2019 to newest version

### ISSUE THREAD

**Issue by xzores** [ThePhD/sol2#974]
I get the error:
'function_pointer_type' is not  member if "sol::lua_bind:traits<sol::basic:reference<false>>
in call.hpp line 344

![image](https://user-images.githubusercontent.com/17770917/83419143-e5d5e680-a424-11ea-8c84-47618ebe7e1d.png)

This happened after updating to vs2019 16.6.0

**Comment by adam4813** [comment]
This is now a problem with github actions as they have moved their Visual Studio version to 16.6. I realize that there was a PR that addressed this, but, from my understanding, you don't plan to release for a month or more. Is it possible to do a patch release version that fixes this to allow github actions to continue to work again?

**Comment by ThePhD** [comment]
Guess I need a quick patch release. Lemme try to split my changes into pieces.

Pray for me: I am bad at git.

**Comment by adam4813** [comment]
If you can make one, I'll make a pr for vcplg.

**Comment by egorpugin** [comment]
Also have been hit by this.

**Comment by ThePhD** [comment]
https://github.com/ThePhD/sol2/releases/tag/v3.2.1

Fire up the CI engines.

**Comment by adam4813** [comment]
Someone beat me to adding a vcpkg PR, but it is up

**Comment by helmesjo** [comment]
@ThePhD Thanks! See [here](https://github.com/conan-io/conan-center-index/pull/1390/files) for an example PR (for the previous version).

**Comment by ThePhD** [comment]
Oop, they require I actually run conan and all that jazz on my local machine to verify it works.

I don't have conan or any idea what it takes to get it all set up xD

**Comment by helmesjo** [comment]
@jgsogo
Hello friend! :)

**Comment by jgsogo** [comment]
Hi! Is this a new version `3.2.1`? 

Have you tried to create the PR to Conan Center? Adding a new version is really, really easy, just add it to `config.yml` and to `3.x.x/conandata.yml` files in this folder: https://github.com/conan-io/conan-center-index/tree/master/recipes/sol2

Version `3.2.0` is already there so probably it is not required to change anything else in the recipe or the build system.

**Comment by ThePhD** [comment]
Nonono, I wasn't confused about /how/ to do it, I know what to do given the PRs that others worked so hard on!

I just can't satisfy the checklist of "and you must run it on your computer to check it works", because I don't have conan on my computer yet!

**Comment by jgsogo** [comment]
You can create the PR with the changes and just have a look to the CI output... I won't punish you for not clicking that checkbox 😅 

But don't worry, tomorrow I'll create the PR myself if you didn't before

**Comment by ThePhD** [comment]
Ahhh you beat me to it! Well, thank you for your help here.

Sometimes, I wish I had less to do. ;;

**Comment by jgsogo** [comment]
> Sometimes, I wish I had less to do. ;;

Same here, but Conan and Conan-related repos is my battlefield. I can move quickly there. 😄

**Comment by jgsogo** [comment]
Already there 🎉  https://conan.io/center/sol2/3.2.1

```
conan install sol2/3.2.1@ -g cmake_find_package [--profile <configuration>]
```

and there you have it, ready to use!

**Comment by ThePhD** [comment]
Sheeeit, you're fast! Thanks for working on this. 💞
