### ISSUE TITLE
thread-local storage is not supported on certain iOS devices

### ISSUE THREAD

**Issue by TheLartians** [ThePhD/sol2#979]
Hey thanks again for this great library!

I'm not sure if this is in the scope of the project, but I wanted you to be aware of the following issue when using this library for mobile development. When building projects using Sol2 targeting iOS 9.3 and above, the compile fails due to `thread_local` storage not being available.

```
In file included from /Users/lars/.cache/CPM/luaglue/e46a1166397520b8ef11b3099c4d7efc2576e2d4/source/state.cpp:14:
In file included from /Users/lars/.cache/CPM/sol2/524cbe7903b2da684ddfbcb6bb3b09253b756434/include/sol/sol.hpp:56:
In file included from /Users/lars/.cache/CPM/sol2/524cbe7903b2da684ddfbcb6bb3b09253b756434/include/sol/state.hpp:27:
In file included from /Users/lars/.cache/CPM/sol2/524cbe7903b2da684ddfbcb6bb3b09253b756434/include/sol/state_view.hpp:31:
In file included from /Users/lars/.cache/CPM/sol2/524cbe7903b2da684ddfbcb6bb3b09253b756434/include/sol/state_handling.hpp:32:
/Users/lars/.cache/CPM/sol2/524cbe7903b2da684ddfbcb6bb3b09253b756434/include/sol/lua_value.hpp:50:11: error: thread-local storage is not supported for the current target
                        static thread_local lua_State* L = nullptr;
                               ^
1 error generated.
```

My current workaround is to disable the `thread_local` keyword by adding the definition `-Dthread_local=` to the target building sol2. As my project's Lua code runs on a single thread, this should be fine but I assume the workaround is not portable.

Maybe a sol2 macro to enable "single-thread mode", that disables thread-local storage would be a nicer alternative in this case.   

## Reproducer

Create a file `CMakeLists.txt` containing the following code.

```cmake
cmake_minimum_required(VERSION 3.15)

project(Sol2-iOS-test)

# ---- Fetch CPM.cmake to add dependencies ----

set(CPM_DOWNLOAD_LOCATION "${CMAKE_BINARY_DIR}/cmake/CPM.cmake")
set(CPM_DOWNLOAD_VERSION 0.27.1)

if(NOT (EXISTS ${CPM_DOWNLOAD_LOCATION} AND CPM_VERSION STREQUAL CPM_DOWNLOAD_VERSION))
  message(STATUS "Downloading CPM.cmake")
  file(DOWNLOAD https://github.com/TheLartians/CPM.cmake/releases/download/v${CPM_DOWNLOAD_VERSION}/CPM.cmake ${CPM_DOWNLOAD_LOCATION})
endif()

include(${CPM_DOWNLOAD_LOCATION})

# ---- Dependencies ----

# Add a specific version of sol2
CPMAddPackage(
  NAME sol2
  VERSION 3.2.1
  URL https://github.com/ThePhD/sol2/archive/v3.2.1.zip
  DOWNLOAD_ONLY YES
)

# Add LuaGlue project (as an example project using sol2)
CPMAddPackage(
  NAME LuaGlue
  GITHUB_REPOSITORY TheLartians/LuaGlue
  VERSION 1.2.4
)

# Uncomment the following line to disable thread_local storage in the LuaGlue target
# target_compile_definitions(LuaGlue PRIVATE -Dthread_local=)
```

To build the project for all supported iOS architectures, run the following commands on a Mac with Xcode installed. This should fail unless the line removing the `thread_local` keyword is defined.

```bash
# configure to build for supported iOS architectures on install target
cmake -E env CXXFLAGS="-fno-aligned-allocation" cmake -H. -Bbuild/ios -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO -DCMAKE_OSX_DEPLOYMENT_TARGET=9.3 -DCMAKE_IOS_INSTALL_COMBINED=YES -DCMAKE_INSTALL_PREFIX=$(pwd)/root
# build library containing code for supported iOS architectures at $(pwd)/root
cmake --build build/ios --target install
```

**Comment by ThePhD** [comment]
Guess I'll just have to mark it as `static` for places that don't have thread local storage. I wonder if there's a feature test macro that works for that... probably not.

Bleurgh...

**Comment by TheLartians** [comment]
TBH I'm also fine with keeping the current approach, as this seems to be a very specific use-case. Targeting iOS 10.0 and above already seems to allow the use of `thread_local` and in my case I can simply "patch" sol through the very hacky macro described above.

**Comment by iamtimmy** [comment]
I would also really appreciate if I could turn the usage of TLS off. Would be a big help!

**Comment by ThePhD** [comment]
Do later versions of iOS have this problem? Which version of Apple Clang doesn't have `thread local`? How do I detect this?

**Comment by TheLartians** [comment]
If we change the argument `CMAKE_OSX_DEPLOYMENT_TARGET` to `10.0` above, then my example compiles, so I assume this only affects projects that target iOS 9.3 and below. I assume this will effect all versions of apple clang as I guess it's related to with the iOS runtime.
As of how to detect it I honestly have no idea, even a CMake feature test probably won't work as it would only check the first architecture and not all that we will be building for in the install target. I would probably let the user figure this out and offer a sol macro to disable TLS when desired.

**Comment by ThePhD** [comment]
Define `SOL2_NO_THREAD_LOCAL` to turn off the use of thread local, without having to hack things.

**Comment by TheLartians** [comment]
I can confirm that using `-DSOL_NO_THREAD_LOCAL=true` works and is is much nicer solution than `-Dthread_local=`. 😉 
Thanks for the quick update!
