### ISSUE TITLE
Complicated functions templates

### ISSUE THREAD

**Issue by felaugmar** [ThePhD/sol2#98]
I'm using a library called [EntityX](https://github.com/alecthomas/entityx);

And I want to use a function with this header:

```
template <typename C, typename ... Args>
ComponentHandle<C> Entity::assign(Args && ... args) {
```

The function above is used this way:
```
Animator anim;

auto entity = ecs.entities.create();
entity.assign<RenderComponent>(anim);
entity.assign<PlayerComponent>();
```

Well, my primary idea is use some Lua code like bellow:

```
local anim = Animator.new();

local entity = World:createEntity();
entity:assign(RenderComponent, anim);
entity:assign(PlayerComponent);
```

Any way to do that directly with the current Sol2 API?

--

My second idea is to do each assign function for each Component, like these:
```
entity:assignRenderComponent(anim);
entity:assignPlayerComponent();
```

Anyone can help-me with a better idea?

**Comment by ThePhD** [comment]
You can't bind *raw* template functions to any FFI: template functions don't exist until you nail them down into the executable with a specific instantiation. So, Nail Them Down:

````
sol::state lua;
// setup
lua.new_usertype<entityx::Entity>( "entity_t", // or whatever you like
    "assignRenderComponent", &entityx::Entity::assign<RenderComponent, Animator&>,
    "assignPlayerComponent", &entityx::Entity::assign<PlayerComponent>
    // anything else you like
);
````

Then, assuming you've also bound "createEntity" and what not, your second idea would work just fine.

NOTE: I only gave a cursory read through EntityX. If that's the syntax, then it should work like that...

**Comment by nabijaczleweli** [comment]
THEY'RE NOT TEMPLATE FUNCTIONS, YOU DUMBO, THEY ARE NOT FUNCTIONS AT ALL.
THEY'RE CALLED *FUNCTION TEMPLATES* FOR A FUCKING REASON.

**Comment by felaugmar** [comment]
Thank you for the detailed info about this,about function templates and how it works at all.

**Comment by nabijaczleweli** [comment]
@ThePhD rude

**Comment by felaugmar** [comment]
Worked, just like you said,
```
    lua.new_usertype<Entity>("Entity",
      "assignRenderComponent", &Entity::assign<RenderComponent, Animator &>,
      "assignPlayerComponent", &Entity::assign<PlayerComponent>
    );
```

**Comment by ThePhD** [comment]
I should probably put something in the docs to describe this specific situation. I'll make a note. Thanks for reporting back!

**Comment by zeroxer** [comment]
I got some error when using template function.
- World.h
```cpp
    template <typename ComponentType, typename ... Args>
    void unpack(Entity entity, ComponentHandle<ComponentType>& handle, ComponentHandle<Args>&...args) {
        auto mgr = getComponentManager<ComponentType>();
        handle = ComponentHandle<ComponentType>(entity, mgr->lookup(entity), mgr);
        unpack<Args...>(entity, args...);
    }

    template <typename ComponentType>
    void unpack(Entity entity, ComponentHandle<ComponentType>& handle) {
        auto mgr = getComponentManager<ComponentType>();
        handle = ComponentHandle<ComponentType>(entity, mgr->lookup(entity), mgr);
    }
```

I cannot  use the follow.
```cpp
    sol::usertype<World> World_type = lua->new_usertype<World>(
        "World",
        "unpackTransform", &World::unpack<Transform>,
        "unpack", &World::unpack<Transform, Motion>
    );
```
but if I comment the first line, it works fine
```cpp
    sol::usertype<World> World_type = lua->new_usertype<World>(
        "World",
        // "unpackTransform", &World::unpack<Transform>,
        "unpack", &World::unpack<Transform, Motion>
    );
```

What's the problem?

**Comment by ThePhD** [comment]
It's ambiguous to have `&World::unpack<Transform>`, because BOTH the first function declaration and the second function declaration cannot work. A better implementation that saves you some shenanigans is:

```cpp
    template <typename ComponentType, typename ... Args>
    void unpack(Entity entity, ComponentHandle<ComponentType>& handle, ComponentHandle<Args>&...args) {
        auto mgr = getComponentManager<ComponentType>();
        handle = ComponentHandle<ComponentType>(entity, mgr->lookup(entity), mgr);
        if constexpr (sizeof...(Args) > 0) {
            unpack<Args...>(entity, args...);
        }
    }
```

**Comment by zeroxer** [comment]
Thanks. It works now.

**Comment by RDSM243** [comment]
Hello i'm trying to implement two template functions, but i'm having a few problems with sol::overload.
`lua.new_usertype<Entity>("Entity", "HasComponent", &Entity::HasComponent<Transform2D>, 
    "GetComponent", sol::overload(&Entity::GetComponent<Transform2D>, &Entity::GetComponent<BoxCollider2D>, &Entity::GetComponent<Sprite>));
    `

My hasComponent is working only when i'm looking for transform component, when i try to use sol::overload and pass other component types i have this error(and the getComponent is not working by the same problem): 
`sol: no matching function call takes this number of arguments and the specified types`

Here is my template functions:
`       template<typename T>
        bool HasComponent() const{
            return componentTypeMap.count(&typeid(T));
        }

        template<typename T>
        T* GetComponent(){
            //Verifying if the requested component exists
            if (HasComponent<T>()){
                return static_cast<T*>(componentTypeMap[&typeid(T)]);
            }
            std::cerr << "Can't find a component in the entity " << name << std::endl;
            return NULL;
        }`
