### ISSUE TITLE
Can't resume coroutine in C++

### ISSUE THREAD

**Issue by ringxiaou** [ThePhD/sol2#981]
The second coroutine cannot be resumed.

	struct waittime
	{
		float pass;
		float time;

		bool update(float elapsedtime)
		{
			pass += elapsedtime;
			if (pass > time) {
				return true;
			}
		}
	};

	waittime timer;

	sol::state lua;
	lua.open_libraries(sol::lib::base, sol::lib::coroutine);

	lua["Wait"] = sol::yielding([&timer](float waittime)
		{
			timer.pass = 0;
			timer.time = waittime;
		});

	sol::string_view code = R"(
			local Thread = coroutine.wrap(
					function()
						print("before")
						Wait(5)
						print("after")
					end)
		
			Thread()

			print("end")
		)";

	sol::thread thread = sol::thread::create(lua);
	sol::coroutine coroutine = thread.state().load(code);

	coroutine();

	while (1)
	{
           // 0.1 is for testing
		if (timer.update(0.1))
		{
			// I want to resume coroutine after 5 seconds
			coroutine();
			break;
		}
	}

The result I want is

before
end
(wait 5 seconds)
after

but, result

before
end
before
end

I know the second "coroutine()" is wrong, 
but I don't know how to resume the second coroutine.

The script is written by the user, and the coroutine name("Thread") is flexible.

**Comment by Rochet2** [comment]
In your code you currently have two coroutines.
One is the whole `code` and another is the `Thread` variable in the lua code.
When you run the lua code by calling `coroutine()`, the inner coroutine is created and executed and it then yields and exists in the middle of execution. Afterwards you print "end".

In your problem description you seem to want to resume the inner coroutine afterwards.
However, the problem in your code seems to be that there is no way to access the `Thread` variable after the function that defines it ends.

To resume the inner coroutine you must provide some access to the `Thread` variable.
Here are some ways to solve the problem:
1. Return the `Thread` at the end of the outer function and use it to resume the inner coroutine later
<details>

```cpp
    sol::string_view code = R"(
		local Thread = coroutine.wrap(
				function()
					print("before")
					Wait(5)
					print("after")
				end)
	
		Thread()

		print("end")
        return Thread
	)";

    sol::thread thread = sol::thread::create(lua);
    sol::coroutine coroutine = thread.state().load(code);

    sol::coroutine Thread = coroutine(); // outer coroutine returns the inner coroutine which has yielded 

    while (1)
    {
        // 0.1 is for testing
        if (timer.update(0.1))
        {
            // I want to resume Thread after 5 seconds
            Thread();
            break;
        }
    }
```

</details>

2. Set `Thread` as a global variable by removing `local` and use it to later resume the coroutine
<details>

    sol::string_view code = R"(
		Thread = coroutine.wrap(
				function()
					print("before")
					Wait(5)
					print("after")
				end)
	
		Thread()

		print("end")
	)";

    sol::thread thread = sol::thread::create(lua);
    sol::coroutine coroutine = thread.state().load(code);

    coroutine();

    while (1)
    {
        // 0.1 is for testing
        if (timer.update(0.1))
        {
            // I want to resume Thread after 5 seconds
            thread.state()["Thread"]();
            break;
        }
    }

</details>

Both of these codes result in the following output that you were after
```
before
end
after
```

**Comment by ringxiaou** [comment]
Thank you very much Rochet2.
We are creating a program that works based on Lua scripts written by users like Roblox.
So we can't change the script like 1 or 2.
I tried to get an internal coroutine from sol::this_state, but couldn't find a way.
I will consider your third solution.
Thanks again for your comment

**Comment by Rochet2** [comment]
Can you not direct the users to program in a specific way? Or are you trying to get some existing codebase to work in a different way?
If you cant direct users, then you can make your original example work if you monkey patch the `coroutine.wrap` function with your own custom variant.

For example here you can see that I did not touch your original lua code, but still the result is what you expected because I replaced the `coroutine.wrap` function to be the `MakeThread` function from the 3rd example. This way any existing user code that follows your original example would work in the way you intended.

```cpp
std::vector<sol::function> threads;
sol::function coroutine_wrap = lua["coroutine"]["wrap"];
 lua["coroutine"]["wrap"] = [&](sol::function f, sol::this_state ts) {
    sol::state_view sv(ts);
    sol::function co = coroutine_wrap(f);
    threads.push_back(co);
    return co;
};

sol::string_view code = R"(
		local Thread = coroutine.wrap(
				function()
					print("before")
					Wait(5)
					print("after")
				end)
	
		Thread()

		print("end")
	)";

sol::thread thread = sol::thread::create(lua);
sol::coroutine coroutine = thread.state().load(code);

coroutine();

while (1)
{
       // 0.1 is for testing
	if (timer.update(0.1))
	{
                // I want to resume Thread after 5 seconds
                for (auto e : threads)
                    e();
		break;
	}
}
```

**Comment by ThePhD** [comment]
I'm gonna say this one is solved for now. If it's not, ping to re-open or say something!
