### ISSUE TITLE
Loading compiled lua: Truncated precompiled trunk

### ISSUE THREAD

**Issue by petergilmour1987** [ThePhD/sol2#983]
When trying to run a script from a .luac compiled lua file, I get the error `Truncated precompiled trunk`

The code itself is just some simple print statements.

I can't find any information on this error. Does sol have a different method for loading compiled lua?

I have tried with `sol.safescript` and `sol.script`

**Comment by ThePhD** [comment]
What does "from a .luac compiled lua file" mean?

`safe_script` and `script` take the actual contents of the script, directly. `safe_script_file` takes the file itself. Which do you need? What are you looking for?

**Comment by petergilmour1987** [comment]
Sorry, I'll try to explain.....

So, reaidng in char* data from a standard .lua file and running that with safe_script works no problem, of course. But by using luac to compile the lua to bytecode, and reading that in using the same technique, sol gives me the error "Truncated precompiled trunk".

I hope that makes more sense.

**Comment by ThePhD** [comment]
Is it using the same Lua version? What version of Lua is in sol? Some of the load functions in 5.1/5.2 don't behave exactly the same and can't handle compiled files well and sol2 has some emulation, so I need more information to pin it down.

**Comment by petergilmour1987** [comment]
I see, well it's 5.3.5. I don't remember reading anywhere that sol needs 5.2, but I may have missed that. I shall try with 5.2 and let you know.

**Comment by ThePhD** [comment]
It is not required: I am just asking if the `luac` generating the compiled file is the same as the `lua` that you are building with sol3. For example, Linux generally installs Lua 5.1 by default. That binary format is not going to play nice with the Lua 5.3 one if you just do `luac program.lua`. Make sure it matches; that's all I'm trying to point out, not that you need to actually change versions.

**Comment by petergilmour1987** [comment]
Ah good. Well yes, The installed version of lua that I'm compiling with matches the version that I'm using with sol.

**Comment by j-schultz** [comment]
Since you say you are "reading char* data from a file", did you make sure that the file is opened in binary mode? Otherwise some of the binary precompiled data might not be read correctly due to newline conversions.

**Comment by petergilmour1987** [comment]
Absolutely, sorry I forgot to close this. It wasn't quite the reading in binary mode issue but the issue was definitely on my end. Sorry about that!
