### ISSUE TITLE
Removed std::result_of used in sol2 for c++20

### ISSUE THREAD

**Issue by NIKEA-SOFT** [ThePhD/sol2#986]
I am using Visual Studio 19, Clang 10.0 compiler, std::c++20.
I cannot use sol2 in c++20, as the standard no longer supports `std::result_of.`
I replaced it with `std::invoke_result_t`, could you add c++20 support?

**Comment by ThePhD** [comment]
I should almost never be using `result_of`, huh.

I'll get right on this one and the other improvements I'm making, hopefully to be released by tomorrow morning!

**Comment by ThePhD** [comment]
Should be fixed in latest, lemme know if I broke something.
