### ISSUE TITLE
Optimal way to handle custom errors in custom methods

### ISSUE THREAD

**Issue by violinyanev** [ThePhD/sol2#987]
Dear ThePhD,

sol is amazing - we love it!

Not sure if this is a feature request, maybe just a "best practice question". What we do:
- load external Lua scripts
- inject our custom types (usertype) and overload index and new_index
- create custom errors when specific requirements are not met

We were asking ourselves the question - what is the best way to generate a custom error (luaL_error) from inside a C function which is used to overload a metatable operation? We first checked the sol samples of course, , but the only way we found is calling luaL_error() directly. That kind of feels wrong, considerung you provide a C++ API which completely wraps Lua calls in a version-independent way. Is this truly the intended way of having custom errors, or did we fail to find a good example?

Here is an overly simplified example:

```cpp
class MyClass{
  static void NewIndex(sol::this_state s, MyClass& data, const sol::object& index, const sol::object& rhs)
  {
    if(index.is<std::string>())
    {
        // This is directly calling Lua - is there a sol wrapper for it?
        luaL_error(s, "Key is string, not cool! Please use integers only");
        return;
    }

    // ... do other cool things
  }
}
```

Supplementary information
- we build on all kinds of compilers - MSVC 2017+, GCC7+, LLVM
- We use C++17 and the latest sol 3.2.1 (had a good laugh at your VS doin' the derps comment - thumbs up)
- We are not allowed to use exceptions

**Comment by ThePhD** [comment]
Well, you should just toss an exceptio-

> We are not allowed to use exceptions

HooooooooOOOOOOOOOOOOO boy!! How exciting!!!!

Quick break down:
- make a `std::expected` type of your own (excellent ones [here](https://github.com/lamarrr/STX) and [here](https://github.com/TartanLlama/expected))
- Override [the customization points (link)](https://sol2.readthedocs.io/en/latest/tutorial/customization.html) to give the behavior of calling `luaL_error` when the type inside is not the right result with whatever error message you want to

Caveats: if the type inside the returned `std::expected` needs to be destroyed, you must handle lifetime closure since `lua_error` and friends to `longjmp` to escape things. This means calling the destructor manually.

**Comment by violinyanev** [comment]
Thanks for the quick and accurate reply!
Question though... We are talking about std::string, i.e. built-in type, **not** a custom one. The custom type (in the example above - _Class_) is the one which carries the overloaded metatable method which expect specific built-in types. Does your answer imply we have to customize std::string in this case?

On a general note (and in order to make this ticket useful for someone else who stumbles over the same problem and unlike us wants to do type checks for real custom types, not built in ones) - where would you need to call the destructor manually? Inside "sol_lua_check" in case the stack types are not what we expect in the custom type, i.e. when success == false at the end of sol_lua_check? Do we still need to call lua_error or is that being orchestrated by sol outside of the specialized sol functions?

**Comment by ThePhD** [comment]
```cpp
class MyClass {
     using expected_t = my_return_expected<void, std::runtime_error>;
   static NewIndex(sol::this_state s, MyClass& data, const sol::object& index, const sol::object& rhs)
  {
    if(index.is<std::string>())
    {
        return expected_t(std::runtime_error("Key is string, not cool! Please use integers only"));
    }

    // ... do other cool things
  }
}
```

Then you implement a customization point for `my_return_expected`, check if it's either the result (`void`) or the error (`std::runtime_error`). If it's the latter, you then (in the `sol_lua_push` customization point in particular) save the string value by pushing it onto the stack with `sol::stack::push( state, the_expected.error().what() );` and then call the destructor with `my_expected.~my_return_expected<...>();` and then call `lua_error(state);`. `lua_error` without the `L` in front of `error` means "Use the last thing on the stack as the object for the error".

And that's the rundown. Best of luck!
