### ISSUE TITLE
Error consistency

### ISSUE THREAD

**Issue by Leadwerks** [ThePhD/sol2#989]
I have VSCode set up to work with Lua and it's amazing. Feels like a real language.

I am having some trouble parsing sol error messages. Most error messages have a format like this:
```
sol: runtime error: [string "c:\(...)\Leadwerks\Projects\Ultra Project\Scripts\main.lua"]:17: attempt to call global 'amera' (a nil value)
stack traceback:
	[string "c:\(...)\Leadwerks\Projects\Ultra Project\Scripts\main.lua"]:17: in main chunk
```
But some have a format like this:
```
sol: runtime error: stack index 1, expected userdata, received sol.sol::detail::unique_usertype<UltraEngine::World>: value is a userdata but is not the correct unique usertype (bad argument into 'std::shared_ptr<UltraEngine::Camera>(std::shared_ptr<UltraEngine::Entity>)')
stack traceback:
	[C]: in function 'Camera'
	[string "c:\(...)\Leadwerks\Projects\Ultra Project\Scripts\main.lua"]:17: in main chunk

```
And I found another version:
```
[sol3] An error occurred and has been passed to an error handler: sol: syntax error: [string "c:\(...)\Leadwerks\Projects\Ultra Project\Script..."]:15: '=' expected near 't'
sol: syntax error: [string "c:\(...)\Leadwerks\Projects\Ultra Project\Script..."]:15: '=' expected near 't'
```

Consequently, it is difficult for me to parse the error, open the correct file, and display an error message.

**Comment by Leadwerks** [comment]
I am also having trouble with file paths being truncated to 64 bytes. I set LUA_IDSIZE to 2048 in my Lua DLL but it seems to make no difference.

**Comment by Leadwerks** [comment]
It appears that syntax errors truncate the filename and runtime errors do not.

**Comment by ThePhD** [comment]
For the "filename" issue, this is the "chunkname" parameter in sol2. It exists outside of Lua. I didn't even know `LUA_IDSIZE` existed. I use 64 because it's a modest buffer size, but I can always make it larger.

**Comment by Leadwerks** [comment]
MAX_INFO_STRING?

**Comment by Leadwerks** [comment]
This is how I am running scripts. I don't know where the file path is being truncated:
```
		sol::protected_function_result solresult;
		try
		{
			solresult = VirtualMachine::lua->safe_script(source, s);
		}
```

**Comment by Leadwerks** [comment]
I can't figure out why, but I am still getting errors that look like this:
```
"sol: syntax error: [string \"c:\\Users\\Name\\Documents\\Leadwerks\\Projects\\Ultra Project\\Script...\"]:18: function arguments expected near 'sed'"
```

**Comment by Leadwerks** [comment]
It says SOL_ID_SIZE_ is 512.

**Comment by Leadwerks** [comment]
An error like this results gives the full correct file path:
```
local framebuffer = Creat eFramebuffer(window);
```
An error like this gives a truncated (useless) file path:
```
while window:Clos ed() == false do
```

**Comment by ThePhD** [comment]
It looks like the `traceback` function of `luaL_traceback` is doing automatic truncation of the "chunk name" description string, semi-outside of my control. It looks like you will need to manually implement your own `traceback` handler, similar to the one that exists in sol2, to get more consistent handling of the behavior: https://github.com/ThePhD/sol2/blob/e256012de1b7ac03b54bce9d09f6e17a2c1ad100/include/sol/state_handling.hpp#L76

Either that, or I could rip the `luaL_traceback` function open and force some different behaviors...

**Comment by Leadwerks** [comment]
I don't understand, I set LUA_IDSIZE to 2048 in the Lua source code. Shouldn't that be sufficient to avoid the problem?

**Comment by ThePhD** [comment]
`traceback` behaves differently and probably has special rules for how it truncates things to provide the traceback, probably. So you'd need to build a better traceback. (Or I would.)

**Comment by Leadwerks** [comment]
These guys seem to have dealt with this problem:
https://forums.civfanatics.com/threads/how-to-restore-runtime-error-reports-for-your-lua-code.485607/

**Comment by Leadwerks** [comment]
I tried just printing the traceback in Lua and it works fine this way:
```
Print(debug.traceback())
```
The full path is printed.

**Comment by Leadwerks** [comment]
I GOT IT!

You know, I had a vague memory of there being another value that had to be modified, from years back.

In llex.c at line 75:
```
#define MAXSRC          80
```
Just change that to a bigger value (preferably the same one you have LUA_IDSIZE set to) and the truncation goes away.

There may be other issues in the error format, but I am going to close this topic.
