### ISSUE TITLE
Windows compile errors

### ISSUE THREAD

**Issue by EToreo** [ThePhD/sol2#99]
I am compiling cross platform and on windows I am getting these errors (single file):

> sol.hpp(3870): error C2062: type 'void' unexpected
> sol.hpp(3870): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
> sol.hpp(3877): error C2039: 'cast': is not a member of 'sol::detail::inheritance<void>' 
> sol.hpp(3877): error C2065: 'cast': undeclared identifier
> sol.hpp(7355): warning C4003: not enough actual parameters for macro 'max'
> sol.hpp(9308): error C2589: '(': illegal token on right side of '::'
> sol.hpp(9308): error C2059: syntax error: '::'

Am I missing a compiler flag or is there something more core going on here?

**Comment by ThePhD** [comment]
I haven't updated the single file... unless you've just done it yourself. In which case, no idea what's going on, since I dev in Windows (VS 2015) and it's been working okay! Time to take a look...

**Comment by ThePhD** [comment]
Can you shoe me what's around that line? I'm just seeing an `ifdef`.

Could very well be a `windows.h` problem, seeing from that" not enough actual parameters for macro max... windows is the only platform to make `max` a macro...

**Comment by EToreo** [comment]
Shoot, I just left the office and won't be near a computer for the next 4 hours. Stay tuned.

**Comment by EToreo** [comment]
I'm compiling this through a node addon.  If you don't know, node addons generate a VS project file and uses it to compile.  A binding.gyp file is used to do this.

Here is  a snip from my binding.gyp file:
```json
    "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "../lua/src",
        "./"
      ],
      "cflags_cc": [
        "-I ../lua/src",
        "-I ./",
        "-fexceptions",
        "-std=c++14",
        "-Wl,--no-as-needed",
      ]
```

Here are the line snips you asked for from the single sol.h file.  It was downloaded from your releases area (v2.5.8).

Line 3870 starts:
```cpp
    static void* cast(void* voiddata, std::size_t ti) {
        T* data = static_cast<T*>(voiddata);
        return static_cast<void*>(ti != id_for<T>::value ? type_cast(types<Bases...>(), data, ti) : data);
    }
```

Line 3877: `using inheritance_cast_function = decltype(&inheritance<void>::cast);`

Line 7355: `va_iterator() : L(nullptr), index(std::numeric_limits<int>::max()), stacktop(std::numeric_limits<int>::max()) {}`

Line 9308: 
```cpp
    protected_function_result invoke(types<>, std::index_sequence<>, std::ptrdiff_t n) {
        int stacksize = lua_gettop( lua_state() );
--->    int firstreturn = std::max( 1, stacksize - static_cast<int>( n ) );
        luacall(n, LUA_MULTRET);
        int poststacksize = lua_gettop(lua_state());
        int returncount = poststacksize - (firstreturn - 1);
        return protected_function_result( lua_state( ), firstreturn, returncount, returncount, status() );
    }
```

**Comment by ThePhD** [comment]
This... definitely looks like problem introduced by `windows.h`. We include `<numeric_limits>` and `<algorithm>`

**Comment by EToreo** [comment]
My src files that include `sol.h` also include `windows.h`.  Is that the source of the conflict?  I don't have a choice in the matter, so I might be stuck.  Is there a resolution to this problem?

**Comment by nabijaczleweli** [comment]
`(std::max)(blerb)` but `#undef`ing those shit macros might be a better idea.

**Comment by EToreo** [comment]
Thanks guys. I got around this by making sure to include `windows.h` after including `sol.h`.  I'm starting to really dislike windows C++ development.

**Comment by nabijaczleweli** [comment]
@EToreo `#define`ing `NOMINMAX` might do the trick, too

**Comment by thinlizzy** [comment]
you can also define WIN32_LEAN_AND_MEAN
http://stackoverflow.com/questions/11040133/what-does-defining-win32-lean-and-mean-exclude-exactly

**Comment by ThePhD** [comment]
I've went through and windows-proofed most of the code (except maybe the errors related to "cast"). But I'm also working on a big refactor, so it won't appear for a little bit...
