### ISSUE TITLE
Build broken with SOL_USE_BOOST

### ISSUE THREAD

**Issue by otristan** [ThePhD/sol2#990]
Hi,
I just have updated sol and I now get some build issue when using SOL_USE_BOOST that disappears when not defining it.

sol.hpp:12776:14: No viable conversion from returned value of type 'const std::__1::nullopt_t' to function return type 'boost::optional<std::__1::basic_string_view<char, std::__1::char_traits<char> > >'

I suppose it should check boost::none when SOL_USE_BOOST is defined

Thanks !

**Comment by ThePhD** [comment]
Oh. Damn. I needed to use `nullopt` specifically there to avoid another error...

Guess it's time to get creative!!

**Comment by otristan** [comment]
For what it worth, I may no longer need myself SOL_USE_BOOST

I used to require it for SOL_UNORDERED_MAP_COMPATIBLE_HASH
but it looks like this is something that doesn't exists anymore
The goal was to avoid allocation thanks to compatible hash key support in boost::unordered_map
Looks like you have rewritten everything related to this.

**Comment by ThePhD** [comment]
Oh, yeah.

I've changed the structure entirely; we don't need the hash map for that anymore.
