### ISSUE TITLE
How to return c++ classes to LUA in a table ? 

### ISSUE THREAD

**Issue by fxfire** [ThePhD/sol2#993]
I'm feeling stupid just for asking, but after reading through the whole docu twice and literally going through all example files in the repo, I cannot find out if I can return a c++ class to lua and have the class members/variables shown with corrent names instead of just seeing a 'userdata' in lua. 

In c++ I have a vector filled with instances of my user class and I want that to be available in LUA, so as simple example I'm basically doing thit:
```
struct Beer {
   int alc = 2;
   std::string name = "yamyam";
}

static std::vector<Beer> someBeers;
someBeers.push_back(Beer())
someBeers.push_back(Beer())

sol::table FunctionCalledFromLuaAndReturnsATable(sol::this_state ts){
      
   sol::state_view lua = ts;
   sol::table obj_table = lua.create_table();
   int count = 0;
  for (auto& beer : someBeers){
    obj_table[i] = &beer;  // Obviously I could build a sub-table here with how I want it to look.
    count++;
  }
  return obj_table;
}
```

Now in LUA I'm obviously seeing this, when 'printing' the table:
```
{
  [0] = <userdata 1>,
  [1] = <userdata 2>
}
```
Is there any way to actually make it show the class member names instead of just 'userdata', without me having to build this table structure manually in c++, so that it looks like this:
```
{
  [0] = {
             alc = 2,
             name = "yamyam",
          },
  [1] = ...
}
```

I've tried it with lua.new_usertype<Beer> but afaik that is not for this purpose....or what am I missing 🤔 ?

Thanks in adv. for a short slap on my head to point me into the right direction 😄

**Comment by ThePhD** [comment]
If you just want visual representation, add a `sol::meta::tostring` argument to your class.

If you want to actually have it be a table, do yet another `create_table` for each userdata and serialize it explicitly.

**Comment by ThePhD** [comment]
(Yes, that means you need to do it explicitly. I have no magic to-table serialization; in fact, I don't think it's possible for me to do that generically.)

**Comment by fxfire** [comment]
First, thanks for the fast response. 
That would have been the golden magical cherry ontop of this pack of awesomeness :)
Working with Lua tables was/is more of a convenient way to skip any documentation of classes&member vars, but the tostring meta_function, I think I can work with that.

Thanks again for the response Mr Derpstorm !

**Comment by fxfire** [comment]
Reopening is always fun ;)

After a few more hours playing with it, I have one last question.
When I defined a new_usertype<T> and set some members and a metamethod that overrides the to_string, is there any way I can get a 'list' of the already defined member keys ? (so that I don't have to write the same keys twice for every class I define...)

Like:
```
auto fileEntry_type = lua.new_usertype<FileEntry>("FileEntry",sol::constructors<FileEntry>());
	// Members
	fileEntry_type[VdStrA("id")] = sol::readonly(&FileEntry::_id);
	fileEntry_type[VdStrA("name")] = &FileEntry::fileName;

        fileEntry_type[sol::meta_function::to_string] = [&]() { return I'd Like To Create A List Of Available Members Here };
```


<3

**Comment by ThePhD** [comment]
Unfortunately, not in any meaningful way yet. That's a feature that I'm trying to crank out.

**Comment by ThePhD** [comment]
(In #1005)
