### ISSUE TITLE
When building SOL2 under /permissive-mode on MSVC, it failed due to error C2440

### ISSUE THREAD

**Issue by QuellaZhang** [ThePhD/sol2#996]
When we trying to build SOL2 under /permissive- mode, we found error C2440: 'initializing': cannot convert from 'sol::load_result' to 'sol::basic_protected_function<sol::reference,false,sol::reference>', this issue can be reproduced on latest commit 7be51ebbef6719b6a99bdd7315acbb3ebe1b4c6c, I provided preprocessed file and build log. Can you help look? Thanks.

**repro steps:**

1. open VS2019 x86 tools command
2. mkdir F:\gitP\ThePhD\sol2\build_x86 && pushd F:\gitP\ThePhD\sol2\build_x86
3. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DSOL2_LUA_VERSION=5.3.5 -DSOL2_CI=ON -DSOL2_BUILD_LUA=ON -DBUILD_LUA_AS_DLL=ON -DSOL2_TESTS=ON -DSOL2_EXAMPLES=ON -DSOL2_TESTS_EXAMPLES=ON ..
4. set _CL_=/permissive-
5. cmake --build . --config Release --verbose -- /maxcpucount

preprocessed file: [dump.i.txt](https://github.com/ThePhD/sol2/files/4964419/dump.i.txt)
build log: [build.log](https://github.com/ThePhD/sol2/files/4964416/build.log)

**error info**
F:\gitP\ThePhD\sol2\examples\source\dump.cpp(27): error C2440: 'initializing': cannot convert from 'sol::load_result' to 'sol::basic_protected_function<sol::reference,false,sol::reference>'
F:\gitP\ThePhD\sol2\examples\source\dump.cpp(27): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

**Comment by ThePhD** [comment]
This should no longer be the case.

**Comment by QuellaZhang** [comment]
Hi @ThePhD , this issue still can be reproduced on latest code version b8aa189e3253fe661bb2d2d90b56fafb2659f20a.
